### ISSUE TITLE
how to only get context prompt

### ISSUE THREAD

**Issue by leadscloud** [jerryjliu/llama_index#1006]
怎么直接得到上下文信息，而不是直接请求openai.com

how to only get reqeust context prompt  messages, i don't need it to reqeust openai.com

**Comment by jerryjliu** [comment]
@leadscloud could you clarify what you'd like to do? 

If you want the raw prompt templates, you can find the default ones here: https://github.com/jerryjliu/llama_index/blob/main/gpt_index/prompts/default_prompts.py

If you would like to pass through queries through a "fake" model to predict token usage, you can use our token predictor:
https://gpt-index.readthedocs.io/en/latest/how_to/analysis/cost_analysis.html

If you would like to log prompts that are being used during LLM calls, you can take a look at the LlamaLogger (see use case here): https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo.ipynb

for more questions like these please consult the discord
