### ISSUE TITLE
[Feature Request] Enable Streaming for ChatGPT Models

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [jerryjliu/llama_index#1007]
Would it be possible to enable streaming for ChatGPT models?
Langchain does have support, but it seems the mechanism (via callbacks) is different from the current implementation. 

Support for this would go a long way in reducing costs while maintaining that low perceived latency.

**Comment by decent-engineer-decent-datascientist** [comment]
Relevant article: https://blog.langchain.dev/streaming-support-in-langchain/

**Comment by decent-engineer-decent-datascientist** [comment]
Here's a potential approach: https://github.com/hwchase17/langchain/discussions/1706

**Comment by Smyja** [comment]
> Would it be possible to enable streaming for ChatGPT models? Langchain does have support, but it seems the mechanism (via callbacks) is different from the current implementation.
> 
> Support for this would go a long way in reducing costs while maintaining that low perceived latency.

streaming is available already. set `streaming=True`

 https://gpt-index.readthedocs.io/en/latest/reference/response.html#gpt_index.response.schema.StreamingResponse

**Comment by decent-engineer-decent-datascientist** [comment]
There’s an instance check that blocks anything other than the standard OpenAI class from leveraging streaming. Someone just posted another issue with the relevant code block. 

Implementing this will require a signification rework of the response class.

**Comment by Smyja** [comment]
> There’s an instance check that blocks anything other than the standard OpenAI class from leveraging streaming. Someone just posted another issue with the relevant code block. 
> 
> Implementing this will require a signification rework of the response class.

Oh, I get what you mean.

**Comment by jerryjliu** [comment]
Hi @decent-engineer-decent-datascientist @Smyja , we put out an initial PR adding streaming to llamaindex with the callback manager: https://github.com/jerryjliu/llama_index/pull/1059

Tbh it's a bit hacky but would love for you to try it out. The key challenge right now is that we don't have a good way to delineate what the "final" llm generated output is, so that we only stream that instead of all intermediate outputs.

**Comment by nhatquang238** [comment]
@decent-engineer-decent-datascientist did you manage to test this out?

I got it to work but only if the text is shorter than max_input_size. Anything longer ran into this [issue here](https://github.com/jerryjliu/llama_index/pull/1059#issuecomment-1513426030)

For now I'm falling back to just using the callback_manager as part of the llm class directly.

**Comment by decent-engineer-decent-datascientist** [comment]
@jerryjliu looks like langchain reworked their callbacks. this should allow selective stream:
https://python.langchain.com/en/latest/modules/callbacks/getting_started.html#using-multiple-handlers-passing-in-handlers

**Comment by jerryjliu** [comment]
We've fixed streaming! https://github.com/jerryjliu/llama_index/pull/3125

guide here: https://gpt-index.readthedocs.io/en/latest/how_to/customization/streaming.html
