### ISSUE TITLE
Documentation still refers to gpt_index instead of llama_index - 

### ISSUE THREAD

**Issue by ProgramItUp** [jerryjliu/llama_index#1008]
I appreciate the effort that is going into llama_index but please help avoid frustration.

The [main page of the repo](https://github.com/jerryjliu/llama_index), mentions 

2/25/2023: By default, our docs/notebooks/instructions now reference "LlamaIndex" instead of "GPT Index"

Please be more explicit, that the "default" does not mean up-to-date.  Please state that the documentation is out of date, and to translate "gpt-index" to "llama_index"

It is confusing to attempt to debug errors, like #926 when the[ latest version of the docs](https://gpt-index.readthedocs.io/en/latest/index.html ) references to 
`classgpt_index.foo.bar`

Thanks.

**Comment by Disiok** [comment]
Fixed!
