### ISSUE TITLE
How can I implement a custom LLM model LangChain class wrapper for GPT4All model?

### ISSUE THREAD

**Issue by traverse-in-reverse** [jerryjliu/llama_index#1014]
Is it possible to do what described here 
https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model  
or here 
https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html#how-to-write-a-custom-llm-wrapper
whith  https://github.com/nomic-ai/gpt4all model?
I'd appreciate any help / hints!

**Comment by Disiok** [comment]
Looks like it's implemented now: [Langchain GPT4All integration](https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html)
