### ISSUE TITLE
Question: Composability

### ISSUE THREAD

**Issue by Krishnan-9** [jerryjliu/llama_index#1015]
Hello! 

I building a graph composability structure where the nodes are combined as a list index and each node is a vector store themselves. Could you kindly clarify the under-the-hood mechanism when I query this object (eg. compare and contrast between Doc A and Doc B) and how to alter the query config file in this case?

My use case is as follows
I have there docs as vector stores:-
index1 = GPTSimpleVectorIndex.from_documents(doc1)
index2 = GPTSimpleVectorIndex.from_documents(doc2)
index3 = GPTSimpleVectorIndex.from_documents(doc3)

I then created a list index and further transformed it into a graph:-
graph = ComposableGraph.build_from_indices(
    GPTListIndex,
    [index1, index2, index3],
    index_summaries=[index1_summary, index2_summary, index3_summary],
)

My queries involve a mixture of questions such as querying individual docs (eg. summarise doc1), compare/contrast between pairs or triplets, etc

I was just wondering if there are any specific query_config I need to use and how exactly it works to address the above query use cases? 

The current query _config I am using is as follows:-
query_configs = [
    {
        "index_struct_type": "dict",
        "query_mode": "default",
        "query_kwargs": {
            "similarity_top_k": 1,
            # "include_summary": True
        }
    },
    {
        "index_struct_type": "list",
        "query_mode": "default",
        "query_kwargs": {
            "response_mode": "tree_summarize",
        }
    },
]

**Comment by jerryjliu** [comment]
Hi @Krishnan-9, I think we may have addressed this question in the discord as well - but the idea is that certain index structures might be better for certain use cases (e.g. use simple vector index to query individual docs, use a graph structure to compare/contrast between different documents). 

How do you decide which index to use then, given the query? 
- You can define an "overall" graph to "choose" an index: https://github.com/jerryjliu/llama_index/blob/main/examples/composable_indices/QASummaryGraph.ipynb 
- You can define each index as a tool, and pass to a langchain agent 

Closing issue for now, for more questions please followup in the discord
