### ISSUE TITLE
ChatOpenAI: stream is only supported for OpenAI LLMs

### ISSUE THREAD

**Issue by veasion** [jerryjliu/llama_index#1020]
source file: llama_index/llm_predictor/base.py
```
if not isinstance(self._llm, OpenAI):
    raise ValueError("stream is only supported for OpenAI LLMs")
```

ChatOpenAI does not extends OpenAI , this is bug.

**Comment by JamMaster1999** [comment]
I have the same exact problem. I tried using this for both gpt-4 and gpt-3.5-turbo 
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-4"))
Please let us know how to fix and we'll contribute a fix.

**Comment by jerryjliu** [comment]
I have an initial PR here to tackle this using callback managers: https://github.com/jerryjliu/llama_index/pull/1059.

A bit hacky, but may suffice for your use case
