### ISSUE TITLE
AttributeError: type object 'GPTSimpleVectorIndex' has no attribute 'from_documents'

### ISSUE THREAD

**Issue by stoneHah** [jerryjliu/llama_index#1028]
I tried to run a demo, but I encountered some problems. My code is as follows
```
from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex.from_documents(documents)
```
the llama-index version is 0.4.32

**Comment by logan-markewich** [comment]
@stoneHah from_documents was introduced in v0.5.0

You can upgrade llama index `pip install --upgrade llama_index langchain`

**Comment by stoneHah** [comment]
> after "pip install --upgrade llama_index langchain" not work, why??

it's ok

**Comment by stoneHah** [comment]
我一开始pip源是使用了清华的，后台在执行升级命令的时候指定了阿里的，估计清华的没同步版本吧

**Comment by stoneHah** [comment]
> my envs: anaconda，i try python 3.7 3.8 3.9，but it not work，whats your envs？

我一开始pip源是使用了清华的，后台在执行升级命令的时候指定了阿里的，估计清华的没同步版本吧

**Comment by lvjianxin** [comment]
更换阿里云源后一样：pip install --upgrade llama_index langchain -i http://mirrors.aliyun.com/pypi/simple/
更新后版本：llama-index：0.4.32，langchain：0.0.116，仍旧是报AttributeError: type object 'GPTSimpleVectorIndex' has no attribute 'from_documents'
