### ISSUE TITLE
About customized embedding model

### ISSUE THREAD

**Issue by Tavish77** [jerryjliu/llama_index#1029]
I used a customized embedding model, but the display size does not match. What should I do
**There is the erro info:**

> Traceback (most recent call last):
>   File "query_index.py", line 83, in <module>
>     response = index.query(question)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/base.py", line 245, in query
>     return query_runner.query(query_str)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/query_runner.py", line 342, in query
>     return query_combiner.run(query_bundle, level)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/query_combiner/base.py", line 66, in run
>     return self._query_runner.query_transformed(
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/query_runner.py", line 202, in query_transformed
>     return query_obj.query(query_bundle)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
>     f_return_val = f(_self, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/base.py", line 394, in query
>     return self._query(query_bundle)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/base.py", line 380, in _query
>     nodes = self.retrieve(query_bundle)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/base.py", line 250, in retrieve
>     nodes = self._retrieve(query_bundle, similarity_tracker=similarity_tracker)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/vector_store/base.py", line 58, in _retrieve
>     query_result = self._vector_store.query(
>   File "/usr/local/lib/python3.8/site-packages/llama_index/vector_stores/simple.py", line 105, in query
>     top_similarities, top_ids = get_top_k_embeddings(
>   File "/usr/local/lib/python3.8/site-packages/llama_index/indices/query/embedding_utils.py", line 32, in get_top_k_embeddings
>     similarity = similarity_fn(query_embedding, emb)
>   File "/usr/local/lib/python3.8/site-packages/llama_index/embeddings/base.py", line 50, in similarity
>     product = np.dot(embedding1, embedding2)
>   File "<__array_function__ internals>", line 180, in dot
> ValueError: shapes (1536,) and (1024,) not aligned: 1536 (dim 0) != 1024 (dim 0)

**I used the custom model here when generating embedding**

> embed_model = HuggingFaceEmbeddings(model_name="GanymedeNil/text2vec-cmedqq-lert-large")
> 
> embed_model = LangchainEmbedding(embed_model)
> prompt_helper = PromptHelper(max_input_size = max_input_size, num_output = num_outputs, max_chunk_overlap = max_chunk_overlap, embedding_limit=embedding_limit, chunk_size_limit=600, separator=separator)
> service_context = ServiceContext.from_defaults(prompt_helper=prompt_helper, chunk_size_limit=chunk_size_limit,embed_model=embed_model)

**Comment by Tavish77** [comment]
Can I change the output format of the embeddingmodel?

**Comment by logan-markewich** [comment]
@Tavish77 it looks like you have some old embeddings generated by OpenAI

You need to start fresh when switching embedding models so that the vector sizes line up 👍

**Comment by Tavish77** [comment]
@logan-markewich Thank you  i have solved it

**Comment by arjunanand13** [comment]
> @Tavish77 it looks like you have some old embeddings generated by OpenAI
> 
> You need to start fresh when switching embedding models so that the vector sizes line up 👍

You mean new open api key ?
