### ISSUE TITLE
Limiting the prompts

### ISSUE THREAD

**Issue by sawhney17** [jerryjliu/llama_index#1030]
Hi, for a project that I am experimenting with, I've succesfully set up llama_index with the gpt-3.5-turbo model. 

I have noticed that for every query that is made, 4000 tokens are being used. Is there any way to limit this number. it's okay if some degree of accuracy is lost. 

Thanks in advance

**Comment by hongyishi** [comment]
The token usage is because the query uses the full node text for querying. You can reduce the size of the context while still keeping relevant info with SentenceOptimizer.

**Comment by Disiok** [comment]
If you want to reduce the context size, you can also consider using vector store indices, setting a low similarity top k, and setting chunk size to be lower.
