### ISSUE TITLE
ValueError: A single term is larger than the allowed chunk size.

### ISSUE THREAD

**Issue by edengbigabid** [jerryjliu/llama_index#1031]
ValueError: A single term is larger than the allowed chunk size.
Term size: 5613
Chunk size: 3900Effective chunk size: 3900

What does that limitation mean? What is the chunk size?

**Comment by hongyishi** [comment]
Looks like the default chunking isn't working correctly to shrink the size of your input data. Do you have an example of the data to share? You can also try using SentenceSplitter.

**Comment by edengbigabid** [comment]
I'm sorry. I cannot share the data.
I removed all csv and xlsx files and it worked so I guess it's because of some big file.
I will check with SentenceSplitter and update the results.
Thanks.
