### ISSUE TITLE
documentation link to langchain LLM page 404s

### ISSUE THREAD

**Issue by jobooker** [jerryjliu/llama_index#1032]
The doc for [Defining LLMS > Example: Changing the underlying LLM](https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-changing-the-underlying-llm) has the following text with a dead link: 

>  "Note that you may plug in any LLM shown on Langchain’s [LLM](https://langchain.readthedocs.io/en/latest/modules/llms.html) page."

Presumably it means to go here now: https://python.langchain.com/en/latest/modules/models/llms.html

**Comment by jerryjliu** [comment]
thanks, will change!
