### ISSUE TITLE
"ValueError: summary field of the index_struct not set." during Multi-Step Query Transformations

### ISSUE THREAD

**Issue by LLYX** [jerryjliu/llama_index#1044]
I created a ComposableGraph using a GPTTreeIndex on top of a collection of GPTSimpleVectorIndex objects, and I made sure that each individual vector index had its own summary, and that the graph itself also had a summary. Querying it normally seems to work fine, single step query decomposition also works fine, but when I attempt to do multi step query decomposition, I get thrown the error.

```
graph = ComposableGraph.from_indices(GPTTreeIndex, [indices[key] for key in indices], [str(summaries[key]) for key in indices], service_context=service_context)
graph.index_struct.summary = "<my_summary>"
step_decompose_transform = StepDecomposeQueryTransform(llm_predictor_chatgpt, verbose=True)
response = graph.query("<my_query>", query_transform=None, service_context=service_context) # Works
response = graph.query("<my_query>", query_transform=step_decomposable_transform, service_context=service_context) # Throws error
```

llama_index=0.5.6

**Comment by chengyjonathan** [comment]
I'm able to set the summary like:

index.index_struct.summary = "some string"

I'm not sure what purpose this summary has though/ why it's needed.

**Comment by LLYX** [comment]
> I'm able to set the summary like:
> 
> index.index_struct.summary = "some string"
> 
> I'm not sure what purpose this summary has though/ why it's needed.

I set that summary as well, but it doesn't seem to help fix the issue, and I'm not sure which index_struct summary is unset...
