### ISSUE TITLE
Question: Communicate with LLM from web app

### ISSUE THREAD

**Issue by pelyhe** [jerryjliu/llama_index#1050]
Hi!

I used llama_index library to train the gpt-3.5-turbo model with google docs. It is working perfectly from the python code. I want to integrate this to my Flutter web application. Is there any best practice solution I should use? Can I build a rest api which uses a prompt and sends back the response? 
Thanks in advance!

**Comment by Disiok** [comment]
Yes, I think any simple web framework could do. Take a look at https://gpt-index.readthedocs.io/en/latest/guides/tutorials/fullstack_app_guide.html as an example.
