### ISSUE TITLE
This model's maximum context length was exceeded.

### ISSUE THREAD

**Issue by JoshuaeKaiser** [jerryjliu/llama_index#1052]
This model's maximum context length is 4097 tokens, however you requested 4120 tokens (3864 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

The above error occurs only sometimes when I query across my index.

I see that the docs specify that we can control the prompt token count and the completion count. 

What does the community recommend to ensure as much context as passed as possible without killing the size of the index chunks. Should we just chop off the end of the context passed is the query pushes over the max char count ?

My query template bellow.

QA_PROMPT_TMPL = (
    "We have provided context information below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given this information, please answer the following question: {query_str}\n"
    "If you can't awnser the question from the context provided respond with 'I am unable to awnser'"
)

**Comment by Disiok** [comment]
Try setting a lower `chunk_size_limit` in `ServiceContext`

**Comment by AI-Aether** [comment]
> Try setting a lower `chunk_size_limit` in `ServiceContext`

Keeping a chunk_size of even 200 is not helping me get rid of this error.
