### ISSUE TITLE
Issue in GPTTreeIndex tree building

### ISSUE THREAD

**Issue by AnshulP10** [jerryjliu/llama_index#1053]
I am trying to build a GPTTreeIndex from a set of 20 customer support tickets. I have a summaryprompt which has instructions on which aspect to focus on. Unfortunately sometimes I am seeing that the same input tickets are being returned in the root nodes
<img width="638" alt="Screenshot 2023-04-04 at 6 47 13 PM" src="https://user-images.githubusercontent.com/44372786/229806733-b56c39f3-ec89-4bd6-982f-c4481de3c9e0.png">

I can also see that in the tree building phase no LLM tokens are being used to create the tree
<img width="917" alt="image" src="https://user-images.githubusercontent.com/44372786/229805621-5ad60b77-f07a-4774-9276-ce41961c6939.png">

Can you help me in understanding why this is happening

I am using llama_index==0.4.12

**Comment by Disiok** [comment]
Could you try to upgrade to >=0.5.0 and see if the issue still persists?
