### ISSUE TITLE
Command line for llama_index?

### ISSUE THREAD

**Issue by iaalm** [jerryjliu/llama_index#1054]
Hi,
llama_index is exceptionally useful to me as it opens up a plethora of opportunities for private document handling. However, relying solely on Python coding is not the most convenient way. I am contemplating if there is a possibility to develop a command line/shell interface akin to openai-python, incorporating both Python library and command interface. I am unsure if this aligns with llama_index's objectives or if others require this feature too. Hence, I have created an issue here. I am willing to try and implement this function if it is deemed useful by the community.

Some random ideas:
```
# init a repo in current directory. Create index.json, maybe a config file also
llama-index-cmd init

# add file to index
llama-index-cmd add [path to file]

# query, or maybe a REPL way?
llama-index-cmd query "What's llama?"

# query index info
llama-index-cmd info
```

**Comment by jerryjliu** [comment]
that's pretty interesting - i actually haven't thought about this. I'm down to try this as an experimental feature, could go in a folder under gpt_index/experimental for now?

**Comment by iaalm** [comment]
Sounds good!
