### ISSUE TITLE
Chatbot Agent Tools deviates from prompt instruction not staying within index context

### ISSUE THREAD

**Issue by timothymugayi** [jerryjliu/llama_index#1055]
Hi guys, wondering if is it possible to ensure indexes do not deviate from the actual provided context within agent tools 

`index = GPTSimpleVectorIndex.from_documents(documents)`

The above loads an index based on website data, below prompt seems to ensure any questions that deviate from context are not answered. 

```
QQA_PROMPT_TMPL = (
    "We have provided context information below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given this information, please answer only based on context if the question is not part of context do not answer. Instead respond with I don't know: {query_str} also return back the context used as part of the answer\n"
)
QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_TMPL)


print(index.query("Who is the president of france",
                  text_qa_template=QA_PROMPT,
                  response_mode="compact"))
```

This returns 

_**I don't know. Context: title: Reldyn, length: 1215, excerpt: Leverage digital transformation with us for efficient and better customer experience., byline: None, dir: None, lang: en, siteName: None.
.**_

Tried a similar approach using agents and tools where the tools loads up the GPTSimpleVectorIndex based off the same web content as above example, at times it works perfectly. Sometimes it just loses the instruction to keep within the context. Any points to ensure am approaching this correctly would be appreciated. 

```

 prompt = PromptTemplate(
        template="""You are a personal assistant for Reldyn company your job is to answer questions. Use only context Website Index to provide answers.
                    Do not provide any answers that deviate from your tools documents. If you don't know the answer, just say "Hmm, Im not sure." Don't try to make up an answer up.:
                   --------
                   Question: {query}
                  """,
        input_variables=["query"],
    )

tools = [Tool(
    name="Website Index",
    func=lambda q: str(index.query(q)),
    description=f"useful for when you want to answer questions from indexed text. Always, you must try the index first, only answer based on index text",
)]

memory = ConversationBufferMemory(memory_key="chat_history")
agent_chain = initialize_agent(
    tools,
    llm,
    agent="zero-shot-react-description",
    memory=memory,
    verbose=True,
    max_iterations=5,
)

agent_prompt = prompt.format(query=user_input)
response = str(agent_chain.run(agent_prompt)).strip()
```

**Comment by timothymugayi** [comment]
Got this to work by providing more strict instructions to focus on the index context and the tool description. the key seems to be playing around with the prompt and tool description. Being too strict produces more direct responses but also limits the range of answers. This might be good for use cases where you ideally don't want the bot deviating and going off on a tangent

**Comment by Disiok** [comment]
Super interesting investigations. Ya, right now there's not too many great ways to fix hallucination beyond prompt engineering. We hope the future instruction fine-tuned models will be better and better.
