### ISSUE TITLE
How can merge multi index file

### ISSUE THREAD

**Issue by loi-nguyen-khanh** [jerryjliu/llama_index#1063]
Hi,

For example I have 2 folder, folder 1 I use GPTTreeIndex and save to index1.json. And folder 2 I save to index2.json.
So, now I want to load 2 index files. Ho can I do it?

**Comment by Disiok** [comment]
Hey @loi-nguyen-khanh, unfortunately we don't have great support for merging saved index jsons yet. The preferred approach is to simply re-index both folders together.

**Comment by nasirus** [comment]
You can use the GPTListIndex to merge multiple indices. The GPTListIndex takes a list of indices as an argument and merges them into a single index.

```
from llama_index import GPTListIndex

index = GPTListIndex([index1, index2])
```

You can then save and load the merged index as you would any other index.

**Comment by xiaojun2sheng** [comment]
@nasirus  Error reported in this way
`from llama_index import GPTListIndex

index = GPTListIndex([index1, index2])`



<img width="1212" alt="image" src="https://user-images.githubusercontent.com/33241230/231677065-dee4ef7d-6d23-4307-af64-17f55ca31653.png">

**Comment by batou069** [comment]
> You can use the GPTListIndex to merge multiple indices. The GPTListIndex takes a list of indices as an argument and merges them into a single index.
> 
> ```python
> from llama_index import GPTListIndex
> 
> index = GPTListIndex([index1, index2])
> ```
> 
> You can then save and load the merged index as you would any other index.

The part you're missing IMO is building a graph, check out the composability part of the docs!
You build the list and then query the list with something like this:

```
index1_summary = "A client-facing knowledgebase "
index2_summary = "Those are articles from our Confluence Knowledgebase for teams A, B, C, D, E, F and G. Here you can learn about the teams, the product and internal information"
index3_summary = This is a collection of articles with very detailed information about the technical side of X. Very relevant for {employee type Y}"
index4_summary = "A collection of answered questions from multiple company slack chat channels"
(replaced some too specific info with generic stuff)

#Building Graph

all_indices = [index1, index2, index3, index4]
index_summaries=[index1_summary, index2_summary, index3_summary, index4_summary]

graph = ComposableGraph.from_indices(GPTTreeIndex, all_indices, index_summaries=index_summaries)    
graph.save_to_disk("graph.json")
** Querying **

# set query config
query_configs = [
    {
        "index_struct_type": "simple_dict",
        "query_mode": "default",
        "query_kwargs": {
            "similarity_top_k": 3,
            "response_mode": "tree_summarize"
        }
    },
]


response = index.query(text, query_configs=query_configs)
    
print(f"Your questions was {text}: \nThe answer is: {str(response)}")
```

Not sure if summaries are needed when doing list instead of tree, i guess not

**Comment by dxv2k** [comment]
> 

Hi, I check your code but after `graph.save_to_disk`. How do you load it? I don't quite get it.

**Comment by batou069** [comment]
> > 
> 
> Hi, I check your code but after `graph.save_to_disk`. How do you load it? I don't quite get it.

That would be:

`index = ComposableGraph.load_from_disk("graph.json")`

**Comment by Siddharth-1698** [comment]
I want to create a chat engine where multiple index is there:
memory = ChatMemoryBuffer.from_defaults(token_limit=2500)
    timea = time.time()

    collections = UserIndexes.objects.filter(
        user_id=user_id)
    timeb = time.time()
    print("filtering collections", timeb-timea)
    indices = []
    for collection in collections:
        if collection.file_name != "":
            timec = time.time()
            index = get_indexes(collection)
            #.as_query_engine()
            # query_engine_tool = QueryEngineTool(
            #     query_engine=index,
            #     metadata=ToolMetadata(
            #         name=collection.file_name,
            #         description=collection.description
            #     ),
            # )
            indices.append(index)
            timed = time.time()
            print("getting index", timed-timec)
    timee = time.time()
    index = GPTListIndex[indices]
    print("getting all indices", timee-timeb)
    # query_engine = SubQuestionQueryEngine.from_defaults(
    #     query_engine_tools=indices,
    #     service_context=get_service_context(),
    #     use_async=True,
    # )

    return index
It's not working

**Comment by Siddharth-1698** [comment]
These are vectorstore indices

**Comment by Sivaprakasam10d** [comment]
> You can use the GPTListIndex to merge multiple indices. The GPTListIndex takes a list of indices as an argument and merges them into a single index.
> 
> ```python
> from llama_index import GPTListIndex
> 
> index = GPTListIndex([index1, index2])
> ```
> 
> You can then save and load the merged index as you would any other index.


Hey @batou069 
if there are documents with the same content in both **index1** and **index2**, the combined index is include duplicate ?

**Comment by rk-spirinova** [comment]
> @nasirus Error reported in this way `from llama_index import GPTListIndex
> 
> index = GPTListIndex([index1, index2])`
> 
> <img alt="image" width="1212" src="https://user-images.githubusercontent.com/33241230/231677065-dee4ef7d-6d23-4307-af64-17f55ca31653.png">

I am also getting same error.

**Comment by hymanqiu** [comment]
is there any better solution so far?
