### ISSUE TITLE
Returning wrong answer in top level Response

### ISSUE THREAD

**Issue by LLYX** [jerryjliu/llama_index#1065]
During my queries over a tree index, the returned response.response is "The original answer already accurately addresses the question based on the limited context provided. Therefore, no refinement is needed with the new context.", however when I inspect the source nodes, the correct/desired response is present in the first source node. How do I fix this behavior?

**Comment by LLYX** [comment]
> I have also had this issue using a GPTSimpleVectorIndex. For me, this only occurs when I am using HuggingFaceEmbeddings(). When I use the default OpenAI embeddings, I do not have this issue. In both cases, I am using gpt-3.5-turbo as the llm_predictor. My desired behavior is that it would give the answer it finds in the document, or state that it does not know. I was able to change the prompt template to achieve this with default embeddings, but not custom embeddings.

I am currently using the default OpenAI embeddings with this issue, unfortunately, and gpt-3.5-turbo as the llm_predictor. What prompt did you use to fix it with OpenAI?

**Comment by pcvbjr** [comment]
I used the following prompt, with no issue using default embeddings.
"We have provided context information below. \\n"
        "---------------------\\n"
        "{context_str}"
        "\\n---------------------\\n"
        "Your job is to continue the conversation as a chatbot.\n"
        "When asked a question, try to use the context provided to directly answer that question.\n"
        "Given this information, please respond to or answer the question: {query_str}"

I also found I am able to use HuggingFaceEmbeddings() with davinci with no issues, but gpt-3.5-turbo (ChatGPT) gives these issues.

**Comment by Disiok** [comment]
We are working on updating our prompt template to support gpt-3.5-turbo model better
