### ISSUE TITLE
Finding relevant images to a query

### ISSUE THREAD

**Issue by kindler-king** [jerryjliu/llama_index#1069]
Hello,

I am interested in serving images, present in a page along with the query.
Now, using something like PyPdf2 or PdfMiner, I can extract the images present in each page, then match the source nodes of a Query from Llamaindex with text extracted from PdfMiner and serve the images that are present in that page along with the response to the Query I made.
However, there will be a huge problem of speed, in this roundabout solution.

Is there any better way, that we can find relevant images to a node ?  And potentially even serve the relevant images with the RESPONSE to a Query.
Thanks a lot for the help :D

**Comment by Disiok** [comment]
Hey @kindler-king, we definitely want to improve our support for images, right now what we have is pretty basic.

Could you say more about the speed concern? Is it the text extraction from image that is the main bottleneck right now?
