### ISSUE TITLE
Cost of building and querying each index 

### ISSUE THREAD

**Issue by ShubhamVerma16** [jerryjliu/llama_index#1070]
From the document it was clear that we can find the values of last_token_usage
Also it is mentioned cost of building and querying each index is a TODO in reference documentation.

Please help me with the below questions:
1. Any update or estimated time for update on cost of building and querying each index
2. What is the default embedding model used if there is no embedding model specified   
3. I am connecting llama_index to Azure Openai and if the embedding model is not specified, does it incur a cost on the default embedding model

**Comment by logan-markewich** [comment]
Have you tried using the mock LLM and embedding predictors to estimate token usage?

https://gpt-index.readthedocs.io/en/latest/how_to/analysis/cost_analysis.html

**Comment by ShubhamVerma16** [comment]
Thank you for your response. Yes i tried using the mock LLM and embedding predictors to estimate token usage.
I want to understand if embedding model text-ada-002 is used internally and if any cost is incurred in the same.

**Comment by logan-markewich** [comment]
@ShubhamVerma16 yea text-ada-002 is the default embedding model. It's pretty cheap, $0.0004/1k tokens

**Comment by manuel-84** [comment]
the problem is when building index there is no way to get the consumed tokens response from openai, so get_openai_callback.total_tokens and index.service_context.llm_predictor.total_tokens_used are both always 0

**Comment by Disiok** [comment]
Up to date way to get token counting: https://gpt-index.readthedocs.io/en/latest/examples/callbacks/TokenCountingHandler.html
