### ISSUE TITLE
Bugs: StepDecomposeQueryTransform

### ISSUE THREAD

**Issue by chengyjonathan** [jerryjliu/llama_index#1073]
1) In the source code, there's a note that says: `NOTE: doesn't work yet.` Not sure if this is true.
2) When I try to get the source text from this step decompose query, ie:

```
for node in response.source_nodes:
        source_text = node.node.get_text()
```

I get a good response from two different sources. 
BUT only one of the source (the latest one) is recorded.
And I know this is the case, because there's no way the response could've been informed by just the source that's recorded.

**Comment by chengyjonathan** [comment]
To elaborate:

When I iterate over source nodes, it's the same source each iteration.

Even though the response contains info not in the output source nodes.

So it looks like there might be some interaction between StepDecomposeQueryTransform and SourceNodes to be fixed.

**Comment by Disiok** [comment]
Hey @chengyjonathan as noted in the code, this is a very experimental feature, very possible that there's a bug right now. 

Would be amazing if you already have figured out what the bug is and make a PR for it. Happy to help review and land it.
