### ISSUE TITLE
feat(agent): Add functionality for langchain agent with LlamaToolkit to return sources

### ISSUE THREAD

**Issue by ajndkr** [jerryjliu/llama_index#1075]
## Description

I am experimenting with the langchain agent solution provided by `llama-index` using `create_llama_agent` and `LlamaToolkit`. While it provides an easy approach to communicate with my index, the agent only responds back with the string LLM response. The agent should have an optional functionality to return sources as well, similar to [`load_qa_with_sources_chain`](https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html) from langchain.

**Comment by Disiok** [comment]
Yea this would definitely be great to have. Noting it down!
