### ISSUE TITLE
Gpt4all model issue when using llama-index 

### ISSUE THREAD

**Issue by Mohamedballouch** [jerryjliu/llama_index#1080]
```

from langchain.llms.base import LLM
from llama_cpp import Llama
from typing import Optional, List, Mapping, Any
from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex, LLMPredictor, PromptHelper,ServiceContext

class LlamaLLM(LLM):
    model_path: str
    llm: Llama

    @property
    def _llm_type(self) -> str:
        return "llama-cpp-python"

    def __init__(self, model_path: str, **kwargs: Any):
        model_path = model_path
        llm = Llama(model_path=model_path)
        super().__init__(model_path=model_path, llm=llm, **kwargs)

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        response = self.llm(prompt, stop=stop or [])
        return response["choices"][0]["text"]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"model_path": self.model_path}

llm = LlamaLLM(model_path="./gpt4all-converted.bin")
llm_predictor = LLMPredictor(llm=llm)

max_input_size = 7096
num_outputs = 2000
max_chunk_overlap = 20
chunk_size_limit = 600

prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)


service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)


documents = SimpleDirectoryReader('docs').load_data()
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
index.save_to_disk('index.json')
#Query and print response
response = index.query("hello")
print(response
```
Response: (can someone advise me on this issue)
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

File [c:\Users\usr1\Anaconda3\envs\chatgpt1\lib\site-packages\gpt_index\embeddings\openai.py:147](file:///C:/Users/usr1/Anaconda3/envs/chatgpt1/lib/site-packages/gpt_index/embeddings/openai.py:147), in get_embeddings(list_of_text, engine)
    145 list_of_text = [text.replace("\n", " ") for text in list_of_text]
--> 147 data = openai.Embedding.create(input=list_of_text, engine=engine).data
    148 data = sorted(data, key=lambda x: x["index"])  # maintain the same order as input.
    
File [c:\Users\usr1\Anaconda3\envs\chatgpt1\lib\site-packages\openai\api_resources\embedding.py:33](file:///C:/Users/usr1/Anaconda3/envs/chatgpt1/lib/site-packages/openai/api_resources/embedding.py:33), in Embedding.create(cls, *args, **kwargs)
     32 try:
---> 33     response = super().create(*args, **kwargs)
     35     # If a user specifies base64, we'll just return the encoded string.
     36     # This is only for the default case.

File [c:\Users\usr1\Anaconda3\envs\chatgpt1\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py:149](file:///C:/Users/usr1/Anaconda3/envs/chatgpt1/lib/site-packages/openai/api_resources/abstract/engine_api_resource.py:149), in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    127 @classmethod
    128 def create(
    129     cls,
   (...)
    136     **params,
    137 ):
...
--> 326     raise retry_exc from fut.exception()
    328 if self.wait:
    329     sleep = self.wait(retry_state)

RetryError: RetryError[]

**Comment by AntonMallasto** [comment]
This doesn't solve the error you are facing, but you could try the [Langchain GPT4All integration](https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html)

**Comment by logan-markewich** [comment]
@AntonMallasto I had no idea langchain was creating wrappers around specific local llms. Would make integrating the llama index very easy I think

**Comment by Disiok** [comment]
Sweet, no need to reinvent the wheels then, using [Langchain GPT4All integration](https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html) should be the preferred approach.

**Comment by zainabalthafeeri1** [comment]
Regarding this issue i'm trying to use the [Langchain GPT4All integration](https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html) with chromadb as follow
`self.service_context = ServiceContext.from_defaults(llm_predictor=GPT4All(model="./gpt4all-converted.bin", n_ctx=512, n_threads=8),
                                                                embed_model=self.embedding_model)
            self.index = GPTChromaIndex.from_documents(documents,
                                service_context=self.service_context,
                                chroma_collection=chroma_collection)
`
but this error arises `'GPT4All' object has no attribute 'get_llm_metadata'`

**Comment by zainabalthafeeri1** [comment]
hello I'm trying to use gpt4all (langchain integration) alongside llama  and chromadb using the following 
```
self.service_context = ServiceContext.from_defaults(llm_predictor=GPT4All(model="./gpt4all-converted.bin", n_ctx=512, n_threads=8),embed_model=self.embedding_model)
```
```
self.index = GPTChromaIndex.from_documents(documents,
                                service_context=self.service_context,
                                chroma_collection=chroma_collection)
```

but this error arises` 'GPT4All' object has no attribute 'get_llm_metadata'`
