### ISSUE TITLE
Extend query interface in `VectorStore` to be able to perform filtered search

### ISSUE THREAD

**Issue by joein** [jerryjliu/llama_index#1081]
I encountered #969 and found out that there is no convenient interface to perform a filtered search at the moment.

I guess only pinecone has a possibility to search with filters and in a hackish way (for each filter set you need to create a separate instance of `VectorStore`).

I haven't dived deep into the library yet, but maybe it is possible just to extend `VectorStore.query` signature to have `filters` argument or at least add `**kwargs`?

If it could be done without getting into the guts of the library, I could work on a PR

**Comment by Disiok** [comment]
Should be fixed now in latest versions
