### ISSUE TITLE
Why is there a limit on the number of characters returned in the query results?

### ISSUE THREAD

**Issue by xiaojun2sheng** [jerryjliu/llama_index#1083]
Why is there a limit on the number of characters returned in the query results?

**Comment by logan-markewich** [comment]
The limit is from OpenAI, which by default is 256 tokens.

You can change that when creating the llm object 

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

**Comment by tea-artist** [comment]
@logan-markewich 

I did it follow the document, but it still working.

```python
LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", num_output=1800))
```

**Comment by xiaojun2sheng** [comment]
solved my problem, thanks
