### ISSUE TITLE
Question: Build conversation chat with Index query over set of documents

### ISSUE THREAD

**Issue by TahaDouaji** [jerryjliu/llama_index#1086]
Hello there,
I'm trying to do queries on a set of custom documents, using Openai integration

```
documents = SimpleDirectoryReader('data_folder').load_data()
index = GPTSimpleVectorIndex.from_documents(documents) 
```

Here, when sending a Query
`index.query("some question")`
How can we have a conversation chat here, like sending the previous questions?
thanks a lot

**Comment by Disiok** [comment]
Take a look at https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html
