### ISSUE TITLE
How to format the data in text file to train the vector index

### ISSUE THREAD

**Issue by swloo618** [jerryjliu/llama_index#1089]
I have a data as below,

curry chicken | $10 | Small
curry chicken | $12 | medium
curry chicken | $18 | large
curry mutton | $18 | medium
curry mutton | $23 |large
stir fried vege | $8 | medium
stir fried vege | $10 | large

I try to create a vector index using GPTSimpleVectorIndex and save it to json file.  When I query the  by passing in prompt "how much you charge for curry chicken, it show me un-train model, can't find the answer.

curry chicken , $10 , Small
curry chicken , $12 , medium
curry chicken , $18 , large
curry mutton , $18 , medium
curry mutton , $23 , large
stir fried vege , $8 , medium
stir fried vege , $10 , large

I try to re-format my data as above and re-create the vector index again.  This time it's show me $23, small.  The response is not correct.  How I can re-format my data before I build the vector index?

below is the code I use to create the vector index

    def createvectorindex(path):
        max_input = 4096
        tokens = 256
        chunk_size = 600
        max_chunk_overlap = 20

        prompt_helper = PromptHelper(max_input, tokens, max_chunk_overlap, chunk_size_limit=chunk_size)

        # def LLM
        predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=tokens))

       # def doc
       docs = SimpleDirectoryReader(path).load_data()
       servicecontext = ServiceContext.from_defaults(llm_predictor=predictor, prompt_helper=prompt_helper)

      # create vector index
      vectorindex = GPTSimpleVectorIndex.from_documents(documents=docs, service_context=servicecontext)

      vectorindex.save_to_disk('vector.json')
      return vectorindex

**Comment by Disiok** [comment]
Hey, is the data table just the 7 rows you noted?

**Comment by swloo618** [comment]
this is just a sample for the question.  My actual rows of data around 200k + rows

**Comment by Disiok** [comment]
vector index might not be the best fit if you have a structured data table. Take a look at https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#queries-over-structured-data
