### ISSUE TITLE
Unable to create GPTListIndex - ValueError: nodes must be a list of Node objects

### ISSUE THREAD

**Issue by athenawisdoms** [jerryjliu/llama_index#1090]
When trying to construct a `GPTListIndex` from a list of `GPTSimpleVectorIndex`, I'm getting the error

> ValueError: nodes must be a list of Node objects

Here's my code that raises this error:

```py
from llama_index import (
    GPTListIndex,
    GPTSimpleVectorIndex,
)

idx_1 = GPTSimpleVectorIndex.load_from_disk("foo.json")
index = GPTListIndex([idx_1])
```

Full trace

```
Traceback (most recent call last):
  File "/home/foo/test.py", line 18, in <module>
    index = GPTListIndex([idx_1])
  File "/home/foo/.local/lib/python3.10/site-packages/llama_index/indices/list/base.py", line 54, in __init__
    super().__init__(
  File "/home/foo/.local/lib/python3.10/site-packages/llama_index/indices/base.py", line 62, in __init__
    raise ValueError("nodes must be a list of Node objects.")
ValueError: nodes must be a list of Node objects.
```

Using `llama-index==0.5.9`

Why is the creation of `GPTListIndex` giving an error?

**Comment by Disiok** [comment]
Hey @athenawisdoms,

we recently change the API for composability. 
```
from llama_index.indices.composability import ComposableGraph

graph = ComposableGraph.build_from_indices(
    GPTListIndex,
    [index1, index2, index3],
    index_summaries=[index1_summary, index2_summary, index3_summary],
)
```

Please see the latest doc for more details: https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/composability.html

**Comment by dcalexchan** [comment]
I am trying to build the index by adding new documents everyday, so my "old_index" will be appending "new_index" everyday I add new documents into it. In this case, I do not want to summarize again my old_index? What is the best practice? My current method will return the same error as OP:

def merge_response(new_response_index):
    old_response_index = GPTSimpleVectorIndex.load_from_disk('response_index.json')
    merged_index = GPTListIndex([old_response_index, new_response_index])
    merged_index.save_to_disk("response_index.json")

    
Thank you.

**Comment by ProgramItUp** [comment]
@Disiok
Where is ComposableGraph.build_from_indices?
I don't see any code to support it.

There is only reference to "build_from_indices" in the repo, and it is in a .md file.
https://github.com/jerryjliu/llama_index/search?q=build_from_indices
