### ISSUE TITLE
Get gpt-3.5-turbo query to respond like ChatGPT website?

### ISSUE THREAD

**Issue by gameveloster** [jerryjliu/llama_index#1091]
I notice that when using `llama-index` with `gpt-3.5-turbo`, the response was very much like a regular human. 

```py
index = GPTSimpleVectorIndex(documents, service_context=service_context)
response = index.query(the_query)
```

Is there a way to configure the query such that the response is similar to what you get on `chat.openai.com/chat`, where the response tends to contain a list of bullet points (but not always)?

**Comment by Smyja** [comment]
> I notice that when using `llama-index` with `gpt-3.5-turbo`, the response was very much like a regular human.
> 
> ```python
> index = GPTSimpleVectorIndex(documents, service_context=service_context)
> response = index.query(the_query)
> ```
> 
> Is there a way to configure the query such that the response is similar to what you get on `chat.openai.com/chat`, where the response tends to contain a list of bullet points (but not always)?

Try to increase your token output.

**Comment by gameveloster** [comment]
@Smyja Which parameter can be used to increase the response output of the query?

**Comment by Smyja** [comment]
> @Smyja Which parameter can be used to increase the response output of the query?

Num output 

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-fine-grained-control-over-all-parameters

**Comment by Disiok** [comment]
Take a look at the FAQ doc if you have further questions! 

https://docs.google.com/document/d/1bLP7301n4w9_GsukIYvEhZXVAvOMWnrxMy089TYisXU/edit#heading=h.7wxuw955edwh
