### ISSUE TITLE
Can i get similarity_top_k in faiss index?

### ISSUE THREAD

**Issue by roujun1115** [jerryjliu/llama_index#1097]
I am using GPTFaissIndex and want to get the top 5 closest matching term to the query. 
Can someone clarify where to set the parameter? i have tried to set in index.query but failed
Code:
```
query = "Who is the author in the book?"
d = 1536
faiss_index = faiss.IndexFlatL2(d)
documents = SimpleDirectoryReader('./test').load_data()
promptHelper = PromptHelper(2000, 512,20)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=promptHelper)
index = GPTFaissIndex.from_documents(documents, faiss_index=faiss_index, service_context=service_context)
result = index.query(
      query_final,
      similarity_top_k=5,
      text_qa_template=prompt,
      mode="embedding",
)
```

**Comment by Disiok** [comment]
It should work, could you post the error message, that could help me debug.

**Comment by roujun1115** [comment]
> It should work, could you post the error message, that could help me debug.

Error:
File ~/.venv/lib/python3.9/site-packages/llama_index/indices/base.py:245, in BaseGPTIndex.query(self, query_str, mode, query_transform, use_async, **query_kwargs)
    231 query_config = QueryConfig(
    232     index_struct_type=self._index_struct.get_type(),
    233     query_mode=mode_enum,
    234     query_kwargs=query_kwargs,
    235 )
    236 query_runner = QueryRunner(
    237     index_struct=self._index_struct,
...
---> 79 node_ids = [self._index_struct.nodes_dict[idx] for idx in query_result.ids]
     80 nodes = self._docstore.get_nodes(node_ids)
     81 query_result.nodes = nodes

KeyError: '-1'

Thanks!

**Comment by KEN-LJQ** [comment]
@roujun1115 @Disiok I found that, if I set `similarity_top_k` and the value is bigger than the documents or nodes numbers,
Like we have only one document and configure `similarity_top_k` to `2`, then the `query_result.ids ` would be `[0, -1]`, but `-1` not exists and cause exception
