### ISSUE TITLE
怎么配置代理能连接到openAI api？WARNING:urllib3.connectionpool:Retrying

### ISSUE THREAD

**Issue by lvjianxin** [jerryjliu/llama_index#1098]
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request'))': /v1....

**Comment by dominicqi** [comment]
you can set https_proxy env

**Comment by Disiok** [comment]
Duplicate of https://github.com/jerryjliu/llama_index/issues/640
