### ISSUE TITLE
How to perform semantic search on GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by athenawisdoms** [jerryjliu/llama_index#1100]
Given a `GPTSimpleVectorIndex`, is it possible to query it as a semantic search, so it returns the relavant text without sending it to the LLM?

The only way to query the index that I am aware of (shown below) will use the LLM.

```py
index = GPTSimpleVectorIndex.load_from_disk("index.json")
response = index.query(query_str)
```

If not possible with `GPTSimpleVectorIndex`, what is the next best way to perform the semantic search?

**Comment by logan-markewich** [comment]
@athenawisdoms you can set `response_mode="no_text"` in the query call, then it will only return the source nodes in `response.source_nodes`

You can also increase how many nodes are retireived by setting something like this in your query `similarity_top_k=3`

**Comment by athenawisdoms** [comment]
Thanks again Logan!

**Comment by NaelsonAccountDrive** [comment]
have a snippets of how make it?
with my code i got this "None"
