### ISSUE TITLE
How to get the usage and other information responded by OpenAI?

### ISSUE THREAD

**Issue by RockerFlower** [jerryjliu/llama_index#1107]
This is the response message from the OpenAI api:

```
{
   "id":"chatcmpl-abc123",
   "object":"chat.completion",
   "created":1677858242,
   "model":"gpt-3.5-turbo-0301",
   "usage":{
      "prompt_tokens":13,
      "completion_tokens":7,
      "total_tokens":20
   },
   "choices":[
      {
         "message":{
            "role":"assistant",
            "content":"\n\nThis is a test!"
         },
         "finish_reason":"stop",
         "index":0
      }
   ]
}
```

Here's the response I get using index.query:

```
{
    "extra_info": null,
    "response": "text",
    "source_nodes": [
        {
            "node": {
                "doc_hash": "42b5f8b6acb0c03e229b6093479990dccf70e77525d9ce869cabea7bc8389460",
                "doc_id": "047322ad-3bc6-49be-a2fb-6a0a710c39fb",
                "embedding": null,
                "extra_info": null,
                "node_info": {
                    "end": 12360,
                    "start": 11744
                },
                "relationships": {
                    "1": "a07a2f85-7735-4648-b78f-a43b66bc38fb",
                    "2": "85320698-eeef-4682-ad22-a1fc4d968807",
                    "3": "729bf224-b65c-4285-94df-7492abf989d1"
                },
                "text":"\ntext\n"
            },
            "score": 0.8182768021866872
        }
    ]
}
```

How can I get the `usage` and other information returned by OpenAI? Compared with the prediction, this really reflects my spending.

**Comment by 23cf00** [comment]
而我却

**Comment by Disiok** [comment]
Hey @RockerFlower Just curious, is the token counter in LLamaIndex not working for you? Is the value obtained through that off?

**Comment by RockerFlower** [comment]
Hi, @Disiok 

Thanks for your reply! 

### My query method:

```
@app.route("/api/query/docs", methods=["POST"])
def queryDocs():
    if request.method == "POST":
        query_text = request.json["query"]

        result = index_docs.query(
            query_text,
            text_qa_template=QA_PROMPT,
            response_mode="tree_summarize",
            similarity_top_k=2,
            mode=QueryMode.EMBEDDING,
            streaming=False,
        )

        response = {
            "result": result,
            "token_used": llm_predictor.last_token_usage, # The actual number returned is 2219.
        }

        return response
```


### Token usage given by llama after my query:

```
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 2219 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 71 tokens
```

### Usage page of OpenAI:

```
gpt-3.5-turbo-0301, 1 request
1,265 prompt + 170 completion = 1,435 tokens

text-embedding-ada-002-v2, 1 request
39 prompt + 0 completion = 39 tokens
```

You can see that there is a big difference in the numbers. I need to record the number of tokens used for each request so that the cost can be calculated.

---

In addition, I searched for content about getting token usage in the langchain documentation. But since I know so little about both Python and llm, I'm not sure if I can implement this myself? Or do I need to wait llama to integrate this functionality?

https://python.langchain.com/en/latest/modules/models/llms/examples/token_usage_tracking.html

**Comment by logan-markewich** [comment]
You can also use our latest token counting callback!

https://gpt-index.readthedocs.io/en/latest/examples/callbacks/TokenCountingHandler.html#token-counting-handler

**Comment by wapiflapi** [comment]
The token counting callback doesn't replace getting the actual values as reported by a remote API.

Especially in cases when using other LLMs, not provided by OpenAI, for which we do not have the tokenizer locally, we would love to get the reported token usage for accounting purposes, rate limitting, etc.

Should we maybe open a new issue to discuss that?

**Comment by spreeni** [comment]
I am having the same issue as @wapiflapi and would say that this option would be desirable.

When using many models from different providers, using the TokenCounter can be very tedious and unfeasible to maintain. Tokenizers will differ between providers, models and are in worst case closed-source and can't be accessed (or require an API-Key to download as is the case with Cohere). Additionally, they might bring a multitude of dependencies into a project.

As Cloud-providers return this information in their API responses, it would be great to read this returned information.
