### ISSUE TITLE
What would be the best way to give the name of document who contains the answer?

### ISSUE THREAD

**Issue by clement-fifty** [jerryjliu/llama_index#1112]
This project is great!

I'm trying to have a bot who can answer based on answers in many PDF files. It would be a huge help if the bot could also say which document the answer is from.

How could I achieve this?

Thanks in advance

**Comment by Smyja** [comment]
> This project is great!
> 
> I'm trying to have a bot who can answer based on answers in many PDF files. It would be a huge help if the bot could also say which document the answer is from.
> 
> How could I achieve this?
> 
> Thanks in advance



> This project is great!
> 
> I'm trying to have a bot who can answer based on answers in many PDF files. It would be a huge help if the bot could also say which document the answer is from.
> 
> How could I achieve this?
> 
> Thanks in advance
Check [this](https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#parsing-the-response)

**Comment by Disiok** [comment]
Thanks @Smyja  for helping out! Exactly as mentioned, you can find references to the source nodes from the response object.
