### ISSUE TITLE
Could we get some better instructions on this...

### ISSUE THREAD

**Issue by Atlas3DSS** [jerryjliu/llama_index#1113]
![image](https://user-images.githubusercontent.com/89653506/230734202-3d28e77a-ccbc-49f2-be1a-7659257e1e8c.png)

I understand that newbs need to "git gud" but clearer followable instructions on the examples would be super helpful. None of them work out of the box and its very difficult as a newb to try and learn while following the examples.

**Comment by Disiok** [comment]
Hey @Atlas3DSS, sorry I'm super sure where you encountered this doc.Are you referring to generating a BEARER token for chatgpt plugin?

**Comment by Atlas3DSS** [comment]
![image](https://user-images.githubusercontent.com/89653506/230740974-179ff216-6a13-47c4-b75e-f49b5d7f6793.png)
I was trying to follow this - like many i am trying to learn how to retrieve and load information into the GPTs.
