### ISSUE TITLE
Question: Is there a way to replace the default chat refine prompt?

### ISSUE THREAD

**Issue by LLYX** [jerryjliu/llama_index#1114]
I wrote a custom refine prompt but when I use ChatGPT, it doesn't seem to be using my custom prompt. 

https://github.com/jerryjliu/llama_index/pull/867

**Comment by logan-markewich** [comment]
Are you using the ChatOpenAI class when defining the LLM?

**Comment by LLYX** [comment]
> Are you using the ChatOpenAI class when defining the LLM?

Yes, I am.

**Comment by logan-markewich** [comment]
And you pass in your prompt like `index.query(..., refine_template=my_refine_template)`

Or are you using a composable graph?

**Comment by LLYX** [comment]
> And you pass in your prompt like `index.query(..., refine_template=my_refine_template)`
> 
> Or are you using a composable graph?

I'm using a composable graph, and I've passed in a query config that looks like

```
    [
        {
            "index_struct_type": "simple_dict",
            "query_mode": "default",
            "query_kwargs": {
                "similarity_top_k": similarity_top_k
            }
        },
        {
            "index_struct_type": "tree",
            "query_mode": "embedding",
            "query_kwargs": {
                "child_branch_factor": child_branch_factor,
                "query_template": BETTER_QUERY_PROMPT,
                "query_template_multiple": BETTER_QUERY_PROMPT_MULTIPLE,
                "text_qa_template": BETTER_TEXT_QA_PROMPT,
                "refine_template": BETTER_REFINE_PROMPT
            }
        }
    ]
```

**Comment by Corona-Throne** [comment]
I have the same question. 
I create the custom refine template following [this tutorial](https://gpt-index.readthedocs.io/en/latest/guides/tutorials/terms_definitions_tutorial.html#improvement-2-refining-better-prompts).
It's working fine in my composable graph, but i build the custom text_qa_template in the same way which isn't working. It also use the default text_qa_template like DEFAULT_TEXT_QA_PROMPT_TMPL in [this link](https://github.com/jerryjliu/llama_index/blob/main/gpt_index/prompts/default_prompts.py)

**Comment by logan-markewich** [comment]
@LLYX don't you also want to pass the text qa and refine templates to the vector index args too?

**Comment by LLYX** [comment]
> @LLYX don't you also want to pass the text qa and refine templates to the vector index args too?

Ah that might be it, I might have misunderstood at which level things worked at, thought you wouldn't need it for embedding search in the vector store since it would pass the found text directly up to the layer above.

**Comment by logan-markewich** [comment]
Yea each layer still uses the templates. The top layer (I'm assuming the tree is the top) decides which vector index to use by reading the summaries of the vector indexes.

Then the response from the LLM is returned from querying the found vector index 👍
