### ISSUE TITLE
Install Is Failing To Find Dependencies 

### ISSUE THREAD

**Issue by dano1066** [jerryjliu/llama_index#1129]
Following the ReadMe Instructions, I have run "pip install llama-index" on windows 10. It seems to be downloading a lot of versions of Llama Index for some reason. Surely I just need the latest but either way, it is dumping out a lot of errors about conflicting dependencies. Anyone know what is going on here?

`ERROR: Cannot install llama-index==0.4.10, llama-index==0.4.11, llama-index==0.4.12, llama-index==0.4.13, llama-index==0.4.14, llama-index==0.4.15, llama-index==0.4.16, llama-index==0.4.17, llama-index==0.4.18, llama-index==0.4.19, llama-index==0.4.20, llama-index==0.4.21, llama-index==0.4.22, llama-index==0.4.22.post1, llama-index==0.4.23, llama-index==0.4.24, llama-index==0.4.25, llama-index==0.4.26, llama-index==0.4.27, llama-index==0.4.28, llama-index==0.4.29, llama-index==0.4.30, llama-index==0.4.31, llama-index==0.4.32, llama-index==0.4.33, llama-index==0.4.34, llama-index==0.4.35, llama-index==0.4.35.post1, llama-index==0.4.36, llama-index==0.4.37, llama-index==0.4.38, llama-index==0.4.39, llama-index==0.4.4.post2, llama-index==0.4.40, llama-index==0.4.5, llama-index==0.4.6, llama-index==0.4.7, llama-index==0.4.8, llama-index==0.4.9, llama-index==0.5.0, llama-index==0.5.1, llama-index==0.5.10, llama-index==0.5.11, llama-index==0.5.12, llama-index==0.5.2, llama-index==0.5.3, llama-index==0.5.4, llama-index==0.5.5, llama-index==0.5.6, llama-index==0.5.7, llama-index==0.5.8 and llama-index==0.5.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    llama-index 0.5.12 depends on langchain>=0.0.123
    llama-index 0.5.11 depends on langchain>=0.0.123
    llama-index 0.5.10 depends on langchain>=0.0.123
    llama-index 0.5.9 depends on openai>=0.26.4
    llama-index 0.5.8 depends on openai>=0.26.4
    llama-index 0.5.7 depends on openai>=0.26.4
    llama-index 0.5.6 depends on openai>=0.26.4
    llama-index 0.5.5 depends on openai>=0.26.4
    llama-index 0.5.4 depends on openai>=0.26.4
    llama-index 0.5.3 depends on openai>=0.26.4
    llama-index 0.5.2 depends on openai>=0.26.4
    llama-index 0.5.1 depends on openai>=0.26.4
    llama-index 0.5.0 depends on openai>=0.26.4
    llama-index 0.4.40 depends on openai>=0.26.4
    llama-index 0.4.39 depends on openai>=0.26.4
    llama-index 0.4.38 depends on openai>=0.26.4
    llama-index 0.4.37 depends on openai>=0.26.4
    llama-index 0.4.36 depends on openai>=0.26.4
    llama-index 0.4.35.post1 depends on openai>=0.26.4
    llama-index 0.4.35 depends on openai>=0.26.4
    llama-index 0.4.34 depends on openai>=0.26.4
    llama-index 0.4.33 depends on openai>=0.26.4
    llama-index 0.4.32 depends on openai>=0.26.4
    llama-index 0.4.31 depends on openai>=0.26.4
    llama-index 0.4.30 depends on openai>=0.26.4
    llama-index 0.4.29 depends on openai>=0.26.4
    llama-index 0.4.28 depends on openai>=0.26.4
    llama-index 0.4.27 depends on openai>=0.26.4
    llama-index 0.4.26 depends on openai>=0.26.4
    llama-index 0.4.25 depends on openai>=0.26.4
    llama-index 0.4.24 depends on openai>=0.26.4
    llama-index 0.4.23 depends on openai>=0.26.4
    llama-index 0.4.22.post1 depends on openai>=0.26.4
    llama-index 0.4.22 depends on openai>=0.26.4
    llama-index 0.4.21 depends on openai>=0.26.4
    llama-index 0.4.20 depends on openai>=0.26.4
    llama-index 0.4.19 depends on openai>=0.26.4
    llama-index 0.4.18 depends on openai>=0.26.4
    llama-index 0.4.17 depends on openai>=0.26.4
    llama-index 0.4.16 depends on openai>=0.26.4
    llama-index 0.4.15 depends on openai>=0.26.4
    llama-index 0.4.14 depends on openai>=0.26.4
    llama-index 0.4.13 depends on openai>=0.26.4
    llama-index 0.4.12 depends on openai>=0.26.4
    llama-index 0.4.11 depends on openai>=0.26.4
    llama-index 0.4.10 depends on openai>=0.26.4
    llama-index 0.4.9 depends on openai>=0.26.4
    llama-index 0.4.8 depends on openai>=0.26.4
    llama-index 0.4.7 depends on openai>=0.26.4
    llama-index 0.4.6 depends on openai>=0.26.4
    llama-index 0.4.5 depends on openai>=0.26.4
    llama-index 0.4.4.post2 depends on openai>=0.26.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict`

**Comment by dano1066** [comment]
I have installed anaconda and was able to get around the issue using this

**Comment by smartrepkostis** [comment]
Just for the record, I was facing the same issue using pip version 20.1.1. I updated to version 23.0.1 and apparently it installed it.

**Comment by DaveMalek** [comment]
can you please help me with this issue (I have the latest version of pip and almost tried everything but still getting the same error when the llama-index installation reaches this point :

  Using cached llama_index-0.4.4.post2.tar.gz (204 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

then I receive this error:

The conflict is caused by:
    llama-index 0.6.8 depends on langchain>=0.0.154
    llama-index 0.6.7 depends on langchain>=0.0.154
    llama-index 0.6.6 depends on langchain>=0.0.154
    llama-index 0.6.5 depends on langchain>=0.0.154
    llama-index 0.6.4 depends on langchain>=0.0.154
    llama-index 0.6.2 depends on langchain>=0.0.154
    llama-index 0.6.1 depends on langchain>=0.0.154
    llama-index 0.6.0 depends on langchain>=0.0.152
    llama-index 0.5.27 depends on langchain==0.0.142
    llama-index 0.5.26 depends on langchain==0.0.142
    llama-index 0.5.25 depends on langchain==0.0.142
    llama-index 0.5.23.post1 depends on langchain==0.0.142
    llama-index 0.5.23 depends on langchain==0.0.142
    llama-index 0.5.22 depends on langchain==0.0.142
    llama-index 0.5.21 depends on langchain==0.0.142
    llama-index 0.5.20 depends on langchain==0.0.142
    llama-index 0.5.19 depends on langchain==0.0.142
    llama-index 0.5.18 depends on langchain==0.0.142
    llama-index 0.5.17.post1 depends on langchain>=0.0.123
    llama-index 0.5.17 depends on langchain>=0.0.123
    llama-index 0.5.16 depends on langchain>=0.0.123
    llama-index 0.5.15 depends on langchain>=0.0.123
    llama-index 0.5.13.post1 depends on langchain>=0.0.123
    llama-index 0.5.13 depends on langchain>=0.0.123
    llama-index 0.5.12 depends on langchain>=0.0.123
    llama-index 0.5.11 depends on langchain>=0.0.123
    llama-index 0.5.10 depends on langchain>=0.0.123
    llama-index 0.5.9 depends on openai>=0.26.4
    llama-index 0.5.8 depends on openai>=0.26.4
    llama-index 0.5.7 depends on openai>=0.26.4
    llama-index 0.5.6 depends on openai>=0.26.4
    llama-index 0.5.5 depends on openai>=0.26.4
    llama-index 0.5.4 depends on openai>=0.26.4
    llama-index 0.5.3 depends on openai>=0.26.4
    llama-index 0.5.2 depends on openai>=0.26.4
    llama-index 0.5.1 depends on openai>=0.26.4
    llama-index 0.5.0 depends on openai>=0.26.4
    llama-index 0.4.40 depends on openai>=0.26.4
    llama-index 0.4.39 depends on openai>=0.26.4
    llama-index 0.4.38 depends on openai>=0.26.4
    llama-index 0.4.37 depends on openai>=0.26.4
    llama-index 0.4.36 depends on openai>=0.26.4
    llama-index 0.4.35.post1 depends on openai>=0.26.4
    llama-index 0.4.35 depends on openai>=0.26.4
    llama-index 0.4.34 depends on openai>=0.26.4
    llama-index 0.4.33 depends on openai>=0.26.4
    llama-index 0.4.32 depends on openai>=0.26.4
    llama-index 0.4.31 depends on openai>=0.26.4
    llama-index 0.4.30 depends on openai>=0.26.4
    llama-index 0.4.29 depends on openai>=0.26.4
    llama-index 0.4.28 depends on openai>=0.26.4
    llama-index 0.4.27 depends on openai>=0.26.4
    llama-index 0.4.26 depends on openai>=0.26.4
    llama-index 0.4.25 depends on openai>=0.26.4
    llama-index 0.4.24 depends on openai>=0.26.4
    llama-index 0.4.23 depends on openai>=0.26.4
    llama-index 0.4.22.post1 depends on openai>=0.26.4
    llama-index 0.4.22 depends on openai>=0.26.4
    llama-index 0.4.21 depends on openai>=0.26.4
    llama-index 0.4.20 depends on openai>=0.26.4
    llama-index 0.4.19 depends on openai>=0.26.4
    llama-index 0.4.18 depends on openai>=0.26.4
    llama-index 0.4.17 depends on openai>=0.26.4
    llama-index 0.4.16 depends on openai>=0.26.4
    llama-index 0.4.15 depends on openai>=0.26.4
    llama-index 0.4.14 depends on openai>=0.26.4
    llama-index 0.4.13 depends on openai>=0.26.4
    llama-index 0.4.12 depends on openai>=0.26.4
    llama-index 0.4.11 depends on openai>=0.26.4
    llama-index 0.4.10 depends on openai>=0.26.4
    llama-index 0.4.9 depends on openai>=0.26.4
    llama-index 0.4.8 depends on openai>=0.26.4
    llama-index 0.4.7 depends on openai>=0.26.4
    llama-index 0.4.6 depends on openai>=0.26.4
    llama-index 0.4.5 depends on openai>=0.26.4
    llama-index 0.4.4.post2 depends on openai>=0.26.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
