### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by ryanshrott** [jerryjliu/llama_index#1133]
I am directly running this example and getting this error:

Code:
https://github.com/jerryjliu/llama_index/blob/main/examples/composable_indices/city_analysis/PineconeDemo-CityAnalysis.ipynb

Error:
query_str = "Tell me more about Boston"
response_chatgpt = graph.query(query_str, query_configs=query_configs, service_context=service_context)

INFO:llama_index.indices.keyword_table.query:> Starting query: Tell me more about Boston
> Starting query: Tell me more about Boston
INFO:llama_index.indices.keyword_table.query:query keywords: ['boston', 'tell']
query keywords: ['boston', 'tell']
INFO:llama_index.indices.keyword_table.query:> Extracted keywords: []
> Extracted keywords: []
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?bf57b57a-62b0-4544-9412-d7c2eb470009)---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[41], line 2
      1 query_str = "Tell me more about Boston"
----> 2 response_chatgpt = graph.query(query_str, query_configs=query_configs, service_context=service_context)

File [c:\Users\Ryan\anaconda3\lib\site-packages\llama_index\indices\composability\graph.py:164](file:///C:/Users/Ryan/anaconda3/lib/site-packages/llama_index/indices/composability/graph.py:164), in ComposableGraph.query(self, query_str, query_configs, query_transform, service_context)
    154 service_context = service_context or self._service_context
    155 query_runner = QueryRunner(
    156     index_struct=self._index_struct,
    157     service_context=service_context,
   (...)
    162     recursive=True,
    163 )
--> 164 return query_runner.query(query_str)

File [c:\Users\Ryan\anaconda3\lib\site-packages\llama_index\indices\query\query_runner.py:349](file:///C:/Users/Ryan/anaconda3/lib/site-packages/llama_index/indices/query/query_runner.py:349), in QueryRunner.query(self, query_str_or_bundle, index_id, level)
    331 """Run query.
    332 
    333 NOTE: Relies on mutual recursion between
   (...)
    344     composable graph.
    345 """
    346 query_combiner, query_bundle = self._prepare_query_objects(
    347     query_str_or_bundle, index_id=index_id
    348 )
--> 349 return query_combiner.run(query_bundle, level)

File [c:\Users\Ryan\anaconda3\lib\site-packages\llama_index\indices\query\query_combiner\base.py:66](file:///C:/Users/Ryan/anaconda3/lib/site-packages/llama_index/indices/query/query_combiner/base.py:66), in SingleQueryCombiner.run(self, query_bundle, level)
     64 """Run query combiner."""
     65 updated_query_bundle = self._prepare_update(query_bundle)
---> 66 return self._query_runner.query_transformed(
     67     updated_query_bundle, self._index_struct, level=level
     68 )

File [c:\Users\Ryan\anaconda3\lib\site-packages\llama_index\indices\query\query_runner.py:204](file:///C:/Users/Ryan/anaconda3/lib/site-packages/llama_index/indices/query/query_runner.py:204), in QueryRunner.query_transformed(self, query_bundle, index_struct, level)
    202         nodes_for_synthesis.append(node_with_score)
    203         additional_source_nodes.extend(source_nodes)
--> 204     response = query_obj.synthesize(
    205         query_bundle, nodes_for_synthesis, additional_source_nodes
    206     )
    207     return response
    208 else:

File [c:\Users\Ryan\anaconda3\lib\site-packages\llama_index\indices\query\base.py:340](file:///C:/Users/Ryan/anaconda3/lib/site-packages/llama_index/indices/query/base.py:340), in BaseGPTIndexQuery.synthesize(self, query_bundle, nodes, additional_source_nodes)
    332 self._prepare_response_builder(
    333     self.response_builder,
    334     query_bundle,
    335     nodes,
    336     additional_source_nodes=additional_source_nodes,
    337 )
    339 if self._response_mode != ResponseMode.NO_TEXT:
--> 340     response_str = self._give_response_for_nodes(
    341         self.response_builder, query_bundle.query_str
    342     )
...
    107 ) // num_chunks
    108 if padding is not None:
    109     result -= padding

ZeroDivisionError: integer division or modulo by zero

**Comment by Disiok** [comment]
Thanks for reporting this @ryanshrott, will take a deeper look very soon!

**Comment by ryanshrott** [comment]
> Thanks for reporting this @ryanshrott, will take a deeper look very soon!

no problem. If you run any of those city demos, you'll see this error when running graph.query.

**Comment by Disiok** [comment]
Hey @ryanshrott, wasn't able to reproduce this. Which version are you on?

**Comment by ryanshrott** [comment]
@Disiok hmm, I was using the latest builds at the time. I will double check soon and get back to you with my exact version

**Comment by rl3250** [comment]
getting same error.... can anyone help with this?

**Comment by yoeldk** [comment]
I also got the same error when building a composable graph over my indices.
My version is 0.5.27

**Comment by kstrempel** [comment]
I get the same now in this colab notebook. 

https://colab.research.google.com/drive/1qBTIjPimo7kRMg8taEA3xDqDJb1QEY_1?usp=sharing
