### ISSUE TITLE
question about summary

### ISSUE THREAD

**Issue by TomShenTom** [jerryjliu/llama_index#1136]
Why is it necessary to build a graph for multi-document question answering, and why does the graph require a summary for each document? Automatic summarization does not produce good enough results, while manual summarization is impractical for a large number of documents. Are there any other methods for multi-document question answering besides building a graph?

**Comment by logan-markewich** [comment]
I would try using a data agent with a tool for each index

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
