### ISSUE TITLE
HowUsing a Custom LLM Model 

### ISSUE THREAD

**Issue by rjc7011855** [jerryjliu/llama_index#1137]

**Comment by Disiok** [comment]
Hey, could you let me know which version of the library is this on? Just trying to see if we can reproduce.

**Comment by khorevnikita** [comment]
> Hey, could you let me know which version of the library is this on? Just trying to see if we can reproduce.

Hi! 
I have the same issue.

Version: 0.5.16

This is the code example:
`
    
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=config.TEMPERATURE, model_name=config.MODEL))
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

    index = GPTSimpleVectorIndex.load_from_disk(config.INDEX_FILE, service_context=service_context)

    response = index.query(question)
`

conf:

```
TEMPERATURE = 0

MODEL = "gpt-3.5-turbo"

INDEX_FILE = "index.json"
```

Also, i tried text-davinci-003

**Comment by Race428** [comment]
Also same issue

**Comment by logan-markewich** [comment]
This is no longer an issue due to changes in how storage works

https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/usage_pattern.html#optional-save-the-index-for-future-use
