### ISSUE TITLE
Not able to choose model 

### ISSUE THREAD

**Issue by gezgblack** [jerryjliu/llama_index#1140]
I'm trying to create the index using the `gpt-3.5-turbo` model but despite selecting it via LLMPredictor, my useage shows that I'm using other models. What could be the cause? Can I possibly force it to use `gpt-3.5-turbo`?

`# define LLM
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=512))

prompt_helper = PromptHelper(4096, 512, 20, chunk_size_limit=600)

service_context = ServiceContext.from_defaults(
  llm_predictor=llm_predictor, prompt_helper=prompt_helper
  )

JSONReader = download_loader("JSONReader")

loader = JSONReader()
documents = loader.load_data(Path('./data.json'))
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)`

![image](https://user-images.githubusercontent.com/7914065/231141414-fa18f3cd-69a0-4c0b-b2cf-128487b4910b.png)

**Comment by Disiok** [comment]
There's 2 type of LLM usage, embedding vs. completion API. Here is showing the embedding API usage for creating the embeddings for the simple vector index.

**Comment by Disiok** [comment]
When you call `index.query`, that's when the completion API tokens would be incurred.

**Comment by gezgblack** [comment]
That's is indeed correct! Thank you for the clarification. Closing.
