### ISSUE TITLE
Indexing and query response time

### ISSUE THREAD

**Issue by rajache-affine** [jerryjliu/llama_index#1141]
We built a QnA bot based on llama index. We tried with both Keyword Rake and Tree index. When we use Tree index, the indexing time is high if we keep on adding more documents, but we feel that the quality response is good. But if we use RAKE index, the indexing time is less but the response quality is not upto the mark. 

How we can improve, the indexing and response time in Tree index? Please suggest best practices for using these indices.

When we get delete option for tree index? if you have built any sample code build delete index functionality using tree index, please share.

**Comment by Disiok** [comment]
Hey @rajache-affine, what kind of questions are you asking your QA bot? Different indices are optimized for different use-cases. One idea is to leverage our composable graph framework and build a tree index on top of (tree index, vector store index), this will allow automatic routing depending on the query.

**Comment by logan-markewich** [comment]
An example plus links to other notebooks can be found on this page:
https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/composability.html
