### ISSUE TITLE
GPTIndex for custom tagging

### ISSUE THREAD

**Issue by Mrs-Hudson** [jerryjliu/llama_index#1142]
Hi
I want to use GPTIndex for custom tagging using an ontology of size ~ 40K. The ontology just contains names and no metadata (very short documents)

 Example:
"Your job is to help clients accumulate their wealth  and assist  them with any other concerns" and we want to tag  this sentence with nodes from the ontology as such:
"Your job is to help clients [accumulate their wealth]_wealth_creation and [assist  them]_customer_service with any other concerns" (where Wealth Creation and Customer service are the relevant tags. 

I attempted this with the GPT Vector index but face the following issues:
1. All tags are not from the ontology (GPT makes up it own tags)
2. Even with a [STOP] token specified in the LLM instantiation, the response continues beyond the [STOP] token
3. Certain phrases are not tagged at all (true negatives). 

Any advice on which index is best for this usecase would be super helpful!

**Comment by Mrs-Hudson** [comment]
Hi, what does the discord tag mean? Should I join the discord channel and discuss this there?

**Comment by logan-markewich** [comment]
I think a pydantic program might work well here. Just pass in each batch of text, define your tags object class, and off you go

https://gpt-index.readthedocs.io/en/latest/examples/output_parsing/openai_pydantic_program.html
