### ISSUE TITLE
build_from_indices out of date?

### ISSUE THREAD

**Issue by gezgblack** [jerryjliu/llama_index#1144]
Trying to use build_from_indices as outlined in the example [here](https://github.com/jerryjliu/llama_index/blob/66db86d2e875fb47384a77a0469bc6c6f45c866e/docs/how_to/index_structs/composability.md) but getting the error:
`AttributeError: type object 'ComposableGraph' has no attribute 'build_from_indices'`

**Comment by logan-markewich** [comment]
@gezgblack I think there is a typo there, try the method `from_indices(..)` instead

**Comment by Disiok** [comment]
Fixed the typo! https://github.com/jerryjliu/llama_index/pull/1150

**Comment by gezgblack** [comment]
Thank you
