### ISSUE TITLE
Not getting an answer

### ISSUE THREAD

**Issue by BoccheseGiacomo** [jerryjliu/llama_index#1145]
`
from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader
import openai
import os

os.environ['OPENAI_API_KEY'] = 'sk-xxxxx' # my api key
documents=SimpleDirectoryReader('data').load_data()
index=GPTSimpleVectorIndex.from_documents(documents)

response=index.query('what is a cat?')
print(response)
`

This is the basic code to get an answer, and should work, but in the response i only get some runtime messages and not the answer:

INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 5 tokens

and the value of the variable response is None

why? thank you

**Comment by arpitsr** [comment]
Are you sure there is data in the data directory ?
`documents=SimpleDirectoryReader('data').load_data()`

**Comment by BoccheseGiacomo** [comment]
I solved thank you. I thought "data" was a built-in example data folder, but it wasn't so.
Thanks
