### ISSUE TITLE
Merge two or more SimpleVectorIndex json files

### ISSUE THREAD

**Issue by ProgramItUp** [jerryjliu/llama_index#1148]
Is it possible to merge two or more saved SimpleVectorIndex json files?

Very similar to this:

[https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-advanced-building-indices-on-top-of-other-indices](https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-advanced-building-indices-on-top-of-other-indices
)
```
from llama_index import GPTSimpleVectorIndex, GPTListIndex

index1 = GPTSimpleVectorIndex.from_documents(documents1)
index2 = GPTSimpleVectorIndex.from_documents(documents2)

# Set summary text
# you can set the summary manually, or you can
# generate the summary itself using LlamaIndex
index1.set_text("summary1")
index2.set_text("summary2")

index3 = GPTListIndex([index1, index2])

#Throws error : ValueError: nodes must be a list of Node objects.
```

**Comment by xiaojun2sheng** [comment]
@ProgramItUp 
How to use the index collection to search, the code is as follows, I need to query the document content in the two json vectors

**Comment by Disiok** [comment]
Ah, looks like the docs there has some outdated documentations. Will fix.

**Comment by ProgramItUp** [comment]
@Disiok,
Any updates to correct the documentation to show how the new APIs can be used are greatly appreciated.
Thanks.

**Comment by rapsli** [comment]
me too...

**Comment by ProgramItUp** [comment]
@Disiok Can we update the docs so that the example works?
Is there an example somewhere?
Thanks

**Comment by ProgramItUp** [comment]
Hi @jerryjliu 
Any chance of getting the sample code updated? 
https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-advanced-building-indices-on-top-of-other-indices
Thanks

**Comment by LGDoor** [comment]
Dig out the underlying calls in `index.query()` function and merge them by myself:

```python
def multiple_index_query(
        vector_index_list,
        query_str,
        mode = QueryMode.DEFAULT,
        query_transform = None,
        use_async = False,
        **query_kwargs,
    ):
    mode_enum = QueryMode(mode)
    node_candidates = []
    for index in vector_index_list:
        index._preprocess_query(mode_enum, query_kwargs)
        query_config = QueryConfig(
            index_struct_type=index._index_struct.get_type(),
            query_mode=mode_enum,
            query_kwargs=query_kwargs,
        )
        query_runner = QueryRunner(
            index_struct=index._index_struct,
            service_context=index._service_context,
            query_context={index._index_struct.index_id: index.query_context},
            docstore=index._docstore,
            query_configs=[query_config],
            query_transform=query_transform,
            recursive=False,
            use_async=use_async,
        )
        query_combiner, query_bundle = query_runner._prepare_query_objects(query_str)
        query_bundle = query_combiner._prepare_update(query_bundle)
        query_obj = query_runner._get_query_obj(query_combiner._index_struct)
        nodes = query_obj.retrieve(query_bundle)
        node_candidates.extend(nodes)
    node_candidates.sort(key=lambda node: node.score)
    node_candidates = node_candidates[-TOP_K:]
    response = query_obj.synthesize(query_bundle, node_candidates)
    return response
```
Then call it with the original parameters:
```
response = multiple_index_query(
    vector_index_list,
    query, 
    service_context=service_context,
    similarity_top_k=TOP_K,
    mode='embedding',
    response_mode='compact'
)
return str(response)
```

**Comment by cschwarz007** [comment]
It seems the query mechanism has changes in the current release (0.6.11)...?
And I still do not find a way to combine multiple SimpleVectorIndices into one which I then can use for similarity search...
Anyone has any ideas / solutions?
