### ISSUE TITLE
Log/view openai API Request/Response

### ISSUE THREAD

**Issue by gladiatorksk** [jerryjliu/llama_index#1149]
Hi There,

Is there a way to log openai api request and response? 

I am using llamaindex by creating index based on pdf files. I wan to see what is being sent to openai api. 

Thank You.

**Comment by logan-markewich** [comment]
@gladiatorksk  You can try setting the logs to debug to print to terminal
```


import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
```

Or you can use the llama logger (see the bottom of this notebook)
https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo.ipynb

**Comment by gladiatorksk** [comment]
Awesome!  Thanks!

The following did the trick, the debug logger does not provide the api request/response.

`service_context.llama_logger.get_logs()`

**Comment by mintisan** [comment]
Yes, Just `print(service_context.llama_logger.get_logs())`...
