### ISSUE TITLE
How to access document information from AgentExecutor ChatAgent

### ISSUE THREAD

**Issue by GillesJ** [jerryjliu/llama_index#1152]
I want to display the retrieved documents/nodes in a RetrievalQA Chatbot. I am using the setup described in the SEC Chatbot tutorial here: https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb

How do I access the Response objects that are normally returned when running the `query()` on an Index object in this set up?

I looked in the Configuration object documentation of all the components that go into the AgentChain, but I couldn't find the option or callback mechanism to retrieve the actual document or index node information in either kwargs for Index, Query, IndexTool, Toolkit, or Chain config. Below is a reproduction of the configuration and run() code.

What is the canonical Llama_index approach to displaying the retrieved document/node information in the chain output?

```
from langchain.agents import Tool
from langchain.chains.conversation.memory import ConversationBufferMemory
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent

from gpt_index.langchain_helpers.agents import LlamaToolkit, create_llama_chat_agent, IndexToolConfig, GraphToolConfig
# define a decompose transform
from gpt_index.indices.query.query_transform.base import DecomposeQueryTransform
decompose_transform = DecomposeQueryTransform(
    llm_predictor, verbose=True
)

# define query configs for graph 
query_configs = [
    {
        "index_struct_type": "simple_dict",
        "query_mode": "default",
        "query_kwargs": {
            "similarity_top_k": 1,
            # "include_summary": True
        },
        "query_transform": decompose_transform
    },
    {
        "index_struct_type": "list",
        "query_mode": "default",
        "query_kwargs": {
            "response_mode": "tree_summarize",
            "verbose": True
        }
    },
]
# define toolkit
index_configs = []
for y in range(2019, 2023):
    tool_config = IndexToolConfig(
        index=index_set[y], 
        name=f"Vector Index {y}",
        description=f"useful for when you want to answer queries about the {y} SEC 10-K for Uber",
        index_query_kwargs={"similarity_top_k": 3},
        tool_kwargs={"return_direct": True}
    )
    index_configs.append(tool_config)
    
# graph config
graph_config = GraphToolConfig(
    graph=graph,
    name=f"Graph Index",
    description="useful for when you want to answer queries that require analyzing multiple SEC 10-K documents for Uber.",
    query_configs=query_configs,
    tool_kwargs={"return_direct": True}
)

toolkit = LlamaToolkit(
    index_configs=index_configs,
    graph_configs=[graph_config]
)
memory = ConversationBufferMemory(memory_key="chat_history")
llm=OpenAI(temperature=0)
agent_chain = create_llama_chat_agent(
    toolkit,
    llm,
    memory=memory,
    verbose=True
)
agent_chain.run(input="hi, i am bob")
```

**Comment by logan-markewich** [comment]
@GillesJ I think you'll need to use a the lower level functions from langchain rather than the wrappers from llama index.

For each tool/index, you can set the func to be a wrapper function that calls query on your index and does whatever you need with the response object 💪

See this demo (it uses a lambda for the func, but you can replace this with your wrapper function): https://github.com/jerryjliu/llama_index/blob/main/examples/langchain_demo/LangchainDemo.ipynb

**Comment by cyberandy** [comment]
This is an important issue as it will allow to display sources. Can you explain more? Is it possible to use the func also when using the GraphToolConfig()? Thanks in advance.

**Comment by logan-markewich** [comment]
@cyberandy tbh, using this langchain setup is a little deprecated and unmaintained.

I recommend using a data agent or chat engine

Each response has a `.sources` attribute containing the output of each tool. If the tool was a query engine, then you can access the raw output object

```
agent_response.sources[0].raw_output.source_nodes  # get query engine sources
str(agent_respoonse.sources[0])  # get tool output
```

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/root.html
