### ISSUE TITLE
Documentation Example for GPTSimpleVectorIndex broken

### ISSUE THREAD

**Issue by DylanAlloy** [jerryjliu/llama_index#1155]
https://github.com/jerryjliu/llama_index/blob/main/examples/langchain_demo/LangchainDemo.ipynb

``` python
import os
from llama_index import GPTSimpleVectorIndex

# load index
!echo $(pwd)
print(os.path.abspath('../vector_indices/index_simple.json'))
index = GPTSimpleVectorIndex.load_from_disk(os.path.abspath('../vector_indices/index_simple.json'))
```

my script here is a small implementation that demonstrates the issue with sanity checks for working directory...

>   File /opt/conda/lib/python3.10/site-packages/llama_index/vector_stores/registry.py:52, in load_vector_store_from_dict(vector_store_dict, type_to_cls, **kwargs)
>        46 def load_vector_store_from_dict(
>        47     vector_store_dict: Dict[str, Any],
>        48     type_to_cls: Optional[Dict[VectorStoreType, Type[VectorStore]]] = None,
>        49     **kwargs: Any,
>        50 ) -> VectorStore:
>        51     type_to_cls = type_to_cls or VECTOR_STORE_TYPE_TO_VECTOR_STORE_CLASS
>   ---> 52     type = vector_store_dict[TYPE_KEY]
>        53     config_dict: Dict[str, Any] = vector_store_dict[DATA_KEY]
>        55     # Inject kwargs into data dict.
>        56     # This allows us to explicitly pass in unserializable objects
>        57     # like the vector store client.
>   
>   KeyError: '\_\_type\_\_'

**Comment by DylanAlloy** [comment]
In the future it would be neat if there was testing or something so that when you rename & publish the package not everything breaks.

**Comment by Disiok** [comment]
Hey @DylanAlloy, thanks for catching this bug. Should just be the serialized JSON being outdated in the repo. Will update.

**Comment by DylanAlloy** [comment]
I was wondering if this was the case. If I were to store data from a pdf for example myself using the new dict format this should resolve the issue?

**Comment by Disiok** [comment]
Yes, it should work. Let me know if otherwise!

**Comment by mfelat** [comment]
hello, I'm getting this error with my app only when I run it on streamlit cloud and couldn't resolve it, can you help me what can I do:

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.





2023-04-17 23:08:01.114 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script

    exec(code, module.__dict__)

  File "/app/chat6529/6529GPT.py", line 99, in <module>

    st.session_state.response_text, st.session_state.similarity_score = process_question(query)

  File "/app/chat6529/6529GPT.py", line 54, in process_question

    index = GPTSimpleVectorIndex.load_from_disk(input_index)

  File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 364, in load_from_disk

    return cls.load_from_string(file_contents, **kwargs)

  File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 340, in load_from_string

    return cls.load_from_dict(result_dict, **kwargs)

  File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 260, in load_from_dict

    vector_store = load_vector_store_from_dict(

  File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/vector_stores/registry.py", line 52, in load_vector_store_from_dict

    type = vector_store_dict[TYPE_KEY]

KeyError: '__type__'

**Comment by Disiok** [comment]
Hey @mfelat, apologies we recently changed how the vector store data is stored on disk. It would be best to simply re-ingest your data.
