### ISSUE TITLE
ImportError: cannot import name 'VectorIndexDocument' from 'llama_index'

### ISSUE THREAD

**Issue by Karthikeya2302** [jerryjliu/llama_index#1159]
I am experiencing with the llama_index package. Specifically, I am encountering an ImportError when trying to import the VectorIndexDocument module. The error message reads: "ImportError: cannot import name 'VectorIndexDocument' from 'llama_index'".

I have tried several solutions, including checking that all required dependencies are installed, uninstalling and reinstalling the llama_index package, and verifying that the package is installed in the correct Python environment. However, none of these solutions have resolved the issue.

Could you please advise on a potential solution or workaround for this problem? Alternatively, if this is a known issue with the llama_index package, could you please let me know if there is a fix planned for a future release?

Thank you for your time and attention to this matter.

![image](https://user-images.githubusercontent.com/130597328/231550268-9660ca22-e9d5-4bc8-94b5-0af0fcc1cbbd.png)

**Comment by Disiok** [comment]
Hey @Karthikeya2302 , `VectorIndexDocument` is not a module we have.

**Comment by Disiok** [comment]
Curious where you got this from? Please take a look at https://gpt-index.readthedocs.io/en/latest/ for the modules we support.

**Comment by Karthikeya2302** [comment]
> Curious where you got this from? Please take a look at https://gpt-index.readthedocs.io/en/latest/ for the modules we support.

Thank you for your response regarding the VectorIndexDocument module in the llama_index package. I appreciate your help in investigating this issue.
I am trying to develop chatbot using openai api and encountered it here
![image](https://user-images.githubusercontent.com/130597328/231571587-fbf88aac-56d3-4dbe-80b7-e1782228c7c5.png)
please help me out with correction

**Comment by Disiok** [comment]
Where did you get the example code from?

**Comment by Disiok** [comment]
Is this from LangChain?

**Comment by Karthikeya2302** [comment]
![image](https://user-images.githubusercontent.com/130597328/231572571-97c922fd-ee1a-4790-aaf3-6547f85ecdfe.png)
this is the entire code

**Comment by Karthikeya2302** [comment]
> Is this from LangChain?

![image](https://user-images.githubusercontent.com/130597328/231572770-4764eecb-7c12-4d4a-a1f2-97610ec42b70.png)

**Comment by Karthikeya2302** [comment]
> Where did you get the example code from?

please help me out with the correction

**Comment by Disiok** [comment]
Perhaps take a look at https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html for how to build Chatbot.
