### ISSUE TITLE
Choosing a model without the context

### ISSUE THREAD

**Issue by gezgblack** [jerryjliu/llama_index#1165]
Hi folks, I'm trying to choose the model(`gpt-3.5-turbo`) for completion but without persisting context. Currently this is how I am choosing the model that I want to use for my completion:

```
# define LLM
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", max_tokens=512))

# define prompt helper
# set maximum input size
max_input_size = 4096
# set number of output tokens
num_output = 256
# set maximum chunk overlap
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

# Load the GPT index from disk
index = GPTSimpleVectorIndex.load_from_disk('docs.json', service_context=service_context)

while True:
    val = input("Enter your value: ")
    response = index.query(val)
    print(response) 
```

This works well however my context seems to persist. So If I ask question A and then I ask question B, the answer in question B seems to be given based on context from question A as if it's a continuation from the ask that I requested at question A. How can I remove this context persistence? I want every single question that I ask to be an individual question without the context persisting.

If I just remove `service_context=service_context` that seems to remove the persisting context and each question is treated as a new question but then the problem is that I am no longer using the model that I chose myself(`gpt-3.5-turbo`), without that I am using the default `text-davinci` model.

**Comment by Disiok** [comment]
You can pass custom service context for each query like `response = index.query(val, service_context=service_context)`

**Comment by gezgblack** [comment]
@Disiok thanks for the answer. Closing now.
