### ISSUE TITLE
save_to_disk and load_from_disk are not working for GTPSimpleVectorIndex in Azure

### ISSUE THREAD

**Issue by spoot82** [jerryjliu/llama_index#1168]
I am working in Azure with an Azure OpenAI subscription to create an index using the GTPSimpleVectorIndex. 
When I initially create the index, I can easily choose the model deployment (for both llm_predictor & embedding model) from my OpenAI resource, and querying on the index works fine. 
However, I want to be able to save the index such that I can test different GPT parameter settings and see which works best, without having to create a new index every time. 

The method save_to_disk works kind of, since I am able to save the index into json. But when I then load this in, it gives the error "INFO:openai:error_code=DeploymentNotFound error_message='The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.' error_param=None error_type=None message='OpenAI API error received' stream_error=False"
This error does not occur when I use the original index.

**Comment by Disiok** [comment]
Take a look at https://docs.google.com/document/d/1bLP7301n4w9_GsukIYvEhZXVAvOMWnrxMy089TYisXU/edit#
