### ISSUE TITLE
how should I limit the embedding tokens in prompt? INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 3986 tokens INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 51 tokens

### ISSUE THREAD

**Issue by leeleersun** [jerryjliu/llama_index#1170]

**Comment by leeleersun** [comment]
The length of response is always limited around 100. I guess I should limit the LLM token usage

**Comment by mttzzz** [comment]
same problem. Can anyone help?

**Comment by Matiasibarra222** [comment]
do anyone know why de LLM token usage is so big?

**Comment by logan-markewich** [comment]
You can increase the max_tokens of the LLM, the default is 256 for openai

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21
