### ISSUE TITLE
为什么构建索引的时候会使用openai的接口

### ISSUE THREAD

**Issue by xinyue0318343** [jerryjliu/llama_index#1172]
![4a4d8c74582251976990affc6d6bfe3](https://user-images.githubusercontent.com/125643602/231712189-dfa29b29-1269-4c7c-9195-1cc2271a1e37.png)

**Comment by habaneraa** [comment]
因为你用到的 `GPTTreeIndex` 会自动地为每个树节点生成一段 summary 来概括这个子树的内容，这个过程会使用特殊的 prompt 调用 llm_predictor，在不加说明的情况下会默认使用 OpenAI 的 GPT3 作为 LLM 来生成 summary. 可以参考 [Using a custom LLM Model](https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model) 来更换默认 LLM.

**Comment by Disiok** [comment]
@habaneraa  thanks for the help to answer!
