### ISSUE TITLE
Azure - ValueError: nodes must be a list of Node objects. 

### ISSUE THREAD

**Issue by geg00** [jerryjliu/llama_index#1173]
I have few files to load
I'm using Azure 

` 
Windows version
Python 3.11.2 | packaged by conda-forge | (main, Mar 31 2023, 17:45:57) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
`

`
text_files = ['../Files/F0.txt', 
          '../Files/F1.txt',
          '../Files/F2.txt',
          '../Files/F3.txt', 
          '../Files/F4.txt'
          ]
`
`
import openai

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

from gpt_index import ServiceContext

from langchain.embeddings import OpenAIEmbeddings

sc = ServiceContext.from_defaults(embed_model=OpenAIEmbeddings(chunk_size=1))

documents = SimpleDirectoryReader(input_files=text_files).load_data()

index = GPTSimpleVectorIndex.from_documents(documents=documents, service_context=sc)

`

I'm getting the following error

`
Output exceeds the size limit. Open the full output data in a text editor---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 13
     11 sc = ServiceContext.from_defaults(embed_model=OpenAIEmbeddings(chunk_size=1))
     12 documents = SimpleDirectoryReader(input_files=text_files).load_data()
---> 13 index = GPTSimpleVectorIndex.from_documents(documents=documents, service_context=sc)
     14 #index = GPTSimpleVectorIndex.from_documents(documents)
     15 #index  = GPTSimpleVectorIndex.from_documents(documents=documents, service_context=sc)

File c:\Users\AppData\Local\mambaforge\envs\kase-webapp\Lib\site-packages\llama_index\indices\base.py:100, in BaseGPTIndex.from_documents(cls, documents, docstore, service_context, **kwargs)
     96     docstore.set_document_hash(doc.get_doc_id(), doc.get_doc_hash())
     98 nodes = service_context.node_parser.get_nodes_from_documents(documents)
--> 100 return cls(
    101     nodes=nodes,
    102     docstore=docstore,
    103     service_context=service_context,
    104     **kwargs,
    105 )

File c:\Users\AppData\Local\mambaforge\envs\kase-webapp\Lib\site-packages\llama_index\indices\vector_store\vector_indices.py:69, in GPTSimpleVectorIndex.__init__(self, nodes, index_struct, service_context, vector_store, **kwargs)
     60 def __init__(
     61     self,
     62     nodes: Optional[Sequence[Node]] = None,
   (...)
     66     **kwargs: Any,
...
---> 62         raise ValueError("nodes must be a list of Node objects.")
     64 self._service_context = service_context or ServiceContext.from_defaults()
     65 self._docstore = docstore or DocumentStore()

ValueError: nodes must be a list of Node objects.
`

**Comment by Disiok** [comment]
You can probably debug this by printing what the loaded documents look like and see if there's anything abnormal.

**Comment by guangsenw** [comment]
I encountered the same error by following the ChatBot_SEC notebook using gpt-35-turbo. Could it due to the use of Azure OpenAI?

**Comment by logan-markewich** [comment]
Going to close this issue for now, as this issue is quite stale given how far the library has progressed

Feel free to re-open if you still have issues!

Also I will note that we have our own azure support now here

https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html#azure-openai
