### ISSUE TITLE
Defining Summary Text documentation appears to indicate an invalid option

### ISSUE THREAD

**Issue by danielaixer** [jerryjliu/llama_index#1177]
https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/composability.html#defining-summary-text

Where it says
`summary = index1.query(
    "What is a summary of this document?", mode="summarize"
)`

It think it should be:
`summary = index1.query(
    "What is a summary of this document?", response_mode="tree_summarize"
)`

Correct me if I'm wrong, but AFAIK, the "mode" option is invalid for an index query, and "summarize" is not even a valid response mode. I get this error with mode="summarize":
`query_cls = INDEX_STRUT_TYPE_TO_QUERY_MAP[index_struct_type][mode]`
`KeyError: <QueryMode.SUMMARIZE: 'summarize'>`

However, response_mode="tree_summarize" works just fine.

I'm new to Python, gpt and indexing and I didn't want to edit the github file myself in case of messing up something.

**Comment by logan-markewich** [comment]
I think that mode is only for tree indexes. Otherwise, use response_mode (I know, confusing names lol)

**Comment by danielaixer** [comment]
I've been checking the docs...

I understand that I mixed up "mode" (for query mode) and "response_mode", which are different.
