### ISSUE TITLE
Have you considered writing a code loader?

### ISSUE THREAD

**Issue by Minweiwangaaaa** [jerryjliu/llama_index#1186]
I want to import code, but I don't seem to see any code loaders for languages like Python, Java, C++, etc. There is only a general one, but it is not very user-friendly. The results of the vector search are not as expected.

**Comment by Minweiwangaaaa** [comment]
If there are any documents that generate document standard documents, I can process the code myself.

**Comment by jerryjliu** [comment]
this is a great point! would love contributions here to llamahub
