### ISSUE TITLE
Best index to create a good response taking "accurate" prompt

### ISSUE THREAD

**Issue by davidcerezal** [jerryjliu/llama_index#1199]
Having a basic index.json that consists mainly of:

```
{
'Article 55: The basics of legal issues consist of....",
'Article 56: Text B with other numbers...',
'Article 57: Text C with other numbers...'
....
}

```
If I prompt something like 'Article 57':
```
index = GPTSimpleVectorIndex.load_from_disk('testIndex.json')
print(index.query(prompt))
```
Usually, the query mixes the parameters and responds with article 55, since it's more relevant. I have been playing with the 'similarity_top_k' parameter, but the results don't improve too much.

Which index and query method do you recommend for these cases?

**Comment by Disiok** [comment]
You can try using `GPTSimpleKeywordTableIndex` if the query is very keyword based.
