### ISSUE TITLE
GPTQdrantIndex query always returns None when upgrading to 0.5.15

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [jerryjliu/llama_index#1203]
As the title, the GPTQdrantIndex has a weird behavior when querying result. The issue wasn't present in version 0.5.13. I think that is because the qdrant vector integration codes are upgraded in 0.5.15, but causes some bugs.

**Comment by logan-markewich** [comment]
I think this was fixed just yesterday, but not released as a version just yet!

You can try installing directly from source and see if that helps? 🙏

**Comment by ZhaoTzuHsien** [comment]
Ok I will try your suggestion. Besides, I think a better testing can consolidate the stability of the library.

**Comment by Disiok** [comment]
For sure, we are actively improving testing for the library!
