### ISSUE TITLE
Possible to add `memory` to index.query?

### ISSUE THREAD

**Issue by iners-max** [jerryjliu/llama_index#1204]
Per title, I have successfully implement memory in the level of langchain. However, it involves a lot of lines and config. I would like to see if there is any shorthand in the llama_index level to use memory?

**Comment by Disiok** [comment]
Not yet, but working on improving that!

**Comment by logan-markewich** [comment]
It's been added, with chat engines and data agents!

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/root.html

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
