### ISSUE TITLE
Use correct tiktoken encoding based on LLM model

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [jerryjliu/llama_index#1205]
I find that both embedding and LLM predictor using the global tiktoken as their tokenizer and use "gpt-2" for encoding.

https://github.com/jerryjliu/llama_index/blob/468e8443a9c0ba4f36dcf043b169ca9e3a3125bb/gpt_index/utils.py#L50

However, the default model for embbeding is `text-embedding-ada-002` and the LLM predictor is `text-davinci-003`, which uses `cl100k_base` and `p50k_base` encoding respectively. Furthermore, the user may choose their custom LLM model like `gpt-3.5-turbo` or `gpt-4`, and the encoding should also be `cl100k_base`.

Encoding name | OpenAI models
-- | --
`cl100k_base` | `gpt-4`, `gpt-3.5-turbo`, `text-embedding-ada-002`
`p50k_base` | `Codex models`, `text-davinci-002`, `text-davinci-003`
`r50k_base (or gpt2)` | `GPT-3 models like davinci`

For these reasons, I suggest `BaseEmbedding` and `LLMPredictor` should choose correct encoding based on the model used, not using the global immutable one.

If you need some help, I can work on it and make a pull request against it.

Reference
- [Tiktoken cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)

**Comment by Disiok** [comment]
You are absolutely right. This is something we've been wanting to improve on. 
Would be amazing if you could open a PR for it!

**Comment by lihaan** [comment]
It would be great to have this fixed! I assume such a fix will improve the accuracy in calculating whether a long chain of text should be split into two nodes (or kept in a single one) before making HTTP request(s) to the LLM?
