### ISSUE TITLE
Handling documents containing <|endoftext|> is little cumbersome

### ISSUE THREAD

**Issue by xhiroga** [jerryjliu/llama_index#1206]
## Premise

If text conrtains `<|endoftext|>`, indexing will fail.

```python
from llama_index import Document, GPTSimpleVectorIndex

docs = [Document("Hello world!<|endoftext|>")]

index = GPTSimpleVectorIndex.from_documents(docs)

# ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
# If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
# If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
# To disable this check for all special tokens, pass `disallowed_special=()`.
```

## Cause

There are two places where encoding is performed by the Tokenizer, and it is necessary to pass an option to ignore special text in both cases.

- Text splitting inside `node_utils#get_nodes_from_document`
- In `GPTSimpleVectorIndex#from_documents` when instantiating the class, the process of counting the number of tokens to obtain `embedding_results` inside `BaseGPTIndex#build_index_from_nodes`

## Simple workaround

Pass `service_context` as an argument to `GPTSimpleVectorIndex.from_documents()`.

```python
enc = tiktoken.get_encoding("gpt2")
tokenizer = lambda text: enc.encode(text, allowed_special={"<|endoftext|>"})
embed_model = OpenAIEmbedding()
embed_model._tokenizer = tokenizer
node_parser = SimpleNodeParser(text_splitter=TokenTextSplitter(tokenizer=tokenizer))
service_context = ServiceContext.from_defaults(
    embed_model=embed_model, node_parser=node_parser
)

docs = [Document("Hello world!<|endoftext|>")]

index = GPTSimpleVectorIndex.from_documents(docs, service_context=service_context)
```

## Suggested improvements

It might be slightly more readable if the `BaseEmbedding` class can accept a tokenizer as an argument, similar to `TokenTextSplitter`. There might be a more fundamental improvement, but I can't think of any ideas at the moment.

**Comment by MiddleDistances** [comment]
Hi @xhiroga i have been working on this issue for 2 days. 

i was following the Camel-5b tutorial and was unable to resolve the `<|endoftext|>` issue through any obvious means, or refrences in the documentation. My intermediate solution was to force `allowed_special = self.special_tokens_set` in tiktoken core.py.

I still cannot follow the desired protocol for the tutorial, do you mind making a suggestion below for myself and others to follow?  https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/SimpleIndexDemo-Huggingface_stablelm.html

```
hf_predictor = HuggingFaceLLMPredictor(
    max_input_size=2048, 
    max_new_tokens=256,
    temperature=0.25,
    do_sample=False,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="Writer/camel-5b-hf",
    model_name="Writer/camel-5b-hf",
    device_map="auto",
    tokenizer_kwargs={"max_length": 2048},
    # uncomment this if using CUDA to reduce memory usage
    # model_kwargs={"torch_dtype": torch.float16}
)
service_context = ServiceContext.from_defaults(chunk_size=512, llm_predictor=hf_predictor)

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

```

**Comment by JRombouts** [comment]
I also ran into this on 0.9.37.post1 

The original [workaround](https://github.com/run-llama/llama_index/issues/1206#issue-1669661414) above did not work for me.

The following did:

```python
import tiktoken

from llama_index import (
    ServiceContext,
    set_global_service_context,
)
from llama_index.callbacks import CallbackManager, TokenCountingHandler
from llama_index.llms import OpenAI


# Configure the tokenizer to disallow endofprompt
encoder = tiktoken.encoding_for_model("gpt-3")
encode = lambda text: encoder.encode(text, disallowed_special=encoder.special_tokens_set - {'<|endofprompt|>'})
token_counter = TokenCountingHandler(tokenizer=encode)

# Create ServiceContext
llm = OpenAI()
callback_manager = CallbackManager([token_counter])
service_context = ServiceContext.from_defaults(llm=llm, callback_manager=callback_manager)

# Set global default to not have to pass this context everywhere.
set_global_service_context(service_context)

# Now we can use VectorStoreIndex.from_documents(...) where documents contain the '<|endofprompt|>'
...

```

Presumably, one can also pass the encoder to be used directly to a `ServiceContext`, but for my case I want to have the token counting enabled.
