### ISSUE TITLE
The completion could only show 140 words in Chinese

### ISSUE THREAD

**Issue by DeceiverLeblanc** [jerryjliu/llama_index#1209]
When using Chinese, the reply from the chatgpt only shows 140 words. After modifying the output_nums , the problems still occurs. And I also found lots of people occur this problem too in Chinese internet community but no one post the proper way to solve it. After reading the document I still don't know how to fix this problem, could you please have a look? Thanks.

**Comment by logan-markewich** [comment]
OpenAI has a default limit of 256 tokens.

You can increase max_tokens in the OpenAI definition 

Here's the docs page (you might find other features on this page useful for as well!)
https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

**Comment by YankoZang** [comment]
I have also tried max_tokens in the OpenAI definition, but still failed

**Comment by DeceiverLeblanc** [comment]
> I have also tried max_tokens in the OpenAI definition, but still failed

Try to merge two function into one. That's how I solve it.

**Comment by YankoZang** [comment]
> > I have also tried max_tokens in the OpenAI definition, but still failed
> 
> Try to merge two function into one. That's how I solve it.

After appending service_context to function load_from_disk, it solved the issue.

Thanks a lot.

**Comment by Kamiyan89** [comment]
> > > I have also tried max_tokens in the OpenAI definition, but still failed
> > 
> > 
> > Try to merge two function into one. That's how I solve it.
> 
> After appending service_context to function load_from_disk, it solved the issue.
> 
> Thanks a lot.

Hi YankoZang, could you share an example of what do you mean with appending service_conext to function load_from_disk? I am having the same issue and I am complete noob.
I have searched everywhere, tried the Max tokens to no avail.
An example would really help me.
