### ISSUE TITLE
PIP INSTALL...

### ISSUE THREAD

**Issue by ortizalfano** [jerryjliu/llama_index#1211]
Hello, hpew everything goes well! Thank you so much to share your code guys!! I have one question about this file "llama_index/tree/main/examples/data_connectors)/DatabaseReaderDemo.ipynb"

I´m working on this step:

# Initialize DatabaseReader object with the following parameters:

db = DatabaseReader(
    scheme = "postgresql", # Database Scheme
    host = "localhost", # Database Host
    port = "5432", # Database Port
    user = "postgres", # Database User
    password = "FakeExamplePassword", # Database Password
    dbname = "postgres", # Database Name
)
I 
(Obviously, I complete that with my data) but is giving me an error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 db = DatabaseReader(
      2     host="mydata",
      3     user="mydata",
      4     password="mydata",
      5     dbname="mydata",
      6 )

File ~/anaconda3/lib/python3.10/site-packages/llama_index/readers/database.py:71, in DatabaseReader.__init__(self, sql_database, engine, uri, scheme, host, port, user, password, dbname, *args, **kwargs)
     69     self.sql_database = SQLDatabase.from_uri(uri, *args, **kwargs)
     70 else:
---> 71     raise ValueError(
     72         "You must provide either a SQLDatabase, "
     73         "a SQL Alchemy Engine, a valid connection URI, or a valid "
     74         "set of credentials."
     75     )

ValueError: You must provide either a SQLDatabase, a SQL Alchemy Engine, a valid connection URI, or a valid set of credentials.

and my code is exactly what do you have on the path https://github.com/jerryjliu/llama_index/blob/main/examples/data_connectors/DatabaseReaderDemo.ipynb

Well, thank you.. I´m learning sorry if this is a stupid question.

**Comment by logan-markewich** [comment]
I think this should be fixed! Feel free to reopen or reach out on discord if you have further questions

**Comment by Aren196** [comment]
Can I get a solution for the above error

**Comment by ztsweet** [comment]
Use sqlalchemy to solve the problem,
The following is an example of connecting to mysql for reference

`
from sqlalchemy import create_engine
from llama_index.core.utilities.sql_wrapper import SQLDatabase
from urllib import parse
# !pip install pymysql
conn = f"mysql+pymysql://{user}:{parse.quote_plus(password)}@IP:PORT/db_name"
engine = create_engine(conn)
db = DatabaseReader(
    engine=engine
)
`
