### ISSUE TITLE
BaseGPTIndex update and docstore.get_document method not working as expected

### ISSUE THREAD

**Issue by diridiri** [jerryjliu/llama_index#1218]
In llama-index 0.5.16, I guess document inserted cannot be found with docstore.get_document method,
here's simple test code to reproduce an error,

```
from llama_index import GPTSimpleVectorIndex, Document

doc = Document(text="11", doc_id="original_doc_id")
index = GPTSimpleVectorIndex.from_documents([doc])
print (index.docstore.get_document("original_doc_id"))
```

this gives ValueError: doc_id original_doc_id not found. 

And also, update is not working as expected to replace original document in index's docstore, it adds new document with new id.
here's simple test code to reproduce error again,

```
from llama_index import GPTSimpleVectorIndex, Document

document1 = Document(text="11", doc_id="original_doc_id")
index = GPTSimpleVectorIndex.from_documents([document1])

print (index.docstore)
document1.text = "asdf"
index.update(document1)
print ("----------- after doc1 update ----------")
print (index.docstore)
```

this gives 2 documents created in docstore.

Always thanks for your support & maintaining this amazing project!!

**Comment by logan-markewich** [comment]
get_document isn't actually for documents, it's for nodes (I know, the naming needs work still). When a document is inserted it is broken into nodes and the original document is lost.

You can check `index.ref_doc_info` to get a mapping of injested document ids mapped to the node ids that came from that document.
