### ISSUE TITLE
Cannot choose a different model

### ISSUE THREAD

**Issue by cheerlessDreamer** [jerryjliu/llama_index#1219]
I have the following script that builds an index from a bunch of text files and takes a query. I have specified the model to be `gpt-3.5-turbo`. I understand that the embeddings will not be affected by this choice (this shows up in my usage as `text-embedding-ada-002-v2`), but when I look at my usage in the OpenAI platform, I see that completions are still being carried out using the `text-davinci` model. Incidentally, if I pass something deliberately wrong to `model_name` (such as `model_name="blah_blah_blah"`), no error is thrown, the index builds fine, and the query returns a correct answer - this leads me to think that `GPTSimpleVectorIndex` is not looking at `model_name` at all.

```
from llama_index import GPTSimpleVectorIndex, Document, SimpleDirectoryReader
from llama_index import LLMPredictor, GPTSimpleVectorIndex, PromptHelper, ServiceContext
from langchain.llms import OpenAIChat
from dotenv import load_dotenv
import os

load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv('OPENAI_API_KEY')

llm_predictor = LLMPredictor(llm=OpenAIChat(temperature=0.2, model_name="gpt-3.5-turbo"))
max_input_size = 4096
num_output = 256
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
documents = SimpleDirectoryReader('data').load_data()

index = GPTSimpleVectorIndex.from_documents(
    documents, service_context=service_context
)

index.save_to_disk('index.json')
index = GPTSimpleVectorIndex.load_from_disk('index.json')

print(index.query("What are these documents about?"))
```

Any help is greatly appreciated. I've been hitting my head against a wall all weekend…

**Comment by brenoferraz** [comment]
I am new to python and github so I am not sure if I should create a new topic for that but I am also having the same issue, did you manage to fix it?

**Comment by cheerlessDreamer** [comment]
I did manage to fix it! It's pretty simple, actually - one needs to pass to service context to the query:
`print(index.query("What are these documents about?", service_context=service_context))`
