### ISSUE TITLE
Loading index from disk works really slow for me

### ISSUE THREAD

**Issue by daxeel** [jerryjliu/llama_index#1221]
Here is how my program works

1. I have built 2 indices with GPTSimpleVectorIndex from almost 300 website pages content and 1 csv data
2. Then saved 2 indices in the disk
3. Built graph with List index and make queries

When I create fresh indices in google collab, it tasks around 7-10 seconds, but when I load indices from disk in the same google collab, it tasks 20+ seconds.

Am I doing something incorrectly?

Let me know how to improve the speed.

This is how I am constructing a composable graph

`graph = ComposableGraph.from_indices(
    GPTListIndex,
    [website_index, faq_csv_index],
    index_summaries=["website index", "faq index"],
)

query_configs = [
    {
        "index_struct_type": "simple_dict",
        "query_mode": "default",
        "query_kwargs": {
            "similarity_top_k": 1,
            # "include_summary": True
        }
    },
    {
        "index_struct_type": "list",
        "query_mode": "default",
        "query_kwargs": {
            "response_mode": "default"
        }
    },
]`

**Comment by logan-markewich** [comment]
There's no way to improve the speed from disk, but you do have quite a few documents. I recommend looking at a qdrant or weaviate integration 👍🏻
