### ISSUE TITLE
`GPTQdrantIndex` is returning None

### ISSUE THREAD

**Issue by estebanpdl** [jerryjliu/llama_index#1223]
I am using `llama-index==0.5.15`.

When running Paul Graham's example, it seems `GPTQdrantIndex` is not processing documents correctly. Although, OpenAI charged tokens. 

```
# text file is located in test-data
documents = SimpleDirectoryReader('./test-data').load_data()
index = GPTQdrantIndex.from_documents(documents, client=client, collection_name="paul_graham")

# save index to disk
index.save_to_disk("./test-response/index_qdrant.json")

response = index.query("What happened with microcomputers?")
print (response)
```

**Output**

```
INFO:httpx:HTTP Request: GET https://e952af18-199d-4eee-9662-9513ab96f3be.us-east-1-0.aws.cloud.qdrant.io:6333/collections/paul_graham "HTTP/2 200 OK"
INFO:httpx:HTTP Request: PUT https://e952af18-199d-4eee-9662-9513ab96f3be.us-east-1-0.aws.cloud.qdrant.io:6333/collections/paul_graham/points?wait=true "HTTP/2 200 OK"
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 17609 tokens
INFO:httpx:HTTP Request: POST https://e952af18-199d-4eee-9662-9513ab96f3be.us-east-1-0.aws.cloud.qdrant.io:6333/collections/paul_graham/points/search "HTTP/2 200 OK"
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 7 tokens
None
```

However, when using `GPTSimpleVectorIndex` with `llama-index==0.5.15`, the script gets the response:

```
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 17609 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 3877 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 7 tokens


Microcomputers allowed people to have a computer sitting right in front of them on a desk that could respond to their keystrokes as it was running instead of just churning through a stack of punch cards and then stopping. This made programming much easier and more accessible, allowing students to learn and experiment with programming without needing to rely on faculty instruction. It also enabled people to create art and other projects in the comfort of their own homes, as evidenced by the example of the student painting still lives in their bedroom at night.
```

Here is an example of the JSON file, based on `index.save_to_disk("./test-response/index_qdrant.json")`

![Screenshot 2023-04-17 12 01 48](https://user-images.githubusercontent.com/13058422/232558428-88aaa214-e3bc-425e-b5ac-a909bcf7666f.png)

**Comment by logan-markewich** [comment]
I think this was fixed very recently, can you try upgrading your llama_index version?

**Comment by estebanpdl** [comment]
Thank you, Logan.

The `llama-index==0.5.16` version now provides the response when adding a Qdrant remote client.

```
client = qdrant_client.QdrantClient(
    # location=":memory:"
    url='https://....aws.cloud.qdrant.io',
    api_key='xxxxxxxxxxxxxxxxxxxxxx',
    https=True
)
```

It also reads the client successfully when loading the index:

```
index = GPTQdrantIndex.load_from_disk(
    "./test-response/index_qdrant_beta.json",
    client=client
)
```

However, I found that `location=":memory:"` and `index.save_to_disk("./test-response/index_qdrant_beta.json")` do not generate the JSON file correctly. Some objects are still empty.

![Screenshot 2023-04-17 13 48 43](https://user-images.githubusercontent.com/13058422/232585624-1670dfeb-6338-4062-927f-9cef7405e835.png)

Not sure if this is the normal behavior when adding a vector engine, such as Qdrant.

**Comment by logan-markewich** [comment]
@estebanpdl I think this is expected when saving to disk with a 3rd party vector store.

All the data is in the qdrant client (which is loaded in memory), so I think you need to save that disk separately?

Normally, 3rd party vector stores should  presist itself outside of llama index, which is why it's not saved in the json

**Comment by estebanpdl** [comment]
Oh got it. It makes sense. Thanks a lot for the support, @logan-markewich 

Best,
