### ISSUE TITLE
Getting type = vector_store_dict[TYPE_KEY] KeyError: 'type' error only on streamlit cloud

### ISSUE THREAD

**Issue by mfelat** [jerryjliu/llama_index#1228]
hello, I'm getting this error with my app only when I run it on streamlit cloud and couldn't resolve it, what might be causing it?

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

2023-04-17 23:08:01.114 Uncaught app exception

Traceback (most recent call last):

File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script

exec(code, module.__dict__)
File "/app/chat6529/6529GPT.py", line 99, in

st.session_state.response_text, st.session_state.similarity_score = process_question(query)
File "/app/chat6529/6529GPT.py", line 54, in process_question

index = GPTSimpleVectorIndex.load_from_disk(input_index)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 364, in load_from_disk

return cls.load_from_string(file_contents, **kwargs)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 340, in load_from_string

return cls.load_from_dict(result_dict, **kwargs)
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 260, in load_from_dict

vector_store = load_vector_store_from_dict(
File "/home/appuser/venv/lib/python3.9/site-packages/llama_index/vector_stores/registry.py", line 52, in load_vector_store_from_dict

type = vector_store_dict[TYPE_KEY]
KeyError: 'type'

**Comment by markusantonuis** [comment]
I am also getting this exact same error with GPTSimpleVectorIndex despite it working fine up until yesterday

**Comment by jerryjliu** [comment]
We recently changed the way we save/load vector stores from disk - sorry about that 

@mfelat out of curiosity, is it expensive to rebuild the vector index?

**Comment by mfelat** [comment]
no not expensive, but the interesting part is, it works on my mac without an error.
how can I reindex the file?

**Comment by jerryjliu** [comment]
Rebuild the index from the existing set of documents

**Comment by mfelat** [comment]
this is how I indexed it, is it changed now?
def read_text_file(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    return content

def split_text(text, chunk_size):
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

def construct_index(file_path):
    # set maximum input size
    max_input_size = 8192
    # set number of output tokens
    num_outputs = 256
    # set maximum chunk overlap
    max_chunk_overlap = 20
    # set chunk size limit
    chunk_size_limit = 3300

    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

    # define LLM
    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="text-embedding-ada-002-v2", max_tokens=num_outputs))

    content = read_text_file(file_path)
    chunks = split_text(content, chunk_size_limit)

    documents = [Document(chunk) for chunk in chunks]

    index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

    index.save_to_disk('index.json')

    return index

construct_index("/Users/mesutozsoy/Desktop/6529/ne/3.txt")

**Comment by IAmStoxe** [comment]
I just spent about $250 indexing a library of legal documents. How can I migrate?

**Comment by splendourbell** [comment]
修改了后，感觉效果不行了

**Comment by markusantonuis** [comment]
Is there still a need to rebuild the index to fix this issue? I would prefer to wait until there is a clear resolution.

**Comment by markusantonuis** [comment]
I downgraded like you suggested and that works, thanks! 
Got an unusual warning from openai:
UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`

**Comment by mfelat** [comment]
> from langchain.chat_models import ChatOpenAI

this is for indexing I think, right? so we probably need to reindex as I'm using gpt-3.5-turbo for completinons

**Comment by ameglio** [comment]
Also for me it works perfectly on my macbook but not on Heroku. I tried to downgrade to 0.4.40 but now I got:

 **`ImportError: cannot import name 'ServiceContext' from 'llama_index' (/app/.heroku/python/lib/python3.11/site-packages/llama_index/__init__.py)`** 

Any suggestion on other solutions? Not sure since which version ServiceContext was available  😢

**Comment by markusantonuis** [comment]
> > from langchain.chat_models import ChatOpenAI
> 
> this is for indexing I think, right? so we probably need to reindex as I'm using gpt-3.5-turbo for completinons

That was for querying only, using GPT3.5. I indexed the documents using the default (ADA2) weeks ago. I haven't tried reindexing yet.

**Comment by mfittko** [comment]
same, would be cool if we could get a hint on how to migrate the index files.

**Comment by Martok88** [comment]
I experienced this issue as well, after upgrading to the latest version. A migration tool would be ideal, to avoid the cost of recreating indexes. I was also wondering, will there be any similar problems with the upcoming 0.6 version?
