### ISSUE TITLE
Question: serialize AgentExecutor object

### ISSUE THREAD

**Issue by pelyhe** [jerryjliu/llama_index#1229]
Hi!

I am creating an AgentExecutor with `llama_index.langchain_helpers.agents`'s `create_llama_chat_agent` function. I want to build a webpage, where users can log in and I store the AgentExecutor objects to each user in the database somehow (to keep the context). 
Do you have any idea how can I serlialize/deseralize an AgentExecutor object in my database? 
I tried load_agent function earlier but it throws [this](https://github.com/hwchase17/langchain/issues/2627) error. I also tried to serialize it with pickle, but I get an error here as well, which says: `cannot pickle 'builtins.CoreBPE' object`. 
Any idea would be appreciated, I am not sticking to serialize the AgentExecutor object. 

Thanks in advance!

**Comment by Disiok** [comment]
Hey @pelyhe, I think `AgentExecutor` doesn't support save/load yet. 
I think an `Agent` class is stateless, and does not store the context.

We are working on making it easier to persist conversations in LlamaIndex, stay tuned. 
In the meanwhile, you can checkout this example of how to build a chat bot with LlamaIndex, and deal with different conversation sessions: https://github.com/run-llama/llama-api/blob/main/poe-api/poe_api/llama_handler.py
