### ISSUE TITLE
Question: session management with llama_index

### ISSUE THREAD

**Issue by pelyhe** [jerryjliu/llama_index#1232]
Hello!

I am building a python (fast api) rest api, which gets a prompt and a user id, and give back a response. I need it to store the context of the previous messages for every userid (such as in BufferMemory). Also I want to use llama_index beacuse I need to “train” the model with my own data (txt files). 

Do you have any advice how should I do this? How should I store the previous context for each user in a different memory?

Thank you very much for your help in advance!

**Comment by Disiok** [comment]
Take a look at https://github.com/run-llama/llama-api/blob/main/poe-api/poe_api/llama_handler.py to see an example of how we implement a Poe Chatbot with LlamaIndex!
