### ISSUE TITLE
Getting "None" on return. Paul_Graham_essay example.

### ISSUE THREAD

**Issue by andrewipu** [jerryjliu/llama_index#1234]
Apologies in advance, I know it's probably a very noob problem. I'm trying to reproduce the paul_graham_example. 

Here's my .py code:

```
import os
import openai

openai.api_key = os.environ["OPENAI_API_KEY"] #I have set my key in the environment variables on my system.

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader


documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex.from_documents(documents)


response = index.query("What did the author do growing up?")
print(response)
```
The return of the above is:

> INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 8 tokens
> None

I'm on llama_index version 0.5.17 on VS Code.

Any help would be much appreciated!

**Comment by logan-markewich** [comment]
It looks like the documents are empty 
`[build_index_from_nodes] Total embedding token usage: 0 tokens`

Did you point it to the correct directory?

**Comment by andrewipu** [comment]
> It looks like the documents are empty `[build_index_from_nodes] Total embedding token usage: 0 tokens`
> 
> Did you point it to the correct directory?

Well...I'm not entirely sure because I assumed it's going to reference the "data" folder in the paul_graham_essay folder which has the essay as a txt. Is that correct?

**Comment by logan-markewich** [comment]
@andrewipu that's right! but does it point to the correct path? Is there a "./data" directory in the same directory as the script? Is there a text file in that directory?

**Comment by andrewipu** [comment]
My .py script is in the "paul_graham_essay" folder. There's a text file inside the "data" folder.

**Comment by logan-markewich** [comment]
Hmmm what the heck haha

In your script, can you print documents to see if there's anything in there, before indexing?

**Comment by andrewipu** [comment]
Hehe...right?! I've been scratching my head over this for hours. Gimme a sec try your suggestion.

**Comment by andrewipu** [comment]
Okay, printing documents returns an empty list ([]). Either there's something I'm doing wrong or it's a bug...it doesn't make sense.

> Hmmm what the heck haha
> 
> In your script, can you print documents to see if there's anything in there, before indexing?

Okay, printing documents returns an empty list ([]). Either there's something I'm doing wrong or it's a bug...it doesn't make sense.

**Comment by logan-markewich** [comment]
@andrewipu ok! One step closer! lol

two things
1. you can try adding this to double-check the path
```
import os
print(os.listdir("./data"))
```

2. try putting the full path to the data dir
`documents = SimpleDirectoryReader("full/path/to/data").load_data()`
Or, at least add the relative symbol to the path
`./data`

**Comment by andrewipu** [comment]
Ok...gimme a few.

**Comment by andrewipu** [comment]
@logan-markewich Ok so, on trying:
```
import os
print(os.listdir("./data"))
```
I get:

> Traceback (most recent call last):
>   File "c:\Users\USER\VS\LlamaIndex\gpt_index\examples\paul_graham_essay\query_index.py", line 2, in <module>
>     print(os.listdir("./data"))
>           ^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 3] The system cannot find the path specified: './data'

I'm guessing the above isn't good...

On the second option:

Putting the full path, I get:

> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape 

If I shorten it just ever so slightly I get an empty list again.

**Comment by logan-markewich** [comment]
OK!

From the first error, I think the data dir is not in the same folder as your py script 🤔 

Or if it is, you need to cd into the same folder as your py script and data dir, and run it from there

**Comment by andrewipu** [comment]
@logan-markewich Ok...I'll take a look at that. In the meantime, I tried putting an "r" just before the full path, and now I get the document returned.

Goes like this:
```
import os
print(os.listdir(r'C:\Users\USER\VS\LlamaIndex\gpt_index\examples\paul_graham_essay\data'))
```

I get:

> ['paul_graham_essay.txt']

It's a good sign I guess... :)

**Comment by andrewipu** [comment]
@logan-markewich Aaaah yes documents prints now!

**Comment by andrewipu** [comment]
@logan-markewich Yeeeesssss!! It works!!! Thank you so much man!! God bless!
This is my full code in the .py:

```
import os
import openai

openai.api_key = os.environ["OPENAI_API_KEY"]

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader


documents = SimpleDirectoryReader(r'C:\Users\USER\VS\LlamaIndex\gpt_index\examples\paul_graham_essay\data').load_data()


index = GPTSimpleVectorIndex.from_documents(documents)


response = index.query("What did the author do growing up?")
print(response)
```

**Comment by logan-markewich** [comment]
@andrewipu perfect! 💪💪🙏🙏
