### ISSUE TITLE
query without access LLM

### ISSUE THREAD

**Issue by try-agaaain** [jerryjliu/llama_index#1245]
I want to call the query function to query the GPTSimpleVectorIndex in some of the most similar document content, but in the process I do not want to access the LLM, in version 0.4.32, I can specify response_mode = "no_text" to achieve this purpose, the code is as follows:
```python
from llama_index import GPTSimpleVectorIndex
index = GPTSimpleVectorIndex.load_from_disk(f"./train_data.json")
query = "my query"
response = index.query(query, response_mode="no_text", 
                           similarity_cutoff=0.6, similarity_top_k=similarity_top_k)
```
However, in the latest version 0.5.17, this parameter is deprecated and I have checked the documentation without finding a suitable solution for now.

**Comment by logan-markewich** [comment]
Try and update to the latest version, it should be working now again 

https://github.com/jerryjliu/llama_index/pull/1236
