### ISSUE TITLE
CustomLLM not working on PDF data

### ISSUE THREAD

**Issue by shaktiman101** [jerryjliu/llama_index#1250]
I'm using [https://github.com/jerryjliu/llama_index/blob/046183303da4161ee027026becf25fb48b67a3d2/docs/how_to/custom_llms.md#example-using-a-custom-llm-model](url) as the base code with slight variation of my own where I'm trying to read a sample pdf file & using facebook/opt-125m model to query the document:

`import torch
from langchain.llms.base import LLM
from llama_index import SimpleDirectoryReader, LangchainEmbedding, GPTListIndex, PromptHelper
from llama_index import LLMPredictor
from transformers import pipeline
from typing import Optional, List, Mapping, Any

max_input_size = 2048
num_output = 256
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

class CustomLLM(LLM):
      model_name = "facebook/opt-125m"
      pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})

      def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
            prompt_length = len(prompt)
            response = self.pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

            # only return newly generated tokens
            return response[prompt_length:]

      @property
      def _identifying_params(self) -> Mapping[str, Any]:
            return {"name_of_model": self.model_name}

      @property
      def _llm_type(self) -> str:
            return "custom"

from pathlib import Path
from llama_index import download_loader
PDFReader = download_loader('PDFReader')
loader = PDFReader()
documents = loader.load_data(file=Path('<pdf file path>'))
index = GPTListIndex.from_documents(documents, service_context=service_context)

response = index.query("<query_text>")
print(response)`

everything seems to run & compile properly except when I try to run 'index.query("<query text>")' it throws me either "IndexError: index out of range in self" or "Input length of input_ids is 3418, but `max_length` is set to 21. This can lead to unexpected behavior".

**Comment by logan-markewich** [comment]
Not sure how max length got set to 21 there 🤔 

I think you'll want to set chunk_size_limit in both the service_context and the prompt_helper constructors.

**Comment by logan-markewich** [comment]
check out the latest guides for custom LLMs and embedding models here

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-huggingface-llm

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations
