### ISSUE TITLE
validation error for LLMChain

### ISSUE THREAD

**Issue by xerxes01** [jerryjliu/llama_index#1251]
I'm trying to replicate the SEC notebook using an open source LLM from huggingface. 

LLM instantitation:
```
import torch
from langchain.llms.base import LLM
from transformers import pipeline
from llama_index import LLMPredictor, ServiceContext


class CustomLLM(LLM):
    model_name = "eachadea/vicuna-13b-1.1"
    pipeline = pipeline("text-generation", model=model_name, device="cuda:1", model_kwargs={"torch_dtype":torch.bfloat16,
                                                                                           "temperature":0})

    def _call(self, prompt, stop=None):
        return self.pipeline(prompt, max_length=9999)[0]["generated_text"]

    def _identifying_params(self):
        return {"name_of_model": self.model_name}

    def _llm_type(self):
        return "custom"

vicuna_llm = LLMPredictor(llm=CustomLLM())
```
However, when I create indices and a graph from these indices and then try to create the agent like this:

```
memory = ConversationBufferMemory(memory_key="chat_history")
agent_chain = create_llama_chat_agent(
    toolkit,
    vicuna_llm,
    memory=memory,
    verbose=True
)
```
I get this error:

> ValidationError: 1 validation error for LLMChain
> llm
>   value is not a valid dict (type=type_error.dict)

Please let me know where am I going wrong!

**Comment by logan-markewich** [comment]
For the custom LLM, I think you need to add all the type annotations.

You'll also want to double check that you are returning a string (I usually cast it as a string just to be safe)

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model

**Comment by jawerty** [comment]
Hey not sure if you're still having this issue but setting`return_dict_in_generate` to True in the generate_kwargs key to the LLM arguments helped me fix this. 

This is happening because the generate function of your custom model isn't returning a dict but LlamaIndex assuming a dict response

**Comment by vladimircape** [comment]
> Hey not sure if you're still having this issue but setting`return_dict_in_generate` to True in the generate_kwargs key to the LLM arguments helped me fix this.
> 
> This is happening because the generate function of your custom model isn't returning a dict but LlamaIndex assuming a dict response

I tried, with no success
```

llm = HuggingFaceLLM(
    context_window=4096,
    max_new_tokens=256,    
    generate_kwargs={"temperature": 0.7, "do_sample": False, "return_dict_in_generate":True},
    system_prompt=system_prompt,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="StabilityAI/stablelm-tuned-alpha-3b",
    model_name="StabilityAI/stablelm-tuned-alpha-3b",
    device_map="auto",
    stopping_ids=[50278, 50279, 50277, 1, 0],
    tokenizer_kwargs={"max_length": 4096},
    # uncomment this if using CUDA to reduce memory usage
    # model_kwargs={"torch_dtype": torch.float16}
)
tools = [
    Tool(
        name="LlamaIndex",
        func=lambda q: str(index.as_query_engine(
            retriever_mode="embedding", 
            verbose=True, 
            service_context=service_context
        ).query(q)),
        description="useful for when you want to answer questions about finance. The input to this tool should be a complete english sentence.",
        return_direct=True,
    ),
]
agent_executor = initialize_agent(
    tools, llm, agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,memory=memory
)
```

**Comment by logan-markewich** [comment]
@vladimircape I pushed a fix for an error with the new huggingface LLM class today.

You can install from source or wait for the next pypi release

**Comment by vladimircape** [comment]
> @vladimircape I pushed a fix for an error with the new huggingface LLM class today.
> 
> You can install from source or wait for the next pypi release
I checked
https://github.com/jerryjliu/llama_index/commit/9d4af9f0483273da482c3291be245a57793ee5e2
and update
but the problem still exists
```
ValidationError                           Traceback (most recent call last)
Cell In[13], line 1
----> 1 agent_executor = initialize_agent(
      2     tools, llm, agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,memory=memory
      3 )
      4 agent_executor.run(input="What is inflation in the Czech Republic?")

File F:\anaconda\lib\site-packages\langchain\agents\initialize.py:57, in initialize_agent(tools, llm, agent, callback_manager, agent_path, agent_kwargs, tags, **kwargs)
     55     agent_cls = AGENT_TO_CLASS[agent]
     56     agent_kwargs = agent_kwargs or {}
---> 57     agent_obj = agent_cls.from_llm_and_tools(
     58         llm, tools, callback_manager=callback_manager, **agent_kwargs
     59     )
     60 elif agent_path is not None:
     61     agent_obj = load_agent(
     62         agent_path, llm=llm, tools=tools, callback_manager=callback_manager
     63     )

File F:\anaconda\lib\site-packages\langchain\agents\conversational\base.py:115, in ConversationalAgent.from_llm_and_tools(cls, llm, tools, callback_manager, output_parser, prefix, suffix, format_instructions, ai_prefix, human_prefix, input_variables, **kwargs)
    105 cls._validate_tools(tools)
    106 prompt = cls.create_prompt(
    107     tools,
    108     ai_prefix=ai_prefix,
   (...)
    113     input_variables=input_variables,
    114 )
--> 115 llm_chain = LLMChain(
    116     llm=llm,
    117     prompt=prompt,
    118     callback_manager=callback_manager,
    119 )
    120 tool_names = [tool.name for tool in tools]
    121 _output_parser = output_parser or cls._get_default_output_parser(
    122     ai_prefix=ai_prefix
    123 )

File F:\anaconda\lib\site-packages\langchain\load\serializable.py:74, in Serializable.__init__(self, **kwargs)
     73 def __init__(self, **kwargs: Any) -> None:
---> 74     super().__init__(**kwargs)
     75     self._lc_kwargs = kwargs

File F:\anaconda\lib\site-packages\pydantic\main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for LLMChain
llm
  value is not a valid dict (type=type_error.dict)
```

**Comment by logan-markewich** [comment]
Just read this error closer, u guess it's slightly different that the one I fixed lol will patch this soon

**Comment by vladimircape** [comment]
> Just read this error closer, I guess it's slightly different that the one I fixed lol will patch this soon (for reference, the error I fixed was specific to the huggingface llm)

LangChain produce such error, but possible the reason in HuggingFace class

**Comment by scoobyd0027** [comment]
Hey @logan-markewich, I am also having  this issue, any updates or ETA?

**Comment by logan-markewich** [comment]
@scoobyd0027 @vladimircape just read the error and example code again. 

My bad for not seeing this, but you are using a llama index LLM inside a lamgchain object class -- these are two incompatible objects

**Comment by scoobyd0027** [comment]
I am trying to run this notebook and running it the same issue https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb, I did not make any changes to it

**Comment by JoshuaJose978** [comment]
> I am trying to run this notebook and running it the same issue https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb, I did not make any changes to it

I think LLMPredictor class is not there anymore in the Llama_Index source code.....so you can actually load your preferred llm and embedding model and then put it into ServiceContext                                                                                             service_context = ServiceContext.from_defaults( llm=llm, embed_model=query_embed_model,)                                                                        where query_embed_model can even be some hugging face embedding model

**Comment by logan-markewich** [comment]
Going to close this issue. The notebook has been updated slightly, but the overall notebook is being completely redone here

https://github.com/jerryjliu/llama_index/pull/7767

The previous notebook used langchain utilities that are both deprecated and unmaintained
