### ISSUE TITLE
What is returned when the retrieved documents don't have information for the given question?

### ISSUE THREAD

**Issue by sp-yang** [jerryjliu/llama_index#1262]
During the testing of a QA system using llama index, I found an issue bellow:
The retrieved documents (i.e. source_nodes) don't have information for the given question, but the response give some strange information that I don't know where do they come from.
So, what is returned when the retrieved documents don't have information for the given question?

**Comment by logan-markewich** [comment]
technically, the LLM is supposed to only use the context to answer the question. If it is not relevant, it will either say so (or make something up if it is not following instructions -- a common problem for some less-smart LLMs)

Sometimes it takes some extra prompt engineering to reduce hallucinations

**Comment by sp-yang** [comment]
I have tried to use Custom Prompt Template for the query function, however it still respond to question with its own knowledge that is outside of the given context. Is there a way in llama-index to restrict LLM to answer questions only using information from our own documents?

**Comment by logan-markewich** [comment]
@sp-yang not perfectly. It's the nature of LLMs, they have to follow instructions in the prompt. It's mostly a prompt engineering problem right now. Just gotta try more custom prompts (make sure you define both a text qa template and a refine template)

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html


You could try using one of the eval functions in the repo, but this will also slow down responses. https://github.com/jerryjliu/llama_index/tree/main/examples/evaluation
