### ISSUE TITLE
seems there's a limit to the response text. "Total embedding token usage" is always less than 38 tokens

### ISSUE THREAD

**Issue by pinsystem** [jerryjliu/llama_index#1278]
I've tested several times with different prompts, and it seems there's a limit to the response text. "Total embedding token usage" is always less than 38 tokens. I don't know if the two are related.
```
...
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 661 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: **38** tokens
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 659 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: **34** tokens
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 651 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: **27** tokens
...
```

I've tried changing variables like `num_outputs`, `max_chunk_overlap`, `chunk_size_limit` and changing models `code-davinci-002`, `text-davinci-003`... and never made it work. 

Here's the whole code. please review it.

```
from llama_index import SimpleDirectoryReader, GPTListIndex, LLMPredictor, PromptHelper, ServiceContext, GPTSimpleVectorIndex
from langchain.chat_models import ChatOpenAI
from langchain.llms import OpenAI
import gradio as gr
import sys
import os

os.environ["OPENAI_API_KEY"] = '...'

def construct_index(directory_path):
    max_input_size = 4096
    num_outputs = 1024
    max_chunk_overlap = 40
    chunk_size_limit = 1200
    
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=num_outputs))
    documents = SimpleDirectoryReader(directory_path).load_data()
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
    index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
    index.save_to_disk('index.json')
    return index

def chatbot(input_text):
    index = GPTSimpleVectorIndex.load_from_disk('index.json')
    response = index.query(input_text, response_mode="compact")
    return response.response
iface = gr.Interface(fn=chatbot,
    				 inputs=gr.inputs.Textbox(lines=7, label="Enter your text"),
    				 outputs="text",
    				 title="test")
index = construct_index("docs")
iface.launch(share=True)
```

**Comment by pinsystem** [comment]
I just found that it happens when the prompt is Korean. When the prompt is English the result(completion) seems not truncated. Its token is 256 and 1285 characters calculated by https://platform.openai.com/tokenizer

**Comment by logan-markewich** [comment]
@pinsystem the embedding tokens during the query are only for the query text (which is why they are small)

If your responses are cutoff, you'll need to also change max_tokens in the llm definition, on addition to changing num_output (num_output and max_tokens should be the same)

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

**Comment by pinsystem** [comment]
@logan-markewich Thank you for your answer. I've already tried to increase `max_tokens` and make it same as `num_output`. But it stays the same. 

I just tested with various languages and found out that only 'alphabet' query provides intact results. Not even Korean but Japanese, Chinese, Russian, Turkish queries.. their responses are all truncated. And Portuguese with special Character(õ) also failed but if it changed to õ → o, the result is not truncated.

![image](https://user-images.githubusercontent.com/84297114/233876274-355ae893-3b74-40b1-9ca2-eaf9770e3a13.png)

This Charset problem seems happening to others.. according to the new issues here. Maybe related to my specific environment? My testing environment is : `Window server 2019 Standard 64bit, Python 3.11.3, pip 23.1`.

**Comment by guilhermelirio** [comment]
@pinsystem The same error occurs here. Even without using an accent, every time the answer is incomplete.

Managed to solve?

Windows 10 
Python 3.8.3
llama_index==0.5.4
langchain==0.0.128

**Comment by Jafo232** [comment]
I am having the same issue.  Changing max_tokens does nothing.

**Comment by logan-markewich** [comment]
you can also now set a global service context

```python
from llama_index import set_global_service_context

set_global_service_context(service_context)
```
