### ISSUE TITLE
How to add promt in index.query for chatmodel gpt-3.5-turbo ?

### ISSUE THREAD

**Issue by sai-kiran-adusumilli** [jerryjliu/llama_index#1280]
for Question Answer promt , i have imported QuestionAnswerPrompt and formed a template and pass it to index.query using "text_qa_template=QA_PROMPT" , its working and it's using text-daninci-003 by default ,but i need to use gpt-3.5-turbo while quering 
#i tried using gpt-3.5-turbo , but

llm_predictor = LLMPredictor(llm=ChatOpenAI(model_name="gpt-3.5-turbo",temperature=0))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor,chunk_size_limit=2000)

from langchain.prompts.chat import (
    AIMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
)

from gpt_index.prompts.prompts import RefinePrompt, RefineTableContextPrompt

# Refine Prompt
CHAT_REFINE_PROMPT_TMPL_MSGS = [
    HumanMessagePromptTemplate.from_template("{query_str}"),
    AIMessagePromptTemplate.from_template("{existing_answer}"),
    HumanMessagePromptTemplate.from_template(
        "We have the opportunity to refine the above answer "
        "(only if needed) with some more context below.\n"
        "------------\n"
        "{context_msg}\n"
        "------------\n"        
        " if the question is out of context,apologize, please reply it's not related to Context \n"
        "keep in mind that the answer should be related to Context provided and not generic answer\n",
    ),
]
CHAT_REFINE_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_PROMPT_TMPL_MSGS)
CHAT_REFINE_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_PROMPT_LC)

response = index.query(query3,verbose=True,
                       promt=CHAT_REFINE_PROMPT,
                       similarity_top_k=1,mode='embedding',
                       response_mode='compact',
                       service_context=service_context)
(response.response)
TypeError: __init__() got an unexpected keyword argument 'promt'

how to integrate the above chat promt with the gpt-3.5 , what is the keyword for it

**Comment by logan-markewich** [comment]
There are two templates: text_qa_template and refine_template 

You can pass them in like this: 
`index.query(..., text_qa_template=text_qa_template, refine_template=refine_template)`

**Comment by sai-kiran-adusumilli** [comment]
Got it , working , thanks
