### ISSUE TITLE
Can the document information include the file name and page number be returned?

### ISSUE THREAD

**Issue by robertjelly** [jerryjliu/llama_index#1291]
Index format:
 doc_id": "17e4de8e-aa12-4923-af2b-9d4a238d1c88",    
"embedding": null,
"doc_hash": "5a88d2ca45cf4243af538d4e9bbb7f1a81f54747cdaa86d37f3f512fba10adca",
"extra_info": null,
"node_info": {
      "start": 6195,
       "end": 10179
doc_id is uuid, node_info How to convert to page numbers?

**Comment by kindler-king** [comment]
@robertjelly I know a way to return the file names that the source_nodes (or the answer fragments) are extracted from.
But I am not aware if it is possible to get the page number.

**Comment by djmaze** [comment]
@kindler-king  How to get the file names?
