### ISSUE TITLE
Is there someway to skip refine on langchain agent query

### ISSUE THREAD

**Issue by xingcici** [jerryjliu/llama_index#1293]
Is there someway to skip refine on langchain agent query。redefine answer is not better。

**Comment by logan-markewich** [comment]
It's not really possible to disable it, it's a necessary part of the process. Some LLMs struggle with it though.

Are you using GPT-3.5? It's been struggling with the refine part for the last week or so.

I've been working on a new refine template. Maybe try something like this:

```
from langchain.prompts.chat import (
    AIMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
)

from llama_index.prompts.prompts import RefinePrompt

# Refine Prompt
CHAT_REFINE_PROMPT_TMPL_MSGS = [
    HumanMessagePromptTemplate.from_template("{query_str}"),
    AIMessagePromptTemplate.from_template("{existing_answer}"),
    HumanMessagePromptTemplate.from_template(
        "I have more context below which can be used "
        "(only if needed) to update your previous answer.\n"
        "------------\n"
        "{context_msg}\n"
        "------------\n"
        "Given the new context, update the previous answer to better "
        "answer my previous query."
        "If the previous answer remains the same, repeat it verbatim. "
        "Never reference the new context or my previous query directly.",
    ),
]


CHAT_REFINE_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_PROMPT_TMPL_MSGS)
CHAT_REFINE_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_PROMPT_LC)
...
index.query("my query", similarity_top_k=3, refine_template=CHAT_REFINE_PROMPT)
```

**Comment by xingcici** [comment]
Yes，I’m using 3.5。I came up with a new prompt early on, forcing it not to
change the original answer structure, but to optimize the original answer,
and achieved good results. Another reason I want to close it is that the
performance will have a relatively large impact after opening it,
especially for relatively long answers and streams cannot be used. I will
continue to see how to deal with it. Do you have any good suggestions for
this one? Thanks.

Logan ***@***.***>于2023年4月24日 周一00:55写道：

**Comment by xingcici** [comment]
> It's not really possible to disable it, it's a necessary part of the process. Some LLMs struggle with it though.
> 
> Are you using GPT-3.5? It's been struggling with the refine part for the last week or so.
> 
> I've been working on a new refine template. Maybe try something like this:
> 
> ```
> from langchain.prompts.chat import (
>     AIMessagePromptTemplate,
>     ChatPromptTemplate,
>     HumanMessagePromptTemplate,
> )
> 
> from llama_index.prompts.prompts import RefinePrompt
> 
> # Refine Prompt
> CHAT_REFINE_PROMPT_TMPL_MSGS = [
>     HumanMessagePromptTemplate.from_template("{query_str}"),
>     AIMessagePromptTemplate.from_template("{existing_answer}"),
>     HumanMessagePromptTemplate.from_template(
>         "I have more context below which can be used "
>         "(only if needed) to update your previous answer.\n"
>         "------------\n"
>         "{context_msg}\n"
>         "------------\n"
>         "Given the new context, update the previous answer to better "
>         "answer my previous query."
>         "If the previous answer remains the same, repeat it verbatim. "
>         "Never reference the new context or my previous query directly.",
>     ),
> ]
> 
> 
> CHAT_REFINE_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_PROMPT_TMPL_MSGS)
> CHAT_REFINE_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_PROMPT_LC)
> ...
> index.query("my query", similarity_top_k=3, refine_template=CHAT_REFINE_PROMPT)
> ```

Yes，I’m using 3.5。I came up with a new prompt early on, forcing it not to
change the original answer structure, but to optimize the original answer, and achieved good results. 
Another reason I want to close it is that the performance will have a relatively large impact after opening it, especially for relatively long answers and streams cannot be used. I will continue to see how to deal with it. Do you have any good suggestions for this one? Thanks.

**Comment by logan-markewich** [comment]
The best option for limiting the refine is usually using a smaller chunk size (and if using a vector index, you can use `index.query(..., response_mode="compact")`, which helps when your similarity_top_k is greater than 1)

**Comment by xingcici** [comment]
> The best option for limiting the refine is usually using a smaller chunk size (and if using a vector index, you can use `index.query(..., response_mode="compact")`, which helps when your similarity_top_k is greater than 1)

Thanks，I will try it tomorrow ！

**Comment by hulemihi** [comment]
Hi @xingcici, did you get the solution for this issue. I got the same problem.
