### ISSUE TITLE
Is Text-Babbage-001 supported? If you do not support it, it would be helpful if you could implement it.

### ISSUE THREAD

**Issue by takanomizuki** [jerryjliu/llama_index#1297]
**I tried the following code and got an error. I have a feeling that perhaps text-Babbage-001 and text-Ada-001 are not supported by the current llama index. However, I estimated that a large index would cost $20,000 for text-davinci-003, so to keep this down to a few hundred dollars, I really need to use text-Babbage-001, which is a personal problem.
If you don't mind, it would be very helpful if you could also implement a less expensive model as it may not affect the quality of the index that much.**

「import os
import sys
from gpt_index import download_loader, GPTTreeIndex
from gpt_index.llm_predictor import LLMPredictor

pdf_file = sys.argv[1]

# 環境変数にAPIキーを設定
os.environ['OPENAI_API_KEY'] = "your_api_key_here"
model_name = "text-Babbage-001"

CJKPDFReader = download_loader("CJKPDFReader")
loader = CJKPDFReader(concat_pages=False)

# Load the PDF data
documents = loader.load_data(file=pdf_file)

# Create an LLMPredictor instance with text-Babbage-001
llm_predictor = LLMPredictor(model=model_name)

# Create an index using GPTTreeIndex
index = GPTTreeIndex(llm_predictor=llm_predictor, openai_api_key=os.environ['OPENAI_API_KEY'])

# Add documents to the index
index.add_documents(documents)

# Save the index to the same directory as the PDF file
index_filename = os.path.join(
    os.path.dirname(pdf_file), f"{os.path.splitext(os.path.basename(pdf_file))[0]}_index.json"
)
index.save_to_disk(index_filename)

print(f"Index saved to {index_filename}")」

「アクション“シェルスクリプトを実行”でエラーが起きました: “Traceback (most recent call last):
File "<string>", line 19, in <module>
TypeError: LLMPredictor.__init__() got an unexpected keyword argument 'model'”」

**Comment by logan-markewich** [comment]
You can use text-babbage like this

(babbage might be lowercase or cuppercase, not sure)
```
from langchain.llms import OpenAI
llm_predictor=LLMPredictor(llm=OpenAI(temperature=0, model_name="text-Babbage-001"))
```

You can also consider using gpt-3.5, which is 10x cheaper than davinci 

```
from langchain.chat_models import ChatOpenAI
llm_predictor=LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo))
```
