### ISSUE TITLE
Question：the return length of chinese

### ISSUE THREAD

**Issue by kolinwei** [jerryjliu/llama_index#1299]
When I use llama_index to construct a Chinese knowledge ，It seems that  the returned Chinese  char will be truncated when it reaches 100。I hava set configuration like this。

`llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", max_tokens=1024))
  max_input_size = 4096
  num_output = 1024
  max_chunk_overlap = 20
  prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
  self.service_context = ServiceContext.from_defaults(llm_predictor=self.llm_predictor, prompt_helper=prompt_helper)`

But it doesn't seem to be working at all. Can you tell me what's going on。

**Comment by logan-markewich** [comment]
try passing in the service context at query time too

`index.query(..., service_context=service_context)`

**Comment by pinsystem** [comment]
suffering same problem. I think it's Charset problem. Only English alphabet queries work.

**Comment by kolinwei** [comment]
> try passing in the service context at query time too
> 
> `index.query(..., service_context=service_context)`

it seems don't work

**Comment by kolinwei** [comment]
Can someone help?

**Comment by hongyishi** [comment]
Hi @kolinwei can you try
from gpt_index.langchain_helpers.text_splitter import SentenceSplitter
sentence_splitter = SentenceSplitter()
node_parser = SimpleNodeParser(text_splitter=sentence_splitter)
service_context = ServiceContext.from_defaults(node_parser=node_parser)

**Comment by Myoungs** [comment]
> Hi @kolinwei can you try from gpt_index.langchain_helpers.text_splitter import SentenceSplitter sentence_splitter = SentenceSplitter() node_parser = SimpleNodeParser(text_splitter=sentence_splitter) service_context = ServiceContext.from_defaults(node_parser=node_parser)

I tried this, but still have the truncation problem

**Comment by Myoungs** [comment]
https://github.com/jerryjliu/llama_index/issues/313

**Comment by is3a** [comment]
> 在 llm_predictor 中设置 max_tokens 有效！！参考：#313

Hello, it seems that it is still not feasible：
def construct_index(directory_path):
    max_input_size = 4096
    num_outputs = 1024
    max_chunk_overlap = 20
    chunk_size_limit = 600
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))

**Comment by is3a** [comment]
> 我用llama_index构造中文知识时，好像返回的中文字符到了100就被截断了。我是这样设置的。
> 
> `llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", max_tokens=1024)) max_input_size = 4096 num_output = 1024 max_chunk_overlap = 20 prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap) self.service_context = ServiceContext.from_defaults(llm_predictor=self.llm_predictor, prompt_helper=prompt_helper)`
> 
> 但它似乎根本不起作用。你能告诉我这是怎么回事吗。

Hello, may I ask if you have solved the issue?

**Comment by Myoungs** [comment]
> > 在 llm_predictor 中设置 max_tokens 有效！！参考：#313
> 
> Hello, it seems that it is still not feasible： def construct_index(directory_path): max_input_size = 4096 num_outputs = 1024 max_chunk_overlap = 20 chunk_size_limit = 600 prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit) llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))

Try setting max_tokens = -1

**Comment by is3a** [comment]
> > > 在 llm_predictor 中设置 max_tokens 有效！！参考：#313
> > 
> > 
> > 你好，好像还是不行： def construct_index(directory_path): max_input_size = 4096 num_outputs = 1024 max_chunk_overlap = 20 chunk_size_limit = 600 prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit) llm_predictor = LLMPre独裁者（llm=OpenAI (temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))
> 
> 尝试设置 max_tokens = -1

Still not working.

**Comment by kolinwei** [comment]
local_index = GPTSimpleVectorIndex.load_from_disk(index_path, **service_context=self.service_context**)

try this，add the service_context parameter to load_from_disk

**Comment by Disiok** [comment]
Closing this now. See https://gpt-index.readthedocs.io/en/latest/core_modules/supporting_modules/service_context.html for more information on configuring service context.
