### ISSUE TITLE
azure openai compatibility

### ISSUE THREAD

**Issue by javixeneize** [jerryjliu/llama_index#1307]
Hi

Is the library compatible with an azure openai instance?

According to azure openai, it requires 3 parameters

https://learn.microsoft.com/en-gb/azure/cognitive-services/openai/quickstart?pivots=programming-language-python&tabs=command-line

openai.api_key = "REPLACE_WITH_YOUR_API_KEY_HERE"
openai.api_base =  "REPLACE_WITH_YOUR_ENDPOINT_HERE" # your endpoint should look like the following https://YOUR_RESOURCE_NAME.openai.azure.com/
openai.api_type = 'azure'
openai.api_version = '2022-12-01' # this may change in the future

**Comment by abhishek-ravikumar-kulkarni** [comment]
i am getting this issue with openai azure gpt4 deployment

`InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

 `

When i am doing, 

`indexAzure = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
`

**Comment by zioproto** [comment]
Does this example from the documentation help ?
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/customization/llms/AzureOpenAI.ipynb
