### ISSUE TITLE
How can I use the already quantized LLaMA-Alpaca model on llama_index?

### ISSUE THREAD

**Issue by Bruce337f** [jerryjliu/llama_index#1309]
class CustomLLM(LLM):
    model_name = r"LLaMA-Alpaca/13B"
    pipeline = pipeline("text-generation", model=model_name, device="cuda:0",
                        model_kwargs={"torch_dtype": torch.bfloat16})

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)
        response = self.pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        return response[prompt_length:]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": self.model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"

but it doesn't work:
    raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model D:\pythonxmu\oobabooga_windows\text-generation-webui\models\13B with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForCausalLM'>).

**Comment by logan-markewich** [comment]
We officially support hugging face models, azure, replicate, palm, and of course openai.

You can also define your own custom LLM class as you have done here, but the usage has changed. I would make sure to use an LLM that has at least 2048 input size (flan is only 512)

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced
