### ISSUE TITLE
Question: System messages

### ISSUE THREAD

**Issue by pelyhe** [jerryjliu/llama_index#1312]
Hi!

I am working with AgentExecutors, which are being created with the create_llama_chat_agent() function.
The relevant part of the code looks like this:
```
        llm = OpenAI(temperature=0, model_name="gpt-3.5-turbo")

        return create_llama_chat_agent(
            toolkit,
            llm,
            memory=memory,
            verbose=True
        )
```
It works perfectly, but I want to add system messages to every request. Can you help me with this?

**Comment by hlcheuk** [comment]
I am having the same problem. I have been building a chatbot following the document here:
https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html

And I want to add a system message to my chatbot by specifying `system_message` and `agent_kwargs` as mentioned at this langchain thread. (as create_llama_chat_agent() is a wrapper around initialize_agent() in langchain)
https://github.com/hwchase17/langchain/issues/6334

But it is not working. Does anyone have ideas on adding a system message to a chatbot?

**Comment by logan-markewich** [comment]
If you use our own data agents, you can easily set the system prompt to be any string.

https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent.html#agent-with-personality

Data Agents Guides:
https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
