### ISSUE TITLE
module 'langchain' has no attribute 'verbose'

### ISSUE THREAD

**Issue by hanqing-blend** [jerryjliu/llama_index#1313]
I'm loading documents and trying to do indexing use GPTSimpleVectorIndex.from_documents(). It throwed me an error message: module 'langchain' has no attribute 'verbose'
I didn't face this issue in last week's attempt. What might be the reason of this?

**Comment by Rammstein-1994** [comment]
Same here

**Comment by climatepro** [comment]
same here

**Comment by adam404** [comment]
Reverting to 0.0.147 seemed to correct the issue 

`!pip install langchain==0.0.147`

**Comment by hanqing-blend** [comment]
The day after I created this issue, this problem solved automatically...

**Comment by nithinkanil1** [comment]
I am also hitting this bug. I updated to langchain==0.0.147. Still facing the issue. It's random and it will fix itself after some time

**Comment by dgerabagi** [comment]
I'm encountering this issue with code that was working yesterday. Tried multiple versions of langchain but still getting the verbose error.

  File "C:\Python311\Lib\site-packages\langchain\llms\openai.py", line 174, in __new__
    return OpenAIChat(**data)
           ^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1066, in pydantic.main.validate_model
  File "pydantic\fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "C:\Python311\Lib\site-packages\langchain\llms\base.py", line 26, in _get_verbosity
    langchain.verbose = False
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'langchain' has no attribute 'verbose'

**Comment by doremi31618** [comment]
@swarajpc thanks ! i solve this issue by your method

**Comment by surajdugg** [comment]
@swarajpc worked for me as well. Thanks!

**Comment by Kiru6ik** [comment]
@swarajpc 0.0.137 version didnt work for me. Tried it in google collab, tried both 0.0.137 and 0.0.147.
For me it worked fine but on the next day again facing no attribute verbose problem

**Comment by AndreasKarasenko** [comment]
I just encountered the same issue with langchain version 0.0.243 similar to @dgerabagi. Yesterday the code worked, today it didn't.
Simply forcing a reinstall with pip fixed the issue for me.

**Comment by imHeartJ** [comment]
pip install langchain==0.0.261
it worked for me, but this issue appeared in 0.0.279 again.

**Comment by YimingYAN** [comment]
I encountered the same problem with the version `0.0.296`. We deployed our app to AWS ECS cluster and this issue went away when we deleted the ECS task and started a new one.

**Comment by tikazyq** [comment]
Same here with the version `0.0.294`

**Comment by khurchla** [comment]
getting this today on langchain==0.0.288 deployed to render. tried deploying with langchain==0.0.261 but my render deployment build then fails. 

Resorting to trying every single version between of langchain but missed the window for my hotfix to have any value. This never came up during local testing. Tough to anticipate this error.

**Comment by Robert-Jia00129** [comment]
If you are using venv, go to your `.venv/lib` directory and search for langchain. In my case, there were langchain (langchain, langchain_openai, langchain_hub ...) packages that had different version numbers. Simply remove and reinstall and it solved the issue.

**Comment by zdb131415** [comment]
please don't name you package "langchain" in you local project!!! Or it will import from your package.
