### ISSUE TITLE
为什么我是用中文问问题，回答确实英文的，文档也是中文的

### ISSUE THREAD

**Issue by xinyue0318343** [jerryjliu/llama_index#1317]
![image](https://user-images.githubusercontent.com/125643602/234218627-e3e9270d-0e68-41ae-99a0-2be82a997f97.png)

**Comment by Myoungs** [comment]
试试query里加上"请用中文回答"

**Comment by xinyue0318343** [comment]
为什么没有根据提问的语言来回来呢，不是用的openai么

**Comment by wey-gu** [comment]
From what I observed, even when using vanilla ChatGPT web service, sometimes it cannot respond in the expected language(the query language). Extra prompt to enforce language is needed in such cases.

**Comment by wey-gu** [comment]
> ![image](https://user-images.githubusercontent.com/125643602/234218627-e3e9270d-0e68-41ae-99a0-2be82a997f97.png)

And from the screen capture, I guess the retrieval got nothing(Chinese) thus the RAG prompt to be sent to LLM was template + empty context, where no(few) Chinese was included, thus it end up with an English response.
