### ISSUE TITLE
Prompt Helper custom values not being used

### ISSUE THREAD

**Issue by Eyon42** [jerryjliu/llama_index#1324]
I tried to change the max_chunk_overlap, but it keep using the default value. This worked on a previous version, now i'm not seeing it work.

```python
 service_context = ServiceContext.from_defaults(
    prompt_helper=PromptHelper(
        max_input_size=4096, max_chunk_overlap=max_chunk_overlap, num_output=1024,
    ),
    chunk_size_limit=chunk_size_limit,
)

nodes = service_context.node_parser.get_nodes_from_documents(documents)
```

**Comment by pinsystem** [comment]
How did you find out that it keep using default value? I'm suffering the response truncated problem. just wondering these are connected.

**Comment by logan-markewich** [comment]
It's now preferred to not use the prompt helper, and instead set values in the service context directly
https://gpt-index.readthedocs.io/en/latest/core_modules/supporting_modules/service_context.html

For response truncation, you need to increase max_tokens on the LLM object
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21
