### ISSUE TITLE
Custom Output/Response Size Issues in PromptHelper

### ISSUE THREAD

**Issue by kindler-king** [jerryjliu/llama_index#1331]
Hi, 

I want to increase the response size from the default value as I noticed in many cases the response stops mid-sentence as if it ran out of tokens. It is understandable owing to the low default value of the num_output parameter.

![t](https://user-images.githubusercontent.com/53633591/234612060-465f2315-2c39-4032-a969-432504f4688e.PNG)

However, as seen in the above image this causes an error.
I tried removing `llm_predictor=llm_predictor, prompt_helper=prompt_helper` from the index definition and just made it

![image](https://user-images.githubusercontent.com/53633591/234612448-9a0bc2fd-3a6f-4603-a89b-3d198d38e998.png)

However, this raised an all new exception.
Any help as to how to fix this is successfully increase the response output size to get larger outputs.

**Comment by logan-markewich** [comment]
I think the docs you are looking at are outdated.

Check out the most recent here https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-fine-grained-control-over-all-parameters

**Comment by kindler-king** [comment]
You are absolutely right, I didn't notice I was referring to an outdated documentation. Solved the issue thanks to your note :D
