### ISSUE TITLE
This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by charanhu** [jerryjliu/llama_index#1332]
This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

**Comment by justinzyw** [comment]
chat model: llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.5, model_name="gpt-3.5-turbo", max_tokens=num_outputs))
text model:  llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.5, model_name="text-davinci-003", max_tokens=num_outputs))

**Comment by tkreuder** [comment]
Solution for me: https://github.com/OpenGVLab/Ask-Anything/issues/29#issuecomment-1633017648

**Comment by logan-markewich** [comment]
@justinzyw is correct. Although we also recently added our own LLM integration for OpenAI, so no need to worry about selecting the correct class anymore

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-changing-the-underlying-llm
