### ISSUE TITLE
StableLMPredictor is hard-coded for CUDA?

### ISSUE THREAD

**Issue by kechan** [jerryjliu/llama_index#1343]
I tried and failed at:

self.model.half().cuda()

during instantiation. I am trying this on a M2 Max so I need MPS. May not be a good idea to hardcode this. Not sure if the same will also fail for TPU.

**Comment by logan-markewich** [comment]
This has been replaced by our hugging face LLM

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-huggingface-llm
