### ISSUE TITLE
Token Usage Issues

### ISSUE THREAD

**Issue by virdi16** [jerryjliu/llama_index#1356]
I am trying to find the total token usage for creating index and query index both. 

But there are two parameters **_last_token_usage_** and _**total_token_usage**_ both are giving same response

Also if we use SimpleVectorIndex, we don't get any LLM token usage while creating index?

**Comment by logan-markewich** [comment]
Total token usage is the usage across the lifetime of the LLMPredictor in your app

Last token usage should be reset after every query I think?

And yes, index construction for a vector index only uses the embedding model, not the llm

**Comment by virdi16** [comment]
Thanks for sharing this.

I tested the two even my understanding is same for both of these, but somehow I was getting same value for both which confused me
