### ISSUE TITLE
Please support SQLAlchemy v2.

### ISSUE THREAD

**Issue by ryugonomura** [jerryjliu/llama_index#1357]
SQLAlchemy v2 is now supported from v0.0.149 of langchain.
Could you consider changing langchain==0.0.142 to 0.0.149 in setup_llama.py?
The following URL is a ticket for langchain for v2.

This issue is related to #1124.

https://github.com/hwchase17/langchain/pull/3310

**Comment by jerryjliu** [comment]
sounds good - noticed this was breaking our build a few days ago, we have an action item to fix :)

**Comment by jerryjliu** [comment]
should be supported via #1387 now
