### ISSUE TITLE
How to make the question answering system can accurately answer the documentation questions, but also avoid forced association for the questions that do not want to be closed

### ISSUE THREAD

**Issue by pythonmanGo** [jerryjliu/llama_index#1371]
def MixSerchGPT(prompt, datadir):
    cachejasonfile = datadir+ 'cache.json'

    try:
        max_input_size = 4096
        # set number of output tokens
        num_output = 1024
        # set maximum chunk overlap
        max_chunk_overlap = 256
        prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
        # define LLM
        llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=num_output))
        
        #llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="gpt-3.5-turbo-0301", max_tokens=num_output))
   
        service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
        jasonfile = datadir + "index.json"
        print(jasonfile)
        new_index = GPTSimpleVectorIndex.load_from_disk(jasonfile, service_context=service_context)  
        # response = new_index.query(prompt, verbose=False)

"
        prompt="\n{"+prompt+"}\n If the question is obviously not relevant to datart, please use the GPT answer directly to avoid misunderstandings."

        response = new_index.query(prompt, similarity_top_k=1)
        print(prompt)
        cacheData[prompt] = str(response)
        with open(cachejasonfile, "w+",encoding='utf-8') as f:

            json.dump(cacheData, f, ensure_ascii=False, indent=4)

    except Exception as e:
        print("llm  error" + str(e))
    print("out MixSerchGPT ********* ")
    responsestring=str(response).replace("\n\n","\n")
    return responsestring

过加载本地文档的方式实现了本地问答功能，但是出现了关联不正确的问题，导致回答不准确。
例如：我输入“prompt” ，“你在干啥”
responsestring会返回：llama_index是一个问答平台，可以用来创建和使用问答等。

希望的回答：我输入“prompt” ，“你在干啥”
系统判断此问题与llama_index无关，则直接调用chatGPT进行聊天，或者返回指定字符串“我是一名llama_index专家，该问题与llama_index无关，请向我提问关于llama_index的问题，谢谢。”
目前主要问题是，无论我问的问题是否与llama_index相关，程序会错误地关联文档和代码，导致一些回答难以理解。如何修改程序，以便在文档不相关的情况下，不要强制进行关联导致对用户误导。

**Comment by Disiok** [comment]
For building a chatbot, you might want to take a look at https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html

**Comment by pythonmanGo** [comment]
@Disiok

In fact, I've already set up a conversation with the document.  But when a user's conversation deviates from an existing document, I want to control chatGPT's answers.  Develop a reliable document question and answer system that responds to information not included in the document by simply saying "don't know" or using chatGPT's large model capabilities to engage in a conversation directly away from the document, rather than making far-fetched forced associations with existing documents that lead to misleading answers. 


such as：

The method of over-loading the local document realizes the local question and answer function, but the problem of incorrect association occurs, resulting in inaccurate answer.  
For example: I type prompt： "what are you doing"  
responsestring returns:“ llama_index is a question-and-answer platform that can be used to create and use questions and answers, etc.  ”
 
I typed prompt： "What are you doing?"  
If the system determines that the problem is unrelated to llama_index, it directly calls chatGPT to chat, or returns the specified string： "I am an expert on llama_index and this problem is unrelated to llama_index. Please ask me about llama_index, thank you."  
The main problem at the moment is that regardless of whether the question I'm asking is related to llama_index or not, the program is incorrectly associating the document with the code, resulting in some answers that are difficult to understand.  How to modify the program so that it does not mislead users by forcing associations when documents are not relevant.

**Comment by iraadit** [comment]
Hi @pythonmanGo

Did you find a solution?

**Comment by pythonmanGo** [comment]
@iaalm @Disiok  updated the version, but it still doesn't work. Maybe the query function should set a confidence value for the query result, which reflects how reliable the current answer is or how relevant it is to the local document. A range of confidence levels is then given so that the developer can decide whether to trust the results returned by the query function.

**Comment by iaalm** [comment]
Maybe you can try adding `if the previous document is not related to the document, just say "I don't know"` to your prompt. This works well for some of my scenarios. I guess GPT may not know what is `use the GPT answer directly` .

**Comment by pythonmanGo** [comment]
i  have  add the  prompt like  “if the previous document is not related to the document, just say "I don't know”
the result is not only  gpt  not anwser  "i do not konw about  xxx ",
but also  nomal answer Deviate  
that  so  oops
seems  llama_index is not  ounder control

**Comment by logan-markewich** [comment]
I would recommend using a chat engine or data agent for this use case

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/root.html

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
