### ISSUE TITLE
Multiple token usage log statements 

### ISSUE THREAD

**Issue by Sparetavns** [jerryjliu/llama_index#1384]
### Using latest release from the main branch. 

<img width="869" alt="Screenshot 2023-04-30 at 12 11 34 PM" src="https://user-images.githubusercontent.com/89649257/235339588-f73e7127-245d-4e65-abe3-4f6205345d96.png">

<img width="855" alt="Screenshot 2023-04-30 at 12 11 21 PM" src="https://user-images.githubusercontent.com/89649257/235339599-87709b28-de2d-460e-9210-b326305ff9ba.png">

Duplicate logs in both the cases , with optimiser and w/o optimiser. it is just the logging issue or token are evaluated two times i.e charging twice for every query ?   This was not the case with llama_index-5 which we were using earlier. 

```
INFO:gpt_index.token_counter.token_counter:> [get_response] Total LLM token usage: 1809 tokens
INFO:gpt_index.token_counter.token_counter:> [get_response] Total embedding token usage: 0 tokens
INFO:gpt_index.token_counter.token_counter:> [get_response] Total LLM token usage: 1809 tokens
INFO:gpt_index.token_counter.token_counter:> [get_response] Total embedding token usage: 0 tokens
```

**Comment by logan-markewich** [comment]
The `get_response` and `optimize` duplicates definitely seem like a bug, I'll look into it. Otherwise though, yea there's a bit more logger for different steps now.

**Comment by Disiok** [comment]
Looks like should be fixed now.
