### ISSUE TITLE
Where can I find the MultiStepQueryEngine

### ISSUE THREAD

**Issue by raywgs** [jerryjliu/llama_index#1385]
I can't find the MultiStepQueryEngine inside the llama_index dependency.

I pip installed llama_index

**Comment by jerryjliu** [comment]
@raywgs which version are you on / how are you trying to import MultiStepQueryEngine?

**Comment by Disiok** [comment]
@raywgs  right now our 0.6.0 is in pre-release, use `pip install llama-index --pre` to install it.
