### ISSUE TITLE
How can I use Conversational memory with llama-index?

### ISSUE THREAD

**Issue by AkshitChugh787** [jerryjliu/llama_index#1386]
`from langchain.chains.conversation.memory import ConversationBufferWindowMemory`
`openai_llm = OpenAI(temperature=0, model_name="text-davinci-003")`
 `conversational_memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=5,
    return_messages=True
)`
`llm_predictor = LLMPredictor(openai_llm)`
`service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, chunk_size_limit=4096)`
`index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)`

How to use my conversational_memory for this piece of code so that I can maintain history of the conversation from the bot?

Thanks

**Comment by jerryjliu** [comment]
LlamaIndex at the moment defines indexes/query interface over your data - you can use these indexes as a memory module actually.

So by default you can use llamaindex as a memory module + tool into an outer framework like langchain agents: https://gpt-index.readthedocs.io/en/latest/how_to/integrations/using_with_langchain.html

We might have more "in-house" support for memory coming soon though!

**Comment by sura2k** [comment]
@jerryjliu Any update on this?
