### ISSUE TITLE
AttributeError: 'GPTVectorStoreIndex' object has no attribute 'as_query_engine'

### ISSUE THREAD

**Issue by papyon2016** [jerryjliu/llama_index#1608]
Hello,
I get this error under Windows 10, Anaconda environment after I did a normal `pip install llama-index`
The code:
```
index = GPTVectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("something...")
```
Note that this works fine:
```
index = GPTVectorStoreIndex.from_documents(documents)
response = index.query("something...")
```
I can't figure out why? The documents all state I should use `as_query_engine`.

**Comment by logan-markewich** [comment]
The latest version of the docs refer to the alpha  version of 0.6.0

To install the pre-release 0.6.0.alpha1, you need to do `pip install --upgarde llama-index==0.6.0.alpha1`

Or, you can view the older docs here 

https://t.co/8SVqjJNXQp

**Comment by harishkm83** [comment]
After upgrading to alpha version, I'm able to save the index, but not able to load from it. Getting the below error.  type object 'GPTVectorStoreIndex' has no attribute 'load_from_disk'
Do we have a new way to load index from saved file? below is the line throwing error.
index = GPTVectorStoreIndex.load_from_disk('CustomData.json', service_context=service_context)

**Comment by jerryjliu** [comment]
@harishkm83 yeah we do, check out https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-save-the-index-for-future-use
