### ISSUE TITLE
[Enhancement] update OpenAI API parameter name "engine" -> "model"

### ISSUE THREAD

**Issue by habaneraa** [jerryjliu/llama_index#1745]
OpenAI has deprecated the term ‘engine’ in favor of ‘model’. 

See [this post](https://community.openai.com/t/api-update-engines-models/18597):

> Most people already use these terms interchangeably, and we consistently hear that ‘model’ is more intuitive. If you’ve used a fine-tuned model, then you’re already familiar with using ‘model’ instead of ‘engine’ when making an API request. Engine listing is also being replaced by Model listing, which will consolidate both base and fine-tuned models in a single place.
We will maintain backward compatibility, but recommend updating your implementation as soon as you can to prevent future confusion.

OpenAI are still supporting "engine" anyway.

It seems like only `llama_index.embeddings.openai` needs to be updated but I'm not sure if there are other code that need to be updated ;)

**Comment by Disiok** [comment]
Would love a contribution on this! Let use know if we can help review.
