### ISSUE TITLE
how do I split a large pdf?

### ISSUE THREAD

**Issue by HananInfiniGrow** [jerryjliu/llama_index#1746]
I am running `documents = SimpleDirectoryReader(directory_path).load_data()` on a single 20MB PDF file.
I would expect there would be a parameter to tell it to split the documents into chunks but I could not find it.
Currently a single large document is retrieved which causes the rest of the pipeline to break. 
What is the solution?

**Comment by Disiok** [comment]
Hey, did you parse the Document into  Node objects? You can read more in: https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html

**Comment by HananInfiniGrow** [comment]
Thanks. Do you use the openAI key to download the model or do you do everything via the API? can I choose?
