### ISSUE TITLE
can anyone explain in simple terms, Fundamentally how llama_index works?

### ISSUE THREAD

**Issue by charanhu** [jerryjliu/llama_index#1749]

**Comment by Disiok** [comment]
Hey @charanhu we have pretty comprehensive documentation at https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html 

Anything you'd like use to clarify?

**Comment by logan-markewich** [comment]
Not sure entirely what you mean here, we don't have a CSV agent. We do have a pandas query engine, which reads `df.head()` and a user query, and generates/executes a python data frame function, and then returns a result.

Feel free to reach out on discord if you have other questions!
