### ISSUE TITLE
what is train_eval.json and dev_eval.json? is there any ml's classical training happening?

### ISSUE THREAD

**Issue by charanhu** [jerryjliu/llama_index#1750]

**Comment by logan-markewich** [comment]
There's no ML training happening here. Llama Index just cleaverly inserts your documents as context when asking LLMs questions. This grounds the response from the LLM and reduces hallucinations, while giving to access to specific information to answer questions

Check out the docs for more info! https://gpt-index.readthedocs.io/en/stable/

**Comment by logan-markewich** [comment]
@charanhu Context just means the text from the documents you indexed 👍
