### ISSUE TITLE
Models and Temperature Changes for Keyword Extraction

### ISSUE THREAD

**Issue by takanomizuki** [jerryjliu/llama_index#1754]
Sorry, I can use the code below to change the model when responding to a query.

It looks like the table index uses daVinci-003 by default, but how do I change the model for keyword extraction during indexing and querying?

This is not talking about changing the mode to symple or RAKE.

Also, it would be helpful to be able to change the temperature as well, as I would like to expand the keyword selection.

I personally feel that using morphological analysis would be cheaper and more accurate.

llm_predictor = LLMPredictor(
        llm=ChatOpenAI(temperature=0.0, max_tokens=500, n=1, model_name="gpt-3.5-turbo")
    )

**Comment by Disiok** [comment]
You can change the model for keyword extraction by passing it in via a `ServiceContext` when constructing the index.

**Comment by takanomizuki** [comment]
I am sorry, but I personally did not understand the idea of passing a. I tried to incorporate my own keyword extraction function in a custom class called GptExtractKeywordTableIndex, but it seemed too difficult to control the function to be added to the index.

As shown in the list below, we used a Japanese keyword extractor to extract keywords in advance, added the pre-extracted keywords to a text file, added brackets and other markers to the keywords in the text to be indexed as a preprocessing step, and added simple_extract_keywords by modifying the regular expression of the keywords function.

I believe this will allow us to extract the keywords that we add to our own list and have them added to the index. However, I have not yet tried this because it takes me a long time to personally extract keywords from a large number of PDFs, so perhaps this approach needs improvement.

会計監査人 64.90247631845992
公認会計士 40.088468874738
監査役 32.49615361854384
公認会計士 32.4037034920393
監査法人 31.543421455299043
監査役 19.66965517449872
監査事業 10.60990001063923
アカウンティング・エンゲージメント 9.929252758940619
ビジネス 6.928203230275509
エグゼクティブ 6.900979901373617
6.0
会計監査人の補足説明 5.514658418571622
