### ISSUE TITLE
run llama_index  with locally llm that have compatible OpenAI's API

### ISSUE THREAD

**Issue by shengkaixuan** [jerryjliu/llama_index#1772]
can llama_index be used with locally hosted model services that simulates OpenAI's API
tools like 
https://github.com/go-skynet/LocalAI
https://github.com/keldenl/gpt-llama.cpp

**Comment by shengkaixuan** [comment]
> Yes, take a look at https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model

hi, what does this code do ,how to use it in llama.cpp ,  also checkout the issue :https://github.com/abetlen/llama-cpp-python/issues/129#issue-1689705372
`pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})`

**Comment by langchain4j** [comment]
Hi, thanks a lot for your hard work!
Could you please add support for [LocalAI](https://github.com/go-skynet/LocalAI)?
