### ISSUE TITLE
Defining custom prompt not working as expected

### ISSUE THREAD

**Issue by harishkm83** [jerryjliu/llama_index#1812]
Based on the sample in the link https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html#example
here is my code snippet.
I'm using UnstructuredURLLoader to input a list of urls as source.
using llama-index==0.6.0.alpha3

loader = UnstructuredURLLoader(urls=urls, continue_on_failure=False, headers={"User-Agent": "value"})
documents = loader.load()
context_str = "You are a technical support chatbot named TestBot. Give step by step instructions. Provide source for the answers always."
query_str = "whats your name?"
storage_context = StorageContext.from_defaults()
service_context=InitializeServiceContext();
index = GPTVectorStoreIndex.from_documents( documents,storage_context=storage_context,service_context=service_context )
#index.storage_context.persist()

QA_PROMPT_TMPL = (
    "We have provided context information below. \n"
    "---------------------\n"
     "{context_str}"
    "\n---------------------\n"
    "Given this information, and no prior knowldge, please answer the question: {query_str}\n"
    )
QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_TMPL)
query_engine = index.as_query_engine(text_qa_template=QA_PROMPT)

with the above code, it not taking the custom prompt. the bot completely misses the context explained.
In the sample code snippet, setting context_str is not explained. 
**1. please suggest on how I can make the context prompt work.
2. Is GPTVectorStoreIndex right one to use for KB articles Q&A? 
3. the answers from the bot mostly looks made up. is there any way we can make sure, it will answer only facts, and don't make up stuff.
4.  any pointers on how I can direct the bot, if keyword = XYZ, use ABC node for answers?**

**Comment by Disiok** [comment]
Hey @harishkm83, based on the code you provided, you never actually passed the additional "context" into the query engine.

When you write
```
QA_PROMPT_TMPL = (
"We have provided context information below. \n"
"---------------------\n"
"{context_str}"
"\n---------------------\n"
"Given this information, and no prior knowldge, please answer the question: {query_str}\n"
)
```

It just sets up the template, and does not actually pass the `context_str` in. You can read more about `python template string` about this. In fact, `context_str` is automatically filled in by the query engine.

To add information into the prompt, just directly it put it into the string template:

**Comment by Disiok** [comment]
Also, if you want to build a chatbot, best to take a look at: https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html

**Comment by Carlo88** [comment]
@harishkm83 Hello! Did you solve the "issue" ? I'm also trying to understand how to do that. 
I found this example: https://gpt-index.readthedocs.io/en/stable/how_to/customization/custom_prompts.html and it works, but I am trying to modify this: https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb but now luck, I don't get the reason.

Thanks and have a nice day! Carlo

**Comment by Carlo88** [comment]
Hey @HerbiePorter how are you! :)
I found this blog post, very insteresting: https://blog.langchain.dev/tutorial-chatgpt-over-your-data/

I cloned it and I modified the QA_PROMPT prompt saying that he only hah to answer to questions related to the context. It is working !!! 🚀
