### ISSUE TITLE
Update simplevector index

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#1849]
How to update simplevector index if some new files are added on google drive folder please help thanks in advance

import os
import pickle
from langchain import OpenAI
from flask import Flask, render_template, request
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from llama_index import LLMPredictor, GPTSimpleVectorIndex, PromptHelper, ServiceContext, download_loader,MockLLMPredictor,MockEmbedding,Document
from langchain.chat_models import ChatOpenAI

os.environ['OPENAI_API_KEY'] = 'my key'

def authorize_gdocs():
    google_oauth2_scopes = [
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/documents.readonly"
    ]
    cred = None
    if os.path.exists("token.pickle"):
        with open("token.pickle", 'rb') as token:
            cred = pickle.load(token)
    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("client_secrets.json", google_oauth2_scopes)
            cred = flow.run_local_server(port=0)
        with open("token.pickle", 'wb') as token:
            pickle.dump(cred, token)

authorize_gdocs()

GoogleDriveReader = download_loader('GoogleDriveReader')
folder_id = '1h02mlinlWRZdxjf1WotZ3GERNDSoGCmk'
loader = GoogleDriveReader()
documents = loader.load_data(folder_id=folder_id)

# Define LLM
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo"))

# Define prompt helper
max_input_size = 4096
num_output = 512
max_chunk_overlap = 20
chunk_size_limit = 600
prompt_helper = PromptHelper(max_input_size, num_output,max_chunk_overlap,chunk_size_limit=chunk_size_limit)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)

 index.save_to_disk('index1.json')

index = GPTSimpleVectorIndex.load_from_disk('index1.json')

**Comment by Disiok** [comment]
You can use `index.insert(document)`

**Comment by vishalp-simplecrm** [comment]
I have inserted some new docs to the folder , want to create index only for newly added files not from scratch

can you put some more details

**Comment by vishalp-simplecrm** [comment]
> You can use `index.insert(document)`

How can I get response in stream format as given by chatgpt
