### ISSUE TITLE
Multi topic Best practice

### ISSUE THREAD

**Issue by DanSan23** [jerryjliu/llama_index#1852]
I'm working on building an index to efficiently query documents. With a single document, everything seems to work fairly well, but as the number of documents increases, the performance degrades. Can you tell me the best practices to deal with this scenario? The biggest problems occur with ambiguous queries where the answer could reside in several different documents.

**Comment by Disiok** [comment]
I think this might be a relevant example to take some inspiration from: https://github.com/jerryjliu/llama_index/blob/main/examples/composable_indices/city_analysis/City_Analysis-Unified-Query.ipynb

tldr: you can define sub-index for each document (or collection of documents), then define a (LLM powered) router to automatically choose between the different sub-indices.
