### ISSUE TITLE
confused about requirement to recreate original service context exactly when re-loading index from disk

### ISSUE THREAD

**Issue by maspotts** [jerryjliu/llama_index#1974]
Hi: I'm a little confused by the new (0.6.0) API re. creating and then re-loading an index.  Specifically this comment:

> NOTE: If you had initialized the index with a custom ServiceContext object, you will also need to pass in the same ServiceContext during load_index_from_storage.

seems to be saying that if I create a custom service context then I must recreate that exact same service context every time I reload the index.  In fact, I am getting the same response (to any given query) whether I recreate the original service context and pass it to load_index_from_storage() or not.  Also, per pre-0.6.0 examples I had the impression that the service context could be deliberately altered: eg. I could create an index with (notionally) gpt-3.5-turbo, but then load it with gpt-4.  That works (doesn't throw an exception, even though the service contexts are different), but also doesn't seem to affect the responses.  Am I missing something obvious?  Thanks!

**Comment by Disiok** [comment]
It doesn't have to be the same one. We meant that save/load does not preserve the original service context. 
Upon loading, it would use the default one, unless explicitly passed in the desired service context.

**Comment by maspotts** [comment]
Thanks: that was my assumption, but I appreciate having it confirmed!

**Comment by maspotts** [comment]
Do you mind clarifying the various ways I *think* I can specify a service context?

  1. I know I can specify it when I create the index, eg:
        `index = GPTVectorStoreIndex.from_documents(documents, service_context = service_context)`

  2. I believe I can also specify it when I load the index, eg:
       `index = load_index_from_storage(storage_context, service_context = service_context)`

  3. I'm hoping I can also specify it when I query the index, but I'm not sure where that might be (since it would passed in as a kwarg I can't figure out if it's used or not!): are either of these uses correct?:
       `retriever = index.as_retriever(retriever_mode = 'embedding', service_context = service_context)`
       `query_engine = RetrieverQueryEngine.from_args(retriever, response_mode = 'tree_summarize', service_context = service_context)`

Thanks!

**Comment by logan-markewich** [comment]
Those are all @maspotts  correct, but tbh I would just a global service context

```
from llama_index import set_global_service_context

set_global_service_context(service_context)
```
