### ISSUE TITLE
How can I create a index that allows me to search across csv and txt data?

### ISSUE THREAD

**Issue by raywanb** [jerryjliu/llama_index#1988]
How can I create an index that allows me to search and give results based on the different data sources accurately? 
Right now, just using a GPTVectorStore doesn't give me the correct results from the csv file when I ask it to query the average data for a column.

**Comment by Disiok** [comment]
vector store index only retrieves best matched chunks of data, so won't be able to handle `average` query well.

**Comment by logan-markewich** [comment]
Create a query tool per index and use a data agent 👍🏻 

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
