### ISSUE TITLE
GraphToolConfig is gone

### ISSUE THREAD

**Issue by ralphscheu** [jerryjliu/llama_index#1995]
Hi, thank you for this awesome project!
After upgrading to 0.6.0, I noticed that while https://github.com/jerryjliu/llama_index/blob/6330d3522d38a487b833e4debee4b274ba7362e2/llama_index/langchain_helpers/agents/__init__.py still mentions `GraphToolConfig`, it does not exist anymore in https://github.com/jerryjliu/llama_index/blob/v0.6.0/llama_index/langchain_helpers/agents/tools.py

I am investigating it myself right now but not yet sure how to migrate my code (Chatbot Tutorial) to the new version.

Thanks for any pointers!

**Comment by jerryjliu** [comment]
@ralphscheu should be unified under LlamaIndexTool - hopefully that works!
