### ISSUE TITLE
Improve local llama support

### ISSUE THREAD

**Issue by matthoffner** [jerryjliu/llama_index#2117]
I'm finding I have to pass `service_context` for literally everything to work, and if I don't I get a warning about an OpenAI key. Could we make it so its more friendly to local Llama users?

**Comment by Disiok** [comment]
@matthoffner Thanks for raising this. Easiest is probably to allow user to set global defaults for the service context. We can look into this!

**Comment by matthoffner** [comment]
@doso-beta https://soundcloud.com/trumpectetera/263536061606496a?si=65bfb5e0fc8f44198c88a4040c05fc08&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
