### ISSUE TITLE
resolve ServiceContext

### ISSUE THREAD

**Issue by womenfull** [jerryjliu/llama_index#2152]
I have part of WebAPI application that I want to move to separate project as class library.
It is common base structure that almost every app has so idea is to make it easy shareable.
Application type is:
ASP.NET Core Web Application / .NET Framework - ASP.NET Core 2.0 / Web API

What I have done in that direction is created a project named Core and moved those shared elements there, including Base Entities (e.g. User, Settings, etc), CoreContext, UnitOfWork, Generic Repository, BaseRepositories,...

In the Main project of app there are others Entities, AppContext that inherits CoreContext, more Repositories, and all Controllers, ...

I was able to build the app but when starting it get the following error:

**Comment by Disiok** [comment]
Not sure what the question is here?
