### ISSUE TITLE
How to migrate index files generated in 0.5.x to 0.6.x?

### ISSUE THREAD

**Issue by zijie0** [jerryjliu/llama_index#2177]
We save and load index files using following code in 0.5.x:

```
documents = SimpleDirectoryReader("my_folder").load_data()
index = GPTSimpleVectorIndex.from_documents(documents)
index.save_to_disk("index.json")

# load from index.json
index = GPTSimpleVectorIndex.load_from_disk("index.json")
```

But in 0.6.x version, there's no `load_from_disk` method. How can we load the old `index.json` file and convert it to the new storage format? We tried to use `load_index_from_storage` directly but it apparently could not find `docstore` and `index_store` files.

We could not find any migration guide for this. Could anyone help with this problem?

**Comment by Disiok** [comment]
Hey @zijie0, since 0.6.0 changes are fairly big, we haven't gotten around to making a migration script.
Would it be possible for you to re-index the files?

**Comment by zijie0** [comment]
@Disiok Yes, we can re-index the files for now. But it would take several hours and might hit the request rate limit in Azure OpenAI. I think that other users may also encounter this problem.

By the way, what are the benefits of upgrading to 0.6.x? I could not find detailed release notes 😂.

**Comment by zijie0** [comment]
Hey @DaytimeAH , you can try to cancel the task by Ctrl + C to get the callstack of the program(or use other techniques). I also met similar problem and find out that the program entered infinite loop when calculating chunk splits. It might be a bug in 0.6.x but I didn't have time to investigate further. In my case, I just removed very long text sequences in documents to avoid this problem.

**Comment by DaytimeAH** [comment]
Hi @zijie0 thanks for the info. i think removing text is really not a long-term solution.😂 
Hi @Disiok Can you help provide some detailed?  Thank you in advance
