### ISSUE TITLE
Not getting accurate answers from documents used for Chatbot

### ISSUE THREAD

**Issue by gauravsinghrawal** [jerryjliu/llama_index#2188]
Hi Team,

I created a Chatbot following this tutorial. I used 5 documents for indexing, but I am receiving inaccurate answers for most of the questions. The chatbot performs better for general questions based on documents but start to give random/inaccurate answers when trying to ask to follow up questions. I am exploring the option of building a chatbot for my team which could utilize 100s of documents and provide accurate answers most (if not all) the times. 

Are there any best practices or improvement approaches/ any other examples, which can be explored to make this better?

Thanks.

**Comment by Disiok** [comment]
which tutorial are you looking at? We recommend this one for building a chat bot:
https://gpt-index.readthedocs.io/en/latest/guides/tutorials/building_a_chatbot.html

**Comment by gauravsinghrawal** [comment]
Hi,

Thanks for your reply.

I am using the same tutorial mentioned. Almost all of it the same way but not getting the desired behaviour.

Thanks.

**Comment by gauravsinghrawal** [comment]
One of the difference being that I am using separate readers like PDfFReader, CSVReader etc. for different type of files. Not sure if that makes any difference in the way indexes are created and searched later.
