### ISSUE TITLE
Need Clarity regarding workflow

### ISSUE THREAD

**Issue by nazkhan-8451** [jerryjliu/llama_index#2218]
```
# max LLM token input size
max_input_size = 1024
# set number of output tokens
num_output = 256
# set maximum chunk overlap
max_chunk_overlap = 20

prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

documents = SimpleDirectoryReader('/your/pdf/location/').load_data()

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embedding_llm,
    prompt_helper=prompt_helper
)

index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)

index.save_to_disk('embedding.json')

index = GPTSimpleVectorIndex.load_from_disk('embedding.json',service_context=service_context)

query = "question about embedded document"

answer = index.query(query)
```

1. Is there a limitation about how many files/ size for `documents`?
2. Does `max_input_size` and `num_output` depends on LLM? What are values for text-davinci-003 and GPT-4?
3.  `index` is a vector database. When we save it in json format, we save it as a dictionary. Can we save it as a database?
4. When we use `load_from_disk` is there a memory limitation? Do we load in RAM?
5. `answer` makes api calls to OpenAPI. During this what information is sent and received? I am guessing some nodes are parsed (like k=3 or 5) from index and sent to OpenAI. How do we select these nodes?

**Comment by Disiok** [comment]
1. no specific limits, but speed and quality of answer might suffer with more documents
2. you can use default values from the LLM by not setting them
3. you can choose different vector DBs to use, the simple vector store is meant for quick experimentation and saving to disk
4. yes, the simple vector store is stored in memory, so is limited by RAM
5. yes, the best matched text from best matched nodes are chosen and sent to model API for synthesis.

**Comment by sudokhan112** [comment]
5. When we are selecting 3 nodes for k=3, what algorithm is used to select these nodes?

**Comment by sudokhan112** [comment]
3. If we choose a different db and save as json, do we save that as a db? then when we load it, it's not limited by RAM like any other database?

**Comment by logan-markewich** [comment]
5. Just cosine similarity, unless you are using a vector db integration (in which case, it's up to that db)

3. dedicated Vector dbs are probably more efficient with memory. For hosted dbs, check out weaviate or pinecone. For self hosted, check out qdrant or chroma
