### ISSUE TITLE
Mac OS X ImportError: cannot import name 'GPTChromaIndex' from 'llama_index' (.../lib/python3.10/site-packages/llama_index/__init__.py)

### ISSUE THREAD

**Issue by PritchardAlexander** [jerryjliu/llama_index#2238]
I've tried installing via pip, pip3, and conda at this point as well as creating a brand new virtual environment for python 3.10 but I eventually hit this error every single time. My programs leveraging llama_index are failing to run.

**Comment by Disiok** [comment]
Hey, we recently released 0.6.0 which changed the API for vector store related indices. Please take a look: https://gpt-index.readthedocs.io/en/stable/

Should be quick to update!

**Comment by Disiok** [comment]
Alternatively you can downgrade to latest `0.5.x`

**Comment by PritchardAlexander** [comment]
Hey @Disiok thanks for responding to me so rapidly! I was actually able to use this project as a cross-reference and for some reason everything worked out of the box when I went through and ran the flask_react project:

base application: https://github.com/logan-markewich/llama_index_starter_pack

Install conda

cd into the flask_react directory

Run the commands:

conda create --name llama_index python=3.11
pip install -r requirements.txt



 1001  cd ~/Downloads/llama_index_starter_pack-main/flask_react 
 1002  conda create --name llama_index python=3.11
 1003  pip install -r requirements.txt
 1004  sh launch_app.sh 
 1005  python3 Demo.py
 1006  pip install trafilatura
 1007  python3 Demo.py

This is its Requirements.txt:

Flask==2.2.3
Flask-Cors==3.0.10
langchain==0.0.128
llama-index==0.5.4
PyPDF2==3.0.1

I don't know if it's wildly out of date or anything like that, but it works for getting the flask_react project running as well as our local Demo which had already been setup.

**Comment by Disiok** [comment]
Ya this uses an older version of the library `llama-index==0.5.4`
We still need to update it to the latest 0.6.0
