### ISSUE TITLE
How can I search for local documents without using OpenAI?

### ISSUE THREAD

**Issue by LexusM** [jerryjliu/llama_index#2240]
**I'd like to perform a search over my local documents without any connection to OpenAI API using this example code:**

_from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader('data').load_data()
index = GPTVectorStoreIndex.from_documents(documents)
response = index.query("Summarize the documents.")_

**unfortunately got an error like this:**

_File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__   Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)_

**any idea how to use llama_index for local documents search without OpenAI?**

**Comment by shubihu** [comment]
@LexusM https://shubihu.github.io/2023/05/08/%E5%9F%BA%E4%BA%8Echatglm-6b%E7%9A%84%E6%9C%AC%E5%9C%B0%E7%9F%A5%E8%AF%86%E9%97%AE%E7%AD%94/

**Comment by logan-markewich** [comment]
You'll need to setup both an embed model and an LLM

LLM
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced

Embed Model
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#local-embedding-models
