### ISSUE TITLE
How to print the final prompt after all processing

### ISSUE THREAD

**Issue by sid8491** [jerryjliu/llama_index#2450]
I want to print the final prompt which is being sent to the LLM after indexing, searching and all the processing has finished.
Is there any way to do that?

After searching relevant chunks from the given document, it must append those chunks with the given prompt to construct a final prompt.

**Comment by sid8491** [comment]
We can use DebugHandler:

https://github.com/jerryjliu/llama_index/blob/main/examples/callbacks/LlamaDebugHandler.ipynb

**Comment by Falven** [comment]
Not sure how you did it, this just prints a trace for me. Would like to be able to see the full prompt with the variable replacements and after response modes are evaluated too.
