### ISSUE TITLE
Can not import name 'GPTOpensearchIndex'

### ISSUE THREAD

**Issue by ZohaibRamzan** [jerryjliu/llama_index#2454]
I am trying to use llama_index with opensearch but failing to import the 'GPTOpensearchIndex' using below code:
`from llama_index.indices.vector_store import GPTOpensearchIndex`

It gives me this error "ImportError: cannot import name 'GPTOpensearchIndex' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)"

Caan you help??

**Comment by jerryjliu** [comment]
thanks for surfacing @ZohaibRamzan - we'll fix the notebook here, GPTOpensearchIndex is deprecated
