### ISSUE TITLE
'GPTListIndex' object has no attribute 'root_index'

### ISSUE THREAD

**Issue by robchen123** [jerryjliu/llama_index#2486]
Hi,
I'm tring to run the codes of "How to build a chatbot" in the tutorials。

```
graph = load_index_from_storage(
    root_id=root_id,
    service_context=service_context,
    storage_context=storage_context
)

custom_query_engines[graph.root_id] = graph.root_index.as_query_engine(
    response_mode='tree_summarize',
    verbose=True,
)
```

then I got an error:
'GPTListIndex' object has no attribute 'root_index'

how to fix it?

**Comment by juancalric** [comment]
I'm having the same issue but with `AttributeError: 'KeywordTable' object has no attribute 'root_id'` have you solve it?

**Comment by Disiok** [comment]
`graph` should be a `ComposableGraph` object, and not a `GPTListIndex`. Maybe double check your code.
