### ISSUE TITLE
ImportError: cannot import name 'StorageContext' from 'llama_index' on 0.6.1

### ISSUE THREAD

**Issue by afewell** [jerryjliu/llama_index#2499]
This looks to be the same error as #1388 except I am already running a newer version than what resolved that one. Just in case I backported to 0.6.0a3 which was the resolution in 1388, but, still had the same error.

**Comment by jerryjliu** [comment]
Hey @afewell, not sure why this is happening. Does `from llama_index.storage.storage_context import StorageContext` work?

**Comment by alikalik9** [comment]
Same issue here. from llama_index.storage.storage_context import StorageContext worked though

**Comment by logan-markewich** [comment]
This should be fixed now!

**Comment by Chukwuebuka-2003** [comment]
it doesn't work

**Comment by logan-markewich** [comment]
@Chukwuebuka-2003 this issue is nearly 8 months old 😅

In v0.10.x it's `from llama_index.core import StorageContext`

v0.10.x was a bit if a change, please check out the docs

**Comment by yangboz** [comment]
> @Chukwuebuka-2003 this issue is nearly 8 months old 😅
> 
> In v0.10.x it's `from llama_index.core import StorageContext`
> 
> v0.10.x was a bit if a change, please check out the docs

finally.
