### ISSUE TITLE
ValueError: No existing llama_index.storage.kvstore.simple_kvstore found at ./storage/docstore.json.

### ISSUE THREAD

**Issue by evrocha** [jerryjliu/llama_index#2518]
I get this error using the Storage Class: 
ValueError: No existing llama_index.storage.kvstore.simple_kvstore found at ./storage/docstore.json.

Code below: 
storage_context = StorageContext.from_defaults(persist_dir="./storage/")
index = load_index_from_storage(storage_context,  service_context=cls.get_service_context())
index.storage_context.persist(persist_dir="./storage/") 

Why?

**Comment by jerryjliu** [comment]
@evrocha any chance you can share the full notebook? we can help repro. feel free to hop in the discrod

**Comment by a6225301** [comment]
Same problem on the window platform, when implement the official example. I think that the path may be cause.

**Comment by a6225301** [comment]
您好，您的邮件我已收到，我会尽快回复。

**Comment by a6225301** [comment]
Anyway, have you missed the code of "index.storage_context.persist()"

**Comment by evrocha** [comment]
This is the code: 
documents = SimpleDirectoryReader(directory_path).load_data()
service_context=cls.get_service_context()
storage_context = IndexMain.get_storage_context()
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context, prompt_helper=cls.prompt_helper)
index.storage_context.persist(persist_dir=".\Arquivos")

"\Arquivos" folder is equal to directory_path, actually. Is this correct?

**Comment by w2lker** [comment]
I have the same issue. Then I run the script manually — it works fine, base restores, but if I run it via Apache WSGI — I get those errors.

**Comment by ayush20501** [comment]
> This is the code: documents = SimpleDirectoryReader(directory_path).load_data() service_context=cls.get_service_context() storage_context = IndexMain.get_storage_context() index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context, prompt_helper=cls.prompt_helper) index.storage_context.persist(persist_dir=".\Arquivos")
> 
> "\Arquivos" folder is equal to directory_path, actually. Is this correct?

have you solve the issue?

**Comment by vince015** [comment]
I am running mine in AWS Lambda container and encountered this error:

```bash
[ERROR] ValueError: No existing llama_index.storage.kvstore.simple_kvstore found at /tmp/index/docstore.json.
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/main.py", line 26, in <module>
    storage_context = StorageContext.from_defaults(persist_dir=index_dir)
  File "/var/task/llama_index/storage/storage_context.py", line 57, in from_defaults
    docstore = docstore or SimpleDocumentStore.from_persist_dir(persist_dir)
  File "/var/task/llama_index/storage/docstore/simple_docstore.py", line 48, in from_persist_dir
    return cls.from_persist_path(persist_path, namespace=namespace)
  File "/var/task/llama_index/storage/docstore/simple_docstore.py", line 64, in from_persist_path
    simple_kvstore = SimpleKVStore.from_persist_path(persist_path)
  File "/var/task/llama_index/storage/kvstore/simple_kvstore.py", line 69, in from_persist_path
    raise ValueError(f"No existing {__name__} found at {persist_path}.")
```

Here's my code

```python
index_dir = "/tmp/index"
storage_context = StorageContext.from_defaults(persist_dir=index_dir)
index = load_index_from_storage(storage_context)
```

**Comment by evrocha** [comment]
This solved my probem: vectorstore = Chroma.from_documents(documents, embedding , persist_directory='.chroma\\index\\')

**Comment by a6225301** [comment]
您好，您的邮件我已收到，我会尽快回复。
