### ISSUE TITLE
Query engine's query method returns None. Token usage is 0.

### ISSUE THREAD

**Issue by Bilski311** [jerryjliu/llama_index#2592]
I am using:
python 3.10.11
langchain 0.0.160
llama-index 0.6.1
Running on MacOS.

Following code:
from langchain.llms import OpenAI
from llama_index import SimpleDirectoryReader, GPTVectorStoreIndex, ServiceContext, LLMPredictor
from llama_index.node_parser import SimpleNodeParser

chat = OpenAI(temperature=0, model_name="text-davinci-003")

documents = SimpleDirectoryReader('data').load_data()
parser = SimpleNodeParser()
nodes = parser.get_nodes_from_documents(documents)

llm_predictor = LLMPredictor(chat)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

index = GPTVectorStoreIndex(nodes, service_context=service_context)
query_engine = index.as_query_engine()
print(f'Query engine output: {query_engine.query("Tell me a story.")}')
print(f'Token usage: {llm_predictor.last_token_usage}')

Gives this output:
python3.10 scripts/test.py
Query engine output: None
Token usage: 0

I tested langchain on it's own in a separate script run in the same venv and it seems to be connecting to OpenAI API without any problems. I also tried several different models and it did not make any difference. I am seeing a lot of similar issues but they seem to at least result in some API calls.

**Comment by Bilski311** [comment]
I downgraded to 
Python 3.9.16
llama-index 0.5.2
langchain 0.0.130
(Used the old API)
And the issue persists:
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 18 tokens
None

**Comment by alikalik9** [comment]
Same issue here.

**Comment by logan-markewich** [comment]
It seem like you did not actually load any documents. Notice the build tokens are zero 👀

Confirm that "./data" is the correct path 💪

**Comment by Bilski311** [comment]
Thanks @logan-markewich that was the issue, my bad. But I do wonder, in the case of failure to load any documents, shouldn't user see some sort of message for that? It wasn't very intuitive to diagnose from the perspective of a new user and seems like this could be a common issue for someone who is using the tool for the first time.(Especially that since v0.6.0 logging is not verbose by default.)
