### ISSUE TITLE
'GPTVectorStoreIndex' object has no attribute 'storage_context'

### ISSUE THREAD

**Issue by shwetalodha** [jerryjliu/llama_index#2634]
Since last few days, I'm facing error: 'GPTVectorStoreIndex' object has no attribute 'storage_context'.
Could you please help me out? Here is my code:

vIndex = GPTVectorStoreIndex.from_documents(documents=documents,service_context=service_context)
vIndex.storage_context.persist(persist_dir = "MyDir")

**Comment by logan-markewich** [comment]
Maybe try with a fresh python env, or reinstalling? 

It works for me 🤔

**Comment by shwetalodha** [comment]
Thanks. It worked.

**Comment by logan-markewich** [comment]
Perfect!
