### ISSUE TITLE
Where to set embed_model when loading index file in 0.6.1?

### ISSUE THREAD

**Issue by qizzzh** [jerryjliu/llama_index#2664]
```
storage_context = StorageContext.from_defaults(
    persist_dir="path"
)
index = load_index_from_storage(storage_context)
```
`StorageContext` and `load_index_from_storage` don't have an option to take a embed_model

**Comment by logan-markewich** [comment]
You can set the embed_model in the service context, and set the service context in the load function

**Comment by qizzzh** [comment]
Thanks for the fast response!
