### ISSUE TITLE
memory history with llama-index

### ISSUE THREAD

**Issue by joshlyman1988** [jerryjliu/llama_index#2711]
I am only recently started learning about llama-index.

I have noticed that standard ChatGPT API i could simply do the following code below to have ChatGPT get message history as context:

```
chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages
        )
```

I am now using llama-index library to train GPT-3.5 on a more specific context, however I don't know how to have the model consider the message_history as well

**Comment by sid-fitmatch** [comment]
I am having the same issue @jerryjliu

**Comment by mintisan** [comment]
I am having the same issue...

**Comment by Disiok** [comment]
We now have basic support via https://gpt-index.readthedocs.io/en/latest/how_to/chat_engine/root.html.

More modes and deeper controls coming soon!

**Comment by Geeksatya** [comment]
Is there any way i can save the chat history using llama_index?

**Comment by TinkyWinky1992** [comment]
any updates? for saving history messages?
