### ISSUE TITLE
Is there any default way to save a composable graph index?

### ISSUE THREAD

**Issue by bhavishpahwa** [jerryjliu/llama_index#2795]
In the composable graph class(https://github.com/jerryjliu/llama_index/blob/main/llama_index/indices/composability/graph.py) there is no method defined to save the composable graph index for later usage, also it does not inherit the BaseGPTIndex class(https://github.com/jerryjliu/llama_index/blob/main/llama_index/indices/base.py) so it does not has access to StorageContext. Still is there any way to save a composable graph index.

**Comment by bhavishpahwa** [comment]
@Disiok @jerryjliu Any advice on this?

**Comment by Kitenite** [comment]
Have you tried this? @bhavishpahwa 
https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/composability.html#optional-persisting-the-graph
