### ISSUE TITLE
Total LLM token usage How to optimize the cost?

### ISSUE THREAD

**Issue by xiaojun2sheng** [jerryjliu/llama_index#2823]
I uploaded a document with tens of thousands of words. After entering a question every time, the Total LLM token usage consumes a lot of tokens. Can this reduce the consumption of tokens? Or optimize the cost issue?

**Comment by kongweigen** [comment]
+1

**Comment by NaelsonAccountDrive** [comment]
+1

**Comment by logan-markewich** [comment]
Depends on the index you are using. A vector index will be by far the most token efficient.

With default settings, the `chunk_size` of nodes is 1024, and the default `similarity_top_k=2`. You can adjust these settings to control token usage.
