### ISSUE TITLE
DB-GPT: which use llama_index + langchain + vicuna build project, very cool

### ISSUE THREAD

**Issue by csunny** [jerryjliu/llama_index#3054]
My project is here: https://github.com/csunny/DB-GPT

SQL Generate
![image](https://user-images.githubusercontent.com/17919400/236994991-9259d516-3c1e-4b8c-b652-9f1ec2cd280b.png)

Knownledge based qa

![image](https://user-images.githubusercontent.com/17919400/236995032-6a76b7da-4e1a-46a3-a083-95030066d98e.png)

**Comment by Disiok** [comment]
Cool project! Feel free to make PR to add this to our project showcase https://github.com/jerryjliu/llama_index/blob/main/docs/gallery/app_showcase.md 

Will close this here since it's an issue.
