### ISSUE TITLE
Getting an error when trying to get the root_id of the graph created

### ISSUE THREAD

**Issue by juancalric** [jerryjliu/llama_index#3103]
```
root_index = graph.get_index(graph.index_struct.root_id, GPTSimpleKeywordTableIndex)
root_index.index_struct.index_id = "compare_contrast"
```

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-21-51a2b9ac45fd>](https://localhost:8080/#) in <cell line: 1>()
----> 1 root_index = graph.get_index(graph.index_struct.root_id, GPTSimpleKeywordTableIndex)
      2 root_index.index_struct.index_id = "compare_contrast"

AttributeError: 'KeywordTable' object has no attribute 'root_id'
```

**Comment by md844108** [comment]
# get root index
root_index = graph.get_index( graph.index_struct.root_id,GPTSimpleKeywordTableIndex) 


AttributeError: 'KeywordTable' object has no attribute 'root_id'

Same error found , can anyone solved it

**Comment by dglee-rbrain** [comment]
Same error here too. And I'm on v0.6.5

**Comment by jensbech** [comment]
Same error.

**Comment by aniketkalamkar** [comment]
it seems its a typo in the blog post. You can try **root_index = graph.get_index(graph.index_struct.index_id)** This gives root index id, Even if you dont pass the id, it will return root index id.
