### ISSUE TITLE
SelectionOutputParser.parse sometimes encounters non-JSON friendly `output` value

### ISSUE THREAD

**Issue by Ryanglambert** [jerryjliu/llama_index#3135]
```
'\nOutput:\n[\n  {\n    "choice": 1,\n    "reason": "Useful for questions that seek to gain a general understanding of something."\n  }\n]'
```

^^^ is not json decoder friendly because there's no opening '['

Instead you see "\nOutput:\n"...

I could fix this within `SelectionOutputParser.parse` but maybe it should be fixed elsewhere? I'll submit PR

**Comment by armen-tractatus** [comment]
Here's more insight if it helps:
https://github.com/jerryjliu/llama_index/issues/2808

**Comment by Ryanglambert** [comment]
This issue is solved by this PR: https://github.com/jerryjliu/llama_index/pull/3136#discussion_r1191344809
