### ISSUE TITLE
How to stream response of llamaindex like chatgpt

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#3142]
I have created the custom bot on my own documents available in google drive , 
Following is the complete code currently getting complete response at once but my question here is how I can stream the response as like what we generally get in chatgpt 

Please help thanks in advance 

GoogleDriveReader = download_loader('GoogleDriveReader')
folder_id = '1AuhkobVmt0Et0lIrEU0swvwavwXRtJYi'
loader = GoogleDriveReader()
documents = loader.load_data(folder_id=folder_id)

#parsing documents into Nodes
parser = SimpleNodeParser()
nodes = parser.get_nodes_from_documents(documents)

llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo",stream=True))

# Define prompt helper
max_input_size = 3500
num_output = 500
max_chunk_overlap = 20

prompt_helper = PromptHelper(max_input_size, num_output,max_chunk_overlap)
# Define LLM

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
path = 'C:\\Users\\Lenovo\\Desktop\\DocumentBot'

# storage_context = StorageContext.from_defaults(persist_dir=path)
# index = GPTVectorStoreIndex.from_documents(nodes, service_context=service_context )

#persisting index
# index.storage_context.persist()

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir=path)

# load index
index = load_index_from_storage(storage_context)

query_engine = index.as_query_engine()
prompt = input("Ask a question: ")
response = query_engine.query(prompt)

**Comment by Disiok** [comment]
Take a look at https://gpt-index.readthedocs.io/en/latest/how_to/customization/streaming.html

We just recently fixed this, you might have to wait for our next release i.e. 0.6.5

**Comment by jerryjliu** [comment]
0.6.5 is out! closing this issue

**Comment by vishalp-simplecrm** [comment]
Install 0.6.5 Still Getting below error

ask here:what is smartsearch?
INFO:llama_index.token_counter.token_counter:> [retrieve] Total LLM token usage: 0 tokens
> [retrieve] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total embedding token usage: 5 tokens
> [retrieve] Total embedding token usage: 5 tokens
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14748\3603361743.py", line 2, in <module>
    response_stream = query_engine.query(prompt,)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\query\base.py", line 20, in query
    return self._query(str_or_query_bundle)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 145, in _query
    response = self._response_synthesizer.synthesize(
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\query\response_synthesis.py", line 172, in synthesize
    source_nodes = list(nodes) + list(additional_source_nodes)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py", line 349, in get_response
    @llm_token_counter("get_response")
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\token_counter\token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py", line 172, in get_response
    text_qa_template,
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py", line 224, in _give_response_single
    for cur_text_chunk in text_chunks:
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\llm_predictor\base.py", line 256, in stream
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\langchain\llms\openai.py", line 417, in stream
    params = self.prep_streaming_params(stop)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\langchain\llms\openai.py", line 425, in prep_streaming_params
    if params["best_of"] != 1:
KeyError: 'best_of'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 1052, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 978, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 878, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\IPython\core\ultratb.py", line 712, in lines
    return self._sd.lines
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "C:\Users\Lenovo\anaconda3\envs\Doc_Bot\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

**Comment by vishalp-simplecrm** [comment]
Getting Following error after updating the llama_index version to 0.6.5
Please Help

ask here:What is smartsearch?
INFO:llama_index.token_counter.token_counter:> [retrieve] Total LLM token usage: 0 tokens
> [retrieve] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total embedding token usage: 5 tokens
> [retrieve] Total embedding token usage: 5 tokens
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 2
      1 prompt=input("ask here:")
----> 2 response_stream = query_engine.query(prompt,)
      3 print(response_stream)

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\query\base.py:20, in BaseQueryEngine.query(self, str_or_query_bundle)
     18 if isinstance(str_or_query_bundle, str):
     19     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 20 return self._query(str_or_query_bundle)

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\query_engine\retriever_query_engine.py:145, in RetrieverQueryEngine._query(self, query_bundle)
    140 self.callback_manager.on_event_end(
    141     CBEventType.RETRIEVE, payload={"nodes": nodes}, event_id=retrieve_id
    142 )
    144 synth_id = self.callback_manager.on_event_start(CBEventType.SYNTHESIZE)
--> 145 response = self._response_synthesizer.synthesize(
    146     query_bundle=query_bundle,
    147     nodes=nodes,
    148 )
    149 self.callback_manager.on_event_end(
    150     CBEventType.SYNTHESIZE, payload={"response": response}, event_id=synth_id
    151 )
    153 self.callback_manager.on_event_end(CBEventType.QUERY, event_id=query_id)

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\query\response_synthesis.py:163, in ResponseSynthesizer.synthesize(self, query_bundle, nodes, additional_source_nodes)
    161 if self._response_mode != ResponseMode.NO_TEXT:
    162     assert self._response_builder is not None
--> 163     response_str = self._response_builder.get_response(
    164         query_str=query_bundle.query_str,
    165         text_chunks=text_chunks,
    166         **self._response_kwargs,
    167     )
    168 else:
    169     response_str = None

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py:295, in CompactAndRefine.get_response(self, query_str, text_chunks, prev_response, **response_kwargs)
    289 with temp_set_attrs(
    290     self._service_context.prompt_helper, use_chunk_size_limit=False
    291 ):
    292     new_texts = self._service_context.prompt_helper.compact_text_chunks(
    293         max_prompt, text_chunks
    294     )
--> 295     response = super().get_response(
    296         query_str=query_str, text_chunks=new_texts, prev_response=prev_response
    297     )
    298 return response

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\token_counter\token_counter.py:78, in llm_token_counter.<locals>.wrap.<locals>.wrapped_llm_predict(_self, *args, **kwargs)
     76 def wrapped_llm_predict(_self: Any, *args: Any, **kwargs: Any) -> Any:
     77     with wrapper_logic(_self):
---> 78         f_return_val = f(_self, *args, **kwargs)
     80     return f_return_val

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py:134, in Refine.get_response(self, query_str, text_chunks, prev_response, **response_kwargs)
    130 for text_chunk in text_chunks:
    131     if prev_response_obj is None:
    132         # if this is the first chunk, and text chunk already
    133         # is an answer, then return it
--> 134         response = self._give_response_single(
    135             query_str,
    136             text_chunk,
    137         )
    138     else:
    139         response = self._refine_response_single(
    140             prev_response_obj, query_str, text_chunk
    141         )

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\indices\response\response_builder.py:179, in Refine._give_response_single(self, query_str, text_chunk, **response_kwargs)
    175     self._log_prompt_and_response(
    176         formatted_prompt, response, log_prefix="Initial"
    177     )
    178 elif response is None and self._streaming:
--> 179     response, formatted_prompt = self._service_context.llm_predictor.stream(
    180         text_qa_template,
    181         context_str=cur_text_chunk,
    182     )
    183     self._log_prompt_and_response(
    184         formatted_prompt, response, log_prefix="Initial"
    185     )
    186 else:

File ~\anaconda3\envs\Doc_Bot\lib\site-packages\llama_index\llm_predictor\base.py:280, in LLMPredictor.stream(self, prompt, **prompt_args)
    277 self._llm.callbacks = [handler]
    279 if not getattr(self._llm, "streaming", False):
--> 280     raise ValueError("LLM must support streaming and set streaming=True.")
    282 thread = Thread(target=self._predict, args=[prompt], kwargs=prompt_args)
    283 thread.start()

ValueError: LLM must support streaming and set streaming=True.

**Comment by willhamlam** [comment]
Same issue here, using models 'text-davinci-003' and 'gpt-3.5-turbo' raise the problem：
`ValueError: LLM must support streaming and set streaming=True.`

Using version 0.6.5

**Comment by Disiok** [comment]
You need to pass streaming=True to the LLM. See https://gpt-index.readthedocs.io/en/latest/how_to/customization/streaming.html

**Comment by vishalp-simplecrm** [comment]
I have already given that in the code still its giving the error

here is the complete code that , can please check and correct me 

import os
import pickle
from langchain import OpenAI
from llama_index.node_parser import SimpleNodeParser
from flask import Flask, render_template, request
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from llama_index import LLMPredictor, PromptHelper, ServiceContext, download_loader,MockLLMPredictor,MockEmbedding,GPTVectorStoreIndex
from langchain.chat_models import ChatOpenAI
from IPython.core.display import HTML
from llama_index import StorageContext, load_index_from_storage


os.environ['OPENAI_API_KEY'] = 'your api key'

def authorize_gdocs():
    google_oauth2_scopes = [
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/documents.readonly"
    ]
    cred = None
    if os.path.exists("token.pickle"):
        with open("token.pickle", 'rb') as token:
            cred = pickle.load(token)
    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("client_secrets.json", google_oauth2_scopes)
            cred = flow.run_local_server(port=0)
        with open("token.pickle", 'wb') as token:
            pickle.dump(cred, token)

authorize_gdocs()
#Drive_loader
GoogleDriveReader = download_loader('GoogleDriveReader')
folder_id = '1AuhkobVmt0Et0lIrEU0swvwavwXRtJYi'
loader = GoogleDriveReader()
documents = loader.load_data(folder_id=folder_id)

#parsing documents into Nodes
parser = SimpleNodeParser()
nodes = parser.get_nodes_from_documents(documents)

llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo",streaming=True))

# Define prompt helper
max_input_size = 3500
num_output = 500
max_chunk_overlap = 20

prompt_helper = PromptHelper(max_input_size, num_output,max_chunk_overlap)
# Define LLM

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
path = 'C:\\Users\\Lenovo\\Desktop\\DocumentBot'
# #Create index from documents 
storage_context = StorageContext.from_defaults(persist_dir=path)
index = GPTVectorStoreIndex.from_documents(nodes, service_context=service_context )

#persisting index
index.storage_context.persist()

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir=path)

# load index
index = load_index_from_storage(storage_context)
query_engine = index.as_query_engine(
    streaming=True,
    similarity_top_k=1
)
# query_engine = index.as_query_engine()
prompt = input("Ask a question: ")
print('prompt given issss:',prompt)
response = query_engine.query(prompt)
print('Responseeeeee:',response)

**Comment by SeloSlav** [comment]
I'm also experiencing the same problem. My code should be correct according to the latest documentation:

```
#  /server/llama_index_server.py

import openai
from flask import Flask, request, Response
from flask_cors import CORS
from dotenv import load_dotenv
import os
import pandas as pd
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader
from llama_index import Document
from langchain.chat_models import ChatOpenAI
from llama_index import LLMPredictor
from llama_index import ServiceContext

app = Flask(__name__)
CORS(app)

load_dotenv()

# Get the API key from the environment variable
api_key = os.getenv('OPENAI_API_KEY')

# Set the OpenAI API key directly
openai.api_key = api_key

# Print the API key for verification
# print(f"API key: {api_key}")

# Loading documents from an Excel file
df = pd.read_excel('data/SupplierSample.xlsx')

# Convert DataFrame rows into documents
# Concatenate all column values into a single string for each row
documents = [Document(text=' '.join(map(str, row.values))) for _, row in df.iterrows()]

# Construct a simple vector index
index = GPTVectorStoreIndex(documents)

# LLM that supports streaming
llm_predictor = LLMPredictor(
    llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True)
)
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor
)

# Configure query engine to use streaming
query_engine = index.as_query_engine(
    streaming=True,
    similarity_top_k=1
)

@app.route('/api/query', methods=['POST'])
def query():
    # Get the payload from the request
    payload = request.json
    
    # Get the question from the messages in the payload
    question = [m['content'] for m in payload['messages'] if m['role'] == 'user'][-1]
    
    # Now, query returns a StreamingResponse object
    streaming_response = query_engine.query(question)

    def response_stream():
        for text in streaming_response.response_gen:
            yield text + "\n"

    return Response(response_stream(), mimetype="text/event-stream")

if __name__ == '__main__':
    # Start the server, to run this script use "python llama_index_server.py" in terminal
    # Invoke-WebRequest -Uri http://localhost:5000/api/query -Method POST -ContentType "application/json" -Body '{"messages":[{"role": "user", "content": "What is OpenAI?"}]}'

    app.run(port=5000)
```

I still get the following error:

```
ValueError: LLM must support streaming and set streaming=True.
127.0.0.1 - - [29/Jun/2023 17:55:09] "POST /api/query HTTP/1.1" 500 -
```

**Comment by NaveedHakim3899** [comment]
Having exact same issue. Were you able to find any solution?
