### ISSUE TITLE
Persisting a Pinecone Index

### ISSUE THREAD

**Issue by raghav-menon** [jerryjliu/llama_index#3147]
Hello, 

Can you please let me know the procedure to persist and load the index in case I am storing the vectors in Pinecone. Would be grateful if you could point me to an example.

Thanks
Raghav

**Comment by Disiok** [comment]
Since pinecone persists the embeddings by default, you just need to re-connect to the same pinecone index.

**Comment by raghavpatnecha** [comment]
I tried but it gives a value error
`pinecone.init(
    api_key=os.environ['PINECONE_API_KEY'],
    environment=os.environ['PINECONE_ENVIRONMENT']
)
pinecone_index = pinecone.Index("test")

vector_store = PineconeVectorStore(
    pinecone_index=pinecone_index,
)

vector_store = PineconeVectorStore(pinecone_index=pinecone_index)

storage_context = StorageContext.from_defaults(vector_store)
index = load_index_from_storage(storage_context=storage_context)`

Error : `ValueError: No index in storage context, check if you specified the right persist_dir.`

**Comment by raghav-menon** [comment]
> Since pinecone persists the embeddings by default, you just need to re-connect to the same pinecone index.

Thanks for the reply. I don’t think it is as simple as that. Had tried doing it but unfortunately I was not successful. I think for Faiss and Pinecone it is a different way in which it has to be read back. Am still struggling with that.

**Comment by raghav-menon** [comment]
> I tried but it gives a value error `pinecone.init( api_key=os.environ['PINECONE_API_KEY'], environment=os.environ['PINECONE_ENVIRONMENT'] ) pinecone_index = pinecone.Index("test")
> 
> vector_store = PineconeVectorStore( pinecone_index=pinecone_index, )
> 
> vector_store = PineconeVectorStore(pinecone_index=pinecone_index)
> 
> storage_context = StorageContext.from_defaults(vector_store) index = load_index_from_storage(storage_context=storage_context)`
> 
> Error : `ValueError: No index in storage context, check if you specified the right persist_dir.`

Yes, I tried the same way but does not work. I saw that Faiss and Pinecone, the way to read is somehow different. I asked this question for the same purpose. Some examples would have been good. Still trying to work out how to do it!

Also still awaiting a reply from Jerry

**Comment by hooman-myadbox** [comment]
Have you found a way to solve this issue?

**Comment by Disiok** [comment]
Try 
```python
vector_store = PineconeVectorStore(pinecone_index=pinecone.Index("test"))
index = VectorStoreIndex.from_vector_store()
```
