### ISSUE TITLE
Issue from ./llama_index/examples/paul_graham_essay/TestEssay.ipynb

### ISSUE THREAD

**Issue by dglee-rbrain** [jerryjliu/llama_index#3149]
At '[Demo] Build Tree Index during Query-Time',

query_engine = index_light.as_query_engine(
    retriever_mode="all_leaf",
    response_mode='tree_summarize',
)
query_engine.query("What did the author do after his time at Y Combinator?")

**TypeError: TreeAllLeafRetriever.__init__() got an unexpected keyword argument 'response_mode'**

It is saying 'response_mode' is an unexpected argument. Why does this happen?

**Comment by astro313** [comment]
I am on v0.6.2. This works for me:
```
from llama_index.query_engine import RetrieverQueryEngine
retriever = index.as_retriever(retriever_mode="all_leaf")     
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo"))       
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
query_engine = RetrieverQueryEngine.from_args(retriever,
                                              service_context=service_context,
                                              response_mode='tree_summarize',
                                    verbose=True
                                    )
response = query_engine.query("your queestion"
                              )
```

**Comment by dglee-rbrain** [comment]
Thank you for your response! It helped me alot.

Was there any setting change commited in 'as_query_engine()' function?

I wonder why that happened.

**Comment by dglee-rbrain** [comment]
> Thank you for your response! It helped me alot.
> 
> Was there any setting change commited in 'as_query_engine()' function?
> 
> I wonder why that happened.



> I am on v0.6.2. This works for me:
> 
> ```
> from llama_index.query_engine import RetrieverQueryEngine
> retriever = index.as_retriever(retriever_mode="all_leaf")     
> llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo"))       
> service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
> query_engine = RetrieverQueryEngine.from_args(retriever,
>                                               service_context=service_context,
>                                               response_mode='tree_summarize',
>                                     verbose=True
>                                     )
> response = query_engine.query("your queestion"
>                               )
> ```

Thank you for your response! It helped me alot.

Was there any setting change commited in 'as_query_engine()' function?

I wonder why that happened.
