### ISSUE TITLE
How to add an additional step to chat agent?

### ISSUE THREAD

**Issue by zeonn** [jerryjliu/llama_index#3172]
I initialize the agent with create_llama_chat_agent and then call its run method.
I'm currently using llama_index version 0.5.27. But I can upgrade to branch 0.6 if needed.

I'm trying to solve this problem: After the agent has found the answer to the given question with or without the index, I would like to add an additional check for completeness of information in the given query in relation to the context found in the index and the answer received from the model. And in case the query wasn't complete enough (for example, it was too abstract and can be interpreted differently), the model should be forced to generate a new question instead of a response, asking for more specific information. Then, this request and the answer received from the user will be used as the context of the dialog, and the following answer will be more accurate, as the clarifying request complements the original one.

Unfortunately, I haven't found the right way to do this. Could someone give me a hint?

**Comment by astro313** [comment]
I would first try using customized prompts doing exactly what you described.

**Comment by zeonn** [comment]
I tried to overwrite the refine_template by adding the line "If the original question is too general (for example \"Will it work in my case?\"), then, instead of answering, ask a new clarifying question."

This worked in some cases. But only sometimes. I would like to hear more variants.
