### ISSUE TITLE
how to load .json index in new llama_index version

### ISSUE THREAD

**Issue by vimalrajan242001** [jerryjliu/llama_index#3177]
I created to vector index using **GPTSimpleVectorIndex** and then saved in json format.
Now I updated to latest llama_index version, in this GPTVectorStoreIndex' has no attribute 'load_from_disk'
how can we load json vector index in latest llama_index. can anyone explain this

**Comment by ismadoukkali** [comment]
Im having the same problem. Thanks.

**Comment by bitcoinbrisbane** [comment]
I think its this... ill let you know soon:

## To save
```python
index.storage_context.persist()
```

## To reaload
```python
    storage_context = StorageContext.from_defaults('storage') # storage_context = StorageContext.from_defaults(persist_dir="<persist_dir>")

    # reload load index
    index = load_index_from_storage(storage_context)
```

**Comment by cbnsndwch** [comment]
> I think its this... ill let you know soon:
> 
> ## To save
> ```python
> index.storage_context.persist()
> ```
> 
> ## To reaload
> ```python
> storage_context = StorageContext.from_defaults('storage') # storage_context = StorageContext.from_defaults(persist_dir="<persist_dir>")
> 
> # reload load index
> index = load_index_from_storage(storage_context)
> ```


This just bit me. I trained a `GPTSimpleVectorIndex` and saved it to a JSON file (with llama_index v0.4.26)

Today I upgraded to v0.6.14 and `GPTSimpleVectorIndex` is gone. In the process of re-learning how to work with it now. I really would appreciate any pointers for how to load my existing index from a JSON file so I don't have to retrain it.

**Comment by Disiok** [comment]
Apologies for breaking backwards compatibility. We've made some big upgrades to the framework and it would be too much work to maintain compatibility.

I would suggest to just re-index for now. Otherwise you can also manually load the old json, and modify it to fit the new schema.
