### ISSUE TITLE
Persisted IndexDict with empty nodes and docs

### ISSUE THREAD

**Issue by logivasz** [jerryjliu/llama_index#3189]
service_context=self.initServiceContext()
        documents=self.loadDocuments(dataFolder)
        for document in documents:
            document.doc_id=document.get_doc_hash()

        environment = 'us-west1-gcp-free'
        index_name = 'myindex'
        uri="mongodb://root:example@mongo:27017"

        pinecone.init(environment=environment)
        pinecone_index = pinecone.Index(index_name=index_name)
        vectoreStore = PineconeVectorStore(pinecone_index=pinecone_index)       
        docstore = MongoDocumentStore.from_uri(uri=uri,db_name='doc_store')       
        indexStore=MongoIndexStore.from_uri(uri=uri,db_name='index_store')
        indexStruct=indexStore.index_structs()
        storage_context = StorageContext.from_defaults(docstore=docstore,index_store=indexStore,vector_store=vectoreStore)
        if len(indexStruct):
           index = load_index_from_storage(storage_context)
           print(index._index_struct)
           upd = index.refresh(documents)
           print(upd)
        else:
            index = GPTVectorStoreIndex.from_documents(documents,storage_context=storage_context,service_context=service_context)        
            print(index._index_struct)

The index_struct always looks like this
IndexDict(index_id='e00a2c45-2857-41d2-a3c6-d53c79b2722d', summary=None, nodes_dict={}, doc_id_dict={}, embeddings_dict={})
nodes_dict={}, doc_id_dict={} is always empty  but  at the first use (index = GPTVectorStoreIndex.from_documents) the index is works fine, I can run queries on it.
When loaded using load_index_from_storage, I get an errors when I run queries on it.
'EOL while scanning string literal (<unknown>, line 4)'
When the data is persisted to the disk everything is ok
What am I doing wrong?

**Comment by logan-markewich** [comment]
Pinecone saves the entire index into the vector db, no need to call save/persist

https://gpt-index.readthedocs.io/en/latest/how_to/storage/customization.html#vector-store-integrations-and-storage
