### ISSUE TITLE
Customized segments of text vs text chunking via ServiceContext

### ISSUE THREAD

**Issue by astro313** [jerryjliu/llama_index#3201]
When indexing from a single text document, Is there a way to not use `ServiceContext` and `chunk_size_limit`, which seems to be calling token splitting `TokenTextSplitter`, but instead just pass a list of strings that are already segmented on this single document? 

Inside `ServiceContext.from_default()`, `PromptHelper.from_llm_predictor` is also using `chunk_size_limit` and calling some methods that performs text splitting given some prompt. 

So can we have a feature that allows customized segments of text for both `ServiceContext` and `PromptHelper`?

**Comment by Disiok** [comment]
If you have documents already chunked, you can directly wrap them as nodes and build index, e.g.:
```
nodes = [Node(chunk) for chunk in chunk_list]
index = VectorStoreIndex(nodes)
```
