### ISSUE TITLE
root_id when loading graph

### ISSUE THREAD

**Issue by astro313** [jerryjliu/llama_index#3202]
When loading graph, we need to provide the root_id, but how would I know the root_id? For example, 

```
from llama_index.indices.composability import ComposableGraph
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, max_tokens=512, model_name='gpt-3.5-turbo'))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
storage_context = StorageContext.from_defaults()

graph = ComposableGraph.from_indices(
    GPTListIndex,
    [essay_index, empty_index],
    index_summaries=[essay_index_summary, empty_index_summary],
    service_context=service_context,
    storage_context=storage_context,
)
```
Then when we reload: 
```
from llama_index.indices.loading import load_graph_from_storage
storage_context.persist('data/heterogenous_graph_test')
graph=  load_graph_from_storage(storage_context, root_id=graph.root_id)
```
But `graph` would not be defined at reloading without reconstructing `graph`

**Comment by rucieryi369** [comment]
I save the root_id and reload graph, but the graph have  KeyError, can't find the docs relation.

**Comment by risto-trajanov** [comment]
I save it in the file name of the folder for example graph_name__id, but later I get an error like this:

  File "G:\Other computers\My Computer\dashboard_v2.py", line 343, in main
    print(graph.root_index)
  File "C:\Users\Risto Trajanov\anaconda3\envs\myenv_3.8\lib\site-packages\llama_index\indices\composability\graph.py", line 34, in root_index
    return self._all_indices[self._root_id]
KeyError: '7b2b0f99-8045-4ba6-b843-5cf5ca5935ae'

**Comment by tapizquent** [comment]
You get that error because of the storage context. 

Try doing this if you have the default.

```
storage_context = StorageContext.from_defaults(persist_dir="./storage")
```

**Comment by puckfried** [comment]
I have the same issue. After creation of the graph i copied the root_id. In next step i tried to load the graph with the copied root_id and in Debugger the graph is loaded, the error (KeyError) occurs, while query is running.

**Comment by astro313** [comment]
> graph

even if you try setting the persist_dir on the fly, you still run into the issue of  `root_id` not defined when you refresh the notebook / code.

```
from llama_index import load_graph_from_storage
graph = load_graph_from_storage(
    # root_id=root_id, 
    service_context=service_context,
    storage_context=StorageContext.from_defaults(persist_dir='./data/uber_index/root'),
)
```
If you try commenting `root_id` out, it will return
`TypeError: load_graph_from_storage() missing 1 required positional argument: 'root_id'`

**Comment by RoboGodzilla** [comment]
+1 to the issue.

Getting the KeyError whenever trying to load the graph and query it.
