### ISSUE TITLE
Documentation Example are broken

### ISSUE THREAD

**Issue by FFX01** [jerryjliu/llama_index#3205]
Hi there! Really interesting project here!

I've been trying to run through the examples in the documentation and I can't seem to get a single one of the tutorial projects to work without major changes. It seems like maybe the examples are out of date?

I've experienced the following issues:

## Dependency Version Conflicts
So far I've only experienced this with numpy and argilla. However, it illustrates that dependencies are not handled well.

## Broken Example Code
Many pieces of example code are simply broken. They have missing/incorrect imports, calls to methods that don't exist, missing dependencies, and references to undefined variables.
### Example: 
```python
response = vector_indices["Toronto"].query("What are the sports teams in Toronto?")
print(str(response))
```
This example will not work. It needs to be changed to:
```python
response = vector_indices["Toronto"].as_query_engine().query("What are the sports teams in Toronto?")
print(str(response))
```

## General Documentation Quality
I know this project is fairly new and I shouldn't expect perfect documentation. However, the documentation as it stands is confusing and outdated(I think) in many places. I would expect that the getting started and tutorial sections at least would work and explain things well, but they do not. Unfortunately, this makes it very difficult for me to test llama-index and next to impossible to recommend adoption at my organization.

I am willing to help improve the documentation, but I honestly have a poor understanding of how the library works and would not be able to update the documentation myself. I want to be clear that I'm not just complaining; I am very willing to help in any way I can. I have some suggestions:

## Suggestions:
1. All example code should "just work". This means that as long as I have the dependencies installed, I should be able to copy-paste the code and run it without any major issues. Of course, any issues with 3rd-party tools/APIs are excluded from this.
2. Ensure all code examples are up-to-date with every release.
3. Restructure tutorials and guides for less confusing control-flow. For example,I ran into several issues where variables defined inside loops were used outside of the loop which requires re-running the loop in order to ensure the variable is present or having to re-write the example code myself
4. Ensure all tutorials and guides explicitly call out required dependencies.
5. Ensure all tutorials and guides are actually importing the modules/functions/classes/etc needed for the code to run.

**Comment by Disiok** [comment]
Really appreciate the detailed and thoughtful feedback.
You are absolutely right and we are actively working on making this better.

**Comment by bitcoinbrisbane** [comment]
> Really appreciate the detailed and thoughtful feedback. You are absolutely right and we are actively working on making this better.

Took me a bit to get things working.  Happy to make PRs on the doco if that helps.

**Comment by FFX01** [comment]
Thanks for the replies. Once again, I'm willing to help where I can. If someone could point me in a direction, I'd be happy to try making a PR or whatever else needs doing.

**Comment by bitcoinbrisbane** [comment]
> Thanks for the replies. Once again, I'm willing to help where I can. If someone could point me in a direction, I'd be happy to try making a PR or whatever else needs doing.

All the docs seem to live in here  :  https://github.com/jerryjliu/llama_index/tree/main/docs

**Comment by logan-markewich** [comment]
@FFX01 Thanks for the feedback and suggestions. Happy to have contributions to the docs. We are trying to actively improve them as well. 

Docs contribution guide is here:
https://gpt-index.readthedocs.io/en/latest/development/documentation.html
