### ISSUE TITLE
Only data from the index is used, and it is necessary to supplement the general knowledge of chatGPT with data from the index...

### ISSUE THREAD

**Issue by IvanPigarev** [jerryjliu/llama_index#3210]
I apologize if this is a silly question, I'm just getting started. Llama index creates indexes from the pdf folder and everything works. But chat only has knowledge from these pdfs. If I ask him about other topics and I want him to give answers based on his previous learning, but to prioritize the information from the pdf - can I do that?

**Comment by reinershir** [comment]
Sure, you can refer to this: https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb 
However, there are some issues as it seems unable to support streaming transmission.

**Comment by Disiok** [comment]
This might be what you want: https://gpt-index.readthedocs.io/en/latest/examples/chat_engine/chat_engine_react.html
