### ISSUE TITLE
 cannot import name 'load_index_from_storage' from 'llama_index'

### ISSUE THREAD

**Issue by Crowdparti** [jerryjliu/llama_index#3240]
Please is there anyone who can advise me? 
I met this error when I tried to run the sample code in the git of Llamaindex 0.6.5
please, refer to this link: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/SimpleIndexDemo.html#load-documents-build-the-gptvectorstoreindex.

**Comment by logan-markewich** [comment]
That should be correct. My reinstall llama index, or even start with a fresh venv

`from llama_index import load_index_from_storage`
https://github.com/jerryjliu/llama_index/blob/main/llama_index/__init__.py#L175

**Comment by Crowdparti** [comment]
You are right it is working now. Thx you!
