### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (2503 > 1024). Running this sequence through the model will result in indexing errors?

### ISSUE THREAD

**Issue by Bruce337f** [jerryjliu/llama_index#3242]
[https://github.com/jerryjliu/llama_index/issues/987#issuecomment-1493259768](url)

I try to use the method here, but it doesn't work, is it because the embedding ada model only supports 1024 maximum tokens?

# NOTE: set a chunk size limit to < 1024 tokens 
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, chunk_size_limit=512)
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)

**Comment by logan-markewich** [comment]
Are your documents in english? If not, you might want to also consider using a different text splitter, maybe the recursive character splitter from langchain?

```python
from langchain.text_splitter import RecursiveCharacterTextSplitter
from llama_index.node_parser import SimpleNodeParser
from llama_index import ServiceContext

service_context = ServiceContext.from_defaults(..., node_parser=SimpleNodeParser(text_splitter=RecursiveCharacterTextSplitter()))
```

**Comment by Shane-Khong** [comment]
Bump - did RecursiveCharacterTextSplitter result in a better outcome?

Also, linking to similar topic to assist with resolving quicker: https://github.com/jerryjliu/llama_index/issues/987

**Comment by abhishek22-ai** [comment]
Hi @jerryjliu,
I have gone through the suggestions mentioned here & the previous same issue,
here's the code snippet
`
self.backup_separators = ["\n\n", "\n", " ", ".", ",", "!", ""]
# Text splitter
self.text_splitter = RecursiveCharacterTextSplitter(
chunk_size=self.chunk_size,
chunk_overlap=self.chunk_overlap,
separators=self.backup_separators,
)
# Service Context
self.service_context = ServiceContext.from_defaults(
    llm_predictor=self.llm_predictor,
    prompt_helper=self.prompt_helper,
    embed_model=self.embedding_model,
    node_parser=SimpleNodeParser(text_splitter=self.text_splitter),
    chunk_size_limit=self.chunk_size,
)
`
But we still face the error after the warning message
`Token indices sequence length is longer than the specified maximum sequence length for this model (7367 > 1024). Running this sequence through the model will result in indexing errors?`

`ValueError: Got a larger chunk overlap (150) than chunk size (-2975), should be smaller.`

**Comment by logan-markewich** [comment]
@sahil-springworks @abhishek22-ai @Shane-Khong @Bruce337f 

If any of you can provide a document+code that reliably reproduces the issue, that would help immensely. It's nearly impossible to track this down otherwise.
