### ISSUE TITLE
load data from dictionary in llamaindex

### ISSUE THREAD

**Issue by javixeneize** [jerryjliu/llama_index#3243]
Hi

How can i load data from a dictionary in llamaindex? I have seen all the examples loading data from a file, but cant see how to load from a dictionary, and load every item as an individual document

**Comment by logan-markewich** [comment]
You can load the data by creating the document objects manually

```
from llama_index import Document
my_data = {'1': 'my_doc'}

documents = []
for key, val in my_data.items():
  documents.append(Document(val))
```

or if its a json file, you can use the loader from here: https://llamahub.ai/l/file-json

**Comment by javixeneize** [comment]
Yeah I’m using the json loader but I think it is loading everything as a single document, as when I ask for some data about one of the items, it answers with data from another, that’s why I believe it doesn’t consider each item as independent

**Comment by logan-markewich** [comment]
Yea, then you may want to load the data on your own and create document objects as I suggested above 👍🏻
