### ISSUE TITLE
Indexing Time Logging

### ISSUE THREAD

**Issue by bradley-pearson6597** [jerryjliu/llama_index#3246]
It would be useful if there was an indication of how many documents have been indexed so far/how long the rest of the indexing process will take. I am indexing 2000+ documents and I have no idea how long it will take. 

If this already exists I look forward to hearing how to do it!

**Comment by Disiok** [comment]
Ya we can add some logging/tqdm for this!

**Comment by logan-markewich** [comment]
This has been added! https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/usage_pattern.html#high-level-api
