### ISSUE TITLE
Is there a way to not load documents in memory in order to be able to query an index? 

### ISSUE THREAD

**Issue by rfarahmand** [jerryjliu/llama_index#3250]
Hello,
I am not sure if I understand the flow of the following program correctly, but suppose I have indexed thousands or millions of documents along with their embeddings in a VectorStore , Say an OpenSearchVectorStore. Why still do I still need to load the documents in the memory in order to to be able to access or query the index? I am thinking that in one call we do a semantic search to the OpenSearchVectorStore using a cosine similarity to get the right documents and then pass one or two of them as the context to the OpenAPI prompt as the subsequent call to do summarization or any other instructions we pass to the OpenAI. This is my program: 
```[python]
documents = SimpleDirectoryReader('../paul_graham_essay/data').load_data()
client = OpensearchVectorClient(endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field,auth=auth)
index = GPTOpensearchIndex.from_documents(documents=documents, client=client)
response = index.query("What did the author do growing up?")
```
what I intended to do is to ingest millions of document, get embedding for them, and store them in a vector store. Then in a separate program that is supposed to only query the index, get the relevant documents so that I can make subsequent calls to OpenAI models with prompts that has the relevant document as the context so that  I don't have to load the documents in the memory but just connect to the vector store? is there a way to access the index without having documents loaded in memory but rather only have them in the vector store? In other words, is there a way to get the `GPTOpensearchIndex` without passing the documents and only the `client`?

Alternatively, I suppose I can pass the cosine similarity script query myself? like 
```
rdr = ElasticsearchReader(endpoint, idx,httpx_client_args ={"verify":False,"auth":("admin","admin")})
rdr.load_data(embedding_field,{
 "size": 4,
 "query": {
   "script_score": {
     "query": {
       "match_all": {}
     },
     "script": {
       "source": "knn_score",
       "lang": "knn",
       "params": {
         "field": embedding_field,
         "query_value": [vector for the question goes here],
         "space_type": "cosinesimil"
       }
     }
   }
 }
}
)
```
 is that correct?

Thanks for your help?

**Comment by Disiok** [comment]
Hey @rfarahmand, if you already have an existing vector store with data already inside, you can directly query data without loading documents. 


You can do something like: 
```
client = OpensearchVectorClient(endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field)
# initialize vector store
vector_store = OpensearchVectorStore(client)
``` 
And starting using that. Note that we changed our API in the latest version (0.6.0), so instead of `GPTOpensearchIndex`, you can just create the vector store and pass it to the `GPTVectorStoreIndex`

**Comment by rfarahmand** [comment]
That did work, although I had to pass the embedding like this:

```
from llama_index.vector_stores import OpensearchVectorStore
from llama_index.vector_stores.types import VectorStoreQuery
from gpt_index.embeddings.openai import OpenAIEmbedding
from llama_index.vector_stores import OpensearchVectorClient


embed_model = OpenAIEmbedding()

auth = {"user": "admin", "pass": "admin"}
client = OpensearchVectorClient(endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field, auth=auth)
vector_store = OpensearchVectorStore(client)
res = vector_store.query(VectorStoreQuery(query_str="which projects do supermarkets?" ,query_embedding=embed_model.get_text_embedding("which projects do supermarkets?")))
print(res.nodes[0].extra_info["content"])
```

Thanks very much from a fellow UofT alumni ;)
