### ISSUE TITLE
Issue with a limit output with chatgpt bot

### ISSUE THREAD

**Issue by qwzxqwzx** [jerryjliu/llama_index#3252]
I have this script that creates a chatbot. The problem is it gives me very limited outputs as an answer is there anything in the script that I can change so I can get the maximum output possible?
Can anyone help me with this issue I would really appreciate it.?
`
from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain.chat_models import ChatOpenAI
import gradio as gr
import sys
import os
import keyring
import openai

api_key = keyring.get_password('OPENAI', 'bbb')

os.environ["OPENAI_API_KEY"] = api_key

def construct_index(directory_path):
    max_input_size = 4096
    num_outputs = 4000
    max_chunk_overlap = 20
    chunk_size_limit = 600

    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))

    documents = SimpleDirectoryReader(directory_path).load_data()

    index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

    index.save_to_disk('index.json')

    return index

def chatbot(input_text):
    index = GPTSimpleVectorIndex.load_from_disk('index.json')
    response = index.query(input_text, response_mode="default")
    return response.response

iface = gr.Interface(fn=chatbot,
                     inputs=gr.components.Textbox(lines=7, label="Enter your text"),
                     outputs="text",
                     title="Custom-trained AI Chatbot")

index = construct_index("docs")
iface.launch(share=True)`

**Comment by logan-markewich** [comment]
Slight misunderstanding here.

For models like GPT, the input and output are connected. Every token generated is added back to the input before generating the next.

By setting num_output to 4000, you are telling llama index to leave room in the prompt for 4000 output tokens. Given that the max input size is 4096, this basically causes nothing to be sent to the LLM

Try setting num_output to 256 or 512. I wouldn't go any higher than around 1000.

**Comment by logan-markewich** [comment]
Also, I think you are on a pretty old version (no worries though)

Also don't forget to pass in everything when loading, like this (in newer versions, this will be a little different)

`index.load_from_disk("index.json", llm_predictor=llm_predictor, prompt_helper=prompt_helper)`

**Comment by sid8491** [comment]
> Slight misunderstanding here.
> 
> For models like GPT, the input and output are connected. Every token generated is added back to the input before generating the next.
> 
> By setting num_output to 4000, you are telling llama index to leave room in the prompt for 4000 output tokens. Given that the max input size is 4096, this basically causes nothing to be sent to the LLM
> 
> Try setting num_output to 256 or 512. I wouldn't go any higher than around 1000.

how can we print the final prompt that is being sent to LLM along with the relevant chunks by the library when we call query() function?

**Comment by logan-markewich** [comment]
You can use the llama debug handler, and get the LLM events

https://github.com/jerryjliu/llama_index/blob/main/examples/callbacks/LlamaDebugHandler.ipynb

**Comment by qwzxqwzx** [comment]
@logan-markewich 
Thanks for your answer I have a few more questions.
1. What version would you recommend me to use?
2. Can you explain to me what would be the recommended size for max_chunk_overlap = 20
and chunk_size_limit=600, max_input_size = 4096,num_outputs = 4000? Since I want my output not to get cut off in the middle and also give me back longer responses.
3. Do you know what would be the longest response I can get and what module will be best to use?

**Comment by qwzxqwzx** [comment]
@logan-markewich 
What is the usage of the chunk_size_limit=600 in the script is it necessary?
