### ISSUE TITLE
Install documentation appears to be incomplete

### ISSUE THREAD

**Issue by normanlove222** [jerryjliu/llama_index#3254]
I have Llama index installed on my desktop for windows and I have code from about 30 days ago that is working fine on desktop.

The issue is im now on my laptop which is linux and trying to recreate a development enviornment and im unable to install llama index. I have followed the latest instructions at https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html, but these appear to be inaccurate or incomplete cause even though Ive followed them to the T, Im unable to properly install llama index. key word being properly. Its installed but my python script cant find the location.

some obvious issues with install page is it says:
git clone git@github.com:jerryjliu/llama_index.git and terminal does not like that and suggests using https at beginning , which then works. 

another issue is the install page then suggests you do pip install -r requirements.txt. which would not work unless you actually change to the directory you installed lamma_index to. this is not as obvious as the developers may feel as installation instructions are supposed to include ALL the steps neccessary to properly install the project.

Even with figuring all this out, iI still get unknown location for llamada index when I run my index.py sample code. 

May I sugest that someone actually create new instructions that will properly install this project on BOTH windows and Linux. or state , hey, this is just for windows etc. 

This is especially important when your code is changing as rapidly as yours is. old code is no longer working after 30 days. 

So in summary after following the install page instructions I get:

`python3.10 index.py
Traceback (most recent call last):
  File "/var/www/html/Text/index.py", line 5, in <module>
    from llama_index import GPTVectorStoreIndex, download_loader
ImportError: cannot import name 'GPTVectorStoreIndex' from 'llama_index' (unknown location)

`
for running this code:

`#current working module that indexes knowledgebase via llamaindex and then prompts via terminal only
import os
import configparser
import logging
from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

# Configure logging settings for llama_index to suppress unwanted messages
llama_index_logger = logging.getLogger('llama_index')
llama_index_logger.setLevel(logging.ERROR)

config = configparser.ConfigParser()
config.read('config.ini')

api_key = config.get('openai', 'api_key')
os.environ['OPENAI_API_KEY'] = api_key

documents = SimpleDirectoryReader('data').load_data()
index = GPTVectorStoreIndex.from_documents(documents)

# save to disk
# index.save_to_disk('index.json')
# # load from disk
# index = GPTSimpleVectorIndex.load_from_disk('index.json')

while True:
   # Get input question from user
    question = input("Ask a question: ")

    # Use llama index to search for the answer
    response = index.query(question)

    # Print the answer
    
    print(response)
`

**Comment by logan-markewich** [comment]
I've worked on both windows and linux, and never had a problem using `pip install llama-index` (although definitely use a venv, as you usually should with python)

I think most of your issues would be fixed if you start with a fresh venv. If you are new to python, here's how to do it

Bash
```
python -m venv venv
source venv/bin/activate
pip install llama-index
```

Powershell
```
python -m venv venv
.\venv\Scripts\Activate.ps1
pip install llama-index
```

You can deactivate the venv at any time using `deactivate` (usually you'd do this before switching to another venv)

**Comment by normanlove222** [comment]
I believe you are correct. Im a newbie to that kinda stuff. Which is why
its probably a good idea for that to be mentioned in the setup page.

I thank you

Lets close this issue then 🙏
