### ISSUE TITLE
Hello I faced a small problem while using "RetrieverQueryEngine"

### ISSUE THREAD

**Issue by dglee-rbrain** [jerryjliu/llama_index#3261]
So I was trying to get response from RetrieverQueryEngine like this

**index = GPTVectorStoreIndex.from_documents(nodes, service_context=service_context)
retriever = index.as_retriever()
query_engine = RetrieverQueryEngine.from_args(retriever, response_mode='tree_summarize')
response = query_engine.query("long summary of the document")
print(str(response))**

And I do get the response just fine. The problem is somehow the response text seems to be limited to 255 tokens, so if it goes longer than that, it is cutted right in the middle of the sentence. I'd like to see it printing out longer than 255 tokens. Do you know how?

**Comment by Disiok** [comment]
Take a look at https://docs.google.com/document/d/1bLP7301n4w9_GsukIYvEhZXVAvOMWnrxMy089TYisXU/edit
