### ISSUE TITLE
is GPTSimpleVectorIndex still being used?

### ISSUE THREAD

**Issue by normanlove222** [jerryjliu/llama_index#3263]
![Screenshot (698)](https://github.com/jerryjliu/llama_index/assets/2139671/023634a3-a9b2-4d33-a11a-c7bed214ed70)

is **GPTSimpleVectorIndex** still being used? Cause I see in some places, here on the issues section, that its been replaced by another Method. 

Yet as you can see in llamahub.ai, a companion site of this project, it shows its still being used. 
Can we get some clarity, and maybe even pointed to a page that has some of the recent changes, so we can update the example code.

**Comment by markusantonuis** [comment]
I'm still using it without problems

**Comment by jerryjliu** [comment]
@normanlove222 good catch, we should update llamahub documentation. doing that now!

**Comment by normanlove222** [comment]
Cool. Cause as a newbie who loves llama_index that has cause confusion. 😊
So thank you.

**Comment by normanlove222** [comment]
So am I on my windows computer because we installed the older code. But if
someone installs using today's instructions, they will get new code and so
it won't recognize the old examples with deprecated methods. It's weird but
that is what's happening. We really have to keep deprecated methods for a
few months at least or some other solution 😊

We know things are moving fast in AI but we can at least try not to change
the method names unless really required.

🙏

**Comment by RafayKhattak** [comment]
AttributeError: 'GPTListIndex' object has no attribute 'query'

**Comment by talhaanwarch** [comment]
with what it has been replaced?

**Comment by logan-markewich** [comment]
@RafayKhattak @talhaanwarch check out the latest version of the docs: 

https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html

queries now use the query engine

```
query_engine = index.as_query_engine()
query_engine.query("my query")
```

GPTSimpleVectorIndex is now GPTVectorStoreIndex

**Comment by normanlove222** [comment]
Oh god thank you so much. 🙏

**Comment by ROZBEH** [comment]
Same in the following tow links
https://colab.research.google.com/drive/1uL1TdMbR4kqa0Ksrd_Of_jWSxWt1ia7o?usp=sharing#scrollTo=3a5cb155-cfe0-4c89-a2b4-c61d5b7cbe61

https://medium.com/@jerryjliu98/how-unstructured-and-llamaindex-can-help-bring-the-power-of-llms-to-your-own-data-3657d063e30d
