### ISSUE TITLE
query without access LLM

### ISSUE THREAD

**Issue by NaelsonAccountDrive** [jerryjliu/llama_index#3270]
I have  construction commented, disable GPT, it seems be smart answer yet, why it? 
```
# index = construct_index("docs")
```
Having info of consume tokens same ChatOpenAI commented.

INFO:llama_index.token_counter.token_counter:> [get_response] Total LLM token usage: 2048 tokens
> [get_response] Total LLM token usage: 2048 tokens

```
    index = GPTSimpleVectorIndex.load_from_disk('index.json')
    response = index.query(input_text, response_mode="compact")
```
`def construct_index(directory_path):
    max_input_size = 4096
    num_outputs = 512
    max_chunk_overlap = 20
    chunk_size_limit = 600

    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))

    documents = SimpleDirectoryReader(directory_path).load_data()
    pprint(documents)
    
    index = GPTSimpleVectorIndex(documents)

    index.save_to_disk('index.json')

    return index

def chatbot(input_text):
    index = GPTSimpleVectorIndex.load_from_disk('index.json')
    response = index.query(input_text, response_mode="compact")
    return response.response

iface = gr.Interface(fn=chatbot,
                     inputs=gr.components.Textbox(lines=7, label="Enter your text"),
                     outputs="text",
                     title="Custom-trained AI Chatbot")

# index = construct_index("docs")
iface.launch(share=True, server_port=3000)`

**Comment by Disiok** [comment]
Not sure what this is asking.
