### ISSUE TITLE
Error wile loading saved index from pinecone

### ISSUE THREAD

**Issue by raghavpatnecha** [jerryjliu/llama_index#3284]
I definned the storage context as pinecone. But now it gives me value error if I tried to load my vector store index
````
pinecone.init(
api_key=os.environ['PINECONE_API_KEY'],
environment=os.environ['PINECONE_ENVIRONMENT']
)
pinecone_index = pinecone.Index("test")

vector_store = PineconeVectorStore(
pinecone_index=pinecone_index,
)

vector_store = PineconeVectorStore(pinecone_index=pinecone_index)

storage_context = StorageContext.from_defaults(vector_store)
index = load_index_from_storage(storage_context=storage_context)`
```

Error : ValueError: No index in storage context, check if you specified the right persist_dir.

**Comment by logan-markewich** [comment]
Actually, you don't really load/persist pinecone indexes because everything is on pinecone.

Just need to pass in the storage context with the pinecone stuff and it should work 

```python
index = GPTVectorStoreIndex([], storage_context=storage_context)
```

**Comment by paulyang99810** [comment]
I am having the same problem - maybe a dumb question but once the index is instantiated for the first time, with storage context of Pinecone... how do I go and instantiate a new query engine later with the already created Pinecone vector db as the Index? 

As with @raghavpatnecha load_index_from_storage(pinecone_storage_context) is yielding an error as above. If we aren't supposed to use load_index_from_storage(), how do I go from a llama_index.vector_stores.pinecone.PineconeVectorStore to a query_engine?

**Comment by Disiok** [comment]
You can also do this now! 
```python
index = GPTVectorStoreIndex.from_vector_store(vector_store)
```

**Comment by ochapple** [comment]
Using the GPTVectorStoreIndex with Pinecone and querying using the index.as_query_engine().query (input_text) seems to be a very slow way to pull back 1 result. Is there a faster way to pull results so they are superfast, or at least what you might expect speed-wise from a single simple natural language query? What's the optimum way to get a match to a natural language query from a Vector Database?
