### ISSUE TITLE
I am trying to use HuggingFace Hub model hosted on HuggingFace using HFAPIToken and Llamaindex, but it is asking for OpenAIAPI Key. Can someone point me in the right direction? 

### ISSUE THREAD

**Issue by j-amit04** [jerryjliu/llama_index#3290]
I am trying to connect HuggingFace model hosted on HuggingFace using HFAPI Token and Llamaindex. Here is the code below, but while running this code, it says "Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)"

from llama_index import GPTListIndex, SimpleDirectoryReader, ServiceContext,GPTVectorStoreIndex
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LangchainEmbedding
from llama_index.llm_predictor import HuggingFaceLLMPredictor
import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = "hf_XXXXX"
# load in HF embedding model from langchain

embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/multi-qa-MiniLM-L6-cos-v1"))

# configure
service_context = ServiceContext.from_defaults(embed_model=embed_model)

documents = SimpleDirectoryReader('docs').load_data()
index = GPTVectorStoreIndex.from_documents(documents,service_context=service_context)

query_engine = index.as_query_engine(
    retriever_mode="embedding", 
    service_context=service_context, 
)
response = query_engine.query(
    "What is the population of India?", 
)

print(str(response))

**Comment by logan-markewich** [comment]
There's two models in llama index - embed_model and llm_predictor

You've only set the embed model, so the llm_predictor is defaulting to openai

**Comment by j-amit04** [comment]
> There's two models in llama index - embed_model and llm_predictor
> 
> You've only set the embed model, so the llm_predictor is defaulting to openai
> 
> If you want to run a local LLM, you can see the docs page here https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-huggingface-llm

Thanks for sharing the link but I would like to use the model hosted on Hugging face using HF API token, Any leads on that?

**Comment by logan-markewich** [comment]
@j-amit04 you might be able to use this https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_hub.html

The load the LLM from there, than pass the llm into the llm_predictor

```python
from llama_index import LLMPredictor, ServiceContext

llm_predictor = LLMPredictor(llm=llm)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
```

You might also need to setup the prompt helper/chunk size limit to match the specs of the LLM you pick https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-fine-grained-control-over-all-parameters

**Comment by j-amit04** [comment]
> There's two models in llama index - embed_model and llm_predictor
> 
> You've only set the embed model, so the llm_predictor is defaulting to openai
> 
> If you want to run a local LLM, you can see the docs page here https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-huggingface-llm

Thanks for sharing the link but I would like to use the model hosted on Hugging face using HF API token, Any leads on that?

> @j-amit04 you might be able to use this https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_hub.html
> 
> The load the LLM from there, than pass the llm into the llm_predictor
> 
> ```python
> from llama_index import LLMPredictor, ServiceContext
> 
> llm_predictor = LLMPredictor(llm=llm)
> service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
> ```
> 
> You might also need to setup the prompt helper/chunk size limit to match the specs of the LLM you pick https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-fine-grained-control-over-all-parameters

Thanks, it worked well.

**Comment by fransb14** [comment]
@j-amit04 could you share it please?

**Comment by lucifermorningstar1305** [comment]
@logan-markewich I tried replicating the code you mentioned earlier but somehow for me the answer is always "Empty Response". 

Here's my code:

```
llm = LLMPredictor(llm=HuggingFaceHub(repo_id="tiiuae/falcon-7b-instruct", 
                                          task="text-generation", huggingfacehub_api_token=api_key))
embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
prompt_helper = PromptHelper(
        context_window=context_window,
        num_output=num_output,
        chunk_size_limit=chunk_size_limit
    )
service_context = ServiceContext.from_defaults(
        llm_predictor=llm, prompt_helper=prompt_helper,
        embed_model=embed_model
    )
docs = SimpleDirectoryReader(path).load_data()
index = GPTListIndex.from_documents(docs, service_context=service_context)
retriever = ListIndexRetriever(index, similarity_top_k=5)
response_synthesizer = ResponseSynthesizer.from_args(
        service_context=service_context,
        response_mode="compact",
        verbose=True
    )

query_engine = RetrieverQueryEngine(
        retriever=retriever,
        response_synthesizer=response_synthesizer
    )
response = query_engine.query(query)
```
