### ISSUE TITLE
Having gpt-index/llama-index respond to simple things, like hi, thanks, etc.

### ISSUE THREAD

**Issue by scooter7** [jerryjliu/llama_index#3355]
I have an app that is querying documents and doing an excellent job providing answers based upon the content being queried. However, the chatbot responds with "none" when prompting with hi/hello/thanks, etc.

Is there a way to enable responses to simple things like that in addition to restricting the app to the content being queried?

Thanks!

**Comment by NaelsonAccountDrive** [comment]
Hi bro! You can create a dataset to answer it's similarity.

**Comment by scooter7** [comment]
Thanks! I'm working on solving it...

**Comment by logan-markewich** [comment]
You'll probably want to use a chat engine or data agent for this

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/root.html

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/root.html
