### ISSUE TITLE
load_index_from_storage: response has no attribute print_response_stream  or response_gen

### ISSUE THREAD

**Issue by Ashish5869** [jerryjliu/llama_index#3366]
After loading the indexed data from the storage it is not printing the streaming response. There is no attribute print_response_stream and response_gen.

```
llm_predictor = LLMPredictor(
    llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", openai_api_key='openai_api_key', streaming=True))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, llama_logger=llama_logger)

vector_store = WeaviateVectorStore(weaviate_client=weaviate_client, class_prefix= 'Indexing')
storage_context = StorageContext.from_defaults(vector_store=vector_store)

index =GPTVectorStoreIndex.from_documents(documents,storage_context=storage_context,service_context=service_context)
index.storage_context.persist(persist_dir='index_test')

storage_context=StorageContext.from_defaults(vector_store=WeaviateVectorStore(weaviate_client=weaviate_client),persist_dir="index_test")
index = load_index_from_storage(storage_context, service_context=service_context)
query_engine = index.as_query_engine( streaming=True)
response = query_engine.query("query)
print(dir(response))
```

OUTPUT:
`['__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'extra_info', 'get_formatted_sources', 'response', 'source_nodes']`

**Comment by Ashish5869** [comment]
Thank you

**Comment by nilevols** [comment]
My output is exactly the same as Ashish5869's.

but
`query_engine = index.as_query_engine(
    service_context=service_context,
    similarity_top_k=3,
    streaming=True,
)`
cannot solve the problem...
