### ISSUE TITLE
LLM must support streaming and set streaming=True

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#3368]
# This is my code

llm = ChatOpenAI(
  temperature=0, 
  model_name="gpt-3.5-turbo",
  frequency_penalty = 0.5,
  max_tokens=500,
  streaming=True,
)
llm_predictor = LLMPredictor(llm=llm)

prompt_helper = PromptHelper(
    max_input_size = 3500, 
    num_output = 500, 
    max_chunk_overlap = 20, 
    chunk_size_limit = 700
)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

documents = SimpleDirectoryReader('./demoDoc/').load_data()

index = GPTVectorStoreIndex.from_documents(
    documents, service_context=service_context )

query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
prompt=input("ask here:")
response_stream = query_engine.query(prompt)
response_stream.print_response_stream()

# For the above code I am getting streamed output result as expected 
# but when I use to save the index and load it and  then pass the query It is showing error as "LLM must support streaming and set streaming=True"

code for storing the index and then loading the index and querying on the loaded index
#persisting index
index.storage_context.persist('./storage/')

### rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir='./storage/')

### load index
index = load_index_from_storage(storage_context)

# Please help thanks in advance

**Comment by logan-markewich** [comment]
When you load it, pass in the service context again

`index = load_index_from_storage(storage_context, service_context=service_context)`

**Comment by sad-mathematician** [comment]
> When you load it, pass in the service context again
> 
> `index = load_index_from_storage(storage_context, service_context=service_context)`

I am passing the service context while loading the index.

```
llm_predictor = llama_index.LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo"))

storage_context = llama_index.StorageContext.from_defaults(persist_dir="./storage")
service_context = llama_index.ServiceContext.from_defaults(llm_predictor=llm_predictor)
index = llama_index.load_index_from_storage(service_context=service_context,storage_context=storage_context)
```

I still get the same error. (ValueError: LLM must support streaming and set streaming=True.)

**Comment by Disiok** [comment]
We will come up with a tutorial for showing to stream output via flask!

**Comment by vishalp-simplecrm** [comment]
Waiting For tutorial @Disiok
