### ISSUE TITLE
Custom properties in Weaviate insert

### ISSUE THREAD

**Issue by sudarshansivakumar** [jerryjliu/llama_index#3370]
Hi I'm relatively new to using Llama Index, and just started playing around with it to perform inserts into a Weaviate vector store.  I really like the simple functionality of index.insert, index.refresh, etc. that allows me to update the vector store based on changes in the source document!
While reading the documentation I understand that the Weaviate Node schema contains properties _doc_id, ref_doc_id,text,node_info,relationships_ 
However for my use case I would also like to insert some additional properties like 
* document_URL 
* document_title 
* chunk_number
* last_updated_date
.. etc.
I do not see anything in the documentation that suggests this is possible, so I'm wondering if I'm missing something or if this is currently not supported

**Comment by Disiok** [comment]
You can store additional metadata information into `extra_info` field of the `Document` object, and then it will be automatically added to the vector store as well!
