### ISSUE TITLE
Purpose of doc_id and ref_doc_id 

### ISSUE THREAD

**Issue by sudarshansivakumar** [jerryjliu/llama_index#3371]
I'm not sure if there is a support forum where I can ask about this. But I am confused about why there is a separate doc_id and ref_doc_id property in Weaviate vector stores. Here's what I did  : 
* Created a list of Documents (List[Document]) which each have a doc_id property, generated through Python's uuid library. I assumed that this doc_id would be stored as the doc_id that every Weaviate data object is supposed to have. However, what I'm seeing is that the Weaviate doc_id property is generated through a separate process (reading the code it seems like it's using the UUID library too). The doc_id that is passed by the user is instead used in ref_doc_id. Is there a reason for this behaviour. 

Because of this separation I'm not sure how exactly to maintain a mapping between each chunk and its doc_id. For instance after inserting 40 documents into a particular weaviate class I tried to insert another document which had a repeated ref_doc_id. This insert was allowed because Weaviate only checks for the doc_id being unique, and not the ref_doc_id too.

**Comment by Disiok** [comment]
Hey, sorry for the lack of clarity here.

By default, we convert each document into a list of nodes. and in this process, we auto generate new uuids for each node. that's why the ids you see are different.

You can use:
```python
nodes = [Node(d) for d in data]
index = VectorStoreIndex(node=nodes)
``` 
to directly initialize the index without text chunking and converting documents to nodes.
