### ISSUE TITLE
Do I understand correctly how embedding tips for chat works?

### ISSUE THREAD

**Issue by IvanPigarev** [jerryjliu/llama_index#3376]
I need to build an index on the basis of a pdf document (and it worked) and then make a query to the index and after getting the necessary context from it, make a query to OpenAI...

It turns out that first there is a query through Llama Index, and then another query through OpenAI? Can't this be done in one query through Llama Index?

import openai
import os

os.environ["OPENAI_API_KEY"] = "my_openai_api_key"
os.environ["INDEX_DIR"] = "tmp"

from llama_index import StorageContext, GPTVectorStoreIndex, SimpleDirectoryReader, load_index_from_storage

storage_context = StorageContext.from_defaults(persist_dir=os.environ["INDEX_DIR"])
index = load_index_from_storage(storage_context)

query_engine = index.as_query_engine()
query = "My query?"
response = query_engine.query(query)

openai.api_key = "my_openai_api_key"

prompt = 'Context: '+response.response+query

response = openai.Completion.create(
    engine="text-davinci-003", 
    prompt=prompt,
    max_tokens=1500, 
    n=1, 
    stop=None,
    temperature=0.1,
    top_p=1,
    frequency_penalty=0,
    presence_penalty=0,
)

answer = response.choices[0].text.strip()
print('Answer: '+answer)

**Comment by Disiok** [comment]
LlamaIndex already calls openai under the hood, the second part of your code is not necessary.

**Comment by IvanPigarev** [comment]
I was sure of that too, but the result was a query only on knowledge from the index. And most of the questions were answered — I don't know, it's not in the data. And I needed it to be able to answer questions more broadly than just by index! Is there such a possibility inside LlamaIndex? Unfortunately, I couldn't find it :( And in this implementation it answers very well, using both global knowledge and hint (first answer LlamaIndex). Please help me to solve this problem correctly!
