### ISSUE TITLE
KeyError: "Unknown task Context information is below.

### ISSUE THREAD

**Issue by vuvskp7** [jerryjliu/llama_index#3380]
query_engine = new_index.as_query_engine()
response = query_engine.query("What did the author do in 9th grade?")

print(response)

│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1184 in check_task        │
│                                                                                                  │
│   1181 │   │   │   │   return task, targeted_task, (tokens[1], tokens[3])                        │
│   1182 │   │   │   raise KeyError(f"Invalid translation task {task}, use 'translation_XX_to_YY'  │
│   1183 │   │                                                                                     │
│ ❱ 1184 │   │   raise KeyError(                                                                   │
│   1185 │   │   │   f"Unknown task {task}, available tasks are {self.get_supported_tasks() + ['t  │
│   1186 │   │   )                                                                                 │
│   1187

**Comment by logan-markewich** [comment]
This looks like an error with a huggingface pipeline, unrelated to llama-index.

Feel free to reach out on discord though!

**Comment by talhaqayyum89** [comment]
Any workarounds on the above problem?? please guide
