### ISSUE TITLE
Performance issues with indexing between 0.5 and 0.6

### ISSUE THREAD

**Issue by DaytimeAH** [jerryjliu/llama_index#3383]
Hi,
I use the same service_context and documents (~5MB json files) for indexing. It took about 5 minutes on version 0.5, but it took an hour on version 0.6. I'm migrating my code from 0.5 to 0.6 and very confused. Any advice is greatly appreciated. 
0.5.26
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
0.6.8
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

**Comment by marcjulianschwarz** [comment]
Leaving one more datapoint here, I am trying to index 1700 markdown files (~2.5MB) with `index = GPTVectorStoreIndex.from_documents(documents)`. It is now approaching half an hour of runtime.
Tested with 100 files before that and it took only about 40 seconds. 

I am on version `0.6.8` and running it in a notebook on Google Colab.

**Comment by logan-markewich** [comment]
google cola is severely rate limited

To speed up indexing, try increasing the batch size of the `embed_model` and setting the `embed_model` in the service context

```python
from llama_index import ServiceContext, set_global_service_context
from llama_index.embeddings.openai import OpenAIEmbedding

# default batch size is 10
embed_model = OpenAIEmbedding(embed_batch_size=50)
ctx = ServiceContext.from_defaults(embed_model=embed_model)
set_global_service_context(ctx)
```
