### ISSUE TITLE
HuggingFaceLLMPredictor not found 

### ISSUE THREAD

**Issue by DSOBoy** [jerryjliu/llama_index#3387]
Hello,

I am attempting to use the StableLM model through hugging face as a custom LLM model but have been unable to import the module 'from llama_index.llm_predictor import HuggingFaceLLMPredictor'. 

The error message is below. I have updated the package and the HuggingFaceLLMPredictor is not in the files.

ImportError: cannot import name 'HuggingFaceLLMPredictor' from 'llama_index.llm_predictor' (C:\Users\DSOBoy\AppData\Local\anaconda3\lib\site-packages\llama_index\llm_predictor\__init__.py)

Any help finding a work around for this would be greatly appreciated. Thank you.

**Comment by logan-markewich** [comment]
Are you sure you've properly updated? Maybe start with a fresh venv?

`pip show llama-index` will show the current version installed
