### ISSUE TITLE
How to get streamed response from Llama_index on Flask Based Html Page like chatgpt streamed response 

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#3388]
# Flask App Code
app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/query', methods=['POST'])
def query():
    query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
    prompt = request.form['prompt']
    prompt += " Give in html format"
    print('prompt given issss:',prompt)
    response_stream = query_engine.query(prompt)
    response = response_stream.print_response_stream()
    
    return render_template('index.html', prompt=prompt,response = response_stream)
    
    
    Here is the code for index.html 
    
    <body>
    <div class="container">
        <h1><Center>Documents Based QA Bot</Center></h1>
        <form id="queryForm" action="/query" method="post">
            <label for="prompt" >Enter a prompt:</label>
            <input type="text" id="prompt" name="prompt">
            <input type="submit" value="Submit">
        </form>
        <div id="result">
            {% if prompt %}
            <h2>Recent Prompt:</h2>
            <p>{{ prompt }}</p>
            {% endif %}
            {% if response %}
            <h2>Response:</h2>
            <p>{{ response|safe }}</p>
            {% endif %}
        </div>
    </div>
    <div class="loader" id="loader"></div>

    <script>
        const form = document.getElementById('queryForm');
        const loader = document.getElementById('loader');
        const resultDiv = document.getElementById('result');

        form.addEventListener('submit', function() {
            loader.style.display = 'block';
            resultDiv.style.display = 'none';
        });

        // If there's a response, hide the loader
        // {% if response %}
        // loader.style.display = 'none';
        // {% endif %}
    </script>
</body>
</html>

**Comment by Disiok** [comment]
You can call `response.response_gen` to get a generator, which you can iterate over to get text one token at a time to populate your page.

**Comment by vishalp-simplecrm** [comment]
Can you please provide the complete code for the same as I am very beginner in this
