### ISSUE TITLE
Passing service context results in broken responses

### ISSUE THREAD

**Issue by rishi-dhar** [jerryjliu/llama_index#3389]
Running across an interesting issue, passing service context during storage context initialization or during index.as_query_engine() calls results in query responses being broken. Getting a large string as a response with `answer answer answer answer` (see screenshot).

Removing the service context fixes the answer but then we are not able to predict the # of tokens used for each query.

![image](https://github.com/jerryjliu/llama_index/assets/23067036/46e52a3a-665d-43fa-8819-79e4f8bfd3ed)

Code for context
```
max_input_size, num_output, max_chunk_overlap = 1024, 256, 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
llm_predictor = MockLLMPredictor(
            llm=OpenAI(temperature=0, model_name="gpt-3.5-turbo")
        )

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    prompt_helper=prompt_helper,
    chunk_size_limit=1024,
)

# build storage context
storage_context = StorageContext.from_defaults()
try:
    # Attempt to read index from local storage (in storage directory)
    index = load_index_from_storage(
        storage_context, service_context=service_context
    )
    print("Loaded index from disk")
except ValueError:
    # If read from local storage fails - read from `data` folder
    documents = self.load_files()
    index = GPTVectorStoreIndex.from_documents(
        documents, service_context=service_context
    )
    index.storage_context.persist()

return llm_predictor, index.as_query_engine(service_context=service_context)
```

**Comment by logan-markewich** [comment]
Right, the mock predictor isn't actually meant for predicting real text, it's just meant to attempt to estimate token usage. Since it isn't actually an LLM, you are seeing the dummy response predicting the max number of expected tokens

Looks like it's working as intended to me?

**Comment by rishi-dhar** [comment]
I see - may be I didn't understand it correctly. We are trying to output the number of tokens estimated for each query + process that actual query.
