### ISSUE TITLE
Repeating semantic search answer

### ISSUE THREAD

**Issue by nazkhan-8451** [jerryjliu/llama_index#3391]
Using text-ada-002 to embed a document. Then using text-davinci-003 to query the document. If i ask a question like `list 5 properties of iron from the document`, each time I get different properties. How can I fix the answer (or repeat the same answer) on every query?

Is there any `args` that I can pass somewhere or use some prompt engineering?

**Comment by Disiok** [comment]
First you should make sure temperature for LLM is set to zero, but beyond that it's hard to guarantee full deterministic answers.
