### ISSUE TITLE
Typo in QUERY_RESPONSE_REFINE_PROMPT causing incorrect refine prompt

### ISSUE THREAD

**Issue by jameshknowles** [jerryjliu/llama_index#3422]
When asking the LLM to evaluate a response the following improper prompt is passed:

"We want to understand if the following query and response isin line with the context information"

With the assumed intent being:

"We want to understand if the following query and response is in line with the context information"

The base.py file has a missing character in the definition of QUERY_RESPONSE_REFINE_PROMPT.  A space was left off the first line so the "is" and "in" become "isin"

QUERY_RESPONSE_REFINE_PROMPT = (
    "We want to understand if the following query and response is"
    "in line with the context information: \n {query_str}\n"
    "We have provided an existing YES/NO answer: \n {existing_answer}\n"
    "We have the opportunity to refine the existing answer "
    "(only if needed) with some more context below.\n"
    "------------\n"
    "{context_msg}\n"
    "------------\n"
    "If the existing answer was already YES, still answer YES. "
    "If the information is present in the new context, answer YES. "
    "Otherwise answer NO.\n"
)

**Comment by Disiok** [comment]
Fixed!
