### ISSUE TITLE
Mongo collection name contains invalid character

### ISSUE THREAD

**Issue by richardeee** [jerryjliu/llama_index#3423]
Hi,

I used Azure CosmosDB for Mongo as Doc Store and Index Store, after initialized storage context, when I try to build new index, I got the error:
`OperationFailure: Collection name contains invalid character., full error: {'ok': 0.0, 'errmsg': 'Collection name contains invalid character.', 'code': 73, 'codeName': 'InvalidNamespace'}`

Here is my code:
```python
connection_string="mongodb://xx"
index_store = MongoIndexStore.from_uri(uri=str(connection_string), db_name="kg_index")
doc_store = MongoDocumentStore.from_uri(uri=str(connection_string), db_name= "doc_store")
storage_context = StorageContext.from_defaults(
            docstore=doc_store,
            index_store=index_store)
```
```python
new_index = GPTKnowledgeGraphIndex.from_documents(
    docs, 
    max_triplets_per_chunk=5,
    service_context=service_context,
    storage_context=storage_context
)
```

It seems the collection name f"{namespace}/data" is not supported, is it possible if I can use no namespace at all? Thanks.

**Comment by richardeee** [comment]
Thanks, this issue can be closed. I create custom CosmosDBDocStore and CosmosDBIndexStore to fix this issue.

**Comment by schwarztrinker** [comment]
I would appreciate a pull request into the open repository! Currently I am struggling with the same error .... @richardeee

**Comment by dgancho** [comment]
@richardeee Can you share your solution please?
