### ISSUE TITLE
How to store embedding vector when using a custom embedding model?

### ISSUE THREAD

**Issue by DZ9** [jerryjliu/llama_index#3424]
I used a custom embedding model from langchain, it is configed as follows:

`embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name=embedding_path))`

`service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper, embed_model=embed_model)`

It is configed in the service_context, which will not be stroed when I call `index.storage_context.persist`

and when I load the saved index, I need to reconfig the service_context and pass it to the index:
`index = load_index_from_storage(storage_context, service_context=service_context)`

So I found that, the persisted `vector_store.json` was empty, and the embedding vector will regenerate every time I run the code.

Is there any way to solve this problem?

**Comment by Hironsan** [comment]
After executing the following code, the embedding was stored in `storage/vector_store.json`.

```python
from llama_index import ServiceContext, LLMPredictor, GPTVectorStoreIndex, LangchainEmbedding
from langchain.chat_models import ChatOpenAI

embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
chat_model = ChatOpenAI(openai_api_key="")
llm_predictor = LLMPredictor(chat_model)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist('storage')
```

Questions:
- What version of Llama index and LangChain are you using?
- Please paste your complete code.

**Comment by DZ9** [comment]
> After executing the following code, the embedding was stored in `storage/vector_store.json`.
> 
> ```python
> from llama_index import ServiceContext, LLMPredictor, GPTVectorStoreIndex, LangchainEmbedding
> from langchain.chat_models import ChatOpenAI
> 
> embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
> chat_model = ChatOpenAI(openai_api_key="")
> llm_predictor = LLMPredictor(chat_model)
> service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
> index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
> index.storage_context.persist('storage')
> ```
> 
> Questions:
> 
> * What version of Llama index and LangChain are you using?
> * Please paste your complete code.

Version: 
llama-index                    0.6.7
langchain                      0.0.169
 ```
import torch
from langchain.llms.base import LLM
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import SimpleDirectoryReader, LangchainEmbedding, GPTListIndex, GPTTreeIndex, PromptHelper, QuestionAnswerPrompt
from llama_index import LLMPredictor, ServiceContext, LangchainEmbedding
from llama_index.indices.tree.select_leaf_embedding_retriever import TreeSelectLeafEmbeddingRetriever
from llama_index.query_engine import RetrieverQueryEngine
from llama_index import StorageContext, load_index_from_storage
from typing import Optional, List, Mapping, Any
from chatglm import ChatGLM
from config import LLM_DEVICE
import logging, csv, sys, codecs, time
max_input_size = 2048
# set number of output tokens
num_output = 200
# set maximum chunk overlap
max_chunk_overlap = 20
embedding_path = "/path/to/text2vec-large-chinese"
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name=embedding_path))
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

# define our LLM
# ChatGLM is a custom LLM defined using langchain interface
llm_predictor = LLMPredictor(llm=ChatGLM(model_name_or_path="/path/to/chatglm-6b",
                   llm_device=LLM_DEVICE))

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper, embed_model=embed_model)

# Load the your data
documents = SimpleDirectoryReader('/path/to/data').load_data()

# define prompt
QA_PROMPT_TMPL = (
    "Question:"
    "{context_str}"
    "\n---------------------\n"
    "Answer:"
)
QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_TMPL)
index = GPTListIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist()
query_engine = index.as_query_engine(retriever_mode="embedding", text_qa_template=QA_PROMPT)
```

**Comment by Disiok** [comment]
Looks like you are using the `GPTListIndex`, which does not store the embedding in the `vector_store.json`. (it's actually kept in `index_store.json`.

Looks like the embedding not saving to disk is a bug, going to fix this! 
In the meanwhile it's best to use the `VectorStoreIndex`.

**Comment by fishfree** [comment]
@Disiok Sorry to disturb you. You marked this issue as completed, then where is your commit, please?
