### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_index_struct' when loading index from load_index_from_storage 

### ISSUE THREAD

**Issue by vrubashr** [jerryjliu/llama_index#3426]
In reference to #3425 

`  # Load the storage context
    docstore = 'storage/docstore.json'
    index_store = 'storage/index_store.json'
    vector_store = 'storage/vector_store.json'
    
    # Load the index from storage
    storage_context = StorageContext.from_defaults(
        docstore=docstore,
        index_store=index_store,
        vector_store=vector_store)
    index = load_index_from_storage(storage_context)`
`doc = Document(doc_id=data_file, text=text)
    max_input_size = 4096
    num_output = 256
    max_chunk_overlap = 20
    chunk_size_limit = 600
    
    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo",max_tokens=num_output))
    prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap,chunk_size_limit=chunk_size_limit)
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
    index = GPTVectorStoreIndex.from_documents([doc], service_context=service_context)
    index.storage_context.persist(index_path)`
    
![image](https://github.com/jerryjliu/llama_index/assets/88377240/f7c61390-bd6a-4a5f-9b9c-3e3883fee8a2)

**Comment by FdBn1999** [comment]
I got the same error, did you find a solution?

**Comment by FdBn1999** [comment]
I solved the error, I defined the `storage context` like this: 
`storage_context = StorageContext.from_defaults(persist_dir=<your_persist_dir>')`

**Comment by vrubashr** [comment]
I see. I didn't solve the error yet but used the older version of llama-index. Thank you for the new solution.

**Comment by alecmolloy** [comment]
still seeing this issue on the lastest version

**Comment by alecmolloy** [comment]
seem to have fixed it by manually fixing the following index_store.json file:
 
 ```json
 {
  "index_store/data": {
    "d393cb55-ce1c-4e4e-8dbe-59a79e80df77": {
      "__type__": "vector_store",
      "__data__": {\"index_id\": \"d393cb55-ce1c-4e4e-8dbe-59a79e80df77\", \"summary\": null, \"nodes_dict\": {\"c60b9d26-8177-4e14-bcd2-ab74956b2e04\": \"c60b9d26-8177-4e14-bcd2-ab74956b2e04\", 
      \"b71e78c0-ccb9-44ff-abdd-fccac175396b\": \"b71e78c0-ccb9-44ff-abdd-fccac175396b\", \"97e75331-05bc-4d6b-9864-9e930ea62e4f\": \"97e75331-05bc-4d6b-9864-9e930ea62e4f\"}, \"doc_id_dict\": {}, \"embeddings_dict\": {}}
    }
  }
}

changing the string to an actual object, and removing the escaped double quotes, to something like this: 

```json
{
  "index_store/data": {
    "d393cb55-ce1c-4e4e-8dbe-59a79e80df77": {
      "__type__": "vector_store",
      "__data__": {
        "index_id": "d393cb55-ce1c-4e4e-8dbe-59a79e80df77",
        "summary": null,
        "nodes_dict": {
          "c60b9d26-8177-4e14-bcd2-ab74956b2e04": "c60b9d26-8177-4e14-bcd2-ab74956b2e04",
          "b71e78c0-ccb9-44ff-abdd-fccac175396b": "b71e78c0-ccb9-44ff-abdd-fccac175396b",
          "97e75331-05bc-4d6b-9864-9e930ea62e4f": "97e75331-05bc-4d6b-9864-9e930ea62e4f"
        },
        "doc_id_dict": {},
        "embeddings_dict": {}
      }
    }
  }
}
```

Works fine for me now! But why is this stringification happening in the first place?
