### ISSUE TITLE
Example for reading and writing simple index to cloud storage

### ISSUE THREAD

**Issue by SikandAlex** [jerryjliu/llama_index#3494]
I see examples for loading data from cloud storage and I've also seen the use of external cloud vector stores.

How can I read and write a simple index to cloud storage (one perhaps constructed on a few web pages)? Do I need to create a custom `StorageContext`? How can I save the index to cloud storage and then reload it from within a serverless function when a user makes an API request to a serverless cloud function?

My background is in computer vision so please excuse any naiive questions. I really appreciate this open-source tool and community.

**Comment by Disiok** [comment]
Take a look at https://gpt-index.readthedocs.io/en/latest/how_to/storage.html

**Comment by SikandAlex** [comment]
I figured this out. Thanks.
