### ISSUE TITLE
Does Llamaindex avaialble as nuget package for C# Developers 

### ISSUE THREAD

**Issue by laharicharan** [jerryjliu/llama_index#3506]
Hi Team,

I would like to understand whether Llamaindex is available as Nuget package for C# developers? so that we utilize this package in C# Apps 

And also i would like to understand whether Llamaindex is compactable to the Microsoft sematic kernel? 

Thanks,
-Charan

**Comment by Disiok** [comment]
We don't have plans to implement as C# package yet
