### ISSUE TITLE
How to change "vector_store.json" file name to "vector_store.index" for Faiss index?

### ISSUE THREAD

**Issue by zeonn** [jerryjliu/llama_index#3526]
When I use the Faiss index, the binary data file is named "vector_store.json" instead of "vector_store.index". It's a bit wrong bacause actrually it's not a JSON.

How can I specify the name of this file explicitly? Or perhaps you could make the required changes so that the file automatically gets the correct name.

**Comment by Disiok** [comment]
Oh ya, that naming is not great, but shouldn't affect anything in practice.

If you want to change it, you an call `FaissVectorStore.persist(file_path)` with the desired name

**Comment by zeonn** [comment]
calling `FaissVectorStore.persist(file_path)` causes an error: 
`TypeError: FaissVectorStore.persist() missing 1 required positional argument: 'self'`

**Comment by Disiok** [comment]
Yes, to be clear `FaissVectorStore` is the class. You need to call `persist` on an instance. Like this
```python
vector_store = FaissVectorStore(...)
vector_store.persist(...)
```
