### ISSUE TITLE
how can I stop the LLM response from being cached?

### ISSUE THREAD

**Issue by maspotts** [jerryjliu/llama_index#3539]
Hi: I've noticed that if I issue the same query string multiple times (against the same index), then although the first query takes a long time, subsequent queries return instantly: making me believe that the query response is being cached (although I'm not passing a `cache` argument to `LLMPredictor()`).  (Also: I've noticed that changing the llm (on subsequent queries) seems to have no effect, which I assume also to be due to caching?). But I can't see any evidence of a cache being updated under my home directory, or in /tmp.  Is there a way to prevent caching, so each query is executed via the API, even if it's a duplicate of a previous query?  And where is the cache file?!  Many tnanks!

**Comment by maspotts** [comment]
I did a bit more digging, and I found that all my LLM responses are being cached in a SQLite database (`~/paperqa/llm_cache.db`); that seems to be configured in the paperqa module, which I import in the same script: but I can't why it's causing llama_index to use that cache file: it's not explicitly setting `langchain.llm_cache`.  I've found a workaround, which is to explicitly set `langchain.llm_cache = InMemoryCache()`, but I wish I understood how the paperqa module is able to affect the LLM caching of llama_index (in the same script)!

**Comment by Smyja** [comment]
> I did a bit more digging, and I found that all my LLM responses are being cached in a SQLite database (`~/paperqa/llm_cache.db`); that seems to be configured in the paperqa module, which I import in the same script: but I can't why it's causing llama_index to use that cache file: it's not explicitly setting `langchain.llm_cache`. I've found a workaround, which is to explicitly set `langchain.llm_cache = InMemoryCache()`, but I wish I understood how the paperqa module is able to affect the LLM caching of llama_index (in the same script)!

there's a paperqa module? wow

**Comment by maspotts** [comment]
paperqa is very cool: it's also built on top of langchain, is very minimal & hard-coded (compared to llama_index) , but it does a very nice job of extracting document metadata and propagating it as references with latex-style citations:

https://github.com/whitead/paper-qa

I'm getting nicer 'neural search' responses out-of-the-box from paperqa, but I'm relying on llama_index to build more complicated pipelines.
