### ISSUE TITLE
Errors occur when reading special strings such as spaces in repository readers.

### ISSUE THREAD

**Issue by takanomizuki** [jerryjliu/llama_index#3586]
Exception occurred: ValueError
Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...} `.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<| endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.
  File "/Users/takanomizuki/george/keywords/vectorstore-create-repository-folder-English.py", line 208, in create_index_from_pdf
    index = GPTVectorStoreIndex.from_documents(
  File "/Users/takanomizuki/george/keywords/vectorstore-create-repository-folder-English.py", line 224, in <module
    create_index_from_pdf(use_model_path)
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...} `.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<| endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.

↓Error line

# Create a GPTVectorStoreIndex instance with the specified USEMultilingualEmbedding instance and custom service context
    index = GPTVectorStoreIndex.from_documents(
        documents=documents, service_context=service_context
        service_context=service_context,.
    )

**Comment by justinrfenn** [comment]
Noticed the same thing when running the [GithubRepositoryReader example](https://gpt-index.readthedocs.io/en/latest/examples/data_connectors/GithubRepositoryReaderDemo.html).

The <|endoftext|> token causing the example to fail is [here](https://github.com/search?q=repo%3Ajerryjliu%2Fllama_index%20%3C%7Cendoftext%7C%3E&type=code) in case it's useful.

**Comment by rheaton64** [comment]
I also ran into this same error. I used the bs4 web reader on the llama-index readthedocs site. The error occurred when I tried to parse the loaded docs into nodes, seems to be coming from the tokenizer in the text splitter
