### ISSUE TITLE
load graph from disk

### ISSUE THREAD

**Issue by rucieryi369** [jerryjliu/llama_index#3638]
new_storage_context = StorageContext.from_defaults(persist_dir=f'./storage/root')

# load index
new_graph = load_graph_from_storage(
    new_storage_context, root_id=graph.root_id, service_context=service_context
)

new_query_engine = new_graph.as_query_engine()
new_response = new_query_engine.query("test query")

When I want to load graph, get 'KeyError:' . It look like can't find the graph doc

**Comment by JaedongLee** [comment]
I encountered the same problem, how did you solve it?

**Comment by pedrohba1** [comment]
In my case, the problem was that I was loading the context from the incorrect persist dir. In the examples, it's commonly used  `storage/root` but I used `storage/graph` instead, for example.
