### ISSUE TITLE
Add weaviate 's filter function

### ISSUE THREAD

**Issue by weishu27** [jerryjliu/llama_index#3651]
This project is awesome! It finished a lot of things I want to do and greatly reduces my workload. 
But in actual scenarios, the filtering function of the vectorsore is very much needed. I wonder if the developers have considered adding this function in the future? Thank you so much

**Comment by Disiok** [comment]
Definitely. We are actively adding metadata filtering support. Right now it works for Pinecone, Chroma and a few other ones.

**Comment by Disiok** [comment]
Would definitely appreciate a contribution here!
