### ISSUE TITLE
Llama Index knows only the knowledge from the Index, nothing else.

### ISSUE THREAD

**Issue by IvanPigarev** [jerryjliu/llama_index#3706]
LlamaIndex already calls openai under the hood, the second part of your code is not necessary.

_Originally posted by @Disiok in https://github.com/jerryjliu/llama_index/issues/3376#issuecomment-1548324665_

-------

I was sure of that too, but the result was a query only on knowledge from the index. And most of the questions were answered — I don't know, it's not in the data. And I needed it to be able to answer questions more broadly than just by index! Is there such a possibility inside LlamaIndex? Unfortunately, I couldn't find it :( And in this implementation it answers very well, using both global knowledge and hint (first answer LlamaIndex: prompt = 'Context: '+ response.response + query). Please help me to solve this problem correctly!

The answers with the second query are radically different in quality! And where do you configure the language model, temperature, and other parameters for the query within llamaIndex? I didn't find such parameters, although it seems logical to have them.

**Comment by reinershir** [comment]
trying to use `agent_chain`
```python
agent_chain = create_llama_chat_agent(
        toolkit,
        llm,
        memory=memory,
        verbose=True
    )

```
`agent_chain.run()`

**Comment by logan-markewich** [comment]
You can customize the prompt templates, or use a chat engine/data agent

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/usage_pattern.html

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/root.html
