### ISSUE TITLE
response truncated

### ISSUE THREAD

**Issue by mccoysc** [jerryjliu/llama_index#3732]
When using index.as_query_engine().query(), sometimes the responses returned may be truncated and incomplete,how i can get the complete response?
@jerryjliu

**Comment by Lupanbr** [comment]
I`m also getting the same error.
I already looked at other similar posts and they all tell to adjust the llm_predictor  which I already did and the problem still happens.

Here`s my code:

`import os
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, LLMPredictor
from llama_index import StorageContext, load_index_from_storage
from langchain.llms import OpenAI


# Substitua 'YOUR_OPENAI_API_KEY' pela sua chave da API da OpenAI
os.environ["OPENAI_API_KEY"] = (my key)

# Substitua 'data' pelo caminho para a pasta que contém seus arquivos Docx convertidos para .txt
documents = SimpleDirectoryReader('.\\docs').load_data()

# Cria um índice a partir dos documentos
llm_predictor = LLMPredictor(llm=OpenAI(
    temperature=0, model_name="text-davinci-003", max_tokens=2048))


index = GPTVectorStoreIndex.from_documents(
    documents, llm_predictor=llm_predictor)

# Para persistir o índice em disco
index.storage_context.persist()

# Para recarregar o índice do disco
storage_context = StorageContext.from_defaults(persist_dir='./storage')
index = load_index_from_storage(storage_context)

query_engine = index.as_query_engine()
response = query_engine.query(
    "Write an article about bicicles")

# Abre o arquivo em modo de escrita
with open('output.txt', 'w') as f:
    f.write(str(response) + '\n')
    f.write("-------" + '\n')
    f.write("Fontes:" + response.get_formatted_sources() + '\n')`

**Comment by logan-markewich** [comment]
You can set the max_tokens on the llm object

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-changing-the-number-of-output-tokens-for-openai-cohere-ai21

**Comment by logan-markewich** [comment]
Feel free to reach out on discord with any other questions!
