### ISSUE TITLE
In version 0.6.8 and and 0.6.9, PDFReader dependency has changed to pypdf instead of PyPDF2

### ISSUE THREAD

**Issue by akhiljain** [jerryjliu/llama_index#3735]
In version 0.6.8 and and 0.6.9, PDFReader dependency has changed to pypdf instead of PyPDF2. pypdf is not the up to date and doesn't read the pdf properly. please revert it back to PyPDF2

**Comment by Disiok** [comment]
Hey, could you give more detail on issue with pypdf? pypdf is the maintained in favor of PyPDF2: https://pypi.org/project/PyPDF2/
