### ISSUE TITLE
LLama Toolkit integration seems to be broken for Vector index.

### ISSUE THREAD

**Issue by akhiljain** [jerryjliu/llama_index#3736]
when building a toolkit and creating llama chat agent (llam_index v0.6.9 and langchain v0.0.175), it doesn't work against the data in vector store and instead creates a generic chat agent. Any pointers on whats missing here?

    from langchain.agents import Tool
    from langchain.chains.conversation.memory import ConversationBufferMemory
    from langchain.chat_models import ChatOpenAI
    from llama_index.langchain_helpers.agents import LlamaToolkit, create_llama_chat_agent, IndexToolConfig
    
    query_engine = index.as_query_engine(verbose=True,text_qa_template=QA_PROMPT,streaming=True)    
    index_configs = []
    tool_config = IndexToolConfig(
        query_engine=query_engine, 
        name=f"Vector Index",
        description=f"Vector index",
        tool_kwargs={"return_direct": True, "return_sources": True},
    )
    index_configs.append(tool_config)
    toolkit = LlamaToolkit(
        index_configs=index_configs
    )
    memory = ConversationBufferMemory(memory_key="chat_history")
    llm = ChatOpenAI(temperature=TEMPERATURE, model_name=OPENAI_MODEL_ID)
    agent_chain = create_llama_chat_agent(
        toolkit,
        llm,
        memory=memory,
        verbose=True
    )
     response = agent.run(query)

**Comment by MuhammadBasitMukhtar** [comment]
Have you got answer to this issue?

**Comment by nmkotoro** [comment]
I am waiting too for an answer to this issue

**Comment by logan-markewich** [comment]
The toolkit is pretty un-maintained right now. Would welcome a contribution, but tbh I would recommend using our own data agents

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html#module-guides
