### ISSUE TITLE
Google LLM

### ISSUE THREAD

**Issue by chadbr** [jerryjliu/llama_index#3749]
Are there any plans to support the Google LLM's as a backend model?

**Comment by Disiok** [comment]
which Google LLM?

**Comment by chadbr** [comment]
https://developers.generativeai.google/products/palm

**Comment by stasaki** [comment]
Supporting Google's APIs for Generative AI and Vertex AI is very helpful.  

https://github.com/hwchase17/langchain/issues/4532#issuecomment-1545622547

**Comment by logan-markewich** [comment]
Palm is now supported!

https://gpt-index.readthedocs.io/en/latest/examples/llm/palm.html#palm

You can create the Llm and directly set it in the service context

```python
from llama_index import ServiceContext, set_global_service_context

ctx = ServiceContext.from_defaults(llm=llm)
set_global_service_context(ctx)
```
