### ISSUE TITLE
No parameter named "graph_configs" in LlamaToolkit 

### ISSUE THREAD

**Issue by ttu-nguyen** [jerryjliu/llama_index#3750]
Hello, I followed the example [here](https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb), but currently we don't have any attribute `graph_configs` in `LlamaToolkit` class. This class only support `index_configs`

**Comment by Disiok** [comment]
Ah looks like the notebook is somewhat outdated. Will update this!

**Comment by ttu-nguyen** [comment]
I can do it if you want. please refer me to good resources to make contribution. thanks.

**Comment by samzoozi** [comment]
I have faced the same issue. Hey @Disiok if graph_configs is removed, Is there an alternative way to pass that to LlamaToolkit now? 
```
toolkit = LlamaToolkit(
    index_configs=index_configs,
    graph_configs=[graph_config]
)
```
