### ISSUE TITLE
Getting Broken Words or not getting words in proper format when using generator response_stream.response_gen

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#3783]
Getting Broken Words or not getting words in proper format when using generator 

Using this below code to stream the result but getting broken words 
for example 
Suppose as su ppose 
Postman as POST MAN
Velocity as Velo city

def generate_response():
        for text in response_stream.response_gen:
                yield f"data: {text}\n\n"
                print(text)
    return Response(stream_with_context(generate_response()), mimetype='text/event-stream')
    
    
Please Help for this

As I want response in HTML format it's giving response like

<p
>
Smart
search
 is
 a
 search
 functionality
 implemented
 using
 pre
-trained
 B
ERT
 (
Bid
irectional
 Encoder
 Represent
ations
 from
 Transformers
)

Spaces within the word

**Comment by Disiok** [comment]
hmm interesting, we haven't noticed this problem before. Do you have a way to help us reproduce this issue easily?

**Comment by vishalp-simplecrm** [comment]
Sure this is my complete code 

import os
from llama_index.node_parser import SimpleNodeParser
from flask import Flask, render_template, request, Response,stream_with_context,jsonify,make_response
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from llama_index import LLMPredictor, PromptHelper, ServiceContext, download_loader,MockLLMPredictor,MockEmbedding,GPTVectorStoreIndex
from langchain.chat_models import ChatOpenAI
from IPython.core.display import HTML
from llama_index import StorageContext, load_index_from_storage
import logging
import sys
import requests
import json,urllib
import sseclient
import time
from flask import Flask
from flask_cors import CORS, cross_origin
app = Flask(__name__)
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'



logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
logging.getLogger('flask_cors').level = logging.DEBUG


os.environ['OPENAI_API_KEY'] = 'my api key'

# def authorize_gdocs():
#     google_oauth2_scopes = [
#         "https://www.googleapis.com/auth/drive.readonly",
#         "https://www.googleapis.com/auth/documents.readonly"
#     ]
#     cred = None
#     if os.path.exists("token.pickle"):
#         with open("token.pickle", 'rb') as token:
#             cred = pickle.load(token)
#     if not cred or not cred.valid:
#         if cred and cred.expired and cred.refresh_token:
#             cred.refresh(Request())
#         else:
#             flow = InstalledAppFlow.from_client_secrets_file("client_secrets.json", google_oauth2_scopes)
#             cred = flow.run_local_server(port=0)
#         with open("token.pickle", 'wb') as token:
#             pickle.dump(cred, token)

# authorize_gdocs()
# #Drive_loader
# GoogleDriveReader = download_loader('GoogleDriveReader')
# folder_id = '1AuhkobVmt0Et0lIrEU0swvwavwXRtJYi'
# loader = GoogleDriveReader()
# documents = loader.load_data(folder_id=folder_id)

llm = ChatOpenAI(
  temperature=0, 
  model_name="gpt-3.5-turbo",
#   frequency_penalty = 0.5,
  max_tokens=500,
  streaming=True,
)
llm_predictor = LLMPredictor(llm=llm)

prompt_helper = PromptHelper(
    max_input_size = 3500, 
    num_output = 500, 
    max_chunk_overlap = 20, 
    chunk_size_limit = 700
)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

# index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context )


#persisting index
# index.storage_context.persist('C:\\Users\\Lenovo\\Desktop\\DocumentBot\\storage')

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="./storage")
# load index
index = load_index_from_storage(storage_context,service_context=service_context)



# Flask App Code
app = Flask(__name__)

@app.route('/')
@cross_origin()
def home():
    return render_template('index.html')


@app.route('/query', methods=['POST'])
@cross_origin()
def query():
    query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
    prompt = request.json
    # prompt['prompt'] += " Give in html format"
    print('prompt given issss:',prompt)
    response_stream = query_engine.query(prompt['prompt']) 
    response_stream.print_response_stream()
    def generate_response():
        for text in response_stream.response_gen:
                yield  f"data:{text}\n\n" 
                print(text)
    return Response(stream_with_context(generate_response()), mimetype='text/event-stream')

if __name__ == '__main__':
    app.run(debug=True)
    
#Using postman to test the result also printing text under generator loop their also getting the same broken one

**Comment by vishalp-simplecrm** [comment]
![image](https://github.com/jerryjliu/llama_index/assets/115548851/25bba3bd-945f-4880-91ab-045579a06ea8)

**Comment by vishalp-simplecrm** [comment]
@Disiok Any progress on this need this urgently please help thanks in advance

**Comment by vishalp-simplecrm** [comment]
@Disiok @jerryjliu Please check this
