### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by jacinticow** [jerryjliu/llama_index#3802]
<img width="1126" alt="Screenshot 2023-05-23 at 20 10 17" src="https://github.com/jerryjliu/llama_index/assets/48676437/1cf0d28f-ac3c-443c-8ff8-325f92660142">
When importing either the GPTVectorStoreIndex or SimpleDirectoryReader I get the TypeError. I am using python version 3.10.10, with llama-index version 0.6.9.

**Comment by logan-markewich** [comment]
Just merged a fix. Should be in the next release! Seems to be related to some langchain typing dependencies

**Comment by spoot82** [comment]
@logan-markewich I am getting this exact same TypeError again after updating the package last Friday. I tried updating llama_index today, but it doesn't resolve the issue. I now have llama-index version 0.7.4, langchain 0.0.228 and python version 3.8.

**Comment by logan-markewich** [comment]
@spoot82 can you try with a fresh venv?

**Comment by spoot82** [comment]
@logan-markewich yes a fresh venv works, thanks!

**Comment by tubakadriye** [comment]
I'm gettingthe same error when I try to import the following on jupyter notebook. Is there a way to fix it?
from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex

**Comment by hammer** [comment]
I am seeing this error with Python 3.9.16, llama-index 0.7.9, and langchain 0.0.234, when I try to run the import at the top of [10k_sub_question.ipynb](https://github.com/jerryjliu/llama_index/blob/main/docs/examples/usecases/10k_sub_question.ipynb):

`from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex`

**Comment by logan-markewich** [comment]
@tubakadriye @hammer it seems to be related to langchain not limiting the pydantic version 🤔

`pip install --upgrade pydantic==1.10.0 typing-extensions==4.5.0` seemed to fix it for me

**Comment by ccampagna1** [comment]
Hi there, I'm facing the same issue here trying to import SimpleDirectoryReader. 

![image](https://github.com/run-llama/llama_index/assets/38267685/20e0b126-d88c-4c41-b13e-d28d2b8cf1cc)

I'm using poetry inside an anaconda env. The dependencies look fine (showed in the image) 

any ideas?
Thanks!

**Comment by logan-markewich** [comment]
@ccampagna1 making a fresh env with llama-index works fine for me.
