### ISSUE TITLE
TypeError when importing GPTVectorStoreIndex with Python 3.10.11 and llama_index==0.6.10

### ISSUE THREAD

**Issue by apptaro** [jerryjliu/llama_index#3834]
from llama_index import GPTVectorStoreIndex
raises
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

works fine with llama_index==0.6.9

![image](https://github.com/jerryjliu/llama_index/assets/998626/93fded1f-fa0d-4bd9-b908-ff70a03fc23b)

**Comment by jerryjliu** [comment]
sorry about this! I think #3837 should fix

**Comment by isliudong** [comment]
Thanks, it seems to be working

**Comment by apptaro** [comment]
Confirmed that the bug is fixed in llama_index==0.6.11.
Thank you for the quick response!!
