### ISSUE TITLE
storage_context.persist() does not creates vector_index.json file

### ISSUE THREAD

**Issue by abhinavmishra590** [jerryjliu/llama_index#3847]
I am trying to persist index to storage after using ChromaDB collection. When I try to reload the index, it throws error `ValueError: No existing llama_index.vector_stores.simple found at ./storage_demo/vector_store.json, skipping load.`

I notice that under persist dir it only has `doctstore.json` and `index_store.json`

Here is my store code:

```
UnstructuredReader = download_loader("UnstructuredReader")
    loader = UnstructuredReader()
    documents = loader.load_data(file=Path('./input/' + filename))

    # create chroma vector store
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = GPTVectorStoreIndex.from_documents(documents, storage_context=storage_context)

    
    # save index to remote blob storage
    vector_index.set_index_id("vector_index")
    
    index.storage_context.persist(persist_dir = './storage_demo')
```

Here is my code to reload:

```
sc = StorageContext.from_defaults(persist_dir='./storage_demo')
    index2 = load_index_from_storage(sc,'vector_index')
    query_engine = index2.as_query_engine()
    response = query_engine.query("What did the author do growing up?")
    return response
```

My Llamaindex version is `0.6.9` and my langchain version is `0.0.176`

**Comment by logan-markewich** [comment]
When persisting to a remote vector store, everything is actually persisted on the remote vector store itself. 

You should be able to reconnect like so

```python
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTVectorStoreIndex([], storage_context=storage_context)
```

**Comment by allendred** [comment]
vector_store = WeaviateVectorStore(weaviate_client=client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTVectorStoreIndex([], storage_context=storage_context,service_context=service_context)
# index = load_index_from_storage(storage_context, service_context=service_context)   
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total embedding token usage: 23 tokens
INFO:llama_index.token_counter.token_counter:> [get_response] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [get_response] Total embedding token usage: 0 tokens
None

There is no clear guidance in the documentation on how external storage is read

**Comment by logan-markewich** [comment]
Did you previously build an index with weaviate+Llama Index? Or are you just connecting to a pre existing db you had on weaviate?

**Comment by allendred** [comment]
> @allendred Did you previously build an index with weaviate+Llama Index? Or are you just connecting to a pre existing db you had on weaviate?

Yes, I used docker to start the vector server before. The following is my storage operation.  After execution, the stored files can be seen on the server. The presist operation is also performed locally, and there are files under the local folder
```
vector_store = WeaviateVectorStore(weaviate_client=client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTVectorStoreIndex.from_documents(documents, storage_context=storage_context,service_context=service_context)
PRESIST_DIR = 'data/test'
index.storage_context.persist(PRESIST_DIR) 
```
![image](https://github.com/jerryjliu/llama_index/assets/4343664/19ecae31-682d-46a2-8970-4b76912f2d70)
<img width="958" alt="image" src="https://github.com/jerryjliu/llama_index/assets/4343664/88180702-cab0-452a-a814-4de161c7d91f">

**Comment by logan-markewich** [comment]
Right, but if you are using weaviate, there's no need to call persist (if you look at the files, you won't find much in there)

Everything is stored on weaviate. 

So, you should be able to connect back to the index using the same settings for the vector store 🤔

**Comment by allendred** [comment]
```python
{'_docstore': <llama_index.storage.docstore.simple_docstore.SimpleDocumentStore object at 0x7f0f93fedc00>,
 '_index_struct': IndexDict(index_id='86ad2bf3-dc0b-4880-b5bd-65286746f902',
                            summary=None,
                            nodes_dict={},
                            doc_id_dict={},
                            embeddings_dict={}),
 '_service_context': ServiceContext(llm_predictor=<llama_index.llm_predictor.base.LLMPredictor object at 0x7f0f72bfeb00>,
                                    prompt_helper=<llama_index.indices.prompt_helper.PromptHelper object at 0x7f0f72bfe710>,
                                    embed_model=<llama_index.embeddings.langchain.LangchainEmbedding object at 0x7f0f72cd6230>,
                                    node_parser=<llama_index.node_parser.simple.SimpleNodeParser object at 0x7f0f72f79f90>,
                                    llama_logger=<llama_index.logger.base.LlamaLogger object at 0x7f0f72f79e40>,
                                    callback_manager=<llama_index.callbacks.base.CallbackManager object at 0x7f0f72bfe590>,
                                    chunk_size_limit=None),
 '_storage_context': StorageContext(docstore=<llama_index.storage.docstore.simple_docstore.SimpleDocumentStore object at 0x7f0f93fedc00>,
                                    index_store=<llama_index.storage.index_store.simple_index_store.SimpleIndexStore object at 0x7f0f95583f10>,
                                    vector_store=<llama_index.vector_stores.weaviate.WeaviateVectorStore object at 0x7f0f72f78c40>),
 '_use_async': False,
 '_vector_store': <llama_index.vector_stores.weaviate.WeaviateVectorStore object at 0x7f0f72f78c40>}
INFO:llama_index.token_counter.token_counter:> [retrieve] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [retrieve] Total embedding token usage: 23 tokens
INFO:llama_index.token_counter.token_counter:> [get_response] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [get_response] Total embedding token usage: 0 tokens
None
``` 

I printed index and it seems _index_struct is missing

**Comment by logan-markewich** [comment]
Right, because when you use weaviate (or most 3rd party vector stores) all the index data is stored in the vector db
