### ISSUE TITLE
`document_exists` always returns False

### ISSUE THREAD

**Issue by cheerlessDreamer** [jerryjliu/llama_index#3854]
I have a very simple function below that builds an index with a single document, and then tests whether the `doc_id` provided exists in the index:

```
def build_and_check_doc_id():
    index = GPTVectorStoreIndex([])
    document = Document(text="Here is some text", doc_id="document_id")
    index.insert(document)

    document_id_1 = "document_id"
    document_id_2 = "test"
    
    print(index.docstore.document_exists(document_id_1)) # Should be True
    print(index.docstore.document_exists(document_id_2)) # Should be False
```

Both the print statements return False. I think that this is wrong. Could someone verify that I am correct in assuming that the first should be True, and the second False?

**Comment by cheerlessDreamer** [comment]
Thanks for your explanation, @logan-markewich 
I will mark this as closed in that case.

**Comment by cheerlessDreamer** [comment]
@logan-markewich Just a quick follow up - since the `doc_id` of a Document actually refers to a node(s), this presumably means that the `delete` method doesn't work as expected. The same goes for the `update` method. They both take a `doc_id` as an input

I built a quick test as below, and can confirm that the document still exists in the index after running the function, when it shouldn't:

```
def delete_doc_id(doc_id):
    persist_dir = './storage/'
    storage_context = StorageContext.from_defaults(persist_dir=persist_dir)
    index = load_index_from_storage(storage_context=storage_context)
    index.delete(doc_id=doc_id)    
    index.storage_context.persist()
```

**Comment by logan-markewich** [comment]
Both documents and nodes have an attribute called doc_id

But yes you are right, these methods refer to the doc_ids of nodes

**Comment by logan-markewich** [comment]
You are saying delete does not actually remove it from the docstore, only the index_struct.
?

**Comment by cheerlessDreamer** [comment]
That's correct - the Docstore retains the document and original text after running the delete method. It only appears to be deleted from index_store.json

**Comment by logan-markewich** [comment]
This should be fixed, or at least much clearer, see this page for detailed guide/usage! Docs are not deleted from the docstore by default (since multiple indexes can be sharing the same docstore), but you can set a flag to force the delete 

https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/document_management.html
