### ISSUE TITLE
how can get confidence score/level of response 

### ISSUE THREAD

**Issue by noke8868** [jerryjliu/llama_index#3870]
for example 
query_engine = index.as_query_engine()
response = query_engine.query("What's the anwser to the question?")
is there any way to get confidence score/level of the response ?
thank you

**Comment by logan-markewich** [comment]
OpenAI doesn't support confidences for responses as far as I know

But if you are using a vector index, you can get the similarity scores for each node used to create the response. In my experience, anything over 0.77 is usually a good sign

`response.source_nodes[0].score` will get the score of the first source node

**Comment by noke8868** [comment]
Thanks so much for your response.
i actually used GPTVectorStoreIndex. 
the response is a list like this [{'generated_text': 'Mr. Tester'}]
don't have '.source_nodes[0].score'; 
any help is really appreciated . 

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
query_engine = index.as_query_engine()
response = query_engine.query("What's the anwser to the question?")

**Comment by noke8868** [comment]
Thank you for your reply. here's full source code running no problem
in colab. 
the line : ret=self.pipeline(prompt, max_length=9999)  generates a list and
final output is a string

can you help to look this?
thank you!

---------------------------------------------------------------
from llama_index import SimpleDirectoryReader, LangchainEmbedding, GPTListIndex,GPTVectorStoreIndex, PromptHelper
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LLMPredictor, ServiceContext,download_loader
import torch
from langchain.llms.base import LLM
from transformers import pipeline
from typing import Mapping

class customLLM(LLM):
    model_name = "google/flan-t5-large"
    pipeline = pipeline("text2text-generation", model=model_name, device=0, 
                        model_kwargs={"torch_dtype":torch.bfloat16})

    def _call(self, prompt, stop=None):
      ret=self.pipeline(prompt, max_length=9999)
      print(ret)
      return ret[0]["generated_text"]
 
    def _llm_type(self):
        return "custom"

    
    @property
    def _identifying_params(self) -> Mapping[str, any]:
        """Get the identifying parameters."""
        return {"n": "nothing important"}


llm_predictor = LLMPredictor(llm=customLLM())

JSONReader = download_loader("JSONReader")
loader = JSONReader()
documents = loader.load_data('/content/llama_index/data/test.json')

hfemb = HuggingFaceEmbeddings()
embed_model = LangchainEmbedding(hfemb)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model)
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

query_engine = index.as_query_engine()
response = query_engine.query("what's the question?")

print(response)
print('---done--------------')

**Comment by logan-markewich** [comment]
Right I see, the response I'm talking about is not from the pipeline, but from query_engine.query()

```python
...

response = query_engine.query(....)
print(response.source_nodes)
print(response.source_nodes[0].score)
```

This shows how to get the similarity score of each source node

**Comment by noke8868** [comment]
works. thank you so much!

**Comment by logan-markewich** [comment]
Nice! 🫡💪

**Comment by mirallm** [comment]
my response.source_nodes[0] gives


[{'page_label': '11', 'file_name': 'b23.pdf', 'allowed_siteGroup_ids': ['3', '4', '5'], 'allowed_siteGroup_display_names': ['eors'], 'allowed_group_ids': ['e67e'],, 'url': 'https://ke/b23.pdf', 'file_path': None}}]

There is no score. is there something wrong that I am doing. I am using QdrantVectorStore and astreamchat

@dosu

**Comment by mirallm** [comment]
when i do source_nodes[0].score, i get this error           ^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'dict' object has no attribute 'score'
    @dosu

**Comment by mirallm** [comment]
@dosu

when i use : 
 response = retriever.retrieve(query)
        for node in response:
            print("node", node.score)
            print("node", node.text)
            print("node", node.metadata)
    
    
    i can get it 
    
    but when i use 
    sync def setup_chatengine(self):

   
        
        self.chat_engine = self.index_handler.vector_index.as_chat_engine(
            chat_mode="condense_plus_context",
            memory=self.memory,
            llm=self.llm,
            context_prompt=(
                "You are a chatbot, You always answer in the language of the query."
                "You only answer questions based on the context"
                "Here are the relevant documents for the context:\n"
                "{context_str}"
                "\nInstruction: Use the previous chat history, or the context above, to interact and help the user."
                "Do NOT answer questions that are not related to the context or any normal interactions. always say I am sorry in that case."
            ),
            verbose=False,
            streaming=True,
            use_async=True
   
        )


    async def get_response(self, text: str):
        try:


        
            response = await self.chat_engine.astream_chat(text)
            
            i cant get it 
            
            can you please let me know with astreamchat

**Comment by mirallm** [comment]
@dosu
