### ISSUE TITLE
filename_as_doc_id 

### ISSUE THREAD

**Issue by elmegatan26** [jerryjliu/llama_index#3873]
Finally upgraded to version 0.6 (tried with 0.6.8, 0.6.9 and 0.6.10) and having issues passing in file name as doc_id. For context, from the tutorial at https://gpt-index.readthedocs.io/en/latest/guides/tutorials/fullstack_app_guide.html

` if request.form.get("filename_as_doc_id", None) is not None:
            manager.insert_into_index(filepath, doc_id=filename)`

I am passing in the filename param as instructed but when reviewing all responses I'm am seeing the auto-generated doc_id. Is anyone having similar issue?

**Comment by logan-markewich** [comment]
Input documents get broken into nodes.

Every node that comes from a documents gets an auto-generated doc_id, but the original ID from the input document is stored on node.ref_doc_id
