### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by elderguardian16** [jerryjliu/llama_index#3883]
Hi, i tried to install llamaindex on my pc but when i prompt import llama_index the python console crashes and give me back this error: Illegal instruction (core dumped). Some specs of my old pc that i use as a multi-purpose server:

- SO: mint "vera" 21.1
- RAM: 8gb 
- CPU: Intel Core DUO quad q6600
- GPU: nvidia gt730 2gb 
- SSD kingdian 240

I've tried installing older version of llamaindex but i haven't obtain nothing, i think that can be something that can it's correlated with cpu instruction but on the docs i haven't found anything on that. If someone knows a solution.... Thanks in advice.

**Comment by Disiok** [comment]
hmm haven't seen this before. not sure what we can do here since it would be hard to reproduce
