### ISSUE TITLE
SubQuestionQueryEngine raises an error   at line:  query_engine = self._query_engines[sub_q.tool_name] KeyError: ''

### ISSUE THREAD

**Issue by bespaloff** [jerryjliu/llama_index#3894]
Hi! 
As always thank you for amazing tool, really appreciate your passion. I have been playing with SubQuestionQueryEngine and after few iterations of self-asking it threw an error:

```console
  File "somefolder/.venv/lib/python3.11/site-packages/llama_index/query_engine/sub_question_query_engine.py", line 124, in aquery_subq
    query_engine = self._query_engines[sub_q.tool_name]
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: ''
```
My code when I am using this is basically copy paste from tutorial:
```python
vector_store = FaissVectorStore.from_persist_dir('./storage')
docstore=SimpleDocumentStore.from_persist_dir(persist_dir='./storage/')
index_store=SimpleIndexStore.from_persist_dir(persist_dir='./storage/')
storage_context = StorageContext.from_defaults(  vector_store=vector_store,index_store=index_store,docstore=docstore)
index = load_index_from_storage(storage_context=storage_context)
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo" , request_timeout=120))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, chunk_size_limit=2048)
query_engine = index.as_query_engine(
    use_async=True, 
            similarity_top_k=1,
            service_context=service_context,
            verbose=True
)
query_engine_tools = [
    QueryEngineTool(

        query_engine=query_engine, 
        metadata=ToolMetadata(name='pg_essay', description='UK rules for taxation, statuary test')
    )
]
query_engine_ = SubQuestionQueryEngine.from_defaults(query_engine_tools=query_engine_tools)

query = "\nMrs Baker, who has been UK resident for 5 years but ...."

response =  query_engine_.query(query)
```
I printed sub_q before the error and it looks like this:

```console
sub_question="What is Mrs Baker's UK employment income for 2021/22" tool_name=''
sub_question="What is Mrs Baker's foreign dividend income for 2021/22" tool_name=''
sub_question='Has Mrs Baker made any remittances to the UK' tool_name=''
```

Seems that it is a llm output that gives unidentified tool. Should prompt be improved to prevent this? Also could a "human" could be used to answer this question anyhow or how to loop back the questions itself, because the answer was mentioned there initially?

**Comment by Disiok** [comment]
Hmm, surprising to me that it's making mistake like this. 

Curious did you try different models/tool names? In my experience it's been pretty robust, so I wonder what's wrong here.

**Comment by bespaloff** [comment]
@Disiok So I figured to the issue. 
SubQuestionQueryEngine.from_defaults uses a default LLMPredictor to formulate subquestions. I think it is gpt-3.5 with some small amount of tokens. Since my question is complicated the output of tokens is longer and LLM returned only part of json. To change it I created custom service context and passed it in question_gen parameter:
```python
llm_predictor_= LLMPredictor(llm=ChatOpenAI(temperature=0.0, model_name="gpt-4" , max_tokens=4096, request_timeout=120))
service_context_ = ServiceContext.from_defaults(llm_predictor=llm_predictor)
query_engine_ = SubQuestionQueryEngine.from_defaults(query_engine_tools=query_engine_tools, question_gen=LLMQuestionGenerator.from_defaults(service_context=service_context))
```

Not sure if it is a bug, however I would recommend to add this note in the documentation. 
Since 0.6.0 Llama index became much more complicated in terms of structure, for sure it allows to customise much much more, but a lot of things are not so obvious.
Anyway thanks!

**Comment by Disiok** [comment]
Ooh, good catch on the issue and thanks for the feedback.

**Comment by logan-markewich** [comment]
This should be not an issue now.

**Comment by logan-markewich** [comment]
Feel free to re-open or reach out on discord!
