### ISSUE TITLE
Issue with nodes being selected for LLM

### ISSUE THREAD

**Issue by domleppard** [jerryjliu/llama_index#3905]
I'm new to Llama_Index. I'm following your basic usage pattern as described here:

https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html

I have just one external file that I am testing llama_index with - a CSV file (linked in this post ) that contains a list of employees, their manager, org unit and then information about the various skills and certifications the employee holds. This isn't real data.

What i'm trying to do is query this data in natural language to ask questions like "Show me a list of people who has skill X" or "Show me all the skills employee X has".

In Python - The following code works fine for me and I get a valid response from the Open AI API:

from llama_index import SimpleDirectoryReader
documents = SimpleDirectoryReader('data').load_data()
index = GPTVectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("Tell me what skills Ada Waters has?")
print(response)

The issue I'm having is with achieving an satisfactory response from the LLM. For example the prompt im submitting asks for the skills Ada Waters has, who is an employee listed in the csv. However, when I query this, the response is completely wrong and/or says it cant find the employee.

It looks like the nodes that are returned from the GPTVectorStoreIndex and passed to the LLM don't seem to contain anything related to Ada Waters....

Can someone help me understand what i'm doing wrong? Is there something wrong with the way i'm using Llama_Index, or an issue with the format of my raw data? or are LLM just not well suited to these type of tasks

I've also tried importing this data in a TXT file in JSON format and have the same issue
[Staff - skills list.csv](https://github.com/jerryjliu/llama_index/files/11567346/Staff.-.skills.list.csv)

**Comment by logan-markewich** [comment]
For this kind of CSV, instead of using the simple directory reader, try using this reader from llama hub 

https://llamahub.ai/l/file-paged_csv

It will load the data in a format that is hopefully more structured. You also might need to increase the top k, since each row will become a document, and they are pretty short 

`query_engine = index.as_query_engine(similarity_top_k=5)`

**Comment by logan-markewich** [comment]
Hmmm, do you have your openai key setup? That code works on my end 🤔

**Comment by domleppard** [comment]
Thanks Logan,  I've got it working now.  It's working better but the results are still unsatisfactory.   I'm doing this:

query_engine = index.as_query_engine(similarity_top_k=5)

For example if I ask "List the people who know Javascript" - it lists two people (who are correct) - but there are about 20 in the CSV who know Javascript that should be displayed

Why isn't it finding everyone?

Thanks
Dom

**Comment by logan-markewich** [comment]
L
