### ISSUE TITLE
SimpleDirectoryReader errors out when dealing with a PDF document containing an UPPERCASE extension

### ISSUE THREAD

**Issue by thedoor76** [jerryjliu/llama_index#3908]
I have a directory of thousands of PDF documents, a handful of which have an uppercase extension of .PDF (instead of the typical lowercase .pdf extension).

This seems to trip the SimpleDirectoryReader. Relevant part of the error stack:
```
  File "[removed]\site-packages\llama_index\readers\file\base.py", line 186, in load_data
    reader_cls = DEFAULT_FILE_READER_CLS[input_file.suffix]
KeyError: '.PDF'
```

As a workaround, I have renamed the uppercase extensions to lowercase, and everything runs as expected.

**Comment by logan-markewich** [comment]
This should be fixed!
