### ISSUE TITLE
Missing Node info when saving to Milvus

### ISSUE THREAD

**Issue by czhang-trinity** [jerryjliu/llama_index#3914]
Hi Community, I think there is a bug on missing save the node info when trying save to milvus database. When the database try to save text, it called the node.get_text(). This only includes the node.extra_info not the node_info so when you try to query it and recompose it as the node, the node info is missing. Also want to know what is a better way to fix it(Putting the text and extra_info together does not like a good implementation since it is hard to separate when query it).

**Comment by logan-markewich** [comment]
This should be fixed in the latest version of llama-index, since we can load/serialize the entire node now. Feel free to reopen or reach out on discord with more questions!
