### ISSUE TITLE
Deprecated Properties for Streaming Response

### ISSUE THREAD

**Issue by mcmichaelau** [jerryjliu/llama_index#3919]
I'm not sure if this is a big deal or not, but ran into these warnings while using `.get_formatted_sources()` for a streaming response:

UserWarning: .source_text is deprecated, use .node.get_text() instead
  warnings.warn(".source_text is deprecated, use .node.get_text() instead")
C:\Users\Austin.McMichael\PycharmProjects\llamaPractice\venv\lib\site-packages\llama_index\data_structs\node.py:171: UserWarning: .doc_id is deprecated, use .node.ref_doc_id instead
  warnings.warn(".doc_id is deprecated, use .node.ref_doc_id instead")

Easy changes in llama_index/response/schema.py took care of it -->

Original: 
`    def get_formatted_sources(self, length: int = 100) -> str:
        """Get formatted sources text."""
        texts = []
        for source_node in self.source_nodes:
            fmt_text_chunk = truncate_text(source_node --->>>.source_text <<<---, length)
            doc_id = source_node --->>> .doc_id <<<--- or "None"
            source_text = f"> Source (Doc id: {doc_id}): {fmt_text_chunk}"
            texts.append(source_text)
        return "\n\n".join(texts)`

Modified:
`    def get_formatted_sources(self, length: int = 100) -> str:
        """Get formatted sources text."""
        texts = []
        for source_node in self.source_nodes:
            fmt_text_chunk = truncate_text(source_node --->>> .node.get_text() <<<--- , length)
            doc_id = source_node --->>> .node.ref_doc_id <<<--- or "None"
            source_text = f"> Source (Doc id: {doc_id}): {fmt_text_chunk}"
            texts.append(source_text)
        return "\n\n".join(texts)`

Just thought I would let you know

**Comment by Disiok** [comment]
Thanks! We will update this
