### ISSUE TITLE
Support for different LLM predictors when the index is loaded from the disk

### ISSUE THREAD

**Issue by chaofanqw** [jerryjliu/llama_index#3920]
Hello,

I'd like to extend my appreciation for developing such a great library. I'm curious to know if you've considered adding support for different LLM predictors when the index is loaded from the disk. As it stands, the system defaults directly to LLMPredictor() which leverages OpenAI(temperature=0, model_name="text-davinci-003").

To facilitate the use of the ChatGPT predictor, I've tried integrating **kwargs into self._service_context = service_context or ServiceContext.from_defaults(**kwargs) in the base.py file. Moreover, I've included the LLM predictor in the load_index_from_storage() function like so: load_index_from_storage(storage_context=context, llm_predictor=LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True)))

Nevertheless, it would greatly enhance the library's functionality if there were built-in support for other LLMs when the index is loaded from the disk. Thank you for considering this suggestion.

**Comment by logan-markewich** [comment]
Whats the issue you are having?

You can configure the LLM to be anything (openai, huggingface, something else) in the service context.

Then when you load from disk, you just pass in the service context you want to use, and the index will use those settings

`load_index_from_storage(storage_context, service_context=service_context)`

**Comment by logan-markewich** [comment]
Here's a docs page for more details on LLMs https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html

**Comment by chaofanqw** [comment]
Thanks for the comment, indeed, I missed the service_context can be initialized within the function, thanks

**Comment by benji56** [comment]
am I correct that if I use the index in this way, the system works only from the local files? Is there a way to be able to respond even if no data is found on the disk (and stream at the same time?)

Or if I'm the only one who doesn't know a setting, how can I determine how flexible the system should be to answer the question?

index = load_index_from_storage(storage_context, service_context=service_context)
