### ISSUE TITLE
Response streaming, so that we are not just working from local data. 

### ISSUE THREAD

**Issue by benji56** [jerryjliu/llama_index#3925]
am I correct that if I use the index in this way, the system works only from the local files? Is there a way to be able to respond even if no data is found on the disk (and stream at the same time?)

Or if I'm the only one who doesn't know a setting, how can I determine how flexible the system should be to answer the question?

index = load_index_from_storage(storage_context, service_context=service_context)

**Comment by vishalp-simplecrm** [comment]
@benji56  
Please check this code you will get stream response 
query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
prompt=input("ask here:")
response_stream = query_engine.query(prompt)
response_stream.print_response_stream()

**Comment by logan-markewich** [comment]
If you want to stream and also respond if not context is found, you can customize the prompts or use a data agent/chat engine

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
