### ISSUE TITLE
How to update vector store index/ inserting new documents to already created index  

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#3928]
In a google drive folder I have 7 docs for which I have created the vector store index
using
GoogleDriveReader = download_loader('GoogleDriveReader')
folder_id = '1LFa04mF3U300ttoej-EkWcT35sHHDZJL'
loader = GoogleDriveReader()
documents = loader.load_data(folder_id=folder_id)
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context )

Now in the same folder i have added some more documents ,
how I can update the index 
how can I use index.insert(document) how it will identify new documents only  

whether it will create index from scratch or it will append new index into that previously created files.

please provide the details about this

**Comment by j0schi** [comment]
I am currently working on the same problem, but i got the feeling the GPTVectorStoreIndex does not support updating or at least not inserting new documents. 

I also tryed the add and insert methods which are both do not exsist for the GPTVectorStoreIndex. Maybe we need to use another vector index... the documentation is not clear about that, so let me know if you find a solution.

Here is my code WHICH DOES NOT WORK:

```
if not index_exists:
    # Index doesn't exist, so create it
    print("Loading documents...")
    # Load documents from your custom folder
    documents = SimpleDirectoryReader(data_directory).load_data()

    # Create index from documents
    print("Creating index...")
    index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

else:
    # Index exists, so load it
    storage_context = StorageContext.from_defaults(persist_dir=persist_directory)
    index = load_index_from_storage(storage_context)
    
    # Load new documents
    print("Loading new documents...")
    new_documents = SimpleDirectoryReader(data_directory).load_data()

    # Create new index with new documents
    print("Creating new index with new documents...")
    new_index = GPTVectorStoreIndex.from_documents(new_documents, service_context=service_context)

    # Merge new index with existing index
    print("Merging new index with existing index...")
    index.merge(new_index)
```

AttributeError: 'GPTVectorStoreIndex' object has no attribute 'merge'
AttributeError: 'GPTVectorStoreIndex' object has no attribute 'insert_documents'
AttributeError: 'GPTVectorStoreIndex' object has no attribute 'add_documents'. Did you mean: 'from_documents'?

Kind regards

**Comment by j0schi** [comment]
It already works actually 
So i check if the index exists (for example by checking if there are files... if not i create a new one, after saving it to disc i move the documents into another folder. If it exists i add the new documents to it and then move them into another folder after the index is updated. You can do this by adding new nodes to an existing index :) I hope this helps! So the magic happens with index.insert_nodes(new_nodes)

```
if not index_exists:
    # Index doesn't exist, so create it
    print("Loading documents...")
    # Load documents from your custom folder
    documents = SimpleDirectoryReader(data_directory).load_data()

    # Create index from documents
    print("Creating index...")
    index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)

else:
    # Index exists, so load it
    storage_context = StorageContext.from_defaults(persist_dir=persist_directory)
    index = load_index_from_storage(storage_context)

    # Load new documents
    print("Loading new documents...")
    new_documents = SimpleDirectoryReader(data_directory).load_data()

    # Parse documents into nodes
    print("Parsing new documents into nodes...")
    parser = SimpleNodeParser()
    new_nodes = parser.get_nodes_from_documents(new_documents)

    # Add nodes to the existing index
    print("Adding new nodes to the existing index...")
    index.insert_nodes(new_nodes)
```

**Comment by YasmineMh** [comment]
Hey @j0schi, how did you check if there are files for `index_exists` variable ?

**Comment by j0schi** [comment]
Hi, this is probably not the best solution but it works for me :) You might have to change the folder / path according to your system. 

# Check if index exists
persist_directory = 'index'
index_files = ['vector_store.json', 'docstore.json', 'index_store.json']
index_exists = all(os.path.exists(os.path.join(persist_directory, file)) for file in index_files)

**Comment by YasmineMh** [comment]
Thanks for your response!
Actually I'm planning to use a vector store from those :  https://gpt-index.readthedocs.io/en/latest/how_to/storage/customization.html#vector-store-integrations-and-storage instead of persist_dir

**Comment by sakibraza-oodles** [comment]
Hey @j0schi,
I don't know why but this code is not updating anything even code is almost same as yours.

       from llama_index import load_index_from_storage

        trained_dir = os.path.join(settings.BASE_DIR, 'trained_data')
        new_data_dir = os.path.join(settings.BASE_DIR, 'new_data')
        update_docs = StorageContext.from_defaults(persist_dir=trained_dir)
        index = load_index_from_storage(update_docs)
        new_documents = SimpleDirectoryReader(new_data_dir).load_data()
        parser = SimpleNodeParser()
        new_nodes = parser.get_nodes_from_documents(new_documents)
        index.insert_nodes(new_nodes)

**Comment by Disiok** [comment]
Take a look at http://localhost:8000/how_to/index/document_management.html, especially the `refresh` section!

**Comment by vishalp-simplecrm** [comment]
Its local server link can't check this?

**Comment by youbai1995** [comment]
> Its local server link can't check this?

https://gpt-index.readthedocs.io/en/latest/how_to/index/document_management.html

**Comment by shauryat97** [comment]
Have similar qustion :
 Do I need to persist my index again after inserting new data into my VectorStore Index or it it done automatically ? I am using MilvusVectorStore.
 
My method :
1. Load from storage an existing index.
2. Insert  new documents (pdfs) to the index.
3. Do I need to call index.storage_context.persist(persist_dir = '') ?

**Comment by gongx030** [comment]
> Have similar qustion : Do I need to persist my index again after inserting new data into my VectorStore Index or it it done automatically ? I am using MilvusVectorStore.
> 
> My method :
> 
> 1. Load from storage an existing index.
> 2. Insert  new documents (pdfs) to the index.
> 3. Do I need to call index.storage_context.persist(persist_dir = '') ?

Based on my experience with `FaissVectorStore`, yes, one has to persist and load the index again to make these newly added nodes available to the query.
