### ISSUE TITLE
Querying a GPTKeywordTableIndex inside a Flask app returns None but works normally in a py file?

### ISSUE THREAD

**Issue by sw3554** [jerryjliu/llama_index#3934]
Hello,

I've been able to query a GPTKeywordTableIndex with a py file, including loading the index from disk and querying it, but when I put the functions in a Flask app it just returns None. I'm using the Paul Graham essay. 
VectorStoreIndex on the other hand works normally in a Flask app.

Am I missing something? I have tried:
Building a GPTKeywordTableIndex and querying it in the same py file-- this works:
```
from llama_index import GPTKeywordTableIndex, SimpleDirectoryReader
import os
os.environ['OPENAI_API_KEY'] = "XXX"
# build keyword index
documents = SimpleDirectoryReader('data').load_data()
index = GPTKeywordTableIndex.from_documents(documents)
query_engine = index.as_query_engine()
index.storage_context.persist()

response = query_engine.query("What did the author do after his time at Y Combinator?")
print(response)
```

Loading an index from disk and querying--this works:
```
from llama_index import (
    StorageContext, 
    load_index_from_storage
)
import os
os.environ['OPENAI_API_KEY'] = "XXX"

storage_context = StorageContext.from_defaults(persist_dir="./storage")
# load index
index = load_index_from_storage(storage_context)

#if index is None:
#    print("Load index failed")
#else:
#    print("Load index success")

query_engine = index.as_query_engine()
response = query_engine.query("What did the author do after his time at Y Combinator?")
print(response)

```

Making as few changes as possible to make it into a Flask app--when I go to '/' to check index, it says index has been loaded, but querying returns None. I don't get any other errors or warnings. I run the flask app using flask --app test_app run.
```
from llama_index import (
    StorageContext, 
    load_index_from_storage
)
import os
from flask import Flask, request, jsonify, make_response
from flask_cors import CORS
os.environ['OPENAI_API_KEY'] = "XXX"
app = Flask(__name__)
CORS(app)

storage_context = StorageContext.from_defaults(persist_dir="./storage")
# load index
index = load_index_from_storage(storage_context)
query_engine = index.as_query_engine()

#if index is None:
#    print("Load index failed")
#else:
#    print("Load index success")

@app.route('/')
def check_index():
    global index
    if index is None:
        return "Load index failed"
    else:
        return "Load index success"

@app.route("/query", methods=["GET"])
def query_app():
    query_text = request.args.get("text", None)
    response = query_engine.query(query_text)
    return str(response)

if __name__=='__main__':
    app.run(debug=True)
```

Many thanks if anyone can see what the problem is!

**Comment by logan-markewich** [comment]
maybe try adding a print to make sure the query_app() function is actually getting the query_text?

**Comment by sw3554** [comment]
So I changed the return line to return print(str(response)) and got an error:
TypeError: The view function for 'query_app' did not return a valid response. The function either returned None or ended without a return statement.

If I swap the files to a vector store index, then it works.

**Comment by logan-markewich** [comment]
I meant to print the query text, not return the print of the response 😅

The keyword index might return blank responses if it fails to extract keywords (I.e. if the query is one word or blank, it may not work)

The vector index will always return some kind of response since it uses embeddings instead of keyword lookup

**Comment by sw3554** [comment]
Ok, returning query_text works, repeats what I entered ("What did the author do for work?").

I don't think it's a keyword problem since I also can't get list index and tree index to work in the flask app either. Document summary index works.

**Comment by Disiok** [comment]
Hey @sw3554  going to close this ticket. It's a bit too difficult for us to help debug this, since it's likely related to your flask code.
