### ISSUE TITLE
[Demo] Build Tree Index with a custom Summary Prompt, directly retrieve answer from root node

### ISSUE THREAD

**Issue by manaskrishnajaiswal** [jerryjliu/llama_index#3941]
from llama_index import GPTTreeIndex, SimpleDirectoryReader, Prompt
from llama_index import GPTTreeIndex, SimpleDirectoryReader, Prompt
documents = SimpleDirectoryReader('data').load_data()
​
// Provide the actual context information
// context_str = "The author grew up in a small town and spent most of their time exploring nature and reading books."
query_str = "What did the author do growing up?"
SUMMARY_PROMPT_TMPL = (
    "Context information is below. \n"
    "---------------------\n"
    f"{context_str}"
    "\n---------------------\n"
    "Given the context information and not prior knowledge, "
    f"answer the question: {query_str}\n"
)
​
SUMMARY_PROMPT = Prompt(SUMMARY_PROMPT_TMPL)
index_with_query = GPTTreeIndex.from_documents(documents, summary_template=SUMMARY_PROMPT)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[25], line 15
      5 query_str = "What did the author do growing up?"
      6 SUMMARY_PROMPT_TMPL = (
      7     "Context information is below. \n"
      8     "---------------------\n"
   (...)
     12     f"answer the question: {query_str}\n"
     13 )
---> 15 SUMMARY_PROMPT = Prompt(SUMMARY_PROMPT_TMPL)
     16 index_with_query = GPTTreeIndex.from_documents(documents, summary_template=SUMMARY_PROMPT)

File D:\MERN Completed Projects\llama-index\llama-index-venv\Lib\site-packages\llama_index\prompts\base.py:56, in Prompt.__init__(self, template, langchain_prompt, langchain_prompt_selector, stop_token, output_parser, metadata, **prompt_kwargs)
     52 # validate
     53 tmpl_vars = {
     54     v for _, v, _, _ in Formatter().parse(template) if v is not None
     55 }
---> 56 if tmpl_vars != set(self.input_variables):
     57     raise ValueError(
     58         f"Invalid template: {template}, variables do not match the "
     59         f"required input_variables: {self.input_variables}"
     60     )
     62 self.prompt = LangchainPrompt(
     63     input_variables=self.input_variables, template=template, **prompt_kwargs
     64 )

AttributeError: 'Prompt' object has no attribute 'input_variables'

**Comment by hashAI** [comment]
Just update llama-index to 0.6.14.
