### ISSUE TITLE
Redis store "saving and loading" only describes saving

### ISSUE THREAD

**Issue by paralin** [jerryjliu/llama_index#3942]
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/RedisIndexDemo.html#saving-and-loading

This section describes saving with persist() but not loading the index back again later.

**Comment by Disiok** [comment]
Ah could make this more explicit ya. You just have to re-construct the vector store object.

**Comment by aetherwu** [comment]
> You just have to re-construct the vector store object.

However how to re-load an exsiting index that is already in Redis server?
