### ISSUE TITLE
How to insert 2 GptListIndex of GptSimpleVectorIndex nodes into another GptListIndex 

### ISSUE THREAD

**Issue by siddhant01** [jerryjliu/llama_index#400]
Hey,
I want to store a GptListIndex for a document with multiple nodes as GptSimpleVectorIndex in db. for easy selection of knowlede-base based on the requirement.

but the problem lies how to insert 2 GptListIndex of GptSimpleVectorIndex nodes into another GptListIndex ?

**Comment by jerryjliu** [comment]
Hi @siddhant01 , not sure what you mean by "store a gpt list index as a gptsimplevectorindex" - those are two separate indices, and i'm not quite sure why you'd want to convert a list index to a simple vector index

**Comment by Disiok** [comment]
Closing since thread is stale.
