### ISSUE TITLE
How to form nodes (in GptSimpleVectorIndex form) based on paragraphs not based on fixed token size?

### ISSUE THREAD

**Issue by siddhant01** [jerryjliu/llama_index#401]
hey,
I want to form node (in GptSimpleVectorIndex form) but based on paragraphs not based on fixed token size (and definitely not containing the full document). so that every node has a fixed context in them so that the minimum no. of nodes is selected for prompt formation.

I currently want to do this on Google Docs. How to achieve this.

**Comment by jerryjliu** [comment]
Hi, we're currently adding the ability to add your own text splitters to an index, hopefully this should help resolve your issue

**Comment by jerryjliu** [comment]
cd @siddhant01 try adding a langchain `text_splitter` field when building an index.

alternatively, "pre-split" the text into separate Document objects, and load that into gpt index during index construction

**Comment by logan-markewich** [comment]
Going to close this issue for now. 

You can write your own custom node parser if needed pretty easily, or pre-split your documents as jerry suggested. 

Base Class:
https://gpt-index.readthedocs.io/en/latest/api_reference/service_context/node_parser.html

Docs:
https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/node_parsers/usage_pattern.html
