### ISSUE TITLE
When you deploy flask in gunicorn's gevent working mode, the stream output is stuck until the access times out

### ISSUE THREAD

**Issue by MonsterZwj** [jerryjliu/llama_index#4027]
I've implemented the flask interface for getting stream data, but when I deployed my project with gunicorn's gevent pattern, I found that accessing the interface for getting stream data kept getting stuck until the interface timed out. Has anyone experienced the same problem

Here is my code
def ask(pyPath, content, similarityTopK=2, similarityCutoff=0.7):
    # @stream_with_context
    def generate(text):
        for res in text:
            yield res
    Token().get_token_text()
    response = LlamaIndexAPI.query_index(
        content=content,
        index_file=os.path.join(app.config["INDEX_FILE"], pyPath),
        similarity_top_k=similarityTopK,
        similarity_cutoff=similarityCutoff
    )
    if response is False:
        raise APIException(StatusCode.ASK_FAILURE)
    return Response(generate(response), content_type="text/event-stream")

**Comment by MonsterZwj** [comment]
Do streams conflict with asynchrony?

**Comment by logan-markewich** [comment]
If your index is setup to return a streaming response, I think you'll want to use something like this

`return Response(stream_with_context(response.response_gen))`
