### ISSUE TITLE
SimpleDirectoryReader document reader doesn't decode in UTF-8

### ISSUE THREAD

**Issue by stephansturges** [jerryjliu/llama_index#406]
It appears that special characters of all kinds are incorrectly decoded in both .txt files and .csv files, using file formats that were saved explicitly with UTF-8 encoding. 

See the screenshot below for an example of extracted text in a JSON index:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/20320678/217289604-1f8bdda6-9ceb-4008-afaf-6a31351ec3ea.png">

**Comment by BadAstronaut** [comment]
yep having the same issue with Spanish, did you find any solucion to change the encoding ?

**Comment by jerryjliu** [comment]
i can add a TODO to add an encoding for simple directory reader!
