### ISSUE TITLE
Am I wrong or gpt-turbo-3.5 is just limited?

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#4176]
I have a list of report files about agriculture (pdf files and each file is about one month (Jan, Feb, ..., Dec)) located in docs, now I just get chatgpt work with those files. However, when I have a question comparing statistics between November and May, the gpt says it does not find information. Is this a normal thing?

**Comment by logan-markewich** [comment]
It's a little normal for gpt-3.5 -> it seems to struggle with complex tasks 

But there are ways to get around it. What does your query/index setup look like?

**Comment by dinhan92** [comment]
max_input_size = 4096
num_outputs = 1
max_chunk_overlap = 20
chunk_size_limit = 256

prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

prepend_messages = [
    SystemMessagePromptTemplate.from_template("You are a helpful assistant that use Vietnamese in every response, response with the max tokens being 1")
]
llm_predictor = ChatGPTLLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True), prepend_messages = prepend_messages)


service_context = ServiceContext.from_defaults(
        llm_predictor = llm_predictor,
        prompt_helper = prompt_helper)

def construct_index(directory_path):
   
    documents = SimpleDirectoryReader(directory_path).load_data()

    index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
    
    index.storage_context.persist(persist_dir='./storage')

    return index

@app.route('/api/chatbot', methods=['GET'])
def chatbot():
    args = request.args
    input_text = args.get('input')
    # rebuild storage context
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
    

    index = load_index_from_storage(storage_context = storage_context,
                                     
                                    service_context = service_context)
    
    query_engine = index.as_query_engine(
        streaming=True,
    )

    response = stream_with_context(query_engine.query(input_text).response_gen)
    
    return Response(response)

I do something like this, is there any thing I can do more to do the complex tasks?

**Comment by trover97** [comment]
I think, you need to change num_outputs to bigger value. This parameters means number of output tokens. It is not like 'n' in chatGPT.

**Comment by logan-markewich** [comment]
@dinhan92 yea, @trover97 is correct, you'll want to change that (although it's not having a huge impact right now, it can cause problems later)

For complex queries like comparing statistics, you will be interested in the sub-query engine, which breaks a query down into multiple questions

https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#multi-document-queries

**Comment by dinhan92** [comment]
Sorry, I put the num_outputs to 512 before I posted this but the paragraph will get truncated, my data is in Vietnamese

**Comment by dinhan92** [comment]
@logan-markewich am I right that this Multi-Document Queries can not be used with streaming = true? Because I get the error in:
 for text in response.response_gen:
AttributeError: 'Response' object has no attribute 'response_gen'
It says there is no response_gen which is used with streaming=true here

**Comment by logan-markewich** [comment]
@dinhan92 I think you can still stream, but you'll need to set streaming=true in two places

See the guide here:
https://gpt-index.readthedocs.io/en/latest/how_to/customization/streaming.html

**Comment by dinhan92** [comment]
@logan-markewich I already do as that guides, In fact, I am able to do streaming with Python and Flutter, however when using stream with Multi-Document Queries, I get that error

**Comment by dinhan92** [comment]
Ah, do you mean I have to run with this:
synth = ResponseSynthesizer.from_args(streaming=True, ...)
query_engine = RetrieverQueryEngine(response_synthesizer=synth, ...)

**Comment by logan-markewich** [comment]
Yes! And also be sure to set streaming=True in the OpenAI/ChatOpenAI definition

**Comment by dinhan92** [comment]
@logan-markewich 
I have tried this: https://gpt-index.readthedocs.io/en/latest/examples/composable_indices/city_analysis/City_Analysis-Decompose.html
with Complex Query 1 and add streaming = true:

 graph = ComposableGraph.from_indices(
        GPTSimpleKeywordTableIndex,
        [index for _, index in report_indices.items()], 
        [summary for _, summary in index_summaries.items()],
        max_keywords_per_chunk=50
    )

decompose_transform = DecomposeQueryTransform(
        llm_predictor, verbose=True
    )

    custom_query_engines = {}
    for index in report_indices.values():
        query_engine = index.as_query_engine(service_context=service_context)
        transform_extra_info = {'index_summary': index.index_struct.summary}
        tranformed_query_engine = TransformQueryEngine(query_engine, decompose_transform, transform_extra_info=transform_extra_info)
        custom_query_engines[index.index_id] = tranformed_query_engine

    custom_query_engines[graph.root_index.index_id] = graph.root_index.as_query_engine(
        retriever_mode='simple', 
        response_mode='tree_summarize', 
        service_context=service_context,
        # streaming=True
    )

    query_engine_decompose = graph.as_query_engine(
        custom_query_engines=custom_query_engines,
        **streaming=True**
    )

But it seems streaming is not in ComposableGraph,
I have tried synth = ResponseSynthesizer.from_args(streaming=True, ...)
query_engine = RetrieverQueryEngine(response_synthesizer=synth, ...) but do not know where to set custom_query_engines.
Can youi guide me?

**Comment by logan-markewich** [comment]
It's a little annoying, but here's a minimum example for me

This is possible currently, but it's a little tricky. We can improve this in the future though!

```python
>>> from llama_index import Document, GPTListIndex, LLMPredictor, ServiceContext
>>> documents = [Document("hello world")]
>>>
>>> from langchain.llms import OpenAI
>>> llm = OpenAI(model_name='text-davinci-003', temperature=0, streaming=True)
>>> service_context = ServiceContext.from_defaults(llm_predictor=LLMPredictor(llm=llm))
>>>
>>> index1 = GPTListIndex.from_documents(documents, service_context=service_context)
>>> index2 = GPTListIndex.from_documents(documents, service_context=service_context)
>>>
>>> from llama_index.indices.composability import ComposableGraph
>>> graph = ComposableGraph.from_indices(GPTListIndex, [index1, index2], index_summaries=['1', '2'], service_context=service_context)
>>> query_engines = {
...     index1.index_id: index1.as_query_engine(streaming=True),
...     index2.index_id: index2.as_query_engine(streaming=True),
...     graph.root_index.index_id: graph.root_index.as_query_engine(streaming=True)
... }
>>> query_engine = graph.as_query_engine(custom_query_engines=query_engines)
>>> response = query_engine .query("Hello world")
>>> type(response)
<class 'llama_index.response.schema.StreamingResponse'>
>>> for token in response.print_response_stream()

**Comment by dinhan92** [comment]
I am trying to do the compare contrast between 2 documents here:
storage_context_1 = StorageContext.from_defaults(persist_dir=f"./storage_Baocao_T05_2022")
    index1 = load_index_from_storage(storage_context = storage_context_1,
                                    # embed_model=embed_model, 
                                    service_context = service_context)
    
    storage_context_2 = StorageContext.from_defaults(persist_dir=f"./storage_Baocao_T11_2022")
    index2 = load_index_from_storage(storage_context = storage_context_2,
                                    # embed_model=embed_model, 
                                    service_context = service_context)



    graph = ComposableGraph.from_indices(GPTListIndex, [index1, index2], index_summaries=["Tài liệu này về Baocao_T05_2022", "Tài liệu này về Baocao_T11_2022"], service_context=service_context)
    query_engines = {
        index1.index_id: index1.as_query_engine(streaming=True),
        index2.index_id: index2.as_query_engine(streaming=True),
        graph.root_index.index_id: graph.root_index.as_query_engine(streaming=True)
    }

    query_engine = graph.as_query_engine(custom_query_engines=query_engines)

I see that the answer is streaming, but there is no information at all in the answer, the question is: "Cho tôi hỏi tình hình trồng trọt tháng 5 so với tháng 11" and the answer is: "Xin lỗi, không có thông tin về tình hình trồng trọt tháng 5 và tháng 11 trong đoạn văn trên. Vui lòng cung cấp thêm thông tin để tôi có thể trợ giúp bạn."

**Comment by dinhan92** [comment]
When I only ask: "Cho tôi hỏi tình hình trồng trọt tháng 11", I get this error: Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-PH8zdIn1RI0V7H7Aak3Lzy73 on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit.

**Comment by logan-markewich** [comment]
Yea on the trial accounts, it's heavily rate limited 😅

**Comment by logan-markewich** [comment]
Ah sorry, forgot you were doing compare/contrast. You'll have the best luck with that using the newer sub question query engine (but you may hit rate limits unless you add payment info to openai lol)

https://github.com/jerryjliu/llama_index/blob/main/docs/examples/query_engine/sub_question_query_engine.ipynb

**Comment by dinhan92** [comment]
I do like this with the link you send and get this error: ValueError: LLM must support streaming and set streaming=True.

 storage_context_1 = StorageContext.from_defaults(persist_dir=f"./storage_Baocao_T05_2022")
    index1 = load_index_from_storage(storage_context = storage_context_1,
                                    # embed_model=embed_model, 
                                    service_context = service_context)
    
    storage_context_2 = StorageContext.from_defaults(persist_dir=f"./storage_Baocao_T11_2022")
    index2 = load_index_from_storage(storage_context = storage_context_2,
                                    # embed_model=embed_model, 
                                    service_context = service_context)
    
    query_engine_1 = index1.as_query_engine(streaming=True)
    query_engine_2 = index2.as_query_engine(streaming=True)

    query_engine_tools = [
        QueryEngineTool(
            query_engine = query_engine_1, 
            metadata = ToolMetadata(name='bao_cao_thang_5', description='Cung cấp thông tin về nông nghiệp tháng 5')
        ),
        QueryEngineTool(
            query_engine = query_engine_2, 
            metadata = ToolMetadata(name='bao_cao_thang_11', description='Cung cấp thông tin về nông nghiệp tháng 11')
        )
    ]

    synth = ResponseSynthesizer.from_args(streaming = True)

    query_engine = SubQuestionQueryEngine.from_defaults(query_engine_tools=query_engine_tools, response_synthesizer=synth)

response = await query_engine.aquery(input_text)

**Comment by dinhan92** [comment]
I ve upgrade llama index, it does not meet that error yet, but a RateLimitError, it seems that I have to pay for that

**Comment by dinhan92** [comment]
Never mind, I know how to fix this, thanks @logan-markewich
