### ISSUE TITLE
Make Flutter run with Streaming True

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#4178]
So I have set Streaming==True and it run fine like chatGpt in Terminal. However, when I make it an api and try running on Flutter, the text only appears when all the response is finished. How do I make it generate word by word?
@app.route('/api/chatbot', methods=['GET'])
def chatbot():
    args = request.args
    input_text = args.get('input')
    
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
    
    index = load_index_from_storage(storage_context = storage_context,
                                    # embed_model=embed_model, 
                                    service_context = service_context)
    
    query_engine = index.as_query_engine(
        streaming=True,
        
    )

    response = stream_with_context(query_engine.query(input_text).response_gen)
    return response

**Comment by logan-markewich** [comment]
Is this flask code? you need to return the stream, not the final result if you want to stream the response

**Comment by dinhan92** [comment]
yes, this is the flask code, I return the stream by stream_with_context

**Comment by dinhan92** [comment]
Am I true or should I return like this? return query_engine.query(input_text).response_gen

**Comment by dinhan92** [comment]
ah okay, I figured it out how to run stream with Flutter, thank you ^^

**Comment by logan-markewich** [comment]
Perfect!
