### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.query_engine'

### ISSUE THREAD

**Issue by alonhartal** [jerryjliu/llama_index#4190]
Using 0.6.13
`from llama_index.query_engine import RetrieverQueryEngine`

getting ModuleNotFoundError: No module named 'llama_index.query_engine'

**Comment by logan-markewich** [comment]
This works on my end. Are you using a venv? Maybe try installing from a fresh venv

Using a bash terminal:

```
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by alonhartal** [comment]
tried as well. doesn't work

**Comment by logan-markewich** [comment]
@alonhartal do you have a python file called llama_index.py? If so, rename that to something else

**Comment by alonhartal** [comment]
ok, I found the issue. thanks for you help

**Comment by navneetkrc** [comment]
How did you resolve the issue?
I am not able to find the llama_index.py

**Comment by samedovzaur** [comment]
> ok, I found the issue. thanks for you help

Bro finding and not telling ha it is disrespectfull :(

**Comment by bmurtagh01** [comment]
Hi there, in my case I was running the code in an outdated version of Jupyter, running the following commands fix it form me:
```
pip3 install --upgrade jupyter-console
pip3 install --upgrade jupyter
```

**Comment by minhhungit** [comment]
If someone gets this error: 
```
"source: The term 'source' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
```

Check this:

On Windows, virtualenv creates a .bat/.ps1 file, so you should run venv\Scripts\activate instead (per the virtualenv [documentation on the activate script](https://virtualenv.pypa.io/en/legacy/userguide.html#activate-script)).

https://stackoverflow.com/a/8921211

**Comment by justin107d** [comment]
I am still getting the same issue.  I am not using jupyter.  I solved this by rolling back to `llama-index==0.9.48`

**Comment by logan-markewich** [comment]
@justin107d v0.10.x is a pretty big update.

Start with a completely fresh venv, and it should make everything easier

**Comment by Labern31** [comment]
The  llama-index package format has changed, try importing this way and it should work:

`from llama_index.core.query_engine import PandasQueryEngine`

**Comment by nogutsnoglorious** [comment]
Yes, indeed! Thanks for the help @Labern31

**Comment by redocdm** [comment]
Thanks Labern31! Worked for me.

**Comment by RisabBiswas** [comment]
They are noe part of llama_index.core. This should work. 


from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.indices.postprocessor import SimilarityPostprocessor

**Comment by Kaburu12** [comment]
@RisabBiswas it worked for me thanks bro

**Comment by chisomloius** [comment]
@justin107d's approach was correct enough

**Comment by francis04j** [comment]
> The llama-index package format has changed, try importing this way and it should work:
> 
> `from llama_index.core.query_engine import ...`

This worked for me. i also had to upgrade to  llama-index==0.10.31

**Comment by zubin-madon** [comment]
> The llama-index package format has changed, try importing this way and it should work:
> 
> `from llama_index.core.query_engine import ...`

This solution worked for me

**Comment by sunson-98** [comment]
> ok, I found the issue. thanks for you help

How did you resolve

**Comment by alexandru2882** [comment]
The problem is fixed by running this command in terminal: 

pip install llama-index-experimental 

then inserting this in the main.py file: 

from llama_index.experimental.query_engine.pandas import PandasQueryEngine

Then this code will run flowlessly:

population_query_engine = PandasQueryEngine(df=population_df, verbose=True)

**Comment by harrisonokoth** [comment]
I didn't find the solution.
Please help.
