### ISSUE TITLE
Index wiped when application closes despite being told to persist (save to disk) according to the documentation 

### ISSUE THREAD

**Issue by JViggiani** [jerryjliu/llama_index#4362]
Here is my script:

```
from llama_index import SimpleDirectoryReader, GPTListIndex, GPTVectorStoreIndex, LLMPredictor, PromptHelper, ResponseSynthesizer, StorageContext, load_index_from_storage, ServiceContext
from llama_index.retrievers import VectorIndexRetriever
from llama_index.query_engine import RetrieverQueryEngine
from llama_index.indices.postprocessor import SimilarityPostprocessor
from llama_index.indices.response.type import ResponseMode

from langchain.chat_models import ChatOpenAI
import gradio as gr
import sys
import os
from dotenv import load_dotenv

load_dotenv()
open_api_key = os.getenv("OPENAI_API_KEY")
print(open_api_key)

docstore = "data/docs"
persistdir = "data/persist"


# def load_or_construct_index():
#     if os.path.exists(indexstore):
#         return load_index()
#     else:
#         return construct_index()

def construct_index():
    max_input_size = 4096
    num_outputs = 512
    max_chunk_overlap = 20
    chunk_size_limit = 600

    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.8, model_name="gpt-3.5-turbo", max_tokens=num_outputs))
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)

    documents = SimpleDirectoryReader(docstore).load_data()

    # index = GPTVectorStoreIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)
    index = GPTVectorStoreIndex.from_documents(
        documents, service_context=service_context
    )

    index.storage_context.persist(persist_dir=persistdir)

    return index

def load_index():
    storage_context = StorageContext.from_defaults()
    storage_context.persist(persist_dir=persistdir)
    index = load_index_from_storage(storage_context)
    return index

# index = construct_index()
index = load_index()

# configure retriever
retriever = VectorIndexRetriever(
    index=index, 
    similarity_top_k=15,
)

# configure response synthesizer
response_synthesizer = ResponseSynthesizer.from_args(
    node_postprocessors=[
        SimilarityPostprocessor(similarity_cutoff=0.7)
    ]
)

# assemble query engine
query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    response_mode=ResponseMode.TREE_SUMMARIZE,
)


def chatbot(input_text):
    response = query_engine.query(input_text)
    return f'{response.response}\nSources:\n{response.get_formatted_sources()}'

iface = gr.Interface(fn=chatbot,
                     inputs=gr.components.Textbox(lines=7, label="Enter your text"),
                     outputs="text",
                     title="Custom-trained AI Chatbot")

iface.launch(share=True)
```

I ran this after quite a long indexing session, and a docstore, index_store and vector_store set of json files were indeed created and populated. 

However, I ctrl+c'd my cmd run because of a now-fixed (I think) bug, and upon close, my json files got wiped! This is rather irritating as it's cost me about $10. 

The documentation is rather sparse here, and it only says that a single function should be called: https://gpt-index.readthedocs.io/en/latest/how_to/storage/save_load.html

I believe that I am doing this on the line: `index.storage_context.persist(persist_dir=persistdir)`

The documentation has nothing to say about when this ought to be called. Am I doing something wrong here, and is it covered by the current documentation?

Again I should stress that the index was indeed written to disk, but that upon application shutdown it was wiped. Now I have three empty json files left on disk. 

Cheers!

**Comment by logan-markewich** [comment]
Definitely a frustrating situation!

`index.storage_context.persist(persist_dir=persistdir)` is indeed the correct way to save the index. Whenever this is called is when the files are written to disk, overwriting anything that was previously in that directory.

Judging by your current code, I'm not sure how they got erased. My best guess is maybe ctrl+c interrupted the index construction but then it continued the function to write to disk and persist (therefore writing a blank index and overwriting the previous files?)

**Comment by JViggiani** [comment]
Hey thanks for the reply!

After some playing around, and manually backing up the generated indicies, I figured out what the issue was. 

I think the ctrl+c was a red herring. The issue was actually in this loading function:

```
def load_index():
    storage_context = StorageContext.from_defaults()
    storage_context.persist(persist_dir=persistdir)
    index = load_index_from_storage(storage_context)
    return index
```

The problem is that I just told it to persist again. It seems like it overwrites the new index if it has to. 

The documentation states:

_Multiple indexes can be persisted and loaded from the same directory, assuming you keep track of index ID’s for loading._

This may be an opportunity to clarify in the docs that if index IDs are not provided, an overwrite of any existing indicies will occur. 

Here's the fixed implementation for any future observers:

```
from llama_index import StorageContext, load_index_from_storage
from llama_index.storage.docstore.simple_docstore import SimpleDocumentStore
from llama_index.storage.index_store.simple_index_store import SimpleIndexStore
from llama_index.vector_stores.simple import SimpleVectorStore

def load_index():
    storage_context = StorageContext.from_defaults(
        docstore=SimpleDocumentStore.from_persist_dir(persist_dir=persistdir),
        vector_store=SimpleVectorStore.from_persist_dir(persist_dir=persistdir),
        index_store=SimpleIndexStore.from_persist_dir(persist_dir=persistdir),
    )
    index = load_index_from_storage(storage_context)
    return index
```

Note that these docs don't have the import statements, might be good to add them here too: https://gpt-index.readthedocs.io/en/latest/how_to/storage/save_load.html

Happy coding!

**Comment by logan-markewich** [comment]
Yea thanks for the docs updates suggestions!

I missed that load function on my first look lol that was definitely the culprit 

Also, your load_index function can be a little more simple

```
def load_index():
    storage_context = StorageContext.from_defaults(persist_dir=persistdir)
    index = load_index_from_storage(storage_context)
    return index
```
