### ISSUE TITLE
If not found context, search directly in openai

### ISSUE THREAD

**Issue by NaelsonAccountDrive** [jerryjliu/llama_index#4374]
like see over title, i have a dataset with some text, but if dont found i need enable to search GPT.

**Comment by mintisan** [comment]
It seems like a natural behavior...
+1

**Comment by reinershir** [comment]
Yes, normally it should be like this.

**Comment by logan-markewich** [comment]
You can either customize the prompts to allow outside info, or use an agent/chat engine

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
