### ISSUE TITLE
getting error raise JsonDecodeError("Extra data", s, end) with llama_index 0.6.9

### ISSUE THREAD

**Issue by siddhant01** [jerryjliu/llama_index#4449]
we are facing an issue with llama_index.download_loader all of a sudden with llama_index 0.6.9

![Screenshot 2023-05-31 at 10 25 17 AM](https://github.com/jerryjliu/llama_index/assets/31789669/6dd5aeac-d6fc-453d-96d6-db310e5753ba)

**Comment by Kefan-pauline** [comment]
Upgrade to the most recent version 0.6.15 resolved my issue.

**Comment by logan-markewich** [comment]
Yea, llama-hub was made into a package, which changed the URL that download_loader uses

Either update llama-index or you can install the llama-hub pip package
