### ISSUE TITLE
RFC: Best practices documentation

### ISSUE THREAD

**Issue by EmanuelCampos** [jerryjliu/llama_index#4514]
Can be interesting to add a best practices documentation page, on the top of the documentation, because there's a lot of ways to do things and currently it's not enough clear.

what about start by adding some anchors like:

Understanding costs:
- [Cost Analysis](https://gpt-index.readthedocs.io/en/latest/how_to/analysis/cost_analysis.html)

**Comment by EmanuelCampos** [comment]
Maybe add which type of index to use together with some use cases examples

**Comment by logan-markewich** [comment]
Does this page not cover some of your questions? 

https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html

**Comment by EmanuelCampos** [comment]
> Does this page not cover some of your questions?
> 
> https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html

It helps with which queries to use, but I think best practices would be a combination of what to use + how to do queries or store indexes in a more performative way

**Comment by Disiok** [comment]
> > Does this page not cover some of your questions?
> > https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html
> 
> It helps with which queries to use, but I think best practices would be a combination of what to use + how to do queries or store indexes in a more performative way

Yea this is a good suggestion. We are going to do some refactoring on our docs. Stay tuned.
