### ISSUE TITLE
AttributeError: 'GPTVectorStoreIndex' object has no attribute 'save_to_disk'

### ISSUE THREAD

**Issue by Ash121205** [jerryjliu/llama_index#4581]
While executing the following line in a function:

  index.save_to_disk('index.json')
  
I am getting this following error: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-28-58e004f2ed5f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 index = construct_index("/content/drive/MyDrive/")

[<ipython-input-22-d7468a517225>](https://localhost:8080/#) in construct_index(directory_path)
     19   index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
     20 
---> 21   index.save_to_disk('index.json')
     22 
     23   return index

AttributeError: 'GPTVectorStoreIndex' object has no attribute 'save_to_disk'

**Comment by logan-markewich** [comment]
This has changed since v0.6.0, I recommend brushing up on the docs

Here's a relevant section for saving/loading 

https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-save-the-index-for-future-use

**Comment by Ash121205** [comment]
yes, I tried doing something like but now i have another issue with me:
[](https://github.com/jerryjliu/llama_index/issues/4592)

I can't say that doing as said in the documentation has worked.
Please look into this issue.

**Comment by kigenchesire** [comment]
Change to:  index.storage_context.persist(persist_dir="<persist_dir>") where <persist_dir>is the directory you want to save the file. You can remove persist_dir if you want to save it in the default directory.
