### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \uXXXX escape

### ISSUE THREAD

**Issue by kashif-khann** [jerryjliu/llama_index#4594]
getting this error when calling llama_index classes like SimpleNodeParser() and GPTVectorStoreIndex()
I upgraded llama_index but still same issue

![k1](https://github.com/jerryjliu/llama_index/assets/59335119/35de01bb-27e3-4823-83f4-6bee4c750c1a)

![k2](https://github.com/jerryjliu/llama_index/assets/59335119/9dda5741-438b-4443-b604-a129bd75199d)

**Comment by Disiok** [comment]
This seems to be unrelated to LlamaIndex. I suspect is a env setup issue? Closing for now.

**Comment by sahil-springworks** [comment]
I'm facing the same issue today. Any solution/reason?

**Comment by sahil-springworks** [comment]
@kashif-khann did you solve this issue?
