### ISSUE TITLE
In the Q & A system, we need to use the website address  http://www.xxx.com（which  is  my  actually  website） ，no such as website address  like  http://www.examples.com.

### ISSUE THREAD

**Issue by pythonmanGo** [jerryjliu/llama_index#4616]
In the Q & A system, we need to use the website address. Now when users ask questions, http://example.com and other systems such as Hu compiled.

How to formulate the address of the official website in a question and answer to http://www.xxx.com.

**Comment by Disiok** [comment]
Not super sure what this is asking about.
