### ISSUE TITLE
Global ServiceContext Issue

### ISSUE THREAD

**Issue by ashutoshsinha25** [jerryjliu/llama_index#4620]
https://github.com/jerryjliu/llama_index/blob/7c5488af848a40c1cef690805bc7de98b8dd7156/docs/how_to/customization/service_context.md 

from this service_context.md, when im following the global serviceContext code, it is giving two error.

1. ServiceContext.from_defaults --> if i add is_global=True it throws : TypeError: from_defaults() got an unexpected keyword argument 'is_global' 
2. set_global_service_context --> when im importing this from from llama_index import set_global_service_context, it is giving cannot import name 'set_global_service_context' from 'llama_index' 

im just following whatever  code is there in the page. Can someone help/suggest what should be done here ?

**Comment by logan-markewich** [comment]
1. My apologies, that argument slipped by. Will remove it from the docs shortly
2. Hmmm that function definitely exists (and works on my end). Maybe try a fresh venv?

**Comment by logan-markewich** [comment]
Fixed the docs :)

**Comment by ckrapu-nv** [comment]
For anyone else that comes across this, you can use the following to import `set_global_service_context`:

```
from llama_index.core.service_context import set_global_service_context
```
