### ISSUE TITLE
How to return streaming response and some other json data to frontend?

### ISSUE THREAD

**Issue by chatgptguru** [jerryjliu/llama_index#4622]
Hi, I am using latest version of llama-index, and by setting streaming=True, I am able to get streaming object in python backend.
I am using python, flask for backend, and now I want to return streaming response and other json data to my react frontend.
Any guide to return streaming response and other json data together, and guide to use that data in frontend?
Please help me :)

**Comment by vishalp-simplecrm** [comment]
This code will work but not getting correct result getting broken words on react frontend

# Flask App Code
app = Flask(__name__)

@app.route('/')
@cross_origin()
def home():
    return render_template('index.html')


@app.route('/query', methods=['POST'])
@cross_origin()
def query():
    query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
    prompt = request.json
    # prompt['prompt'] += " Give in html format"
    print('prompt given issss:',prompt)
    response_stream = query_engine.query(prompt['prompt']) 
    # response_stream.print_response_stream()
    def generate_response():
        for text in response_stream.response_gen:
                yield  f"data: {text}\n\n" 
                # print(text)
    return Response(stream_with_context(generate_response()), mimetype='text/event-stream')

**Comment by Disiok** [comment]
We are adding a tutorial on how to do this! Stay tuned.

**Comment by asadabbas09** [comment]
@Disiok just wondering do we have a tutorial yet?

**Comment by asadabbas09** [comment]
I have used the following and it worked with Flask backend and react front end:


```
from flask import Response

def generate_response_stream(response_gen):
    """Yield the response stream."""
    for text in response_gen:
        yield text

@app.route('/query', methods=['POST'])
def process_query():
    data = request.get_json()
    user_query = data['query']
    response = query_engine.query(user_query)
    return Response(generate_response_stream(response.response_gen), mimetype='text/plain')
```

**Comment by XFRCSD45** [comment]
Hey how did you handle the response in frontend in react ?
