### ISSUE TITLE
Make multiple documents / indexes with PDFReader from llamahub

### ISSUE THREAD

**Issue by Michasx** [jerryjliu/llama_index#4642]
Hi, I try to use llama hub and get data from pdf by PDFReader(), but then I realize that I can make only one pdf with this (I have 6 diffrent), becouse I need to use file=Path(). I try making 2 index and use GPTListIndex but this didn't work. Does anyone solve that problem before?

PS: sorry for any mistake or stupid sentences, I'm new in this XD

![image](https://github.com/jerryjliu/llama_index/assets/62339592/0d65a48a-5fc1-446b-bc61-1ef22b9a3c01)

![image](https://github.com/jerryjliu/llama_index/assets/62339592/1738adef-e166-4111-b7b4-4851c1d0759a)

**Comment by logan-markewich** [comment]
You can load all pdfs into a single index, the SimpleDirectoryReader makes this easy 

```python
from llama_index import SimpleDirectoryReader, GPTVectorStoreIndex

documents = SimpleDirectoryReader("./path/to/data").load_data

index = GPTVectorStoreIndex.from_documents(documents)
```

**Comment by vishalp-simplecrm** [comment]
Can we read pdf from google drive also

**Comment by Michasx** [comment]
> Can we read pdf from google drive also

Yea you probably can use this: https://llamahub.ai/l/google_drive
or this one: https://llamahub.ai/l/google_docs

**Comment by Michasx** [comment]
> You can load all pdfs into a single index, the SimpleDirectoryReader makes this easy
> 
> ```python
> from llama_index import SimpleDirectoryReader, GPTVectorStoreIndex
> 
> documents = SimpleDirectoryReader("./path/to/data").load_data
> 
> index = GPTVectorStoreIndex.from_documents(documents)
> ```

But then I cannot load pdf, I need to use loader.load_data(), I thing SimpleDirectoryReader work only with txt file.
And also get this error
![image](https://github.com/jerryjliu/llama_index/assets/62339592/81268a1b-15f5-46ab-90d8-664d48ecd12d)

**Comment by logan-markewich** [comment]
Whoops, typo. Yea you need load_data() at the end

SimpleDirectoryReader supports a ton of file extensions, not just txt

**Comment by Michasx** [comment]
> Whoops, typo. Yea you need `load_data()` at the end: `documents = SimpleDirectoryReader("./path/to/data").load_data()`
> 
> SimpleDirectoryReader supports a ton of file extensions, not just txt

Oh yea XD, my mistake. It worked but I can feel it's not the same like using PDFReader, the AI answer sometimes isn't what I expected. When I use this PDFReader the AI answer was more matching and specific to question. Probably there is no best way to do this, so thank you so much for helping, I will go SimpleDirectoryReader ^^

**Comment by logan-markewich** [comment]
Yea, there's a few other settings you can tweak like similarity_top_k and chunk_size, I'm sure you'll find what works best after some experimenting! 💪
