### ISSUE TITLE
Knowledge Graph always hits rate limits

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/llama_index#465]
No matter what I do it seems like that the knowledge graph structure always hits rate limits upon indexing:

```
            llm_predictor_deep = LLMPredictor(
                llm=OpenAI(model_name="text-davinci-003", temperature=0, max_tokens=-1)
            )
            index = await self.loop.run_in_executor(
                None, partial(GPTKnowledgeGraphIndex, documents, chunk_size_limit=512, max_triplets_per_chunk=2, embed_model=embedding_model, llm_predictor=llm_predictor_deep)
            )
```

will always result in a ratelimit error no matter what the documents are that I'm making the graph with

```
openai.error.RateLimitError: Rate limit reached for default-text-davinci-002 in organization org-4GsP10uk0ZJ5DfkUDN7BiGbh on tokens per min. Limit: 250000.000000 / min. Current: 490580.000000 / min. Contact support@openai.com if you continue to have issues.
```

**Comment by Kav-K** [comment]
Eventually it starts just outright erroring out on the requests

```
 500 {'error': {'message': 'The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Fri, 17 Feb 2023 03:05:19 GMT', 'Content-Type': 'application/json', 'Content-Length': '292', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Model': 'text-davinci-003', 'Openai-Organization': 'gpt3discord', 'Openai-Processing-Ms': '30092', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Request-Id': '44d2b03abdc3140a620d7962e86bbccb'}
 ```

**Comment by jerryjliu** [comment]
if you're still running into rate limits, can you try text-davinci-002?

**Comment by Kav-K** [comment]
![image](https://user-images.githubusercontent.com/21161101/221343899-e4e425bb-2d23-4bc0-8933-13f171244da7.png)

text-davinci-002 has the same issues unfortunately, knowledge graph index is entirely unusable for me

**Comment by Kav-K** [comment]
It seems like it's doing one request, for over the max token amount, instead of batching it into like two requests of smaller size?

**Comment by jerryjliu** [comment]
@Kav-K is this still an issue for you?

**Comment by Mrs-Hudson** [comment]
I am seeing this issue as well

**Comment by Kav-K** [comment]
Yup still also an issue for me

**Comment by Kav-K** [comment]
This is fine for me on 0.4.17, still quite slow but not entirely blocked

**Comment by jerryjliu** [comment]
yeah @Kav-K i think this may be more due to openai's rate limit issues

**Comment by Disiok** [comment]
Closing this for now, since it's mostly due to openai's rate limit issues.

We will continue to make optimizations to e.g. reduce number of requests.
