### ISSUE TITLE
query without index with vector database with node info

### ISSUE THREAD

**Issue by hawktang** [jerryjliu/llama_index#4666]
version 0.6.16post1

Is possible to remove index in the constructor for query when using vector database like qdrant.

When there is node info and extra info in vector database, there seem not need for doc store and index store.

By this, the index and query process can be decoupled, make query side much slim.

**Comment by Disiok** [comment]
We recently made this slightly less cumbersome: https://gpt-index.readthedocs.io/en/latest/how_to/index/vector_store_guide.html#connect-to-external-vector-stores-with-existing-embeddings

But yes, continuing to improve the abstractions here. Stay tuned!

**Comment by wilmerhenao** [comment]
> 

Did you move this document somewhere? It doesn't work.
