### ISSUE TITLE
can prompt_tokens_count and prediction_tokens_count be statics separately

### ISSUE THREAD

**Issue by hawktang** [jerryjliu/llama_index#4667]
version 0.6.16post1
can prompt_tokens_count and prediction_tokens_count be statics separately as GPT4 has different price for can prompt_tokens_count and prediction_tokens_count.

**Comment by logan-markewich** [comment]
They are now!

https://gpt-index.readthedocs.io/en/latest/examples/callbacks/TokenCountingHandler.html
