### ISSUE TITLE
multiturn prompt and index update

### ISSUE THREAD

**Issue by noke8868** [jerryjliu/llama_index#4943]
Hi 
thank you for your efforts for providing such good tool.
i am trying to build a multiturn chatbox via Chatgpt API. i am trying to understand a generic procedure to use llama_index for this case.
Chatgpt requires the current input and the history as new input. 
my two questions are:
--should i use the new input as context_str for prompt like below?
--if yes, should i also use index.insert to generate new document and new index?
thank you for your help

    Support_Prompt = (
    "As a product support professional, try to provide a suitable resolution to the customer's issue.\n "
    "\n"
    "\n"
    "{context_str}\n"
    "\n"
    "\n"
    "Given this information, please answer the question: {query_str}\n"
    )

**Comment by Disiok** [comment]
Take a look and see if this is what you need https://gpt-index.readthedocs.io/en/latest/how_to/chat_engine/root.html
