### ISSUE TITLE
Add postgres vector database support 

### ISSUE THREAD

**Issue by m3hari** [jerryjliu/llama_index#499]
Postgres can now facilitate vector similarity search with the newly developed [pgvector extension](https://github.com/pgvector/pgvector). As Postgres is widely used in the application layer, having a single database engine for simple apps would greatly simplify the development process.

**Comment by jerryjliu** [comment]
@m3hari do you mean using postgres as a vector store? there's already a database reader in llamahub that allows loading of structured data into unstructured documents https://llamahub.ai/l/database, and we also have a structured store index allowing text-to-SQL queries https://gpt-index.readthedocs.io/en/latest/reference/indices/struct_store.html

**Comment by m3hari** [comment]
@jerryjliu no, I don't mean loader, I am referring to **storing indices** the default way seems to be a local file (JSON format) as far as I understand, but I want to store the embeddings in Postgres.

Like  **qdrant**, Postgres can be used as vector/embedding storage and search with this [extension](https://github.com/pgvector/pgvector).

**Comment by m3hari** [comment]
Basically, storing vector indices with Postgres as a backend like (Pinecone, qdrant ...)

**Comment by bborn** [comment]
Just adding my support for this @jerryjliu. I started trying to do this myself but got a bit lost in the index internals. 

Here's what I have so far: https://gist.github.com/bborn/5d3a7f138fce32610102ef7775502d2f

**Comment by jerryjliu** [comment]
> Just adding my support for this @jerryjliu. I started trying to do this myself but got a bit lost in the index internals.
> 
> Here's what I have so far: https://gist.github.com/bborn/5d3a7f138fce32610102ef7775502d2f

@bborn this looks great! these are basically the main components that you'd need to add (the vector store, a wrapper around the index and query classes).

**Comment by rl3250** [comment]
@bborn Did you got PR on this?

**Comment by bborn** [comment]
@rl3250  nope - haven't had a chance yet.

**Comment by logan-markewich** [comment]
This has been added

https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/postgres.html#postgres-vector-store
