### ISSUE TITLE
FlexGen with GPT Index

### ISSUE THREAD

**Issue by ekiwi111** [jerryjliu/llama_index#507]
FlexGen has just been released - https://github.com/Ying1123/FlexGen

FlexGen is a high-throughput generation engine for running large language models with limited GPU memory (e.g., a 16GB T4 or a 24GB RTX3090 gaming card!).

Would it be possible to run GPT Index with it?

**Comment by logan-markewich** [comment]
By default, gpt index doesn't run any models, and merely queries the openAI api 

You can use custom LLMs that are run locally in gpt index as well. I've got access to a 46GB card, and so far nothing open source has come even close to match OpenAI's LLM performance (Facebook OPT, Google FLAN T5, GPT-J 6B), so I'd say it's not worth your time (but this will likely change in the coming month I suspect! New models are always on the horizon)

**Comment by genesst** [comment]
> and so far nothing open source has come even close to match OpenAI's LLM performance (Facebook OPT, Google FLAN T5, GPT-J 6B)
I this applicable to all downstream tasks or just a subset? Wouldn't they work comparable similar for classification, question-answering or text summarization?

**Comment by logan-markewich** [comment]
Not really comparable. OPT and GPT-J are great text-generation models, they will ramble on forever. But they won't follow instructions.

FLAN-T5 comes close, as it was trained on over 1000 tasks, but it still struggles to follow some prompts. Additionally, the limited input size (512 tokens!) really limits its usefulness (in the context of this repo)

At least for now, I wouldn't bother using anything other than OpenAI for LLMs, unless you are prepared to take a hit in quality

**Comment by jiweiqi** [comment]
@genesst did you figure out how to use FlexGen with GPTindex? It is still worth using FlexGen for a quick demo. OpenAI's API is quite expensive for large documents.

**Comment by genesst** [comment]
> @genesst did you figure out how to use FlexGen with GPTindex? It is still worth using FlexGen for a quick demo. OpenAI's API is quite expensive for large documents.

Not yet, waiting for llama or flan-t5 integration

**Comment by Ying1123** [comment]
GPTIndex could be a perfect fit for FlexGen. FlexGen targets high-throughput batch processing, so generating embedding for a batch of local documents is its ideal use case.
We (the FlexGen team) will be happy to help if anyone wants to undertake this.

**Comment by jiweiqi** [comment]
> 

look forward to a working example :)

**Comment by jerryjliu** [comment]
Hi @Ying1123, sorry for  the delay in response. we'd be happy to explore an integration! 

Currently you can generally swap out the underlying LLM through langchain, but we also added a very light chatgpt wrapper here: https://github.com/jerryjliu/gpt_index/blob/main/gpt_index/langchain_helpers/chatgpt.py
