### ISSUE TITLE
Show progress when ingesting many documents using GPTWeaviateIndex

### ISSUE THREAD

**Issue by hsm207** [jerryjliu/llama_index#523]
It would be useful to show progress e.g. using tqdm when user upload a lot of documents.

**Comment by jerryjliu** [comment]
it's a good TODO to think about re: all indices

**Comment by logan-markewich** [comment]
You can now show progress during index construction

https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/usage_pattern.html#high-level-api

**Comment by rnbokade** [comment]
Is there a programmatic way to access the progress while the indexing is happening? Like instead of tqdm if we could somehow get the progress and send it over some api
