### ISSUE TITLE
Nit: Add corresponding code block on top of screenshot

### ISSUE THREAD

**Issue by jianghoy** [jerryjliu/llama_index#531]
Hi, I was reading the documentation and this line (docs/how_to/embeddings.md#line15) is a screenshot while all other code blocks are perfectly fine. I think it would be a good idea to swap it with the actual code, or have an actual code on top of it. Let me know if you endorse my idea. Can submit PR for this issue.

**Comment by jerryjliu** [comment]
Hi @jianghoy, sure! sorry been a bit swamped, feel free to submit a PR for this

**Comment by Disiok** [comment]
Closing thread since it's stale.
