### ISSUE TITLE
Implement a streaming text splitter

### ISSUE THREAD

**Issue by not-poma** [jerryjliu/llama_index#546]
Currently, the TextSplitter interface only allows for splitting text into fixed-size chunks and returning the entire list before any queries are run. It would be great if we could split text input dynamically to provide each query step with as large context window as possible, this would make tasks like summarization much more efficient.

It should estimate the number of available tokens for each query and ask the TextSplitter to yield the next chunk of at most X tokens.

**Comment by jerryjliu** [comment]
interesting - out of curiosity, why would this make summarization more efficient? wouldn't you still need to wait for all chunks to be processed before getting the final answer?

**Comment by not-poma** [comment]
This can be important for more complex summary formats where a summary can take like 1000 tokens:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/111893939/222498966-a8647446-ef9d-4254-910c-502b8a338190.png">

In this case, up to 1000 tokens are taken by the previous summary, and up to 1000 tokens are left for the generated summary, plus some more for the instructions. This means each additional iteration will waste up to 2k tokens, and we want to minimize that.

In addition to that, I think a single invocation with a large context gives better results than 2 sequential invocations with smaller chunks, it's useful to have the model see as much context as possible when generating the summary.
