### ISSUE TITLE
Please replace the Tiktoken dependency with a library in pure python (not Rust)

### ISSUE THREAD

**Issue by Emasoft** [jerryjliu/llama_index#567]
Please replace the Tiktoken dependency with a tokenizer library in pure python (not Rust dependencies) for people like me that cannot compile and run Rust binaries on their system (for various reasons: package managers support, company policy, intranet or local machine security, docking containers limitations, vm restrictions, environment virtualization, lack of Rust support in jupyter notebooks remote hosting, etc).

**Comment by fredzannarbor** [comment]
I would not say "replace" but I endorse providing an alternate pure-python path.  at some places it's very difficult to install anything unfamiliar.

**Comment by Emasoft** [comment]
Yes, you can add the pure python version as a fallback.
@jerryjliu ?

**Comment by jerryjliu** [comment]
@Emasoft thanks for flagging, hopefully will take a look today or tomorrow

**Comment by Emasoft** [comment]
@jerryjliu Any update on this?

**Comment by logan-markewich** [comment]
If you are running python3.8, the tokenizer from transformers will be used instead of tiktoken

**Comment by fredzannarbor** [comment]
Wow, this is way better than a human would have produced, if at all.
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>
