### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#5832]
My docs is in Vietnamese and I get this error:
ZeroDivisionError: integer division or modulo by zero
When trying to run Compare Contrast Query:

graph = ComposableGraph.from_indices(
        GPTSimpleKeywordTableIndex,
        [index for _, index in report_indices.items()], 
        [summary for _, summary in index_summaries.items()],
        max_keywords_per_chunk=50
    )

    decompose_transform = DecomposeQueryTransform(
        llm_predictor, verbose=True
    )

    custom_query_engines = {}
    for index in report_indices.values():
        query_engine = index.as_query_engine(service_context=service_context, streaming=True)
        transform_extra_info = {'index_summary': index.index_struct.summary}
        tranformed_query_engine = TransformQueryEngine(query_engine, decompose_transform, transform_extra_info=transform_extra_info)
        custom_query_engines[index.index_id] = tranformed_query_engine

    custom_query_engines[graph.root_index.index_id] = graph.root_index.as_query_engine(
        retriever_mode='simple', 
        response_mode='tree_summarize', 
        service_context=service_context,
        streaming=True
    )

    query_engine_decompose = graph.as_query_engine(
        custom_query_engines=custom_query_engines,
        # streaming=True
    )
response = query_engine_decompose.query(input_text)

**Comment by logan-markewich** [comment]
This is likely because no keywords were found in the query

You are using the simple keyword index. This will use a regex and some basic parsing to remove stopwords, and all remaining words are considered keywords.

If the query is too short, or contains no keywords, this error cam happen

**Comment by dinhan92** [comment]
Thanks @logan-markewich I fix this
