### ISSUE TITLE
ChatGPT model when used for querying is a bit forced / fixed, breaks the query chain

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/llama_index#590]
![image](https://user-images.githubusercontent.com/21161101/222315905-4b27a097-97ee-4f80-a07b-1e16db442eea.png)

The query refining pipeline when doing a query seems to be a little broken (I guess the Q&A / pipeline prompt will need adjustment for chatgpt?), it seems to take the context step too literally and if there's new context provided that's better than previous context it won't mention the previous context, effectively "losing" data as it proceeds through the refining steps

**Comment by Kav-K** [comment]
The screenshot is the result of me doing a query on a GPTTreeIndex that contains content from the web about "Harald Baldr". The query was simply "Who is harald baldr"?

**Comment by Kav-K** [comment]
![image](https://user-images.githubusercontent.com/21161101/222491648-c6b8de1e-13d0-4bd3-ae42-b972351ace8f.png)

Getting this also from the result of querying a simple vector index -- looks like the ChatGPT personality behaviour really breaks the internal dialogue when doing a query

**Comment by jerryjliu** [comment]
Hi @Kav-K, yeah this is something we can look into. Btw are you using langchain's wrapper or the gpt index chatgpt wrapper? try using the former

**Comment by jerryjliu** [comment]
Hi @Kav-K we just landed a refine prompt update. take a look at using the chat refine prompt here: https://github.com/jerryjliu/gpt_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb

**Comment by Kav-K** [comment]
Hmm, seems like the same issues if not worse now:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/21161101/223218596-ebb586f1-a5ee-4752-bf7c-ed048c6088e2.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/21161101/223218617-b0d75ee9-f1c3-485e-9e1c-f028154cb609.png">

These are queries from simple vector indexes with nodes=2

**Comment by adi87** [comment]
Sort of relevant to this, for my use case the `gpt-3.5-turbo` model provides a good answer that doesn't need refinement. Is it possible to skip the refine step when running the `index.query()`?

**Comment by logan-markewich** [comment]
We've introduced some improvements to the refine prompt recently

Regarding your comment @adi87 you would need to define how to detect when the answer is good enough 😉 Pretty hard problem, but would love to see a contribution on this.
