### ISSUE TITLE
response_stream.response_gen giving addition spaces when we used this to show response using react frontend

### ISSUE THREAD

**Issue by vishalp-simplecrm** [jerryjliu/llama_index#5999]
# Getting Broken Words
taking unnecessary spaces within the words please resolve this issue
BERT is single word given as B ERT
 Bidirectional as  Bid irectional

![image](https://github.com/jerryjliu/llama_index/assets/115548851/ce48dbe8-7250-48bf-94d6-b193b4254249)

**Comment by logan-markewich** [comment]
Are you using streaming? tbh I've never seen anyone have this issue before. Might be a problem with your frontend code?

**Comment by vishalp-simplecrm** [comment]
#please refer this code which I am using 
@app.route('/query', methods=['POST'])
def query():
    query_engine = index.as_query_engine(similarity_top_k=3, streaming=True)
    prompt = request.json
    # prompt['prompt'] += " Give in html format"
    print('prompt given issss:',prompt)
    response_stream = query_engine.query(prompt['prompt']) 
    # response_stream.print_response_stream()
    def generate_response():
        for text in response_stream.response_gen:
                yield  f"data: {text}\n\n" 
                # print(text)
    return Response(stream_with_context(generate_response()), mimetype='text/event-stream')
