### ISSUE TITLE
Support for complex prompt formats in the chat engine, similar to OpenAI's Chat Completions API

### ISSUE THREAD

**Issue by XTZhang** [jerryjliu/llama_index#6047]
Hello,

I'm currently using the chat engine in LlamaIndex and I'm having some issues regarding the format of the prompts. Specifically, the current implementation doesn't seem to support the complex format used by OpenAI's Chat Completions API (https://api.openai.com/v1/chat/completions).

The OpenAI API takes a list of messages as input, each with a role (either 'system', 'user', or 'assistant') and content (the text of the message). For example:

json

{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello!"}]
}

However, in the chat engine configuration (https://gpt-index.readthedocs.io/en/latest/how_to/chat_engine/usage_pattern.html), when I define the custom_prompt for CondenseQuestionChatEngine.from_defaults, it doesn't seem to support this context string format.

python

chat_engine = CondenseQuestionChatEngine.from_defaults(
    query_engine=query_engine, 
    condense_question_prompt=custom_prompt,
    chat_history=custom_chat_history,
    verbose=True
)

This limitation is inhibiting the ability to have more sophisticated interactions with the model, especially in the context of conversational AI.

I would like to request that you consider adding support for this complex prompt format, similar to how it is implemented in OpenAI's Chat Completions API. It would greatly enhance the flexibility and usability of the chat engine.

Thank you for your consideration.

**Comment by mintisan** [comment]
This feature is really a good way to reuse the experience of OpenAI, and it can also make our LlamaIndex interface more flexible.

Very much looking forward to...

XD

**Comment by Disiok** [comment]
You are absolutely right @XTZhang, we need more chat engine implementation that better integrates with OpenAI chat API.

**Comment by Disiok** [comment]
Trying to prioritize this among other stuff we are improving! Stay tuned, also would appreciate contribution in this direction if you guys want to take a stab!
