### ISSUE TITLE
TypeError with LlamaIndexTool keyword args/uncertainty between LlamaIndexTool/IndexToolConfig usage

### ISSUE THREAD

**Issue by ahwitz** [jerryjliu/llama_index#6056]
Issue encountered on both `0.6.15` and `0.6.20`.

Our desired usecase is:

1) Build an index that contains one document per file in one or more Github repositories.
2) Prompt the LLM with a text description of a requested code change.
3) Have the LLM fill out the context it needs to confidently make the code change.
4) Retrieve the code it generated.

Where we're at right now:
- Followed the [Chatbot SEC](https://github.com/jerryjliu/llama_index/blob/5a515c7ec0f9f3812daf2a68c2923cda0a4490f5/examples/chatbot/Chatbot_SEC.ipynb) example as possible to get one index per repository, with one ComposableGraph on top of them.
- Set up LlamaIndexTool instances used by `langchain.agents.initialize_agent`, which resulted in the titular error:
```
Thought: 

To provide the new content of the file, we need to access the content of the file in the <repo-name> repository. We can use the Vector IndexToolConfig for repo <org-name>/<repo-name> to find the content of the file. Once we have the content, we can copy and paste it into the new file in the <new-repo-name> repository.

Action:
{
  "action": "Vector IndexToolConfig for repo <org-name>/<repo-name>",
  "action_input": {
    "title": "src/traffic-event-interceptor/inject/addInjected.ts"
  }
}

Traceback (most recent call last):
  File "index.py", line 78, in <module>
    prompt_generator.prompt_single_file_content(file_json)
  File "prompts.py", line 142, in prompt_single_file_content
    response = chat_agent.run("\n".join([
  File ".venv/lib/python3.10/site-packages/langchain/chains/base.py", line 236, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
  File ".venv/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File ".venv/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File ".venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 922, in _call
    next_step_output = self._take_next_step(
  File ".venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 800, in _take_next_step
    observation = tool.run(
  File ".venv/lib/python3.10/site-packages/langchain/tools/base.py", line 255, in run
    raise e
  File ".venv/lib/python3.10/site-packages/langchain/tools/base.py", line 251, in run
    else self._run(*tool_args, **tool_kwargs)
TypeError: LlamaIndexTool._run() got an unexpected keyword argument 'title'
```
- Set up IndexConfigTool instances used by `create_llama_chat_agent`, which didn't seem to parse things correctly:
```
> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: Vector IndexToolConfig for repo <org-name>/<repo-name>
Action Input: contents of addInjected.ts
Observation: I'm sorry, but I cannot provide the contents of the "addInjected.ts" file as it is not mentioned or included in the provided context information.
```

The code shell for the latter (which doesn't seem to be recognizing things correctly) would be:
```py
index_configs = [] # setup from chatbot example
graph_config = IndexToolConfig(
    query_engine=graph_query_engine,
    name=f"Graph Index",
    description="Can be used to learn more about files in other code repositories.",
    tool_kwargs={"return_direct": True}
)
configs = index_configs + [graph_config]
toolkit = LlamaToolkit(
    index_configs=configs
)

memory = ConversationBufferMemory(memory_key="chat_history")
llm=ChatOpenAI(temperature=0)
agent_chain = create_llama_chat_agent(
    toolkit,
    llm,
    memory=memory,
    verbose=True
)

response = chat_agent.run("\n".join([
    self._get_feature_request_text(),
    self._get_file_list_text(),
    f"Your job is to provide a single file change for the above feature request. You have been asked to change the file at {path}."
    # plus some more information
]))
```

The code shell for the former (which does seem to be recognizing things correctly, but runs into an error where `action_input` isn't passed in correctly) would be:

```py
index_configs = [] # setup from chatbot example
graph_config = LlamaIndexTool(
    query_engine=graph_query_engine,
    name=f"Graph Index",
    description="Can be used to learn more about files in other code repositories.",
    return_direct=True
)
tools = index_configs + [graph_config]

memory = ConversationBufferMemory(memory_key="chat_history")
llm=ChatOpenAI(temperature=0)
agent_chain = initialize_agent(
    tools,
    llm=llm,
    agent="structured-chat-zero-shot-react-description",
    memory=memory,
    verbose=True
)

response = chat_agent.run("\n".join([
    self._get_feature_request_text(),
    self._get_file_list_text(),
    f"Your job is to provide a single file change for the above feature request. You have been asked to change the file at {path}."
    # plus some more information
]))
```

It seems like the LlamaIndexTool strategy is getting us the best results from OpenAI, but we're open to either path if you've got recommendations. The two questions on our minds are:

- Is the TypeError user error or an issue with parts of this codebase and LangChain evolving quickly, and is there anything we can do to move past it? I'm going to try updating a few things in my local copy as I'm expecting it's an issue with `tool_input` in [this line](https://github.com/jerryjliu/llama_index/blob/5a515c7ec0f9f3812daf2a68c2923cda0a4490f5/llama_index/langchain_helpers/agents/tools.py#L58), but any easy advice y'all have will be appreciated.
- If we want to be using the `structured-chat-zero-shot-react-description` agent, are we right to be going with LlamaIndexTool/initialize_agent, or is IndexToolConfig/create_llama_chat_agent overall a more stable/intended solution from the intention of where the codebase is going?

Sorry for the complex usecase and question - let me know if there's any more diagnostic info I can provide!

**Comment by ahwitz** [comment]
Also worth noting: we tried stopping at `ComposableGraph.as_query_engine()` but wanted the Thought/Action/Observation debug to be able to trace how the engine was processing the prompts. If there's a way to get that debug from `as_query_engine.query()`, let us know, especially if that sounds better for our use case.

**Comment by logan-markewich** [comment]
I would recommend using our own react agent now actually: 
https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/usage_pattern.html#query-engine-tools

**Comment by logan-markewich** [comment]
Feel free to re-open if this is still an issue!
