### ISSUE TITLE
Using llama index with existing postgres db and pgvector extension

### ISSUE THREAD

**Issue by alexanderfrey** [jerryjliu/llama_index#6058]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

thanks for the great work ! I am a bit lost when using llama index for paragraph retrieval together with an existing postgres db and a table that already has embeddings computed. 

I am initiating like this:

`vector_store = SupabaseVectorStore(
    postgres_connection_string="postgresql://user:password@host:5432/defaultdb", 
    collection_name='news_paragraphs',
    dimension=768
)`

I have 2 questions:

1.  How can I specify the table to use and the field that contains the embeddings ? Is it collection_name ?
2. Once I did that how can I query the vector_store ? 

Really appreciate any help

**Comment by Disiok** [comment]
I think right now the SupabaseVectorStore assumes that the table is created via `vecs` library or from llama index.
I need to look more closely at the `vecs` library to know how it maps to an existing table.

But once you have properly connected to your table. You can do the following https://gpt-index.readthedocs.io/en/latest/how_to/index/vector_store_guide.html#connect-to-external-vector-stores-with-existing-embeddings

**Comment by sfkeller** [comment]
See also #499

**Comment by jon-chuang** [comment]
From https://github.com/supabase/vecs/blob/35ea7db551c1fef10fb16eebdd9ed27104c087a3/docs/concepts_collections.md?plain=1#L25 the `collection_name` used to initialize `SupabaseVectorStore` is the table name you want to connect to.

I think the docs should be updated to reflect the raw postgres usage, and perhaps one can rename the `SupabaseVectorStore` to `PgVectorStore`. I will test locally that the existing code can work against a local postgres.

Once done we should close both this issue and #499

**Comment by jon-chuang** [comment]
success:

```python
>>> vector_store = SupabaseVectorStore( postgres_connection_string="postgresql://postgres:postgres@127.0.0.1:5432/postgres", collection_name='test_vector_col')
>>> storage_context = StorageContext.from_defaults(vector_store=vector_store)
>>> index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)
>>> query_engine = index.as_query_engine()
>>> response = query_engine.query("Who is the author?")
/home/jonch/.pyenv/versions/llama_index/lib/python3.10/site-packages/vecs/collection.py:182: UserWarning: Query does not have a covering index for cosine_distance. See Collection.create_index
  warnings.warn(
>>> response
Response(response='\nThe author of this text is Paul Graham.'
...
```

**Comment by adrianog** [comment]
I think it'd be better to have a config for this.

**Comment by rahulbayer** [comment]
@jon-chuang  what is documents in the line
>>> index = VectorStoreIndex.from_documents(documents, storage_context=storage_context). I believe for existing DB it should not be required? can you confirm and how to define this documents?
