### ISSUE TITLE
Import error for Multimodall notebook example

### ISSUE THREAD

**Issue by Irene-PHAM** [jerryjliu/llama_index#6116]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

First of all, thank you for the amazing library.

I'm testing out the functionality with multimodal notebook, however it seems that the example is dated. The function name is not the same. Could you please help to pinpoint the exact version used in the example. Or the new notebook? 

Here's the notebook that i run: https://github.com/jerryjliu/llama_index/blob/main/examples/multimodal/Multimodal.ipynb

Many thanks

**Comment by logan-markewich** [comment]
Latest notebook in the repo should be working! Closing for now
