### ISSUE TITLE
[Documentation]: SimilarityPostprocessor enhancement 

### ISSUE THREAD

**Issue by EmanuelCampos** [jerryjliu/llama_index#6122]
### Documentation Issue Description

not enough information about the similarity_cutoff parameters and how it works.

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/how_to/query_engine/advanced/second_stage.html#similaritypostprocessor

**Comment by EmanuelCampos** [comment]
https://github.com/jerryjliu/llama_index/pull/6121

**Comment by logan-markewich** [comment]
This is merged, thanks!
