### ISSUE TITLE
[Bug]: Why do I upgrade llama_index to the newest version and get RateLimitError?

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#6125]
### Bug Description

Why do I upgrade llama_index to the newest version and get RateLimitError?

openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-PH8zdIn1RI0V7H7Aak3Lzy73 on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

### Version

0.6.20

### Steps to Reproduce

max_input_size = 4096
num_outputs = 512
max_chunk_overlap = 0.02
chunk_size_limit = 256

prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

prepend_messages = [
    SystemMessagePromptTemplate.from_template("You are a helpful assistant that use Vietnamese in every response")
]
llm_predictor = ChatGPTLLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=True), prepend_messages = prepend_messages)

service_context = ServiceContext.from_defaults(
        llm_predictor = llm_predictor,
        prompt_helper = prompt_helper)

def chatbot:
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
 
    index = load_index_from_storage(storage_context = storage_context,
                                    
                                    service_context = service_context)
  
    query_engine = index.as_query_engine(
        streaming=True,
       
    )

    
    response = query_engine.query(input_text)

**Comment by Disiok** [comment]
Hey @dinhan92, not sure what might've caused the difference. 

One thing I did notice is that you are using fairly small chunk size at 256. For some index this might mean a lot of LLM calls are executed

**Comment by dinhan92** [comment]
@Disiok where should I set the language? Now it is English... the language of the old version is correct but in the latest version, it's wrong

**Comment by nithinjp1997** [comment]
Can I ask why having a small chunk size cause an issue if I am using vectorstoreindex and compact response mode. My reasoning is that even if the chunk size is small the default no of documents retrieved is 2 and compact mode puts these 2 documents into a single prompt so in total only a single call for completion is required. So what difference does a larger chunk size have over the smaller chunk size. ( cause any how both of them should only make 1 api call in effect )

**Comment by dinhan92** [comment]
Nevermind, I fix this, Thanks @Disiok
