### ISSUE TITLE
[Question]: Vector index creation with LLM-A and Query with LLM-B. Loading vector without connection to API and costs for tokens.

### ISSUE THREAD

**Issue by itsergiu** [jerryjliu/llama_index#6163]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Question 1.
Why does the loading of already created and stored vectors require OpenAI API and cost tokens the same as for creation?
How to avoid costs for tokens every time a vector is loaded?

Question 2.
Does LlamaIndex support other LLM integration?
_Vector creation with gpt4all and query with gpt4all is possible: 
https://colab.research.google.com/drive/16QMQePkONNlDpgiltOi7oRQgmB8dU5fl?usp=sharing__

How about vector creation with gpt4all and query with OpenAI

Regards,
Sergiu

**Comment by araichev** [comment]
@logan-markewich i am also curious about using local LLMs with Llama index.
Could you fix the last two links above, which appear to describe how to do that?
They are broken with 404 errors.

**Comment by logan-markewich** [comment]
@araichev 

Embeddings
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations


LLMs
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-huggingface-llm

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced
