### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nithinjp1997** [jerryjliu/llama_index#6172]
### Bug Description

![image](https://github.com/jerryjliu/llama_index/assets/61446944/60591172-fece-498d-94ed-3d9c607a04df)
Even though I am specifying the no of top-k documents to pull the retriever is still pulling only 2 documents. I even tried changing the default value inside the code still no change . Please look into this. I am using VectorStoreIndex. 

### Version

0.6.20

### Steps to Reproduce

Create an index using VectorStoreIndex.
Load it from the disk . 
Set the index as a retriever and pass the similarity_top_k = anything other than 2 ( because 2 is default)

**Comment by Disiok** [comment]
You should do `retriever = index.as_retriever(similarity_top_k=5)` to pass kwargs
