### ISSUE TITLE
Question: The documentation is not clear about what the project really does

### ISSUE THREAD

**Issue by murilocurti** [jerryjliu/llama_index#618]
What the project really does for us?

The Proposed Solution: 

> That’s where the LlamaIndex comes in. LlamaIndex is a simple, flexible interface between your external data and LLMs. It resolves the > following pain points:
>
> Provides simple data structures to resolve prompt size limitations.
>
> Offers data connectors to your external data sources.
>
> Offers you a comprehensive toolset trading off cost and performance.
>
> At the core of LlamaIndex is a data structure. Instead of relying on world knowledge encoded in the model weights, a GPT Index data > structure does the following:
>
> Uses a pre-trained LLM primarily for reasoning/summarization instead of prior knowledge.
>
> Takes as input a large corpus of text data and build a structured index over it (using an LLM or heuristics).
> 
> Allow users to query the index by passing in an LLM prompt, and obtaining a response.

Could explain what and how the project solves the problem.
I suggest a drawing with a flow and explain what happens when creating the index and when a prompt is made by the user.

**Comment by logan-markewich** [comment]
Docs have been revamped lately, check them out!

I especially like the high-level concepts section
https://gpt-index.readthedocs.io/en/latest/getting_started/concepts.html
