### ISSUE TITLE
[Question]: Injecting context to SqlDatabase, context is not stored locally

### ISSUE THREAD

**Issue by sumanthp** [jerryjliu/llama_index#6185]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to inject additional context related to sql database tables and trying to store the index created locally. The index files stored do not have additional context getting stored.

`def create_index(selected_tables, table_contexts, model_option, model_temperature, index_name):
    storage_context = StorageContext.from_defaults(persist_dir="./storage")
    # Set up Azure OpenAI chat model
    llm = AzureChatOpenAI(
        model=model_option,
        deployment_name=model_option,
        temperature=model_temperature,
        max_tokens=512,
        openai_api_base=openai.api_base,
        openai_api_key=AZURE_OPENAI_KEY,
        openai_api_version=AZURE_OPENAI_API_VERSION
    )
    llm_predictor = LLMPredictor(llm=llm)
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=st.session_state["embedding_llm"])
    
    sql_database = SQLDatabase(st.session_state["engine"], include_tables=selected_tables, view_support=True)
    st.session_state.index_sql_db_map[index_name] = sql_database
    if table_contexts is not None and len(table_contexts)>0:
        # Retrieve additional table context text boxes input
        additional_contexts = {}
        for table in selected_tables:
            if table in table_contexts and table_contexts[table]:
                additional_contexts[table] = [Document(table_contexts[table])]

        context_builder = SQLContextContainerBuilder.from_documents(
            additional_contexts, 
            sql_database,
            service_context=service_context
        )
        context_container = context_builder.build_context_container()
        index = GPTSQLStructStoreIndex.from_documents(
            [],
            sql_database=sql_database,
            sql_context_container=context_container,
            service_context=service_context,
            storage_context=storage_context
        )
    else:
        index = GPTSQLStructStoreIndex.from_documents(
            [],
            sql_database=sql_database,
            service_context=service_context,
            storage_context=storage_context
        )
    storage_context.persist(persist_dir=f'./storage/streamlit_indexes/llama/'+index_name)
    st.session_state.index_id_map[index_name] = index.index_id
    st.session_state.index_chain_map[index_name] = initialize_chain(model_temperature, index)
    return index`

**Comment by logan-markewich** [comment]
actually, `persist()` doesn't really work for SQL indexes, since everything is stored in the DB for the most part

I would hardcode the table descriptions personally
