### ISSUE TITLE
[Bug]: Weaviate Vector Store Index Invalid class name error

### ISSUE THREAD

**Issue by Sik819** [jerryjliu/llama_index#6193]
### Bug Description

![image](https://github.com/jerryjliu/llama_index/assets/39178157/7c507dab-5110-42a8-83e2-44fb009d4e5b)
 
The vectore index library seems to be suffixing _node and seems like weaviate does not allow _ in their class and property names. I tried using the WeaviateIndexDemo Notebook  which also seems to raising the error.

### Version

llama_index: 0.6.19 Weaviate-client: v3.19.2

### Steps to Reproduce

1. Initiate Weaviate Client - I am using docker (client = weaviate.Client('http://localhost:8080')
2. Initiate Weaviate Vector Store - vector_store = WeaviateVectorStore(weaviate_client=client)

**Comment by Disiok** [comment]
I think the old logic uses a random int, and you got unlucky with an int that's too long. 
This is fixed now (PR landing soon).
