### ISSUE TITLE
[Bug]: not able to run PandasExcelReader 

### ISSUE THREAD

**Issue by eyalsofer** [jerryjliu/llama_index#6203]
### Bug Description

when running the excat same code of the ofiicial example of PandasExcelReader at llama-hub page, i get the following err:
TypeError: PandasExcelReader.load_data() got an unexpected keyword argument 'pandas_config'
when removing pandas_config parameter, i get the following err:
AttributeError: 'PandasExcelReader' object has no attribute '_row_joiner'

### Version

V0.6.21.post1

### Steps to Reproduce

just try the official example code of PandasExcelReader

**Comment by SteffenEnz** [comment]
Same for me :-(

**Comment by Adam-StarOps** [comment]
Having the same issue

**Comment by andresrex** [comment]
Same here :/

**Comment by iklein99** [comment]
Same here.  Any update?  Do we actually test this stuff?

**Comment by j-amit04** [comment]
Is there any update on this issue?

**Comment by Korayem** [comment]
I stopped using llama index and switched to langchain doc loaders

**Comment by kevinlu1248** [comment]
Got Sweep to fix at https://github.com/emptycrown/llama-hub/pull/391. Not sure if the docs were wrong or if it was a real bug though...

**Comment by jerryjliu** [comment]
hey everyone, sorry about this issue. the example shown here is wrong (there's no `pandas_config` arg in `load_data`) https://llamahub.ai/l/file-pandas_excel

**Comment by jerryjliu** [comment]
Closed in https://github.com/emptycrown/llama-hub/pull/397
