### ISSUE TITLE
[Question]: Does GPTVectorStoreIndex serve as the sole vector index for storing the data into a DB?

### ISSUE THREAD

**Issue by YasmineMh** [jerryjliu/llama_index#6219]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey, I attempted to index documents using GPTTreeIndex and save them into Weaviate using the following code:

```
vector_store = WeaviateVectorStore(weaviate_client=client, class_prefix=class_prefix)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTTreeIndex.from_documents(doc, storage_context=storage_context)
```

However, the data was not saved. Nevertheless, when I tested it with GPTVectorStoreIndex, the data was successfully saved:

```
vector_store = WeaviateVectorStore(weaviate_client=client, class_prefix=class_prefix)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTVectorStoreIndex.from_documents(doc, storage_context=storage_context)
```

Any insights on that?

Thanks!

**Comment by Disiok** [comment]
The tree index doesn't use a vector store. It saves its data into an index store and document store. If you don't explicitly set the two, in memory versions are used. You need to call `persist` on the storage context to save them (i.e. to disk)

**Comment by Disiok** [comment]
yes, that's correct. You'd need to use a separate document store.
