### ISSUE TITLE
[Question]: Understanding token usage when generating indexes

### ISSUE THREAD

**Issue by sousanunes** [jerryjliu/llama_index#6229]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there!

I'm generating a vector index for several documents, totaling 41568 words. Considering an average of 1.3 tokens per word, the default llama_index chunk size of 1024 tokens, and the default overlap of 200 tokens, I get the following estimates (rounded):

No. input tokens = 1.3 * No. input words = 1.3 * 41568 = 54038 tokens
No. chunks = No. input tokens / (1024 - 200) = 54038 / 824 = 65.6 chunks
No. tokens to embed = chunk size * no. chunks = 1024 * 65.6 = 67155 tokens

However, the llama_index token counter tells me I've used 134046 tokens, which is almost exactly the double of my 67155 estimate.

What I am missing here? Do we generate embeddings twice in llama_index, or is my estimate way off?

I tried looking into llm_predictor.last_token_usage but it doesn't make sense.

Any tips greatly appreciated :)

**Comment by Disiok** [comment]
Great question, that seems off. Will dig into this to understand what's going on soon.

**Comment by manuel-84** [comment]
i have a problem  when building a GPTVectorIndex using a custom LLMPredictor(llm=ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')) seems there is no way to get the consumed tokens, so get_openai_callback.total_tokens and index.service_context.llm_predictor.total_tokens_used are always 0

**Comment by sousanunes** [comment]
+1

I was recently trying the MockPredictor and the MockEmbedding for cost analysis (like [here](https://gpt-index.readthedocs.io/en/latest/how_to/analysis/cost_analysis.html)) and I always get 0 tokens as the output of llm_predictor.last_token_usage.

**Comment by logan-markewich** [comment]
Does this same issue occur using the new token counting callback?

https://gpt-index.readthedocs.io/en/latest/examples/callbacks/TokenCountingHandler.html

Feel free to re-open if its still an issue @sousanunes
