### ISSUE TITLE
 Texts with different data volumes are used as index json, and the response output obtained by using index.query will be interrupted within 200 characters

### ISSUE THREAD

**Issue by CCSsunman** [jerryjliu/llama_index#623]
I am working on a professional technical text tool. When I use text with different data volumes to index JSON, the response obtained by using index.query will be interrupted. It can only display about 200 characters at most. Is the token output limited? , I checked the documentation and didn’t find where this optimization can be done, does anyone know?
![524](https://user-images.githubusercontent.com/108789995/223079307-6838f71f-c256-41a0-9605-0d98fdc6f891.png)

**Comment by jerryjliu** [comment]
https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html should help

**Comment by CCSsunman** [comment]
Thank you for your reply. I did read Defining LLMs and found that：
It seems that when index.json is loaded using classmethod load_from_disk, the set max_tokens goes back to the default 256. 
So when I don't save to disk, I directly use 
"
index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper
    )
"
 modifying max tokens in llm_predictor and prompt_helper is effective, 
If I use save_to _disk,
"
index.save_to_disk('index.json')
"
then loading from disk,
"
 index = GPTSimpleVectorIndex.load_from_disk('index.json'), 
"
It will be limited to the default output of 256tokens

Is it because I have a mistake with saving to disk 
or do I need to use other parameters when load_from_disk,

 thank you for your help

**Comment by CCSsunman** [comment]
Thank you for your reply, it has been resolved
The problem comes from the fact that when loading the index.json generated by save to disk, using loan from disk will use the default output limit of 256 tokens

**Comment by logan-markewich** [comment]
When loading from disk/storage, you'll need to pass in the service context again. The latest documentation is here:
https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-save-the-index-for-future-use

Going to close this issue for now!
