### ISSUE TITLE
[Question]:  How I save to disk an index?

### ISSUE THREAD

**Issue by Dave86ch** [jerryjliu/llama_index#6271]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I used to use GPTTreeIndex.save_to_disk('/index.json') and GPTTreeIndex.load_from_disk('/index.json'), but they appear to be deprecated now. What is the updated alternative for saving an index to disk and loading it back? 

Thank you

**Comment by logan-markewich** [comment]
It's actually on the main tutorial in our docs, but here's the TLDR

```python
from llama_index import StorageContext, load_index_from_disk

index.storage_context.persist(persist_dir="./storage")

loaded_index = load_index_from_disk(StorageContext.from_defaults(persist_dir="./storage"))
```

Resources:
https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#optional-save-the-index-for-future-use
https://gpt-index.readthedocs.io/en/latest/how_to/storage/save_load.html
https://gpt-index.readthedocs.io/en/latest/how_to/storage/customization.html

**Comment by ryaker** [comment]
I’ve done this, I can see the files but load index from storage is telling me it sees no index store in the storage context and I’m not sure how to debug.

**Comment by logan-markewich** [comment]
Can you share your save/load code?

If you are using a vector store integration, the entire index is actually saved in the vector db. To "load" you just have to setup the vector store to point to the existing store and do `index = VectorStoreIndex.from_vector_store(vector_store)`

**Comment by ryaker** [comment]
I got it working changing it from

storage_context = StorageContext.from_defaults('Store')

to 

storage_context = StorageContext.from_defaults(persist_dir='Store')
