### ISSUE TITLE
[Question]: why fetch the nodes is return None by ResponseMode.NO_TEXT

### ISSUE THREAD

**Issue by youbai1995** [jerryjliu/llama_index#6278]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Why does llama return None when response_mode is no_text?
`       service_context = create_service_context()
        index = self.embedding.load_index_simple(game_id, service_context)
        retriever = index.as_retriever(similarity_top_k=15)
        engine = RetrieverQueryEngine.from_args(retriever, service_context,
                                                response_mode=ResponseMode.NO_TEXT)
`
i saw the nodes was print, but it not return

**Comment by logan-markewich** [comment]
the nodes are in the response object

```python
response = index.as_query_engine(response_mode="no_text").query("query")
print(response.source_nodes)
```

**Comment by youbai1995** [comment]
> thank you very much! the document need update ^.^
