### ISSUE TITLE
[Question]: Want to ask how to support the streaming of multi-document question

### ISSUE THREAD

**Issue by MonsterZwj** [jerryjliu/llama_index#6384]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to implement multi-document streaming answers, I use SubQuestionQueryEngine, I found a built-in parameter of this method response_synthesizer, set ResponseSynthesizer.from_args(streaming=True）It seems to work, but it still reports ValueError: LLM must support streaming and set streaming=True. I tried to use service_context to solve this problem, but it didn't work

**Comment by MonsterZwj** [comment]
I was happy to solve the problem myself

**Comment by dinhan92** [comment]
@MonsterZwj how do you solve it, I get that error too ?
