### ISSUE TITLE
My question is in Vietnamese, why is the answer in English? Is that because of gpt-3.5-turbo limited?

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#6386]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

![image](https://github.com/jerryjliu/llama_index/assets/86275789/a00aa50b-38ca-477b-9285-bf26b0d40b65)

I already set Vietnamese in the prepend messages:
max_input_size = 4096
num_outputs = 512
max_chunk_overlap = 0.2
chunk_size_limit = 1000

prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
prepend_messages = [
    SystemMessagePromptTemplate.from_template("You are a helpful assistant that use the same language as the input question and use Vietnamese as your base language")
]
llm_predictor = ChatGPTLLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo-0301", openai_api_key="API Key", streaming=True), prepend_messages = prepend_messages)

and use VectorStoreIndex:
 index = VectorStoreIndex.from_documents(documents, service_context=service_context)

This appears when I upgade to 0.6.20

**Comment by qypanzer** [comment]
chinese is similiar, the summary is English.
