### ISSUE TITLE
[Bug]: cannot import name 'SQLStructStoreIndex' from 'llama_index' 

### ISSUE THREAD

**Issue by GregXD** [jerryjliu/llama_index#6404]
### Bug Description
I'm getting this error when trying to build an index on top of structured data (sqlite)

    from llama_index import SQLStructStoreIndex
    ImportError: cannot import name 'SQLStructStoreIndex' from 'llama_index' 

I'm using the latest version of Llama-Index. Trying to build an index on top of structured data. The other Llama imports are working fine.

Is this method deprecated? I'm following these docs: https://gpt-index.readthedocs.io/en/latest/examples/index_structs/struct_indices/SQLIndexDemo-Context.html#build-index-with-context

### Version

0.6.22

### Steps to Reproduce

from llama_index import SQLStructStoreIndex

### Relevant Logs/Tracbacks

```shell
Cell In[26], line 1
----> 1 from llama_index import SQLStructStoreIndex

ImportError: cannot import name 'SQLStructStoreIndex' from 'llama_index'
```

**Comment by logan-markewich** [comment]
Are you using venv? Maybe re-install from a fresh environment

The import works for me locally, and is in the codebase here: https://github.com/jerryjliu/llama_index/blob/383725d873ff1d9e40858010b2216d8cc8ba6455/llama_index/__init__.py#L151

**Comment by logan-markewich** [comment]
Going to close this for now. The SQL index is technically deprecated anyways, in favour of the SQL query engine

https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/structured_data/sql_guide.html
