### ISSUE TITLE
[Bug]:  cannot import name 'Protocol' from 'typing'

### ISSUE THREAD

**Issue by lacls** [jerryjliu/llama_index#6407]
### Bug Description

After installing by the follwing command: "pip install llama-index" 

I got an error of cannot import name 'Protocol' from 'typing'

<img width="769" alt="Screen Shot 2023-06-10 at 22 44 35" src="https://github.com/jerryjliu/llama_index/assets/42736388/214820a2-ec38-4ce6-ba09-5a8950830e9d">

Many thanks for your reading and support.

### Version

0.5.9

### Steps to Reproduce

Error after running an install command

**Comment by logan-markewich** [comment]
Python3.7 is not supported. Can you try updating to a new version? (conda is really good for this, but up to you on how to upgrade)

**Comment by lacls** [comment]
Many thanks for your reply. I updated my Python to 3.11.0 and it works well. Have a nice day.
