### ISSUE TITLE
[Bug]: API key not assigned even if the key environment variable is set!!

### ISSUE THREAD

**Issue by nick26** [jerryjliu/llama_index#6414]
### Bug Description

Running on google colab:
Authentication Error

I have set openai_api_key in environment variable as well as tried to pass it in the call but I still get this error.
Do not understand what I am doing wrong, all of my programs are failing at this point

### Version

lastest

### Steps to Reproduce

import os
os.environ ["OPENAI_API_KEY"]='a valid key'
os.environ.get('OPENAI_API_KEY')

from llama_index import GPTVectorStoreIndex, StorageContext, ServiceContext
from llama_index.embeddings.openai import OpenAIEmbedding

# setup our storage (vector db)
storage_context = StorageContext.from_defaults(
    vector_store=vector_store
)
# setup the index/query process, ie the embedding model (and completion if used)
embed_model = OpenAIEmbedding(model='text-embedding-ada-002', embed_batch_size=100)
service_context = ServiceContext.from_defaults(embed_model=embed_model)

# fails at this point
index = GPTVectorStoreIndex.from_documents(
    docs, storage_context=storage_context,
    service_context=service_context
)

### Relevant Logs/Tracbacks

```shell
AuthenticationError                       Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    381                 try:
--> 382                     result = fn(*args, **kwargs)
    383                 except BaseException:  # noqa: B902

19 frames
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

The above exception was the direct cause of the following exception:

RetryError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in iter(self, retry_state)
    324             if self.reraise:
    325                 raise retry_exc.reraise()
--> 326             raise retry_exc from fut.exception()
    327 
    328         if self.wait:
```

**Comment by Disiok** [comment]
Hmm, that's strange. Did you try `openai.api_key = <API-KEY>` as well?
