### ISSUE TITLE
[Question]: Can you create an index with one LLM and query using another

### ISSUE THREAD

**Issue by Samshive** [jerryjliu/llama_index#6445]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi 

Great tool btw, I was wondering if it is possible to create an index with one LLM and query using another. I'm specifically trying to reduce the cost for index creation by using a cheaper model for index creation, but I want the power of the more capable LLMs when responding to queries. 

Your assistance is much appreciated. 

Kind regards

**Comment by matthiaskern** [comment]
This is supported! You can specify different `service_context` instances for the different stages:

e.g.:

```
index = VectorStoreIndex.from_documents(docs, service_context=service_context_cheap)
query_engine = index.as_query_engine(service_context=service_context_expensive)
```

**Comment by Samshive** [comment]
Thanks, much appreciated.
