### ISSUE TITLE
[Feature Request]: Return native LLM output if context is not found.

### ISSUE THREAD

**Issue by reinershir** [jerryjliu/llama_index#6449]
### Feature Description

For example, if I want to implement an AI customer service, I hope that when the customer asks a question that does not exist in the document, it will directly return the native answer of GPT-3.5.

### Reason

This is a very common use case

### Value of Feature

This can achieve AI customer service with faster response speed

**Comment by logan-markewich** [comment]
You'll want to use a data agent for this

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
