### ISSUE TITLE
[Feature Request]: Make the AI to generate the answer contacting with a specific person

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#6450]
### Feature Description

As the question, I seem to not be able to find out how to do make the AI to generate the answer that provide a way to contact with a person in case the AI can not answer the question.

### Reason

I think this make the chatbot better, because there are specific questions that the AI can not answer, only a user can answer

### Value of Feature

This can make the chatbot more comfortable with the user

**Comment by logan-markewich** [comment]
You'll want to use a data agent for this I think: 
https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
