### ISSUE TITLE
[Bug]: Index Fetched from local storage always returns NONE 

### ISSUE THREAD

**Issue by khushburajani** [jerryjliu/llama_index#6451]
### Bug Description

Fetching of node from documents storage works fine. Currently I have stored index in MongoDb Atlas. Initially when index is created query engine works fine by searching relevant node. On second time when index is passed externally or loaded from storage response returned is always NONE. Can you please help out where this is going wrong ?

### Version

0.6.23

### Steps to Reproduce

uri = "mongodb://user:passwrd@cluster0-shard-00.mongodb.net" //example string

index_store = MongoIndexStore.from_uri(uri)

storage_context = StorageContext.from_defaults(
    docstore=MongoDocumentStore.from_uri(uri=uri),
    index_store=index_store)
    
index = load_index_from_storage(storage_context,index_id='55712fe8-82db-7a21-52a9-c1373f6bff1a')
    or if one index 
index = load_index_from_storage(storage_context')

vector_retriever = VectorIndexRetriever(index=index, similarity_top_k=1)

# define response synthesizer
response_synthesizer = ResponseSynthesizer.from_args(
    node_postprocessors=[
        SimilarityPostprocessor(similarity_cutoff=0.7)
    ]
)

# vector query engine
vector_query_engine = RetrieverQueryEngine.from_args(
    retriever=vector_retriever,
    
    # response_mode='compact',
    response_synthesizer=response_synthesizer,
)

response = vector_query_engine.query("What is vector?")

print(response.source_nodes)

print(response)

    

### Relevant Logs/Tracbacks

```shell
// logs of Index Struct
IndexDict(index_id='f62222fe8-82db-4a21-92a9-czzzzzz', summary=None, nodes_dict={'1111444-1ce2-48a5-84b0-2ec8a596262e': 'a6fdd863-1ce2-48a5-84b0-2ec8a66662e'}, doc_id_dict={}, embeddings_dict={})

 // Logs of nodes
[]
//Response 
None
```

**Comment by logan-markewich** [comment]
You are creating a MongoDocumentStore, but setting it as an index store 🤔 

For a vector db, I recommend using monad atlas: 
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/MongoDBAtlasVectorSearch.html

You'll need to setup the db a little manually sadly. See either the langchain instructions or this thread from discord
https://discord.com/channels/1059199217496772688/1122793802214670336/1122904691416772780

https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/mongodb_atlas
