### ISSUE TITLE
[Bug]: Issue while accessing GPTVectorStoreIndex.from_documents(documents)

### ISSUE THREAD

**Issue by bala-ceg** [jerryjliu/llama_index#6453]
### Bug Description

https://colab.research.google.com/drive/11UD_FvE-uUl26dhEiAjrXyj0HK73utAQ#scrollTo=YNRPpcI181gk&line=1&uniqifier=1

I believe Database Reader will have also issues

### Version

 0.6.25.post1

### Steps to Reproduce

https://colab.research.google.com/drive/11UD_FvE-uUl26dhEiAjrXyj0HK73utAQ?usp=sharing

**Comment by logan-markewich** [comment]
```
[Document(text=Pandas(Index=0, Paragraph1='MindsDB i.....
```

The document text needs to be a string, not a pandas object

`Document('document text string')`

**Comment by manny-uncharted** [comment]
I also experienced the same issue yesterday with using a .txt document and .pdf document

**Comment by bala-ceg** [comment]
Thanks @logan-markewich for clarifying, i am closing this issue
