### ISSUE TITLE
[Bug]: Issue with importing CitationQueryEngine

### ISSUE THREAD

**Issue by Sourasky-DHLAB** [jerryjliu/llama_index#6454]
### Bug Description

When importing the following:
from llama_index.query_engine import CitationQueryEngine
The following error is received:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3553 in run_code        │
│                                                                                                  │
│   3550 │   │   │   │   elif async_ :                                                             │
│   3551 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3552 │   │   │   │   else:                                                                     │
│ ❱ 3553 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3554 │   │   │   finally:                                                                      │
│   3555 │   │   │   │   # Reset our crash handler in place                                        │
│   3556 │   │   │   │   sys.excepthook = old_excepthook                                           │
│ in <cell line: 4>:4                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'CitationQueryEngine' from 'llama_index.query_engine' 
(/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/__init__.py)

### Version

0.6.25.post1

### Steps to Reproduce

!pip install llama_index
from llama_index import query_engine
from llama_index.query_engine import CitationQueryEngine

### Relevant Logs/Tracbacks

```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3553 in run_code        │
│                                                                                                  │
│   3550 │   │   │   │   elif async_ :                                                             │
│   3551 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3552 │   │   │   │   else:                                                                     │
│ ❱ 3553 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3554 │   │   │   finally:                                                                      │
│   3555 │   │   │   │   # Reset our crash handler in place                                        │
│   3556 │   │   │   │   sys.excepthook = old_excepthook                                           │
│ in <cell line: 3>:3                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'CitationQueryEngine' from 'llama_index.query_engine' 
(/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/__init__.py)
```

**Comment by logan-markewich** [comment]
@Sourasky-DHLAB apologies, something happened to the __init__.py file. I can fix this shortly. For now though, you can import directly from the file

`from llama_index.query_engine.citation_query_engine import CitationQueryEngine`
