### ISSUE TITLE
[Bug]: OpenAPI Key doesn't work as environment variable anymore?

### ISSUE THREAD

**Issue by jexp** [jerryjliu/llama_index#6458]
### Bug Description

Not sure if that's an openai or LlamaIndex integration issue.

Previously one could provide the openai key as `OPENAI_API_KEY` but since a week ago my notebook stopped working like that, and raises this error:

```
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

The above exception was the direct cause of the following exception:
```

I had to work around the issue with:

```
import openai

load_dotenv("openai.env")
openai.api_key=os.getenv('OPENAI_API_KEY')
```

But that's not ideal.

### Version

0.6.19

### Steps to Reproduce

Colab notebook: https://colab.research.google.com/drive/1NUrIoiOh692LaQkBHEmnD-5IuLBpBqGJ#scrollTo=ysVg3VDrUy2Z

### Relevant Logs/Tracbacks

```shell
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

**Comment by jexp** [comment]
Yeah seems not to happen locally, oddly it worked before in colab.

**Comment by Hikari-Haru** [comment]
I have the same issue, but I've found out it's langchain that's the issue. Version 0.0.192 and upwards doesn't work

**Comment by juangon** [comment]
> I have the same issue, but I've found out it's langchain that's the issue. Version 0.0.192 and upwards doesn't work

Thanks! In my case when downgrading to 0.0.191 other issue arises:

```Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>```

**Comment by Disiok** [comment]
Think this is a langchain issue, which hopefully should be resolved now, also we are rolling our own Openai/AzureOpenAI integration.
