### ISSUE TITLE
  组建LlamaIndex中文学习小组 完善中文语料库  Discussion on Chinese corpus solutions, discussing LlamaIndex and llm together

### ISSUE THREAD

**Issue by stayhungry148** [jerryjliu/llama_index#646]
LlamaIndex is a very good project, and it can be used for professional chat in many subdivided knowledge bases. It is worth investing in research. We also found that the current
There are some imperfections in the processing of LlamaIndex on the Chinese corpus. If you want to form a discussion group to learn and improve together, you can also have more ideas. I hope more people will join. If you are interested, please contact wechat linmumu948, remark llm That's it, welcome. 
Thanks jerryjliu for Creation of this project and continued dedication

我们是一个对aigc十分关注的团队，认为LlamaIndex是个很好的项目，可以在很多细分知识库做专业性chat 很值得投入去研究。同时我们也发现目前LlamaIndex 在中文文本上处理存在一些不完善的地方，想要组建一个讨论小组共同学习和完善，也可以有更多想法的碰撞，希望有更多人加入 如果有兴趣，欢迎联系微信 linmumu948，备注 llm即可，欢迎。
感谢jerryjliu创建这个项目和持续的奉献

**Comment by jerryjliu** [comment]
Hey @stayhungry148, thanks for the heads up. Do you want to start a private group chat on the discord? https://discord.gg/dGcwcsnxhU

**Comment by wesleysanjose** [comment]
this is a great project, I am also interested

**Comment by logan-markewich** [comment]
Going to close this issue for now, as there appears to be no action items left!

**Comment by mru4913** [comment]
Can I join this group?

**Comment by mru4913** [comment]
Could I join in this group?
