### ISSUE TITLE
[Bug]: `aquery()` does not work asynchronously 

### ISSUE THREAD

**Issue by jjmachan** [jerryjliu/llama_index#6463]
### Bug Description

I want to call `aquery()` to get async responses but that is not happening. I've spent some debugging it and mentioned the issue below.

### Version

0.6.24

### Steps to Reproduce

```python
index = GPTVectorStoreIndex.from_documents(documents=docs, use_async=True)
qe = index.as_query_engine()
qe.async_query(question)
```

This will only run sync. This is because all the `ResponseBuilder` objects redirect the `aget_response()` as so
```python
    @llm_token_counter("aget_response")
    async def aget_response(
        self,
        query_str: str,
        text_chunks: Sequence[str],
        prev_response: Optional[str] = None,
        **response_kwargs: Any,
    ) -> RESPONSE_TEXT_TYPE:
        return self.get_response(query_str, text_chunks, prev_response)
```
filepath: llama_index/indices/response/refine.py

**Comment by logan-markewich** [comment]
@jjmachan definitely make a PR, would be greatly appreciated! 🙏🏻

**Comment by jjmachan** [comment]
after a bit more bit more digging I realized that I was wrong. The bottle neck currently is the embedding endpoint in the for retriever 
![image](https://github.com/jerryjliu/llama_index/assets/5261489/2c790fb3-1802-4a71-b005-95e7957e61cd)

the `get_agg_embedding_from_queries()` does not have an async counterpart and that network call is blocking the async query request.

given that the retriever is also an expensive part (mainly the embedding call but I'm not sure what other types of retrievers are present) adding an async version of `_retrieve` is one possiblitily

![image](https://github.com/jerryjliu/llama_index/assets/5261489/eb8d643f-2bcb-4f15-bc53-a1777c2060e2)

@logan-markewich @Disiok let me know what you guys think and I'll finish up the draft. Personally I'm going to prototype a `async retrieve()` call and experiment how its going to look like

looking forward to your feedbacks 🙂

**Comment by jjmachan** [comment]
closing this in favour of https://github.com/jerryjliu/llama_index/issues/6591
