### ISSUE TITLE
[Question]: 【Discussion】Multiple sources of information retrieval and inquiry for a question

### ISSUE THREAD

**Issue by mintisan** [jerryjliu/llama_index#6464]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

For a problem, it may involve [code/log/documentation] multiple information sources.

 I tried putting all of them in a string-splitter-embedding-retrieval, but the result is not good.

So I think that the code/log/documentation creates an index_code/index_log/index_doc respectively, and then each index has top_k_3, so that we have three sources of information with nine nodes for the same problem, 

but **how do we use these three index/nine nodes in LlamaIndex. The information sources are packaged together through the prompt and sent to ChatGPT.**

Maybe I need a prompt template just like below:

```
"""
User has a question : {query_str}.

He has relative {context_str_doc-1-2-3} description.

And relative codes {context_str_code-1-2-3} with logs {context_str_log-1-2-3} print out.

Give the reason with above information.

"""
```

I read the relevant information in the document/links, but it seems that it can't solve my problem. 

So, I'm here to ask for thoughts.

Related reference links:

- https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#routing-over-heterogeneous-data
- https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#synthesis-over-heterogeneous-data
- https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#multi-document-queries
- https://gpt-index.readthedocs.io/en/latest/examples/query_engine/RouterQueryEngine.html#define-query-engines-and-set-metadata

**Comment by logan-markewich** [comment]
You can combine these three indexes using a graph index (likely with a list or vector index on top of the three sub-indexes).
https://gpt-index.readthedocs.io/en/latest/how_to/index/composability.html

In the future, the router query engine will support multiple sources as well!

**Comment by mintisan** [comment]
@logan-markewich Thanks for your advice.

I'll go to see how to implement it...

XD

**Comment by logan-markewich** [comment]
I would also recommend a data agent for this task. Good luck! Feel free to reach out on discord

https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
