### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by noke8868** [jerryjliu/llama_index#6498]
### Bug Description

Hi 
i have around 8000 small json files under a folder(most of them are under 10k size)
i scan them and load into documents which is very fast.
i try to generate index from them . however it stuck here for over 17 hours.
no error, you may see picture below
**index = GPTListIndex.from_documents(documents, service_context=service_context)**
is it a bug?
thank you

<img width="946" alt="index_Capture" src="https://github.com/jerryjliu/llama_index/assets/15937904/d2e0ef5b-05c2-4063-93ef-05678192a26b">

### Version

latest

### Steps to Reproduce

source code are here:

file_list = []
JsonDataReader = download_loader("JSONReader")
loader = JsonDataReader()
documents = []
#mylist=['13208035.txt']
for root, dirs, files in os.walk(folder_path):
    for file in files:
      #if file not in mylist:
      #  continue
      file_path = os.path.join(root, file)
      file_list.append(file)
      docs = loader.load_data(file_path)
      documents.extend(docs)
print(len(file_list))

prompt_helper = PromptHelper(
            num_output=PROMPT_NUM_OUTPUTS,
            chunk_overlap_ratio=0.1
        )

llm_predictor = LLMPredictor(
    llm = ChatOpenAI(temperature = OPENAI_MODEL_temperature,
                      model_name = OPENAI_MODEL_name,
                      max_tokens = PROMPT_NUM_OUTPUTS)
    )

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
**index = GPTListIndex.from_documents(documents, service_context=service_context)**
index_file='bot_index.json'
index.save_to_disk(index_file)
print('done save_to_disk')

**Comment by logan-markewich** [comment]
I would try running locally if possible. OpenAI heavily rate limits from google colab

You can also increase the embedding batch size (default is 10)

```
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index import ServiceContext

embed_model = OpenAIEmbedding(embed_batch_size=50)
serivce_context =ServiceContext.from_defaults(embed_model=embed_model)
```

**Comment by Disiok** [comment]
Closing since it's quite old.
