### ISSUE TITLE
[Question]: I am trying to create stream with agent: create_llama_chat_agent but with no luck, is it not supported yet?

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#6506]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Here is my code, I want to streaming with agent, but not find a way, even when I print, it is not a stream but a string:

              query_engine = index.as_query_engine(
                      streaming=True,
                  )
              
                   # define toolkit
                  index_configs = []
                  tool_config = IndexToolConfig(
                      query_engine=query_engine, 
                      name=f"Vector Index",
                      description=f"useful for when you want to answer queries about the Report of Economy in England",
                      tool_kwargs={"return_direct": True}
                  )
                  index_configs.append(tool_config)
              
                  toolkit = LlamaToolkit(
                      index_configs=index_configs,
                  )
              
                  memory = ConversationBufferMemory(memory_key="chat_history")
                  llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo-0301", openai_api_key="open_ai_key", streaming=True,
                      callbacks=[FinalStreamingStdOutCallbackHandler()]
                  )
                  
                  agent_chain = create_llama_chat_agent(
                      toolkit,
                      llm,
                      memory=memory,
                      verbose=False
                  )
              
                  print(agent_chain.run(input=input_text))
              
                  return agent_chain.run(input=input_text)

**Comment by logan-markewich** [comment]
Just merged a PR with support today! Will be in the next release or you can install from source :) https://github.com/jerryjliu/llama_index/pull/6524

**Comment by logan-markewich** [comment]
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/customization/streaming/chat_engine_condense_question_stream_response.ipynb

**Comment by dinhan92** [comment]
@logan-markewich hey bro, when streaming=True in as_chat_engine is released, is response_gen for as_chat_engine work as it work for as_query_engine?

**Comment by logan-markewich** [comment]
@dinhan92 yea it'll be the same. There's an example notebook too btw 
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/customization/streaming/chat_engine_condense_question_stream_response.ipynb

**Comment by dinhan92** [comment]
@logan-markewich when will the next release become public? I ve tested and find out that this is what I need ^^ I can not wait ^^

**Comment by dinhan92** [comment]
@logan-markewich Can I use as_chat_engine with SubQuestionQueryEngine like as_query_engine?

**Comment by logan-markewich** [comment]
@dinhan92 you can, if you create the chat engine from the base constructor  using from_defaults

https://github.com/jerryjliu/llama_index/blob/66a15080f4334599317331bacd1184f73f692d7e/llama_index/chat_engine/condense_question.py#L53

**Comment by dinhan92** [comment]
@logan-markewich I had a look at CondenseQuestionChatEngine. However, my case is, I want data come from 2 sources, one is pdf, one is Mongo. So if I use as_query_engine, I can use SubQuestionQueryEngine to query those data. 

However, now I want to use chat engine. CondenseQuestionChatEngine seems to only accept one query_engine, and it does not have streaming, ...

**Comment by dinhan92** [comment]
@logan-markewich thank you, so I make CondenseQuestionChatEngine work with SubQuestionQueryEngine. However, it seems I 2 two sources, so it generate 2 sub questions. However it takes lots of time to generate answer for those 2 sub questions. How to reduce time for that, or can I make it generate only one question respectively?
