### ISSUE TITLE
[Bug]: The `_get_llm_metadata` function reports an error: "Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter." (type=value_error)

### ISSUE THREAD

**Issue by zhugexinxin** [jerryjliu/llama_index#6513]
### Bug Description

The `_get_llm_metadata` function reports an error: "Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter." (type=value_error)

I've passed the `openai_api_key` parameter, but it doesn't seem to be getting through to the `_get_llm_metadata` function within the `context_window=OpenAI().modelname_to_contextsize(llm.model_name)` line.

I believe this is not reasonable. It should support the parameters corresponding to the `ChatOpenAI` generation.

### Version

llama-index==0.6.27

### Steps to Reproduce

llm=ChatOpenAI(
    openai_api_base='https://xxxxx,
    openai_api_key='sk-xxxxx',
    temperature=0,
    model_name="gpt-3.5-turbo"
)
llm_predictor = LLMPredictor(llm=llm)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 141, in from_defaults
    llm_metadata=llm_predictor.get_llm_metadata(),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/llm_predictor/base.py", line 177, in get_llm_metadata
    return _get_llm_metadata(self._llm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/llm_predictor/base.py", line 53, in _get_llm_metadata
    context_window=OpenAI().modelname_to_contextsize(llm.model_name),
                   ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/load/serializable.py", line 61, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
>>>
```
```

**Comment by logan-markewich** [comment]
A PR recently removed that fixes this, by getting the context window another way

https://github.com/jerryjliu/llama_index/pull/6490
