### ISSUE TITLE
[Bug]: StreamingResponse already iterated over before returning in CondenseQuestionChatEngine

### ISSUE THREAD

**Issue by stadeltobi** [jerryjliu/llama_index#6514]
### Bug Description

While I can get my LLM (ChatOpenAI, in my case) to return streaming responses with

```
engine = index.as_chat_engine(streaming=True, chat_mode=ChatMode.CONDENSE_QUESTION)
```
it turns out that on a call to `engine.chat('...')`, the StreamingResponse object is already iterated over, so there's no chance to provide streaming user experience in the frontend.

After some debugging, I found that this probably happens in https://github.com/jerryjliu/llama_index/blob/0f4b057bcdd1a3e67812a55a75ce4d156c236e22/llama_index/chat_engine/condense_question.py#L122

... where the str(response) part is the problematic one, since it will already iterate over the  response_gen object, probably. 

### Version

0.6.28

### Steps to Reproduce

see above. any call to `engine.chat()` will return a StreamingResponse object where in this example

```
for text in response.response_gen:
  do_something()
```

the do_something() method will never be called

**Comment by logan-markewich** [comment]
Yea the chat engine does not support streaming yet, but it is on our todo list! A recent PR was opened actually by a community member, but it's not quite ready yet
https://github.com/jerryjliu/llama_index/pull/6524

**Comment by logan-markewich** [comment]
Just merged the PR!

**Comment by HollowMan6** [comment]
Cool! I actually didn't notice that there was an issue for it.

**Comment by stadeltobi** [comment]
Nice, thanks! Feel free to ping me if you need assistance testing or similar.
