### ISSUE TITLE
[Feature Request]: text extraction from diagrams/graphs

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6516]
### Feature Description

Examples: 
1. https://huggingface.co/google/deplot (only tabular data)
2. https://huggingface.co/google/pix2struct-infographics-vqa-base
   
Larger workflow: Text extraction pipeline for non-textual documents e.g. 
1. image using ViT (blip/blip2): https://llama-hub-ui.vercel.app/l/file-image_blip2

Does this feature belong to [llama hub](https://llama-hub-ui.vercel.app/) instead of llama_index? 

Next levels - how can we integrate this into a PDF document extraction / website extraction workflow? (text + img)

### Caveat
1. Before further work, let's test out if Blip2 can handle technical diagrams or graphs (my guess is no)
2. This work will not cover direct VQA. In the direct VQA pipeline, there may need to exist a refactor or separate layer to handle various types of mixed-media retrieval. From a feasibility standpoint, existing text captions and autocaptioning of diagrams/graphs can serve as the text-based retrieval embedding for mixed media. The retrieved media can then be fed into the downstream VQA/multi-modal LLM pipeline. It is an open question whether descriptive or tabular data extraction from diagrams/graphs/natural images is sufficient or whether direct VQA is necessary for good performance on task. I believe this depends on the use-case.

### Value of Feature

Increase the amount of information extracted from mixed-media documents.

I think they (and Blip2 models) should be part of the PDF/website workflows with automatic dispatch, preprocessing and model selection/ensembling layer, but some coordination and maintenance on the best performing models would be valuable. 

Some filtering layer to filter out low-quality outputs from the vision models could be helpful as well.

**Comment by Disiok** [comment]
good points all around. Some quick responses to your questions:
* RE where to put this: probably fits better in llama_hub right now. Would be amazing if you want to make a contribution there.
* RE how to integrate into PDF/website extraction: this takes some refactoring right now, current workflow is parse PDF/website in to plain text documents, then parse documents into Nodes. We are moving towards keeping more raw information, and then parsing document into multi-media Nodes (e.g. image node, table node, etc)
* RE beyond text based retrieval: we are moving towards supporting joint image/text embeddings (e.g. Google Palm API) to do native cross-modal retrieval. 
* RE value of feature: 100% agreed. If you are interested in help making this happen, let's chat more!

**Comment by jon-chuang** [comment]
Actually, I think what I did was not very useful.

In the typical use-case, an image caption is equivalent to the image content. In the graph case, the description of the graph is what we want for the embedding, but the content should be the graph data.

**Comment by jon-chuang** [comment]
Another interesting direction is extraction from diagrams graphs -> inserting into SQL database.

We may expect varied results here, especially since the source attribution is lost. Not my favourite pathway but combining the SQL database with original sources seems decent solution for some kinds of queries.

**Comment by jon-chuang** [comment]
Definitely believe that to effectively make use of the charts/diagrams, the [multi-step query engine](https://gpt-index.readthedocs.io/en/latest/examples/query_transformations/SimpleIndexDemo-multistep.html) would be key.
