### ISSUE TITLE
[Documentation]: OpenAI Agent + Query Engine Experimental Cookbook - "index" variable not declared

### ISSUE THREAD

**Issue by tuitejc** [jerryjliu/llama_index#6519]
### Documentation Issue Description

In the OpenAI Agent + Query Engine Experimental Cookbook documentation, when defining the Function Tool, the variable for index is used but never defined in the example:
retriever = VectorIndexRetriever(
        index,
        filters=MetadataFilters(filters=exact_match_filters),
        top_k=top_k
    )

Is this supposed to be the index we created in the previous step?  I tried to use that but it did not work.  Not sure how to define index.

### Documenation Link

https://github.com/jerryjliu/llama_index/blob/main/docs/examples/agent/openai_agent_query_cookbook.ipynb

**Comment by logan-markewich** [comment]
The index is defined in cell 8

![image](https://github.com/jerryjliu/llama_index/assets/22285038/b4e90a56-2111-4e42-ab20-ff7baa4941cc)

it should be working as a global variable no?

**Comment by tuitejc** [comment]
oh wow i must have missed that one line somehow, my bad!

**Comment by tuitejc** [comment]
I figured it out.  I was splitting up the sections into 3 files and didn't carry over this variable.  Easy fix. Thanks again, this library is super cool!

**Comment by logan-markewich** [comment]
Thanks! I hope you build something awesome with it! 💪
