### ISSUE TITLE
[Question]: How to use the DEFAULT_SCHEMA_EXTRACT_PROMPT ?

### ISSUE THREAD

**Issue by derekgray23** [jerryjliu/llama_index#6521]
### Question Validation

- [ ] I have searched both the documentation and discord for an answer.

### Question

I have read the [custom prompt doc](https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html): ,  and searched all examples ,  but failed to figure out how to use the DEFAULT_SCHEMA_EXTRACT_PROMPT ,  how to pass the prompt template parameters ({text} and {schema}) value to llama-index?  is it possible for a large text?

**Comment by logan-markewich** [comment]
@derekgray23 Those variables get filled in automatically by llama index, so you have to leave them as variables in the prompt template

**Comment by derekgray23** [comment]
> @derekgray23 Those variables get filled in automatically by llama index, so you have to leave them as variables in the prompt template

@logan-markewich thanks for your reply.  I have a customized JSON schema, how to let llama-index know this customized schema?

**Comment by logan-markewich** [comment]
@derekgray23 so you are using the json query engine here? Or what is the use case you are attempting?

If you are using the json query engine, you just have to create the json schema in a file and pass it into the engine :)

https://gpt-index.readthedocs.io/en/latest/examples/query_engine/json_query_engine.html#let-s-start-on-a-toy-json

**Comment by derekgray23** [comment]
@logan-markewich the use case is to extract specified fields from unstructured text (non-performing loan asset description in fact),  hope the query engine could respond in JSON format.

**Comment by logan-markewich** [comment]
@derekgray23 ah I see, that makes sense

Tbh, you might be better off using the openai pydantic program https://github.com/jerryjliu/llama_index/blob/main/docs/examples/output_parsing/openai_pydantic_program.ipynb

Define an output object with the fields you want to collect, and then send the program off to do it's job on each chunk of text. Pydantic makes it really easy to convert objects to JSON, and the new OpenAI function call API makes it easy to generate pydantic objects

```python
from pydantic import BaseModel

class ThingToExtract(BaseModel):
    """This object defines ThingToExtract, which is used as an example."""
    field_to_extract: str

class ThingsExtracted(BaseModel):
    """This object represents a collection of extracted things."""
    things: List[ThingToExtract]

# NOTE: this may take some prompt engineering to get OpenAI LLM to call our output_cls
prompt_template_str = "Generate a list of things to extract from the follow text: {text}\n"

program = OpenAIPydanticProgram.from_defaults(
    output_cls=ThingsExtracted, 
    prompt_template_str=prompt_template_str,
    verbose=True,
)

extracted_things = program(text="my text to extract from, should be about 1000-2000 tokens long")
```

Tbh we should probably bake this process into our code soon so it's easier to do :)

**Comment by derekgray23** [comment]
@logan-markewich thanks for your great help, I will give it a try.

**Comment by derekgray23** [comment]
@logan-markewich thanks for your great help, I will give it a try.
