### ISSUE TITLE
[Question]: I have customized the prompt in Chinese, but the answer is still in English. who knows？

### ISSUE THREAD

**Issue by dongxu** [jerryjliu/llama_index#6523]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have customized the prompt in Chinese, but the answer is still in English. who knows？

**Comment by logan-markewich** [comment]
Which prompts did you customize? Can you show me?

**Comment by dongxu** [comment]
> Which prompts did you customize? Can you show me?

below content is my code.
self.index = GPTVectorStoreIndex.from_documents(documents, 
                                                        service_context=self.service_context)
TEACH_QA_PROMPT_TMPL = (
            "我想你担任公司的产品售前工程师，我会在下面提供公司产品相关的信息. \n"
            "---------------------\n"
            "{context_str}"
            "\n---------------------\n"
            "根据上面的产品信息, 请回答这个问题: {query_str}\n"
        )
QA_PROMPT = Prompt(TEACH_QA_PROMPT_TMPL)
# Configure query engine
query_engine = self.index.as_query_engine(text_qa_template=QA_PROMPT)
response = query_engine.query(question)

**Comment by logan-markewich** [comment]
You'll also want to customize the refine template as well actually

`query_engine = self.index.as_query_engine(text_qa_template=QA_PROMPT, refine_template=REFINE_PROMPT)`

Here is the default refine template:
https://github.com/jerryjliu/llama_index/blob/d9b62c46fa42f48d249d5238412bc32599b6efea/llama_index/prompts/default_prompts.py#L81

And here is the default refine template if you use gpt-3.5 or gpt-4
https://github.com/jerryjliu/llama_index/blob/d9b62c46fa42f48d249d5238412bc32599b6efea/llama_index/prompts/chat_prompts.py#L12

**Comment by dongxu** [comment]
Thanks. I try it.
