### ISSUE TITLE
PyPDF2 Error : Cannot read an empty file

### ISSUE THREAD

**Issue by areeb1245** [jerryjliu/llama_index#653]
I got it to work perfectly. But since last night, I am getting this error that I am unable to figure out why.

PyPDF2.errors.EmptyFileError: Cannot read an empty file.

But the file clearly has data in it. It suddenly stopped working for some reason.

**Comment by jerryjliu** [comment]
@areeb1245 could it be due to a version of pypdf2? (e.g. could you try downgrading a version?) let me know if you do, i'm happy to pin the version in our pdfreader

**Comment by Disiok** [comment]
Hey @areeb1245  are you still experiencing this issue? If not, could you close the ticket?

**Comment by logan-markewich** [comment]
We current;y do not use pypdf2 anymore. Closing this issue for now
