### ISSUE TITLE
[Question]: Ingest Unstructured Data Through the Unstructured.io Reader

### ISSUE THREAD

**Issue by achilela** [jerryjliu/llama_index#6541]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
I am trying to run the 10K-ChatBot using VSCode, however, each and everytime I run 
UnstructuredReader` = download_loader("UnstructuredReader", refresh_cache=True)
I got an error
JSONDecodeError: Extra data: line 1 column 4 (char 3)

Whereas running on Colab works charmingly without any issue. Is this related to some local dependencies? I am running the VSCode on Ubuntu 22.4 on Macbook Air.

**Comment by logan-markewich** [comment]
What's the full traceback/error?

**Comment by achilela** [comment]
There it goes as below:

---------------------------------------------------------------------------
JSONDecodeError Traceback (most recent call last) Cell In[3], line 1 ----> 1
UnstructuredReader = download_loader("JSONReader") # only run once per cell
File ~/llm/lib/python3.10/site-packages/llama_index/readers/download.py:133
<https://file+.vscode-resource.vscode-cdn.net/home/ataliba/LLM_Workshop/LlmaIndex/~/llm/lib/python3.10/site-packages/llama_index/readers/download.py:133>,
in download_loader(loader_class, loader_hub_url, refresh_cache,
use_gpt_index_import, custom_path) 131 if loader_id is None: 132
library_raw_content, _ = _get_file_content(loader_hub_url, "/library.json
<https://file+.vscode-resource.vscode-cdn.net/library.json>") --> 133
library = json.loads(library_raw_content) 134 if loader_class not in
library: 135 raise ValueError("Loader class name not found in library")
File /usr/lib/python3.10/json/__init__.py:346
<https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.10/json/__init__.py:346>,
in loads(s, cls, object_hook, parse_float, parse_int, parse_constant,
object_pairs_hook, **kw) 341 s = s.decode(detect_encoding(s), 'surrogatepass
') 343 if (cls is None and object_hook is None and 344 parse_int is None and
parse_float is None and 345 parse_constant is None and object_pairs_hook is
None and not kw): --> 346 return _default_decoder.decode(s) 347 if cls is
None: 348 cls = JSONDecoder File /usr/lib/python3.10/json/decoder.py:340
<https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.10/json/decoder.py:340>,
in JSONDecoder.decode(self, s, _w) 338 end = _w(s, end).end() 339 if end !=
len(s): --> 340 raise JSONDecodeError("Extra data", s, end) 341 return obj
JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by logan-markewich** [comment]
@achilela can you try updating your llama index version? There was some changes a few weeks ago 🤔

**Comment by achilela** [comment]
@logan-markewich it worked charmingly once I have updated to the new version of llama-index. Thanks indeed. I am really enjoying learning and practicing llama-index framework.
