### ISSUE TITLE
[Bug]: Imcomplete Doc on Reranker

### ISSUE THREAD

**Issue by astro313** [jerryjliu/llama_index#6547]
### Bug Description

Following this example on https://gpt-index.readthedocs.io/en/latest/examples/node_postprocessor/LLMReranker-Gatsby.html#retrieval

once we get the nodes, how do we pass it to the query engine to get the final response from the LLM? 

First, the documentation mentioned `[reranker]` which is not defined. 

Second, there are incomplete code (the very last cell).

There aren't any other documentation to explain how to pass thee reranked nodes to the query engine. 

### Version

0.6.30

### Steps to Reproduce

see https://gpt-index.readthedocs.io/en/latest/examples/node_postprocessor/LLMReranker-Gatsby.html#retrieval

**Comment by Disiok** [comment]
Ah, if you are building the query engine, it's doing retrieval under the hood, so you don't have to worry about passing the nodes in.

I think the reranker is defined earlier in the notebook.

```
        reranker = LLMRerank(
            choice_batch_size=5, top_n=reranker_top_n, service_context=service_context
        )
```
