### ISSUE TITLE
[Question]: Where is this prompt written in the code

### ISSUE THREAD

**Issue by ItsEnosgit** [jerryjliu/llama_index#6571]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

‘Given the context information and not prior knowledge, answer the question:’
I want to know where this piece of code appears，and trying to change it.Thanks

**Comment by Disiok** [comment]
This is the default prompt specified in `llama_index/prompts/default_prompts.py`. 

You can modify this following this guide: https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html
