### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JSv4** [jerryjliu/llama_index#6596]
### Bug Description

In the latest version of Llama-Index, creating a SimpleDirectoryReader with a directory containing .docx file results in an error. 

This call:

```python
logger.debug(f"Build index from {tempdir_path}")
            SimpleDirectoryReader = download_loader("SimpleDirectoryReader")
            loader = SimpleDirectoryReader(
                tempdir_path, recursive=True, exclude_hidden=False
            )
            logger.debug(f"Loaded created...")
```
Fails at the loader = ... step. Error message is 

```
No module named 'llama_index.readers.schema'
```

Downgrading to 0.6.30 fixed the issue (I picked something a couple versions back as I don't have time to trace exactly which version has the problem change and wanted to revert a couple versions to be safe). 

### Version

0.6.34

### Steps to Reproduce

Try to create a SimpleDirectoryReader with a directory containing a docx.

### Relevant Logs/Tracbacks

```shell
See above.
```

**Comment by logan-markewich** [comment]
@JSv4 this will be fixed shortly, definitely aware :)

**Comment by logan-markewich** [comment]
https://github.com/jerryjliu/llama_index/pull/6598
