### ISSUE TITLE
[Feature Request]: Create CallbackManager that can handle async and concurrent event completion

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6602]
### Feature Description

See https://github.com/jerryjliu/llama_index/issues/6594#issuecomment-1608647941 for original discussion

We should design and create a new `CallbackManager` that can fit these requirements

The logic is as follows:
```python
def on_event_end(event_id, ..):
  if trace_stack.last().event_id != event_id: 
  # The ToS has not completed. This means that the completion is async (or there is an error)
    trace_stack.last().dependent_events.push(event_type, payload, event_id, kwargs)
  else:
    # handle current event
    ..
    # handle dependent events
    for event in dependent_events:
      self.on_event_end(event)
```

For this reason, we also need to handle errors to ensure that the event (with corresponding success or failure payload) is always registered.

An alternate behaviour is to disregard syncing the stack, but only sync the `end_trace`.

**Comment by logan-markewich** [comment]
It's on my radar for sure. Really for it to work, each async event just needs it's own copy of the current callback manager, and then you just need to aggregate the trace's at the end

Some kind of specialized dispatching function would do the trick,

**Comment by jon-chuang** [comment]
> you just need to dispatch the tasks and aggregate the trace's at the end

Do you mean async dispatch?

Well, basically, the above system would also do the trick but not requiring async. 

As it relies on the callback completion to trigger the downstream action (and eventual trace end). But we need to ensure that the callback is _always_ sent (we can also implement some timeout behaviour)

**Comment by jon-chuang** [comment]
Anw, I think we're on the same page here, let me implement something and we can iterate on that.

**Comment by logan-markewich** [comment]
yea go for it, that would be amazing! 🙏🏻

**Comment by jon-chuang** [comment]
Tasks:
- [ ] Basic callback handling
- [ ] Add timeout
- [ ] Attempt to send error callbacks to report error traces - and have a more reliable callback completion (rely less on timeout - only as a fallback)

**Comment by jon-chuang** [comment]
Oops, since we have setup and exit behaviour for `CallbackHandler`s as well, we need to handle concurrent sessions for these as well. The plot thickens...

**Comment by jon-chuang** [comment]
Actually, there are several severe concurrency issues with the above described solution.

 A session should be tied to a context manager still. The children all inherit from the root session, unless there is no root, then that span becomes the root.

**Comment by jon-chuang** [comment]
After some further thought, I believe that the following set of APIs are required:
1. Per run handlers (most granular). Every run of `query`, `retrieval` carry the root invocation's `run_id`. This is a global `uuid`. Children handlers are always passed the parent `run_id` and will write to this namespace. A new `uuid` is generated when no parent `run_id` exists. Note that a single chat session will contain multiple `LlamaIndex` Aggregation is across time, along a `run_id`.
    - examples: per-run traces, logs, MLOps logging.
2. Global session tracing. Aggregation across entire session.
    - examples: global `num_tokens`, `num_embedding_tokens`, `num_completion_tokens` etc.

I like the idea of always performing per-run handlers and then aggregating across runs.

I believe that some thought needs to be given to scaling up. I like the above aggregation pattern because multi-step aggregations (e.g. across a cluster) become a lot easier.


---

All in all, this suggests the following set of concrete APIs:

```python
class BaseCallbackHandler:

# A callback that only has access to a single run (e.g. a single top level "query") 
class SingleCallbackHandler(BaseCallbackHandler):
  def start_trace():
  def end_trace():
  
# A callback that aggregates across runs in a session
# It can be polled and reset periodically (and synced to e.g. prometheus) 
# If the callback is stateless between runs, and directly
# logs to some external system, then the aggregation can be ignored.
class AggregateCallbackHandler(BaseCallbackHandler):
  agg_map: Dict[int, SingleCallbackHandler] # maps a `run_id` to a given callback object
  
  # aggregates across all runs
  # default is to do nothing
  def aggregate():
  
  def exit():
    self.aggregate()
    self.print_tabular()
  
  
```

**Comment by jon-chuang** [comment]
Any preference for naming:
1. `run_id`
2. `invoke_id`
3. `call_id`

@logan-markewich ?

**Comment by jon-chuang** [comment]
Long story short we are actually converging to langchain's solution, which is that we now need to pass `Callback`s directly into each run instance, and a per-run `CallbackManager` is always created.

How langchain has done it is exactly is even more granular than what I describe. Every level of invocation has with it associated a `uuid` run_id. This means that callbacks can happen on llm level, chain level etc.

**Comment by logan-markewich** [comment]
Also feel free to DM me on discord, happy to help hash out finer details if you get stuck or anything!

**Comment by logan-markewich** [comment]
This is actually handled already. Thanks @dosu-beta
