### ISSUE TITLE
[Question]: Difficulty Accessing metadata from NodeWithScore in LlamaIndex version 0.6.34.post1

### ISSUE THREAD

**Issue by Victor-Dimitrov** [jerryjliu/llama_index#6605]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there,

I am currently using the LlamaIndex library (version 0.6.34.post1) to create an information retrieval system and I've encountered some issues that I would appreciate your help with.

In the process of trying to retrieve the document associated with a given query response, I tried to access the metadata field from source_nodes in the response object. However, I got an AttributeError stating that the 'NodeWithScore' object has no attribute 'metadata'.

Here is a snippet of my code that produces the error:

```
response = query_engine.query(question)
document_id = response.source_nodes[0].metadata['file_name']  # Raises AttributeError
```

I found in the LlamaIndex documentation that the 'metadata' property should be available in each source node, created from the document. However, in the actual usage, it seems 'NodeWithScore' object doesn't have the 'metadata' attribute.

Moreover, I noticed that the 'NodeWithScore' object is not explicitly documented in the how-to guides or in the API reference. The [Node reference page](https://gpt-index.readthedocs.io/en/latest/reference/node.html) is empty. Therefore I couldn't understand its properties and usage.

Could you provide some guidance on how to correctly access the metadata of a source node in a response? Also, it would be helpful if you could consider enhancing your documentation to include more details on the 'NodeWithScore' object and its attributes.

Thanks in advance you for your time and help!

Victor

**Comment by logan-markewich** [comment]
@Victor-Dimitrov that way of accessing was slightly deprecated.

With some recent changes as well, you can access using `response.source_nodes[0].node.metadata['file_name']`

**Comment by Victor-Dimitrov** [comment]
@logan-markewich noted, thank you for your quick response! Works fine now.
