### ISSUE TITLE
[Question]: Using Hugging Face Text Generation Inference with llama-index

### ISSUE THREAD

**Issue by Maxusmusti** [jerryjliu/llama_index#6608]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

I was curious if there was a recommended approach for using llama-index alongside Hugging Face's [Text Generation Inference Server](https://github.com/huggingface/text-generation-inference).

There seems to be langchain support for [defining the llm](https://python.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_textgen_inference)

Wanted to see if I should use that and pass it directly into my service context, or if I should write an `LLMPredictor` wrapping it, or if there was any other recommended route for utilizing TGIS as the "llm".

For context, I am currently using Falcon-7B directly with the HuggingFaceLLMPredictor in llama-index, but would like to switch to running Falcon-7B via TGIS, then using llama-index on top of that.

**Comment by logan-markewich** [comment]
It shouuuld work if you wrap it with the LLMPredictor class yea @Maxusmusti

**Comment by Maxusmusti** [comment]
Got it, I'll give it a try!

**Comment by Maxusmusti** [comment]
Update: I managed to get it working via the following:

```
tgis_predictor = LLMPredictor(
        llm=HuggingFaceTextGenInference(
            inference_server_url="http://localhost:8010/",
            max_new_tokens=256,
            temperature=0.7,
            server_kwargs={},
        )
    )
```

however, I realized my model performed much worse without being able to pass in system prompts and query wrapper prompts into the predictor, like you can with the HuggingFaceLLMPredictor, so I made some changes to the standard LLMPredictor to make the following possible:
```
    system_prompt = """# Falcon-7B Instruct
    - You are a helpful AI assistant and provide the answer for the question based on the given context.
    - You answer the question as truthfully as possible using the provided text, and if the answer is not contained within the text below, you say "I don't know".
    """ 

    # This will wrap the default prompts that are internal to llama-index
    query_wrapper_prompt = SimpleInputPrompt(">>QUESTION<<{query_str}\n>>ANSWER<<")

    # Change default model
    embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
    tgis_predictor = LLMPredictor(
        llm=HuggingFaceTextGenInference(
            inference_server_url="http://localhost:8010/",
            max_new_tokens=256,
            temperature=0.7,
            server_kwargs={},
        ),
        system_prompt=system_prompt, # added in llama-index by myself
        query_wrapper_prompt=query_wrapper_prompt # added in llama-index by myself
    )
```

This addition SIGNIFICANTLY improved model response accuracy/desirability.

I've opened up a PR to add the feature to llama-index upstream: #6647

**Comment by Maxusmusti** [comment]
@logan-markewich Let me know if there's anything improperly formatted or set up with the way I made the PR, and thanks again for the quick response!

**Comment by mjsteele12** [comment]
Thanks for working on this- I stumbled across it after making something similar (I'm running falcon 40b-instruct with TGI locally along with my own hosted embedding service). fwiw, I also implemented my own custom HuggingFaceTextGenInference for other things I needed, so I just ended up implementing the query wrapper there (along with adjusting max_new_tokens to avoid size issues).
