### ISSUE TITLE
[Documentation]: The loading documents example does not work with latest versions

### ISSUE THREAD

**Issue by kadereub** [jerryjliu/llama_index#6611]
### Documentation Issue Description

The example of loading the documents from a list of text strings in Python results in an error using the latest langchain/llama index installations.

This code below results in the error.

```
from llama_index import Document

text_list = [text1, text2, ...]
documents = [Document(t) for t in text_list]
```

Langchain version: `'0.0.217'`

LLama Index version: `'0.6.34.post1'`

**Error:**

![image](https://github.com/jerryjliu/llama_index/assets/31546506/f00db798-b6b4-4d93-b608-cd657880848a)

**Proposed fix:**

```
from llama_index import Document

text_list = [text1, text2, ...]
documents = [Document(page_content=t) for t in text_list]
```

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#load-in-documents

**Comment by logan-markewich** [comment]
@kadereub It should be `Document(text=t)`, appologies for missing this. Will merge a patch to the docs in a second
