### ISSUE TITLE
[Documentation]: Defining Prompts

### ISSUE THREAD

**Issue by iooab10** [jerryjliu/llama_index#6621]
### Documentation Issue Description

THis page... 

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html#full-example

Brought me here as a promise of a FULL Example of a custom prompt.  

https://github.com/jerryjliu/llama_index/blob/main/examples/paul_graham_essay/TestEssay.ipynb

Yes, this code example uses a customized prompt.  How do I see that custom prompt in action?  What question(s) do I ask because I do NOT see any special prompts in action. 

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_prompts.html#full-example

**Comment by logan-markewich** [comment]
Right. So just modify the template with your new instructions. It will be used `in action` during queries when you pass in the prompt template as a kwarg.

For proof that it's working, just ask it to talk like a pirate or something silly.

If this did not answer your question, give me a more specific example of what you want. I don't exactly get what you mean when you say `I want to see the words "We have also provided some context information below" in the OUTPUT`

**Comment by iooab11** [comment]
Tweaking https://github.com/jerryjliu/llama_index/blob/main/examples/paul_graham_essay/TestEssay.ipynb

documents = SimpleDirectoryReader('data').load_data()
# query_str = "What did the author do growing up?"
query_str = "talk like a pirate"
context_str = "unknown"
SUMMARY_PROMPT_TMPL = (
    "Context information is below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given the context information and not prior knowledge, "
    f"answer the question: {query_str}\n"
)
SUMMARY_PROMPT = Prompt(SUMMARY_PROMPT_TMPL)

DEFAULT_TEXT_QA_PROMPT_TMPL = (
    "Context information is below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given the context information answer the following question "
    "(if you don't know the answer, use the best of your knowledge): {query_str}\n"
)
TEXT_QA_TEMPLATE = QuestionAnswerPrompt(DEFAULT_TEXT_QA_PROMPT_TMPL)

# both with our without the templates, the output is the same
index_with_query = TreeIndex.from_documents(documents, text_qa_template=TEXT_QA_TEMPLATE, summary_template=SUMMARY_PROMPT)
# index_with_query = TreeIndex.from_documents(documents)

query_engine = index_with_query.as_query_engine(
    retriever_mode="root"
)
print(query_engine.query(query_str))

result:
rk. But alas, 'twas not t' be found, so the brave soul decided t' start a web app for makin' web apps instead. And then, lo and behold, the brave soul stumbled upon a grand audience, and realized that anyone could publish anythin' on the web. So the brave soul set out t' write essays, and give talks, and start a summer program for undergrads t' start startups. And then, after a few years, the brave soul decided t' hand the business over t' a new captain, and set out t' write essays and work on other things. So, me hearties, if ye ever find yerselves in a similar situation, remember the brave soul's tale and be sure t' make the most of yer opportunities! Arrr!
