### ISSUE TITLE
[Bug]: Explicitly imported SimpleDirectoryReader does not add extra_info to parsed nodes

### ISSUE THREAD

**Issue by JSv4** [jerryjliu/llama_index#6629]
### Bug Description

I am deploying an app based on Llamaindex inside of a docker container. I ran into a docker-related issue using the `download_loader()` to create a `SimpleDirectoryReader`:

``` python 
  # Create the GPTVectorStoreIndex
  logger.debug(f"Build index from {tempdir_path}")
  SimpleDirectoryReader = download_loader("SimpleDirectoryReader")
  loader = SimpleDirectoryReader(
      tempdir_path, recursive=True, exclude_hidden=False
  )
  documents = loader.load_data()
  logger.debug("Loaded...")
```

The dynamic installation and loading of `SimpleDirectoryReader` worked as expected for the most part in a local container that has the local app directory as a read/write volume. After a query, the source node looks like this:

```
Node: ['__abstractmethods__', '__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__post_init__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_generate_doc_hash', 'child_node_ids', 'dataclass_json_config', 'doc_hash', 'doc_id', 'embedding', 'extra_info', 'extra_info_str', 'from_dict', 'from_json', 'get_doc_hash', 'get_doc_id', 'get_embedding', 'get_node_info', 'get_origin_type', 'get_text', 'get_type', 'get_types', 'is_doc_id_none', 'is_text_none', 'next_node_id', 'node_info', 'parent_node_id', 'prev_node_id', 'ref_doc_id', 'relationships', 'schema', 'text', 'to_dict', 'to_json']
Extra info: {'file_name': 'NVCA-2020-Stock-Purchase-Agreement-1-September-1-2020_eVQ4P4y.docx'}
Node info: {'start': 56846, 'end': 60980, '_node_type': '1'}
[NVCA-2020-Stock-Purchase-Agreement-1-September-1-2020.docx](https://github.com/jerryjliu/llama_index/files/11899087/NVCA-2020-Stock-Purchase-Agreement-1-September-1-2020.docx)
```

**In production,** however, my Docker container does not have write access to the python install directory or packages dir,  *but* it appears loading the `SimpleDirectoryReader` using `download_loader` in this way tries to modify packages on the fly (not a huge surprise, but I hadn't considered this ahead of time). I didn't want to have the container modifying my Python packages dynamically for a) security reason and b) this has a performance penalty as the containers will be loaded and stopped repeatedly and so this install process needs to re-occur repeatedly, increasing latency and bandwidth costs. 

I tried to work around this by manually installing `llama-hub` when creating the container and then loading `SimpleDirectoryLoader` explicitly like so:

```python
from llama_index.readers.file.base import SimpleDirectoryReader

# Create the GPTVectorStoreIndex
logger.debug(f"Build index from {tempdir_path}")
loader = SimpleDirectoryReader(
    tempdir_path, recursive=True, exclude_hidden=False
)
documents = loader.load_data()
logger.debug("Loaded...")
```

Now my docker issue is solved, there are no run time modifications of my python directory, **BUT** it appears the instantiated readers are no longer adding the `extra_info` metadata. Here's my logs related to the source nodes:

```
Node: ['__abstractmethods__', '__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__post_init__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_generate_doc_hash', 'child_node_ids', 'dataclass_json_config', 'doc_hash', 'doc_id', 'embedding', 'extra_info', 'extra_info_str', 'from_dict', 'from_json', 'get_doc_hash', 'get_doc_id', 'get_embedding', 'get_node_info', 'get_origin_type', 'get_text', 'get_type', 'get_types', 'is_doc_id_none', 'is_text_none', 'next_node_id', 'node_info', 'parent_node_id', 'prev_node_id', 'ref_doc_id', 'relationships', 'schema', 'text', 'to_dict', 'to_json']
Extra info: None
Node info: {'start': 24890, 'end': 29195, '_node_type': '1'}
```

Any idea what's up here?

### Version

0.6.30

### Steps to Reproduce

Instantiate a SimpleDirectoryReader using download_loader() and load attached docx. `Extra_info` will be populated in returned queries' sources. 

Then, instantiate a SimpleDirectoryReader loaded via `from llama_index.readers.file.base import SimpleDirectoryReader`. Create an index with the same docx and run a query. No extra_info is attached to the response nodes. 

[NVCA-2020-Stock-Purchase-Agreement-1-September-1-2020.docx](https://github.com/jerryjliu/llama_index/files/11899174/NVCA-2020-Stock-Purchase-Agreement-1-September-1-2020.docx)

### Relevant Logs/Tracbacks

```shell
See above
```

**Comment by logan-markewich** [comment]
@JSv4 `SimpleDirectoryReader` is actually built into llama-index, no need to download it

`from llama_index import SimpleDirectoryReader`

**Comment by JSv4** [comment]
@logan-markewich, I think the issue is it needs to download a docx reader from llama-hub? It definitely modifies my Python directory when spinning it up to load a docx. I can get the specific log line if you want. In either case, the behavior is not the same depending on how I import and instantiate the class. `extra_info` is missing when I load it via `from llama_index.readers.file.base import SimpleDirectoryReader` I can try `from llama_index import SimpleDirectoryReader`, but I suspect that would have the same issue?

**Comment by logan-markewich** [comment]
Hmm, yea I see the issue, in our docx loader. It's a bit out of sync with llamahub. Will patch in a sec
