### ISSUE TITLE
download_loader Not working. Takes long time

### ISSUE THREAD

**Issue by pradeepdev-1995** [jerryjliu/llama_index#6640]
### Bug Description

Tried to load the download_loader. But it takes long time and not terminating the code
```
from llama_index import download_loader
UnstructuredReader = download_loader('UnstructuredReader', refresh_cache=False)
```

### Version

0.6.35

### Steps to Reproduce

```
from llama_index import download_loader
UnstructuredReader = download_loader('UnstructuredReader', refresh_cache=False)
```

**Comment by Disiok** [comment]
Works fine for me. Could not reproduce. Please feel free to re-open if you can help provide more specifics to reproduce.
