### ISSUE TITLE
[Feature Request]: Improve performance of the default vector index

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6650]
### Feature Description

The default vector index which uses SVMs, is extremely slow for retrieval. I suggest to improve the default with some simple index that has minimal dependencies but offers good performance.

### Reason

Better UX.

**Comment by logan-markewich** [comment]
Isn't the default just using simple cosine similarity across all embeddings using numpy?

Pretty sure the SVM (and MMR) modes are optional

**Comment by jon-chuang** [comment]
Hmm I see. Let me check. But it's really slow. Let me try to quantify.

Are we OK installing external dep for this?

**Comment by jon-chuang** [comment]
Yep, it doesn't use SVM, but computes all the embeddings. Seems like a poor default IMO. Let me see if something in pure python can be much faster.

**Comment by jon-chuang** [comment]
Oops, turns out it was the LLM response that was slow, I misread the logs.
