### ISSUE TITLE
[Question]: Average query time is 25 seconds for me

### ISSUE THREAD

**Issue by sorrentinopasquale** [jerryjliu/llama_index#6657]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi all, 
I am having fun with LLAMA index and now trying to make it more efficient.

I am using a bit older version, but even if I upgrade the time improves just a bit.
I am happy of the answers but the average query time is 25 seconds using OpenAI. 
Any suggestion? Do you advise any specific model? My goal is to retrieve fast from documents

I save the index by project and then load it:
`index = GPTSimpleVectorIndex.load_from_disk(projectId + '.json')`
`results = index.query(prompt)`
`message = results.response`

**Comment by logan-markewich** [comment]
text-davinci-003 (the default) is definitely slower than using something like gpt-3.5

Also in the older versions of llama-index, the default chunk size was quite a lot bigger (3900 vs. 1024 now), so newer versions of llama-index are a bit faster (which you noticed)

The main bottlenecks are 
a) how many LLM calls the query makes (default settings with newer versions of llama-index should be 1 llm call)
a) how much text you send
b) how much text the model generates and 
c) which LLM you use

**Comment by logan-markewich** [comment]
Going to close for now! Feel free to reach out on the discord with any more questions
