### ISSUE TITLE
[Question]: How do I set the base prompt personality to Donald Trump or Barack Obama for example?

### ISSUE THREAD

**Issue by reversingentropy** [jerryjliu/llama_index#6658]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using GPT-3.5-turbo and the Knowledge Graph Index object to create a chatbot that answers information based on the triples I have uploaded. 

llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo"))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
index = KnowledgeGraphIndex([], service_context=service_context, llm_predictor=llm_predictor)
query_engine = index.as_chat_engine(include_text=False, response_mode="tree_summarize")

However, I would like to explore setting the personality of the model. How does one go about doing so? How do we edit base templates and where do we insert the prompt into this pipeline? Thank you

**Comment by logan-markewich** [comment]
The main templates to modify are the `text_qa_template` and the `refine_template`
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules

If you are using a chat engine or agent, you can also pass in a `system_prompt` which is just a string with extra instructions for how to act.
https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent.html#agent-with-personality
