### ISSUE TITLE
[Bug]: Service context not working correctly on Mac

### ISSUE THREAD

**Issue by yousifKashef** [jerryjliu/llama_index#6707]
### Bug Description

I am trying to run the pdf local example notebook example on my Mac but I am getting this error: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 13
     10 prompt_helper = PromptHelper(max_input_size=512, num_output=256, max_chunk_overlap=-1000)
     11 embed_model = HuggingFaceEmbeddings()
---> 13 service_context = ServiceContext.from_defaults(
     14     llm_predictor=llm_predictor,
     15     embed_model=embed_model,
     16     prompt_helper=prompt_helper,
     17     node_parser=SimpleNodeParser(text_splitter=TokenTextSplitter(chunk_size=300, chunk_overlap=20))
     18 )
     20 # Document setup
     21 PyMuPDFReader = download_loader("PyMuPDFReader")

File ~/LLM_venv/lib/python3.10/site-packages/llama_index/indices/service_context.py:138, in ServiceContext.from_defaults(cls, llm_predictor, llm, prompt_helper, embed_model, node_parser, llama_logger, callback_manager, chunk_size, chunk_overlap, context_window, num_output, chunk_size_limit)
    136 # NOTE: the embed_model isn't used in all indices
    137 embed_model = embed_model or OpenAIEmbedding()
--> 138 embed_model.callback_manager = callback_manager
    140 prompt_helper = prompt_helper or _get_default_prompt_helper(
    141     llm_metadata=llm_predictor.get_llm_metadata(),
    142     context_window=context_window,
    143     num_output=num_output,
    144 )
    146 node_parser = node_parser or _get_default_node_parser(
    147     chunk_size=chunk_size,
    148     chunk_overlap=chunk_overlap,
    149     callback_manager=callback_manager,
    150 )

File ~/LLM_venv/lib/python3.10/site-packages/pydantic/main.py:357, in pydantic.main.BaseModel.__setattr__()

ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"

### Version

0.6.38.post1

### Steps to Reproduce

run a service context: service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model,
    prompt_helper=prompt_helper,
    node_parser=SimpleNodeParser(text_splitter=TokenTextSplitter(chunk_size=300, chunk_overlap=20))
)

**Comment by logan-markewich** [comment]
@yousifKashef the huggingface embeddings have to be wrapped in our langchain adapter class, see here
https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

**Comment by wyzhhhh** [comment]
Have you solved this problem ? I met the same

**Comment by logan-markewich** [comment]
@wyzhhhh does the above link not help? You need to wrap huggingface embeddings with the LangchainEmbedding class

**Comment by wyzhhhh** [comment]
> @wyzhhhh does the above link not help? You need to wrap huggingface embeddings with the LangchainEmbedding class

solved it!!!Thank you very muchhhhhh!!

**Comment by Data-drone** [comment]
Docs give 404?

**Comment by logan-markewich** [comment]
@Data-drone https://gpt-index.readthedocs.io/en/stable/core_modules/model_modules/embeddings/usage_pattern.html#local-embedding-models

The search in our docs also works well 👌
