### ISSUE TITLE
[Bug]: from llama_index import GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by silvacarl2** [jerryjliu/llama_index#6709]
### Bug Description

pip install llama-index

python
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from llama_index import GPTSimpleVectorIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'GPTSimpleVectorIndex' from 'llama_index' (/home/silvacarl/.local/lib/python3.8/site-packages/llama_index/__init__.py)
>>>

it doesnt matter what i do or install, i cannot get around this error.  any ideas?

### Version

latest/current

### Steps to Reproduce

see above.

### Relevant Logs/Tracbacks

```shell
see above.
```

**Comment by logan-markewich** [comment]
@silvacarl2 I just installed llama_index in a fresh venv, the import works for me 🤔 

Maybe also try a fresh venv? Also technically, while that import is supported, it is deprecated. The newer import is `from llama_index import VectorStoreIndex`

Although both imports should work

**Comment by Disiok** [comment]
Please see https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html for the most up-to-date usage guide :)

**Comment by silvacarl2** [comment]
thx got it
