### ISSUE TITLE
Way to exclude directories and files using SimpleDirectoryReader

### ISSUE THREAD

**Issue by ShakesB33r** [jerryjliu/llama_index#671]
Sometimes directories contain both relevant and irrelevant subdirectories and/or files, it would be nice to have a keyword argument for excluding them, perhaps even with some matching syntax, e.g. 

`documents = SimpleDirectoryReader('...', recursive=True, exclude=["*/misc/*, "note.txt"])`

**Comment by Minweiwangaaaa** [comment]
nice feature
