### ISSUE TITLE
[Feature Request]: Local-model defaults for non-predictor sensitive experimentation

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6720]
### Feature Description

It can be costly to run experiments using paid APIs, especially, if code is accidentally re-run.

Hence, it should be as easy as `ServiceContext(local=true)` to download e.g. from huggingface, store in local cache, and utilize local model. Local model should be lightweight but effective (100M-500M params, e.g. BERT/sentence transformer).

To evaluate: is dev loop slower due to high latency from local model (e.g. on CPU-only devices)

### Reason
Configuring a cheap local model each time is cumbersome.

### Value of Feature
Save cost, save hassle

**Comment by tirthajyoti** [comment]
Good proposal, in my opinion.

**Comment by jon-chuang** [comment]
Once https://github.com/jerryjliu/llama_index/issues/6692 is implemented, we should decide if it's better to also use the subprocess service.

**Comment by logan-markewich** [comment]
One concern is that any model that is that size (100M-500M) parameters will likely not be useful enough as an LLM. LLMs at this size (like GPT-2) struggle to follow instructions. At least, the last time I looked this was the case. Maybe this has changed recently. 

For an embedding model though, its a decent size.

**Comment by jon-chuang** [comment]
Indeed. However, what I was thinking was to provide the ggml 4bit quantized models, (either 7B or 13B) as the local default,) for llm which includes models like vicuna and I think orca and also open license models like OpenLlama and perhaps MPT and (need to check for the full list). I've worked with ggml models before (llama.cpp) so it shouldn't be too difficult to implement this.

**Comment by jon-chuang** [comment]
Btw, switching between models easily like this is one of the motivations for a global service context. Perhaps the API would be

```python
service_context.to_local()
service_context.to_defaults()
```

Not too sure yet.

**Comment by jon-chuang** [comment]
I think we should open this again; reinvestigate with aggressive pruning of long context using rerankers and node pruners.

**Comment by jon-chuang** [comment]
After looking [more closely](https://www.sbert.net/docs/pretrained_models.html), `all-MiniLM-L6-v2` is actually pretty bad for search. Anyway, let's just keep `all-mpnet-base-v2` in mind.
