### ISSUE TITLE
[Bug]: ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"

### ISSUE THREAD

**Issue by wyzhhhh** [jerryjliu/llama_index#6750]
### Bug Description

I replaced the original model with the native language model and the embedding model, but I got an error when running code of
**service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model,
    context_window=context_window,
    num_output=num_output
)**

Traceback (most recent call last):
  File "/home/data/llama-index/Try_llamaindex.py", line 41, in <module>
    service_context = ServiceContext.from_defaults(
  File "/root/anaconda3/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 138, in from_defaults
    embed_model.callback_manager = callback_manager
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"

### Version

v0.6.38

### Steps to Reproduce

import torch
from langchain.llms.base import LLM
from llama_index import LLMPredictor
from transformers import pipeline
from typing import Optional, List, Mapping, Any
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
# set context window size
context_window = 2048
# set number of output tokens
num_output = 256

# store the pipeline/model outisde of the LLM class to avoid memory issues
model_name = "vicuna-chinese"
pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype": torch.bfloat16})

class CustomLLM(LLM):
    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]
        # only return newly generated tokens
        return response[prompt_length:]
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": model_name}
    @property
    def _llm_type(self) -> str:
        return "custom"

# define our LLM
llm_predictor = LLMPredictor(llm=CustomLLM())

#from langchain.embeddings.huggingface import HuggingFaceInstructEmbeddings
from llama_index import LangchainEmbedding, ServiceContext
#embed_model = LangchainEmbedding(HuggingFaceInstructEmbeddings())
from text2vec import SentenceModel
from sentence_transformers import SentenceTransformer
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
#embed_model= SentenceModel('./text2vec-base-chinese')
embed_model = HuggingFaceEmbeddings(model_name='./text2vec-base-chinese')
#embed_model = SentenceTransformer("./text2vec-base-chinese")
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model,
    context_window=context_window,
    num_output=num_output
)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/data/llama-index/Try_llamaindex.py", line 41, in <module>
    service_context = ServiceContext.from_defaults(
  File "/root/anaconda3/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 138, in from_defaults
    embed_model.callback_manager = callback_manager
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"
```

**Comment by logan-markewich** [comment]
Since you are extending the LLM class from langchain, you need to wrap with the LangchainLLM class

If you pass the LLM directly into the service context, this is handled for you

`service_context = ServiceContext.from_defaults(llm=CustomLLM())`

Our latest docs reflect this https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced
