### ISSUE TITLE
[Documentation]: Example: Using a Custom LLM Model - Advanced

### ISSUE THREAD

**Issue by kiasar** [jerryjliu/llama_index#6753]
### Documentation Issue Description

My package is updated (0.7.1). But I still get an error running your example code.
`ImportError: cannot import name 'CustomLLM' from 'llama_index.llms'`

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced

**Comment by logan-markewich** [comment]
This has been fixed in v0.7.2, was just missing the import in the init file

**Comment by kiasar** [comment]
Thanks. But other imports are still a problem! I mean CompletionResponse and LLMMetadata. Neither of them is in llama_index.llms.

**Comment by kiasar** [comment]
I created a pull request to fix this
https://github.com/jerryjliu/llama_index/pull/6762
