### ISSUE TITLE
How to Integrate Cache into LLM Predictor

### ISSUE THREAD

**Issue by BharahthyKannan** [jerryjliu/llama_index#6759]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

In a recent version, ChatGPTLLMPredictor is removed. We wired the GPT cache with the llmpredictor. Now it is breaking. What is the alternate way to integrate GPT cache with the LLM predictor ?

**Comment by logan-markewich** [comment]
If you are using langchain LLM classes, you should still be able to follow their instructions here and set the cache on the langchain module

https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llm_caching

```python
import langchain
from langchain.cache import InMemoryCache

langchain.llm_cache = InMemoryCache()

from langchain.chat_models import ChatOpenAI
from llama_index import ListIndex, Document, ServiceContext

llm = ChatOpenAI(model_name="gpt-3.5-turbo")
service_context = ServiceContext.from_defaults(llm=llm)
index = ListIndex.from_documents([Document("Hello World")], service_context=service_context)
index.as_query_engine().query("Hello?")
index.as_query_engine().query("Hello?")
```

The second query will return instantly.

Should be added to our native LLMs at some point too :)
