### ISSUE TITLE
[Feature Request]: Configurable DynamoDB url

### ISSUE THREAD

**Issue by louislivingston** [jerryjliu/llama_index#6760]
### Feature Description

Please add the ability to set the url for DynamoDB. A suggestion would be to get it from environment variables

### Reason

I am interested in using the DynamoDB implementation for document storage, however, I noticed that the boto3 initialization does not give me the ability to specify the url to use for DynamoDB.

### Value of Feature

This would help out greatly in development environments where DynamoDB is hosted locally.

**Comment by rjarun8** [comment]
This is how I feel we can address the issue. Your thoughts?

@classmethod
def from_table_name(cls, table_name: str) -> DynamoDBKVStore:    
  """Load a DynamoDBKVStore from a DynamoDB table name.
      Args:
          table_name (str): DynamoDB table name """
      try:
          import boto3
      except ImportError:
          raise ImportError(IMPORT_ERROR_MSG)
      _**# Get the DynamoDB URL from environment variable
      dynamodb_url = os.getenv('DYNAMODB_URL')**_
      # Create a session
      session = boto3.Session()
      **_# If the DynamoDB URL is set, use it as the endpoint URL
      if dynamodb_url is not None:
          ddb = session.resource("dynamodb", endpoint_url=dynamodb_url)
      else:
          # Otherwise, let boto3 use its default configuration
          ddb = session.resource("dynamodb")_**
      return cls(table=ddb.Table(table_name))

**Comment by louislivingston** [comment]
The only change I would make is the conditional. It should only need `if dynamodb_url:`
