### ISSUE TITLE
[Bug]: TypeError: replace() should be called on dataclass instances

### ISSUE THREAD

**Issue by kiasar** [jerryjliu/llama_index#6763]
### Bug Description

I'm trying my best to replicate the[ official custom LLM example](https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced) but I find it hard to do so!

With Llama_index version 0.7.2, first I changed the import to this to make it work:
```
from llama_index.llms import CustomLLM
from llama_index.llms.base import CompletionResponse, LLMMetadata, CompletionResponseGen
```
P.S. Note that CompletionResponseGen is not even imported in the example.

But now I get this error: 
`TypeError: replace() should be called on dataclass instances`
Which is from these lines:
```
service_context = ServiceContext.from_defaults(
    llm=llm,
    context_window=context_window,
    num_output=num_output
)
```

This is the full error if that helps:
```
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/z/zahra/PyCharm/Document_filler/main.py", line 135, in <module>
    service_context = ServiceContext.from_defaults(
  File "/afs/csail.mit.edu/u/z/zahra/.virtualenvs/MIT_prune/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 140, in from_defaults
    prompt_helper = prompt_helper or _get_default_prompt_helper(
  File "/afs/csail.mit.edu/u/z/zahra/.virtualenvs/MIT_prune/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 42, in _get_default_prompt_helper
    llm_metadata = dataclasses.replace(llm_metadata, context_window=context_window)
  File "/usr/lib/python3.10/dataclasses.py", line 1425, in replace
    raise TypeError("replace() should be called on dataclass instances")
TypeError: replace() should be called on dataclass instances
```

### Version

0.7.2

### Steps to Reproduce

Run the official example (but first correct the imports)

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced

**Comment by logan-markewich** [comment]
Just merged the fix for this! Will be in the next release (or you can install from source)
