### ISSUE TITLE
[Bug]: cannot import name 'HuggingFaceLLMPredictor' from 'llama_index.llm_predictor' 

### ISSUE THREAD

**Issue by vladimircape** [jerryjliu/llama_index#6772]
### Bug Description

in 0.7.2 version it's not working
` from llama_index.llm_predictor import HuggingFaceLLMPredictor`

### Version

0.7.2

### Steps to Reproduce

from llama_index.llm_predictor import HuggingFaceLLMPredictor

**Comment by logan-markewich** [comment]
Please see the updated usage

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-huggingface-llm

**Comment by Orescout** [comment]
link points to 404

**Comment by logan-markewich** [comment]
@Orescout yea we refactored the docs 

New link here https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-huggingface-llm

The search also works very well btw 😉
