### ISSUE TITLE
Is llamaindex supports conversationBufferMemory?

### ISSUE THREAD

**Issue by pradeepdev-1995** [jerryjliu/llama_index#6775]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there any chat memory keeping functionality in **llamaindex** like that in langchain?
Eg: 
```
from langchain.memory import ConversationBufferMemory
```

**Comment by rjarun8** [comment]
https://github.com/jerryjliu/llama_index/issues/1386

**Comment by logan-markewich** [comment]
Our agents and chat engines have very basic chat history support (just an array of messages). You can manually manipulate this as needed.

We are pushing for more advanced stuff soon (I know I know, Jerry said the same thing in May, but for realsies this time)

**Comment by wey-gu** [comment]
> Our agents and chat engines have very basic chat history support (just an array of messages). You can manually manipulate this as needed.
> 
> We are pushing for more advanced stuff soon (I know I know, Jerry said the same thing in May, but for realsies this time)

looking forward to it!

**Comment by vipinap98** [comment]
is the conversational memory implemented?

**Comment by uzumakinaruto19** [comment]
Is this implemented yet?

**Comment by logan-markewich** [comment]
A basic chat buffer is implemented (and it's the default for all agents and chat engines)

https://github.com/jerryjliu/llama_index/blob/main/llama_index/memory/chat_memory_buffer.py
