### ISSUE TITLE
[Feature Request]: Streaming completion for HuggingFace local models

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6793]
### Feature Description

HuggingFace should support streaming completion. Let's add it to improve local model support

**Comment by logan-markewich** [comment]
This is already supported in the HuggingFaceLLM actually

**Comment by logan-markewich** [comment]
https://github.com/jerryjliu/llama_index/blob/6541794cfef0f7059a61dffca6643e8fd3252075/llama_index/llms/huggingface.py#L130
