### ISSUE TITLE
[Documentation]: Example Notebook Contains Old TransformQueryEngine Interface Call

### ISSUE THREAD

**Issue by mickeybeurskens** [jerryjliu/llama_index#6807]
### Documentation Issue Description

In the Uber SEC-10K notebook which showcases searching with VectorIndexes, TransformQueryEngine is used to construct a tool chain for langchain. It is called as such:

```python
query_engine = TransformQueryEngine(
        query_engine,
        query_transform=decompose_transform,
        transform_extra_info={"index_summary": index.index_struct.summary},
    )
```

However, `transform_extra_info` seems to be deprecated in favor of `transform_metadata`. 
As far as I understand, the call should become:

```python
query_engine = TransformQueryEngine(
        query_engine,
        query_transform=decompose_transform,
        transform_metadata={"index_summary": index.index_struct.summary},
    )
```

Link to notebook: https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb

### Documenation Link

https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb

**Comment by marco-ve** [comment]
transform_extra_info is still used in the chatbot example:

https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/chatbots/building_a_chatbot.html
