### ISSUE TITLE
[Bug]: PineCone Filters features don't work right outside the bog

### ISSUE THREAD

**Issue by Arafatk** [jerryjliu/llama_index#6813]
### Bug Description

Pinecone has an upsert feature that let's you add metadata tags to your embeddings while upserting so that you can filter based on those things 

```
import pinecone

pinecone.init(api_key="your-api-key", environment="us-west1-gcp")
index = pinecone.Index("example-index")

index.upsert([
    ("A", [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], {"genre": "comedy", "year": 2020}),
    ("B", [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2], {"genre": "documentary", "year": 2019}),
    ("C", [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3], {"genre": "comedy", "year": 2019}),
    ("D", [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4], {"genre": "drama"}),
    ("E", [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], {"genre": "drama"})
])

```

In the code above the filters look like this ` {"genre": "comedy", "year": 2020}` and they help you selectively use those exclusively to get results just on the filters. 

Right now the add function has a metadata field which is ideally supposed to get the "filters" 
https://github.com/jerryjliu/llama_index/blob/5b8148f71daee3a1d9f6f88b78b568c92f11c1b0/llama_index/vector_stores/pinecone.py#L174-L192

And the contents of metadata can be used as a filter so you can filter on "file_name" for example coz it's in metadata but the custom filters provided by the user don't get passed around so you can't make custom filters and pass them around 
https://github.com/jerryjliu/llama_index/blob/5b8148f71daee3a1d9f6f88b78b568c92f11c1b0/llama_index/vector_stores/pinecone.py#L208-L214

One way that I thought that could be done was to set `_insert_kwargs` at the time of initialization but even that wouldn't do it. Right now I can still filter somewhat using namespace, file_name but it would be very nice to filter using custom filters.

I couldn't find an example in docs It would love to see this improvement. 

### Version

Latest

### Steps to Reproduce

```

filters = MetadataFilters(filters=[ExactMatchFilter(key="custom", value="custom_value")])

def add_folder_to_pinecone(folder = DOWNLOADS_DIR, index_name = DEFAULT_PINECONE_INDEX, environment = DEFAULT_PINECONE_ENV):
    vector_store = PineconeVectorStore(index_name=index_name,environment=environment, filters=filters)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    documents = SimpleDirectoryReader(DOWNLOADS_DIR).load_data()
    VectorStoreIndex.from_documents(documents, storage_context=storage_context)

def remove_file_from_pinecone(file_name, index_name = DEFAULT_PINECONE_INDEX, environment = DEFAULT_PINECONE_ENV):
    file_name

def retreive_from_pinecone(folder = DOWNLOADS_DIR, index_name = DEFAULT_PINECONE_INDEX, environment = DEFAULT_PINECONE_ENV, top_k = SIMILARITY_TOP_K):
    vector_store = PineconeVectorStore(index_name=index_name,environment=environment)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store, storage_context=storage_context)
    retriever = VectorIndexRetriever(index=index, similarity_top_k=top_k, filters=filters)
    input_text = "education"
    all_chunks = retriever.retrieve(input_text)
    pdb.set_trace()

```
In this code `all_chunks` shouldn't be nil but it is.

**Comment by Disiok** [comment]
Hey @Arafatk , I think what you want to do is to set metadata on the documents? We have a guide on how to to that here: https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/documents_and_nodes/usage_documents.html

Let me know if this solves your issue.

**Comment by Disiok** [comment]
Once you have the metadata properly set, the metadata filtering should just work.

**Comment by Disiok** [comment]
Going to close for now. If this doesn't resolve your problem, please re-open!

**Comment by Arafatk** [comment]
@Disiok I will certainly look into that. Thanks a lot
