### ISSUE TITLE
[Question]: Which examples are still working with the breaking changes of v0.74

### ISSUE THREAD

**Issue by ianscrivener** [jerryjliu/llama_index#6814]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

New to llama_index, though mostly familiar with ML & Python etc

I can get the v0.74 demo code (below) working... but all the Jupyter examples I've tried are failing.
Is this due to the breaking changes of v0.74?

```
from llama_index import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)
`11

**Comment by logan-markewich** [comment]
how is it breaking? that looks correct to me. Did you set your openai key?

If you are running in a notebook, you might need to set the API key in the env vars, as well as directly on the module

```
import openai
openai.api_key = "sk-..."
```

**Comment by ianscrivener** [comment]
thanks, 
I did have an expired OpenAI keyearlier.. but there are other issues
eg with`/examples/paul_graham_essay/SentenceSplittingDemo.ipynb`

```
LookupError                               Traceback (most recent call last)
Cell In[1], line 35
     29         f.write(
     30             "\n-------\n\n{}. Size: {} tokens\n".format(idx, len(tokenizer(doc.text)))
     31             + doc.text
     32         )
     34 nltk_splitter = NLTKTextSplitter()
---> 35 text_chunks = nltk_splitter.split_text(document.text)
     36 doc_chunks = [Document(text=t) for t in text_chunks]
     37 tokenizer = globals_helper.tokenizer

File ~/miniconda3-mac-silicon/envs/coreml_jupyter/lib/python3.10/site-packages/langchain/text_splitter.py:1008, in NLTKTextSplitter.split_text(self, text)
   1006 """Split incoming text and return chunks."""
   1007 # First we naively split the large input into a bunch of smaller ones.
-> 1008 splits = self._tokenizer(text)
   1009 return self._merge_splits(splits, self._separator)

File ~/miniconda3-mac-silicon/envs/coreml_jupyter/lib/python3.10/site-packages/nltk/tokenize/__init__.py:106, in sent_tokenize(text, language)
     96 def sent_tokenize(text, language="english"):
     97     """
     98     Return a sentence-tokenized copy of *text*,
     99     using NLTK's recommended sentence tokenizer
   (...)
    104     :param language: the model name in the Punkt corpus
    105     """
--> 106     tokenizer = load(f"tokenizers/punkt/{language}.pickle")
    107     return tokenizer.tokenize(text)

File ~/miniconda3-mac-silicon/envs/coreml_jupyter/lib/python3.10/site-packages/nltk/data.py:750, in load(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)
    747     print(f"<<Loading {resource_url}>>")
    749 # Load the resource.
--> 750 opened_resource = _open(resource_url)
    752 if format == "raw":
    753     resource_val = opened_resource.read()

File ~/miniconda3-mac-silicon/envs/coreml_jupyter/lib/python3.10/site-packages/nltk/data.py:876, in _open(resource_url)
    873 protocol, path_ = split_resource_url(resource_url)
    875 if protocol is None or protocol.lower() == "nltk":
--> 876     return find(path_, path + [""]).open()
    877 elif protocol.lower() == "file":
    878     # urllib might not use mode='rb', so handle this one ourselves:
    879     return find(path_, [""]).open()

File ~/miniconda3-mac-silicon/envs/coreml_jupyter/lib/python3.10/site-packages/nltk/data.py:583, in find(resource_name, paths)
    581 sep = "*" * 70
    582 resource_not_found = f"\n{sep}\n{msg}\n{sep}\n"
--> 583 raise LookupError(resource_not_found)
```

**Comment by ianscrivener** [comment]
Just a comment:
many of the Jupyter examples are advanced level and don't seem to return much to the user...
I'll try look around for some more _"I'm just. starting with llama_lindex"_ level examples

**Comment by ianscrivener** [comment]
OK, the other was "**user impatience**"
Jupyter is very subtle about telling you it "is processing"
.. while other apps have spinner.. Jupyter just puts an asterix next to the processing that is running...
![image](https://github.com/jerryjliu/llama_index/assets/163229/accd41e2-9ac2-4ebb-8542-e589c7472676)

**Comment by logan-markewich** [comment]
Sounds like you got it mostly figured out!

We are actually working on a giant docs refactor right now. Should be out in the next day or two. I hope you and others end up finding it helpful!

**Comment by ianscrivener** [comment]
thanks Logan, 

Yes.. the docs could do with some improvements. I have decades of development experiences.. but am new to ML. Many of the documents seems to be aimed at users with medium to advanced prior knowledge/experience in the space. For me that is not the case.

I like how langchain divides their docs into "Components" and "Use Cases".. this helps ease the learning curve and increase user/developer progress and satisfation.

Perhaps a glossary. For me also high level explanations help a lot. "Overall Concepts" Diagrams.

Keep up the great work 🏆

**Comment by logan-markewich** [comment]
@ianscrivener about to merge the refactor in a few minutes! I hope you like it 🙏 still room to improve, but I think the flow and organization is much better
