### ISSUE TITLE
[Question]: Is it possible to extract similarity values before sending prompt to gpt?

### ISSUE THREAD

**Issue by rmj1405** [jerryjliu/llama_index#6815]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

Hi! I'm fairly new to llamaindex, this is my first time working with it. I am trying to create a chatbot which uses base gpt-3.5-turbo's knowledge if it is unable to answer the question using the context I have provided. I have managed to achieve this using a custom prompt template and few shot learning. 

However, I find that I am using extra tokens in context which ends up getting wasted when gpt is not using it to construct the answer. The idea I have in mind is to create a custom parser that takes in my query text and can extract the embeddings similarity prior to sending the context to gpt-3.5-turbo(after receiving query embeddings from ada). If the similarity is below a threshold, say 0.85, I will reset the context to be 'Context is vague' or something similar. This will help me save a lot of tokens as I do not have to send the entire custom prompt each time. 

I am leaning towards extracting the similarity from the node post-processors but I am unsure where should this function be called i.e. as a argument to query_engine.query() or somewhere else. Hope my question is clear, I would be happy to provide more info/code if needed. Thank you!

**Comment by logan-markewich** [comment]
yea, node post-processors get called after retrieval, but before response synthesis

You could make a custom node postprocessor to filter out nodes, as well as add different nodes to return

```
query_engine = index.as_query_engine(node_postprocessors=[MyCustomProcessor()])
```

If you want to prevent calling gpt-3.5 altogether, you'll have to run the retrieval and response synthesis steps outside of the query engine

```
from llama_index import get_response_synthesizer
retriever = index.as_retriever()

response_synthesizer = get_response_synthesizer(response_mode="compact", service_context=service_context)

nodes = retriever.retrieve(query)

<insert filter logic>

response = response_synthesizer.synthesize(query, nodes=nodes)
```

**Comment by rmj1405** [comment]
Thank you so much, I managed to do it following the way you've provided!
