### ISSUE TITLE
[Bug]: async not work with stream and OpenAIAgent

### ISSUE THREAD

**Issue by dinhan92** [jerryjliu/llama_index#6835]
### Bug Description

So I have follow this docs with astream_chat and OpenAI Agent: https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent.html
And get this error: 'async for' requires an object with __aiter__ method, got coroutine

### Version

0.7.4

### Steps to Reproduce

``` python 
agent_stream = agent.astream_chat(input_text)

@stream_with_context
        async def generate():
            # for text in response:
            async for response in agent_stream:
                response_gen = response.response_gen

```

**Comment by logan-markewich** [comment]
@dinhan92 hmmm, either it's a difference in python versions when I initially wrote that, or something else.

In either case, I just tried this and it worked

```
async for response in await agent_stream:
    response_gen = response.response_gen
```

**Comment by dinhan92** [comment]
@logan-markewich thank you, it works !!! ^^
