### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate

### ISSUE THREAD

**Issue by vruti1121** [jerryjliu/llama_index#6844]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
context str = "abc"
query_str = "def"
    template = ("We have provided context information below. \n"
                "---------------------\n"
                f"{context_str}\n"
                "\n---------------------\n"
                f"Given this information, please answer the question: {query_str}\n")
    text_qa_template = Prompt(template=template)
    vector_store = WeaviateVectorStore(weaviate_client=client, index_name="LlamaIndex")
    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)

    query_engine = index.as_query_engine(text_qa_template=text_qa_template)
    response = str(query_engine.query(query_str))
```

I am getting the error below in the above snippet of code:
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
Invalid prompt schema; check for mismatched or missing input parameters. &#39;&#34;url&#34;&#39;
(type=value_error)

Can anyone please help me with the same? Thanks.

**Comment by logan-markewich** [comment]
@vruti1121 the `context_str` and `query_str` variables should not be formatted, they will be filled in automatically by llama-index. Leave them as string variables :)

**Comment by logan-markewich** [comment]
template = ("We have provided context information below. \n"
                "---------------------\n"
                "{context_str}\n"
                "\n---------------------\n"
                "Given this information, please answer the question: {query_str}\n")
