### ISSUE TITLE
I am having problems loading multiples indexes.

### ISSUE THREAD

**Issue by fpiantoni** [jerryjliu/llama_index#6852]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using llama_index==0.6.35 

I have created multiple GPTVectorStoreIndex with different data and i am trying to load all of them so i can make a query.

I have the following directory structure: 

![image](https://github.com/jerryjliu/llama_index/assets/47485566/d1a07093-619e-46da-9ee3-c9d1b21172d5)

And this is how i am loading it. I have never used llama_index before, i managed to load data from a single index but i am not being able to do it with multiple ones. 

def chatbot(input_text):
    print(input_text)
    storage_context = StorageContext.from_defaults(persist_dir='index/')
    print("I have passed the storage_context")
    print(storage_context) 
    promt_input = input_text
    try:
         # Specify the IDs of the indices you want to load
        index_ids = ['index1', 'index2', 'index3', 'index4']
        index = load_indices_from_storage(storage_context, index_ids=index_ids)  # Load the index
        print("I have passed the index")
        query_engine = index.as_query_engine(streaming=False, similarity_top_k=3)
        response = query_engine.query(promt_input)
        print(response.response)
        return response.response
    except Exception as e:
        print(f"Error: {e}")
        return None

Thanks in advance for the help. 

:)

**Comment by logan-markewich** [comment]
You can't load multiple indexes as a single index actually

You can either load them all individually (and use them in an agent as query tools, or more advanced query engine), or you can re-create them as a single index

**Comment by fpiantoni** [comment]
@logan-markewich Thanks for your response!!

When you say re-create them as a single index you mean re-training? I am not able to train it with all the data at the same time, because i exceed the OpenAI token limit, that's the reason i have divided the files in 4 different folders. 

Do you have an example on: "use them in an agent as query tools, or more advanced query engine"? 

Appreciate your time ;)

**Comment by logan-markewich** [comment]
@fpiantoni you could avoid token limits by either decreasing the batch size, or loading documents one at a time

Changing batch size (default is 10): https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#batch-size

Loading one at a time:
```python
import time

# throw in the service context or storage context as needed
index = VectorStoreIndex([], ...)
for doc in documents:
    index.insert(doc)
    time.sleep(1)
```


Advanced Query tools:
https://gpt-index.readthedocs.io/en/latest/examples/query_engine/sub_question_query_engine.html
https://gpt-index.readthedocs.io/en/latest/examples/query_engine/RouterQueryEngine.html
https://gpt-index.readthedocs.io/en/latest/examples/query_engine/RetrieverRouterQueryEngine.html


Agents
https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent_with_query_engine.html
https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent.html

**Comment by logan-markewich** [comment]
Going to close this for now, but definitely reach out here or on discord if you have more questions!
