### ISSUE TITLE
[Documentation]: LangChainEmbedding example code

### ISSUE THREAD

**Issue by ahayat16** [jerryjliu/llama_index#6862]
### Documentation Issue Description

For custom embeddings there might be a slight issue in the example code given with LangChain: the given code is

```
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LangchainEmbedding, ServiceContext

embed_model = LangchainEmbedding(
  HuggingFaceEmbeddings("sentence-transformers/all-mpnet-base-v2")
)
service_context = ServiceContext.from_defaults(embed_model=embed_model)

```
this would return an error (like __init__ has one argument, 2 are specified) as it should maybe be, given the current initialization of HuggingFaceEmbeddings:

```
embed_model = LangchainEmbedding(
  HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
)

```

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#custom-embedding-model

**Comment by jon-chuang** [comment]
Indeed, thanks. I also encountered this bug.

**Comment by logan-markewich** [comment]
whoops, will update
