### ISSUE TITLE
[Bug]: 'embedding' is not a valid TreeRetrieverMode

### ISSUE THREAD

**Issue by ZhuJD-China** [jerryjliu/llama_index#6863]
### Bug Description

# set Logging to DEBUG for more detailed outputs
query_engine = index.as_query_engine(retriever_mode="embedding")
response = query_engine.query(
    "What is the name of the professional women's basketball team in New York City?"
)

[Bug]: 'embedding' is not a valid TreeRetrieverMode

### Version

LlamaIndex 🦙 0.7.5

### Steps to Reproduce

TestNYC_Embeddings.ipynb

**Comment by logan-markewich** [comment]
hmm, it seems this was updated to "select_leaf_embedding" instead of "embedding"

Or, using the enum class

```python
from llama_iundex.indices.tree.base import TreeRetrieverMode
retriever_mode = TreeRetrieverMode.SELECT_LEAF_EMBEDDING
```
