### ISSUE TITLE
[Bug]: Metadata is missing from vector store results.

### ISSUE THREAD

**Issue by tszumowski** [jerryjliu/llama_index#6864]
### Bug Description

I am running `llama-index==0.7.5`. I noticed when I retrieve from a Pinecone Vector Store, no metadata is returned even though I have metadata in my Pinecone index. 

Stepping through the source code, I see this:
https://github.com/jerryjliu/llama_index/blame/main/llama_index/vector_stores/utils.py#L98

```
metadata = {}
for key, val in metadata.items():
...
``` 

It clears the metadata dictionary, and then loops over an empty dictionary.

This line was introduced in https://github.com/jerryjliu/llama_index/pull/6586.
In that PR I see:
> Massive change, appologies in advance.

Is it possible that is an accidental line?

When I revert to `llama-index-0.6.33` which is before this PR, I see metadata again. 

### Version

0.7.5

### Steps to Reproduce

1. Create a vector store that has metadata, in my case it is a Pinecone vector store with a Pinecone index with metadata
2. Instantiate vector and index
3. Query
4. Attempt to print sources

Pseudo-code:
```
    # Get API Keys from env
    pinecone_api_key = os.environ.get("PINECONE_API_KEY")

    # Initialize Pinecone
    pinecone.init(environment=pinecone_env_name, api_key=pinecone_api_key)
    pinecone_index = pinecone.Index(pinecone_index_name)

    # Initialize vector store
    vector_store = PineconeVectorStore(
        pinecone_index=pinecone_index, namespace=namespace
    )

    # Build index from existing vector store
    index = VectorStoreIndex.from_vector_store(
        vector_store
    )

    # Create engine
    query_engine = index.as_query_engine(similarity_top_k=top_k)

    response = query_engine.query(query)

    print("\nResponse:\n")
    print(response)

    print("\nSources:\n")
    sources = response.get_formatted_sources()
    print(sources)

```

**Comment by logan-markewich** [comment]
Thanks for debugging this. Going to investigate right now

**Comment by logan-markewich** [comment]
The function you pointed out is only used for legacy indexes (i.e. created before 0.6.34), but it is indeed a bug. Going to confirm the non-legacy version works as intended next

**Comment by logan-markewich** [comment]
Should be fixed. Thanks again for pointing this out!
