### ISSUE TITLE
[Question]: how to set as_query_engine model？ not working！

### ISSUE THREAD

**Issue by ZhuJD-China** [jerryjliu/llama_index#6902]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

# query_engine = index.as_query_engine()
query_engine = index.as_query_engine(streaming=True, language_model=OpenAI(model="gpt-3.5-turbo-0613"))

**Comment by logan-markewich** [comment]
Please see the documentation for setting up the LLM here
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-changing-the-underlying-llm
