### ISSUE TITLE
[Question]: why is llama-index using the wrong model and temperature?

### ISSUE THREAD

**Issue by thedoor76** [jerryjliu/llama_index#6909]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I feel this must be a goofy mistake on my part, but I cannot figure it out..

I am attempting to formulate an answer using qdrant vector store.

This is my method:
```
    def query(self, query, top_k=10, temp=0, model_name='gpt-3.5-turbo', filters=None, response_mode='compact'):
        vector_store = QdrantVectorStore(client=self._client, collection_name=self._collection)
        llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=temp, model_name=model_name))
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
        index = GPTVectorStoreIndex([], storage_context=storage_context, service_context=service_context)

        #setup filters
        flts = []        
        for key, value in filters.items():            
            flts.append(ExactMatchFilter(key=key, value=value))

        # https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/response_synthesizers/usage_pattern.html
        response_synthesizer = get_response_synthesizer(response_mode=response_mode, text_qa_template=self._PROMPT_TEXT_QA)
        query_engine = index.as_query_engine(filters=MetadataFilters(filters=flts), similarity_top_k=top_k, response_synthesizer=response_synthesizer, service_context=service_context)        

        results = query_engine.query(query)
```

This is how I invoke the method:
`answer = q.query(query=question, temp=0.25, model_name="gpt-3.5-turbo", filters=qdrant_filters, top_k=6, response_mode="compact")
`

But when I look at debug info, I see no mention of gpt-3.5-turbo or temp 0.25. Instead, I noticed that the following is used:
`"stream": false, "model": "text-davinci-003", "temperature": 0.0, "max_tokens": 675`

Can anyone point me in the right direction?

Thank you in advance.

**Comment by logan-markewich** [comment]
Since you are defining your own response synthesizer, you need to pass the service context into that as well

However, it's probably just easier to set a global service context

```python
from llama_index import set_global_service_context

set_global_service_context(service_context)
```

**Comment by thedoor76** [comment]
Thanks, @logan-markewich. That did the trick.
