### ISSUE TITLE
JS Version

### ISSUE THREAD

**Issue by tiagoefreitas** [jerryjliu/llama_index#691]
Langchain has langchainjs and they are almost done with supporting [Edge Functions like Cloudflare Workers or Vercel Edge](https://github.com/hwchase17/langchainjs/issues/62)

Any plans for LlamaIndexjs?

Would be awesome.

**Comment by ymansurozer** [comment]
Fully agree. A JS/TS version would be great. I have to say I am learning Python solely to use GPT Index. :)

**Comment by swk777** [comment]
I have started a project using Node.js and am seeking assistance to bring it to completion.
https://github.com/swk777/llama_index_node
