### ISSUE TITLE
[Bug (UX)]: Open AI key validation should happen earlier

### ISSUE THREAD

**Issue by jon-chuang** [jerryjliu/llama_index#6932]
### Bug Description

In my experience, it takes about 30s for the key validation to take place. I think we should validate on creation of the various classes. (Embedding, LLM)

### Version

master

### Steps to Reproduce

Create an embedding or LLM without key.

**Comment by jon-chuang** [comment]
I just tested this, it's only delayed on embeddings, not on llm.

**Comment by tyre** [comment]
Fixed in #6940, @jon-chuang I think you can close
