### ISSUE TITLE
[Question]: sql_query_engine in SQLAutoVectorQueryEngine tutorial is not defined

### ISSUE THREAD

**Issue by cjen07** [jerryjliu/llama_index#6975]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
in this [SQLAutoVectorQueryEngine tutorial](https://gpt-index.readthedocs.io/en/latest/examples/query_engine/SQLAutoVectorQueryEngine.html) the variable `sql_query_engine` is not defined, what is the best way to fix it?
Thanks in advance.

**Comment by cjen07** [comment]
hi @logan-markewich 
this simple fix doesn't work for me.
I got `ValueError: sql_query_tool.query_engine must be an instance of NLStructStoreQueryEngine` when executing this
`query_engine = SQLAutoVectorQueryEngine(
    sql_tool, vector_tool, service_context=service_context
)`
that's the reason I asked this question
my llama-index version is  `0.7.11.post1`

**Comment by logan-markewich** [comment]
Laaaame

I'll take another look and actually run the notebook this time
