### ISSUE TITLE
[Documentation]: Questions for RedisIndex

### ISSUE THREAD

**Issue by aetherwu** [jerryjliu/llama_index#6978]
### Documentation Issue Description

May I ask for more explaination for doc of RedisStore.
- How to load index in RedisVectorStore that had been loaded previously? (So that it avoids embedding and cost again.)
- Would SimpleDirectoryReader('data').load_data() do it automatically (Assume files are all unchange) 
- Or neither of it and VectorStoreIndex.from_documents do it, which means I need to implement this layer myself? 

I also suggest that add 'retriever = index.as_retriever()' part to this page, so that readers can understand its usage with flexibility.

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/RedisIndexDemo.html

**Comment by aetherwu** [comment]
I've tried something like this:
```
r = redis.Redis()
    check_exist = r.get(f"added:{index_name}")
    if check_exist:
        print(f"index {index_name} found.")
        vector_store = RedisVectorStore(
                index_name=index_name,
                index_prefix="llama",
                redis_url=redisURL,
                # overwrite=True,
            )
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        index = load_index_from_storage(storage_context=storage_context)
```

However it says:
>  index = load_index_from_storage(storage_context=storage_contex)
ValueError: No index in storage context, check if you specified the right persist_dir.

I've refered other source, but it did not apply to Redis:
https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/storage/save_load.html
```
storage_context = StorageContext.from_defaults(
    docstore=SimpleDocumentStore.from_persist_dir(persist_dir="<persist_dir>"),
    vector_store=SimpleVectorStore.from_persist_dir(persist_dir="<persist_dir>"),
    index_store=SimpleIndexStore.from_persist_dir(persist_dir="<persist_dir>"),
)
```

Also, RedisVectorStore seems do not have a smilar function called 'from_persist_dir' or 'from_persist'.

**Comment by aetherwu** [comment]
I've found code here and tried to put them togeher:
https://github.com/jerryjliu/llama_index/pull/6619

```
index_store = RedisIndexStore.from_host_and_port(
            host="localhost", port=6379, namespace="llama_index"
        )
        storage_context = StorageContext.from_defaults(vector_store=vector_store, index_store=index_store)
        index = load_index_from_storage(storage_context)
```
It still says 
>ValueError: No index in storage context, check if you specified the right persist_dir.

There I've traced to:
llama_index/indices/loading.py line 64:
> index_structs = storage_context.index_store.index_structs()

This line returns empty 'index_structs' as []

That's the furthest way I can explore on my own.

**Comment by aetherwu** [comment]
I've tried another piece here:
https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/vector_store_guide.html

```
vector_store = RedisVectorStore(
                index_name=index_name,
                index_prefix="llama",
                redis_url=redisURL,
                # overwrite=True,
            )

# ADD HERE:
index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
```

I was able to proceed to:
```
r = index.as_retriever()
response = r.retrieve(promt_text)
```

Then got a strange error from redis:
```
INFO:llama_index.vector_stores.redis:Querying index index_name
Querying index index_name
...
... return self._retrieve(str_or_query_bundle)
... query_result = self._vector_store.query(query, **self._kwargs)
... response = connection.read_response()
/redis/connection.py", line 905, in read_response
    raise response
redis.exceptions.ResponseError: Property `vector_score` not loaded nor in schema
```

**Comment by logan-markewich** [comment]
That final approach is the intended way to load a saved vector store

Not sure on that error though, that's a little weird 🤔

**Comment by aetherwu** [comment]
> That final approach is the intended way to load a saved vector store
> 
> Not sure on that error though, that's a little weird 🤔

Now everything is functioning normally, but I have no clue whatsoever.

**Comment by srishti1004** [comment]
any resolution to this vector_score problem 
despite following the same code its still showing the same error
raise response
redis.exceptions.ResponseError: Property `vector_score` not loaded nor in schema

**Comment by Entername1983** [comment]
I am also getting this error, very strange as the code ran fine, then I flushed the DB and recreated the index in exactly the same way and my next query threw that error.  FT.INFO reveals the a correct index.
