### ISSUE TITLE
[Question]: Truncation Issues 

### ISSUE THREAD

**Issue by azaiman1** [jerryjliu/llama_index#6986]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

I am currently using my own custom Embeddings to have weighted embeddings to feed into the database. However, when I try to to embed the data it seems as if the text is being truncated leading to many errors. I believe it is because of the ServiceContext truncating the text however there is nothing on what the default chunk size is. I am wondering how to make it so it does not truncate any text chunk

**Comment by logan-markewich** [comment]
Can you explain what kinds of errors you are getting?

The default chunk size is 1024

**Comment by azaiman1** [comment]
Thank you I believe it is fixed now but the service context seemed to truncate my text so I was unable to parse it to generate embeddings
