### ISSUE TITLE
How to do batch question answering?

### ISSUE THREAD

**Issue by snbhanja** [jerryjliu/llama_index#699]
Hi, I want to do multiple questions at a time. Like I will send a list of questions to GPTindex, and it should return answers for all questions. 

It is possible by directly using open ai api. Link: [Open ai Batch request](https://platform.openai.com/docs/guides/rate-limits/batching-requests).

But I want the same using Gptindex, is it possible?

**Comment by Disiok** [comment]
Hey @snbhanja, not possible via GPTIndex yet, but should be a simple change to support it.

**Comment by Disiok** [comment]
In the meanwhile, if speed is a concern, you could consider using the async query functionality! See https://github.com/jerryjliu/gpt_index/blob/main/examples/async/AsyncQueryDemo.ipynb for examples.

**Comment by snbhanja** [comment]
> In the meanwhile, if speed is a concern, you could consider using the async query functionality! See https://github.com/jerryjliu/gpt_index/blob/main/examples/async/AsyncQueryDemo.ipynb for examples.

Thank you @Disiok.
I am ok with async calls for now. :)

**Comment by DiaaAj** [comment]
I can work on this if still not assigned to anyone

**Comment by Disiok** [comment]
We don't have plans to support batched request at the query engine level in the near term.  Will close this for now.

**Comment by mad-lad1** [comment]
Are there any new updates on this? Is OpenAI Batch API supported?
