### ISSUE TITLE
[Documentation]: Please add the changelog to github releases

### ISSUE THREAD

**Issue by dukemagus** [jerryjliu/llama_index#6994]
### Documentation Issue Description

Right now, all the changes only appear in the readthedocs site (https://gpt-index.readthedocs.io/en/latest/development/changelog.html), but not in the actual repository.

It would be more acessible to see the changes on the same place where we check for updates on the repo. The changelog would also show up for anyone following the repository on github, making information more readily availiable.

### Documenation Link

https://github.com/jerryjliu/llama_index/releases

**Comment by Disiok** [comment]
The change log is actually at https://github.com/jerryjliu/llama_index/blob/main/CHANGELOG.md
