### ISSUE TITLE
[Feature Request]: Add column comments to SQLTable's table info?

### ISSUE THREAD

**Issue by radbrt** [jerryjliu/llama_index#6996]
### Feature Description

Expand SQLTable's `get_single_table_info` method to include any column comments in the template it creates.

### Reason

I made a very naive test here, which seems to work: https://github.com/radbrt/llama_index/blob/34d97505dcf7e13959744b5f1ca7fd1541a42ea0/llama_index/langchain_helpers/sql_wrapper.py#L54

Column comments are already available in the column inspector element. In the example I just added the description at the end, but I don't have opinions about the structure - there might be a better way. 

In any case, I am happy to give it a try and create a PR if this is interesting.

### Value of Feature

Some use column comments quite extensively, and column comments can add important information. Since dbt has a persist_docs option that writes metadata to column comments (and table comments as far as I know), this might be interesting for a number of teams.

One possible drawback of this is that the added descriptions adds a lot of text to the prompt, which might cause problems. Maybe making it an option when instantiating SQLTable is a way to square it?

**Comment by Disiok** [comment]
Thanks for the suggestion and would love to have a PR on this!
