### ISSUE TITLE
[Bug]: ResponseEvaluator and QueryResponseEvaluator Error

### ISSUE THREAD

**Issue by RobertPurdy** [jerryjliu/llama_index#7006]
### Bug Description

The ResponseEvaluator and QueryResponseEvaluator break on evaluation of the response from the chat engine. 

The response type of the chat engine has changed to AgentChatResponse which differs from the Response type of the query engine.

AgentChatResponse does not contain the property source_nodes. 

### Version

v0.7.11

### Steps to Reproduce

from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.evaluation import ResponseEvaluator, QueryResponseEvaluator

documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
query = "What did the author do growing up?"
chat_engine = index.as_chat_engine()
response = chat_engine.chat(query)
response_evaluator = ResponseEvaluator(service_context=index.service_context)
query_response_evaluator = QueryResponseEvaluator(service_context=index.service_context)
response_evaluation = response_evaluator.evaluate_source_nodes(response)
query_response_evaluation = query_response_evaluator.evaluate_source_nodes(query=query, response=response)
print(response_evaluation)
print(query_response_evaluation)

### Relevant Logs/Tracbacks

```shell
AttributeError: 'AgentChatResponse' object has no attribute 'source_nodes'
```

**Comment by Disiok** [comment]
I _think_ this should be fixed by https://github.com/jerryjliu/llama_index/pull/7029
