### ISSUE TITLE
[Question]: Similarity score of chroma: `1.0 - math.exp(-distance)`

### ISSUE THREAD

**Issue by obilixilido** [jerryjliu/llama_index#7007]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

https://github.com/jerryjliu/llama_index/blob/main/llama_index/vector_stores/chroma.py#L167

```
similarity_score = 1.0 - math.exp(-distance)
```

It looks like strange. 
If the distance equals to zero, the score will be zero. 
Why is this?

**Comment by kevon217** [comment]
I noticed this too. The closest matches via cosine similarity are given lower scores, but it should be the reverse.

**Comment by giacomolg** [comment]
Hi!

Also here to point out that `similarity_score` is wrong (in the sense that you want higher `distance` resulting in **lower** `similarity_score`).
Maybe we can simply have:
```python
similarity_score = math.exp(-distance)
```

Which, given `distance` is >=0, would make the `similarity_score` constrained from 0 to 1.

I noticed the function (https://www.desmos.com/calculator/wzotg2o0ul) falls to 0 pretty quickly, it might make sense to add a factor _f_:

$`e^{-\left(\frac{distance}{f}\right)}`$

See for example plot with _f_ = 16: https://www.desmos.com/calculator/xashz0yhos
