### ISSUE TITLE
how charge openai api url

### ISSUE THREAD

**Issue by zbsean** [jerryjliu/llama_index#701]
my app connect by proxy to openai,  so the openai addres not api.openai.com.  how charge it ?

**Comment by kenn** [comment]
Just set the `OPENAI_API_BASE` environment variable like this

```bash
OPENAI_API_BASE = 'https://domain.com/api'
```

**Comment by Disiok** [comment]
Duplicate of https://github.com/jerryjliu/llama_index/issues/640

**Comment by chrischjh** [comment]
> 

It works by setting env vars, but the env var has to be set before importing llama_index libs
