### ISSUE TITLE
Adding documents to a Composible graph after creating the graph

### ISSUE THREAD

**Issue by Samshive** [jerryjliu/llama_index#7012]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been able to create a composible graph over my documents. But I want to make it dynamic such that new documents can be added if needed, how best can I do this?

If I could get access to the index that is created over my documents it would be easy to add a node, but I don't know how to directly get access to the index. I also want to be able to change the default retrieval option for the index. I tried using a custom retriever as the documentation shows, but that only worked for the sub-indices, not the index itself. I tried passing the composible graph itself to the custom retriever, but that gave an error.

Please assist.

**Comment by logan-markewich** [comment]
There isn't a single index in a graph, just a collection of sub-indexes.

You'll have to add the document to the sub-index it belongs to, and possibly re-build the graph I think 🤔

**Comment by Samshive** [comment]
Ya, I figured that I could do that, but it seems like a wasteful way to do it. I know there is an underlying index that retrieves the sub-indices to query, so it makes sense that if I can access it I can treat it as a normal index and just add a node.

**Comment by logan-markewich** [comment]
But how would an insert function know which sub index to put the new document in? It wpuld almost have to use an LLM to decide?

Tbh if you just update the appropriate sub index, I don't think you have to rebuild unless you change the index summaries

**Comment by logan-markewich** [comment]
I would almost recommend using a data agent or sub question engine here instead of a composable index. The composable index hasn't been maintained as well, hence the janky UX

**Comment by Samshive** [comment]
> But how would an insert function know which sub index to put the new document in? It wpuld almost have to use an LLM to decide?
> 
> Tbh if you just update the appropriate sub index, I don't think you have to rebuild unless you change the index summaries

Am I understanding the composible graph incorrectly? I thought it was just a wrapper that takes in indexes of individual documents, treats them as nodes (hence why they need a summary), and creates a new index on top of them (defined by the index type that you specify).

So when you pass a query, it first identifies which document is the most appropriate to query and passes that query onto just that index. 

So my thinking is that there is an index in the back that you can add another node to as a sub-index. 

But ya, thanks for the feedback, I'll try some other options like sub-querying.
