### ISSUE TITLE
[Bug]: How to get a streaming response from a chat engine?

### ISSUE THREAD

**Issue by pors** [jerryjliu/llama_index#7016]
### Bug Description

I can't find a way to get streaming with chat working.

I tried this from the documentation:

```
chat_engine = index.as_chat_engine()
streaming_response = chat_engine.stream_chat("Tell me a joke.")
for token in streaming_response.response_gen:
    print(token, end="")
```

And got the following error: `NotImplementedError: stream_chat not implemented`

Also tried this (from an [example notebook](https://github.com/jerryjliu/llama_index/blob/main/docs/examples/customization/streaming/chat_engine_condense_question_stream_response.ipynb)):

```
chat_engine = index.as_chat_engine(chat_mode="condense_question", streaming=True)
response_stream = chat_engine.chat("What did Paul Graham do after YC?")
response_stream.print_response_stream()
```

And now I got this error: `AttributeError: 'AgentChatResponse' object has no attribute 'print_response_stream'`

### Version

0.7.11.post1

### Steps to Reproduce

See above.

**Comment by logan-markewich** [comment]
@pors are you using something other than openai? Streaming is implemented on the openai agent (the default chat engine), but if you are using another llm it will default to the react agent (which still needs to implement streaming)

The second thing is a small oversight, implementing that function for the agent response class now!

**Comment by pors** [comment]
@logan-markewich I am using the default LLM and I provided my openai API key as an env var. So yes, I use openai (the default). I am literally using the example from the docs.

**Comment by logan-markewich** [comment]
hmm, will try as well. One sec.

Also about to merge this https://github.com/jerryjliu/llama_index/pull/7018

**Comment by logan-markewich** [comment]
Ah, @pors make sure your LLM is set to gpt-3.5 or gpt-4 (the openai agent, which has streaming, requires one of these). We have been meaning to make gpt-3.5 the default, but migrating our prompt templates has taken time.

Will update the docs to make this clearer as well.

```
from llama_index.llms import OpenAI
from llama_index import ServiceContext, set_global_service_context

ctx = ServiceContext.from_defaults(llm=OpenAI(model="gpt-3.5-turbo", temperature=0))
set_global_service_context(ctx)

chat_engine = index.as_chat_engine()
response = chat_engine.stream_chat("Hello!")
for token in response.response_gen:
    print(token, end="")
```
<img width="1117" alt="image" src="https://github.com/jerryjliu/llama_index/assets/22285038/6ce216ac-70ed-4381-ac0c-28c88370bfa4">

**Comment by pors** [comment]
Cool!

**Comment by pors** [comment]
Yes! That does it, thanks!

**Comment by SuperEllipse** [comment]
Hi, does streaming work for llama2 on ollama as well ? I am trying to get the following to work using chainlit and ollama :
 ```
 logger.info(f"type :{type(response_stream.response_gen)}")
  logger.info(f"value :{response_stream.response_gen}")
    
  for token in response_stream.response_gen:
    logger.info("Inside Generator for loop")
    logger.info(f"TOKEN:{token}")
    await msg.stream_token(token)
  await msg.send()
```
It never gets into the for loop. The only messages logged are : 
```
2024-04-05 12:44:14 - type :<class 'generator'>
2024-04-05 12:44:14 - value :<generator object stream_chat_response_to_tokens.<locals>.gen at 0x7f2c1633fac0>
```

**Comment by logan-markewich** [comment]
Streaming works, but no idea with chairlift, never used it
