### ISSUE TITLE
[Question]: Can I print out the context window (after the knowledge-retrieval but before the query_engine's inference)?

### ISSUE THREAD

**Issue by Orescout** [jerryjliu/llama_index#7026]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

This would be useful in order to be able to debug whether (a) the knowledge doesn't end up in the context window in the first place or (b) the context window contains the right info, but just fails to be compiled into a great answer.  Does that make sense?

The printout would need to be in English, not numbers, ofc.

**Comment by Disiok** [comment]
To debug the retrieved context, you can look at `response.source_nodes`. Otherwise, you can use a debug handler to print out of the specific requests/responses: https://gpt-index.readthedocs.io/en/latest/examples/callbacks/LlamaDebugHandler.html
