### ISSUE TITLE
[Bug]: "Invalid OpenAI API key" error with valid Azure OpenAI key

### ISSUE THREAD

**Issue by gfrmin** [jerryjliu/llama_index#7042]
### Bug Description

Using AzureOpenAI works with version 0.7.9 but not 0.7.12. 

With the latter version, the following error occurs even though the key is perfectly fine.

### Version

0.7.12

### Steps to Reproduce

```
with llama_index.llms import AzureOpenAI

os.environ["OPENAI_API_KEY"] = xxxxxx

llm = AzureOpenAI(<usual arguments>)
```

### Relevant Logs/Tracbacks

```shell
ValueError: Invalid OpenAI API key.
API key should be of the format: "sk-" followed by 48 alphanumeric characters.
```

**Comment by dst1213** [comment]
+1

**Comment by hooyao** [comment]
This [commit](https://github.com/jerryjliu/llama_index/commit/1287a1d5439f58b2ec298baa73a35c3d7098dc01) breaks Azure support

**Comment by ian-fox** [comment]
I hit the same thing, working on a PR for it now.

**Comment by logan-markewich** [comment]
Thanks for the change @ian-fox 

Will cut a new release shortly
