### ISSUE TITLE
[Question]: Explainability of Vector Search

### ISSUE THREAD

**Issue by reichenbch** [jerryjliu/llama_index#7056]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can someone help me with understanding how does the vectorisation process works for Vector Store and Vector Search ? I tried looking at the documentation and code implementation but couldn't figure it out due to abstraction.

What I am looking for/at is the simplistic approach for building a RAG via embeddings of my choice and overall usage of embeddings of my choice for the Vector Storage and little verbose work on the implementation/running for the user.

**Comment by logan-markewich** [comment]
Basically, the embedding model transforms chunks of text into a list of numbers (i.e. an embedding vector)

When you query, an embedding vector is also generated for the query text. Then, cosine similarity is used to find the top k matching pieces of text compared to the query.

If you want to customize the embeddings model, you can set that in the service context
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations
