### ISSUE TITLE
[Bug]: chat_engine doesn't respected messages_to_prompt from the llm context

### ISSUE THREAD

**Issue by semoal** [jerryjliu/llama_index#7057]
### Bug Description

I have this LLM function:

```python
llm = Replicate(
    model="a16z-infra/llama13b-v2-chat:df7690f1994d94e96ad9d568eac121aecf50684a0b0963b25a41cc40061269e5",
    temperature=0.01,
    # override max tokens since it's interpreted
    # as context window instead of max tokens
    context_window=context_window,
    # override completion representation for llama 2
    completion_to_prompt=custom_completion_to_prompt,
    # if using llama 2 for data agents, also override the message representation
    messages_to_prompt=messages_to_prompt,
)
```

But when I use:

```python
index.as_chat_engine(
    chat_mode="context",
    vector_store=vector_store,
    service_context=service_context,
    verbose=True,
).chat("Who's the agent in the ocr.pdf file?")
```

My prompt is respected but the embed information is not appended to the prompt, but when I comment the lines from the llm `messages_to_prompt` and `completion_to_prompt`, the context is present. but the format is not correct, and Llama enters into an infinite loop- 

### Version

0.7.13

### Steps to Reproduce

```python


def custom_completion_to_prompt(completion: str, *args, **kwargs) -> str:
    print(args)
    print(kwargs)
    return completion_to_prompt(
        completion,
        system_prompt=(
            "You are a Q&A assistant. Your goal is to answer questions as "
            "accurately as possible in the instructions and context provided."
        ),
    )


# set context window size
context_window = 4096


llm = Replicate(
    model="a16z-infra/llama13b-v2-chat:df7690f1994d94e96ad9d568eac121aecf50684a0b0963b25a41cc40061269e5",
    temperature=0.01,
    # override max tokens since it's interpreted
    # as context window instead of max tokens
    context_window=context_window,
    # override completion representation for llama 2
    completion_to_prompt=custom_completion_to_prompt,
    # if using llama 2 for data agents, also override the message representation
    messages_to_prompt=messages_to_prompt,
)

service_context = ServiceContext.from_defaults(
    context_window=context_window,
    llm=llm,
    embed_model=embed_model,
)

set_global_service_context(service_context)
documents = SimpleDirectoryReader("./data").load_data()
index = VectorStoreIndex.from_documents(
    documents=documents,
    service_context=service_context,
    show_progress=True,
)

index.as_chat_engine(
    chat_mode="context",
    service_context=service_context,
    verbose=True,
).chat("Who's the agent in the ocr.pdf file?")

```

**Comment by semoal** [comment]
If some of you can give some hints or guidelines where to look at, I can try to fix it and contribute :)

**Comment by Disiok** [comment]
Ah, this might be confusing but the `ContextChatEngine` calls the `llm.chat` endpoint underneath, so `messages_to_prompt` is where you would customize things.

**Comment by semoal** [comment]
> I think we're currently having the same issue too. In the first chat with the engine, the context is not appended to the prompt, so what ends up happening is that the LLM just tries to answer the question directly without any context. Is this expected behaviour of `messages_to_prompt`?
> 
> Further, if I pass in a `system_prompt` into `index.as_chat_engine()`, this also doesn't get included into the first chat as a result (since it actually gets appended to the context [here](https://github.com/jerryjliu/llama_index/blob/644c034a249fa359181f8ebe988b8c2b93401814/llama_index/chat_engine/context.py#L152), and then it doesn't actually get added to the prompt somewhere in `messages_to_prompt`).
> 
> They do appear in the second chat though, so this feels like a bug and not expected.
> 
> @rwood-97 and I have been trying to fix this, so happy to make a PR for this.

That would be amazing, happy to review it when it's ready; feel free to ping me!

**Comment by rchan26** [comment]
@semoal I've made a PR in #7597. I'm not sure if we do have the same issue actually, but do let me know how this works with what you're trying to do.

**Comment by logan-markewich** [comment]
This should be fixed, thanks @rchan26 !
