### ISSUE TITLE
[Question]: Support for function call api for OpenAI 

### ISSUE THREAD

**Issue by h1Logic** [jerryjliu/llama_index#7060]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

As recently function call api was added for openai api (https://openai.com/blog/function-calling-and-other-api-updates) i was trying to integrate such approach (among other things it allows for output parsing, which may be an alternative for existing apporach for output parsers). Unfortunately as far as i can tell it's impossible for current moment - the issue is that here (https://github.com/jerryjliu/llama_index/blob/main/llama_index/llm_predictor/base.py#L118) only `chat_response.message.content` is checked, but when using function call api it's possible that the `chat_response.message.content` will be `None` and the actual response will be found here `chat_response.message.additional_kwargs['function_call']['arguments']` - as of current state this is missing 
```
output = chat_response.message.content or ""
```

Solution:
As for solution that would be bullet proof i think the most feasible one would be to return raw chat_response instead of `content` - since `raw` response is already in `chat_response` but in the next line there is extraction which commits function call api entirely.

Btw. thanks for great work at this package!

**Comment by logan-markewich** [comment]
We support the function calling api in a ton of our stuff.

If you want access using the low-level LLM object, check out how it works in the OpenAIAgent here 
https://github.com/jerryjliu/llama_index/blob/779e7fc56cfff1edcd926c22a296d4813ba76117/llama_index/agent/openai_agent.py#L114C8-L114C8

**Comment by h1Logic** [comment]
Thanks for such quick response - it seems to solve the issue ;) 
I must have missed `Agent` abstraction - there was a lot of going on around `llm` interfaces lately.

Issue to close

**Comment by logan-markewich** [comment]
Haha I agree, easy to miss! Glad I could help
