### ISSUE TITLE
[Feature Request]: Return doc_id along with source_nodes

### ISSUE THREAD

**Issue by hwuiwon** [jerryjliu/llama_index#7066]
### Feature Description

Currently, when we make ComposableGraph from existing indices, and if we query, we can see the source_nodes, but we need to go through additional steps to see what doc_id that source_nodes belong to. It will be a good idea to return a source_doc_ids to see which document the answer is from.

### Value of Feature

Can clearly acknowledge which document the response has been created from.

**Comment by Disiok** [comment]
for the `additional steps`, do you mean just calling the appropriate property on the source nodes? If so, I think the usability improvement is small and we probably won't prioritize for now.
