### ISSUE TITLE
[Feature Request]: OpenAI agent refactor

### ISSUE THREAD

**Issue by SlapDrone** [jerryjliu/llama_index#7075]
### Feature Description

Following a discussion with @logan-markewich in #6985, it was suggested a refactor to the OpenAI agent to reduce code duplication and improve clarity would be a necessary precondition for further work to extend its functionality.

### Reason

(see #6985)

> Although I'm also hesitant to add more functions to the interface, because right now the main four (chat/achat/stream_chat/astream_chat) are all mostly duplicates of each-other.

> Tbh, if you are interested in contributing here and working on this, there's a few issues/tech debt that I'd love to solve and just haven't had time to look at:

>    **major code duplication across 4 functions (and possibly 5-6 with these suggestions!)**
    ~~callbacks un-aware of parents (and also not quite working for async, ha!)~~

### Value of Feature

> I think if either of those are solved, then adding intermediate responses should be a little more straightforward/less scary 💪🏻

**Comment by Disiok** [comment]
Thanks! Really appreciate the help here in refactoring!

**Comment by logan-markewich** [comment]
Thanks a ton @SlapDrone this looks great to far!
