### ISSUE TITLE
Doc Typo in guides/index_guide.md

### ISSUE THREAD

**Issue by psk907** [jerryjliu/llama_index#710]
I've spotted what might be a typo in the documentation. Have a look at the screenshot below -
![image](https://user-images.githubusercontent.com/37346450/224530719-ef1aa0b3-6f75-47be-a5e5-41d4368a8e35.png)

> The phrase should go something like "LlamaIndex simply **loads** all Nodes".

You can find this at [https://gpt-index.readthedocs.io/en/latest/guides/index_guide.html#querying](https://gpt-index.readthedocs.io/en/latest/guides/index_guide.html#querying).

The fix would be targeting the file - [docs/guides/index_guide.md](https://github.com/jerryjliu/gpt_index/blob/main/docs/guides/index_guide.md)

**Comment by jerryjliu** [comment]
Closed by #711
