### ISSUE TITLE
[Bug]: Node IDs retrieved by callback are not found in docstore/ vector store/ index store

### ISSUE THREAD

**Issue by axiomofjoy** [jerryjliu/llama_index#7101]
### Bug Description

While building a callback handler, the node IDs retrieved from the retrieval callback hook don't match any of the node IDs in the docstore/ vector store/ index store. I expected these node IDs to be the same as the IDs in the storage context. Is that a correct assumption?

As additional context, I would ideally like the node IDs collected by the callback at query time to match the IDs in the underlying vector store/ vector DB.

### Version

latest `main` (773a6834)

### Steps to Reproduce

Run the notebook reproducing the issue [here](https://colab.research.google.com/drive/1ssL2FGI_ZLagmX6up4UKueeEYW8SkGbR?usp=sharing).

### Relevant Logs/Tracbacks

```shell
n/a
```

**Comment by logan-markewich** [comment]
@axiomofjoy can you provide a quick code sample? Are you referring to the embedding callback event?

**Comment by logan-markewich** [comment]
@axiomofjoy I noticed you are loading an index. Was this index created with an older version of llama-index?

I tried to re-create the issue with a fresh index and was unable to do so.

I suspect our code for loading legacy indexes (i.e. pre V0.7.0) has a slight bug for node ids 🤔

**Comment by axiomofjoy** [comment]
@logan-markewich The index is indeed pretty old. I'll try re-indexing and let you know if that works.

**Comment by axiomofjoy** [comment]
@logan-markewich I've confirmed that this issue is resolved by rebuilding the index. I'm going to open up a PR to change the `OpenInferenceCallbackHandler` to use node IDs rather than hashes. Thanks for the help!
