### ISSUE TITLE
[Bug]: Async prediction with ChatOpenAI worked until 0.6.38, but does not work after 0.7.0

### ISSUE THREAD

**Issue by apptaro** [jerryjliu/llama_index#7118]
### Bug Description

LLMPredictor.apredict with ChatOpenAI works asynchronously until 0.6.38, but it works synchronously from 0.7.0 to 0.7.16.

### Version

0.7.16

### Steps to Reproduce

Code:
```
import asyncio
from typing import Tuple
from langchain.chat_models import ChatOpenAI
from llama_index import LLMPredictor, Prompt

llm_predictor = LLMPredictor(ChatOpenAI(temperature = 0))

async def task1():
  print("task1")
  response = await llm_predictor.apredict(Prompt(f"who wrote The Great Gatsby"))
  print(response[0] if isinstance(response, Tuple) else response)

async def task2():
  print("task2")
  response = await llm_predictor.apredict(Prompt("who wrote Romeo and Juliet?"))
  print(response[0] if isinstance(response, Tuple) else response)

async def do_tasks():
  await asyncio.gather(*[task1(), task2()])

#asyncio.run(do_tasks()) # for python script
await do_tasks() # type: ignore (for jupyter)
```

Run it on 0.6.38, the result is:
```
task1
task2
The Great Gatsby was written by F. Scott Fitzgerald.
William Shakespeare wrote Romeo and Juliet.
```

Run it on 0.7.0 - 0.7.16, the result is:
```
task1
The Great Gatsby was written by F. Scott Fitzgerald.
task2
William Shakespeare wrote Romeo and Juliet.
```

**Comment by apptaro** [comment]
see below:
https://github.com/jerryjliu/llama_index/blob/main/llama_index/llms/langchain.py#L105

**Comment by logan-markewich** [comment]
@apptaro try using our LLM integration, not langchain, for a better native experience

```
from llama_index.llms import OpenAI

llm_predictor = LLMPredictor(OpenAI(model="gpt-3.5-turbo", temperature=0))
```

In fact, you don't even need the LLMPredictor anymore. You can use the LLM object directly.
https://gpt-index.readthedocs.io/en/latest/examples/llm/openai.html

```
service_context = ServiceContext.from_defaults(llm=llm)
```

But yea, the langchain llm class should at least be trying to use the async method, if it's implemented, I agree.

**Comment by apptaro** [comment]
@logan-markewich Hi! Thank you for your reply. I will try using llama_index.llms.OpenAI.

I leave this bug open as this bug is still a bug.
