### ISSUE TITLE
[Bug]: Keep getting OpenApi key requested

### ISSUE THREAD

**Issue by ChezzPlaya** [jerryjliu/llama_index#7120]
### Bug Description

Eventhough I provided the local embedding model, I keep getting API key request.

Why?

```
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.

service_context = ServiceContext.from_defaults(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys
```

### Version

0.7.16

### Steps to Reproduce

```
import os
import chromadb
from llama_index import (
    LangchainEmbedding,
    SimpleDirectoryReader,
    ServiceContext,
    StorageContext,
    VectorStoreIndex,
)
from llama_index.vector_stores import ChromaVectorStore
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import set_global_service_context


def main():
    # construct embed model
    embed_model = LangchainEmbedding(
        HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
    )

    service_context = ServiceContext.from_defaults(
        chunk_overlap=200, chunk_size=1000, embed_model=embed_model
    )
    set_global_service_context(service_context=service_context)

    # get current directory based on the file location
    current_directory = os.path.dirname(os.path.abspath(__file__))

    documents = SimpleDirectoryReader(
        os.path.join(current_directory, "resources")
    ).load_data()

    db = chromadb.PersistentClient(path="./chroma_db")
    chroma_collection = db.get_or_create_collection("pdf_resources")
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)

    index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)

    query_engine = index.as_query_engine()
    response = query_engine.query("Set the warning of the acoustic warning to 5")
    print(response)


# main
if __name__ == "__main__":
    main()
```

**Comment by semoal** [comment]
You're not specifying any LLM, so by default is OpenAI.
```python
llm = CustomLLM()
 service_context = ServiceContext.from_defaults(
        llm=llm,
        embed_model=embed_model,
    )
```

**Comment by ChezzPlaya** [comment]
Fine, but why do I have to provide a LLM, even though I don't intent to use it? I just want to store indexed docs...
Also, the default llm value is None, why it's not set explicitely to OpenAI LLm?

**Comment by semoal** [comment]
But if you don't provide an LLM how do you expect to ask in natural language questions about that indexed docs? Probably I'm wrong but I think that's impossible

**Comment by ChezzPlaya** [comment]
Because I just want to persist the data. And querying them using another lib in a different setting, e.g. microservice. Basically the steps are:

1. Indexing Data using LLama Index
2. Load data somewhere else and run query -> Here of course I would then need an llm

Also, why everyone puts OpenAI as default in various frameworks related to LLM? I'd personally prefer Huggingface llama based finetuned model as default... But, thats only my personal preference...

**Comment by logan-markewich** [comment]
Huggingface models are .... not great at being used with llama-index. I think the only one worth using would be llama2 right now. You want users to have a good first experience with the defaults though, and OpenAI provides that.

Once we have a llama.cpp integration, we can make it easy to enable at least!

In the meantime, just set your openai key to be something random, or set the `llm` in the service context to be a random string, or anything other than `None` so that it doesn't default to openai
