### ISSUE TITLE
[Bug]: Pydantic validator fails for valid configurations of AzureOpenAI

### ISSUE THREAD

**Issue by proschowsky** [jerryjliu/llama_index#7121]
### Bug Description

AzureOpenAI from llama_index.llms does not work with Azure AD authentication. 

When authentication to Azure with AD, the api_type must be set to "azure_ad".
The validator only accepts "azure"

Valid values of the api_type is "azure", "azure_ad", "azuread"

Error:

```
pydantic.error_wrappers.ValidationError: 1 validation error for AzureOpenAI
__root__
  You must set OPENAI_API_TYPE to `azure` for Azure OpenAI. (type=value_error)
```

### Version

0.7.16

### Steps to Reproduce

Example of script that use Azure AD

```
import openai
from llama_index.llms import AzureOpenAI

# config open ai
openai.api_type = "azure_ad"
openai.api_key = 123456
...

llm = AzureOpenAI(model="gpt-35-turbo", engine="gpt-35-turbo", temperature=0.2)

```

**Comment by logan-markewich** [comment]
@proschowsky thanks for pointing this out, I can merge an update shortly
