### ISSUE TITLE
[Bug]: RouterQueryEngine not detecting AzureOpenAi ServiceContext

### ISSUE THREAD

**Issue by Matt-Scheetz** [jerryjliu/llama_index#7126]
### Bug Description

I'm testing out using RouterQueryEngine's example from [the docs](https://gpt-index.readthedocs.io/en/latest/examples/query_engine/RouterQueryEngine.html).

I've set my service context:
```
    def init_skds(self):
        self.prompt_helper = PromptHelper(self.max_input_size, 
                                          self.num_output, 
                                          chunk_overlap_ratio=self.overlap_ratio)

        self.llm=AzureChatOpenAI(temperature=self.temperature, 
                                 deployment_name=self.deployment_name,
                                 model_name=self.deployment_model, 
                                 max_tokens=self.num_output,
                                 openai_api_version=self.ai_api_version)

        self.llm_predictor = LLMPredictor(self.llm)

        self.aiEmbedding = OpenAIEmbeddings(model=self.embedding_model,
                                            deployment=self.embedding_deployment,
                                            chunk_size=self.embedding_chunk_size)

        self.embedding = LangchainEmbedding(self.aiEmbedding)

        self.service_context = ServiceContext.from_defaults(llm_predictor=self.llm_predictor, 
                                                            prompt_helper=self.prompt_helper,
                                                            embed_model=self.embedding)

        set_global_service_context(self.service_context)
```
After initializing my indexes, I'm creating the RouterQueryEngine:
```
    def _get_multi_query_engine(self):
        list_qe = self._get_list_query_engine()
        vector_qe = self._get_vector_query_engine()
        
        filenames = self.indexed_filenames_v2()
        filenames_str = ','.join(filenames)

        list_tool = QueryEngineTool.from_defaults(
            query_engine=list_qe,
            description=f"Useful for summarization questions related to {filenames_str}"
        )

        vector_tool = QueryEngineTool.from_defaults(
            query_engine=vector_qe,
            description=f"Useful for retrieveing specific context from {filenames_str}"
        )

        try:
            query_engine = RouterQueryEngine(
                selector=PydanticSingleSelector.from_defaults(),
                query_engine_tools=[
                    list_tool,
                    vector_tool
                ],
                service_context=self.service_context
            )

            return query_engine
        except Exception as e:
            logging.error(e)
            raise

```

Here is the error that is being thrown when i run `query_engine.query(input_text)`:

```
    def multi_chat(self, input_text: str):
        query_engine = self._get_multi_query_engine()

        try:
            response = query_engine.query(input_text)

            return response
        except Exception as e:
            logging.error(e)
            raise
```

> No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

While debugging, I can expand my `query_engine.service_context` and see my AzureOpenAi config settings for both the `llm` and `llm_predictor`

I'm currently running similar code only using a VectorStoreIndex and a regular query_engine; this error is not getting thrown.

### Version

0.7.16

### Steps to Reproduce

* Initialize indexes: ListIndex + VectorStorageIndex
* Create RouterQueryEngine
* Query RouterQueryEngine

**Comment by logan-markewich** [comment]
Hmm, it looks like the pydantic single selector does not use the service context.

As a work-around, you can pass the `llm` object directly into the selector. Since you are using the Langchain LLM object and not our azure LLM, you'll need to wrap it with a langchain wrapper

```python
from llama_index.llms import LangChainLLM

...
selector=PydanticSingleSelector.from_defaults(llm=LangChainLLM(self.llm))
...
```

**Comment by logan-markewich** [comment]
As a note for the future too, here's an example of using our `AzureOpenAI` LLM class https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html

**Comment by Matt-Scheetz** [comment]
Implemented both the above suggestions
1. passing the llm into the selector seems to work on the initial issue:
``` python
selector = PydanticSingleSelector.from_defaults(llm=self.llm)
query_engine = RouterQueryEngine(
  selector=selector,
  query_engine_tools=[
    list_tool,
    vector_tool
  ]
```

2. using llama's Azure llm class
``` python
self.llm=AzureOpenAI(
  engine=self.deployment_name,
  model=self.deployment_model)
```

Now when querying, i'm getting the following error:

> 'Unrecognized request arguments supplied: function_call, functions'

``` python
response = query_engine.query(input_text)
```

> [2023-08-03T15:29:40.513Z] message='Request to OpenAI API' method=post path=https://az-resource.openai.azure.com//openai/deployments/ai-deployment/chat/completions?api-version=2023-06-01-preview
[2023-08-03T15:29:40.513Z] api_version=2023-06-01-preview data='{"messages": [{"role": "user", "content": "Some choices are given below. It is provided in a numbered list (1 to 2),where each item in the list corresponds to a summary.\\n---------------------\\n(1) Useful for summarization questions related to Indexed_File.docx\\n\\n(2) Useful for retrieveing specific context from Indexed_File.docx\\n---------------------\\nUsing only the choices above and not prior knowledge, generate the selection object and reason that is most relevant to the question: \'what is the total amount?\'\\n"}], "stream": false, "temperature": 0.0, "max_tokens": null, "functions": [{"name": "SingleSelection", "description": "A single selection of a choice.", "parameters": {"title": "SingleSelection", "description": "A single selection of a choice.", "type": "object", "properties": {"index": {"title": "Index", "type": "integer"}, "reason": {"title": "Reason", "type": "string"}}, "required": ["index", "reason"]}}], "function_call": {"name": "SingleSelection"}}' message='Post details'
[2023-08-03T15:29:40.517Z] https://az-resource.openai.azure.com:443 "POST //openai/deployments/ai-deployment/chat/completions?api-version=2023-06-01-preview HTTP/1.1" 400 178
[2023-08-03T15:29:40.519Z] message='OpenAI API response' path=https://az-resource.openai.azure.com//openai/deployments/ai-deployment/chat/completions?api-version=2023-06-01-preview processing_ms=11.9456 request_id=082a7db8-66e6-48d3-96da-04d007285c52 response_code=400
[2023-08-03T15:29:40.521Z] error_code=None error_message='Unrecognized request arguments supplied: function_call, functions' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-08-03T15:29:40.523Z] Unrecognized request arguments supplied: function_call, functions

**Comment by Matt-Scheetz** [comment]
I've found the issue; there were 2:
1. Update open ai api version `OPENAI_API_VERSION="2023-07-01-preview"`
2. Update my Azure OpenAI deployment of `gpt-35-turbo` Model version from `0301` to `0613`
