### ISSUE TITLE
[Bug]: llama_index.llms.OpenAI does not use api_type & api_key passed in

### ISSUE THREAD

**Issue by apptaro** [jerryjliu/llama_index#7132]
### Bug Description

I don't want to set OPENAI_API_TYPE & OPENAI_API_KEY environment variables because I use multiple ChatGPTs.
So I do this:
```
llm = OpenAI(api_type = "open_ai", api_key = "sk-xxx")
llm.chat(...)
```
Then it raises `openai.error.AuthenticationError: No API key provided` error.

Actually, this works:
```
llm = OpenAI(api_type = "open_ai", api_key = "sk-xxx", additional_kwargs = { "api_type": "open_ai", "api_key": "sk-xxx" })
llm.chat(...)
```

But it's redundant. 

This code checks top-level parameters, so I suppose you don't have to use additional_kwargs, correct?
https://github.com/jerryjliu/llama_index/blob/535a05fdabf87c2a89be25a0eb8b433498d7c1f1/llama_index/llms/openai.py#L47

### Version

0.7.17

### Steps to Reproduce

```
from llama_index.llms import OpenAI
from llama_index.llms.base import ChatMessage
llm = OpenAI(api_type = "open_ai", api_key = "sk-xxx")
llm.chat([ChatMessage(content = "Who wrote Romeo and Juliet?")])
```

**Do not set OpenAI environment variables!**

**Comment by sourabhdesai** [comment]
Thanks for raising this!

FWIW the `api_key` parameter was recently re-added to the constructor's kwargs list in [this PR](https://github.com/jerryjliu/llama_index/pull/7263).

It still doesn't have the `api_type` kwarg parameter, I can try adding that too soon.
