### ISSUE TITLE
[Question]: openai.Getting error.InvalidRequestError on SubQuestionQueryEngine

### ISSUE THREAD

**Issue by Yackadaisical** [jerryjliu/llama_index#7133]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My set up works for all other kinds of queries I been working on, but today I was trying to add SubQuestionQueryEngine to my code, and keep getting this error:

openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

This is basic outline of my code:

```
llm = AzureOpenAI(engine="try2", model="gpt-3.5-turbo-16k", temperature=0.2)

embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="embedding_try1",
        openai_api_key=openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_type=openai.api_type,
        openai_api_version=openai.api_version,
    ),
    embed_batch_size=1,
)

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embedding_llm,
)

set_global_service_context(service_context)

storage_context = StorageContext.from_defaults(
    persist_dir="docs_index_storage"
)

vector_query_engine = load_index_from_storage(
    storage_context=storage_context, 
    service_context=service_context
    ).as_query_engine()

query_engine_tools = [
    QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name="tissue_research", description="Provide information on consumer tissue paper."
        ),
    ),
]

query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context
)

answer = query_engine.query("What is the latest trends on tissue paper")

print(answer.get_formatted_sources())
```

Whenever I run .query it would raise openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

**Comment by Yackadaisical** [comment]
Was using gpt-3.5-turbo-16k,, changed to gpt-3.5-turbo, but still giving me the same error. 
Also am using the exact same initialization as the SubQuestionQueryEngine documentation, the only difference is that I'm using Azure OpenAI LLM and embedding

**Comment by Yackadaisical** [comment]
Moving to Bug: https://github.com/jerryjliu/llama_index/issues/7167#issue-1838062488

**Comment by Shubham-Sahay** [comment]
@Yackadaisical did your issue got resolved as i am facing same issue.
