### ISSUE TITLE
[Question]:cannot import name 'GPTFaissIndex' from 'llama_index'

### ISSUE THREAD

**Issue by bankshotbandwidth** [jerryjliu/llama_index#7135]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have installed llama_index, but the process of import GPTFaissIndex keeps reporting [cannot import name 'GPTFaissIndex' from 'llama_index']

**Comment by logan-markewich** [comment]
`GPTFaissIndex` is a pretty old name/import

See the latest guide here: https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/FaissIndexDemo.ipynb
