### ISSUE TITLE
llama_index.text_splitter is not available 

### ISSUE THREAD

**Issue by oroojlooy** [jerryjliu/llama_index#7156]
### Bug Description

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[26], line 1
----> 1 from llama_index.text_splitter import SentenceSplitter

ModuleNotFoundError: No module named 'llama_index.text_splitter'

### Version

llama_index-0.7.18

### Steps to Reproduce

from llama_index.text_splitter import SentenceSplitter

**Comment by logan-markewich** [comment]
@oroojlooy sorry about that, the docs updated before the release

Should be fixed with v0.7.19

We also updated the docs to point to the latest `stable` release, rather than `latest`
