### ISSUE TITLE
[Question]: How to use custom chat history with reactChatEngine

### ISSUE THREAD

**Issue by AchintyaX** [jerryjliu/llama_index#7173]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to build a chatbot, for managing concurrent chat sessions I am using redis to store the chat history.
I was able to use `CondenseQuestionChatEngine` with custom chat history, but I wanted to reactChatEngine since in my experimentation it is generally performs better. 
I couldn't find any ways to do it in the documentation and on discord

**Comment by logan-markewich** [comment]
The above bot is correct

You can also just pass in the custom chat history when you create the chat engine as well

```
chat_engine = index.as_chat_engine(chat_mode="react", chat_history=chat_history)
```

**Comment by casezhao** [comment]
The bot answer is incorrect.  I searched the source code globally, It seems that this function is not implemented. 
I have a similar problem to yours, except I'm using mongo to store the chat history. If your server have many different chat session, may be need implement this function by ourself.

**Comment by logan-markewich** [comment]
@casezhao it's correct? The chat buffer code is here
https://github.com/jerryjliu/llama_index/blob/main/llama_index/memory/chat_memory_buffer.py

**Comment by casezhao** [comment]
`def as_chat_engine(
        self, chat_mode: ChatMode = ChatMode.BEST, **kwargs: Any
    ) -> BaseChatEngine:
        query_engine = self.as_query_engine(**kwargs)
        if "service_context" not in kwargs:
            kwargs["service_context"] = self._service_context

        # resolve chat mode
        if chat_mode == ChatMode.BEST:
            # get LLM
            service_context = cast(ServiceContext, kwargs["service_context"])
            llm = service_context.llm

            if isinstance(llm, OpenAI) and is_function_calling_model(llm.model):
                chat_mode = ChatMode.OPENAI
            else:
                chat_mode = ChatMode.REACT

        if chat_mode == ChatMode.CONDENSE_QUESTION:
            # NOTE: lazy import
            from llama_index.chat_engine import CondenseQuestionChatEngine

            return CondenseQuestionChatEngine.from_defaults(
                query_engine=query_engine,
                **kwargs,
            )
        elif chat_mode == ChatMode.CONTEXT:
            from llama_index.chat_engine import ContextChatEngine

            return ContextChatEngine.from_defaults(
                retriever=self.as_retriever(**kwargs),
                **kwargs,
            )

        elif chat_mode in [ChatMode.REACT, ChatMode.OPENAI]:
            # NOTE: lazy import
            from llama_index.agent import OpenAIAgent, ReActAgent
            from llama_index.tools.query_engine import QueryEngineTool

            # convert query engine to tool
            query_engine_tool = QueryEngineTool.from_defaults(query_engine=query_engine)

            # get LLM
            service_context = cast(ServiceContext, kwargs.pop("service_context"))
            llm = service_context.llm

            if chat_mode == ChatMode.REACT:
                return ReActAgent.from_tools(
                    tools=[query_engine_tool],
                    llm=llm,
                    **kwargs,
                )
            elif chat_mode == ChatMode.OPENAI:
                return OpenAIAgent.from_tools(
                    tools=[query_engine_tool],
                    llm=llm,
                    **kwargs,
                )
            else:
                raise ValueError(f"Unknown chat mode: {chat_mode}")
        else:
            raise ValueError(f"Unknown chat mode: {chat_mode}")`
I found the solution. The actual source code returns a ReActAgent, and its from_tools will receive a chat_history, so just pass it here.

**Comment by casezhao** [comment]
> @casezhao it's correct? The chat buffer code is here https://github.com/jerryjliu/llama_index/blob/main/llama_index/memory/chat_memory_buffer.py

I know, I guess he wants to implement a multi-user server, and the chat history is stored in the database.
