### ISSUE TITLE
[Bug]: ValueError: "GPT4AllEmbeddings" object has no field "callback_manager"

### ISSUE THREAD

**Issue by Ashish5869** [jerryjliu/llama_index#7176]
### Bug Description

I have downloaded gpt4all model. Using langchain gpt4all embedding and llm, when defining service context, i am defining embed model. then i am getting error that embed_model doesn't have callback manager.
Please look into this. 
Am i doing something wrong?

### Version

0.7.20

### Steps to Reproduce

from llama_index import (
    LLMPredictor, 
    ServiceContext,
    set_global_service_context
)
from langchain.llms import GPT4All
from langchain.embeddings import GPT4AllEmbeddings
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

   
callbacks = [StreamingStdOutCallbackHandler()]
local_path = "/path/to/gpt4 model/llama-2-7b-chat.ggmlv3.q4_0.bin"

llm = GPT4All(model=local_path, callbacks=callbacks, backend="gptj", verbose=True)

service_context = ServiceContext.from_defaults(
    llm_predictor=LLMPredictor(llm=llm), 
    embed_model=GPT4AllEmbeddings()
)

OUTPUT:
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_83194/1998556855.py in <module>
     53 # )
     54 
---> 55 service_context = ServiceContext.from_defaults(
     56     llm_predictor=llm_predictor,

~/anaconda3/lib/python3.10/site-packages/llama_index/indices/service_context.py in from_defaults(cls, llm_predictor, llm, prompt_helper, embed_model, node_parser, llama_logger, callback_manager, chunk_size, chunk_overlap, context_window, num_output, chunk_size_limit)
    163         # NOTE: the embed_model isn't used in all indices
    164         embed_model = embed_model or OpenAIEmbedding()
--> 165         embed_model.callback_manager = callback_manager
    166 
    167         prompt_helper = prompt_helper or _get_default_prompt_helper(

~/.local/lib/python3.10/site-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__setattr__()

ValueError: "GPT4AllEmbeddings" object has no field "callback_manager"

# Commented the line 165 in docs

embed_model = embed_model or OpenAIEmbedding()
- 165 embed_model.callback_manager = callback_manager

# after commented 165 line. Got error while indexing
index = GPTVectorStoreIndex.from_documents(
    document2,
    storage_context=storage_context,
    service_context=service_context
)

# Error
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_92161/889443836.py in <module>
     22 ]
     23 
---> 24 index = GPTVectorStoreIndex.from_documents(
     25 #     [],
     26     document2,
. . .
~/anaconda3/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py in _get_node_embedding_results(self, nodes, show_progress)
     99         for n in nodes:
    100             if n.embedding is None:
--> 101                 self._service_context.embed_model.queue_text_for_embedding(
    102                     n.node_id, n.get_content(metadata_mode=MetadataMode.EMBED)
    103                 )

AttributeError: 'GPT4AllEmbeddings' object has no attribute 'queue_text_for_embedding'

**Comment by logan-markewich** [comment]
@Ashish5869 you need to wrap the embeddings with the langchain wrapper

https://gpt-index.readthedocs.io/en/stable/examples/embeddings/Langchain.html
