### ISSUE TITLE
[Documentation]: Twitter link to GitHub is outdated

### ISSUE THREAD

**Issue by dtbuchholz** [jerryjliu/llama_index#7185]
### Documentation Issue Description

Your twitter profile is here: https://twitter.com/llama_index

It lists a GitHub link: https://github.com/jerryjliu/llam

But the correct link should be: https://github.com/jerryjliu/llama_index

### Documenation Link

https://twitter.com/llama_index

**Comment by logan-markewich** [comment]
Fixed
