### ISSUE TITLE
[Question]: I want to write my own prompt for TREE_SUMMARIZE

### ISSUE THREAD

**Issue by Orescout** [jerryjliu/llama_index#7186]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi!
I'm trying to summarize a long document, using the (phenomenal) [TREE_SUMMARIZE](056cfb2d77666ba3c5659750b/llama_index/response_synthesizers/tree_summarize.py#L47) using Llama-2 from HuggingFace. The end command is: doc_summary_index.get_document_summary(documents[0].id_)

To my understanding, each chunk gets summarized in a tree manner. However, I have little control to the summarization prompt! Here's three different places where I need to be aware of the prompt passed in:
- HuggingFaceLLM with parameter query_wrapper_prompt=SimpleInputPrompt("<|USER|>{query_str}<|ASSISTANT|>")
- response_synthesizer with parameter text_qa_template = Prompt((
                              "Context information is below.\n"
                              "---------------------\n"
                              "{context_str}\n"
                              "---------------------\n"
                              "Given the context information and not prior knowledge, "
                              "summarize it. \n"
                          ), 
                          prompt_type=PromptType.QUESTION_ANSWER)
- DocumentSummaryIndex.from_documents with parameter summary_query = (
    "Give a concise summary of this document. Also describe some of the questions "
    "that this document can answer. "
)

So, the final prompt, ends up being a puzzle of all of the above, right? How can I write ONE prompt in ONE place that includes basically one thing: {context_str}. Cause the {query_str} doesn't change as far as my document summarization is concerned. The query str is already in my prompt which is used for every chunk. Does that make sense?

What I've tried:
- editing summary_query. For whatever reason, only the first line gets accepted. My summarization prompt is longer than one line/sentence.
- Removing the query_wrapper_prompt=SimpleInputPrompt("<|USER|>{query_str}<|ASSISTANT|>"). This causes the summarization to produce an empty string (!). no clue why. even the slightest edit, will cause it to pop out empty.
- Editing text_qa_template and passing in empty or almost-empty summary_query. Doesn't seem to work, for whatever reason.

Any advice or fixes or wisdom? Much appreciated :)

**Comment by logan-markewich** [comment]
@Orescout the tree summarize mode uses the `text_qa_template` -- so customizing this is all you need to do

```python
from llama_index import get_response_synthesizer

response_synthesizer = get_response_synthesizer(
    response_mode="tree_summarize",  # it looks like the index actually defaults to "compact" 
    text_qa_template=CUSTOM_TEMPLATE,
    service_context=service_context  # optional, needed to propagate settings

index = DocumentSummaryIndex.from_documents(documents, ...., response_synthesizer=response_synthesizer)
```

In the code, you can see the summaries being built here, with the response synthesizer you passed in
https://github.com/jerryjliu/llama_index/blob/6e9a7b41db1adc2eb8b29be0b650b6842799ca28/llama_index/indices/document_summary/base.py#L145

**Comment by bSharpCyclist** [comment]
I ran into a similar situation today which I chatted with you about, Logan. I thought the below would work at first. 

`query_engine = index.as_query_engine(response_mode="tree_summarize", 
                                     service_context=service_context,
                                     summary_template=custom_chat_template)
`
                                     
But it turns out that I had to do this

`response_synthesizer = get_response_synthesizer(
    response_mode="tree_summarize",
    summary_template=custom_chat_template,
    service_context=service_context,
)

query_engine = index.as_query_engine(response_synthesizer=response_synthesizer)
`                                 

Note at first I wanted to set text_qa_template, according to the docs below. Seems to mention that should be used. But after digging through the source code I found that summary_template needs to be defined. I think with a few simple modifications, you could make the 3 line of code at the beginning work, but maybe the expectation is that one should their own response synthesizer.

https://gpt-index.readthedocs.io/en/stable/core_modules/query_modules/query_engine/response_modes.html#response-modes

**Comment by logan-markewich** [comment]
@bSharpCyclist yea the docs should be updated, but also, I see no reason why the initial 3 line attempt didn't work. I can attempt to debug this

**Comment by bSharpCyclist** [comment]
Thanks, @logan-markewich. This is what I saw, in retreiver_query_engine.py. I'm happy to try and submit a PR and do something meaningful in the open source community :D

```
    def as_query_engine(self, **kwargs: Any) -> BaseQueryEngine:
        # NOTE: lazy import
        from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine

        retriever = self.as_retriever(**kwargs)

        kwargs["retriever"] = retriever
        if "service_context" not in kwargs:
            kwargs["service_context"] = self._service_context
        return RetrieverQueryEngine.from_args(**kwargs)
```

You'd have to add support for summary_template in RetrieverQueryEngine.from_args I think. And then if passed, set it below when a response synthesizer isn't passed.

```
        response_synthesizer = response_synthesizer or get_response_synthesizer(
            service_context=service_context,
            text_qa_template=text_qa_template,
            refine_template=refine_template,
            simple_template=simple_template,
            response_mode=response_mode,
            use_async=use_async,
            streaming=streaming,
        )
```

**Comment by logan-markewich** [comment]
@bSharpCyclist You you got it, just made a PR to fix this
