### ISSUE TITLE
[Question]:  cannot import name 'llm_callback' from 'llama_index.llms' 

### ISSUE THREAD

**Issue by xinkeyb** [jerryjliu/llama_index#7191]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to use  local LLM，I'm referencing the code in this example：“https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced” . 
But the following problem was encountered:"ImportError: cannot import name 'llm_callback' from 'llama_index.llms' (/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/llms/__init__.py)".

The version of llama_index is 0.7.21

**Comment by xinkeyb** [comment]
> _Answer generated by a 🤖_
> 
> ## Answer
> Hello,
> 
> The error message "ImportError: cannot import name 'llm_callback' from 'llama_index.llms'" suggests that the module 'llama_index.llms' does not have an attribute or function named 'llm_callback'.
> 
> In the context shared, it appears that 'llm_callback' might be a misinterpretation or typo. The 'llama_index' package has a 'callbacks' module, which contains various callback handlers such as 'OpenInferenceCallbackHandler', 'CallbackManager', 'LlamaDebugHandler', etc., but there is no 'llm_callback'.
> 
> If you are trying to use a callback function, you should import the appropriate callback handler from 'llama_index.callbacks' instead. Here is how you can import and use them in your code:
> 
> ```python
> from llama_index.callbacks import CallbackManager, OpenInferenceCallbackHandler
> 
> # Your code here using CallbackManager, OpenInferenceCallbackHandler
> ```
> 
> Please update your code accordingly and try again. If the problem persists, please provide more context or check the latest documentation for LlamaIndex version 0.7.21.
> 
> If you were referring to 'llm_chat_callback' and 'llm_completion_callback', these are decorators imported from 'llama_index.llms.base'. They are used to decorate the methods in the 'LlamaAPI' class.
> 
> The 'llm_chat_callback' is used to decorate the 'chat' and 'stream_chat' methods. The 'chat' method takes a sequence of 'ChatMessage' objects and additional keyword arguments, and returns a 'ChatResponse'. The 'stream_chat' method also takes a sequence of 'ChatMessage' objects and additional keyword arguments, but it returns a 'ChatResponseGen' (presumably a generator of 'ChatResponse' objects). However, the 'stream_chat' method is not implemented in the 'LlamaAPI' class.
> 
> The 'llm_completion_callback' is used to decorate the 'complete' and 'stream_complete' methods. The 'complete' method takes a prompt string and additional keyword arguments, and returns a 'CompletionResponse'. The 'stream_complete' method also takes a prompt string and additional keyword arguments, but it returns a 'CompletionResponseGen' (presumably a generator of 'CompletionResponse' objects). However, the 'stream_complete' method is not implemented in the 'LlamaAPI' class.
> 
> The exact functionality of these decorators ('llm_chat_callback' and 'llm_completion_callback') is not provided in the given context. They could be used for a variety of purposes, such as logging, timing, precondition checking, postcondition checking, or modifying the return values of the decorated methods. Without more information, it's impossible to say what they do.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [llama_index/llms/llama_api.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/llama_api.py)
> * [llama_index/llms/**init**.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/__init__.py)
> * [llama_index/callbacks/**init**.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/callbacks/__init__.py)
> * [docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb](https://github.com/jerryjliu/llama_index/blob/-/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb)
> 
> This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

This is my code:
import logging
import sys
from llama_index.llms import CustomLLM, CompletionResponse, LLMMetadata, llm_callback
from llama_index import ServiceContext

import torch
from transformers import pipeline
from typing import Optional, List, Mapping, Any

from llama_index import (
    ServiceContext,
    SimpleDirectoryReader,
    LangchainEmbedding,
    ListIndex
)


# set context window size
context_window = 2048
# set number of output tokens
num_output = 256

# store the pipeline/model outisde of the LLM class to avoid memory issues
model_name = "/data/zhaoxinke/PromptCBLUE-main/src/bloom-7b1"
pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype": torch.bfloat16})


class OurLLM(CustomLLM):

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=context_window,
            num_output=num_output,
            model_name=model_name
        )

    @llm_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        text = response[prompt_length:]
        return CompletionResponse(text=text)

    @llm_callback()
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        raise NotImplementedError()


# define our LLM
llm = OurLLM()

service_context = ServiceContext.from_defaults(
    llm=llm,
    context_window=context_window,
    num_output=num_output
)

**Comment by xinkeyb** [comment]
this is my code:
import logging
import sys
from llama_index.llms import CustomLLM, CompletionResponse, LLMMetadata
from llama_index import ServiceContext

import torch
from transformers import pipeline
from typing import Optional, List, Mapping, Any

from llama_index import (
    ServiceContext,
    SimpleDirectoryReader,
    LangchainEmbedding,
    ListIndex
)


# set context window size
context_window = 2048
# set number of output tokens
num_output = 256

# store the pipeline/model outisde of the LLM class to avoid memory issues
model_name = "/data/zhaoxinke/PromptCBLUE-main/src/bloom-7b1"
pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype": torch.bfloat16})


class OurLLM(CustomLLM):

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=context_window,
            num_output=num_output,
            model_name=model_name
        )

    @llm_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        text = response[prompt_length:]
        return CompletionResponse(text=text)

    @llm_callback()
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        raise NotImplementedError()


# define our LLM
llm = OurLLM()

service_context = ServiceContext.from_defaults(
    llm=llm,
    context_window=context_window,
    num_output=num_output
)

**Comment by xinkeyb** [comment]
thank you very much，I adopted your suggestion，but it encountered the following error：“NameError: name 'CompletionResponseGen' is not defined”，so I added a line of code:"from llama_index.llms.base import CompletionResponseGen".

but it occur another error：“Traceback (most recent call last):
  File "/data/zhaoxinke/test.py", line 65, in <module>
    llm = OurLLM()
TypeError: __init__() missing 1 required positional argument: 'callback_manager'”

**Comment by logan-markewich** [comment]
@xinkeyb seems like I need to update that example 😓 Will do so shortly

**Comment by xinkeyb** [comment]
thank you very much，I adopted your suggestion：
       callback_manager = CallbackManager([])
       llm = OurLLM(callback_manager

but it encountered the following error:
Traceback (most recent call last):
  File "/data/zhaoxinke/test.py", line 67, in <module>
    service_context = ServiceContext.from_defaults(
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 164, in from_defaults
    embed_model = embed_model or OpenAIEmbedding()
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/embeddings/openai.py", line 248, in __init__
    validate_openai_api_key(
  File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/llms/openai_utils.py", line 268, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

**Comment by xinkeyb** [comment]
thank you very much，I adopted your suggestion：
callback_manager = CallbackManager([])
llm = OurLLM(callback_manager

but it encountered the following error:
Traceback (most recent call last):
File "/data/zhaoxinke/test.py", line 67, in
service_context = ServiceContext.from_defaults(
File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 164, in from_defaults
embed_model = embed_model or OpenAIEmbedding()
File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/embeddings/openai.py", line 248, in init
validate_openai_api_key(
File "/home/zhaoxinke/miniconda3/envs/kgllm/lib/python3.9/site-packages/llama_index/llms/openai_utils.py", line 268, in validate_openai_api_key
raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

I have some doubts, when I try to use a local LLM, Why did he tell me he need OPENAI_API_KEY？

**Comment by logan-markewich** [comment]
@xinkeyb there are two models in llama index. An LLM and an embedding model

See more about local/custom LLMs here on this page
https://gpt-index.readthedocs.io/en/stable/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations

**Comment by xinkeyb** [comment]
Is this okay？：

callback_manager = CallbackManager([])
llm = OurLLM(callback_manager)
service_context = ServiceContext.from_defaults(
    llm=llm,
    context_window=context_window,
    num_output=num_output,
    embed_model=llm
)
llm and embed_model are set to the local LLM

**Comment by logan-markewich** [comment]
The embed model can't be the LLM, it has to be a model actually trained/setup for embeddings 

a quick default is just setting embed_model="local"
