### ISSUE TITLE
[Feature Request]: Fastchat RESTful OpenAI API server drop-in for Llama 2

### ISSUE THREAD

**Issue by asaiacai** [jerryjliu/llama_index#7212]
### Feature Description

I'm trying to make drop-in replacement chat endpoint for `meta-llama/Llama-2-7b-chat-hf` using the [FastChat OpenAI API](https://github.com/lm-sys/FastChat/blob/32c1910ebb3567545556f9cb859ba02b36b35ed6/docs/openai_api.md). Something like.

```
import os
from llama_index.llms import ChatMessage, OpenAI

os.environ["OPENAI_API_KEY"] = "EMPTY"
os.environ["OPENAI_API_BASE"] = "http://localhost:8000/v1"

messages = [
    ChatMessage(role="system", content="You are a pirate with a colorful personality"),
    ChatMessage(role="user", content="What is your name"),
]

resp = OpenAI(model="Llama-2-7b-chat-hf").chat(messages)
print(resp)
```

### Reason
I can interact with my model through the `openai` python library and set my key with `export OPENAI_API_KEY="EMPTY"`. However, the `OPENAI_API_KEY` value is format checked disallowing this behavior if I use LlamaIndex.

```
ValueError: Invalid OpenAI API key.
API key should be of the format: "sk-" followed by 48 alphanumeric characters.
```

Also if I hard code `OPENAI_API_KEY` to pass the format check, I run into another issue where I cannot use `OpenAI(model="Llama-2-7b-chat-hf")` since it is not in the list of supported models. Maybe it makes more sense to create a new subclass in this situation?

```
  File "/Users/asai/miniconda3/envs/llama/lib/python3.10/site-packages/llama_index/llms/openai_utils.py", line 186, in openai_modelname_to_contextsize
    raise ValueError(
ValueError: Unknown model: Llama-2-7b-chat-hf. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-32k, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo
```

### Value of Feature

Fastchat integrates with vLLM which is currently SoTA for serving OSS LLMs and has an openAI API server already.

**Comment by cwerner** [comment]
I am interested in this as well. I want to use the local API endpoints from LM Studio which is supposedly OpenAI compatible.

**Comment by logan-markewich** [comment]
As a work around, you can wrap the API into an extension of the customLLM class.

If your API supports messages, you can also implement `chat` and `stream_chat`

If your API supports async, you can also implement `acomplete`, `achat`, etc

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced

Source code reference
https://github.com/jerryjliu/llama_index/blob/main/llama_index/llms/custom.py

**Comment by asaiacai** [comment]
I got this example to work on my end for a Fastchat Llama 7b OpenAI endpoint I setup.

https://github.com/Trainy-ai/llm-atc/blob/main/examples/llama_index/llama_index_chat.py

**Comment by logan-markewich** [comment]
That works too!
