### ISSUE TITLE
[Question]: Can I past a list of query strings to query_engine.query() or query_engine.retrieve() i.e., batch query/retrieve?

### ISSUE THREAD

**Issue by kevon217** [jerryjliu/llama_index#7218]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

It's not entirely clear to me if a RetrieverQueryEngine() supports batch queries. I'm not using an LLM and just want to retrieve semantically similar results.

My query engine for my chromdb index is defined as follows:

`index = VectorStoreIndex.from_vector_store(vector_store=vector_store,storage_context=storage_context, 
service_context=service_context,)`

`retriever = VectorIndexRetriever(
    index=index,
    similarity_top_k=cfg.semantic_search.query.similarity_top_k,
    vector_store_query_mode="text_search",
)`

`response_synthesizer = get_response_synthesizer(
  response_mode="no_text", service_context=service_context
)`

`rerank = SentenceTransformerRerank(
    model=cfg.semantic_search.query.rerank.cross_encoder.model_name,
    top_n=cfg.semantic_search.query.rerank.cross_encoder.top_n,
)`

`query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[DummyNodePostprocessor(), rerank],
)`

My hope was that I could pass a list of query strings as follows:

` results_q = query_engine.query(queries)`
OR
`results_r = query_engine.retriev(queries)`

Do async methods apply at all?

**Comment by logan-markewich** [comment]
The bot is correct :) Just need to be careful about rate limits then when running so many queries

**Comment by kevon217** [comment]
Wow, that was a great bot response. Appreciate it and your confirmation.

I'm actually just using it for semantic search retrieval, so no calls to llm.

**Comment by Data-drone** [comment]
@logan-markewich  Is there a Query engine designed for batch queries?

**Comment by logan-markewich** [comment]
@Data-drone nah, and I don't think there's one planned 

Your best bet is async with aquery() and aretrieve()

Would welcome PR for it though
