### ISSUE TITLE
GPTListIndex does not do well

### ISSUE THREAD

**Issue by azmathr** [jerryjliu/llama_index#723]
Since my file was large GPT would timeout with GPTSimpleVectorIndex. So I split the document into multiple files and saved though GPTSimpleVectorIndex. After slitting I merged them using GPTListIndex. But the quality of results are remarkable. Querying he index created using GPTListIndex does not even appear to be contextual, its getting data from other source. Is there any other way to merge all the indices created by GPTSimpleVectorIndex into one?

```
document1 = loader.load_data('jason_nm-_MConverter.eu_-1-500.pdf')
document2 = loader.load_data('jason_nm-_MConverter.eu_-500-1000.pdf')
document3 = loader.load_data('jason_nm-_MConverter.eu_-1001-1500.pdf')
document4 = loader.load_data('jason_nm-_MConverter.eu_-1501-2000.pdf')
document5 = loader.load_data('jason_nm-_MConverter.eu_-2001-2621.pdf')
documentF = loader.load_data('nm.pdf')

index1 = GPTSimpleVectorIndex(document1)
index2 = GPTSimpleVectorIndex(document2)
index3 = GPTSimpleVectorIndex(document3)
index4 = GPTSimpleVectorIndex(document4)
index5 = GPTSimpleVectorIndex(document5)

index1.set_text("summary1")
index2.set_text("summary2")
index3.set_text("summary3")
index4.set_text("summary4")
index5.set_text("summary5")

index6 = GPTListIndex([index1, index2, index3, index4, index5])

response = index6.query('How to get out of addiction')
print(response)

```

**Comment by jerryjliu** [comment]
Hi @azmathr i'm trying to understand this issue. what do you mean by `Querying he index created using GPTListIndex does not even appear to be contextual, its getting data from other source.`? 

also what do you mean by `GPT would timeout with GPTSimpleVectorIndex`? defining a list index over your documents will take longer because it's creating a compute graph

**Comment by jerryjliu** [comment]
Since this isn't a bug i'd refer to our discord: https://discord.gg/dGcwcsnxhU

**Comment by azmathr** [comment]
Hi @jerryjliu  Thank you very much for your quick reply. What I mean is that, when I create and index using list index and I query that listindex, the answers are widely out of the context provided. For instance, when queried without using listindex (that is if I manually put all the data into one file and use GPTsimpleVectorIndex to query), the answers are much relevant to the data provided. In a nutshell, when I use listindex the answers are very different and outside the scope of trained data, while quirieng a manually merged large file using Vectorindex gives accurate answers.

**Comment by ymansurozer** [comment]
@azmathr I am having the exact same issue. The ListIndex seems to not use the chunks in the index files I provided so the answer is out of context.

Were you able to fix this?
