### ISSUE TITLE
[Bug]: The changes on v0.7.24 is too big and break many things.

### ISSUE THREAD

**Issue by rendyfebry** [jerryjliu/llama_index#7231]
### Bug Description

This particular PR (#7223) changed so many things at once, which caused backward incompatibility or behavior changes. 

Either needs a way to inform to the user, or make some kind of "major" release (e.g.: v0.8.x)

To name a few:
 * Due to the switching text splitter to sentence splitter, need to install/update additional package (e.g.: nltk, a newer version of langchain that include HuggingFaceBgeEmbeddings)
 * Changing the default text splitter to be sentence splitter might also change the end-user behavior, which might break user test cases.
 * The sentence splitter uses nltk package, and as described on https://github.com/jerryjliu/llama_index/pull/6579, nltk will try to download the file to /home which is not available on many cloud serverless solutions (e.g.: lambda, fargate, etc). So until the user explicitly sets the `NLTK_DATA` env var, it won't run.
 * The change message now has a [default prompt](https://github.com/jerryjliu/llama_index/pull/7223/files#diff-5512b0e5f147e1df32fc2aa14440952c502f3b835ece360ced5e095690a62da9). Which make the Chat engine behavior changed completely and OpenAIAgent even straight up refuse to answer with "I'm sorry, but I cannot provide a <REDACTED> based on the given context information"

### Version

0.7.24

### Steps to Reproduce

If you have an existing application, try to update to v0.7.24 and you would will notice the problem

**Comment by jerryjliu** [comment]
thanks for flagging - this is a big PR with lots of breaking changes 

it makes sense to cut a 0.8.0 release. we'll patch the existing pypi release on 0.7.x to remove these changes

**Comment by logan-markewich** [comment]
0.8.0 is out, with some improvements that were mentioned here!
