### ISSUE TITLE
Returning Zero Nodes with similarity_cutoff

### ISSUE THREAD

**Issue by eriktlu** [jerryjliu/llama_index#724]
Is there a solution for when I set `similarity_cutoff` and there are no nodes with a high enough float point?

Maybe there could be a separate prompt template for that case. For example, in my use case, I would like to find the top 5 closest nodes with .9 `similarity_cutoff`, and if there are none then I would like the model to try to answer the question without any added context.

**Comment by Smyja** [comment]
been running into the same issue, i can't go above 0.7
