### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by gajavelli** [jerryjliu/llama_index#7242]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm not able to use gpt-4

tried the example from /GPT4Comparison.ipynb. 

InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

Not sure what is wrong. Any help or direction would be much appreciated

**Comment by logan-markewich** [comment]
That example notebook is pretty old

Just to confirm, this is how you properly switch to gpt-4

```
from llama_index.llms import OpenAI

llm = OpenAI(temperature=0.2, model="gpt-4")
service_context = ServiceContext.from_defaults(llm=llm)
```

**Comment by gajavelli** [comment]
> That example notebook is pretty old
> 
> Just to confirm, this is how you properly switch to gpt-4
> 
> ```
> from llama_index.llms import OpenAI
> 
> llm = OpenAI(temperature=0.2, model="gpt-4")
> service_context = ServiceContext.from_defaults(llm=llm)
> ```
👆
Yes that is exactly, how my code looks like the above snippet 

**However, I tried a different way for instancing the llm like below and it worked.**
But not able to use llama_index and gpt-4, Not sure what is missing or wrong with the above code .

This works 👇
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(model_name='gpt-4')
service_context = ServiceContext.from_defaults(llm=llm)

**Comment by logan-markewich** [comment]
Using the langchain LLM kind of removes a lot of key features. 

No idea why the sample I gave didn't work for you, this is exactly what I use to setup gpt-4 every time 😅 maybe double check you were tying with the llama_index LLM class?

**Comment by logan-markewich** [comment]
Either way, best of luck! Going to close this because it doesn't seem to be an issue either way
