### ISSUE TITLE
[Question]: combine gpt-3.5-turbo with HuggingFace embedding model

### ISSUE THREAD

**Issue by nacho00112** [jerryjliu/llama_index#7245]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Let's suppose i want to use `gpt-3.5-turbo` but with the huggingface embedding model instead of `ada-embedding-002`, how i can do that?
By monkeypatching `llama_index.embeddings.utils.resolve_embed_model(embed_model)` to receive `'local'` i could do it but i thought it's better to ask about this here

**Comment by dhuynh95** [comment]
I would be quite interested to know too! 

There is a mention of a local embedding example in the [docs](https://gpt-index.readthedocs.io/en/stable/core_modules/model_modules/llms/usage_custom.html) on customization, but the link is empty.

**Comment by logan-markewich** [comment]
Easy! @dhuynh95 @nacho00112 

```
from llama_index import ServiceContext, set_global_service_context

service_context = ServiceContext.from_defaults(embed_model="local")
set_global_service_context(service_context)
```


The following will download and run our default local embedding model: `BAAI/bge-small-en`

You can set the model directly in a similar way

`service_context = ServiceContext.from_defaults(embed_model="local:BAAI/bge-small-en")`

The path after the colon should line up with an existing model name from huggingface.

Optionally, you can also use any embedding model from langchain

```
from llama_index.embeddings import LangchainEmbedding

lc_embed_model = <lc_embed_model>
service_context = ServiceContext.from_defaults(embed_model=LangchainEmbedding(lc_embed_model))
```

**Comment by ibicdev** [comment]
Will
```service_context = ServiceContext.from_defaults(embed_model="local:BAAI/bge-small-en")```
automatically use GPUs if available?  Or we should use LangChain's `HuggingFaceBgeEmbeddings` with `model_kwargs = {'device': 'gpu'}` and wrap it in `llama_index.embeddings.LangchainEmbedding`?

**Comment by logan-markewich** [comment]
Hmm It might use gpu if available? It's actually using langchain under the hood anyways LOL but I think it might need to be specifically in the kwargs like you mentioned 

If it doesn't run on GPU, then ya, you can do it that second way 👍

**Comment by ibicdev** [comment]
Just gave it a quick try and it seems it uses my GPU automatically - guess the underlying `sentence_transformers` takes care of it.
