### ISSUE TITLE
Locate the location of the source file according to node_info

### ISSUE THREAD

**Issue by mingxin-yang** [jerryjliu/llama_index#725]
If my source file is a pdf, how should I locate the page and line of the source file according to node_info={'start':32444,'end':33918}.

**Comment by Disiok** [comment]
Hi @mingxin-yang,  I believe the `node_info` shows the start and end position in terms of character count.

So yes, it's currently difficult to locate the page and line of the source file.

We hope to add better source referencing, but probably won't get to it soon. 

If you have ideas on how to make this better, feel free to open a PR to help the community!
