### ISSUE TITLE
[Question]: Can I persist metadata in node without using it in the embedding?

### ISSUE THREAD

**Issue by kevon217** [jerryjliu/llama_index#7250]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm a little confused when using llamaindex in conjunction with chromadb for simple semantic search (WITHOUT an LLM) using a custom embedding model WITHOUT incorporating metadata strings into the embedding. I'd like for my nodes to have a metadata dictionary that I can easily access when I retrieve my node results, however, when I exclude all my metadata keys when creating my nodes ( **exclude_embed_metadata_keys** ), it resets the metadata field to an empty set. The metadata DOES get added to the chromadb node_content field, HOWEVER, in order to access that when I retrieve my node results with a query engine, it's located in a deeper nested field. 

I was hoping the metadata field would have the metadata I'm interested in accessing ( **node['metadata']** ), but it seems to only be stored in the chromadb node info ( **relationships['1']['metadata]** ). _Is this the expected location to access node metadata when using a vector store?_

Below is my retrieved node result as a dictionary:

{'node': {'id_': 'a5febf45-a445-455a-aac4-db4fb31ecd68',
  'embedding': None,
  'metadata': {},
  'excluded_embed_metadata_keys': ['variable name',
   'title',
   'element type',
   'definition',
   'short description',
   'datatype',
   'input restriction',
   'minimum value',
   'maximum value',
   'data element concept identifiers',
   'data element concept names',
   'permissible values',
   'permissible value descriptions',
   'permissible value concept identifiers',
   'permissible value concept names',
   'unit of measure',
   'preferred question text',
   'creation date',
   'last change date'],
  'excluded_llm_metadata_keys': ['variable name',
   'title',
   'element type',
   'definition',
   'short description',
   'datatype',
   'input restriction',
   'minimum value',
   'maximum value',
   'data element concept identifiers',
   'data element concept names',
   'permissible values',
   'permissible value descriptions',
   'permissible value concept identifiers',
   'permissible value concept names',
   'unit of measure',
   'preferred question text',
   'creation date',
   'last change date'],
  'relationships': {<NodeRelationship.SOURCE: '1'>: {'node_id': 'a4026290-896b-4f4f-a309-5b7a9cbddab5',
    'node_type': None,
    'metadata': {'variable name': 'LEC5LifThrtningIlnesInjryCat',
     'title': 'Life Events Checklist 5 (LEC-5) - Life-threatening Illness or Injury Category',
     'element type': 'Unique Data Element',
     'definition': 'Category of Life-threatening illness or injury is seriously dangerous, and it might even result in death as part the of Life Events Checklist 5 (LEC-5).',
     'short description': 'Category of Life-threatening illness or injury is seriously dangerous, and it might even result in death as part the of Life Events Checklist 5 (LEC-5).',
     'datatype': 'Alphanumeric',
     'input restriction': 'Multiple Pre-Defined Values Selected',
     'minimum value': nan,
     'maximum value': nan,
     'data element concept identifiers': nan,
     'data element concept names': nan,
     'permissible values': 'a|b|c|d|e|f',
     'permissible value descriptions': 'Happened to you personally|You witnessed it happen to someone else|You learned about it happening to a close family member or closefriend|You were exposed to it as part of your job (for example, paramedic, police, military, or other first responder)|You are not sure if it fits|It does not apply to you',
     'permissible value concept identifiers': nan,
     'permissible value concept names': nan,
     'unit of measure': nan,
     'preferred question text': 'Life-threatening illness or injury',
     'creation date': '9/7/2016',
     'last change date': '9/14/2016'},
    'hash': '8f018af5ec5d8d8e0bbe0ea6df6885764d453912c5a0821c2096a6b35aae2e17'}},
  'hash': '44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a',
  'text': 'Life Events Checklist 5 (LEC-5) - Life-threatening Illness or Injury Category',
  'start_char_idx': 0,
  'end_char_idx': 77,
  'text_template': '{metadata_str}\n\n{content}',
  'metadata_template': '{key}: {value}',
  'metadata_seperator': '\n'},
 'score': 0.7744697}

**Comment by logan-markewich** [comment]
I feel like the bot sliiightly hallucinated this? While it isn't completely wrong, the metadata should not be cleared from the node as you are observing.

Can you provide some minimum code to reproduce the issue? Just want to confirm if the issue is in the codebase or in your setup 👍🏻

**Comment by kevon217** [comment]
@logan-markewich,

Sure, below is the code I'm using to create VectorStoreIndex. The metadata dictionary is empty regardless if I use SimpleNodeParse(include_metadata=True) or SimpleNodeParse(include_metadata=False).

Let me know if this snippet helps or if you need more information.


`

    # LOAD SENTENCE TRANSFORMER EMBEDDING MODEL
    embed_model = LangchainEmbedding(
        HuggingFaceEmbeddings(
            model_name=cfg.indices.index.collections.embed.model_name,
            model_kwargs={},
            encode_kwargs=cfg.indices.index.collections.embed.model_kwargs,
        ),
        embed_batch_size=cfg.indices.index.collections.embed.model_kwargs.batch_size,  # have to manual override
    )

    # CREATE LLAMAINDEX DOCUMENTS
    id_col = cfg.indices.index.collections.embed.id_column
    embed_cols = cfg.indices.index.collections.embed.columns
    metadata_cols = cfg.indices.index.collections.metadata_columns
    index_nodes = {}
    setup_index_logger.info("Creating Llamaindex Documents")
    parser = SimpleNodeParser.from_defaults(
        include_metadata=True, chunk_size=512, chunk_overlap=0
    )
    # parser = SimpleNodeParser.from_defaults(
    #     include_metadata=False, chunk_size=512, chunk_overlap=0
    # )
    for col in embed_cols:
        ids = []
        documents = []
        for idx, row in df.iterrows():
            doc = row[col]
            meta = {val: row[val] for val in metadata_cols}
            document = Document(
                text=doc,
                metadata=meta,
                excluded_embed_metadata_keys=list(meta.keys()),
                text_template="{content}"
            )
            documents.append(document)
        nodes = parser.get_nodes_from_documents(documents, show_progress=True)
        index_nodes[col] = nodes

    # CREATE CHROMADB & LLAMAINDEX FROM DOCUMENTS
    storage_path_root = cfg.indices.index.collections.storage_path_root
    storage_path_indices = {}
    setup_index_logger.info("Initializing local vector store")
    client = chromadb.PersistentClient(path=storage_path_root)
    service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)
    set_global_service_context(service_context)
    indices = {}
    for col in index_nodes.keys():
        setup_index_logger.info(f"Creating collection: {col}")
        chroma_collection = client.get_or_create_collection(
            col, metadata=dict(cfg.indices.index.collections.distance_metric)
        )
        vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        index = VectorStoreIndex(
            index_nodes[col],
            storage_context=storage_context,
            service_context=service_context,
            embed_model=embed_model,
            show_progress=True,
        )
        # PERSIST INDEX TO LOCAL
        setup_index_logger.info(f"Persistening Llamaindex: {col}")
        index.summary = f"{cfg.indices.index.summary} {col}"
        index.set_index_id(col)
        storage_path_index = Path(storage_path_root, col).as_posix()
        index.storage_context.persist(storage_path_index)
        storage_path_indices[col] = storage_path_index
        indices[col] = index

    # SAVE CONFIG
    cfg.indices.index.collections.storage_paths_indices = storage_path_indices
    helper.save_config(
        cfg,
        cfg.indices.index.collections.storage_path_root,
        "config_chromdb_llamaindex.yaml",
    )

    return indices`

**Comment by logan-markewich** [comment]
@kevon217 

Hmm, I managed to re-produce the issue, and I also fixed it, but I can't explain why it's happening 😆 

Either way, from my testing, the issue seems to happen when you load an existing index.

To properly load an existing index, do something like this. I will update the demo notebook shortly as well

```
# load from disk
db2 = chromadb.PersistentClient(path="./chroma_db")
chroma_collection = db2.get_or_create_collection("quickstart")
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
index = VectorStoreIndex.from_vector_store(
    vector_store,
    service_context=service_context,
)
```

**Comment by kevon217** [comment]
@logan-markewich , thanks for looking into that!

**Comment by logan-markewich** [comment]
Your welcome! 💪🏻
