### ISSUE TITLE
[Question]: Asks for Open AI API key when using local LLM model and embeddings model

### ISSUE THREAD

**Issue by nat-tsang** [jerryjliu/llama_index#7259]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to use a local llm and hugging face embeddings model, but when I try to load my index from storage, I get an error saying: ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys
I can't find any other ways to load the index store when using a local LLM besides what I have tried to implement in my code. 

index.py to create index
```
def localGPT():
    local_llm_path = './ggml-gpt4all-j-v1.3-groovy.bin'
    llm = GPT4All(model=local_llm_path, backend='gptj', streaming=True, max_tokens=512)
    return llm

def create_index(docs):
    llm = LLMPredictor(llm=localGPT())
    # embeddings are downloaded and run locally through hugging face
    embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="./all-mpnet-base-v2"))
    prompt_helper = PromptHelper(num_output=256)
    service_context = ServiceContext.from_defaults(
        llm_predictor=llm,
        prompt_helper=prompt_helper,
        embed_model="local",
        node_parser=SimpleNodeParser(text_splitter=TokenTextSplitter(chunk_size=300, chunk_overlap=20))
    )
    index = GPTVectorStoreIndex.from_documents(docs, service_context=service_context)
    index.storage_context.persist()
    return index

create_index(docs)
```

streamlit.py to create streamlit ui:
```
def streamlit_app():
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
    index = load_index_from_storage(storage_context)
```

**Comment by logan-markewich** [comment]
@nat-tsang when you load the index from storage, you still need to pass in the service context

`index = load_index_from_storage(storage_context, service_context=service_context)`

**Comment by logan-markewich** [comment]
@nat-tsang also you'll need to wrap GPT4ALL with `LangChainLLM`

```
from llama_index.llms import LangChainLLM

llm = LangChainLLM(GPT4ALL(...))
```

or you can pass in the LLM directly to the service context and it gets wrapped automatically, no need for `LLMPredictor` in that case

`service_context = ServiceContext.from_defaults(llm=llm, ....)`

**Comment by nat-tsang** [comment]
thanks, got it running. It is still taking a while to load though, is this usually the case even with index storage? I have around 500 documents

**Comment by logan-markewich** [comment]
that sounds about right for that number of documents. If you have CUDA installed though, it will run on GPU automatically and be much faster. Right now, the embeddings are likely running on CPU
