### ISSUE TITLE
[Bug]: PandasQueryEngine - Unexpected Indent

### ISSUE THREAD

**Issue by yapnel** [jerryjliu/llama_index#7269]
### Bug Description

The python code generated has IndentationError: unexpected indent

### Version

0.8.2.post1

### Steps to Reproduce

import pandas as pd
from llama_index.query_engine import PandasQueryEngine
from llama_index.llms import LlamaCPP
from llama_index import SimpleDirectoryReader, VectorStoreIndex, ServiceContext, StorageContext, load_index_from_storage
from llama_index import set_global_service_context
from langchain.embeddings import HuggingFaceEmbeddings
from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt

def custom_completion_to_prompt(completion: str) -> str:
    return completion_to_prompt(
        completion,
        system_prompt=(
            "You are a Q&A assistant. Your goal is to answer questions as "
            "accurately as possible is the instructions and context provided."
        ),
    )

llm = LlamaCPP(
    model_path="./models/llama-2-7b-chat.ggmlv3.q8_0.bin",
    temperature=0.9,
    max_new_tokens=4096,
    context_window=4096,
    verbose=True,
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=custom_completion_to_prompt,    
 )

embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2',model_kwargs={'device': 'cpu'})
service_context = ServiceContext.from_defaults(chunk_size=512, chunk_overlap=200, llm=llm, embed_model=embeddings)
set_global_service_context(service_context)

df = pd.DataFrame(
    {"city": ["Toronto", "Tokyo", "Berlin"], "population": [2930000, 13960000, 3645000]}
)

query_engine = PandasQueryEngine(df=df, verbose=True, service_context=service_context)
response = query_engine.query("What is the city with the highest population?")

### Relevant Logs/Tracbacks

```shell
Llama.generate: prefix-match hit
> Pandas Instructions:

  Understood! To answer the query "What is the city with the highest population?", we can use the `df` dataframe and the `pandas` library to create an executable Python code.
Here's the solution:

population_max = df['population'].max()
print("The city with the highest population is:", population_max[0])
```
Explanation:

* We use the `df['population'].max()` method to get the maximum value of the 'population' column in the dataframe. This returns a Series (a pandas data structure similar to a NumPy array) containing the maximum value.
* We then use the `print()` function to output the answer to the query, along with the city name.
* The final line of code is an executable Python expression that can be called using the `eval()` function. This expression will evaluate to the maximum population value and print the corresponding city name.
Note: In this solution, we assume that the dataframe 'df' has a 'population' column containing the population values for each city. If the column name is different in your case, you may need to adjust the code accordingly.
```
> Pandas Output: There was an error running the output as Python code. Error message: unexpected indent (<unknown>, line 1)
Traceback (most recent call last):
  File "c:\Temp\chatCSV\.venv\lib\site-packages\llama_index\query_engine\pandas_query_engine.py", line 58, in default_output_processor
    tree = ast.parse(output)
  File "C:\Program Files\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    Understood! To answer the query "What is the city with the highest population?", we can use the `df` dataframe and the `pandas` library to create an executable Python code.
IndentationError: unexpected indent
```

**Comment by logan-markewich** [comment]
@yapnel yea, the error here is that the LLM wrote extra text, rather than just the python code 😓 

I see you are using llama.cpp, so some extra prompt tuning might be needed. You'll probably want to edit the instruction_str https://github.com/jerryjliu/llama_index/blob/332a0a1f088bbe930536e6b87648d2988c03a2ff/llama_index/query_engine/pandas_query_engine.py#L102

In general though, open-source llms seem to be less reliable for structured output like this, at least that's my impression right now

**Comment by yapnel** [comment]
@logan-markewich I am new to all these and would appreciate if you could suggest a prompt that may resolve this problem. 

Btw, I can't tell from the log where the indentation that is causing the problem. Thanks

**Comment by logan-markewich** [comment]
@yapnel it's not the indentation that's causing an issue, it's the fact that it generated something other than python code 😅

It really just takes some fiddling around to get proper results out of less-competant models.

Its usually good practice to start with the current default and modify from there. I would start with something like this 

```
instruction_str = (
    "We wish to convert this query to executable Python code using Pandas.\n"
    "The final line of code should be a Python expression that can be called "
    "with the `eval()` function. This expression should represent a solution "
    "to the query. Your response should ONLY contain python code."
)
```

**Comment by yapnel** [comment]
Thank you. Will give it a try and report back.

**Comment by yapnel** [comment]
Swapping over to OpenAI the problem went away. Looks like open source model is not suitable for these sort of things yet.

**Comment by jc1518** [comment]
I have not tried it with open source LLM, but I made it work with Claude v2 with following prompting.

```
instruction_str = (
    "Human: Please convert this query to executable Python code using Pandas. "
    "The final line of code should be a Python expression that can be called "
    "with the `eval()` function. This expression should represent a solution "
    "to the query. Your response should ONLY contain python code without ``` or ```python or new line.\n\n"

    "Assistant: "
)
```
