### ISSUE TITLE
Cosine similarity value does not match

### ISSUE THREAD

**Issue by AravAct** [jerryjliu/llama_index#7277]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi , I would like to understand the cosine similarity scores. I have tried to replicate the scores using cosine similarity fn and dot product, but I am getting different numbers for the same chunk of text
![image](https://github.com/jerryjliu/llama_index/assets/122975761/fabb3e65-0565-42f1-a736-e4dfc6c1eba0)

In the image : scores_llama is similarity score from each node for 10 different nodes using node.score method
llama_cosine and llama_dot are calculated using simple np functions 
```from numpy import dot
from numpy.linalg import norm

def cosine_similarity(A, B):
    return dot(A, B) / (norm(A) * norm(B))

def dot_product(A, B):
    return dot(A, B)
```
cosine similarity and dot product value differs from llama-index score (I have not changed the default similarity method)
Acc to the code it should be the same, but it is not
```
def similarity(
    embedding1: EMB_TYPE,
    embedding2: EMB_TYPE,
    mode: SimilarityMode = SimilarityMode.DEFAULT,
) -> float:
    """Get embedding similarity."""
    if mode == SimilarityMode.EUCLIDEAN:
        # Using -euclidean distance as similarity to achieve same ranking order
        return -float(np.linalg.norm(np.array(embedding1) - np.array(embedding2)))
    elif mode == SimilarityMode.DOT_PRODUCT:
        product = np.dot(embedding1, embedding2)
        return product
    else:
        product = np.dot(embedding1, embedding2)
        norm = np.linalg.norm(embedding1) * np.linalg.norm(embedding2)
        return product / norm
```
Would like to understand the issue here

**Comment by AravAct** [comment]
I am using text-embeddings-ada-002 for all the embeddings , so there should not be any difference

**Comment by logan-markewich** [comment]
So as discussed on discord, `node.text` is not actually the text that is embedded

By default all metadata is sent to the embedding model, but the attribute `excluded_embed_metadata_keys` excludes certain keys from your metadata 

To check what text the embedding model uses, you can use this

```
from llama_index.schema import MetadataMode

for n in response.source_nodes:
  print(n.node.get_content(metadata_mode=MetadataMode.EMBED))
```
