### ISSUE TITLE
[Bug]: text-to-SQL example fails with the new LlamaCPP fallback

### ISSUE THREAD

**Issue by PepppoVal** [jerryjliu/llama_index#7278]
### Bug Description

The example of a text-to-SQL query that is provided here:
https://gpt-index.readthedocs.io/en/latest/examples/index_structs/struct_indices/duckdb_sql_query.html
fails with the latest 0.8.2.x 
when it tries to use the new default llm, which is 
`Using default LlamaCPP=llama2-13b-chat.`
as per the message that shows up when I instantiate a
`NLSQLTableQueryEngine`

I suspect the expected format of the first response, in which he the SQL query is generated, may be wrong. 
The error message, no matter the query I try to make, is always in the following form:

```
ProgrammingError: (duckdb.ParserException) Parser Error: syntax error at or near "Sure"
LINE 1: Sure, I'd be happy to help! Here's the ...
        ^
[SQL: Sure, I'd be happy to help! Here's the query to list all cities in reverse alphabetical order based on the 'city_name' column:
SQLQuery: SELECT city_name FROM city_stats ORDER BY city_name DESC;

This will return a list of all cities in the 'city_stats' table, sorted in reverse alphabetical order based on the 'city_name' column.

Now, let me run the query and provide the results:]
```

### Version

0.8.2.post1

### Steps to Reproduce

simply through the first example in: https://gpt-index.readthedocs.io/en/latest/examples/index_structs/struct_indices/duckdb_sql_query.html

**Comment by PepppoVal** [comment]
Thanks for the tip. Unfortunately, using a restrictive `text_to_sql_prompt` does not seem to have any effect.
It still returns the same error i.e.
ProgrammingError: (duckdb.ParserException) Parser Error: syntax error at or near "Sure"
```
LINE 1: Sure, I'd be happy to help! Here's the ...
        ^
[SQL: Sure, I'd be happy to help! Here's the SQL query to find the city with the highest population:
SQLQuery: SELECT city_name, population FROM city_stats WHERE population = (SELECT MAX(population) FROM city_stats);
This query uses a subquery to find the maximum population in the city_stats table and then selects only the rows where the population matches that value.
Now, let me run this query and provide the results:]
```

**Comment by logan-markewich** [comment]
Should merge a PR (linked above) that will help. Confirmed it worked with llama2-chat-13B and our SQL notebook demo

**Comment by PepppoVal** [comment]
Sounds great! Looking forward to  trying it out once released.
