### ISSUE TITLE
[Question]: How to add previous Chat context when querying an index?

### ISSUE THREAD

**Issue by niels-bosman** [jerryjliu/llama_index#7296]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am looking for a way to send the context of my chat application to Llama index via the .query() function but it seems like it only accepts a string:

```py
streaming_response = index.as_query_engine(
        streaming=True, similarity_top_k=1
    ).query(query_text)
```

I would like to know how I can make it so Llama understands the context of my chats like I can do with OpenAI:

```js
openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

Any tips on how I can achieve this using the Llama API? Thanks.

**Comment by logan-markewich** [comment]
@mcmoochi the context chat engine CAN be restrained, you just have to write a system prompt that encourages that behaviour. Tbh the system prompt is powerful if written well.

Other options include the 
- condense question chat engine (will query the index every time, but can lead to some "forced" logic/conversation)
- an agent with an index as a tool. Since the agent decides when to invoke the query engine, this is maybe less controlled, but...
- an agent with [forced tool calling](https://gpt-index.readthedocs.io/en/stable/examples/chat_engine/chat_engine_openai.html#force-chat-engine-to-query-the-index) -- you can setup an agent and force it to use a tool every time. Again, this can feel forced.

**Comment by mcmoochi** [comment]
> @mcmoochi the context chat engine CAN be restrained, you just have to write a system prompt that encourages that behaviour. Tbh the system prompt is powerful if written well.
> 
> Other options include the
> 
> * condense question chat engine (will query the index every time, but can lead to some "forced" logic/conversation)
> * an agent with an index as a tool. Since the agent decides when to invoke the query engine, this is maybe less controlled, but...
> * an agent with [forced tool calling](https://gpt-index.readthedocs.io/en/stable/examples/chat_engine/chat_engine_openai.html#force-chat-engine-to-query-the-index) -- you can setup an agent and force it to use a tool every time. Again, this can feel forced.

Thanks very much for the response. I have tried the system prompt, it doesn't seem to be working for me for some reason.

For example, I'm passing this system prompt: "Don't answer if question is not directly related to [My company]." and using. "how to cook a potato" as a control question. My index only consist of terms of conditions of products, currently the bot will give a detailed response on how to cook a potato...

Condense question seems to do the same thing, not sure if I'm doing something wrong. I'll try the agent forced too calling. Any help would be greatly appreciated!

Here are my codes:

```
custom_prompt = """
    Act friendly and charming \
    say 'I don't know' if question is not directly related to [my company]. \
    Make your responses short and concise. \
    If the question is not specific, ask for more information. \
    Use Australian english spelling and grammar. \
"""
```

  ```
def construct_index(directory_path):
      num_outputs = 512
      llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="text-davinci-003", max_tokens=num_outputs))
      service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
      docs = SimpleDirectoryReader(directory_path).load_data()
      index = GPTVectorStoreIndex.from_documents(docs, service_context=service_context, summary_template=custom_ft_prompt)
      index.storage_context.persist(persist_dir='index.json')
      return index
```

```
    def respond(message, chat_history):
        storage_context = StorageContext.from_defaults(persist_dir="index.json")
        index = load_index_from_storage(storage_context)
        chat_engine = index.as_chat_engine(
            chat_mode="condense_question", memory=memory)
        response=chat_engine.chat(message)
        ##appending message history
        bot_message = str(response)
        chat_history.append((message, bot_message))
        return "", chat_history
```

**Comment by niels-bosman** [comment]
@logan-markewich When using the chat engine instead of the query engine, don’t you lose the ability to also use the data as context? It also does not look like the chat engine supports streaming like the query engine does with `streaming=True`.

**Comment by logan-markewich** [comment]
@niels-bosman nope, you still get the data as context. Each chat engine uses the index under the hood in slightly different ways

Also, with chat engines, streaming is enabled by using specific endpoints -- `chat_engine.stream_chat()` and `chat_engine.astream_chat`

Then, you can iterate over the response

Going to link some docs pages that relevant, but I think it's safe to close this for now. Feel free to reach out on discord!

https://gpt-index.readthedocs.io/en/latest/core_modules/query_modules/chat_engines/usage_pattern.html

https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent.html#streaming-chat
