### ISSUE TITLE
Please help how to fix this

### ISSUE THREAD

**Issue by abganzon** [jerryjliu/llama_index#7300]
### Bug Description

[/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py](https://localhost:8080/#) in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    226     mode: Literal['before', 'after'] = 'before' if pre is True else 'after'
    227     if pre is False and skip_on_failure is not True:
--> 228         raise PydanticUserError(
    229             'If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.'
    230             ' Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.',

PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

### Version

0.8.3

### Steps to Reproduce

[/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py](https://localhost:8080/#) in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    226     mode: Literal['before', 'after'] = 'before' if pre is True else 'after'
    227     if pre is False and skip_on_failure is not True:
--> 228         raise PydanticUserError(
    229             'If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.'
    230             ' Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.',

PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

**Comment by logan-markewich** [comment]
Can you give more information? How did this get triggered? What pydantic version do you have?

**Comment by abganzon** [comment]
> Can you give more information? How did this get triggered? What pydantic version do you have?

when running it says error in the first line PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.vector_stores import PineconeVectorStore
from llama_index.storage.storage_context import StorageContext
from llama_index import load_index_from_storage

**Comment by kaechele** [comment]
Hitting this too, right now.

Completely fresh installation from PyPI using `pip install llama_index` in a virtualenv on Ubuntu 22.04 (Python 3.10.12).
Attempting the [Starter Tutorial in the docs](https://gpt-index.readthedocs.io/en/stable/getting_started/starter_example.html) is sufficient to trigger the error.

Full backtrace:
```
/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/felix/Development/llama_index_test/./llama_index_test.py", line 2, in <module>
    from llama_index import VectorStoreIndex, SimpleDirectoryReader
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/llama_index/__init__.py", line 12, in <module>
    from llama_index.data_structs.struct_type import IndexStructType
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/llama_index/data_structs/__init__.py", line 3, in <module>
    from llama_index.data_structs.data_structs import (
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/llama_index/data_structs/data_structs.py", line 14, in <module>
    from llama_index.schema import BaseNode, TextNode
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/llama_index/schema.py", line 215, in <module>
    class TextNode(BaseNode):
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/llama_index/schema.py", line 243, in TextNode
    def _check_hash(cls, values: dict) -> dict:
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/home/felix/Development/llama_index_test/venv/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.2/u/root-validator-pre-skip
```

`pip list` for that virtualenv. The following packages were installed into that venv using `pip install`:
* `llama-cpp-python[server]`
* `llama-index`
* `sentence-transformers`
<details>

```
$ pip list
Package                  Version
------------------------ ----------
aiohttp                  3.8.5
aiosignal                1.3.1
annotated-types          0.5.0
anyio                    3.7.1
async-timeout            4.0.3
attrs                    23.1.0
beautifulsoup4           4.12.2
certifi                  2023.7.22
charset-normalizer       3.2.0
click                    8.1.6
cmake                    3.27.2
dataclasses-json         0.5.14
diskcache                5.6.1
exceptiongroup           1.1.3
fastapi                  0.101.1
filelock                 3.12.2
frozenlist               1.4.0
fsspec                   2023.6.0
greenlet                 2.0.2
h11                      0.14.0
huggingface-hub          0.16.4
idna                     3.4
Jinja2                   3.1.2
joblib                   1.3.2
langchain                0.0.267
langsmith                0.0.24
lit                      16.0.6
llama-cpp-python         0.1.77
llama-index              0.8.3
MarkupSafe               2.1.3
marshmallow              3.20.1
mpmath                   1.3.0
multidict                6.0.4
mypy-extensions          1.0.0
nest-asyncio             1.5.7
networkx                 3.1
nltk                     3.8.1
numexpr                  2.8.5
numpy                    1.25.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
openai                   0.27.8
openapi-schema-pydantic  1.2.4
packaging                23.1
pandas                   2.0.3
Pillow                   10.0.0
pip                      22.0.2
pydantic                 2.2.0
pydantic_core            2.6.0
pydantic-settings        2.0.3
python-dateutil          2.8.2
python-dotenv            1.0.0
pytz                     2023.3
PyYAML                   6.0.1
regex                    2023.8.8
requests                 2.31.0
safetensors              0.3.2
scikit-learn             1.3.0
scipy                    1.11.1
sentence-transformers    2.2.2
sentencepiece            0.1.99
setuptools               59.6.0
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.4.1
SQLAlchemy               2.0.20
sse-starlette            1.6.5
starlette                0.27.0
sympy                    1.12
tenacity                 8.2.3
threadpoolctl            3.2.0
tiktoken                 0.4.0
tokenizers               0.13.3
torch                    2.0.1
torchvision              0.15.2
tqdm                     4.66.1
transformers             4.31.0
triton                   2.0.0
typing_extensions        4.7.1
typing-inspect           0.9.0
tzdata                   2023.3
urllib3                  1.26.16
uvicorn                  0.23.2
wheel                    0.41.1
yarl                     1.9.2
```

</details>

**Comment by kaechele** [comment]
In fact, a simple `import llama_index` is enough to trigger the error.

**Comment by logan-markewich** [comment]
@abganzon try downgrading your pydantic version -- `pip install pydantic==1.10.12`

Should have a PR soon that will help avoid this as well

**Comment by kaechele** [comment]
Downgrading worked.

Possibly unrelated but I also needed to `pip install unstructured==0.7.12` in order to use `download_loader('UnstructuredReader')`. Otherwise you'd hit ` NameError: name 'partition_pdf' is not defined. Did you mean: 'partition_xml'?`

**Comment by logan-markewich** [comment]
Ok, glad that worked! Will have a new release on pypi (v0.8.4) to avoid this.

RE the second point, also unrelated 😓 Seems like the unstructured loader on llama-hub likely needs it's reqs updated
https://github.com/emptycrown/llama-hub/tree/main/llama_hub/file/unstructured
