### ISSUE TITLE
Why `aquery` with default mode can only use sync `_get_response_default`?

### ISSUE THREAD

**Issue by Green-li** [jerryjliu/llama_index#732]
I want to use async create of openai.
But the default mode can only use sync get response.
When an use summarize mode in ListIndex, it raise an error:
```
query_cls = self._index_registry.type_to_query[index_struct_type][mode]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: <QueryMode.SUMMARIZE: 'summarize'>
```
So is there a option to choose use sync or async?

**Comment by Disiok** [comment]
Outdated, see latest docs.
