### ISSUE TITLE
[Bug]: faild to use OpenAI API in llms/OpenAI class 

### ISSUE THREAD

**Issue by sari-rev00** [jerryjliu/llama_index#7321]
### Bug Description

Following tutorial code raises type-error at openai library.
```
# environment:
OPENAI_API_KEY=xxxxx

# code:
from llama_index import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader(input_dir='your_data_dir').load_data()
index = VectorStoreIndex.from_documents(documents)
response = query_engine.query("any_query")

# error:
 '0.1' is not of type 'number' - 'temperature'
```

to solve this:
Change the type of "temperature" (llms/OpenAI class variable), from str to float.
`temperature: str = Field(description="The tempature to use during generation.")`
https://github.com/jerryjliu/llama_index/blob/main/llama_index/llms/openai.py#L42

### Version

0.8.5

### Steps to Reproduce

Kidly refer to bug description.

**Comment by yisding** [comment]
Thanks for the bug report!
