### ISSUE TITLE
[Question]: How to print the number of tokens used on each query? I want to print that. 

### ISSUE THREAD

**Issue by rahul311291** [jerryjliu/llama_index#7323]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to print the number of tokens used on each query? I want to print that.

**Comment by rahul311291** [comment]
this is not working. Can you please help me with a very clear code ?

**Comment by logan-markewich** [comment]
@rahul311291 yea the bot tried its best there lol

Here's an actual notebook example https://gpt-index.readthedocs.io/en/stable/examples/callbacks/TokenCountingHandler.html

**Comment by uzumakinaruto19** [comment]
token_counter.total_embedding_token_count always returning 0

**Comment by devstein** [comment]
@uzumakinaruto19 As of now, Dosu only responds to the author of issues. If you have any feature requests for Dosu, let me know!

**Comment by logan-markewich** [comment]
@uzumakinaruto19 I think you messaged in discord? But yea, token counting only works for streaming in newer versions of llama-index
