### ISSUE TITLE
[Bug]: module 'llama_index' has no attribute 'global_service_context'

### ISSUE THREAD

**Issue by fsndzomga** [jerryjliu/llama_index#7327]
### Bug Description

Here is what I am trying to do:
# Building and querying an index

from llama_index import VectorStoreIndex

index = VectorStoreIndex.from_documents(branch_documents)

query_engine = index.as_query_engine()

response = query_engine.query("How to create a github repository reader ?")

print(response)

Here is the bug:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-3b211f20ab7f>](https://dpylnivaw5m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230817-060103-RC00_557775453#) in <cell line: 5>()
      3 from llama_index import VectorStoreIndex
      4 
----> 5 index = VectorStoreIndex.from_documents(branch_documents)
      6 
      7 query_engine = index.as_query_engine()

1 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/indices/base.py](https://dpylnivaw5m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230817-060103-RC00_557775453#) in from_documents(cls, documents, storage_context, service_context, show_progress, **kwargs)
     90         """
     91         storage_context = storage_context or StorageContext.from_defaults()
---> 92         service_context = service_context or ServiceContext.from_defaults()
     93         docstore = storage_context.docstore
     94 

[/usr/local/lib/python3.10/dist-packages/llama_index/indices/service_context.py](https://dpylnivaw5m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230817-060103-RC00_557775453#) in from_defaults(cls, llm_predictor, llm, prompt_helper, embed_model, node_parser, llama_logger, callback_manager, system_prompt, query_wrapper_prompt, chunk_size, chunk_overlap, context_window, num_output, chunk_size_limit)
    120             chunk_size = chunk_size_limit
    121 
--> 122         if llama_index.global_service_context is not None:
    123             return cls.from_service_context(
    124                 llama_index.global_service_context,

AttributeError: module 'llama_index' has no attribute 'global_service_context'

### Version

Version: 0.8.5.post1

### Steps to Reproduce

# Import the Github Repository Reader class
from llama_index.readers import GithubRepositoryReader
import os

os.environ["GITHUB_TOKEN"] = ""

# Read the llama-index repository
reader = GithubRepositoryReader("jerryjliu", 
                                "llama_index", 
                                ignore_directories=[".github", ".vscode", 
                                                    "benchmarks", "docs", 
                                                    "examples", "experimental",
                                                    "scripts", "tests"])

# Building and querying an index

from llama_index import VectorStoreIndex

index = VectorStoreIndex.from_documents(branch_documents)

query_engine = index.as_query_engine()

response = query_engine.query("How to create a github repository reader ?")

print(response)

**Comment by logan-markewich** [comment]
@fsndzomga I'm not able to reproduce this on my end. While the bots response may help, there's no reason why what you have would cause this.

Maybe try uninstalling + reinstalling the package? Or creating a fresh venv?

**Comment by fsndzomga** [comment]
I did uninstall and reinstall and I still got the same error. Let me spin a different env and see how it goes.

One thing I noticed I still get errors for some dependencies not installed. Why not include all these dependencies so that when I install llama-index, I get them all instead of having to get an error and then manually installing ?

**Comment by fsndzomga** [comment]
It worked when instead of setting the openai api key through os.environ I did this:
openai.api_key = apikey

**Comment by fsndzomga** [comment]
Thanks for the help @logan-markewich !

**Comment by logan-markewich** [comment]
Ah yea, I've had to do that before, especially in notebooks for whatever reason.

Btw, we can't include all dependencies, so optional/non-core features have optional installs like that. If we included all dependencies, it would be impossible to manage 😅

Anyways, glad you got it working 💪

**Comment by rawwerks** [comment]
i'm having the same issue in a jupyter notebook, but unforunately @fsndzomga 's fix of manually writing the openai api key is not working. 
```
AttributeError: module 'llama_index' has no attribute 'global_service_context'

```

@logan-markewich is there a simple demo jupyter notebook with just a basic local embedding example that i can copy?

```
documents = SimpleDirectoryReader("../path").load_data()
index = VectorStoreIndex.from_documents(documents)
```

**Comment by logan-markewich** [comment]
@rawwerks are you working in a notebook? Try restarting the runtime/kernel. Can also try installing/re-installing llama-index

To use local embeddings, easiest is just 

```
from llama_index import ServiceContext 

service_context = ServiceContext.from_defaults(embed_mod="local:/BAAI/bge-base-en-v1.5")

index = VectorStoreIndex.from_documents(documents, service_context=service_context)
```

**Comment by rawwerks** [comment]
ok all i had to do was restart the jupyter notebook runtime...thanks @logan-markewich 

(probably something to do with the fact that i only thought to install llama_index in a later cell and then tried to use it right away.)
