### ISSUE TITLE
[Question]: How do I integrate a custom vector store index?

### ISSUE THREAD

**Issue by mhk197** [jerryjliu/llama_index#7344]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Team,

I am working with a hosted vector store index that I access via a python client. The index is hosted in the cloud, and is coupled with a served embedding model as well with a table of metadata. It is already populated with the relevant data. I can query it with: 

```
client.query(
query_string, 
k={n_similar_chunks_to_retrieve}, 
metadata={dict of metadata fields to include}
})
```

It will embed the query, perform ANN on the index, and return a dictionary consisting of the retrieved strings and their metadata. With this setup, I do not load the embedding model -- the only functionality that the API would expose to the llamaindex app is the above query method. 

How would I go about using this as a llamaindex retriever/vector store? Is it possible, even though the embedding model/indexing/storage would be managed separately from the LLM?

Thank you!

**Comment by mhk197** [comment]
@dosu-bot 

Thank you! 

Can you provide more guidance on how to create a custom VectorStore class? In particular, llama-index will not have access to manage the vector database or index -- just to retrieve query results. So there is no use for methods that add, delete, or update the data, or for those that create or persist the database.

**Comment by logan-markewich** [comment]
Haha wow, the bot is doing surpringly well here.

Yea, basically you just need to implement the init and query/aquery methods. You may also have to implement stubs for the unused functions if you get errors (i.e. add, etc.)

**Comment by logan-markewich** [comment]
Going to close this issue for now! Feel free to reach out on the discord if you need help building the vector store wrapper 👍🏻
