### ISSUE TITLE
[Question]: GPTVectorStoreIndex

### ISSUE THREAD

**Issue by tovsali** [jerryjliu/llama_index#7349]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I try to make chat gpt, which answer on my questions with using my local knowledge base. My code: 
# Импорт необходимых пакетов
import os
import pickle

from google.auth.transport.requests import Request

from google_auth_oauthlib.flow import InstalledAppFlow
from llama_index import GPTVectorStoreIndex, download_loader

os.environ['OPENAI_API_KEY'] = 'key'

def authorize_gdocs():
    google_oauth2_scopes = [
        "https://www.googleapis.com/auth/documents.readonly"
    ]
    cred = None
    if os.path.exists("token.pickle"):
        with open("token.pickle", 'rb') as token:
            cred = pickle.load(token)
    if not cred or not cred.valid:
        if cred and cred.expired and cred.refresh_token:
            cred.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("credentials.json", google_oauth2_scopes)
            cred = flow.run_local_server(port=0)
        with open("token.pickle", 'wb') as token:
            pickle.dump(cred, token)

# функция для авторизации или загрузки последних учетных данных
authorize_gdocs()

# инициализируйте LlamaIndex google doc reader
GoogleDocsReader = download_loader('GoogleDocsReader')

# список документов google, которые нужно проиндексировать
gdoc_ids = ['key']
loader = GoogleDocsReader()

# загрузка gdocs и их индексация
documents = loader.load_data(document_ids=gdoc_ids)
index = GPTVectorStoreIndex(documents, show_progress=True)

This is the beginning of the code, but on the last line the program runs indefinitely. I see this: Generating embeddings: 0%| | 0/1 [00:00<?, ?it/s]
And it doesn't change. Help me please.

**Comment by logan-markewich** [comment]
The bot is wrong lol

I'm not sure why the embeddings are stalling for you (network issues? VPN?). 

Two suggestions that could help?

1. Also set the key on the openai module
```
import os
import openai

os.environ['OPENAI_API_KEY'] = 'key'
openai.api_key = os.environ['OPENAI_API_KEY']
```

2. If that fails, just use local embeddings? Although this assumes that the LLM will work later for actual queries 
```
from llama_index import ServiceContext, set_global_service_context

ctx = ServiceContext.from_defaults(embed_model="local")
set_global_service_context(ctx)
```

**Comment by tovsali** [comment]
Thx
