### ISSUE TITLE
[Bug]: BaseChatEngine.chat() returns None if OpenAi is used and function_call="query_engine_tool"

### ISSUE THREAD

**Issue by NoahMoritz** [jerryjliu/llama_index#7359]
### Bug Description

Hello all,

I've tried a few different scenarios but the basic underlying issue seems to be, that whenever I use a Cheat Engine with OpenAi, the return value from all chat functions is None. Here a sample code where the issues exists:

```python
import os
os.environ["OPENAI_API_KEY"] = '----------------------------------'

from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.chat_engine.types import ChatMode
from llama_index.llms import OpenAI

service_context = ServiceContext.from_defaults(llm=OpenAI(model="gpt-3.5-turbo-0613"))
documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context)

chat_engine = index.as_chat_engine(chat_mode=ChatMode.OPENAI, Verbose=True)

while True:
    user_msg = input("User: ")
    print(chat_engine.chat(user_msg, function_call="query_engine_tool"))
```

If I remove the function_call, I get a response (which then does not use the index, no matter what the question is). If I leave it in, (I've tried this in another scenario) then it does ask questions to the query engine (so it's being used and the results are good), but the result is still None.

What I have also tried:
- using GPT-4
- using an old version of llama-index
- trying different ways to create the chat engine
- using different methods (async chat, ...)
- using a different venv

I don't know if I'm doing something wrong or if this is bug. Since (at least for me) it is reproducible all the time in different scenarios, I assume it is a bug. If I'm wrong, help would be appreciated.

Best

### Version

0.8.5.post2

### Steps to Reproduce

Use the code, but your API Key in and but some random Textfile into a folder called "data". Then ask questions about this file.

**Comment by NoahMoritz** [comment]
@dosu-bot
Okay, I analyzed the issue based on your help. I think, what you said might not be the issue. When I look into the chat history, I can see that the there is one "USER" message, 7 "ASSISTANT" messages and 6 "FUNCTION" messages. The last message is a assistant message which contains the content None. But it contains one function call.
The reason why I think this might be a problem is, that the _max_function_calls is defaulted to 5. So the LLM tries to call a function, but the limit is exceeded and therefore the content is returned.

**Comment by NoahMoritz** [comment]
@dosu-bot
Okay, i think I now found the exact cause. The max function calls loop is the problem, because the call to OpenAi will always set the function_call parameter in the API (see [Open Ai API documentation](https://platform.openai.com/docs/api-reference/chat/create#chat/create-function_call)) to whatever is defined. The model will only finish with a user message if it is set to "none" or "auto".
This implementation however (when it reaches the limit) just returns. Instead one of the following things should happen:
- Either the first request only should contain the request to call the function
- After the limit is reached there should be a last request with "none" in the function_call parameter of the OpenAi API, because otherwise there will be no human readable error message.

**Comment by logan-markewich** [comment]
@NoahMoritz yea I just ran into this today too. It's weird that it USED to work according to the notebook showcasing the feature.

I agree, the function call should only be forced for the first iteration, then disregarded. I can try and fix this later today (or feel free to take a stab at it as well!)
