### ISSUE TITLE
[Bug]: IndexStore is not updated when using PgVectorStore

### ISSUE THREAD

**Issue by rendyfebry** [jerryjliu/llama_index#7360]
### Bug Description

As per my understanding, IndexStore has the responsibility of keeping track of which Documents/Nodes belong to which index, by adding the map to `nodes_dict`

This is useful if we want to use multiple indices in our system. 

```
[
    {
        _id: 'eastern',
        __type__: 'vector_store',
        __data__: '{"index_id": "eastern", "summary": null, "nodes_dict": {"203eeae4-7814-4ffd-8b2d-84dae91fbcb7": "203eeae4-7814-4ffd-8b2d-84dae91fbcb7", "22e00d3f-49aa-444c-bca0-167448a5c8ad": "22e00d3f-49aa-444c-bca0-167448a5c8ad", "734c4ef7-c7d3-46ba-af0f-a6e0031f7351": "734c4ef7-c7d3-46ba-af0f-a6e0031f7351"}, "doc_id_dict": {}, "embeddings_dict": {}}'
    },
    {
        _id: 'western',
        __type__: 'vector_store',
        __data__: '{"index_id": "western", "summary": null, "nodes_dict": {"8ab5c446-3ae5-4952-ba79-ee5141b96338": "8ab5c446-3ae5-4952-ba79-ee5141b96338", "801bf16c-3a34-452b-bd33-143f56c19945": "801bf16c-3a34-452b-bd33-143f56c19945", "154a3c33-1325-49cd-8e35-2bc45cf430c0": "154a3c33-1325-49cd-8e35-2bc45cf430c0"}, "doc_id_dict": {}, "embeddings_dict": {}}'
    }
]
```

A problem will happen when we introduce `PgVectorStore`. When using this Vector Store, the IndexStore won't be updated anymore.

```
{
    _id: 'eastern',
    __type__: 'vector_store',
    __data__: '{"index_id": "eastern", "summary": null, "nodes_dict": {}, "doc_id_dict": {}, "embeddings_dict": {}}'
}
```

This won't be a problem if we only have 1 index, but when having multiple indexes, we expect the query_engine to only search from Documents/Nodes that belong to a specific index. But with this bug, the query will always run against all Documents/Nodes.

### Version

v0.8.5.post2

### Steps to Reproduce

Create multiple indices and store them to PgVectorStore

**Comment by rendyfebry** [comment]
@dosu-bot

A good start, can you give example how other vector_stores implement this?

**Comment by rendyfebry** [comment]
Looks like it's expected behavior when using VectorStoreIndex implementation which stores the whole index in VectorStore (`stores_text=True`, PgVectorStore is [one of them](https://github.com/jerryjliu/llama_index/blob/main/llama_index/vector_stores/postgres.py#L42)), LlamaIndex won't bother updating the index store and docstore anymore,  unless we specifically override the behavior.

```python
western_index = VectorStoreIndex.from_documents(documents,
                                                service_context=self.service_context,
                                                storage_context=self.storage_context,
                                                store_nodes_override=True) # Override
```

**Comment by rendyfebry** [comment]
> When using VectorStoreIndex implementation which stores the whole index in VectorStore (stores_text=True, PgVectorStore is [one of them](https://github.com/jerryjliu/llama_index/blob/main/llama_index/vector_stores/postgres.py#L42)), LlamaIndex won't bother updating the index store and docstore anymore

Hi @logan-markewich @jerryjliu 

Just curious, when the VectorStore stores the whole index setup (stores_text=True) the Index Store and Docstore basically become useless. If so, can we set them to `None` so we don't need to provision and maintain them at all?

I know we can set them to low/cheap storage solution like S3 FS or Dynamo, but still. :D

**Comment by longhotsummer** [comment]
This still seems to be a problem with `refresh_ref_docs()` because it calls `self._docstore.get_document_hash()`, expecting the docstore to be up-to-date. Instead, I think it should be getting the metadata directly from the psql table and then calculating the hash.
