### ISSUE TITLE
[Question]: Is there a way we can use select OpenAI Key dynamically?

### ISSUE THREAD

**Issue by rendyfebry** [jerryjliu/llama_index#7377]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

As per documentation, the only possible way to inject OpenAI key is by using the environment variable `OPENAI_API_KEY`.

If let's say I have multiple API Kesy and want to change between them on the fly, what's the best way to do that?

**Comment by rendyfebry** [comment]
Cool, thank you

**Comment by rendyfebry** [comment]
Actually it doesn;t work reliably

**Comment by logan-markewich** [comment]
A similar thing also works for embeddings

![image](https://github.com/jerryjliu/llama_index/assets/22285038/1a89d75b-448b-457d-b698-697c9a3aa179)

**Comment by rendyfebry** [comment]
Hi @logan-markewich 

Thanks for testing that. When I do it standalone like that, it seems to work, but when I use that with the rest of the system it doesn't work.

```
llm_predictor = LLMPredictor(llm=OpenAI(temperature=self.__llm_temperature,
                                        model=self.__llm_model_name,
                                        max_tokens=self.__llm_num_outputs))
service_ctx = ServiceContext.from_defaults(llm_predictor=llm_predictor,
                                           node_parser=node_parser,
                                           callback_manager=self.__get_llm_callback_manager())

index = VectorStoreIndex([], service_context=service_ctx, storage_context=storage_ctx)
```

**Comment by rendyfebry** [comment]
Found one problem here.

When `ServiceContext` initializes without passing `embed_model`, it will call `resolve_embed_model` which will try to use `OpenAIEmbedding()`  without any parameter. Therefore the custom `api_key` won't be respected and fallback to `OPENAI_API_KEY`

https://github.com/jerryjliu/llama_index/blob/main/llama_index/embeddings/utils.py#L52

For now, I will pass the embed_model to ServiceContext, but would be great if we could pass the api_key down the line automatically.

**Comment by logan-markewich** [comment]
Since the embed model and llm are completely separate abstractions, it's a bit tricky to nicely pass the openai key to both of them under the hood, since that is explicit to openai?

For now, I think having to initialize both the embed model and llm is a fair compromise for this use case :)
