### ISSUE TITLE
[Question]: After using TextSplitter to split a text, how can I obtain the indices of the split texts in the original text?

### ISSUE THREAD

**Issue by MBearo** [jerryjliu/llama_index#7379]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```python
from llama_index import Document
from llama_index.node_parser import SimpleNodeParser

node_parser = SimpleNodeParser.from_defaults(chunk_size=1024, chunk_overlap=20)

nodes = node_parser.get_nodes_from_documents([Document(text="long text")], show_progress=False)
```
How can I obtain the index positions of each node in the original text?

**Comment by logan-markewich** [comment]
Currently this is not possible, although it used to be. But keeping track of this was limiting any development or improvement on our text splitters, and causing the text splitter implementations to be very difficult to debug and use

The bots suggestion is around the correct lines though, `find()` will be useful here
