### ISSUE TITLE
[Bug]: Temperature broken on OpenAI LLM 

### ISSUE THREAD

**Issue by RobertPurdy** [jerryjliu/llama_index#7381]
### Bug Description

Setting the temperature on OpenAI LLM is broken. 

When I set any float value using the temperature arg or the default value, it is converted to an int. 

The bug is here in openai.py line 42: temperature: int = Field(description="The tempature to use during generation.") 

The pydantic type should be float in the class definition.

### Version

0.8.8

### Steps to Reproduce

from llama_index.llms import OpenAI
llm = OpenAI(temperature=0.5)
print(llm)

### Relevant Logs/Tracbacks

```shell
callback_manager=<llama_index.callbacks.base.CallbackManager object at 0x10101c350> model='gpt-3.5-turbo' temperature=0 max_tokens=None additional_kwargs={} max_retries=10
```

**Comment by logan-markewich** [comment]
huh, could have sworn I fixed this. Will make a PR shortly

**Comment by RobertPurdy** [comment]
Thanks Logan!
