### ISSUE TITLE
[Question]: Is it possible to append new nodes to an existing index without overriding the whole index?

### ISSUE THREAD

**Issue by DomenicoMireles** [jerryjliu/llama_index#7383]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a database to which I constantly add new data, then I made an index to query that database, but since that database is constantly being updated, every time the database changes, I need to overwrite the index with the new database nodes, which are the exact same except for the new ones.
Is there a way I could just add the new elements to the same index instead of overwriting it?

**Comment by logan-markewich** [comment]
If you have a way of setting a consistent doc id for each input document, you could use the refresh function.

Basically, the same source document should have some consistent ID for this to work properly. For example, it could be a filename, or maybe the thread_id for a thread of discord messages. Just has to be static

https://gpt-index.readthedocs.io/en/stable/core_modules/data_modules/index/document_management.html#refresh
