### ISSUE TITLE
llm versus llm_predict

### ISSUE THREAD

**Issue by erlebach** [jerryjliu/llama_index#7385]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

llm  and llm_predictor are two of the arguments of service_context.from_defaults. I don't understand the difference between the two. Is that clearly explained anywhere? Thanks.

**Comment by erlebach** [comment]
Thanks for the veryquick response. Can you provide an example of why llm_predictor is ever needed given that there is a default value if it is not provided. I also did not find mention in the documentation that only one of the two can be provided. 

    Gordon

**Comment by logan-markewich** [comment]
llm_predictor is basically a non-user facing tech-debt object lol

All it does is format prompts before calling the LLM

The actual LLM object is the thing generating text, and is used by the llm predictor. 

When you pass in the llm object to the service context, it gets wrapped by an llm_predictor object automatically. You only ever really need to worry about the LLM object
