### ISSUE TITLE
[Bug]: Unable to build the VectorStoreIndex from simple PDF documents

### ISSUE THREAD

**Issue by mukundhareddy1996** [jerryjliu/llama_index#7391]
### Bug Description

I was following the [documentation ](https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/vector_store_guide.html)and trying to load the simple PDF document using SimpleDirectoryReader. 

`documents = SimpleDirectoryReader(r"MyLocalPath\InputFiles").load_data()`

_I am using a valid Azure OpenAI keys with turbo 3.5 model and text-embedding-ada-002 model for embeedings._

The data loading is done successfully and post that the vector indexing is not happening and returning the **RetryError[]**. Tried the documents directly from wikipedia using download_loader, but still the same error as below. 

`vector_index = VectorStoreIndex.from_documents(documents)`

Tried the other way as below:
_From the documents I have created nodes and tried to index those nodes too. But still the same error._ 

Error:
---------------------------------------------------------------------------
```
InvalidRequestError                       Traceback (most recent call last)
File [c:\\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py:382](file:///C://AppData/Local/Programs/Python/Python310/lib/site-packages/tenacity/__init__.py:382), in Retrying.__call__(self, fn, *args, **kwargs)
    381 try:
--> 382     result = fn(*args, **kwargs)
    383 except BaseException:  # noqa: B902

File [c:\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\embeddings\openai.py:167](file:///C://AppData/Local/Programs/Python/Python310/lib/site-packages/llama_index/embeddings/openai.py:167), in get_embeddings(list_of_text, engine, **kwargs)
    165 list_of_text = [text.replace("\n", " ") for text in list_of_text]
--> 167 data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
    168 return [d["embedding"] for d in data]

File [c:\\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\embedding.py:33](file:///C://AppData/Local/Programs/Python/Python310/lib/site-packages/openai/api_resources/embedding.py:33), in Embedding.create(cls, *args, **kwargs)
     32 try:
---> 33     response = super().create(*args, **kwargs)
     35     # If a user specifies base64, we'll just return the encoded string.
     36     # This is only for the default case.

File [c:\\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py:149](file:///C://AppData/Local/Programs/Python/Python310/lib/site-packages/openai/api_resources/abstract/engine_api_resource.py:149), in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    127 @classmethod
    128 def create(
    129     cls,
   (...)
    136     **params,
    137 ):
...
--> 326     raise retry_exc from fut.exception()
    328 if self.wait:
    329     sleep = self.wait(retry_state)

RetryError: RetryError[]
```

### Version

llama-index 0.8.8
Python 3.10.0

### Steps to Reproduce

Try to import the document form wikipedia and load it using download_loader

`from llama_index import download_loader 
WikipediaReader = download_loader("WikipediaReader") 
loader = WikipediaReader() 
documents = loader.load_data(pages=["2023 in science"], auto_suggest=False)`

Post getting the documents loaded. Now try to create a vector indexer using the below code.
`vector_index = VectorStoreIndex.from_documents(documents)`

**Comment by mukundhareddy1996** [comment]
I am using Azure openAI and the keys and endpoints I have provided are correct. The reason I also tried to create the knowledge graph indexer via Neo4J and it is working and I am able to get the result for the same document. But the error exists only with the VectorStoreIndex.

**Comment by logan-markewich** [comment]
@mukundhareddy1996 the kg index doesn't use embeddings.

If you are using azure, can you double check your setup follows this guide? Setting the global service context is pretty important for azure

https://gpt-index.readthedocs.io/en/stable/examples/customization/llms/AzureOpenAI.html

**Comment by mukundhareddy1996** [comment]
Thanks @logan-markewich 

I followed that document and changed the code a little bit and it worked.

`import os`
`import json`
`import openai`
`from langchain.embeddings import OpenAIEmbeddings`
`from llama_index.llms import AzureOpenAI`
`from llama_index import LangchainEmbedding`
`from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext`
`import logging`
`import sys`

`from IPython.display import Markdown, display`

```
logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output
```
`logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))`

```
openai.api_type = "azure"
openai.api_base = "Your Azure OpenAI deployment URL"
openai.api_version = "2023-03-15-preview"
os.environ["OPENAI_API_KEY"] = "Your Azure OpenAI key"
openai.api_key = os.getenv("OPENAI_API_KEY")
```

//llm = AzureOpenAI(engine="turbo35", mode="gpt-35-turbo")
```
llm = AzureOpenAI(
    deployment_name="Your turbo 3.5 Deployment Name",
    model_name ="gpt-35-turbo",
    temperature=0,
    openai_api_version=openai.api_version,
    model_kwargs={
        "api_key": openai.api_key,
        "api_base": openai.api_base,
        "api_type": openai.api_type,
        "api_version": openai.api_version,
    },
)
llm_predictor = LLMPredictor(llm=llm)
```

//You need to deploy your own embedding model as well as your own chat completion model
```
embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="Your Embeddings deployment name",
        openai_api_key=openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_type=openai.api_type,
        openai_api_version="2023-03-15-preview",
    ),
    embed_batch_size=1,
)
```

```
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embedding_llm,
)
```

`set_global_service_context(service_context)`

**Comment by yuvansharma** [comment]
When trying to define llm = AzureOpenAI(deployment_name = ....), I am getting the error "you must define an engine parameter". Any ideas how to fix that? I'm using llama-index 0.8.10 and langchain 0.0.274.

**Comment by logan-markewich** [comment]
@yuvansharma try to follow the guide I sent above closely. Usually setting a global service context solves most issues

**Comment by yuvansharma** [comment]
@logan-markewich Yup, I followed the guide, and I'm getting the same issue that the author was receiving, of not being able to make a VectorStoreIndex. I have set all environment variables correctly. This is my code, any insight would be greatly appreciated:

`llm = AzureOpenAI(engine="gpt-4-default-version", model="gpt-4", temperature=0)


llm_predictor = LLMPredictor(llm=llm)


embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="gpt-4-default-version",
        openai_api_key=openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_type=openai.api_type,
        openai_api_version=openai.api_version,
    ),
    embed_batch_size=1,
)

documents = SimpleDirectoryReader(input_dir="UploadedFiles").load_data()

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embedding_llm,
)

set_global_service_context(service_context)

index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()`

**Comment by mukundhareddy1996** [comment]
The embeedings model name which you provided is gpt-4. Please deploy the model text-ada-embeedings 002 and use that. Hope this resolves your issue.

**Comment by yuvansharma** [comment]
oh I see. Thank you so much! How can I deploy the text-ada-embeddings model in Azure? I only see options for gpt-3,gpt-4, gpt-3.5.

**Comment by harshitsinghai77** [comment]
@yuvansharma 

![image](https://github.com/jerryjliu/llama_index/assets/30886142/0956663c-3689-4b40-97f1-9ad77c22e48b)

Also you can refer this - https://gpt-index.readthedocs.io/en/stable/examples/customization/llms/AzureOpenAI.html

**Comment by harshitsinghai77** [comment]
I was running into a weird error saying resource not found:
This is what fixed the issue.

`openai.api_version = "2023-05-15"`
