### ISSUE TITLE
[BUG]: KnowledgeGraphRAGRetriever returns syntax error

### ISSUE THREAD

**Issue by salahaz** [jerryjliu/llama_index#7392]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

@wey-gu @logan-markewich I have been currently using the KnowledgeGraphRAGRetriever on an existing NebulaGraph space, and it throws the following error:

![nebula-error](https://github.com/jerryjliu/llama_index/assets/41476094/11350e45-7d4a-44de-aeb4-35fc21b6b45e)

I have done some digging and found out that it's an issue with executing the multi-hop subgraph query in the flat_rel_map function. The query failed on the db side. Do you think there's an issue with the way the query and the params are being passed?

**Comment by wey-gu** [comment]
Dear @salahaz

Is it possible to paste the full query here?
Would you mind sharing some details of your graphstore arguments? 

Thanks!

**Comment by salahaz** [comment]
@wey-gu 
Here are the graphstore arguments I am using.

![graphstore](https://github.com/jerryjliu/llama_index/assets/41476094/e15be568-f595-47a3-a108-dba7b0073c62)

I think the issue is related to how the query at llama_index/graph_stores/nebulagraph.py line 410 is being constructed or formatted because running the same exact query in the nebula console works fine for me.

**Comment by salahaz** [comment]
@wey-gu I think I found where the issue is:
https://github.com/jerryjliu/llama_index/blob/39ff38293b5d4d1fc33d8fbadacf9bb57861ccbe/llama_index/graph_stores/nebulagraph.py#L410-L435

In the following query, a space is required between flattened_rels and RETURN at line 430, otherwise, they get concatenated together when sent to nebula

**Comment by salahaz** [comment]
@wey-gu after making that fix, I am not receiving the SyntaxError anymore but instead a SemanticError as seen below
![llama_error2](https://github.com/jerryjliu/llama_index/assets/41476094/511f0ee8-5f20-4690-8662-cd9a16ca118d)

However, the edge type exists in the nebula schema and running the same query from line 430 directly in the nebula console works, but through llama_index it throws the error in the screenshot. Any suggestions?

**Comment by wey-gu** [comment]
> In the following query, a space is required between flattened_rels and RETURN at line 430, otherwise, they get concatenated together when sent to nebula

Oh, sorry my bad on this.

**Comment by wey-gu** [comment]
> However, the edge type exists in the nebula schema and running the same query from line 430 directly in the nebula console works, but through llama_index it throws the error in the screenshot. Any suggestions?

What if you temporarily remove `targets` from edge_types and recreate graph store?

Just to know if it's related to my impl. in llamaindex or state of NebulaGrpah itself.

**Comment by salahaz** [comment]
Without the "target" edge type, it gives me `Storage Error: RPC failure, probably timeout.`
![llama-error-3](https://github.com/jerryjliu/llama_index/assets/41476094/0fcc26a4-c342-418d-8919-dafedbc38c27)

Not sure why both errors. Any idea why?

**Comment by wey-gu** [comment]
Dear @salahaz ,

Thanks, I locally tested(this time I created Heterogeneous graph local e2e notebooks, future changes will execute them first, thanks to logan's ninja fix: https://github.com/jerryjliu/llama_index/pull/7398/commits/4f9f9812551b55e06ed206d39b15a805c96487cb the graph_store should be clean now.

For the RPC failure, could you reproduce it via nebula-console? If yes, could you help check logs in graphd/storaged?

Can you help share the query in text here or via Discord?

Some thing should be triggered in the NebulaGraph server side in your case now, let's see what happened with your query.

**Comment by salahaz** [comment]
Hello @wey-gu,

Great the query syntax error is fixed now. Regarding the RPC failure, this is what I found in the logs.

for graphd:
`
E20230825 10:17:35.264469    51 StorageClientBase-inl.h:227] Request to "storaged2":9779 failed: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.264623    52 StorageClientBase-inl.h:227] Request to "storaged1":9779 failed: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.265307    53 StorageClientBase-inl.h:227] Request to "storaged0":9779 failed: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.265412    37 StorageClientBase-inl.h:143] There some RPC errors: RPC failure in StorageClient: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.265483    37 StorageClientBase-inl.h:143] There some RPC errors: RPC failure in StorageClient: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.265511    37 StorageClientBase-inl.h:143] There some RPC errors: RPC failure in StorageClient: Failed to write to remote endpoint. Wrote 0 bytes. AsyncSocketException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E20230825 10:17:35.265585    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 8
E20230825 10:17:35.265599    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 1
E20230825 10:17:35.265605    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 6
E20230825 10:17:35.265633    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 10
E20230825 10:17:35.265642    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 4
E20230825 10:17:35.265650    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 2
E20230825 10:17:35.265656    37 StorageAccessExecutor.h:47] Traverse failed, error E_RPC_FAILURE, part 9
E20230825 10:17:35.266367    23 QueryInstance.cpp:151] Storage Error: RPC failure, probably timeout., query: WITH map{`true`: '-[', `false`: '<-['} AS arrow_l,     map{`true`: ']->', `false`: ']-'} AS arrow_r MATCH (s)-[e:`located-at`|`uses`|`part-of`|`indicates`|`mitigates`|`subtechnique-of`*..2]-()   WHERE id(s) IN $subjs   WITH     id(s) AS subj, [rel IN e |   [CASE type(rel)   WHEN "located-at" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)] WHEN "uses" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)] WHEN "part-of" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)] WHEN "indicates" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)] WHEN "mitigates" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)] WHEN "subtechnique-of" THEN   arrow_l[tostring(typeid(rel) > 0)] +  rel.`_type` +  arrow_r[tostring(typeid(rel) > 0)]   END,   CASE typeid(rel) > 0    WHEN true THEN dst(rel)    WHEN false THEN src(rel)  END  ] ] AS rels   WITH    subj,    REDUCE(acc = collect(NULL), l in rels | acc + l) AS         flattened_rels  RETURN  subj,  REDUCE(acc = subj, l in flattened_rels | acc + ', ' + l ) AS       flattened_rels
E20230825 10:21:29.121176 15646 FunctionUdfManager.cpp:41] UDF Folder doesn't Exist!
E20230825 10:26:29.111290 15646 FunctionUdfManager.cpp:41] UDF Folder doesn't Exist!
E20230825 10:31:29.113134 15646 FunctionUdfManager.cpp:41] UDF Folder doesn't Exist!
`

For the storaged logs: 
`
E20230825 10:34:33.997503     1 MetaClient.cpp:112] Heartbeat failed, status:Wrong cluster!
I20230825 10:34:33.997561     1 MetaClient.cpp:137] Waiting for the metad to be ready!
`

When I run the same query (from `get_flat_rel_map`) in the console, it executes successfully without any errors
https://github.com/jerryjliu/llama_index/blob/39ff38293b5d4d1fc33d8fbadacf9bb57861ccbe/llama_index/graph_stores/nebulagraph.py#L410-L435

Let me know what you think.

**Comment by wey-gu** [comment]
I think it's not related to the client anymore.

What does the `SHOW HOSTS` say?

**Comment by salahaz** [comment]
@wey-gu The storage hosts are connected and online 

![storage-hosts](https://github.com/jerryjliu/llama_index/assets/41476094/410593bb-f0f6-4bac-8799-11db9d5da924)

Same for meta, and graph hosts:

![graph-hosts](https://github.com/jerryjliu/llama_index/assets/41476094/961df020-73b4-4710-8b5f-f6d745624a46)

![meta-hosts](https://github.com/jerryjliu/llama_index/assets/41476094/e48acafd-419a-4f9a-b143-9c72801576e9)

**Comment by salahaz** [comment]
If you're using llama-index with nebula-graph database that runs with docker-compose, the RAG system must be on the same network as nebula-graph for it to run without RPC timeout error.

**Comment by wey-gu** [comment]
As we talked in NebulaGraph community, this is still unexpected to me as graphd was by default exposed it's endpoint outside of the docker net, and it's all it's needed for graphd clients(for meta/storages clients, that's not the case while here we only need graphd clients).

But docker compose is not recommended for production, for test we could do so with the mitigation.

Also, interestingly , I cannot reproduce this due to I am running my NebulaGraph cluster with docker and connecting to it from another host all the time 😅
