### ISSUE TITLE
During the create and refine process, intermediate responses are not saved

### ISSUE THREAD

**Issue by Martok88** [jerryjliu/llama_index#740]
Hi @jerryjliu. We talked on Discord about this and I figured I'd open an issue in order to track it and possibly recruit help, since I don't think I'm quite familiar enough with your code to tackle it myself yet.

Using ChatGPT to query a document index, I find that I sometimes get a response such as "Return the original answer. The new context is not relevant to the question ..." It would be helpful to store the responses that are being generated during the create and refine process, in case they are more useful than the final response.

As a workaround, I'm using a custom StringIO logger to grab the debug output, and then filtering each line looking for "Initial response" and "Refined response." In order to make this work, I modified "indices/response/builder.py" to remove newlines which are sometimes being added in front of or within the responses.

https://github.com/jerryjliu/llama_index/compare/main...Martok88:gpt_index:main#diff-8583bac0dcc8a7df7316fa7cc4b57e087845f8ccc9d02f5272ebf2d07d345b24

```
# Additional imports needed
import logging
from io import StringIO

# Configure custom string IO logger
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
log_capture_string = StringIO()
log_handler = logging.StreamHandler(log_capture_string)
log_handler.setLevel(logging.DEBUG)
logger.addHandler(log_handler)

# Suppress debug messages from imported modules (Optional, makes console output more readable)
gpt_index_logger = logging.getLogger("gpt_index")
gpt_index_logger.setLevel(logging.INFO)
openai_logger = logging.getLogger("openai")
openai_logger.setLevel(logging.INFO)
urllib3_logger = logging.getLogger("urllib3")
urllib3_logger.setLevel(logging.INFO)

# ... Query as usual, then ...
# Loop over debug messages to get initial and refined responses
responselist = []
log_contents = log_capture_string.getvalue()
log_capture_string.truncate(0)
for line in log_contents.splitlines():
    if line[0:20] == "> Refined response: " or line[0:20] == "> Initial response: ":
        responselist.append(line[2:])
response.response = "\n\n".join(responselist)
```

**Comment by jerryjliu** [comment]
Should be solved in #745 !
