### ISSUE TITLE
[Question]: responsing very slow

### ISSUE THREAD

**Issue by axz91** [jerryjliu/llama_index#7410]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

https://huggingface.co/spaces/AXZ91/p53
Now it takes more than 10 s to return the response, i use the SupabaseVectorStore, any issues there? thanks!

**Comment by axz91** [comment]
the size is very small but still takes long time to have reponse

**Comment by logan-markewich** [comment]
It looks fine to me. My best guess is either openai is having issues, or they are throttling responses from huggingface spaces 🤷🏻‍♂️ Not much to do about it tbh. Locally with similar code I get 2-3s responeses

**Comment by axz91** [comment]
> It looks fine to me. My best guess is either openai is having issues, or they are throttling responses from huggingface spaces 🤷🏻‍♂️ Not much to do about it tbh. Locally with similar code I get 2-3s responeses

I used pinecone/qdrant and there is no issue, only slow with supbase

**Comment by logan-markewich** [comment]
Maybe a supabase issue then? Tbh I haven't used it.
