### ISSUE TITLE
Editing Document content

### ISSUE THREAD

**Issue by erlebach** [jerryjliu/llama_index#7414]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I generated a `Document` , stored in a variable `doc`. Its text content is `doc.get_content()`. I wish to run `unidecode` to handle unicode issues. How can I update the textual component of `Document` without affecting metadata and other information?

**Comment by logan-markewich** [comment]
The bots response is almost correct. But it also assumes that you want to update a document in an index.

In any case, you can modify the text directly using the `document.text` attribute

```
document.text = "new text"
```
