### ISSUE TITLE
[Feature Request]: Enable to use Metadata extractors for manually created nodes

### ISSUE THREAD

**Issue by c64er4ever** [jerryjliu/llama_index#7422]
### Feature Description

Hi,
Currently, If I understand correctly, Metadata extractors can only be used via Node Parsers when splitting a document to nodes.
However, sometimes it is not required to use Text Splitters and Node Parsers as the logical splitting to nodes is already known and available. In this case, it seems that it is not possible to use extractors such as SummaryExtractor, QuestionsAnsweredExtractor or KeywordsExtractor, which could be a very nice and useful feature. Will it be possible to use these extractors directly on a TextNode, for example, or using some kind of Node Utils class? 
Thanks!
Guy

### Reason

Today, Metadata extractors can only be used via Node Parsers when splitting a document to nodes.

### Value of Feature

Existing cool functionality can be used also for manually created nodes.

**Comment by logan-markewich** [comment]
You can use them today!

You can build the `MetadataExtractor` class with the extractors you want to use and call it directly.

```
metadata_extractor = MetadataExtractor(extractors=[SummaryExtractor(llm=llm])
new_nodes = metadata_extractor.process_nodes(nodes)
```

Or you could call the extractor directly `extractor.extract(nodes)`, but it returns a list of metadata that you have to handle manually
