### ISSUE TITLE
[Question]: Is there a way that we can use AutoMergingRetriever without a docstore?

### ISSUE THREAD

**Issue by hwuiwon** [jerryjliu/llama_index#7435]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was reading through the new AutoMergingRetriever and its implementation, and it looks like it requires a docstore to work properly. Will future support make it work with only a vector store?

**Comment by logan-markewich** [comment]
If you have an idea for how to make it work though, would love to see a PR :)
