### ISSUE TITLE
[Question]: any wrong of my code?

### ISSUE THREAD

**Issue by axz91** [jerryjliu/llama_index#7451]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

#Assuming index is defined somewhere, for example:                                                            
storage_context = storage_context.from_defaults(vector_store=vector_store,persist_dir="./stor")
index = load_indices_from_storage(storage_context)

batch_size = 5

# Get the list of files from the directory
files = os.listdir(dir_path)

# Calculate the number of batches
num_batches = len(files) // batch_size + (len(files) % batch_size > 0)

for i in range(num_batches):
    # Select files for the current batch
    batch_files = files[i*batch_size : (i+1)*batch_size]
    
    for f in batch_files:
        file_path = os.path.join(dir_path, f)
        print(f"Processing {f}")

        # Move the file to the new directory
        new_path_for_index = os.path.join(path_for_index, f)
        shutil.move(file_path, new_path_for_index)

        # Read the file
        docs = SimpleDirectoryReader(input_files= [f'{new_path_for_index}']).load_data()
        for doc in docs:
            new_index.insert(doc)
            ## save index
            # Move the file to the final directory
            print(f"Moving to already indexed folder {doc}")
            new_path = os.path.join(indexed_dir_path, f)
            shutil.move(new_path_for_index, new_path)
        # Persist the index after inserting the new document
    new_index.set_index_id("vector_index")
    new_index.storage_context.persist("./stor")

will the last one     new_index.set_index_id("vector_index"), overight my previous data stored in under this index name, thanks

**Comment by axz91** [comment]
> 

I have index.insert

        docs = SimpleDirectoryReader(input_files= [f'{new_path_for_index}']).load_data()
        for doc in docs:
            new_index.insert(doc)
            ## save index
            # Move the file to the final directory
            print(f"Moving to already indexed folder {doc}")
            new_path = os.path.join(indexed_dir_path, f)
            shutil.move(new_path_for_index, new_path)
        # Persist the index after inserting the new document
    new_index.set_index_id("vector_index")
    new_index.storage_context.persist("./stor")



can i just remove     new_index.set_index_id("vector_index")

**Comment by logan-markewich** [comment]
What's the issue you are facing? I don't think you ever mentioned it 😅

**Comment by axz91** [comment]
> What's the issue you are facing? I don't think you ever mentioned it 😅

I am concerned if new_index.set_index_id("vector_index")  will override my previous data under the same index name

**Comment by logan-markewich** [comment]
@axz91 so if you save to the same directory, it will overwrite the previous index, regardless of index id

The only way to share a folder with multiple indexes is if all indexes share the same storage context with different index IDs 🤔

**Comment by axz91** [comment]
> @axz91 so if you save to the same directory, it will overwrite the previous index, regardless of index id
> 
> The only way to share a folder with multiple indexes is if all indexes share the same storage context with different index IDs 🤔

Oh,, thanks, I only one all document being store in one index under one folder, but not sure if code is right.

**Comment by logan-markewich** [comment]
The code looks right to me!
