### ISSUE TITLE
[Question]: Is it possible to mix index data from both files and URLs?

### ISSUE THREAD

**Issue by Ma-Fukudama** [jerryjliu/llama_index#7455]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I insert and run an index created from a file into an index created from a URL using 'llamaindex'?

`import os, sys, json,logging
from dotenv import load_dotenv
from llama_index import SimpleDirectoryReader, StorageContext, ListIndex, LLMPredictor, Document, load_index_from_storage
from langchain.chat_models import ChatOpenAI
from llama_index.langchain_helpers.agents import create_llama_chat_agent, IndexToolConfig

load_dotenv()

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, force=True)

text_list = ['A.txt','B.txt']
index = ListIndex([])
doc_chunks = []
for i, text in enumerate(text_list):
    doc = Document(text=text, id_=f"doc_id_{i}")
    doc_chunks.append(doc)

for doc_chunk in doc_chunks:
    index.insert(doc_chunk)

llm = OpenAI(model="gpt-4", temperature=0, max_tokens=2048)
service_context = ServiceContext.from_defaults(llm=llm)

documents = SimpleWebPageReader(html_to_text=True).load_data(
    [
        "http://paulgraham.com/worked.html",
    ]
)
index = ListIndex.from_documents(documents, service_context=service_context)

index.storage_context.persist(persist_dir="index")`

**Comment by Ma-Fukudama** [comment]
Thank you for your response. Should I implement the BaseIndex as shown in the following source code in the sample code?
'from llama_index import BaseIndex'

**Comment by logan-markewich** [comment]
@Ma-Fukudama I think what the bot meant is that you can do that with a ListIndex, not with `BaseIndex` (that's just the base class)

Tbh its a little hacky, I'm not sure if it will work. My best suggestion is just to re-create the index using all the documents you need. You are already using insert, so you could also insert the second batch of documents.

**Comment by Ma-Fukudama** [comment]
@logan-markewich 
I was able to create an index using the information you provided.
However, if you ask a question based on the content written in the index created from the URL, you will be told that it is not specified.
If you ask about the contents of the index created from the file, you will receive an answer.

Is it possible to create an index that reflects the contents of both?
