### ISSUE TITLE
[Feature Request]: could Lama_index integrate LiteLLM ?

### ISSUE THREAD

**Issue by solyarisoftware** [jerryjliu/llama_index#7458]
### Feature Description

just a curiosity/proposal: 

Did you thought about decoupling the LLM integration, maybe using LiteLLM 
https://github.com/BerriAI/litellm/ ?

### Reason

I read you already support relevant LLMs as described here:
https://gpt-index.readthedocs.io/en/stable/core_modules/model_modules/llms/modules.html

nevertheless decoupling LLMs integrations could save time to focus on the "core business" of llama_index (RAG / private data management).

**Comment by krrishdholakia** [comment]
We've had another user ask for this (cc: @yisding) - let's definitely make an integration.

**Comment by solyarisoftware** [comment]
great!
