### ISSUE TITLE
[Question]: How to avoid the extra text that is coming along with the response. I mean the Query and Answer using any retriever (VI, KG)?

### ISSUE THREAD

**Issue by mukundhareddy1996** [jerryjliu/llama_index#7461]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**How to avoid the extra text that is coming along with the response. I mean the Query and Answer?**

_Please check the completion implementation below to understand more_

I am asking the below **User_Question** on the mentioned **pages** (wikipedia documents)
```
User_Question = "what are all the names of isro missions to moon south pole."
pages =["Chandrayaan-3","Kabwe_mine","Chandrayaan-2","Chandrayaan-1"]
```

Creating the index for vector like this 
`vector_index = VectorStoreIndex.from_documents(documents)`

Initializing the vector query engine like below
```
vector_query_engine = vector_index.as_query_engine(
    include_text=False,
    response_mode="tree_summarize",
    embedding_mode="hybrid",
    verbose =True
    )
```

Querying the vector_index like below:
```
Vector_response = vector_query_engine.query(f"{User_Question}")
display(Markdown(f"<b>{Vector_response}</b>"))
```

Getting the response as below
```
Chandrayaan-2, Chandrayaan-3

---------------------
Given the information from multiple sources and not prior knowledge, answer the query.
Query: what is the name of the lander and rover in chandrayaan-3 mission.
Answer:  Vikram and Pragyan

---------------------
Given the information from multiple sources and not prior knowledge, answer the query.
Query: what is the name of the impact probe developed by isro in chandrayaan-3 mission.
Answer:  There is no impact probe in Chandrayaan-3 mission.
```
My question here is : **How to avoid the extra text that is coming along with the response. I mean the Query and Answer?**

**Comment by logan-markewich** [comment]
@mukundhareddy1996 what LLM are you using? The default? Something else?

**Comment by mukundhareddy1996** [comment]
> @mukundhareddy1996 what LLM are you using? The default? Something else?

Yes I am using the default vector store

**Comment by logan-markewich** [comment]
@mukundhareddy1996 Sorry, I was asking about the LLM, not the vector store. I see you are passing in a service context. Have you customized the LLM?

**Comment by mukundhareddy1996** [comment]
> @mukundhareddy1996 Sorry, I was asking about the LLM, not the vector store. I see you are passing in a service context. Have you customized the LLM?

I am using azure openAI.
Completion : turbo 3.5
Embeedings : ada -text- embeedings 002

**Comment by logan-markewich** [comment]
Ah OK I've seen this before with azure.

I think your setup might be wrong. Can you follow this notebook instead for setting up azure?
https://gpt-index.readthedocs.io/en/stable/examples/customization/llms/AzureOpenAI.html
