### ISSUE TITLE
[Bug]: uvloop error - Running guidance with FastAPI

### ISSUE THREAD

**Issue by vinodvarma24** [jerryjliu/llama_index#7466]
### Bug Description

When we try to use GuidancePydanticProgram() with FastAPI, we are running into this error:

`Error while running the program: Can't patch loop of type <class 'uvloop.Loop'>`

Currently, it's getting solved with the solution provided below. But a more permanent solution is required for FastAPI.
https://github.com/guidance-ai/guidance/issues/184

### Version

llama-index==0.8.10

### Steps to Reproduce

just run the program = GuidancePydanticProgram(
                    output_cls=Columns,
                    prompt_template_str="xxxxxxxxxxxxxxxxx",
                    guidance_llm=OpenAI("text-davinci-003"),
                    verbose=True
                )
        sql_query = response.sources[0].raw_output.metadata['sql_query']
        columns = program(sql_query=sql_query)

### Relevant Logs/Tracbacks

```shell
`Error while running the program: Can't patch loop of type <class 'uvloop.Loop'>`
```

**Comment by logan-markewich** [comment]
Going to close this for now, but if you have an idea for how to solve this compatibility issue, please do raise a PR
