### ISSUE TITLE
[Bug]: ServiceContext Not Accepting Fine Tune Model

### ISSUE THREAD

**Issue by EyeOfHorus396** [jerryjliu/llama_index#7467]
### Bug Description

Trying to pass the fine tune 3.5 turbo model into ServiceContext and it throws an error:

ValueError: Unknown model: ft. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-32k, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo
`
ft_context = ServiceContext.from_defaults(
    llm=OpenAI(model=ft_model_names, temperature=0.3),
    context_window=2048, 
)
`

### Version

0.8.12

### Steps to Reproduce

Following the steps from this cookbook: https://colab.research.google.com/drive/1NgyCJVyrC2xcZ5lxt2frTU862v6eJHlc?usp=sharing

### Relevant Logs/Tracbacks

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-59-f4d3f6b9ee98> in <cell line: 15>()
     13 # Option 2: you can also specify the model name manually
     14 ft_model_names = "ft:gpt-3.5-turbo-0613:model-name::9svdEgjk"
---> 15 ft_context = ServiceContext.from_defaults(
     16     llm=OpenAI(model=ft_model_names, temperature=0.3),
     17     context_window=2048,  # limit the context window artifically to test refine process

3 frames
/usr/local/lib/python3.10/dist-packages/llama_index/llms/openai_utils.py in openai_modelname_to_contextsize(modelname)
    191 
    192     if context_size is None:
--> 193         raise ValueError(
    194             f"Unknown model: {modelname}. Please provide a valid OpenAI model name."
    195             "Known models are: " + ", ".join(ALL_AVAILABLE_MODELS.keys())
```

**Comment by EyeOfHorus396** [comment]
@dosu-bot, that is invalid. @jerryjliu ran the same logic with a fine tuned model in the cookbook that I provided without any issues. Langchain already supports fine tuned model names from openai.

**Comment by logan-markewich** [comment]
@EyeOfHorus396 I'm unable to reproduce this. 

This works for me

```
>>> from llama_index import ServiceContext
>>> from llama_index.llms import OpenAI
>>> ctx = ServiceContext.from_defaults(llm=OpenAI(model="ft:gpt-3.5-turbo-0613:model-name::9svdEgjk"))
>>>
```

And if I do it with a clearly incorrect name
```
>>> ctx = ServiceContext.from_defaults(llm=OpenAI(model="clearly fake model name"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/loganm/llama_index_proper/llama_index/llama_index/indices/service_context.py", line 170, in from_defaults
    llm_metadata=llm_predictor.metadata,
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganm/llama_index_proper/llama_index/llama_index/llm_predictor/base.py", line 125, in metadata
    return self._llm.metadata
           ^^^^^^^^^^^^^^^^^^
  File "/home/loganm/llama_index_proper/llama_index/llama_index/llms/openai.py", line 104, in metadata
    context_window=openai_modelname_to_contextsize(self._get_model_name()),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganm/llama_index_proper/llama_index/llama_index/llms/openai_utils.py", line 193, in openai_modelname_to_contextsize
    raise ValueError(
ValueError: Unknown model: clearly fake model name. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-32k, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo
>>> 
```

The code under the hood is here, are you sure you passed in the model name correctly?
https://github.com/jerryjliu/llama_index/blob/ecc5a0520cf6c2cb5d872b1fefbe249163ba5717/llama_index/llms/openai_utils.py#L179

**Comment by logan-markewich** [comment]
According to the error, the code parsed the model name as `ft`, which doesn't seem possible 🤔

**Comment by EyeOfHorus396** [comment]
@logan-markewich please give this a try and let me know what it returns for you:
`
from llama_index import ServiceContext
from llama_index.llms import OpenAI
ctx = ServiceContext.from_defaults(llm=OpenAI(model="ft:gpt-3.5-turbo-0613:swift-loan::7svdNdjk"))
`

**Comment by logan-markewich** [comment]
ah, I see the issue, one sec

**Comment by logan-markewich** [comment]
Lucky you, you have the one model name that breaks the string parsing 😆 

Will merge the fix in a sec, you can install from source when it merges:
`pip install git+https://github.com/jerryjliu/llama_index`

or wait for the next pypi release

**Comment by EyeOfHorus396** [comment]
@logan-markewich scratch that, it still throws the error, even after commenting out DISCONTINUED_MODELS but I know now that the letter "T" in the word "swift" throws the error. It works fine if I remove the letter 't' or replace it with any other letter. ctx = ServiceContext.from_defaults(llm=OpenAI(model="ft:gpt-3.5-turbo-0613:swift-loan::9svdEgjk")).
