### ISSUE TITLE
[Bug]: OS freezes when using the default index 

### ISSUE THREAD

**Issue by YasmineMh** [jerryjliu/llama_index#7475]
### Bug Description

I tested the code provided below, and it consistently keeps running without encountering a condition to exit (until my OS froze).
```

from llama_index import SimpleDirectoryReader
from llama_index.node_parser import SimpleNodeParser
from llama_index import VectorStoreIndex

documents = SimpleDirectoryReader('./data').load_data()
parser = SimpleNodeParser.from_defaults()
nodes = parser.get_nodes_from_documents(documents)
index = VectorStoreIndex(nodes)
query_engine = index.as_query_engine()
response = query_engine.query("a question")
print(response)

```
I'm utilizing the default embedding and QA models (model_name=BAAI/bge-small-en and llama2). The code appears to become stuck on the line `response = query_engine.query("a question")`
I've conducted tests both locally and on Colab, and the same issue persists in both environments.

Thank you!

### Version

0.8.13

### Steps to Reproduce

Install the requirements below:

```
llama-index==0.8.13
llama-cpp-python==0.1.78
nltk==3.8.1
sentence-transformers==2.2.2
```

Then run the code.

### Relevant Logs/Tracbacks

```shell
No output; it consumes my RAM until the computer crashes.
```

**Comment by logan-markewich** [comment]
@YasmineMh 

Are you intending on using OpenAI as the LLM? Or are you letting it default to LlamaCPP?

**Comment by logan-markewich** [comment]
You need at least 12GB of ram to run the default LlamaCPP model 🤔

**Comment by YasmineMh** [comment]
Letting it default to LlamaCPP

**Comment by YasmineMh** [comment]
I'm using 16GB of Ram already. 
A question, To index the data we use BAAI/bge-small-en and for the QA we use llama2

**Comment by YasmineMh** [comment]
Actually, yeah, I think it's a RAM problem.
(I'll try on a more powerful machine later. and if I encounter the same problem, I will reopen this issue)
Thanks @logan-markewich !

**Comment by logan-markewich** [comment]
@YasmineMh Sounds good!

Yea, indexing will use bge-small, and QA uses llama2 👍🏻
