### ISSUE TITLE
[Question]: KnowledgeGraphRAGRetriever sub-graph extraction filter by property instead of ids

### ISSUE THREAD

**Issue by salahaz** [jerryjliu/llama_index#7481]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello going through the subgraph extraction query, I have found that it is being accomplished by filtering using `id(s)`

https://github.com/jerryjliu/llama_index/blob/39ff38293b5d4d1fc33d8fbadacf9bb57861ccbe/llama_index/graph_stores/nebulagraph.py#L414

However, in many real-life use cases, the IDs don't have any semantic meaning; they can be only database identifiers. That is why it would be better if the sub-graph extraction query supports filtering by properties as well using something like this for example `properties(s).name`?

Any ideas @wey-gu @logan-markewich

**Comment by wey-gu** [comment]
This is exactly something I am planning to do in next step, the latest pr is for representation of meaningless ids.

And also I'll add relationship-wise starting node fetching options, too.

And finally, will add embedding based search.

**Comment by logan-markewich** [comment]
Sounds good to me!
