### ISSUE TITLE
[Bug]:The parameter storage_context of KnowledgeGraphRAGRetriever does not support neo4j

### ISSUE THREAD

**Issue by houjibofa2050** [jerryjliu/llama_index#7483]
### Bug Description

code as follows
`import logging
import sys

logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output

from llama_index import (
    KnowledgeGraphIndex,
    LLMPredictor,
    ServiceContext,
    SimpleDirectoryReader,
)
from llama_index.storage.storage_context import StorageContext
from llama_index.graph_stores import NebulaGraphStore
from llama_index.llms import OpenAI

from IPython.display import Markdown, display

# define LLM
# NOTE: at the time of demo, text-davinci-002 did not have rate-limit errors
llm = OpenAI(temperature=0, model="text-davinci-002")
service_context = ServiceContext.from_defaults(llm=llm, chunk_size_limit=512)

from llama_index.query_engine import RetrieverQueryEngine
from llama_index.retrievers import KnowledgeGraphRAGRetriever
from llama_index.graph_stores import Neo4jGraphStore

username = "neo4j"
password = "12345678"
url = "bolt://localhost:7687"
database = "xxxx"

graph_store = Neo4jGraphStore(
    username=username,
    password=password,
    url=url,
    database=database,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

graph_rag_retriever = KnowledgeGraphRAGRetriever(
    storage_context=storage_context,
    service_context=service_context,
    llm=llm,
    verbose=True,
)

query_engine = RetrieverQueryEngine.from_args(
    graph_rag_retriever, service_context=service_context
)
response = query_engine.query("中国有多少民族")
print("response:", response)`

response = query_engine.query("中国有多少民族") 报错
![llama_index报错](https://github.com/jerryjliu/llama_index/assets/19608744/e3ec718c-7ee8-4a5e-bc5c-a86fa709743d)

### Version

llama-index           0.8.11.post3

### Steps to Reproduce

response = query_engine.query("中国有多少民族")

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\cm\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\callbacks\base.py", line 155, in as_trace
    yield
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 165, in _query
    nodes = self.retrieve(query_bundle)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 113, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\base_retriever.py", line 22, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 746, in _retrieve
    nodes.extend(self._retrieve_keyword(query_bundle))
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 697, in _retrieve_keyword
    return self._build_nodes(knowledge_sequence, rel_map)
  File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 663, in _build_nodes
    f"{_new_line_char.join(knowledge_sequence)}"
TypeError: sequence item 0: expected str instance, list found
```

**Comment by wey-gu** [comment]
> ### Bug Description
> 
> code as follows
> 
> `import logging
> 
> import sys
> 
> 
> 
> logging.basicConfig(
> 
>     stream=sys.stdout, level=logging.INFO
> 
> )  # logging.DEBUG for more verbose output
> 
> 
> 
> from llama_index import (
> 
>     KnowledgeGraphIndex,
> 
>     LLMPredictor,
> 
>     ServiceContext,
> 
>     SimpleDirectoryReader,
> 
> )
> 
> from llama_index.storage.storage_context import StorageContext
> 
> from llama_index.graph_stores import NebulaGraphStore
> 
> from llama_index.llms import OpenAI
> 
> 
> 
> from IPython.display import Markdown, display
> 
> 
> 
> 
> 
> # define LLM
> 
> # NOTE: at the time of demo, text-davinci-002 did not have rate-limit errors
> 
> llm = OpenAI(temperature=0, model="text-davinci-002")
> 
> service_context = ServiceContext.from_defaults(llm=llm, chunk_size_limit=512)
> 
> 
> 
> 
> 
> from llama_index.query_engine import RetrieverQueryEngine
> 
> from llama_index.retrievers import KnowledgeGraphRAGRetriever
> 
> from llama_index.graph_stores import Neo4jGraphStore
> 
> 
> 
> 
> 
> username = "neo4j"
> 
> password = "12345678"
> 
> url = "bolt://localhost:7687"
> 
> database = "xxxx"
> 
> 
> 
> graph_store = Neo4jGraphStore(
> 
>     username=username,
> 
>     password=password,
> 
>     url=url,
> 
>     database=database,
> 
> )
> 
> storage_context = StorageContext.from_defaults(graph_store=graph_store)
> 
> 
> 
> 
> 
> graph_rag_retriever = KnowledgeGraphRAGRetriever(
> 
>     storage_context=storage_context,
> 
>     service_context=service_context,
> 
>     llm=llm,
> 
>     verbose=True,
> 
> )
> 
> 
> 
> query_engine = RetrieverQueryEngine.from_args(
> 
>     graph_rag_retriever, service_context=service_context
> 
> )
> 
> response = query_engine.query("中国有多少民族")
> 
> print("response:", response)`
> 
> 
> 
> 
> 
> response = query_engine.query("中国有多少民族") 报错
> 
> ![llama_index报错](https://github.com/jerryjliu/llama_index/assets/19608744/e3ec718c-7ee8-4a5e-bc5c-a86fa709743d)
> 
> 
> 
> ### Version
> 
> llama-index           0.8.11.post3
> 
> ### Steps to Reproduce
> 
> response = query_engine.query("中国有多少民族")
> 
> ### Relevant Logs/Tracbacks
> 
> ```shell
> Traceback (most recent call last):
> 
>   File "C:\Users\cm\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
> 
>     self.gen.throw(typ, value, traceback)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\callbacks\base.py", line 155, in as_trace
> 
>     yield
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\query\base.py", line 23, in query
> 
>     response = self._query(str_or_query_bundle)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 165, in _query
> 
>     nodes = self.retrieve(query_bundle)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 113, in retrieve
> 
>     nodes = self._retriever.retrieve(query_bundle)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\base_retriever.py", line 22, in retrieve
> 
>     return self._retrieve(str_or_query_bundle)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 746, in _retrieve
> 
>     nodes.extend(self._retrieve_keyword(query_bundle))
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 697, in _retrieve_keyword
> 
>     return self._build_nodes(knowledge_sequence, rel_map)
> 
>   File "D:\software\langchain16\langchain16\venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 663, in _build_nodes
> 
>     f"{_new_line_char.join(knowledge_sequence)}"
> 
> TypeError: sequence item 0: expected str instance, list found
> ```
> 

will take a look at this later.

**Comment by wey-gu** [comment]
This should fix it: https://github.com/jerryjliu/llama_index/pull/7488

**Comment by houjibofa2050** [comment]
neo4j data as follow
(:Entity {id: "中国"})  │[:首都] │(:Entity {id: "北京"})  
(中国)->(首都)->(北京)
