### ISSUE TITLE
[Feature Request]: Ollama support

### ISSUE THREAD

**Issue by mchiang0610** [jerryjliu/llama_index#7487]
### Feature Description

Adding Ollama support: 

https://github.com/jmorganca/ollama/issues/278

**Comment by hammer** [comment]
Ollama is the easiest way to get a local LLM working on macOS that I've found, it would be great if their interface was supported by LlamaIndex!

**Comment by shauryr** [comment]
new litellm support PR https://github.com/jerryjliu/llama_index/pull/7600 
If we have litellm; we can also get ollama working through it - https://github.com/BerriAI/litellm/blob/main/cookbook/liteLLM_Ollama.ipynb

**Comment by krrishdholakia** [comment]
@logan-markewich has given me some feedback on the PR - i'll work on it and make the integration hopefully by EOD
