### ISSUE TITLE
SQLDatabase not using MSSQL in syntax

### ISSUE THREAD

**Issue by keithschm** [jerryjliu/llama_index#749]
Having strange behavior with SQLDatabase. See code below. I am clearly connected to a mssql database, yet the query returned is not MSSQL. Is this a bug or am I missing something?  

```
from llama_index import GPTSimpleVectorIndex, Document, SimpleDirectoryReader,GPTSQLStructStoreIndex,SQLDatabase
from llama_index.indices.struct_store import SQLContextContainerBuilder
import os
from sqlalchemy import create_engine, MetaData, Table, Column, String, Integer, select, column
con = create_engine('mssql+pyodbc://:@my_server/my_db?driver=SQL+Server+Native+Client+11.0')
metadata_obj = MetaData(bind=con)

sql_database = SQLDatabase(con, include_tables=["my_table"])

index = GPTSQLStructStoreIndex(
    [],
    sql_database=sql_database, 
    table_name="mytable",
)

response = index.query("which PM had the most responses?")
print(response)
```

The Response is not MSSQL as there is no Limit!

sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near 'LIMIT'. (102) (SQLExecDirectW)")
[SQL: SELECT PM, COUNT(*) AS NumResponses
FROM my_table
GROUP BY PM
ORDER BY NumResponses DESC
LIMIT 1;]

**Comment by keithschm** [comment]
Thank you @jerryjliu , it Is Microsoft SQL, I do not see in any of the  docs how to set DB type within the input Prom. Can you point me in the right direction?

**Comment by jerryjliu** [comment]
@keithschm could you actually try again? #783 might have solved your issue

**Comment by logan-markewich** [comment]
This should be fixed. Please reopen the issue if it comes up again!
