### ISSUE TITLE
[Bug]: Not able to load langchain text splitters in SimpleNodeParser

### ISSUE THREAD

**Issue by dhruv2512** [jerryjliu/llama_index#7506]
### Bug Description

When I try to use Langchain's RecursiveCharacterTextSplitter in SimpleNodeParser, it gives me the below error:

ValidationError: 1 validation error for SimpleNodeParser
text_splitter
  value is not a valid dict (type=type_error.dict)

### Version

0.7.13

### Steps to Reproduce

Load RecursiveCharacterTextSplitter into SimpleNodeParser

**Comment by dhruv2512** [comment]
> _🤖_
> 
> Hi there,
> 
> The error you're encountering is likely due to the fact that the `load_text_splitter` function in the `SimpleNodeParser` class is expecting a dictionary as input. This dictionary should contain a key "class_name" which corresponds to the name of a recognized text splitter.
> 
> In your case, you're trying to load Langchain's `RecursiveCharacterTextSplitter` into `SimpleNodeParser`. However, based on the provided context, `RecursiveCharacterTextSplitter` is not included in the `RECOGNIZED_TEXT_SPLITTERS` dictionary. This means that when you try to load it, the function cannot find it in the dictionary and raises a ValueError.
> 
> To resolve this issue, you would need to add `RecursiveCharacterTextSplitter` to the `RECOGNIZED_TEXT_SPLITTERS` dictionary, assuming that `RecursiveCharacterTextSplitter` is a valid TextSplitter. Here's how you might do that:
> 
> ```python
> from llama_index.text_splitter.recursive_character_text_splitter import RecursiveCharacterTextSplitter
> 
> RECOGNIZED_TEXT_SPLITTERS: Dict[str, Type[TextSplitter]] = {
>     SentenceSplitter.class_name(): SentenceSplitter,
>     TokenTextSplitter.class_name(): TokenTextSplitter,
>     CodeSplitter.class_name(): CodeSplitter,
>     RecursiveCharacterTextSplitter.class_name(): RecursiveCharacterTextSplitter,
> }
> ```
> 
> Please note that you'll need to import the `RecursiveCharacterTextSplitter` class at the top of your file. The exact import statement might vary depending on the actual location of the `RecursiveCharacterTextSplitter` class in your project.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [llama_index/text_splitter/loading.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/text_splitter/loading.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

But we don't have RecursiveCharacterTextSplitter in llama-index

**Comment by logan-markewich** [comment]
Should be included in the next pypi release, or you can install from source!

**Comment by dhruv2512** [comment]
Hi @logan-markewich thanks for the fix. 
But it was working for me earlier. Not sure how it stopped.
When is the next PyPI release?

**Comment by logan-markewich** [comment]
It stopped working because we switched the base class to be pydantic, and forgot to include langchain splitters in the typing logic 

Next release will probably be sometime this weekend. Or you can install from source

**Comment by dhruv2512** [comment]
@logan-markewich I tried installing from the source. Still getting the same issue
