### ISSUE TITLE
[Documentation]: Fix Parsing the response numbering

### ISSUE THREAD

**Issue by connorjoleary** [jerryjliu/llama_index#7512]
### Documentation Issue Description

On the [usage pattern page](https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/usage_pattern.html) in the docs, `Parsing the response` starts with a 5 even though it is the 6th section. Also, it is not listed at the top table of contents.

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/usage_pattern.html

**Comment by logan-markewich** [comment]
Feel free to submit a PR to correct this :)

**Comment by noble-varghese** [comment]
Since no one is assigned this issue, I am taking this up and raising a PR :)
