### ISSUE TITLE
Router Query Engine Streaming

### ISSUE THREAD

**Issue by yuvansharma** [jerryjliu/llama_index#7529]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a way to use streaming with the router query engine? And if not, would it be possible to make a feature request for it?

**Comment by logan-markewich** [comment]
@yuvansharma yea it is possible, you can do something like this:

```
from llama_index.response_synthesizers import TreeSummarize

summarizer = TreeSummarize(service_context=service_context, streaming=True, use_async=False)

query_engine = RouterQueryEngine.from_defaults(...., summarizer=summarizer)
```

**Comment by dhirajsuvarna** [comment]
> @yuvansharma yea it is possible, you can do something like this:
> 
> ```
> from llama_index.response_synthesizers import TreeSummarize
> 
> summarizer = TreeSummarize(service_context=service_context, streaming=True, use_async=False)
> 
> query_engine = RouterQueryEngine.from_defaults(...., summarizer=summarizer)
> ```

@logan-markewich 
This workaround not working in the latest release
