### ISSUE TITLE
[Question]: chat_engine with flask: how to deal with multiple chats at the same time

### ISSUE THREAD

**Issue by Iwannabanana** [jerryjliu/llama_index#7542]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I am a beginner python developer and just got messed up by the question below, any help is appreciated:

`import necessary flask and llama_index modules `
`app = Flask(__name__)`
`service_context = ServiceContext.from_defaults(llm=OpenAI(model='gpt-4'))`
`storage_content = StorageContext.from_defaults(persist_dir="./storage_content")`
`new_index_ = load_index_from_storage(storage_content)`
`chat_engine = new_index.as_chat_engine(similarity_top_k=4,chat_mode='openai',verbose=True)`
`@app.route('/', methods=['GET','POST'])`
`def peixun_2_demo_5_why():`
`    if request.method == 'POST':`
`        question = request.form['question']`
`        response = chat_engine.chat(question)`
`        return render_tempaltes('index.html', ans =response)`

With reference to the code above, if there are multple user interfacing my flask API at the same time, what the code does is simply putting all the chat history together in one giant history log and generate answer from there. If there a method to separate differenct chat **channel** for each user? Many thanks.

**Comment by logan-markewich** [comment]
The bot is pretty close to a correct answer.

Basically, you need some way to manage the chat history per user. You can get the current chat_history of a chat engine using
`chat_engine.chat_history`

You can clear the chat history using `chat_engine.reset()`

You can pass in your own chat history using `chat_engine.chat(user_message, chat_history=chat_history)`

**Comment by Iwannabanana** [comment]
wow, problem beautifully solved.

**Comment by Iwannabanana** [comment]
problem well solved, Many thanks.
