### ISSUE TITLE
[Question]: Retrieving Top-K Unique Documents Instead of Top-K Nodes with VectorIndexRetriever

### ISSUE THREAD

**Issue by kevon217** [jerryjliu/llama_index#7544]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**Description:**
I'm currently using the RetrieverQueryEngine with a VectorIndexRetriever (chromadb) for document retrieval. I have a specific requirement: I want the top_k results to be a list of top_k unique documents, rather than top_k nodes.

**Context**:
Similarity Calculations: I understand that the similarity is calculated at the node level.
Multiple Hits: In my pipeline, multiple hits against the same document shouldn't count towards the top_k retrieved list.
Postprocessing: I could do node postprocessing, but then I'd have to increase my top_k to get a sufficient number of unique documents.

**Questions:**
Is there a built-in parameter to fetch results at the document level that I might be overlooking?
If not, would achieving this require customization at the VectorStore level?
Are there any recommendations for a workaround, perhaps at the post-processing level, that doesn't involve increasing the top_k?

Any insight would be much appreciated!

**Comment by logan-markewich** [comment]
Hmm, as far as I know, none of the major vector stores are offering a feature like this.

My suggestion is something I think you've realized already -- cranking up the top-k, and using a custom node-postprocessor to figure out the top-k at the document-level vs. the node-level

**Comment by kevon217** [comment]
@logan-markewich, yeah i figured. not a big deal, but was wondering if i overlooked something simple. appreciate the quick reply!
