### ISSUE TITLE
[Question]: GGUF model support?

### ISSUE THREAD

**Issue by llermaly** [jerryjliu/llama_index#7547]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The new version of llama.cpp throws an error because now will only support GGUF based models. The workaround is to downgrade llama.cpp-python. 

Will llama_index support GGUF models any time soon? I couldn't find any discussion about this.

https://www.reddit.com/r/LocalLLaMA/comments/15xycn2/llamacpp_gguf_merged/

**Comment by llermaly** [comment]
Thanks @logan-markewich 

So like this example you provided I can pass the GGUF version and will work?

```
from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    model_url="https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/resolve/main/llama-2-13b-chat.ggmlv3.q4_0.bin",
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path=None,
    temperature=0.1,
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 1},
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)

from llama_index import ServiceContext, set_global_service_context

ctx = ServiceContext.from_defaults(llm=llm)
set_global_service_context(ctx)
```

**Comment by logan-markewich** [comment]
@llermaly you got it. You'd just change the model path or model URL to point to the GGUF model to use

Not a bad idea to detect the llama-cpp version

**Comment by rchan26** [comment]
hi, I came across this issue last week actually. I think it would be useful to add a note about the llama-cpp versioning in the documentation. I'm happy to make a contribution for this 😊
