### ISSUE TITLE
[Feature Request]: Please reduce constant rewriting of llama-index

### ISSUE THREAD

**Issue by bespaloff** [jerryjliu/llama_index#7555]
### Feature Description

Dear Jerry, 

First of all let me express my great appreciation to the work done by you and your team.
I find this project as absolutely genius and I think it will face a great future.

The only thing I can wish is that from version to version (including minor!) there would be MUCH less changes of classes and APIs.

### Reason

More and more often we are facing need of full rewrite of the code or even reindex data when we need upgrade version in a month or so. 

### Value of Feature

Well, llama_index should be mature in order to be more widely used in production.

**Comment by logan-markewich** [comment]
Hey @bespaloff thanks for the feedback!

Was there a specific issue you had?

Normally, we try to limit breaking changes (if any) to the middle version (0.7.X -> 0.8.X)

But for the most case, breaking changes are (small?) tweaks on the UX side that we do our best to mitigate

There's definitely a tradeoff between stability and velocity of improvements. I think over time any breaking changes should continue to be smaller 🙏🏻
