### ISSUE TITLE
[Question]: "How to create a document for VectorStoreIndex for comparative use using multiple JSON files containing information about employees over the years?"

### ISSUE THREAD

**Issue by iriye** [jerryjliu/llama_index#7566]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

"How to create a document for VectorStoreIndex for comparative use using multiple JSON files containing information about employees over the years?"
for example files:  2019_employee.json, 2020_employee.json, 2021_employee.json etc.

How to add seperately documents object?

**Comment by logan-markewich** [comment]
I think I answered this here, lets keep discussion to a single github issue 🙏🏻 https://github.com/jerryjliu/llama_index/issues/7581
