### ISSUE TITLE
[Question]: How to split or seperate nodes Doucment data?

### ISSUE THREAD

**Issue by iriye** [jerryjliu/llama_index#7569]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

JSONReader = download_loader("JSONReader")
loader = JSONReader()
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
 when I use this code documents prompt size very big, How to split documents text i or how to seperate nodes?

**Comment by logan-markewich** [comment]
You can also just decrease the chunk size in the service context

```
from llama_index import ServiceContext
service_context = ServiceContext.from_defaults(chunk_size=512, ...)
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
query_engine = index.as_query_engine(similarity_top_k=2)
```
