### ISSUE TITLE
[Question]: How to seperate each line documents object list created JsonReder?

### ISSUE THREAD

**Issue by iriye** [jerryjliu/llama_index#7579]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

"How can I create separate lists for each line in the documents from json file  instead of having the entire JSON content in a single text using a JsonReader?"

 Example json files :json file like this 
        "parameters": [
          {
            "name": "latitude",
            "in": "query",
            "description": "Latitude component of location.",
            "required": true,
            "type": "number",
            "format": "double"
          },
          {
            "name": "longitude",
            "in": "query",
            "description": "Longitude component of location.",
            "required": true,
            "type": "number",
            "format": "double"
          }
        ],

**Comment by ikarakaya89** [comment]
I want to load json file using Llmaindex JsonReader;
JSONReader = download_loader("JSONReader")
loader = JSONReader()

With this module, I want to create the JSON above in the following way.
[Document(id_='2ce42bf7-090b-41d3-b514-6ca4029f2da5', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='ee70384c03fcdcc1ff9e7b7872fcb5799ec98cdb1dba38b2a14b1a2309a49dca', text="['name": "latitude",
"in": "query",
"description": "Latitude component of location.",
"required": true,
"type": "number",
"format": "double" ‘]", start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), Document(id_='86f2bded-8f64-42e4-8fe1-4ec27ed969ad', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='a339925ab38da38d7c7720fe0539bdfd59f784750bb9899947c7edd5abe143ac', text="["name": "longitude",
"in": "query",
"description": "Longitude component of location.",
"required": true,
"type": "number",
"format": "double"]", start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n')]

**Comment by logan-markewich** [comment]
@iriye I think you just need to create your own loader for this :) It's pretty easy though

**Comment by logan-markewich** [comment]
Going to close this in favor of the second issue you opened 👍🏻
