### ISSUE TITLE
[Question]: "How can I create separate lists for each line in the documents from json file instead of having the entire JSON content in a single text using a JsonReader?"

### ISSUE THREAD

**Issue by iriye** [jerryjliu/llama_index#7580]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Example json files :json file like this
"parameters": [
{
"name": "latitude",
"in": "query",
"description": "Latitude component of location.",
"required": true,
"type": "number",
"format": "double"
},
{
"name": "longitude",
"in": "query",
"description": "Longitude component of location.",
"required": true,
"type": "number",
"format": "double"
}
],

I create  Document from this json file using llamaindex JsonReader  like this ;

[Document(id_='2ce42bf7-090b-41d3-b514-6ca4029f2da5', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='ee70384c03fcdcc1ff9e7b7872fcb5799ec98cdb1dba38b2a14b1a2309a49dca', text="['name": "latitude",
"in": "query",
"description": "Latitude component of location.",
"required": true,
"type": "number",
"format": "double" ‘]", start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), Document(id_='86f2bded-8f64-42e4-8fe1-4ec27ed969ad', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, hash='a339925ab38da38d7c7720fe0539bdfd59f784750bb9899947c7edd5abe143ac', text="["name": "longitude",
"in": "query",
"description": "Longitude component of location.",
"required": true,
"type": "number",
"format": "double"]", start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n')]

JsonReader create Document object all squence one text value, I want to each row of json file seperate Document

**Comment by logan-markewich** [comment]
Yea @iriye as the bot is suggesting, it sounds like you just need to write your own data loader :) It's pretty easy though
