### ISSUE TITLE
[Question]: Is it possible to answer the question based on the selected document?

### ISSUE THREAD

**Issue by iriye** [jerryjliu/llama_index#7581]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When create VectorStore using multiple documents that change from year to year keys same all documents but value change each year, for example old in first document 20 second 21, how to answer question based on spesific document?

**Comment by logan-markewich** [comment]
@iriye The key here is to seperate your indexes into years. Then, it's a perfect use case for the sub-question query engine
https://gpt-index.readthedocs.io/en/stable/examples/query_engine/sub_question_query_engine.html

It will take a users query like `How did X change between 2021 and 2020` and break it down into two sub-queries and send them to the appropriate sub-index

Then it will aggregate all responses to answer the original query
