### ISSUE TITLE
[Question]: Getting error while using Elasticsearch Vector Store

### ISSUE THREAD

**Issue by dhruv2512** [jerryjliu/llama_index#7594]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to use a newly supported ES vector store.

But after building the index, I got the below error:

```
    244 logger.debug(
    245     f"Creating index {index_name} with mappings {index_settings['mappings']}"  # noqa: E501
    246 )
--> 247 self.client.indices.create(index=index_name, **index_settings)

File ~/.conda/lib/python3.11/site-packages/elasticsearch/client/utils.py:152, in query_params.<locals>._wrapper.<locals>._wrapped(*args, **kwargs)
    150     if p in kwargs:
    151         params[p] = kwargs.pop(p)
--> 152 return func(*args, params=params, headers=headers, **kwargs)

TypeError: IndicesClient.create() got an unexpected keyword argument 'mappings'
```

ES version: 7.9.1
Python ES client version: 7.9.1

**Comment by logan-markewich** [comment]
@joemcelroy any idea on this one? Elastic search is way out of my knowledge, but since you implemented it hopefully you can help here

**Comment by joemcelroy** [comment]
Hey,

Old version of elasticsearch (7.9). I suggest using the latest version 8.9.

and @logan-markewich feel free to ping me on further elasticsearch issues!

**Comment by dhruv2512** [comment]
Hi @joemcelroy, @logan-markewich I am getting below error while creating an index:
`File [/python3.11/site-packages/elasticsearch/client/utils.py:152], in query_params.<locals>._wrapper.<locals>._wrapped(*args, **kwargs)
    150     if p in kwargs:
    151         params[p] = kwargs.pop(p)
--> 152 return func(*args, params=params, headers=headers, **kwargs)

TypeError: IndicesClient.create() got an unexpected keyword argument 'mappings'`

Can someone please help

**Comment by joemcelroy** [comment]
Did you manage to upgrade your elasticsearch version? What version are you currently running on? Also double check the elasticsearch client version matches the elasticsearch version

**Comment by dhruv2512** [comment]
Yeah, this was coming because the client version wasn't updated. Working fine now.
Thanks @joemcelroy
