### ISSUE TITLE
[Documentation]: 

### ISSUE THREAD

**Issue by moti-malka** [jerryjliu/llama_index#7595]
### Documentation Issue Description

On AzureOpenAI docs there is typo on this line:
llm = AzureOpenAI(engine="<insert deployment name from azure>", **mode="model** name")

need to replace to this (just need to add 'l' to model arguments):
llm = AzureOpenAI(engine="<insert deployment name from azure>", model="model name")

here the link for the docs: https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html

can create new branch and fix that ? 

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html

**Comment by logan-markewich** [comment]
This is fixed 👍
