### ISSUE TITLE
[Question]: How to resolve this error?

### ISSUE THREAD

**Issue by qxpf666** [jerryjliu/llama_index#7609]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Parsing documents into nodes: 100%|████████████████████████████████████████████████████| 11/11 [00:00<00:00, 64.00it/s]
Generating embeddings: 100%|█████████████████████████████████████████████████████████| 181/181 [02:13<00:00,  1.36it/s]
Internal Server Error: /api/chat-with-custommodel/
Traceback (most recent call last):
  File "D:\djangosass\sass_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\djangosass\sass_env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\djangosass\sass_env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\hr_management\views.py", line 82, in post
    response = query_engine.query(input_text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 170, in _query
    nodes = self.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 118, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\indices\base_retriever.py", line 22, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 87, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 164, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\vector_stores\simple.py", line 168, in query
    top_similarities, top_ids = get_top_k_embeddings(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\indices\query\embedding_utils.py", line 30, in get_top_k_embeddings
    similarity = similarity_fn(query_embedding_np, emb)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\djangosass\sass_env\Lib\site-packages\llama_index\embeddings\base.py", line 48, in similarity
    product = np.dot(embedding1, embedding2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (1536,) and (768,) not aligned: 1536 (dim 0) != 768 (dim 0)

**Comment by qxpf666** [comment]
LlamaIndex  0.8.22

**Comment by logan-markewich** [comment]
@qxpf666 what embedding model did you use to create the index?

The embedding model used to create the index has to be the same as the one that is used to query

**Comment by qxpf666** [comment]
> _🤖_
> 
> The error you're encountering is due to a mismatch in the dimensions of the embeddings. The error message `ValueError: shapes (1536,) and (768,) not aligned: 1536 (dim 0) != 768 (dim 0)` indicates that the system is trying to compare or operate on two vectors of different dimensions, one of dimension 1536 and the other of dimension 768.
> 
> This issue has been encountered before in the LlamaIndex repository. Here are some solutions that have been suggested:
> 
> 1. The Llama-Index does not support existing collections created outside of it. You need to modify the Chroma implementation to support existing collections. This can be achieved by creating a method to inform Llama-Index where to find key fields such as text, id, etc. This solution was suggested in a similar context for Pinecone and can be applied here as well. You can refer to this issue for more details: [Embedding dimension 1536 does not match collection dimensionality 768](https://github.com/jerryjliu/llama_index/issues/7110)
> 2. You need to start fresh when switching embedding models so that the vector sizes line up. This was suggested in this issue: [About customized embedding model](https://github.com/jerryjliu/llama_index/issues/1029)
> 3. The error could be due to a conflict between the lengths of the huggingface embeddings and the OpenAI embeddings. You are advised to recreate the index using huggingface. This was suggested in this issue: [ValueError: shapes (768,) and (1536,) not aligned: 768 (dim 0) != 1536 (dim 0)](https://github.com/jerryjliu/llama_index/issues/741)
> 
> The expected dimension of the embeddings in the LlamaIndex framework is determined by the `embed_dim` parameter in the `MockEmbedding` class. This parameter is an integer that specifies the dimension of the embedding vector. You can refer to the `MockEmbedding` class in the [llama_index/token_counter/mock_embed_model.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/token_counter/mock_embed_model.py) file for more details.
> 
> The default embedding dimension used in the LlamaIndex framework is 1536. This is indicated in the constants.py file with the line of code: `DEFAULT_EMBEDDING_DIM = 1536`. You can refer to the [llama_index/constants.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/constants.py) file for more details.
> 
> Please try the suggested solutions and let me know if you need further assistance.
> 
> ## Sources
> * [[Question]: Embedding dimension 1536 does not match collection dimensionality 768](https://github.com/jerryjliu/llama_index/issues/7110)
> * [About customized embedding model](https://github.com/jerryjliu/llama_index/issues/1029)
> * [ValueError: shapes (768,) and (1536,) not aligned: 768 (dim 0) != 1536 (dim 0)](https://github.com/jerryjliu/llama_index/issues/741)
> * [llama_index/token_counter/mock_embed_model.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/token_counter/mock_embed_model.py)
> * [llama_index/constants.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/constants.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I found the reason for the error. I attempted to use two different storage methods, but it worked when I made them consistent. Thank you very much for your patient responses. Thank you.

"
service_context = ServiceContext.from_defaults(
            llm=llm, embed_model=embed_model, chunk_size=1024, chunk_overlap=20)

 storage_context = StorageContext.from_defaults(
             persist_dir="D:/index/index_json")
         index = load_index_from_storage(storage_context)
"
