### ISSUE TITLE
[Question]:  ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"

### ISSUE THREAD

**Issue by axz91** [jerryjliu/llama_index#7619]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

from langchain.text_splitter import CharacterTextSplitter

from langchain.embeddings import HuggingFaceEmbeddings
embed_mode = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2'

node_parser = SimpleNodeParser(
  text_splitter=TokenTextSplitter(chunk_size=100, chunk_overlap=100)
)
prompt_helper = PromptHelper(
  context_window=500,
  num_output=256,
  chunk_overlap_ratio=0.1,
  chunk_size_limit=20
)

service_context = ServiceContext.from_defaults(
  llm=llm,  chunk_size=800,embed_model=embed_mode
)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py:357](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/main.py:357), in pydantic.main.BaseModel.__setattr__()

ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?70d6868f-15af-4032-8692-7072c2ca5557) or open in a [text editor](command:workbench.action.openLargeOutput?70d6868f-15af-4032-8692-7072c2ca5557). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by axz91** [comment]
> _🤖_
> 
> Hello,
> 
> The error you're encountering is likely due to the fact that the "HuggingFaceEmbeddings" object does not have a "callback_manager" field. This field is being set for the "embed_model" object in the "from_defaults" and "from_service_context" methods of the "ServiceContext" class. If your "embed_model" is an instance of "HuggingFaceEmbeddings" and this class does not have a "callback_manager" field, you will encounter a ValueError.
> 
> To resolve this issue, you should ensure that the "HuggingFaceEmbeddings" class (or whatever class is being used for the "embed_model") has a "callback_manager" field. If it doesn't, you may need to add this field to the class definition, or modify the "ServiceContext" class to handle "embed_model" objects that do not have a "callback_manager" field.
> 
> In the context shared, it appears that the "LLM" class, which may be the class you're referring to as "HuggingFaceEmbeddings", does indeed have a "callback_manager" field in its constructor. However, it doesn't seem to be used or stored as an instance variable. If you're trying to access this field after the object has been constructed, you may encounter a ValueError. You may need to modify the "LLM" class to store the "callback_manager" as an instance variable if you need to access it later.
> 
> Here are the relevant sources for your reference:
> 
> * [llama_index/indices/service_context.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/indices/service_context.py)
> * [llama_index/llms/huggingface.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/huggingface.py)
> * [llama_index/llms/base.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/base.py)
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [[Bug]: ValueError: "GPT4AllEmbeddings" object has no field "callback_manager"](https://github.com/jerryjliu/llama_index/issues/7176)
> * [[Bug]: ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"](https://github.com/jerryjliu/llama_index/issues/6750)
> * [llama_index/indices/service_context.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/indices/service_context.py)
> * [llama_index/llms/huggingface.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/huggingface.py)
> * [llama_index/llms/base.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/llms/base.py)
> * [llama_index/callbacks/base.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/callbacks/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

But i see:


We also support any embeddings offered by Langchain [here](https://python.langchain.com/docs/modules/data_connection/text_embedding/).

The example below loads a model from Hugging Face, using Langchain’s embedding class.

from langchain.embeddings.huggingface import HuggingFaceBgeEmbeddings
from llama_index import ServiceContext

embed_model = HuggingFaceBgeEmbeddings(model_name="BAAI/bge-base-en")

service_context = ServiceContext.from_defaults(embed_model=embed_model)

**Comment by axz91** [comment]
cannot import name 'resolve_embed_model' from 'llama_index.embeddings' (C:\Users\ab880\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\embeddings\__init__.py)

**Comment by logan-markewich** [comment]
@axz91 What llama-index version do you have? It should be wrapping the embeddings with our wrapper automatically, but for now, do this

```python
from llama_index.embeddings import LangchainEmbedding

embed_model = LangchainEmbedding(
    HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
)
```

**Comment by axz91** [comment]
> @axz91 What llama-index version do you have? It should be wrapping the embeddings with our wrapper automatically in newer versions, but for now, do this
> 
> ```python
> from llama_index.embeddings import LangchainEmbedding
> 
> embed_model = LangchainEmbedding(
>     HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
> )
> ```
Thanks. Now there is another issue 

response = query_engine.query("tell me the document you have?")
print(response)


RecursionError: maximum recursion depth exceeded while calling a Python object
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?6b381ee1-35f8-4d75-b57b-c9446ffbb8ba) or open in a [text editor](command:workbench.action.openLargeOutput?6b381ee1-35f8-4d75-b57b-c9446ffbb8ba). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by logan-markewich** [comment]
@axz91 do you have a more complete traceback? Pretty hard to debug with just that.

To me it's likely caused by library version issues -- I would just start with a fresh venv

**Comment by axz91** [comment]
> @axz91 do you have a more complete traceback? Pretty hard to debug with just that.
> 
> To me it's likely caused by library version issues -- I would just start with a fresh venv






RecursionError                            Traceback (most recent call last)
Cell In[97], line 1
----> 1 response = query_engine.query("tell me the document you have?")
      2 print(response)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\indices\query\base.py:23](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/indices/query/base.py:23), in BaseQueryEngine.query(self, str_or_query_bundle)
     21 if isinstance(str_or_query_bundle, str):
     22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23 response = self._query(str_or_query_bundle)
     24 return response

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\query_engine\retriever_query_engine.py:175](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/query_engine/retriever_query_engine.py:175), in RetrieverQueryEngine._query(self, query_bundle)
    169         nodes = self.retrieve(query_bundle)
    171         retrieve_event.on_end(
    172             payload={EventPayload.NODES: nodes},
    173         )
--> 175     response = self._response_synthesizer.synthesize(
    176         query=query_bundle,
    177         nodes=nodes,
    178     )
    180     query_event.on_end(payload={EventPayload.RESPONSE: response})
    182 return response

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\response_synthesizers\base.py:125](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/response_synthesizers/base.py:125), in BaseSynthesizer.synthesize(self, query, nodes, additional_source_nodes)
    120     query = QueryBundle(query_str=query)
    122 with self._callback_manager.event(
    123     CBEventType.SYNTHESIZE, payload={EventPayload.QUERY_STR: query.query_str}
    124 ) as event:
--> 125     response_str = self.get_response(
    126         query_str=query.query_str,
    127         text_chunks=[
    128             n.node.get_content(metadata_mode=MetadataMode.LLM) for n in nodes
    129         ],
    130     )
    132     additional_source_nodes = additional_source_nodes or []
    133     source_nodes = list(nodes) + list(additional_source_nodes)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\response_synthesizers\tree_summarize.py:149](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/response_synthesizers/tree_summarize.py:149), in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
    140     summaries = [
    141         self._service_context.llm_predictor.predict(
    142             summary_template,
   (...)
    145         for text_chunk in text_chunks
    146     ]
    148 # recursively summarize the summaries
--> 149 return self.get_response(
    150     query_str=query_str,
    151     text_chunks=summaries,
    152 )

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\response_synthesizers\tree_summarize.py:149](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/response_synthesizers/tree_summarize.py:149), in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
    140     summaries = [
    141         self._service_context.llm_predictor.predict(
    142             summary_template,
   (...)
    145         for text_chunk in text_chunks
    146     ]
    148 # recursively summarize the summaries
--> 149 return self.get_response(
    150     query_str=query_str,
    151     text_chunks=summaries,
    152 )

    [... skipping similar frames: TreeSummarize.get_response at line 149 (2948 times)]

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\response_synthesizers\tree_summarize.py:149](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/response_synthesizers/tree_summarize.py:149), in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
    140     summaries = [
    141         self._service_context.llm_predictor.predict(
    142             summary_template,
   (...)
    145         for text_chunk in text_chunks
    146     ]
    148 # recursively summarize the summaries
--> 149 return self.get_response(
    150     query_str=query_str,
    151     text_chunks=summaries,
    152 )

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\response_synthesizers\tree_summarize.py:101](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/response_synthesizers/tree_summarize.py:101), in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
     99 """Get tree summarize response."""
    100 text_qa_template = self._text_qa_template.partial_format(query_str=query_str)
--> 101 summary_template = SummaryPrompt.from_prompt(
    102     text_qa_template, prompt_type=PromptType.SUMMARY
    103 )
    104 # repack text_chunks so that each chunk fills the context window
    105 text_chunks = self._service_context.prompt_helper.repack(
    106     summary_template, text_chunks=text_chunks
    107 )

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\prompts\base.py:139](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/prompts/base.py:139), in Prompt.from_prompt(cls, prompt, llm, prompt_type)
    136         format_dict[var] = f"{{{var}}}"
    138 template_str = prompt.format(llm=llm, **format_dict)
--> 139 cls_obj = cls(
    140     template_str,
    141     prompt_type=prompt_type or PromptType.CUSTOM,
    142     **prompt.prompt_kwargs,
    143 )
    144 return cls_obj

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\prompts\base.py:45](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/llama_index/prompts/base.py:45), in Prompt.__init__(self, template, langchain_prompt, langchain_prompt_selector, output_parser, prompt_type, metadata, **prompt_kwargs)
     40     if template is None:
     41         raise ValueError(
     42             "`template` must be specified if `langchain_prompt` is None"
     43         )
---> 45     self.prompt = LangchainPrompt.from_template(
     46         template=template, **prompt_kwargs
     47     )
     48     self.prompt_selector = PromptSelector(default_prompt=self.prompt)
     49 # finally, check if langchain_prompt is provided
     50 else:

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\prompts\prompt.py:218](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/langchain/prompts/prompt.py:218), in PromptTemplate.from_template(cls, template, template_format, partial_variables, **kwargs)
    213 if _partial_variables:
    214     input_variables = {
    215         var for var in input_variables if var not in _partial_variables
    216     }
--> 218 return cls(
    219     input_variables=sorted(input_variables),
    220     template=template,
    221     template_format=template_format,
    222     partial_variables=_partial_variables,
    223     **kwargs,
    224 )

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\load\serializable.py:74](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/langchain/load/serializable.py:74), in Serializable.__init__(self, **kwargs)
     73 def __init__(self, **kwargs: Any) -> None:
---> 74     super().__init__(**kwargs)
     75     self._lc_kwargs = kwargs

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py:339](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/main.py:339), in pydantic.main.BaseModel.__init__()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py:1076](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/main.py:1076), in pydantic.main.validate_model()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:895](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:895), in pydantic.fields.ModelField.validate()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:928](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:928), in pydantic.fields.ModelField._validate_sequence_like()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:1094](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:1094), in pydantic.fields.ModelField._validate_singleton()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:884](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:884), in pydantic.fields.ModelField.validate()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:1101](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:1101), in pydantic.fields.ModelField._validate_singleton()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\fields.py:1157](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/fields.py:1157), in pydantic.fields.ModelField._apply_validators()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\class_validators.py:337](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/class_validators.py:337), in pydantic.class_validators._generic_validator_basic.lambda13()

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\validators.py:61](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ab880/Documents/GitHub/gtp/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydantic/validators.py:61), in pydantic.validators.str_validator()

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by logan-markewich** [comment]
Yea this feels like a pydantic issue. Try `pip install pydantic==1.10.12`

**Comment by axz91** [comment]
> Yea this feels like a pydantic issue. Try `pip install pydantic=1.10.12` maybe? Or update your llama index version

Now no error, but I only got output:

None

**Comment by logan-markewich** [comment]
That could be any number of things. Did you load the correct files? Are you connecting to an existing vector store, and if so, did you connect properly?

**Comment by axz91** [comment]
> That could be any number of things. Did you load the correct files? Are you connecting to an existing vector store, and if so, did you connect properly?

i think i did connecting the vector store properly

**Comment by logan-markewich** [comment]
Can you share the code for that? Something must not be correct, since it's not finding any nodes 🤔

**Comment by axz91** [comment]
> Can you share the code for that? Something must not be correct, since it's not finding any nodes 🤔

Here is my code https://github.com/axz91/gtp/blob/main/immu.ipynb

**Comment by logan-markewich** [comment]
@axz91 loading an existing chroma index (towards the end) should probably look more like this 

```
index = VectorStoreIndex.from_vector_store(
    vector_store
    service_context=service_context,
)
```

Also, your service context settings above that are kind of out of whack. The chunk size in the prompt helper is waaaay too small  (although you aren't setting it in the service context, but thought I'd point it out)

```
node_parser = SimpleNodeParser(
  text_splitter=TokenTextSplitter(chunk_size=512, chunk_overlap=100)
)

prompt_helper = PromptHelper(
  context_window=3900,  # llama2 input size is 4096, decrease slightly to leave room for token counting errors
  num_output=256,
  chunk_overlap_ratio=0.1,
)
```

**Comment by axz91** [comment]
> @axz91 loading an existing chroma index (towards the end) should probably look more like this
> 
> ```
> index = VectorStoreIndex.from_vector_store(
>     vector_store
>     service_context=service_context,
> )
> ```
> 
> Also, your service context settings above that are kind of out of whack. The chunk size in the prompt helper is waaaay too small (although you aren't setting it in the service context, but thought I'd point it out)
> 
> ```
> node_parser = SimpleNodeParser(
>   text_splitter=TokenTextSplitter(chunk_size=512, chunk_overlap=100)
> )
> 
> prompt_helper = PromptHelper(
>   context_window=3900,  # llama2 input size is 4096, decrease slightly to leave room for token counting errors
>   num_output=256,
>   chunk_overlap_ratio=0.1,
> )
> ```

still nothing get back

**Comment by bmax** [comment]
If you're loading no documents and using a vector store index it will not be able to answer 1+1 unless the answer is in your documents.

If you want to use things outside of the document try using an Agent, https://gpt-index.readthedocs.io/en/stable/end_to_end_tutorials/agents.html#agents

Feel free to join the discord for more help!

**Comment by aryangoyal90** [comment]
I am creating a query engine by Llama-index using HuggingFace Api embedding.
I am using Llama-index version v0.10.10
## **Full Code:-**
```
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.core.node_parser import SimpleNodeParser
from llama_index.core import ServiceContext,StorageContext

from llama_index.llms.huggingface import HuggingFaceInferenceAPI    
from llama_index.embeddings.langchain import LangchainEmbedding
from langchain_community.embeddings.huggingface import HuggingFaceInferenceAPIEmbeddings

import os
from huggingface_hub import login

hf_token=''
login(hf_token)

os.environ['HuggingFaceHub_API_Token']= hf_token

Persis_Dir = './db'

llm= HuggingFaceInferenceAPI(
    model_name="HuggingFaceH4/zephyr-7b-alpha",
    api_key=hf_token
)

emb_model=HuggingFaceInferenceAPIEmbeddings(
    model_name="thenlper/gte-large",
    api_key=hf_token
)

documents = SimpleDirectoryReader('data').load_data()
parser=SimpleNodeParser()   #parsing_doc_into_nodes
nodes=parser.get_nodes_from_documents(documents)

StorageContext= StorageContext.from_defaults()

index=VectorStoreIndex(
    nodes,
    llm=llm,
    embed_model=emb_model,
    storage_context=StorageContext
)
```
#### Error:-
I am facing error in index line 
```
ValueError: "HuggingFaceInferenceAPIEmbeddings" object has no field "callback_manager"
```
--------------------------------
Service Context is deprecated since llama-index v10.10 so I have directly written llm=llm instead of defining service context.
What should I do??
