### ISSUE TITLE
[Question]: Query engine and context

### ISSUE THREAD

**Issue by uzumakinaruto19** [jerryjliu/llama_index#7628]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a way I could see what context goes through the query engine when I ask a question ? like what is the metadata
` 
index = GPTVectorStoreIndex.from_documents(documents)
service_context = ServiceContext.from_defaults(llm=ChatOpenAI(temperature=0, model_name=model_name, streaming=True),chunk_size=1000)`
`query_engine = index.as_query_engine(service_context=service_context, system_prompt=input_prompt, similarity_top_k=3, streaming=True) `
`quest = query_engine.query(input_prompt)
`

**Comment by logan-markewich** [comment]
@uzumakinaruto19 you can see the source nodes that were used by checking the response object

```
print(response.source_nodes[0].node.text)
print(response.source_nodes[0].node.metadata)
```

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 you can see the source nodes that were used by checking the response object
> 
> ```
> print(response.source_nodes[0].node.text)
> print(response.source_nodes[0].node.metadata)
> ```
@logan-markewich Hi thanks for the response,
I've been using it with Flask, but while trying to print it
`    print(response.source_nodes[0].node.text)
AttributeError: 'str' object has no attribute 'source_nodes'`

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 you can see the source nodes that were used by checking the response object
> 
> ```
> print(response.source_nodes[0].node.text)
> print(response.source_nodes[0].node.metadata)
> ```

From this, I'm getting the entire page's data not just relevant chunks, idk am I doing something wrong?

**Comment by logan-markewich** [comment]
@uzumakinaruto19 those nodes are the relevant chunks. They are the pieces of text that were sent to the llm to answer the query

They might look large, the default chunk size is 1024 tokens. 

You can get the similarity scores in a similar manner 

`print(response.source_nodes[0].score)`

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 those nodes are the relevant chunks. They are the pieces of text that were sent to the llm to answer the query
> 
> They might look large, the default chunk size is 1024 tokens.
> 
> You can get the similarity scores in a similar manner
> 
> `print(response.source_nodes[0].score)`

Okay, Thanks @logan-markewich 

Is it possible for me to view the complete prompt that is sent to the LLM, including my system prompt and relevant context,(after similarity serch) all together?

**Comment by logan-markewich** [comment]
@uzumakinaruto19 https://gpt-index.readthedocs.io/en/stable/end_to_end_tutorials/one_click_observability.html#simple-llm-inputs-outputs

Or if you are using openai 
```
import openai
openai.log = "debug"
```

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 https://gpt-index.readthedocs.io/en/stable/end_to_end_tutorials/one_click_observability.html#simple-llm-inputs-outputs
> 
> Or if you are using openai
> 
> ```
> import openai
> openai.log = "debug"
> ```

when i'm trying with 
`llama_index.set_global_handler("simple")`

``ValueError: Eval mode simple not supported.``

**Comment by logan-markewich** [comment]
@uzumakinaruto19 it was added in a recent version, you may have to upgrade to use it
