### ISSUE TITLE
[Bug]: ERROR WHEN USING 'chat_history' PARAMETER INSIDE engine.chat(). ERROR : 'dict' object has no attribute 'content'

### ISSUE THREAD

**Issue by sayantan-diatoz** [jerryjliu/llama_index#7629]
### Bug Description

engine=index.as_chat_engine() 
query="What You Want To Ask From Engine."
conversation=[
        {
            "role": "user",
            "content": "What is the revenue for India"
        },
        {
            "role": "assistant",
            "content": "The total revenue for India is 50000 Rupees."
        }       
    ]
response = engine.chat(message=query, chat_history=conversation)

GIVING ERROR AS : 'dict' object has no attribute 'content'.

### Version

0.8.5.post2

### Steps to Reproduce

Create an 'engine' from 'index.as_chat_engine()'.
query="What You Want To Ask From Engine."
Send previous conversation inside 'chat_history'.
Like,
response= engine.chat(message=query,chat_history=conversation).
Where,
conversation=[
        {
            "role": "user",
            "content": "What is the revenue for India"
        },
        {
            "role": "assistant",
            "content": "The total revenue for India is 50000 Rupees."
        }       
    ]

**Comment by sayantan-diatoz** [comment]
conversation=[
{
"role": "user",
"content": "What is the revenue for India?"
},
{
"role": "assistant",
"content": "The total revenue for India is 60000 Rupees."
}
]


How to work if the above format is coming from a Post API? 

How to put the above format inside chat_history?

**Comment by logan-markewich** [comment]
@sayantan-diatoz You just need to convert your chat history to `ChatMessage` objects like the bot suggests 👍🏻 

```
from llama_index.llms import ChatMessage

conversation = [ChatMessage(role="user", content="..."), ...]
```
