### ISSUE TITLE
multimodal/ Multimodal.ipynb example doesn't include vital details

### ISSUE THREAD

**Issue by pleabargain** [jerryjliu/llama_index#763]
There are a number of libs | imports not included
e.g. # ! pip install sentencepiece
#! pip install transformers
# ! pip install gpt_index

And the code insists on openai_api_key
but no matter how I try to set this VAR, the code complains that the openai_api_key doesn't exist.

reciept reader code complains for a long time:
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.

I tried with
OPENAI_API_KEY="sk-XXX"
and
openai_api_key="sk-XXX"
both failed with

Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by Disiok** [comment]
How do you currently set your API key? Do other notebook examples work?

**Comment by logan-markewich** [comment]
Going to close this issue, as being stale

For reference, there are several ways to set the key

in a bash terminal
`export OPENAI_API_KEY="my key"`

Directly in code
`import os`
`os.environ['OPENAI_API_KEY'] = "my key"`

Directly in LLM
`llm_predictor = LLMPredictor(llm=OpenAI(model_name='text-davinci-003', temperature=0, openai_api_key="my key"))`
