### ISSUE TITLE
[Bug]: OpenAI agent execution doesn't propagate trace_ids to function calls

### ISSUE THREAD

**Issue by mikeldking** [jerryjliu/llama_index#7639]
### Bug Description

Initialize an OpenAIAgent as follows:

```python
# Define very simple calculator tools for our agent

    def multiply(a: int, b: int) -> int:
        """Multiple two integers and returns the result integer"""
        return a * b

    multiply_tool = FunctionTool.from_defaults(fn=multiply)

    def add(a: int, b: int) -> int:
        """Add two integers and returns the result integer"""
        return a + b

    add_tool = FunctionTool.from_defaults(fn=add)
    llm = OpenAI(model="gpt-3.5-turbo-0613")
    cb_handler = OpenInferenceTraceCallbackHandler()
    callback_manager = CallbackManager(handlers=[cb_handler])
    agent = OpenAIAgent.from_tools(
        [multiply_tool, add_tool], llm=llm, verbose=True, callback_manager=callback_manager
    )
    agent.query("What is 2 * 3?")
 ```
  
where `OpenInferenceTraceCallbackHandler` can be any callback handler. even with `nested_asyncio` applied, the `start_trace` and `end_trace` don't get proper parent trace ids to correlate the function calls with the llm calls and vice versa
    

### Version

llama-index==0.8.21

### Steps to Reproduce

1. define a data agent

```python

    def multiply(a: int, b: int) -> int:
        """Multiple two integers and returns the result integer"""
        return a * b

    multiply_tool = FunctionTool.from_defaults(fn=multiply)

    def add(a: int, b: int) -> int:
        """Add two integers and returns the result integer"""
        return a + b

    add_tool = FunctionTool.from_defaults(fn=add)
    llm = OpenAI(model="gpt-3.5-turbo-0613")
    cb_handler = MyCallbackHander()
    callback_manager = CallbackManager(handlers=[cb_handler])
    agent = OpenAIAgent.from_tools(
        [multiply_tool, add_tool], llm=llm, verbose=True, callback_manager=callback_manager
    )
    agent.query("What is 2 * 3?")

```

where MyCallbackHander implements the `start_trace` and `end_trace` callback. 

Note that you will get distinct executions of `llm` and `function_call` but they will not be a part of the same trace.

**Comment by RogerHYang** [comment]
Because `CBEventType.LLM` is a [`LEAF_EVENT`](https://github.com/jerryjliu/llama_index/blob/518783f712e97a26837fd1d212ce67f0c30f6c09/llama_index/callbacks/schema.py#L71), the `current_trace_stack` gets appended to, even though it engenders children such as `CBEventType.FUNCTION_CALL`. See [here](https://github.com/jerryjliu/llama_index/blob/518783f712e97a26837fd1d212ce67f0c30f6c09/llama_index/callbacks/base.py#L90-L93).

**Comment by mikeldking** [comment]
As @RogerHYang mentioned, the trace for a data agent ends up looking like a fan-out with no root, making it hard to analyze the final input and output of the execution.

<img width="429" alt="Screenshot 2023-09-11 at 7 01 33 PM" src="https://github.com/jerryjliu/llama_index/assets/5640648/c615409f-5e1c-4643-9785-ece52d7937db">

**Comment by logan-markewich** [comment]
@mikeldking
just curious -- a flat fan-out correct right? Just the the lack of a root node

**Comment by mikeldking** [comment]
> @mikeldking
> 
> just curious -- a flat fan-out correct right? Just the the lack of a root node seems to be an issue?

Yes, I think having a root "span" would solve the issue

**Comment by logan-markewich** [comment]
Hmm, ran a quick test using your example above, but using `LlamaDebugHandler(print_on_trace_end=True)` to print the trace to terminal

I get something like this
```
**********
Trace: query
    |_CBEventType.LLM ->  1.29725 seconds
    |_CBEventType.FUNCTION_CALL ->  0.000256 seconds
    |_CBEventType.LLM ->  0.735938 seconds
**********
```

The `query` is the `trace_id` -- it should definitely be renamed. But I would consider this to be the root essentially 🤔
