### ISSUE TITLE
Load GPTSQLStructStoreIndex from disk

### ISSUE THREAD

**Issue by Thieund** [jerryjliu/llama_index#764]
Hi,
I've created a GPTSQLStructStoreIndex and saved it to disk.
Then I tried to load it from disk as following:
`index = GPTSQLStructStoreIndex.load_from_disk('citizenDb.json', sql_database=sql_database)`
I encountered the error "Only one of documents or index_struct can be provided."
Could anyone help me with that ? Thanks.

**Comment by Disiok** [comment]
Looks like a small bug, we will take a look at this soon!

**Comment by jerryjliu** [comment]
should be fixed by #765, will help land soon

**Comment by logan-markewich** [comment]
There is technically nothing to save with our struct stores (although we should do a better job at handling this). Tracking the issue internally, thanks!
