### ISSUE TITLE
[Bug]: AzureOpenAI.stream_chat causes IndexError

### ISSUE THREAD

**Issue by apptaro** [jerryjliu/llama_index#7640]
### Bug Description

AzureOpenAI.stream_chat causes IndexError. Not happening with OpenAI.stream_chat.

This has just started happening today, so probably something has changed on Azure OpenAI service.

### Version

0.8.23.post1

### Steps to Reproduce

Run the following code to reproduce the issue:

```
import os
from llama_index.llms import OpenAI, AzureOpenAI
from llama_index.llms.base import ChatMessage

use_azure = True

if use_azure:
    os.environ["OPENAI_API_TYPE"] = "azure"
    os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
    os.environ["OPENAI_API_BASE"] = "https://xxxx.openai.azure.com/"
    os.environ["OPENAI_API_KEY"] = "xxxxxxxxxxxxxxxxxxxxxxx"
    llm = AzureOpenAI(engine = "gpt-35-turbo")
else:
    os.environ["OPENAI_API_TYPE"] = "open_ai"
    os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxxxxxxxxxxx"
    os.environ["OPENAI_API_BASE"] = "https://api.openai.com/v1"
    llm = OpenAI()

for delta in llm.stream_chat([ChatMessage(content = "Hello!")]):
    print(delta)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/ubuntuuser/LlamaIndex_env/project/test.py", line 19, in <module>
    for delta in llm.stream_chat([ChatMessage(content = "Hello!")]):
  File "/home/ubuntuuser/LlamaIndex_env/lib/python3.10/site-packages/llama_index/llms/base.py", line 157, in wrapped_gen
    for x in f_return_val:
  File "/home/ubuntuuser/LlamaIndex_env/lib/python3.10/site-packages/llama_index/llms/openai.py", line 229, in gen
    delta = response["choices"][0]["delta"]
IndexError: list index out of range
```

**Comment by apptaro** [comment]
response["choices"][0] is causing the issue because the server returns an empty array:

```
{
  "id": "",
  "object": "",
  "created": 0,
  "model": "",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [],
  "usage": null
}

```

**Comment by ret2libc** [comment]
Another thing I just realized is that there probably was a change of behaviour of `AzureOpenAI` class. Before, setting `openai.api_version` was the right thing to do (AFAIR), but now you have to do `AzureOpenAI(api_version='....')`, otherwise it will use the default `2023-08-01-preview`, which generates the error we are seeing.

**Comment by logan-markewich** [comment]
Also I might revert that api change -- I realize that it doesn't line up with any of our docs

**Comment by ret2libc** [comment]
> Yea we can make the same fix as langchain -- but why is the response empty? Why are there no choices? Feels weird tbh

I'm not sure tbh. I think it has to do with the first message bringing only the content filtering data.

> Also I might revert that api change -- I realize that it doesn't line up with any of our docs

Let us know please. Thanks!
