### ISSUE TITLE
[Bug]: pdb in llama_cpp code affects execution

### ISSUE THREAD

**Issue by imartinez** [jerryjliu/llama_index#7653]
### Bug Description

During the fix of https://github.com/jerryjliu/llama_index/issues/7547, a call to `pdb` was introduced, in https://github.com/jerryjliu/llama_index/commit/94912afd2c15fc10b7eddbe7f95cba8555fd1fc6. 

It should not be in the final code, as it can affect production execution and affect the development work.

### Version

v0.8.24

### Steps to Reproduce

When LlamaCPP is created without specifying a model_path, the pdb is imported and stops the execution.

It can be found by checking llama_index/llms/llama_cpp.py L105

`        else:
            cache_dir = get_cache_dir()
            import pdb

            pdb.set_trace()
            model_url = model_url or self._get_model_path_for_version()
            model_name = os.path.basename(model_url)`

**Comment by logan-markewich** [comment]
Just cut v0.8.25 to fix this. Thanks for the catch!
