### ISSUE TITLE
[Question]: Connectiing multiple index to create one chat engine

### ISSUE THREAD

**Issue by Siddharth-1698** [jerryjliu/llama_index#7674]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi I have multiple index, I am using chromadb for storing vectors, Each collection is separate index. I want to create one chat engine combining all these collections or indexes, how do I do it?
I tried  adding doc to the same collection to create one collection but it only stored 2 files and after that it did not store anything.
Here's my chroma collection code:
chroma_client = chromadb.PersistentClient(
    path="./storage/vector_storage/chromadb/"
)
chroma_collection = chroma_client.create_collection(
            f"{user_id}_{filename}_collection")

**Comment by logan-markewich** [comment]
Likely using an agent is the best solution here
https://gpt-index.readthedocs.io/en/stable/examples/agent/openai_agent_with_query_engine.html#openai-agent-with-query-engine-tools

You can also force an agent to call a certain tool for every user message if that's something you want

```
agent = OpenAIAgent.from_tools(tools, function_call="tool_name_to_always_call")
```
