### ISSUE TITLE
Amazon S3 or Pinecone for Vector Store?

### ISSUE THREAD

**Issue by akshaysoni099** [jerryjliu/llama_index#7683]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm building a chatbot for document Q&A, for deployment I need an online store for vector storage. I can see 2 implementations in the document, one is with amazon s3 and other with pinecone vector store. Which one should I use and when is one required over other?

**Comment by logan-markewich** [comment]
@akshaysoni099 yea, S3 is for file storage -- i.e. using the basic vector store backend that saves to local json files. This is good for fast experimentation and smaller indexes.

Pinecone (or any other vector db, like weaviate, qdrant, chroma) is more optimized for larger indexes and faster retrieval
