### ISSUE TITLE
[Bug]: KeyError in retriever.retrieve when sent index does not include all nodes in document store

### ISSUE THREAD

**Issue by c64er4ever** [jerryjliu/llama_index#7684]
### Bug Description

Hi,
I have created multiple indexes, each covering different set of nodes. I am then using one of the indexes to retrieve nodes based on a query. However, it seems that the retriever is trying to process nodes that are out of the context of the specific index that I have provided, causing a KeyError exception in this line in llama_index/indices/vector_store/retrievers/retriever.py:
self._index.index_struct.nodes_dict[idx] for idx in query_result.ids

I noticed that it is possible to send list of node_ids to retrieve in order to constraint it. Haven't tried it yet and I guess that it will work. However, I believe that it is better if the retrieve function itself verifies that only nodes that are covered by the provided index are processed.

Thanks!
Guy

### Version

0.8.5.post2

### Steps to Reproduce

1. Create doc store with X nodes (e.g. 100)
2. Create index that covers only part of the nodes (e.g. 10)
3. Use the created index to create a Retriever: retriever = VectorIndexRetriever(my_index)
4. Call retrieve with a question: nodes = retriever.retrieve("This is my question")

If the query returns nodes that are excluded from the provided index, KeyError exception occurs

**Comment by logan-markewich** [comment]
The bot is right! If you aren't using `index.as_retriever(..)`, then you need to pass in the doc_ids

**Comment by afalamna** [comment]
@logan-markewich I am facing this isssue and I added the code snippet provided by the bot in retriever.py but its still giving me this error. This is my code.

from llama_index.llms import OpenAI
from llama_index.embeddings import TextEmbeddingsInference
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext, StorageContext, load_index_from_storage
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.node_parser import SimpleNodeParser
from llama_index.query_engine import RetrieverQueryEngine


documents = SimpleDirectoryReader(
    input_files=["uber_10q_june_2022.pdf","uber_10q_march_2022.pdf"]
).load_data()

embed_model = TextEmbeddingsInference(
    model_name="BAAI/bge-large-en-v1.5",  # required for formatting inference text,
    timeout=60,  # timeout in seconds
    embed_batch_size=10,  # batch size for embedding
)

llm = OpenAI(temperature=0, model="gpt-3.5-turbo", max_tokens=1024)
print('Processing......')
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model)
index = VectorStoreIndex.from_documents(documents = documents,service_context=service_context)
query_engine = index.as_query_engine(similarity_top_k=3)

**Comment by comptoircsf-blip** [comment]
Cherche Un api utiliser photoshop et capcut professionnel
