### ISSUE TITLE
[Bug]: Issues with the "Local Llama2 + VectorStoreIndex" notebook

### ISSUE THREAD

**Issue by sia-cerebras** [jerryjliu/llama_index#7693]
### Bug Description

Issue is regarding this notebook: [https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb](https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb)

The code creates a HuggingFaceLLM `llm` object but never uses it.

Further down when it called `index = VectorStoreIndex.from_documents(documents)`, it errors out asking for OpenAI

When I add the OpenAI key, it work, BUT now my question is when I call `query_engine.query("blah?")` is it using OpenAI API or is it using `llm`. I'm asking because `llm` is not referenced anywhere. 

### Version

0.8.27

### Steps to Reproduce

Run this notebook [https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb](https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb)

**Comment by logan-markewich** [comment]
It's updated now, just had to use the service context
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemoLlama-Local.ipynb
