### ISSUE TITLE
[Question]: How do I stop the system from printing "Llama.generate: prefix-match hit" when using  query_engine.query?

### ISSUE THREAD

**Issue by robgon-art** [jerryjliu/llama_index#7699]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am running the LlaMaCPP example from the notebook here, https://github.com/jerryjliu/llama_index/blob/main/docs/examples/llm/llama_2_llama_cpp.ipynb

It runs fine, but I keep getting this notification, "Llama.generate: prefix-match hit"

```
...
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)

Llama.generate: prefix-match hit
  Based on the given context information, the author's childhood activities were writing short stories and programming. They wrote programs on punch cards using an early version of Fortran and later used a TRS-80 microcomputer to write simple games, a program to predict the height of model rockets, and a word processor that their father used to write at least one book.
```

How do I disable this? I tried setting the logging level to CRITICAL, but it didn't help.

```
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.CRITICAL)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
```
I'm running llama_index v0.8.28.

**Comment by robgon-art** [comment]
Hello, here are the answers to your questions.

1. OS: Ubuntu 22.04.2 LTS
2. Python version: 3.10.12
3. LlamaCPP version: 0.1.78 (from llama-cpp-python)

I see this info message when I run queries using an index of documents.

These show the info message:
```
documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)

query_engine = index.as_chat_engine(chat_mode="context")
response = query_engine.chat("What did the author do growing up?")
print(response)
response = query_engine.chat("Oh interesting, tell me more.")
print(response)
```

But this one doesn't:
```
response_iter = llm.stream_complete("What did Paul Graham do growing up?")
```

**Comment by logan-markewich** [comment]
@robgon-art tbh I have no idea for sure, it's coming from the llama-cpp-python library. 

You can try setting verbose=False on the llm definition

```
from llama_index.llms import LlamaCPP

llm = LlamaCPP(..., verbose=False)

service_context = ServiceContext.from_defaults(llm=llm)
```

https://gpt-index.readthedocs.io/en/stable/examples/llm/llama_2_llama_cpp.html#setup-llm

**Comment by robgon-art** [comment]
@logan-markewich Thanks for the tip!

Looking in the llama-cpp-python repo, I found this:
```
if self.verbose:
  print("Llama.generate: prefix-match hit", file=sys.stderr)
```
https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama.py#L765

I'll close this here. But I'll report back with the results of testing with `verbose=False`
