### ISSUE TITLE
Is there a way to prevent the model from querying things unrelated to the data?

### ISSUE THREAD

**Issue by ahmedpanju** [jerryjliu/llama_index#770]
I currently have a .txt file that is being indexed, and queried against. It's working really well, except the model still answers questions that are unrelated to things in the .txt file (ex. I can ask "When was world war 2" despite the .txt file being about job descriptions)

Is there a workaround for this, and if not, has anyone managed to come up with a validation layer?

**Comment by Disiok** [comment]
Hey @ahmedpanju, it's generally a hard problem to ensure model stick to the given context. I think the instruction fine-tuned models are better in this regard, but also cannot guarantee. 

Having a general validation layer would be challenging, but we have some ideas about leverage LLMs for evaluation/validation. Hope to have some initial version soon!

**Comment by Disiok** [comment]
Closing this for now. Please join the discord community (https://discord.gg/dGcwcsnxhU) for better support!
