### ISSUE TITLE
[Question]: Is token count correct?

### ISSUE THREAD

**Issue by uzumakinaruto19** [jerryjliu/llama_index#7710]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i was trying to get the token usage using the token counter, while printing the 

`token_counter.prompt_llm_token_count` 
I'm getting around 5000 or more tokens , but I am using gpt-3.5-turbo as my model and that has a token limit of  4,096 ?
am I doing some thing wrong or is the calculation wrong??

ps:I'm passing my previous answer with the servicecontext to the system prompt that's why the input prompt is so big,, as of my understanding the input +completion should have 4096 tokens to be used, in my case still its Generates the response even if the input prompt is more than 4096

Any help will be greatly appreciated

**Comment by logan-markewich** [comment]
@uzumakinaruto19 the system may be doing more than one LLM call, depending on your settings. If the retrieved nodes for a query don't fit into a single LLM call, an answer is refined

**Comment by logan-markewich** [comment]
@uzumakinaruto19 https://gpt-index.readthedocs.io/en/stable/core_modules/query_modules/query_engine/response_modes.html#response-modes

**Comment by uzumakinaruto19** [comment]
Hi, @logan-markewich 
Still, I'm confused with the LLM prompt token, because when I manually calculate the input that goes to the model as prompt that token has a huge difference from what I got from `token_counter.prompt_llm_token_count`

**Comment by logan-markewich** [comment]
@uzumakinaruto19 and how are you counting tokens?

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 and how are you counting tokens? Where are you getting the text to count from? Can you make an example?

im assuming its my system prompt + the retrieved chunks+the query

**Comment by uzumakinaruto19** [comment]
> > @uzumakinaruto19 and how are you counting tokens? Where are you getting the text to count from? Can you make an example?
> 
> im assuming its my system prompt + the retrieved chunks+the query and I get the sum of this and count using tiktoken

**Comment by logan-markewich** [comment]
I think it will make sense if you just read the source code.

If you find an issue, feel free to open a PR and we can get that merged

https://github.com/jerryjliu/llama_index/blob/0e094f5ea9239989f0c3f316deb9d24a79adc4be/llama_index/callbacks/token_counting.py#L117

**Comment by logan-markewich** [comment]
The token counting includes more than just the returned chunks, query, and system prompt

There's also the prompt template itself. Plus I'd the refine prompt is hit(which it is in your case) then there is also the previous answer to include

**Comment by logan-markewich** [comment]
If you set a breakpoint in the token counter, it will probably make more sense
