### ISSUE TITLE
[Question]: Does OpenAIAgent support the use of customllm

### ISSUE THREAD

**Issue by 123zzw** [jerryjliu/llama_index#7721]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, the performance of OpenAIAgent is very impressive. I recently encountered a problem where when I use a local model, it seems that OpenAIAgent is not working and can only treat the local model as a conversation assistant.So I would like to ask if OpenAIAgent does not support loading local models, that is, openai must be used instead of customLLM. 
What should I do if I want to use customllm?

**Comment by logan-markewich** [comment]
@123zzw the openai agent using the Function Calling API from OpenAI. It is much more reliable than a typical react agent, since the function/tool selection is baked into the model/api

You can use it with a custom LLM, but that custom LLM needs to support a similar API. LlamaAPI is an example of this
https://github.com/jerryjliu/llama_index/blob/1ae5a686490e3f9dc0bdd2c5daa713ea2b9eb993/llama_index/llms/llama_api.py#L81

Specifically, the LLM metadata should indicate that it is a function calling LLM

**Comment by 123zzw** [comment]
> @123zzw the openai agent using the Function Calling API from OpenAI. It is much more reliable than a typical react agent, since the function/tool selection is baked into the model/api
> 
> You can use it with a custom LLM, but that custom LLM needs to support a similar API. LlamaAPI is an example of this
> 
> https://github.com/jerryjliu/llama_index/blob/1ae5a686490e3f9dc0bdd2c5daa713ea2b9eb993/llama_index/llms/llama_api.py#L81
> 
> Specifically, the LLM metadata should indicate that it is a function calling LLM

Thank you very much for your reply. I tried llama2-13b chat locally, but when running this [demo](https://gpt-index.readthedocs.io/en/stable/examples/agent/openai_agent_with_query_engine.html#openai-agent-with-query-engine-tools), I replaced the model with llama2-13b chat. At this time, the model cannot access my local files and can only have normal conversations with me that are not based on files. What is the reason for this? I look forward to your reply very much.

**Comment by logan-markewich** [comment]
@123zzw yea once again, the openai agent is only supported for function calling models. Llama2 is not a function calling model, unless you have some special api on top of it

I would use a react agent instead
https://gpt-index.readthedocs.io/en/stable/examples/agent/react_agent_with_query_engine.html

**Comment by 123zzw** [comment]
> function calling models

Thank you for your detailed explanation. I have understood the reason behind it！
