### ISSUE TITLE
[Question]: Compatibility issue with snowflake-sqlalchemy

### ISSUE THREAD

**Issue by arsentievalex** [jerryjliu/llama_index#7725]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I'm running into what it seems to be a version compatibility issue between llama-index and snowflake-sqlalchemy. I'd like to use a DatabaseReader to read the data from Snowflake.
When trying to deploy an app to the Streamlit cloud I get the following message:

```
llama-index 0.8.29 depends on sqlalchemy>=2.0.15
snowflake-sqlalchemy 1.5.0 depends on sqlalchemy<2.0.0 and >=1.4.0
```

Is there a way to introduce support for sqlalchemy <2? maybe an earlier version of llama-index?

**Comment by bmax** [comment]
@arsentievalex Thanks for opening this issue.

Unfortunately LlamaIndex isn't able to support an older version of sqlalchemy, rather snowflake-sqlalchemy should support the newer version. 

which, looking at their [pypi](https://pypi.org/project/snowflake-sqlalchemy/) it looks like it does support it in version `v1.4.1(Aug 18, 2022)`

Feel free to pop in the discord if you need any other help.
