### ISSUE TITLE
[Question]: Metadata exclusion

### ISSUE THREAD

**Issue by ddealwis09** [jerryjliu/llama_index#7733]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Using SimpleDirectoryReader, is there a way to pass only certain metadata applied to the document to the nodes using the metadataextractors? i.e. I want some metadata on the document to only be used for metadata filtering in my app but do not want to include them on the nodes and embeddings. Thanks!

**Comment by logan-markewich** [comment]
@ddealwis09 you can set excluded keys

```
document.excluded_embed_metadata_keys = ["key"]
document.excluded_llm_matadata_keys = ["key"]
```

**Comment by bmax** [comment]
Closing this issues, if you have any more questions please stop by the Discord!
