### ISSUE TITLE
[Documentation]: overview of `examples/`

### ISSUE THREAD

**Issue by jamesbraza** [jerryjliu/llama_index#7736]
### Documentation Issue Description

It would be nice to make either a:

- `README.md` within [`examples/`](https://github.com/jerryjliu/llama_index/tree/main/examples)
- Page in the ReadTheDocs

Explaining the various `examples/`, and what's significant/notable about each of them

### Documenation Link

https://github.com/jerryjliu/llama_index/tree/main/examples

**Comment by logan-markewich** [comment]
This folder actually should be removed. All maintained notebooks are in docs/examples, since those notebooks can be properly linked in the docs and converted to html

**Comment by jamesbraza** [comment]
It looks like `examples/` has some examples that aren't in `docs/examples/`.  Maybe they get moved to `docs/examples/` instead of just being removed entirely.

One question is, where does `docs/examples/` show up in https://gpt-index.readthedocs.io/en/stable/index.html?

**Comment by logan-markewich** [comment]
Yea I think anything still in `/examples` is just not maintained lol and should be removed imo 

Notebooks in `/docs/examples` show up in the docs only when they are linked from another page.

For example, here we link a bunch of example notebooks. And each one is rendered in the browser
https://gpt-index.readthedocs.io/en/stable/core_modules/agent_modules/agents/modules.html

**Comment by bmax** [comment]
Closing, feel free to create a PR and join the discord! @jamesbraza
