### ISSUE TITLE
Support for gpt-3.5-turbo 

### ISSUE THREAD

**Issue by rcala1** [jerryjliu/llama_index#774]
Is it possible to use newest gpt-3.5-turbo for llm_predictor in indices?

...
llm_predictor = LLMPredictor(llm=OpenAI(model_name="gpt-3.5-turbo"))
index_csv = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor)
...

**Comment by logan-markewich** [comment]
@rcala1 you should use the ChatOpenAI class instead. See this example: https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb

**Comment by rcala1** [comment]
@logan-markewich Thank you
