### ISSUE TITLE
[Bug]: Hybrid Postgresql hardcoded "text_search_tsv_idx"

### ISSUE THREAD

**Issue by bogdanalexandrutreica** [jerryjliu/llama_index#7740]
### Bug Description

When I want to create a new table with embeddings I get this error

Error: CREATE INDEX text_search_tsv_idx ON data_test_folder_2 USING gin (text_search_tsv)

because of the "text_search_tsv_idx" is hardcoded in the file /vector_store/postgres.py

Pyhton version: Python 3.10.12

### Version

0.8.29.post1

### Steps to Reproduce

Just try to create a new table with a different name using PGVectorStore + hybrid_search = True

I solved the problem locally by using

like line 45 in postgres.py
**indexname = "idx_%s"  % index_name  # dynamic index name**

and on line 67
Index(
            **indexname,**
            model.text_search_tsv,  # type: ignore
            postgresql_using="gin",
        )

**Comment by logan-markewich** [comment]
This has been fixed in a PR
https://github.com/jerryjliu/llama_index/pull/7741
