### ISSUE TITLE
Options to save the vector database locally (apart from Chroma and FAISS)

### ISSUE THREAD

**Issue by zzadiues** [jerryjliu/llama_index#7745]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am searching for vector database options that let you save the vector database on disk locally. I know that ChromaDB and FAISS let you do that but I am unable to use either due to some complications. 

Are there any other vector databases that allow you to save locally ? 

It seems that options like epsilla or weaviate only keep the database in memory and we need to regenerate those every time
we restart the application. Amiright?
Folks kindly help me out im a newbie in all this..
Thanks a ton

**Comment by logan-markewich** [comment]
Qdrant also saves locally. In fact, any db that is listed as "self-hosted" here are storing files locally, whether in a db table or in actual files 
https://gpt-index.readthedocs.io/en/stable/core_modules/data_modules/storage/vector_stores.html#vector-store-options-feature-support
