### ISSUE TITLE
[Question]: Are there any restrictions on where files can be placed when creating an index from a file?

### ISSUE THREAD

**Issue by Ma-Fukudama** [jerryjliu/llama_index#7751]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Even if you specify the path where the file is located when creating an index from a file, it will not be created successfully.
Will the index not be created unless the file is placed in the data directory under the path where the python file is located?

**Comment by bmax** [comment]
Hey @Ma-Fukudama,

Thanks for writing in. Are you using https://gpt-index.readthedocs.io/en/stable/examples/data_connectors/simple_directory_reader.html 

If so, it should the directory + files should be accessible / exist. 

Please feel free to join discord if you have any other questions!
