### ISSUE TITLE
[Question]:node strategy 

### ISSUE THREAD

**Issue by ddealwis09** [jerryjliu/llama_index#7756]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
Does llama-index have any abstractions for optimizing the node chunking - chunk size and overall for a specific document? 

Thanks!

**Comment by bmax** [comment]
Hey @ddealwis09,

Check out this documentation, you can control the text splitter, chunk size, chunk overlap and more.
https://gpt-index.readthedocs.io/en/stable/core_modules/data_modules/node_parsers/usage_pattern.html

Feel free to join the discord if you have any other questions!
