### ISSUE TITLE
[Documentation]: Cost Analysis Documentation doesnt work.

### ISSUE THREAD

**Issue by GinoWoz1** [jerryjliu/llama_index#7762]
### Documentation Issue Description

I really need to calculate token usage but I follow this documentation to a T and it does not work, any idea? If you go to MockLLMPredictor, there is no attribute last_token_usage.

MockLLMPredictor Class: https://github.com/jerryjliu/llama_index/blob/2f95b888746e0509244029a894ab4f67080f0fc4/llama_index/llm_predictor/mock.py#L87

### Documenation Link

https://gpt-index.readthedocs.io/en/v0.6.31/how_to/analysis/cost_analysis.html

**Comment by GinoWoz1** [comment]
Thanks @bmax . Does this line of code cost anything since it is referencing gpt-3.5-turbo? Trying to understand the usage. 

`tokenizer=tiktoken.encoding_for_model("gpt-3.5-turbo").encode`

**Comment by bmax** [comment]
No, that does not call any api's just uses BPE tokenizer

https://github.com/openai/tiktoken
