### ISSUE TITLE
[Question]: For NLSQLTableQueryEngine, how to use a GGUF LLM model other than the default Llama 2 Q4_0?

### ISSUE THREAD

**Issue by ridho-0** [jerryjliu/llama_index#7814]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have successfully followed [this tutorial](https://gpt-index.readthedocs.io/en/stable/end_to_end_tutorials/structured_data/sql_guide.html). However, I encountered some problems while trying to test other GGUF models. None of them return any `sql_query`. That is, within the `Response`, I always get `metadata={'sql_query': ''}`.

Then I tried to explicitly pass the default model (via `ServiceContext`) into `NLSQLTableQueryEngine`, but I'm still having the same problem as above. 

Specifically, this works:
```
query_engine = NLSQLTableQueryEngine(
    sql_database=sql_database,
    tables=["city_stats"],
)
```
and when calling `query_engine.query(query_str)` I would get responses like:
`Response(response='  Based on the query results, the city with the highest population is Tokyo, with a population of 13960000.', source_nodes=[], metadata={'result': [('Tokyo', 13960000)], 'sql_query': 'SELECT city_name, population FROM city_stats WHERE population = (SELECT MAX(population) FROM city_stats);'})`

But this doesn't work:
```
llm_url = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf"
llm = LlamaCPP(model_url=llm_url, 
               model_kwargs={"n_gpu_layers": 1},
              )
service_context = ServiceContext.from_defaults(llm=llm)
query_engine = NLSQLTableQueryEngine(
    sql_database=sql_database,
    tables=["city_stats"],
    service_context=service_context
)
```
despite the fact that it uses the exact same model. 
I get responses like:
`Response(response='\n\nPlease provide the SQL query and the response you would like to generate based on that query. Then, I can help you synthesize a response from the query results.', source_nodes=[], metadata={'sql_query': ''})`
the `response`s can be different, and they can sometimes be gibberish, but in 10 questions that I have tested they all return empty `sql_query`. This doesn't happen when I did not specify the LLM explicitly (on the contrary it works well).

I have checked my Cache folder (where the models are downloaded and stored), and I confirm that there is only one Llama 2 13B Chat Q4_0 GGUF model there.

Maybe there are some other parameters on `LlamaCPP`, `service_context`, or `query_engine` that I also need to explicitly set? But after scouring the codebase, I see that everything should be set automatically in the same way when I let the `query_engine` retrieves the model itself.

**Comment by ridho-0** [comment]
> However, it's not clear from your question whether the GGUF LLM model you're trying to use is different from the default LLM model used by the NLSQLTableQueryEngine

It should be the same one. I used https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf, which is also used in `DEFAULT_LLAMA_CPP_GGUF_MODEL`.

https://github.com/jerryjliu/llama_index/blob/c81a0761defc2f9aac3ec3009e8bde4b2436d055/llama_index/llms/llama_cpp.py#L33-L35

**Comment by ridho-0** [comment]
@dosu-bot

> However, it's not clear from your question whether the GGUF LLM model you're trying to use is different from the default LLM model used by the NLSQLTableQueryEngine

It should be the same one. I used https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf, which is also used in `DEFAULT_LLAMA_CPP_GGUF_MODEL`.

https://github.com/jerryjliu/llama_index/blob/c81a0761defc2f9aac3ec3009e8bde4b2436d055/llama_index/llms/llama_cpp.py#L33-L35

**Comment by ridho-0** [comment]
@dosu-bot

I am not accessing the `sql_query` directly, I am just using `query_engine.query(query_str)` for several `query_str`s and checking the generated responses (which include the `sql_query`).

I don't think it is a problem with the specific queries that I am using as I tested 10 and they work just well when I just don't specify the LLM URL explicitly. Some of the queries that I was testing:

- Which city has the highest population?
- Which city has the least population?
- Which country has the city with the highest population?
- Which country has the highest total population?
- Which town has the most population?
- Which country has the town with the most population?

All returned `{'sql_query': ''}` within the response. But when I don't explicitly specify the LLM and let the default settings run, they all return a query (although some of them are incorrect).

**Comment by logan-markewich** [comment]
@ridho-0 You'll need to include extra formatting logic to ensure the prompts to the LLM are adjusted to Llama2 format

See this example for the full code -- notice the functions we use from llama_utils
https://gpt-index.readthedocs.io/en/stable/examples/llm/llama_2_llama_cpp.html#setup-llm

**Comment by ridho-0** [comment]
@logan-markewich thank you, that fixes it. Follow-up question then

(1) How do I correctly specify customs `messages_to_prompt` for a non-llamaGGUF model? I see that the current llama `message_to_prompt` is (somewhat) taken from the Prompt Template shown on the Huggingface Model page. Example below:

<img width="676" alt="image" src="https://github.com/jerryjliu/llama_index/assets/61729558/db585627-59e1-4320-971b-597f7d08b77d">

Is it always the same for other models? For example, these are the templates for Alpaca and Vicuna:

<img width="672" alt="image" src="https://github.com/jerryjliu/llama_index/assets/61729558/c3e9bb24-f98b-406e-9a70-2c84728a23a4">
<img width="700" alt="image" src="https://github.com/jerryjliu/llama_index/assets/61729558/f803366e-a72f-4ab6-82a9-b7e5249dd186">

If not, how do I find the correct formatting logic for these models?

(2) Will non-chat models work? For instance, this [XWin model](https://huggingface.co/TheBloke/Xwin-LM-13B-V0.1-GGUF), which uses Vicuna prompting format.

(3) I am a bit lost with the `completion_to_prompt`.  Is it essentially just the same format as the `messages_to_prompt` but without the actual messages itself?

**Comment by logan-markewich** [comment]
@ridho-0 

1) the model card should give the format. If not, then it's a mystery hunt 😅 such is the nature of open source

2) non chat models will work fine for query engines. For agents/chat engines, probably not so well

3) exactly. One takes a list of chat message objects, the other just has to format a single string prompt
