### ISSUE TITLE
[Feature Request]: Support for OllamaEmbeddings

### ISSUE THREAD

**Issue by shauryr** [jerryjliu/llama_index#7833]
### Feature Description

Ollama LLM is supported by llama-index for generation but not for embedding. 

Langchain supports the embedding model - https://api.python.langchain.com/en/latest/embeddings/langchain.embeddings.ollama.OllamaEmbeddings.html

It would be great if we can get the ollama embeddings working for llama-index as well

### Value of Feature

This will allow the users to run everything locally!

**Comment by shauryr** [comment]
nvm.

The following works - 

```python
from langchain.embeddings import OllamaEmbeddings
embed_model = OllamaEmbeddings(base_url="http://localhost:11434", model="llama2")
service_context = ServiceContext.from_defaults(
        llm = Ollama(model="llama2"),
        embed_model=embed_model
)
```

**Comment by akhoury** [comment]
@shauryr it's been added

```python
from llama_index import ServiceContext
from llama_index.llms import Ollama
from llama_index.embeddings import OllamaEmbedding

def create_base_context(model,  embed_model_name):
    llm = Ollama(model=model)
    embed_model = OllamaEmbedding(model_name=embed_model_name)
   return ServiceContext.from_defaults(
        llm=llm,
        embed_model=embed_model,
    )
```
