### ISSUE TITLE
[Question]: what is NL SQL?

### ISSUE THREAD

**Issue by jamesbraza** [jerryjliu/llama_index#7837]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am looking at `NLSQLTableQueryEngine`, and its docstring talks about NL SQL. I am pretty sure NL = natural language.

My question is, what is NL SQL? Google searching "natural language SQL" doesn't come up with a match.  It matches NL to SQL, but not NL SQL directly.

**Comment by logan-markewich** [comment]
Yea it's natural language

It just implies that (by default anyways) the response by the LLM will be in natural language

So there's 3 steps
1. Use the user query and SQL shcema to generate a SQL query
2. Run the SQL query
3. Use the SQL query + result + user query to generate a natural language response with the LLM

**Comment by jamesbraza** [comment]
Thanks @logan-markewich !
