### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'eval_utils'

### ISSUE THREAD

**Issue by zxiaodong-mineral** [jerryjliu/llama_index#7846]
### Bug Description

I have try to  fine tuning  adapter,when i import eval_utils, the model not found,
```
from eval_utils import evaluate, display_results
```
Please tell me why this problem occurs

Thanks！

### Version

 0.8.29.post1

### Steps to Reproduce

from eval_utils import evaluate, display_results

**Comment by zxiaodong-mineral** [comment]
> _🤖_
> 
> Hello,
> 
> The error you're encountering, "ModuleNotFoundError: No module named 'eval_utils'", is likely because the module 'eval_utils' is not found in your current Python environment. This could be due to a few reasons:
> 
> 1. If 'eval_utils' is a module you've created, please ensure it's located in the correct directory and that the directory is included in your Python path.
> 2. If 'eval_utils' is a third-party module, please make sure it's installed in your Python environment. You can do this by running `pip install eval_utils` or `conda install eval_utils`, depending on your package manager.
> 
> However, if 'eval_utils' is supposed to be a part of LlamaIndex, it's possible that it was removed or renamed in version 0.8.29.post1. I've checked the `llama_index/evaluation/__init__.py` file in the repository and 'eval_utils' is not among the imports.
> 
> Unfortunately, I couldn't find any specific information about the 'eval_utils' module being removed or renamed in the LlamaIndex version 0.8.29.post1 within the repository.
> 
> Could you please provide more information about where 'eval_utils' is supposed to come from? This will help me assist you better.
> 
> Best, Dosu
> 
> ## Sources
> * [llama_index/evaluation/**init**.py](https://github.com/jerryjliu/llama_index/blob/main/llama_index/evaluation/__init__.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Hello,

I ran it according to the llamaindex document.
Prompt to reference  'eval_utils' in the documentation, and 'eval_utils' is not a third-party module.
It may be that the doc is not updated causing this problem.
![image](https://github.com/jerryjliu/llama_index/assets/134027468/bc427876-7258-412c-833f-117465dcad36)

**Comment by logan-markewich** [comment]
`eval_utils` is a file next to the notebook. You can find it here:
https://github.com/jerryjliu/llama_index/blob/main/docs/examples/finetuning/embeddings/eval_utils.py
