### ISSUE TITLE
[Bug]: BaseSynthesizer does not work with TextNodes as nodex parameter

### ISSUE THREAD

**Issue by andreas-kopecky** [jerryjliu/llama_index#7854]
### Bug Description

BaseSynthesizer expects Node objects (passed in via nodes param) to have a "node" attribute (like NodeWithScore does).
This is, however, not the case for TextNode, Documents, etc.

https://github.com/jerryjliu/llama_index/blob/f8c95479bb9e502eb1eb4f938b942cb2551d6f08/llama_index/response_synthesizers/base.py#L131 is the link to the faulty line.

assuming that EVERY node object has a node attribute - which it does not.

### Version

0.8.35

### Steps to Reproduce

```
from llama_index.schema import Node, Document, NodeWithScore
from llama_index.response_synthesizers import ResponseMode, get_response_synthesizer
from llama_index.indices.service_context import ServiceContext
from llama_index.node_parser import SimpleNodeParser

parser = SimpleNodeParser.from_defaults()

content = ["I am a funny text", "I should be in context"]
nodes = [Node(text=t) for t in content]

response_synthesizer = get_response_synthesizer(
    response_mode=ResponseMode.ACCUMULATE, 
    service_context=ServiceContext.from_defaults(llm=llm)
)

response_synthesizer.synthesize("All your base are belong to us.", nodes=nodes)
```

results in

`AttributeError: 'TextNode' object has no attribute 'node'`

Wrapping nodes a second time as "NodeWithScore" fixes this but.

```
from llama_index.schema import Node, Document, NodeWithScore
from llama_index.response_synthesizers import ResponseMode, get_response_synthesizer
from llama_index.indices.service_context import ServiceContext
from llama_index.node_parser import SimpleNodeParser

parser = SimpleNodeParser.from_defaults()

content = ["I am a funny text", "I should be in context"]
nodes = [Node(text=t) for t in content]
l2_nodes = [NodeWithScore(node=n, score=1.0) for n in nodes]

response_synthesizer = get_response_synthesizer(
    response_mode=ResponseMode.ACCUMULATE, 
    service_context=ServiceContext.from_defaults(llm=llm)
)

response_synthesizer.synthesize("All your base are belong to us.", nodes=l2_nodes)
```
runs successfully but is rather stupid

**Comment by logan-markewich** [comment]
@andreas-kopecky The proper input here is `NodeWithScore` actually, if you follow the typing here
https://github.com/jerryjliu/llama_index/blob/f8c95479bb9e502eb1eb4f938b942cb2551d6f08/llama_index/response_synthesizers/base.py#L116

And `NodeWithScore` is defined here
https://github.com/jerryjliu/llama_index/blob/f8c95479bb9e502eb1eb4f938b942cb2551d6f08/llama_index/schema.py#L423

**Comment by andreas-kopecky** [comment]
Thanks for pointing out the typing hint - you should really update the synthesizer docs on your webpage though in that case since this uses lists of Nodes (i.e. TextNode) in every example.

**Comment by logan-markewich** [comment]
@andreas-kopecky just a single example uses Node by accident. Every other example I could find uses NodeWithScore

Will update accordingly
