### ISSUE TITLE
[Bug]: double curly brace breaking JSON marshaling in LLM selector

### ISSUE THREAD

**Issue by jamesbraza** [jerryjliu/llama_index#7886]
### Bug Description

Please see the below steps to reproduce, we should expand our JSON marshaling capabilities.

### Version

0.8.36

### Steps to Reproduce

Given the below `prediction` from a LLM predictor ([link](https://github.com/jerryjliu/llama_index/blob/v0.8.36/llama_index/selectors/llm_selectors.py#L103)):

```none
 Based on the given choices, the most relevant choice for the question "<redacted>?" is:
(1) Useful for <redacted>
The reason for this choice is <redacted>. Therefore, option (1) is the most relevant choice for someone looking for information on <redacted>
Here is the output in JSON format:
{{
  "type": "array",
  "items": {{
    "type": "object",
    "properties": {{
      "choice": 1,
      "reason": "<redacted>"
    }},
    "required": [
      "choice",
      "reason"
    ],
    "additionalProperties": false
  }}
}}

```

Gets marshaled ([link](https://github.com/jerryjliu/llama_index/blob/v0.8.36/llama_index/output_parsers/utils.py#L12)) to this `str` JSON:

```json
{{
  "type": "array",
  "items": {{
    "type": "object",
    "properties": {{
      "choice": 1,
      "reason": "Useful for getting information on cell lines"
    }},
    "required": [
      "choice",
      "reason"
    ],
    "additionalProperties": false
  }}
}}
```

Then fails `json.loads` due to double curly brace.  We should allow the marshalling to replace `{{` with `{`, and `}}` with `}`

**Comment by kwong718** [comment]
Why'd you guys remove this? Some 'smarter' LLMs actually follow the example we send them.

This format string
```
FORMAT_STR = """The output should be ONLY JSON formatted as a JSON instance.

Here is an example:
[
    {
        choice: 1,
        reason: "<insert reason for choice>"
    },
    ...
]
"""
```

Eventually ends up having double braces because of the function _escape_curly_braces()
