### ISSUE TITLE
[Question]: How to Use ReAct Chat Engine to Query a Collection of PandasQueryEngines

### ISSUE THREAD

**Issue by benhgm** [jerryjliu/llama_index#7892]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

does anyone know if i am able to use a ReAct chat engine to perform data analysis on a collection of pandas dataframes?

what is the best way to compose an application for such a use case? 

As per the documentation, using ReAct and Single Query Transform can be done on VectorStoreIndexes. However, I can't find any documentation on how to create a VectorStoreIndex using pandas dataframes.

**Comment by benjamin-ta** [comment]
I've followed the `PandasQueryEngine` example from the last comment. However, no matter what I write (a natural language query or pandas instruction), I get the following error when using the `query_engine.query()`:

```
Traceback (most recent call last):
  File "/home/jupyter/venv/lib/python3.10/site-packages/llama_index/query_engine/pandas_query_engine.py", line 59, in default_output_processor
    tree = ast.parse(output)
  File "/opt/conda/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    Note: The input query is not in a specific format, it's just a description of what we want to achieve. We need to convert this query into an executable Python code using Pandas.
                                                         ^
SyntaxError: unterminated string literal (detected at line 3) 
```

Any chance we can get a working example of `PandasQueryEngine` anywhere? Everything saw in the documentations fail on the `default_output_processor`
