### ISSUE TITLE
"ModuleNotFoundError: No module named 'llama_cpp'" when using Palm API.

### ISSUE THREAD

**Issue by hsmsci** [jerryjliu/llama_index#7898]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am following the code from: https://gpt-index.readthedocs.io/en/stable/examples/llm/palm.html 
to use Palm api for inference and it is working fine. After that I am trying to extend the code to do 10Q analysis, using this code:

`#10 Q Analysis
import nest_asyncio

nest_asyncio.apply()
from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex
from llama_index.response.pprint_utils import pprint_response
from llama_index.llms import OpenAI

from llama_index.tools import QueryEngineTool, ToolMetadata
from llama_index.query_engine import SubQuestionQueryEngine

service_context = ServiceContext.from_defaults(llm=llm)

march_2022 = SimpleDirectoryReader(
    input_files=["10q1.pdf"]
).load_data()

march_index = VectorStoreIndex.from_documents(march_2022)

`

I am getting this error when initializing the vector store index: 

> ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/llama_index/llms/llama_cpp.py:82, in LlamaCPP.__init__(self, model_url, model_path, temperature, max_new_tokens, context_window, messages_to_prompt, completion_to_prompt, callback_manager, generate_kwargs, model_kwargs, verbose)
     81 try:
---> 82     from llama_cpp import Llama
     83 except ImportError:

ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[11], line 2
      1 llm
----> 2 march_index = VectorStoreIndex.from_documents(march_2022)

Why is it looking for llama_cpp when I am using Palm api. How do I fix this?

**Comment by logan-markewich** [comment]
@hsmsci you did not pass in the service context 

`march_index = VectorStoreIndex.from_documents(march_2022, service_context=service_context)`

Or, you could set it globally 

```
from llama_index import set_global_service_context 

set_global_service_context(service_context)
```

**Comment by hsmsci** [comment]
Thank you @logan-markewich this helps.
