### ISSUE TITLE
[Feature Request]: chat engine to support recursive retriever

### ISSUE THREAD

**Issue by mingqxu7** [jerryjliu/llama_index#7922]
### Feature Description

In the current system architecture, there's a noted incongruity between the inherent capabilities of the recursive retriever and its integration within the chat engine framework. Specifically, while the recursive retriever demonstrates substantial utility for specific use cases, its deployment within the chat engine relies on the underlying index, which isn't inherently recursive. As of now, a workaround requires direct modifications to the chat engine's core codebase to accept the recursive retriever as an argument. This not only disrupts the intended abstraction layers but also potentially compromises modularity and future supportability. A more streamlined integration method, preserving abstraction and ensuring flexibility, would be a significant enhancement to the system's design paradigm.

### Reason

Within the current architectural framework, the primary mechanism in place is the RetrieverQueryEngine. However, I find the contextual handling and output structure of a chat engine more aligned with certain requirements. The chat engine inherently possesses the capability to maintain and understand chat context, a feature critical for nuanced applications. Being relatively unfamiliar with the intricacies of the llama index, it's plausible that my configuration for the RetrieverQueryEngine might not be fully optimized. If there exists a possibility to adapt or modify the RetrieverQueryEngine to emulate the behavior and contextual awareness of a chat engine, it would merit serious consideration for integration.

On a related note, I've successfully restructured my langchain RAG project in a span of a weekend, demonstrating the agility and adaptability of the framework. I'm inclined to leverage the llama index for forthcoming RAG projects, emphasizing the importance of ensuring the chat engine's compatibility and versatility in these contexts.

### Value of Feature

In the context of RAG scenarios, the implementation of blind-folded fixed set chunking presents inherent challenges that can hinder optimal results. The Recursive Retriever emerges as a refined solution, meticulously addressing these challenges. By integrating it within the chat engine, we stand to enhance the quality and precision of responses. This will not only sidestep the pitfalls associated with conventional chunking techniques but also elevate the chat engine's capability to deliver more nuanced, accurate, and context-aware results. However, my previous PM experience tells me that I am better served not to push for a specific implementation but to be open to alternatives.

**Comment by logan-markewich** [comment]
Any chat engine/agent can support the recursive retriever -- or any retriever / query engine. You just have to constructor the chat engine/agent from the base constructor rather than using `as_chat_engine()`

**Comment by mingqxu7** [comment]
cool! thanks for the quick response!
