### ISSUE TITLE
[Question]: LlamaCPP system prompt

### ISSUE THREAD

**Issue by mzoonAlwalmani** [jerryjliu/llama_index#7924]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using LlamaCPP and I want to pass a system prompt. i believe I should use messages_to_prompt, could you please share with me how to correctly pass a prompt. i am looking for something like HuggingFaceLLM where I can pass the system prompt easily.  

`from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    model_url=model_url,
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path= model_path,
    temperature=0.1,
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 1},
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)`

**Comment by mzoonAlwalmani** [comment]
@dosu-bot thank you for your answer, i tried the suggested way, however i am getting the following error when running the below. it seems  LlamaCPP is not accepting string, 

```
from llama_index.llms.base import ChatMessage, MessageRole

# Create a system message
system_message = ChatMessage(role=MessageRole.SYSTEM, content="you are an assistant. ")

# Create a user message
user_message = ChatMessage(role=MessageRole.USER, content="")

# Create a sequence of messages
messages = [system_message, user_message]

# Call the function
prompt = messages_to_prompt(messages)

llm = LlamaCPP(
    model_path= model_path,
    temperature=0.1,
    max_new_tokens=256,
    context_window=3900,
    generate_kwargs={},
    model_kwargs={"n_gpu_layers": 1},
    messages_to_prompt= messages_to_prompt(messages),
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)
```


```
ValidationError: 1 validation error for LlamaCPP
messages_to_prompt

[/INST] is not callable (type=type_error.callable; value=<s> [INST] <<SYS>>
```

**Comment by mzoonAlwalmani** [comment]
@dosu-bot this did not solve the issue,  LlamaCPP expect a callable field for messages_to_prompt not a string. i am not sure how to pass a a customized system message to the prompt.

**Comment by logan-markewich** [comment]
@mzoonAlwalmani You just need to make a function that converts the messages to a prompt. I would do something like this

```
from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt

def custom_messages_to_prompt(messages):
  return messages_to_prompt(messages, system_prompt="Talk like a pirate in every response.")

def custom_completion_to_prompt(completion):
  return completion_to_prompt(completion, system_prompt="Talk like a pirate in every response.")

llm = LlamaCPP(
  ..., 
  messages_to_prompt=custom_messages_to_prompt, 
  completion_to_prompt=custom_completion_to_prompt
)
```

**Comment by logan-markewich** [comment]
Source: https://github.com/jerryjliu/llama_index/blob/main/llama_index/llms/llama_utils.py

**Comment by mzoonAlwalmani** [comment]
@logan-markewich  it is working without throwing an error, however i don't think the system message got passed to the propmt because whatever change i made nothing is changed. i am using query_engine and below is my code

```

def custom_messages_to_prompt():
    # Create a system message
#     system_message = ChatMessage(role=MessageRole.SYSTEM, content="you are an assistant. ")

    # Create a user message
    user_message = ChatMessage(role=MessageRole.USER, content="{query_str}")

    # Create a sequence of messages
    messages = [user_message]
    return messages_to_prompt(messages, system_prompt="Talk like a pirate in every response.") 

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    #     model_url=model_url,
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path= model_path,
    temperature=0.1,
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 1},
    # transform inputs into Llama2 format
    messages_to_prompt= custom_messages_to_prompt,
#     completion_to_prompt=completion_to_prompt,
    verbose=True,
)
# use Huggingface embeddings
from llama_index.embeddings import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embed_model,
)

# load documents
documents = SimpleDirectoryReader("Data/").load_data()

# create vector store index
index = VectorStoreIndex.from_documents(documents, service_context=service_context)

# set up query engine
query_engine = index.as_query_engine()

response = query_engine.query("how to transfer confidintial data")
print(response)
```

**Comment by logan-markewich** [comment]
@mzoonAlwalmani query engines don't use chat, they use the completion_to_prompt, that's why I put examples for both above 👍

**Comment by mzoonAlwalmani** [comment]
@logan-markewich thank you for your help,  i end up defining the function as you can see below, now i have another issue which is when i try to query using the query engine it seems that there is no context or user query.

```
def custom_completion_to_prompt(completion:Optional[str] = None):
    completion = "the observation is {query_str}"
    return completion_to_prompt(completion, system_prompt="you are an assistant. you will be provided with observation and context, the observation is an audit observation which is normally a violation or failure to adhere to the standard or general instructions , the context is the relevent information found in the standard and General instructins documents, your goal is to generat a referense from the context in the following format: first start by mentioning the document name and number then state the related referance information that shows way is the observation is againest the standard. make the response as short as possible and to the point with no additional information out side the context")

```
```

response = query_engine.query("the system allows all the users with no restrictions, there is no access contro")
print(response)
```
here is the response
> 
Sure, I'd be happy to help! Can you please provide the document name and number, as well as the related observation from the audit?
