### ISSUE TITLE
[Bug]: start_char_idx and end_char_idx removed

### ISSUE THREAD

**Issue by tkreuder** [jerryjliu/llama_index#7925]
### Bug Description

This commit https://github.com/jerryjliu/llama_index/pull/7236/commits/f887df2ee95ec693b28e6d575afe2f06bb45cd55 removed start_char_idx and end_char_idx from node_utils.py

### Version

0.8.37

### Steps to Reproduce

Use SimpleParser and you will always get start_char_idx and end_char_idx of None.

**Comment by logan-markewich** [comment]
@tkreuder this is not a bug -- it was an intended change.

Those two attributes were making text splitters and node parsers both a) hard to maintain and b) hard to expand. Plus, the indexes were often incorrect anyways.

In our own SECInsights app, we used fuzzy matching to find the text location, and it worked quite well. I suggest doing something similar

**Comment by tkreuder** [comment]
@logan-markewich Thanks for the answer and all the effort you guys put into the project!  much appreciated :) 
 
Thus it was a breaking change, which was not expected and announced, but still these two fields remain and are now always None.
For me it meant 20k documents and its resulting embeddings are now stored useless within pinecone, so it would be nice, if breaking changes are announced. I was wondering why my newest batch of documents, did not contain these indices anymore and had to find out manually, which commit was causing this.

**Comment by tkreuder** [comment]
> @tkreuder this is not a bug -- it was an intended change.
> 
> Those two attributes were making text splitters and node parsers both a) hard to maintain and b) hard to expand. Plus, the indexes were often incorrect anyways.
> 
> In our own SECInsights app, we used fuzzy matching to find the text location, and it worked quite well. I suggest doing something similar

You refer to https://www.fusejs.io/ ?
