### ISSUE TITLE
Reading PDF file from cloud storage (GCS)

### ISSUE THREAD

**Issue by ctle-vn** [jerryjliu/llama_index#793]
Hi there,

Came across `SimpleDirectoryReader` which lets you read in a file, given the file path. 

I have files that I store on cloud (Google Cloud Storage) that I fetch from. Is there a way to use `SimpleDirectoryReader` without the path that's required, but instead provide the file itself?

Currently I workaround it with the following by parsing myself and providing the documents to `GPTSimpleVectorIndex`.

**Comment by jerryjliu** [comment]
@ctle-vn do you mean providing the file name instead of folder name? yeah you can do that by specifying input_files kwarg e.g. 

```
reader = SimpleDirectoryReader(input_files=["path/to/downloaded/file.ext"]).load_data()
```

**Comment by ctle-vn** [comment]
Hey @jerryjliu thanks for the reply.

More like having the actual file in memory, this is the function header:

`def generate_embeddings_with_pdf_filer(file: UploadFile) -> None:`

am i able to pass the file directly in?

**Comment by jerryjliu** [comment]
> Hey @jerryjliu thanks for the reply.
> 
> More like having the actual file in memory, this is the function header:
> 
> `def generate_embeddings_with_pdf_filer(file: UploadFile) -> None:`
> 
> am i able to pass the file directly in?

Ah got it. At the moment no :/  we do have an s3 reader on llamahub, but that also just downloads files to a temp directory and uses SimpleDirectoryReader too

**Comment by ctle-vn** [comment]
Got it got it, thanks for the reply!
