### ISSUE TITLE
I want him to answer me in the same language I asked him

### ISSUE THREAD

**Issue by Wangkaixinlove** [jerryjliu/llama_index#799]
Why was the issue closed? I also met the same problem, my data is pure English, I want to ask questions in different languages, but only English reply is returned, but I directly call openai will not have this problem, can you answer the reason?

1.these are my query code
`# query_index.py   从index文件里获得相关资料并向GPT提问
import os
import sys
os.environ["OPENAI_API_KEY"] = ''
from llama_index import GPTSimpleVectorIndex
index = GPTSimpleVectorIndex.load_from_disk(os.path.dirname(__file__) + '/index.json')
print(index.query('如何获取鲜花',mode="embedding"))`

2.these are my data
{"question": "How do I get flowers?", "answer":"1. Login to check in: Each user can get 3 flowers per day just by checking in. 2. Invite friends: Each time you successfully invite a friend to WeSing, you will get 1 flower, and each day you can get up to 3 flowers.  3. Singing bonus: Each time you post a song with an average score over 60, you will get 5 flowers, and each day you can get up to 5 flowers. If your outstanding song is recommended by the editor, you will get 5 flowers, and each day you can get up to 15 flowers."}

3.this is response
Answer: Flowers can be obtained in several ways: 1. Login to check in: Each user can get 3 flowers per day just by checking in. 2. Invite friends: Each time you successfully invite a friend to WeSing, you will get 1 flower, and each day you can get up to 3 flowers. 3. Singing bonus: Each time you post a song with an average score over 60, you will get 5 flowers, and each day you can get up to 5 flowers. If your outstanding song is recommended by the editor, you will get 5 flowers, and each day you can get up to 15 flowers. 4. Complete tasks: After you accomplished a mission in the Mission Center, you can get corresponding number of flowers as a reward. 5. Recharge your account: To obtain K coins, recharge your account.

but I want it answer me in the same language I asked him, please help me, thanks.

**Comment by Smyja** [comment]
> Why was the issue closed? I also met the same problem, my data is pure English, I want to ask questions in different languages, but only English reply is returned, but I directly call openai will not have this problem, can you answer the reason?
> 
> 1.these are my query code `# query_index.py 从index文件里获得相关资料并向GPT提问 import os import sys os.environ["OPENAI_API_KEY"] = '' from llama_index import GPTSimpleVectorIndex index = GPTSimpleVectorIndex.load_from_disk(os.path.dirname(__file__) + '/index.json') print(index.query('如何获取鲜花',mode="embedding"))`
> 
> 2.these are my data {"question": "How do I get flowers?", "answer":"1. Login to check in: Each user can get 3 flowers per day just by checking in. 2. Invite friends: Each time you successfully invite a friend to WeSing, you will get 1 flower, and each day you can get up to 3 flowers. 3. Singing bonus: Each time you post a song with an average score over 60, you will get 5 flowers, and each day you can get up to 5 flowers. If your outstanding song is recommended by the editor, you will get 5 flowers, and each day you can get up to 15 flowers."}
> 
> 3.this is response Answer: Flowers can be obtained in several ways: 1. Login to check in: Each user can get 3 flowers per day just by checking in. 2. Invite friends: Each time you successfully invite a friend to WeSing, you will get 1 flower, and each day you can get up to 3 flowers. 3. Singing bonus: Each time you post a song with an average score over 60, you will get 5 flowers, and each day you can get up to 5 flowers. If your outstanding song is recommended by the editor, you will get 5 flowers, and each day you can get up to 15 flowers. 4. Complete tasks: After you accomplished a mission in the Mission Center, you can get corresponding number of flowers as a reward. 5. Recharge your account: To obtain K coins, recharge your account.
> 
> but I want it answer me in the same language I asked him, please help me, thanks.

you should specify in your prompt that it should respond in chinese. Also you can check out [guardrails](https://shreyar.github.io/guardrails/examples/translation_with_quality_check/) and an example of how to use guardrails with gptindex
