### ISSUE TITLE
Similarity_top_k does not work with GPTChromaIndex

### ISSUE THREAD

**Issue by timonmat** [jerryjliu/llama_index#802]
I'm creating a client with persisntant 'duckdb+parquet' config. indexing to GPTChromaIndex. Saving the index to disk, and persisting the chromadb.

then loading from disk later.

Similarity_top_k does not impact query results in any way. I always get one node results.
https://github.com/timonmat/ChatObsidian/blob/main/utils/chroma.py#L66

When used with GPTSimpleIndex, exactly the same way, similariy_top_k works as expected.

**Comment by jerryjliu** [comment]
@timonmat weird, going to take a look. do you mean it's only returning one node in `response.source_nodes`?
