### ISSUE TITLE
Can I use llama-index based on a locally deployed model?

### ISSUE THREAD

**Issue by Meaninles** [jerryjliu/llama_index#805]
I wish to use llama-index with a locally deployed chatglm model, how should I do it? Or what changes should I make?

**Comment by jerryjliu** [comment]
we use langchain as the underlying LLM abstraction under the hood, i'd follow [langchain docs](https://langchain.readthedocs.io/en/latest/modules/llms/examples/custom_llm.html) for how to add a custom llm

docs for how to integrate llm into llamaindex: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html

**Comment by huangjiaheng** [comment]
> we use langchain as the underlying LLM abstraction under the hood, i'd follow [langchain docs](https://langchain.readthedocs.io/en/latest/modules/llms/examples/custom_llm.html) for how to add a custom llm
> 
> docs for how to integrate llm into llamaindex: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html

404
