### ISSUE TITLE
The answer degrades comparing asking chatGPT directly. 

### ISSUE THREAD

**Issue by jma7889** [jerryjliu/llama_index#809]
When indexing a relatively small document (60kB in file size), the indexing constantly filter out the correct portion of the document and thus impossible for ChatGPT find the correct answer. I am not sure how to improve it using llama index. For other folks using the lib, do you find it useful or waste of time?

**Comment by verrannt** [comment]
Have you tried using different indexes? I observed the same issue using the `GPTSimpleVectorIndex`, while the `GPTTreeIndex` worked fine and mostly picked out the correct info.

**Comment by Disiok** [comment]
@jma7889 could you give an example of the type of questions you are asking? What kind of index are you using?

**Comment by jma7889** [comment]
> GPTTreeIndex

I was using GPTSimpleVectorIndex, after switching to GPTTreeIndex, it is much better now. Thanks @verrannt
It seems have some response merging issues. It also uses much more tokens (X100 times more).
