### ISSUE TITLE
issue with storing extra_info in Chroma

### ISSUE THREAD

**Issue by eugenepyvovarov** [jerryjliu/llama_index#811]
It seems like node.extra_info not stored in Chromadb metadata, I think I fixed it locally by changing the code in file  `/vector_stores/chroma.py` line 66

```
metadata_to_add = result.node.extra_info
metadata_to_add['document_id'] = result.doc_id
metadatas.append(metadata_to_add)
```

**Comment by Disiok** [comment]
Hey @eugenepyvovarov, would be amazing if you can create a PR with your change. I can help review and land!
