### ISSUE TITLE
Where is the embedded cache?

### ISSUE THREAD

**Issue by Luffffffy** [jerryjliu/llama_index#816]
```
How are Embeddings Generated?[](https://gpt-index.readthedocs.io/en/latest/how_to/embeddings.html#how-are-embeddings-generated)
Since we offer embedding support during query-time for our list and tree indices, embeddings are lazily generated and then cached (if mode="embedding" is specified during index.query(...)), and not during index construction. This design choice prevents the need to generate embeddings for all text chunks during index construction.
```
According to the [document](https://gpt-index.readthedocs.io/en/latest/how_to/embeddings.html#how-are-embeddings-generated) description: `embeddings are lazily generated and then cached `

If my device is Windows, can cache be saved to the C drive/folder?

**Comment by jerryjliu** [comment]
> For list/tree indexes, embeddings are stored in memory after they are calculated. Then when you call `index.save_to_disk("index.json")`, the embeddings are stored in the json file

exactly what @logan-markewich said. going to close this for now

**Comment by Luffffffy** [comment]
> For list/tree indexes, embeddings are stored in memory after they are calculated. Then when you call `index.save_to_disk("index.json")`, the embeddings are stored in the json file

Okay, but it‘s not saved in the json file

paste my code and json file:

![image](https://user-images.githubusercontent.com/49063302/226795866-4b4b478d-15f4-4b96-8a44-d7b06fedbacb.png)

![image](https://user-images.githubusercontent.com/49063302/226795832-5c732afd-2b69-419a-828e-0d2ed5c2fab6.png)

**Comment by logan-markewich** [comment]
@Luffffffy for a list index, the embeddings only get computed on the fly if you use mode="embedding" in the query

Instead, the default operation for a list index is to check every node.

You can also try the GPTSimpleVectorIndex, which will generate the embeddings at index construction, and will only check the closest matching top_k nodes

**Comment by Luffffffy** [comment]
@logan-markewich Oh I see I see. 

So, if I use a `GPTListIndex` or `GPTTreeIndex`  to generate  a summray(`in GPTListIndex response_mode='tree_summarize'` or `in GPTTreeIndex mode="summarize"`)

I will request the API to build the embeddings every time I call `index.query`, right?

Because now I want to use `llama_index` to generate summaries based on external data(my .txt files)

**Comment by Luffffffy** [comment]
Okay, I understand roughly.
Thank you very much for your patient response and answer, although the issue has been closed, thank you!!!
