### ISSUE TITLE
ImportError: cannot import name 'HyDEQueryTransform' from 'llama_index.indices.query.query_transform' and  "ModuleNotFoundError: No module named 'a'" for from a.langchain_helpers.text_splitter import TokenTextSplitter

### ISSUE THREAD

**Issue by gajavelli** [jerryjliu/llama_index#826]
![image](https://user-images.githubusercontent.com/5496552/226725385-00f0b11c-71e3-4a6a-86f9-fb23dd8ea611.png)

I got the latest llama_index version 0.4.34 and appears to be broken in two places  as shown in the screenshot.

my previous install 3 weeks right after rename of 
GPT Index -> LlamaIndex was working fine. 

Any pointers on how to resolve ?

**Comment by jerryjliu** [comment]
i'm not sure...did you accidentally edit the library files by any chance? you could try uninstalling llama-index and reinstalling

**Comment by gajavelli** [comment]
Yes I edited, since it was missing the agents folder under
langchain_helpers in my previous install.

After that I uninstalled and reinstalled it several times but still have
the same problem.
Seems to be cached somewhere
Running out of time as I wanted demonstrate a use case and your llama-index
framework has been very helpful to rapidly prototype.

**Comment by gajavelli** [comment]
I edited in two places
one  in base.py under query_transform

Other  place under langchain_helpers where I added agents folder

**Comment by gajavelli** [comment]
Yes I'm still getting the same with gpt_index imports.

**Comment by gajavelli** [comment]
the error in importing TokenTextSplitter was caused by accidental typo "a." in my screenshot. (NOT AN ISSUE Please Ignore) . Apologies for inconvenience.
However the HyDEQueryTransform appears to have some sort of circular reference.

**Comment by blackstorm** [comment]
Same error on colab

**Comment by gajavelli** [comment]
Thanks @blackstorm  that worked
