### ISSUE TITLE
ValueError: int_id not found in nodes_dict

### ISSUE THREAD

**Issue by iraadit** [jerryjliu/llama_index#827]
Why modifying the new _Chatbot_SEC.ipynb_ file and executing 
`agent_chain.run(input="My question?")`
I get the following error:
```
File [.../llama_index/llama_index/indices/query/base.py:296], in BaseGPTIndexQuery.get_nodes_and_similarities_for_response(self, query_bundle)
    289 """Get list of tuples of node and similarity for response.
    290 
    291 First part of the tuple is the node.
    292 Second part of tuple is the distance from query to the node.
    293 If not applicable, it's None.
    294 """
    295 similarity_tracker = SimilarityTracker()
--> 296 nodes = self._get_nodes_for_response(
...
--> 221         raise ValueError("int_id not found in nodes_dict")
    222     nodes.append(self.nodes_dict[int_id])
    223 return nodes

ValueError: int_id not found in nodes_dict
```

The only change I see that could explain it would be that I replaced the years (that were of the type int) by countries (of the type string)

Do you have any idea @jerryjliu 

Thank you for your amazing work !

**Comment by jerryjliu** [comment]
@iraadit what version of llama-index are you on?

**Comment by iraadit** [comment]
0.4.34, the last one
Installed through pip a couple of hours ago
Before that, I tried with source install (-e), with the same result

**Comment by iraadit** [comment]
Sorry, it works!
I restarted my Jupiter Notebook. I did it already before, but it seems it stayed in a weird state.

I'll close the issue.

Thank you
