### ISSUE TITLE
Is Llama Index thread safe? Particularly the Index stores

### ISSUE THREAD

**Issue by kokhoor** [jerryjliu/llama_index#830]
Hi,

I am writing a web application and since requests comes in different thread, would like to ask, is it safe to instantiate the index once, and reuse it, or do I have to explicitly re-instantiate the index store (I am using GPTSimpleVectorIndex) everytime I need to use index.query?

Thanks.

**Comment by Disiok** [comment]
Not super sure, but since `query` is read-only, I think it would be thread-safe. 

Please join the discord community (https://discord.com/invite/dGcwcsnxhU) if you have more concerns!

**Comment by MarcSkovMadsen** [comment]
Did you learn something here @kokhoor . I'm developing a web app. And as soon as I start using threads my app starts working as expected. Simply not responding any more.
