### ISSUE TITLE
stream is only supported for OpenAI LLMs

### ISSUE THREAD

**Issue by mingxin-yang** [jerryjliu/llama_index#831]
```
from langchain.chat_models import ChatOpenAI

llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo"))
index = GPTSimpleVectorIndex.load_from_disk(file_path, llm_predictor=llm_predictor)
response = index.query(query_str, response_mode="compact", streaming=True)
```

**chatopenAI can't use stream, how to supported it?**

**Comment by logan-markewich** [comment]
I think OpenAI needs to enable streaming in their API for chatGPT, but they haven't yet

**Comment by mingxin-yang** [comment]
> I think OpenAI needs to enable streaming in their API for chatGPT, but they haven't yet

@logan-markewich OpenAI's API is support with stream, I used it in node

**Comment by mingxin-yang** [comment]
nobody face this problem？

**Comment by mingxin-yang** [comment]
@Disiok @jerryjliu

**Comment by neove** [comment]
same problem +1

**Comment by mingxin-yang** [comment]
https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb
https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo-streaming.ipynb
Hope to use the both example. @jerryjliu 🧐

**Comment by xumo97** [comment]
Same questio

**Comment by hlwhl** [comment]
@mingxin-yang  @xumo97 Take this repo as reference https://github.com/hlwhl/knowledge_base_server. It's achieved stream response based on callback manager.

**Comment by Disiok** [comment]
Closing this ticket to tracker under https://github.com/jerryjliu/llama_index/issues/1007
