### ISSUE TITLE
I'm trying to add documents using llama index, but this error arises after I have updated the llama index version 0.4.35

### ISSUE THREAD

**Issue by zainabalthafeeri1** [jerryjliu/llama_index#836]
File "/venv/lib/python3.8/site-packages/llama_index/indices/vector_store/base.py", line 186, in _add_document_to_index
    new_ids = self._vector_store.add(embedding_results)
              │    │             │   └ [NodeEmbeddingResult(id='ade16889-c5c4-4c80-a230-14110ed4f494', node=Node(text='Email Policy\n\nEmail Policy\n\n\n\n\n\n Prop...
              │    │             └ <function ChromaVectorStore.add at 0x7fab1ddaaa60>
              │    └ <llama_index.vector_stores.chroma.ChromaVectorStore object at 0x7fab06adcac0>
              └ <llama_index.indices.vector_store.vector_indices.GPTChromaIndex object at 0x7fab06adca90>
  File "/venv/lib/python3.8/site-packages/llama_index/vector_stores/chroma.py", line 68, in add
    metadatas.append(extra_info | {"document_id": result.doc_id})
    │         │      │                            │      └ '14815e2f-f819-43f7-a3f1-4955e0d1a061'
    │         │      │                            └ NodeEmbeddingResult(id='ade16889-c5c4-4c80-a230-14110ed4f494', node=Node(text='Email Policy\n\nEmail Policy\n\n\n\n\n\n Propr...
    │         │      └ {}
    │         └ <method 'append' of 'list' objects>
    └ []

TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by jerryjliu** [comment]
thanks for raising @zainabalthafeeri1, will take a look soon
