### ISSUE TITLE
Querying Multiple Faiss Indices Without Summaries

### ISSUE THREAD

**Issue by mnkasikci** [jerryjliu/llama_index#837]
I am trying to create a composable graph to query multiple Faiss Indices together. 
What I want is
1- Query multiple faiss indices as if they are a single faiss index. Namely, I don't want to "actually" query the summaries (set_text() or get_text()) at all. Even if the summary is empty, or has nothing to do with the content, I want its content to be taken into account when querying.
2- Be able to load the faiss indices from the disk for the purpose above. Currently I can't do it because `QueryConfig` requires me to provide a `faiss_index` as a part of query_kwargs, which I can't provide from a faiss Index, which is  loaded from the disk by using `GPTFaissIndex.load_from_disk` I've taken a look into #362 but the syntax there (`faiss_2._faiss_index`) seems to be written for illustration. 
3- I only need to retrieve top_k results from all the indices combined. (not k from each index, so top n chunks could be from index1 and top (k-n) chunks could be from index2, totaling k). I don't need the response. 

Here is my code. What I can't achieve there is

1- Query all the indices without taking their summary into account. Currently if I change the set_text part for indices to something irrelevant (like "index1") it doesn't take the content into account. 
2- I can't load the faiss indices from the disk, since in that case I can't reach the faiss_index itself to feed it to QueryConfig. I've tried vector_store and several other attributes/properties/methods but none of them worked.
3- If I keep the first QueryConfig (list) , to my understanding, it only finds the most relevant document according to their summaries and queries that one. If I omit it, it uses 121 tokens to query the list, in which I guess it somehow creates an actual new index, which is time and token consuming. I can't achieve what I want in article 3 above. 

My version is 0.4.35, the last version as of now. 

My code: 

```
from llama_index import Document, GPTListIndex, GPTFaissIndex, QueryConfig, IndexStructType, QueryMode
from llama_index.composability import ComposableGraph


import faiss
d = 1536
faiss_index1 = faiss.IndexFlatL2(d)
faiss_index2 = faiss.IndexFlatL2(d)

text = "Joe lives in France. He is a fashion designer. She loves to travel."
document = Document(text, doc_id="Joe")
index1 = GPTFaissIndex(documents=[document], faiss_index=faiss_index1)
index1.set_text("Joe")

text2 = "Alice is a software developer. She makes a living out of it. Joe loves Alice. He lives in the US."
document2 = Document(text2, doc_id="Alice")
index2 = GPTFaissIndex(documents=[document2], faiss_index=faiss_index2)
index2.set_text("Alice and Joe")

listIndex = GPTListIndex(documents=[index1, index2])

graph = ComposableGraph.build_from_index(listIndex)
query_configs = [
    # I add and remove this QueryConfig
    QueryConfig(
        index_struct_type=IndexStructType.LIST,
        query_mode=QueryMode.EMBEDDING,
        query_kwargs={"response_mode": "no_text"},
        index_struct_id=listIndex.get_doc_id(),
    ),
    # The below are the same as before
    QueryConfig(
        index_struct_type=IndexStructType.DICT,
        query_mode=QueryMode.EMBEDDING,
        query_kwargs={'faiss_index': faiss_index1,
                      "response_mode": "no_text"},
        index_struct_id=index1.get_doc_id(),
    ),
    QueryConfig(
        index_struct_type=IndexStructType.DICT,
        query_mode=QueryMode.EMBEDDING,
        query_kwargs={'faiss_index': faiss_index2,
                      "response_mode": "no_text"},
        index_struct_id=index2.get_doc_id(),
    ),
]
question = "Tell me about Joe"

response = graph.query(query_str=question,
                       query_configs=query_configs,
                       )
for source_node in response.source_nodes:
    print(
        f"source_node_text = {source_node.source_text[:40]} | difference = {source_node.similarity},\
          doc_id = {source_node.doc_id}")
```
@jerryjliu

**Comment by thiswillbeyourgithub** [comment]
Related to #737 

I'm in the same situation, I already computed several FaissIndex and want to route my query to all of them at the same time without having to create a summary!

**Comment by thiswillbeyourgithub** [comment]
Surprisingly, the exact feature we seem to be looking for is mentionned here in langchain : https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/faiss.html

**Comment by thiswillbeyourgithub** [comment]
I ended up moving away from llama index and towards langchain. They recently setup a cache for embeddings that might solve this but otherwise my solution was to create indices of length 1 then pickle it and combine them on the go.

Here's the code : https://github.com/thiswillbeyourgithub/DocToolsLLM/blob/0726eb2730b90d8c51f9469ddd782e3bc1fd5562/utils/file_loader.py#L656

**Comment by thiswillbeyourgithub** [comment]
@dosu-beta please reopen the issue. The other users manifested themselves and although I migrated i still think it's worth implementing.

**Comment by logan-markewich** [comment]
Here's the solution for querying multiple indexes

https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#simple-fusion-retriever
