### ISSUE TITLE
The original answer is already appropriate and does not need to be refined.

### ISSUE THREAD

**Issue by Thieund** [jerryjliu/llama_index#838]
Could anyone tell me how to get the original response when the response is "The original answer is already appropriate and does not need to be refined" ?Thanks.

**Comment by Disiok** [comment]
Which LLM model are you using?

I think sometimes ChatGPT (i.e. `turbo`) could be a bit more "opinionated" and give responses like this. Trying a different model might help. Alternatively, use the `tree_summarize` response mode instead of the default.
