### ISSUE TITLE
Support milvus vector store

### ISSUE THREAD

**Issue by elonzh** [jerryjliu/llama_index#850]
> Milvus is an open-source vector database built to power embedding similarity search and AI applications. Milvus makes unstructured data search more accessible, and provides a consistent user experience regardless of the deployment environment.

> Milvus was released under the [open-source Apache License 2.0](https://github.com/milvus-io/milvus/blob/master/LICENSE) in October 2019. It is currently a graduate project under [LF AI & Data Foundation](https://lfaidata.foundation/).

See https://milvus.io/ for more details.

**Comment by Disiok** [comment]
Should be coming in the near future! Stay tuned.

**Comment by logan-markewich** [comment]
We support milvus now!

https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/MilvusIndexDemo.html
