### ISSUE TITLE
Asks for OPENAI_KEY when it's not needed

### ISSUE THREAD

**Issue by mjp0** [jerryjliu/llama_index#852]
I'm playing around with Qdrant as a vector store index using sentence-transformer embeddings from HuggingFace. 

However, when I try to create an index, I get an error message `Did not find openai_api_key, please add an environment variable OPENAI_API_KEY which contains it, or pass  openai_api_key as a named parameter.`. I'm not using any OpenAI API, so why is llama-index asking for the key?

```python
model_name = "sentence-transformers/all-mpnet-base-v2"
embed_model_lang = LangchainEmbedding(HuggingFaceEmbeddings(model_name=model_name))   
data = "hello world"
documents = embed_model_lang.get_text_embedding(data) 
index = GPTQdrantIndex(documents, collection_name="test", client=client, embed_model=embed_model_lang)
```

**Comment by Disiok** [comment]
@mjp0 if you have more questions beyond @logan-markewich's super helpful response, please join the discord community (https://discord.gg/dGcwcsnxhU) and continue the discussion there!

**Comment by AngelTs** [comment]
> I'm playing around with Qdrant as a vector store index using sentence-transformer embeddings from HuggingFace.
> 
> However, when I try to create an index, I get an error message `Did not find openai_api_key, please add an environment variable OPENAI_API_KEY which contains it, or pass openai_api_key as a named parameter.`. I'm not using any OpenAI API, so why is llama-index asking for the key?
> 
> ```python
> model_name = "sentence-transformers/all-mpnet-base-v2"
> embed_model_lang = LangchainEmbedding(HuggingFaceEmbeddings(model_name=model_name))   
> data = "hello world"
> documents = embed_model_lang.get_text_embedding(data) 
> index = GPTQdrantIndex(documents, collection_name="test", client=client, embed_model=embed_model_lang)
> ```

Can you share a example how to create embeddings with your documents WITHOUT openai api key?
Reading this repository have feeling that they work ONLY for openai ...

**Comment by AngelTs** [comment]
> I'm playing around with Qdrant as a vector store index using sentence-transformer embeddings from HuggingFace.
> 
> However, when I try to create an index, I get an error message `Did not find openai_api_key, please add an environment variable OPENAI_API_KEY which contains it, or pass openai_api_key as a named parameter.`. I'm not using any OpenAI API, so why is llama-index asking for the key?
> 
> ```python
> model_name = "sentence-transformers/all-mpnet-base-v2"
> embed_model_lang = LangchainEmbedding(HuggingFaceEmbeddings(model_name=model_name))   
> data = "hello world"
> documents = embed_model_lang.get_text_embedding(data) 
> index = GPTQdrantIndex(documents, collection_name="test", client=client, embed_model=embed_model_lang)
> ```

Can you share a example how to create embeddings with your documents WITHOUT openai api key?
Reading this repository have feeling that they work ONLY for openai ...
PS: Spuriously, the link about how to make custom LLM in the answer not works

**Comment by logan-markewich** [comment]
There are two models, the embed model and the llm

You'll need to set both in the service context, and pass your service context into the index


https://colab.research.google.com/drive/16QMQePkONNlDpgiltOi7oRQgmB8dU5fl?usp=sharing

**Comment by AngelTs** [comment]
> There are two models, the embed model and the llm
> 
> You'll need to set both in the service context, and pass your service context into the index
> 
> https://colab.research.google.com/drive/16QMQePkONNlDpgiltOi7oRQgmB8dU5fl?usp=sharing

Thank you for the answer, but the simple example is missing.
Am i wrong if conclude that embedding is private technology of OpenAI and there is no way to use on other LLMs?
I can't find a simple example of python script using embeddings WITHOUT to use OpenAI API.
The only one alternative is Extensible retrieval augmented system of OpenChatKit!, BUT it is in experimental stage

**Comment by logan-markewich** [comment]
```python
hf_predictor = HuggingFaceLLMPredictor(
    max_input_size=2048, 
    max_new_tokens=256,
    temperature=0.25,
    do_sample=False,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="Writer/camel-5b-hf",
    model_name="Writer/camel-5b-hf",
    device_map="auto",
    tokenizer_kwargs={"max_length": 2048},
    model_kwargs={"torch_dtype": torch.bfloat16}
)

embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2"))

service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)
```

This runs everything locally, on your machine, no openai

**Comment by AngelTs** [comment]
> ```python
> hf_predictor = HuggingFaceLLMPredictor(
>     max_input_size=2048, 
>     max_new_tokens=256,
>     temperature=0.25,
>     do_sample=False,
>     query_wrapper_prompt=query_wrapper_prompt,
>     tokenizer_name="Writer/camel-5b-hf",
>     model_name="Writer/camel-5b-hf",
>     device_map="auto",
>     tokenizer_kwargs={"max_length": 2048},
>     model_kwargs={"torch_dtype": torch.bfloat16}
> )
> 
> embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2"))
> 
> service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)
> ```
> 
> This runs everything locally, on your machine, no openai

I put in text file your code and start "python yourcode.py" and receive a bunch of errors.
Can you be so kind to provide a simple example of local text python file, not colab or any remote service?
Here is my code:

import torch
from llama_index.llm_predictor import HuggingFaceLLMPredictor
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.llms import GPT4All
from llama_index.node_parser.simple import SimpleNodeParser
from llama_index.langchain_helpers.text_splitter import TokenTextSplitter
from llama_index import (
    GPTVectorStoreIndex, 
    LangchainEmbedding, 
    LLMPredictor, 
    ServiceContext, 
    StorageContext, 
    download_loader,
    PromptHelper
)
from llama_index.prompts.prompts import SimpleInputPrompt

# This will wrap the default prompts that are internal to llama-index
# taken from https://huggingface.co/Writer/camel-5b-hf
query_wrapper_prompt = SimpleInputPrompt(
    "Below is an instruction that describes a task. "
    "Write a response that appropriately completes the request.\n\n"
    "### Instruction:\n{query_str}\n\n### Response:"
)

# NOTE: the first run of this will download/cache the weights, ~20GB
hf_predictor = HuggingFaceLLMPredictor(
    max_input_size=2048, 
    max_new_tokens=256,
    temperature=0.25,
    do_sample=False,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="models/ggml-gpt4all-j-v1.3-groovy.bin",
    model_name="models/ggml-gpt4all-j-v1.3-groovy.bin",
    device_map="auto",
    tokenizer_kwargs={"max_length": 2048},
    model_kwargs={"torch_dtype": torch.bfloat16}
)

embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"))

service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="source_documents")

query_engine = index.as_query_engine(streaming=True, similarity_top_k=3, service_context=service_context)
response_stream = query_engine.query("What are the main climate risks to our Oceans?")
response_stream.print_response_stream()

**Comment by AngelTs** [comment]
> ```python
> hf_predictor = HuggingFaceLLMPredictor(
>     max_input_size=2048, 
>     max_new_tokens=256,
>     temperature=0.25,
>     do_sample=False,
>     query_wrapper_prompt=query_wrapper_prompt,
>     tokenizer_name="Writer/camel-5b-hf",
>     model_name="Writer/camel-5b-hf",
>     device_map="auto",
>     tokenizer_kwargs={"max_length": 2048},
>     model_kwargs={"torch_dtype": torch.bfloat16}
> )
> 
> embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2"))
> 
> service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)
> ```
> 
> This runs everything locally, on your machine, no openai

I put in text file your code and start "python yourcode.py" and receive a bunch of errors.
Can you be so kind to provide a simple example of local text python file, not colab or any remote service?
Here is my code:

import torch
from llama_index.llm_predictor import HuggingFaceLLMPredictor
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.llms import GPT4All
from llama_index.node_parser.simple import SimpleNodeParser
from llama_index.langchain_helpers.text_splitter import TokenTextSplitter
from llama_index import (
GPTVectorStoreIndex,
LangchainEmbedding,
LLMPredictor,
ServiceContext,
StorageContext,
download_loader,
PromptHelper
)
from llama_index.prompts.prompts import SimpleInputPrompt

query_wrapper_prompt = SimpleInputPrompt(
"Below is an instruction that describes a task. "
"Write a response that appropriately completes the request.\n\n"
"### Instruction:\n{query_str}\n\n### Response:"
)

max_input_size=2048,
max_new_tokens=256,
temperature=0.25,
do_sample=False,
query_wrapper_prompt=query_wrapper_prompt,
tokenizer_name="models/ggml-gpt4all-j-v1.3-groovy.bin",
model_name="models/ggml-gpt4all-j-v1.3-groovy.bin",
device_map="auto",
tokenizer_kwargs={"max_length": 2048},
model_kwargs={"torch_dtype": torch.bfloat16}
)

embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"))

service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="source_documents")

query_engine = index.as_query_engine(streaming=True, similarity_top_k=3, service_context=service_context)
response_stream = query_engine.query("What are the main climate risks to our Oceans?")
response_stream.print_response_stream()

**Comment by AngelTs** [comment]
Here is my refined, but still NOT working code with error "ImportError: cannot import name 'BaseOutputParser' from 'langchain.schema'":

import torch
from llama_index.prompts.prompts import SimpleInputPrompt

query_wrapper_prompt = SimpleInputPrompt(
    "Below is an instruction that describes a task. "
    "Write a response that appropriately completes the request.\n\n"
    "### Instruction:\n{query_str}\n\n### Response:"
)
hf_predictor = HuggingFaceLLMPredictor(
    max_input_size=2048, 
    max_new_tokens=512,
    temperature=0.25,
    do_sample=False,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="./models/ggml-gpt4all-j-v1.3-groovy.bin",
    model_name="./models/ggml-gpt4all-j-v1.3-groovy.bin",
    device_map="auto",
    tokenizer_kwargs={"max_length": 2048},
    # uncomment this if using CUDA to reduce memory usage
    model_kwargs={"torch_dtype": torch.float16}
)
prompt_helper = PromptHelper(max_input_size=2048, num_output=512, max_chunk_overlap=50)
embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"))
service_context = ServiceContext.from_defaults(chunk_size_limit=512, llm_predictor=hf_predictor, embed_model=embed_model)
index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
index.storage_context.persist(persist_dir="source_documents")
query_engine = index.as_query_engine(streaming=True, similarity_top_k=4, service_context=service_context)
response_stream = query_engine.query("What are the main climate risks to our Oceans?")
response_stream.print_response_stream()

**Comment by aniruddhs07** [comment]
can anyone comment if we can run everything in an offline where we have downloaded the models. So no need for a connectkion to huggingface.co

**Comment by AngelTs** [comment]
> The colab notebook I linked uses local huggingface embeddings...

Your colab notebook example requires open_api key which is the opposite of the question ...

**Comment by logan-markewich** [comment]
@AngelTs once again, of course you can use local models without openai

While this thread is pretty old now, here's a detailed example right from our docs, the updated usage for v0.7.9. Much of the LLM setup is specific to stable lm, you'll want to see the model card from huggingface for full setup details

```python
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LangchainEmbedding, ServiceContext

embed_model = LangchainEmbedding(
  HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
)

from llama_index.prompts import Prompt

system_prompt = """<|SYSTEM|># StableLM Tuned (Alpha version)
- StableLM is a helpful and harmless open-source AI language model developed by StabilityAI.
- StableLM is excited to be able to help the user, but will refuse to do anything that could be considered harmful to the user.
- StableLM is more than just an information source, StableLM is also able to write poetry, short stories, and make jokes.
- StableLM will refuse to participate in anything that could harm a human.
"""

# This will wrap the default prompts that are internal to llama-index
query_wrapper_prompt = Prompt("<|USER|>{query_str}<|ASSISTANT|>")

import torch
from llama_index.llms import HuggingFaceLLM
llm = HuggingFaceLLM(
    context_window=4096, 
    max_new_tokens=256,
    generate_kwargs={"temperature": 0.7, "do_sample": False},
    system_prompt=system_prompt,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="StabilityAI/stablelm-tuned-alpha-3b",
    model_name="StabilityAI/stablelm-tuned-alpha-3b",
    device_map="auto",
    stopping_ids=[50278, 50279, 50277, 1, 0],
    tokenizer_kwargs={"max_length": 4096},
    # uncomment this if using CUDA to reduce memory usage
    # model_kwargs={"torch_dtype": torch.float16}
)
service_context = ServiceContext.from_defaults(
    chunk_size=1024, 
    llm=llm,
    embed_mode=embed_model
)

# set global settings
from llama_index import set_global_service_context 
set_global_service_context(service_context)
```

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-huggingface-llm

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#embedding-model-integrations

https://gpt-index.readthedocs.io/en/latest/core_modules/supporting_modules/service_context.html

**Comment by AngelTs** [comment]
> can anyone comment if we can run everything in an offline where we have downloaded the models. So no need for a connection to huggingface.co

I just can say that for some reason guys here DO NOT WANT to provide a simple example WITHOT openaAI api key (maybe they are their contractors, or employees or whatever ...)
So if your goal is to achieve privacy, true privacy of your data, this is not the right place to seek TRUE answer!
(i asked them [polite] couple of times to proved a simple example without openai infrastructure and they offered me colab notebook EXACTLY for openai (see upper post). I will not sped time here any more ...

**Comment by logan-markewich** [comment]
@AngelTs I just provided a clear example of using local models from huggingface... in any case, best of luck in your LLM journey

**Comment by canberk17** [comment]
I am also getting the following error:

```
Traceback (most recent call last):
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/embeddings/utils.py", line 59, in resolve_embed_model
    validate_openai_api_key(embed_model.api_key)
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/embeddings/openai/utils.py", line 104, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/app.py", line 78, in <module>
    index = VectorStoreIndex.from_documents(documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 145, in from_documents
    return cls(
           ^^^^
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 71, in __init__
    else embed_model_from_settings_or_context(Settings, service_context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/settings.py", line 274, in embed_model_from_settings_or_context
    return settings.embed_model
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/settings.py", line 67, in embed_model
    self._embed_model = resolve_embed_model("default")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ck/fugazi_tech/rag_projects/llama_banker/venv/lib/python3.11/site-packages/llama_index/core/embeddings/utils.py", line 66, in resolve_embed_model
    raise ValueError(
ValueError: 
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******
```

Even though I am exclusively passing huggingfaceEmbedding in my code:

```
# Create embeddings instance explicitly with HuggingFaceEmbeddings
embed_model = LangchainEmbedding(HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2"))

llm = Bedrock(
    model_id=llamaModelId,
    model_kwargs={'max_gen_len': 2048, 'top_p': 0.5, 'temperature': 0.9}
)

service_context = ServiceContext.from_defaults(
    chunk_size=1024,
    llm=llm,
    embed_model=embed_model  # Use the globally set HuggingFaceEmbeddings
)

# Set the global service context
llama_index.global_service_context = service_context 
```

Why is this the case, I couldnt find any resolution to this problem in any of the linked issues here. Could you please assist me in the right direction here @logan-markewich

**Comment by canberk17** [comment]
Using the following solved the problem for me:

`embed_model = LangchainEmbedding(SentenceTransformerEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2"))`

instead of using this:


`embed_model = LangchainEmbedding(HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2"))
`

**Comment by lmaddox** [comment]
bump
