### ISSUE TITLE
ValidationError on configs

### ISSUE THREAD

**Issue by hanbyul-kim** [jerryjliu/llama_index#853]
@jerryjliu

I'm reproducing this jupyter notebook. (https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb)
While running the notebook, I have a validation error like this.
This seems like a type mismatch exception and happens in other configs too.

```python
# define toolkit
index_configs = []
for y in range(2019, 2023):
    tool_config = IndexToolConfig(
        index=index_set[y], 
        name=f"Vector Index {y}",
        description=f"useful for when you want to answer queries about the {y} SEC 10-K for Uber",
        index_query_kwargs={"similarity_top_k": 3},
        tool_kwargs={"return_direct": True}
    )
    index_configs.append(tool_config)
File ~/chatgpt/lib/python3.9/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for IndexToolConfig
index
  instance of BaseGPTIndex expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseGPTIndex)
```

I was able to run it successfully by relaxing the index and graph types to `Any`.
Do you have any idea on these errors?

```diff 
--- a/gpt_index/langchain_helpers/agents/tools.py
+++ b/gpt_index/langchain_helpers/agents/tools.py
@@ -1,18 +1,19 @@
 """LlamaIndex Tool classes."""

-from typing import Dict, List, cast
+from typing import Dict, List, cast, Any

 from langchain.tools import BaseTool
 from pydantic import BaseModel, Field

 from gpt_index.composability.graph import QUERY_CONFIG_TYPE, ComposableGraph
 from gpt_index.indices.base import BaseGPTIndex
+from gpt_index.indices.vector_store.vector_indices import GPTSimpleVectorIndex


 class IndexToolConfig(BaseModel):
     """Configuration for LlamaIndex index tool."""

-    index: BaseGPTIndex
+    index: Any
     name: str
     description: str
     index_query_kwargs: Dict = Field(default_factory=dict)
@@ -27,7 +28,7 @@ class IndexToolConfig(BaseModel):
 class GraphToolConfig(BaseModel):
     """Configuration for LlamaIndex graph tool."""

-    graph: ComposableGraph
+    graph: Any
     name: str
     description: str
     query_configs: List[Dict] = Field(default_factory=dict)
@@ -43,7 +44,7 @@ class LlamaIndexTool(BaseTool):
     """Tool for querying a LlamaIndex."""

     # NOTE: name/description still needs to be set
-    index: BaseGPTIndex
+    index: Any
     query_kwargs: Dict = Field(default_factory=dict)

     @classmethod
@@ -70,7 +71,7 @@ class LlamaGraphTool(BaseTool):
     """Tool for querying a ComposableGraph."""

     # NOTE: name/description still needs to be set
-    graph: ComposableGraph
+    graph: Any
     query_configs: List[Dict] = Field(default_factory=list)
```

**Comment by jerryjliu** [comment]
> @jerryjliu
> 
> I'm reproducing this jupyter notebook. (https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb) While running the notebook, I have validation an error like this. This seems like a type mismatch exception and happens in other configs too.
> 
> ```python
> # define toolkit
> index_configs = []
> for y in range(2019, 2023):
>     tool_config = IndexToolConfig(
>         index=index_set[y], 
>         name=f"Vector Index {y}",
>         description=f"useful for when you want to answer queries about the {y} SEC 10-K for Uber",
>         index_query_kwargs={"similarity_top_k": 3},
>         tool_kwargs={"return_direct": True}
>     )
>     index_configs.append(tool_config)
> File ~/chatgpt/lib/python3.9/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()
> 
> ValidationError: 1 validation error for IndexToolConfig
> index
>   instance of BaseGPTIndex expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseGPTIndex)
> ```
> 
> I was able to run it successfully by relaxing the index and graph types to `Any`. Do you have any idea on these errors?
> 
> ```diff
> --- a/gpt_index/langchain_helpers/agents/tools.py
> +++ b/gpt_index/langchain_helpers/agents/tools.py
> @@ -1,18 +1,19 @@
>  """LlamaIndex Tool classes."""
> 
> -from typing import Dict, List, cast
> +from typing import Dict, List, cast, Any
> 
>  from langchain.tools import BaseTool
>  from pydantic import BaseModel, Field
> 
>  from gpt_index.composability.graph import QUERY_CONFIG_TYPE, ComposableGraph
>  from gpt_index.indices.base import BaseGPTIndex
> +from gpt_index.indices.vector_store.vector_indices import GPTSimpleVectorIndex
> 
> 
>  class IndexToolConfig(BaseModel):
>      """Configuration for LlamaIndex index tool."""
> 
> -    index: BaseGPTIndex
> +    index: Any
>      name: str
>      description: str
>      index_query_kwargs: Dict = Field(default_factory=dict)
> @@ -27,7 +28,7 @@ class IndexToolConfig(BaseModel):
>  class GraphToolConfig(BaseModel):
>      """Configuration for LlamaIndex graph tool."""
> 
> -    graph: ComposableGraph
> +    graph: Any
>      name: str
>      description: str
>      query_configs: List[Dict] = Field(default_factory=dict)
> @@ -43,7 +44,7 @@ class LlamaIndexTool(BaseTool):
>      """Tool for querying a LlamaIndex."""
> 
>      # NOTE: name/description still needs to be set
> -    index: BaseGPTIndex
> +    index: Any
>      query_kwargs: Dict = Field(default_factory=dict)
> 
>      @classmethod
> @@ -70,7 +71,7 @@ class LlamaGraphTool(BaseTool):
>      """Tool for querying a ComposableGraph."""
> 
>      # NOTE: name/description still needs to be set
> -    graph: ComposableGraph
> +    graph: Any
>      query_configs: List[Dict] = Field(default_factory=list)
> ```

Ah. do you have llama-index installed (instead of gpt-index)? Change all imports to `import llama_index` and `from llama_index` instead of `import gpt_index` and `from gpt_index`

**Comment by hanbyul-kim** [comment]
I'd wanted to run the below cell replacing gpt_index to llama_index and I got another error.

```python
from langchain.agents import Tool
from langchain.chains.conversation.memory import ConversationBufferMemory
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent

from llama_index.langchain_helpers.agents import LlamaToolkit, create_llama_chat_agent, IndexToolConfig, GraphToolConfig
```

```python

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[16], line 6
      3 from langchain.chat_models import ChatOpenAI
      4 from langchain.agents import initialize_agent
----> 6 from llama_index.langchain_helpers.agents import LlamaToolkit, create_llama_chat_agent, IndexToolConfig, GraphToolConfig

ModuleNotFoundError: No module named 'llama_index.langchain_helpers.agents'
```

**Comment by hanbyul-kim** [comment]
Oh, I forgot to mention my code version.`6adb0fe` had the errors above.

**Comment by hanbyul-kim** [comment]
Probably I already imported `llama_index` version of indices!
I restored them to `gpt_index` version and it works on `6adb0fe`. 
So the reported error was caused by my mistake.

Just for test, I checkout to main, `1ca5ddc7d44677d3ff91e65a43651fdd194ef741` and this works fine, too!
Sorry for confusion.
