### ISSUE TITLE
It is not possible to answer this question with the given context information.

### ISSUE THREAD

**Issue by yngstr** [jerryjliu/llama_index#856]
I'm using:

```
documents = SimpleDirectoryReader('directory').load_data()
index = GPTSimpleVectorIndex(documents)
query = 'What are expectations around the Dungeons & Dragons movie'
response = index.query(query)
```

The strange part is that when I only have 1 document in the 'directory', I get the correct answer. However when I put many documents into this directory (including the original document that got the right answer), I get:

```
It is not possible to answer this question with the given context information.
```

Am I misunderstanding something about how index works? Does it only embed some documents and not others from the directory?

**Comment by Disiok** [comment]
This is because `GPTSimpleVectorIndex` queries for the top 1 similar document by default.

If you have more documents, the retrieval might miss the desired document with the correct context.

Try using a higher `similarity_top_k` when querying.

**Comment by yngstr** [comment]
> This is because `GPTSimpleVectorIndex` queries for the top 1 similar document by default.
> 
> If you have more documents, the retrieval might miss the desired document with the correct context.
> 
> Try using a higher `similarity_top_k` when querying.

Thank you! Couldn't figure this out!
