### ISSUE TITLE
Rate limit issue

### ISSUE THREAD

**Issue by xmalina** [jerryjliu/llama_index#857]
I keep getting this issue -- building indexes is taking for ever -- and then it sort of times out. I can't figure it out at all. Appreciate any tips. 

For context, I'm loading in a CSV and treating each row as a document. The documents have at most a 50 tokens.

llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
index = GPTKeywordTableIndex(documents[:5], llm_predictor=llm_predictor)

WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).

WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).

Followed by this:

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>

**Comment by Disiok** [comment]
Hey @xmalina  This is most likely due to OpenAI API availability issues. There's not much we can do on our side.

You might have better luck trying a different model.
