### ISSUE TITLE
Bug: GPTSimpleVectorIndex with Text and Images can't save to disk

### ISSUE THREAD

**Issue by chengyjonathan** [jerryjliu/llama_index#858]
I had an index with just text documents that I could save to disk.

When I add image documents to that index, I get this error. I imagines it's because of how the images are encoded?

```
File ~/.conda/envs/gptindex/lib/python3.8/site-packages/llama_index/indices/base.py:619, in BaseGPTIndex.save_to_disk(self, save_path, encoding, **save_kwargs)
    603 def save_to_disk(
    604     self, save_path: str, encoding: str = "ascii", **save_kwargs: Any
    605 ) -> None:
    606     """Save to file.
    607 
    608     This method stores the index into a JSON file stored on disk.
   (...)
    617 
    618     """
--> 619     index_string = self.save_to_string(**save_kwargs)
    620     with open(save_path, "wt", encoding=encoding) as f:
    621         f.write(index_string)

File ~/.conda/envs/gptindex/lib/python3.8/site-packages/llama_index/indices/base.py:601, in BaseGPTIndex.save_to_string(self, **save_kwargs)
    588 """Save to string.
    589 
    590 This method stores the index into a JSON string.
   (...)
    598 
...
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type bytes is not JSON serializable
```

**Comment by sanjeebtiwary** [comment]
Yes, it is possible that the error you are seeing is related to how the image documents are encoded. The error message suggests that the object being saved to disk contains bytes, which are not JSON serializable.

JSON is a text-based format, and it can only represent a subset of the types that Python can handle. Specifically, it can handle strings, numbers, booleans, lists, and dictionaries. When you try to serialize an object that is not one of these types, you will get a TypeError.

It is likely that the image documents you are adding to the index are being represented as bytes objects in Python. To fix the error, you will need to convert the bytes objects to a format that can be JSON serialized. One option is to convert the bytes to a string using base64 encoding, which can be easily JSON serialized.

Here is an example of how you could modify the save_to_string method to handle image documents encoded as bytes using base64:

import json
import base64

class MyGPTIndex(BaseGPTIndex):
    def save_to_string(self, **save_kwargs):
        # convert image documents to base64 encoded strings
        index_dict = {}
        for key, value in self.index.items():
            if isinstance(value, bytes):
                value = base64.b64encode(value).decode('ascii')
            index_dict[key] = value

        # serialize the index to a JSON string
        index_string = json.dumps(index_dict, **save_kwargs)
        return index_string


When you save the index to disk using the modified save_to_string method, the image documents will be represented as strings in the JSON file. When you load the index back into memory, you can decode the base64 strings back into bytes objects.

**Comment by liumuqi** [comment]
i had this problem, when fix it.Please confirm the time
