### ISSUE TITLE
proposal: Extend readers to all storage services

### ISSUE THREAD

**Issue by Xuanwo** [jerryjliu/llama_index#865]
Hi, do you think it's a good idea to extend readers to all storage services so that we can read and index data stored at `s3`, `azblob` or `gcs`?

## Guide-level explanation

After this proposal implemented, users can read data from all storage services:

```py
import os
os.environ["AWS_ACCESS_KEY_ID"] = 'YOUR_AWS_ACCESS_KEY_ID'
os.environ["AWS_SECRET_ACCESS_KEY"] = 'YOUR_AWS_SECRET_ACCESS_KEY'

from llama_index import GPTSimpleVectorIndex, OpendalReader
documents = OpendalReader('s3', bucket='my-bucket', root='path/to/data').load_data()
index = GPTSimpleVectorIndex(documents)
```

By extending readers support, we can read data from all storage services.

## Reference-level explanation

[OpenDAL](https://github.com/apache/incubator-opendal) is an Apache Incubating project which focus on accessing data freely, painlessly, and efficiently. It's written in rust, and provides a native python binding:

```shell
pip install opendal
```

```py
import asyncio

async def main():
    op = opendal.AsyncOperator("s3", root="/path/to/data")
    print(await op.read("test.txt"))

asyncio.run(main())
```

OpenDAL is supports [20+ services](https://github.com/apache/incubator-opendal/blob/main/core/README.md) including `s3`, `gcs`, `azblob`, `hdfs` and so on.

---

I am the committer of Opendal and I am interested in implementing this feature. Please let me know if you have any comments. Thanks in advance!

**Comment by jerryjliu** [comment]
This is a great idea! If you are able to open a PR against llama-hub that would be amazing 🙏 https://github.com/emptycrown/llama-hub

**Comment by Xuanwo** [comment]
Thanks for the quick response!

I have submit a PR https://github.com/emptycrown/llama-hub/pull/137 for this proposal, PTAL

**Comment by jerryjliu** [comment]
awesome! thanks so much for the quick turnaround, will take a look soon
