### ISSUE TITLE
Doc : PromptHelper - need more info on parameters

### ISSUE THREAD

**Issue by ezawadzki** [jerryjliu/llama_index#870]
It would be great to have more information about parameters of `PromptHelper` :

![image](https://user-images.githubusercontent.com/4253915/227500033-f2fb9e9c-e22f-4091-a839-48095af29146.png)

- Definition of parameters, the impact, for what they are used to 
- Precise the unity (nb of chars ? etc...)
- Min / Max ?

Enventually, we can provide external link documentation from LLM Theory.

**Comment by Disiok** [comment]
Agreed, we should definitely make the documentation clearer. Will take a todo here.

**Comment by mingxin-yang** [comment]
Hello, have you figured out the purpose of these parameters? I want to control the number of tokens used by the query each time. Which parameters are mainly used? @ezawadzki

**Comment by ezawadzki** [comment]
@mingxin-yang I guess number of chars but not sure...

**Comment by logan-markewich** [comment]
The documentation has been updated with more info on token parameters. All parameters related to chunk sizes are measured in tokens. Furthermore, the prompt helper isn't really user facing anymore. Instead, you can use the service context directly. 

Check the docs out!
https://gpt-index.readthedocs.io/en/latest/core_modules/supporting_modules/service_context.html#configuring-the-service-context
