### ISSUE TITLE
Can not load image for Could not find image processor class in the image processor config or the model config

### ISSUE THREAD

**Issue by geeeezx** [jerryjliu/llama_index#872]
I tried to use the SimpleDirectoryReader to load the image.jpg but failed.
Just logged 
`Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.`

Could you help me with that? Thankyou!

**Comment by Disiok** [comment]
This is just a warning, shouldn't prevent the image processor from running.

**Comment by csrss** [comment]
I have same issue, but no images in a directory.

**Comment by cheerlessDreamer** [comment]
> I have same issue, but no images in a directory.

You may still face this warning if you have, for example, a PDF that contains images.
