### ISSUE TITLE
Index loaded from saved file behaves differently from the original one

### ISSUE THREAD

**Issue by vadimber** [jerryjliu/llama_index#892]
Hi,
In the following example, I build an index, then save it and upload it once again to a different instance. I am asking the same question:
Where Micha Josef Berdyczewski was born? Tell something about this place

and I am getting these two answers:
1) From the original index:
Micha Josef Berdyczewski was born in 1865 in the town of Medzhibozh (today Medzhybizh) in Podolia Governorate, to a family of Hasidic Rabbis.
2) From index recovered from the saved file:
The given context information does not provide any information about the birthplace or any details about Micha Josef Berdyczewski's birthplace.

I tried to debug it, but the code is very cumbersome... I tried to bypass it with pickle, but it doesn't work because of the same "cannot pickle 'builtins.CoreBPE' object" I opened yesterday.

Following is the e2e example to reproduce this case (you will need to 
[example.txt](https://github.com/jerryjliu/llama_index/files/11070507/example.txt)
substitute your API keys):

**Comment by iraadit** [comment]
That could explain some problems I have too

**Comment by logan-markewich** [comment]
If you are defining a ServiceContext, be sure to pass it in when loading from disk as well

Going to close this for now. Feel free to join the discord if you have further questions!
