### ISSUE TITLE
Integration with llama.cpp

### ISSUE THREAD

**Issue by 0x090909** [jerryjliu/llama_index#898]
Hello, 

Im reading the documentation and it seems that this indexer cannot be used with https://github.com/ggerganov/llama.cpp.

Am I correct?

If so, will it be integrated in the future?

Thanks

**Comment by logan-markewich** [comment]
@0x090909 the documentation provides an example of using a custom LLM here: https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html#example-using-a-custom-llm-model

**Comment by ianscrivener** [comment]
@logan-markewich .. sorry, but that link is dead now

**Comment by ianscrivener** [comment]
I'm using llama.cpp a lot. C++ inference of 4 bit quantized and optimised models is VERY performant. Significantly faster than FP16 python code

One approach to use **llama.cpp** with **llama_index** would be to use Abetlen's [https://github.com/abetlen/llama-cpp-python](https://github.com/abetlen/llama-cpp-python) pip pakcage hich replicates OpenAIa's API... though this (I assume) would require runnign two processes to get the job done

Ideally, there would be a **llama_index** Custom LLM module, that used an existing **llama.cpp** install .. `llama_cpp-bin=/somwhere/llama.cpp/bin/main`... leveraging the python C++ headers as per **llama-cpp-python**

**Comment by ianscrivener** [comment]
Another good, C++ FAST local LLM inference engine is [https://github.com/OpenNMT/CTranslate2](https://github.com/OpenNMT/CTranslate2)... which can use Llama family models.. as well as other family LLM models.

**Comment by logan-markewich** [comment]
You can use any LLM that langchain offers (which happens to include llama.cpp)

Using v0.7.4
```
from llama_index import SeviceContext, set_global_service_context 

llm = <setup langchain llm>
service_context = ServiceContext.from_defaults(llm=llm)
set_global_service_context(service_context, context_window=<context window of llm>, chunk_size=<some value about 25%smaller than the context window of the llm>)
```

Ngl but the last time I tried, llama.cpp is still not as fast as I'd like, and I think the context window was only 512 which is quite tiny for llama index

**Comment by ianscrivener** [comment]
thanks @logan-markewich 🙏

So langchain supports llama.cpp via llama-cpp-python library... which is fine - usually just 1 release version behind llama.cpp. [https://github.com/abetlen/llama-cpp-python/blob/main/docs/install/macos.md](llama-cpp-python & llama.cpp happily run Mac Arm64 & Metal)

BTW: llama.cpp currently supports context size up to **2048**, the C++ devs are currently working on extending context size via **RoPE scaling**.

llama.cpp is _by far the best & fastest self hosted LLM inference I have found for Mac Silicon (Metal)_

**Comment by ianscrivener** [comment]
Here's how I upgraded llama-cpp-python to support MacOS MEtal GPU
```
pip uninstall llama-cpp-python
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir
```
BTW: xcode is required to compile the llama.cpp binary

**Comment by trover97** [comment]
Hi!
Which tokenizer should I use in the llama_index pipelines along with llama.cpp?
