### ISSUE TITLE
Python3.10 with lama index on ubuntu

### ISSUE THREAD

**Issue by myrulezzz** [jerryjliu/llama_index#899]
Hi installing llama index on ubuntu 20.0.4 with all its dependecies and creating a simple python app i get Traceback (most recent call last):
  File "/root/openai/./opendoc.py", line 4, in <module>
    from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader
  File "/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py", line 15, in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
  File "/usr/local/lib/python3.10/dist-packages/llama_index/embeddings/openai.py", line 6, in <module>
    import openai
  File "/root/openai/openai.py", line 2, in <module>
    from llama_index import download_loader
ImportError: cannot import name 'download_loader' from partially initialized module 'llama_index' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py). 
Any idea why i get the partial. I don't see any other dependencies to install.
On my mac is working fine.
Thanks in advance.

**Comment by logan-markewich** [comment]
It looks like your directory structure is causing some name conflicts?

llama_index imports openai, but then it's importing from your files in /root/openai rather than importing from dist-packages

Try renaming /root/openai to something else

**Comment by myrulezzz** [comment]
Hi @logan-markewich changing the directory did the trick thanks. However i am experiencing with SimpleMongoreader and i stack to find documentation how to pass auth with username and password. Here is what the reader accepts:
reader = SimpleMongoReader(host, port)
I have tried to add username and password but it fails as it uses only 2 parameters and it gets username as hostname and port as port
Are you aware of any link that could help me?

**Comment by logan-markewich** [comment]
@myrulezzz I don't see any mention of username/password in the source code.
https://github.com/emptycrown/llama-hub/blob/main/loader_hub/mongo/base.py

Using just the port/host doesn't work? I'm not experienced with Mongo tbh lol

It's us8ng pymongo under the hood, if that helps: https://pymongo.readthedocs.io/en/stable/

**Comment by myrulezzz** [comment]
ok thanks.i will check. Any suggestion for storage of data do use with llama index?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by logan-markewich** [comment]
I would use either a vector store integration (since they store the entire index in the vector store) or you could look into using something like S3

Some helpful links for your journey
https://gpt-index.readthedocs.io/en/latest/how_to/storage/save_load.html#using-a-remote-backend
https://gpt-index.readthedocs.io/en/latest/how_to/storage/customization.html#vector-store-integrations-and-storage
https://gpt-index.readthedocs.io/en/latest/how_to/storage/vector_stores.html


Of course, saving to disk works just fine as well. 

Going to close this issue for now. Feel free to re-open or join the discord!
