### ISSUE TITLE
Answer based only on my documents

### ISSUE THREAD

**Issue by stergiosmaster** [jerryjliu/llama_index#901]
Hi, this is not an issue but a question,

I wanted to ask if the answer of the chatbot is based only on the index-documents given, or it might give extra information. 
For example let's say I have a document with 1 sentence about "newton laws", but in my query I ask a lot of things about newton laws, which are not in the document. How can I make the response be based **only** on my document? I wouldnt like to have extra information that is not coming from my document

**Comment by logan-markewich** [comment]
Internally llama index tells the model to only use information from the documents.

But LLMs are not perfect yet, and don't always follow instructions perfectly, especially for common/popular topics like newton's laws where it might have internal knowledge on the topic.
 
A lot of this is dependent on prompt engineering. You can try customizing the prompts further by following the guide here: 
https://gpt-index.readthedocs.io/en/latest/how_to/custom_prompts.html

**Comment by Disiok** [comment]
One idea we have in this direction is to use LLM to evaluate whether the answer is correct and matches the retrieved context. See https://twitter.com/gpt_index/status/1636768877014319106 for an example.
