### ISSUE TITLE
How to create a BaseDocument object manually?

### ISSUE THREAD

**Issue by mzhadigerov** [jerryjliu/llama_index#903]
There are helper wrappers to read files from a directory e.g. `SimpleDirectoryReader` etc. 
We can then convert them into `BaseDocument`s list using `load_data()` function. 
But how can we create such a documents manually?

e.g.:

```
raw_texts = ["A", "B", "C"]
documents = [BaseDocument(text=r, .....) for r in raw_texts]
```

we can then pass that documents into our index:

```
GPTSimpleVectorIndex(documents, ....)
```

**Comment by jerryjliu** [comment]
BaseDocument is an abstract class but do `from gpt_index import Document` (which is a subclass of BaseDocument).

e.g. 
```
extra_info = {} # put your metadata here
doc = Document("text here", doc_id="doc id", extra_info=extra_info)
```

**Comment by mzhadigerov** [comment]
@jerryjliu THAT's what I was looking for! Thank you!
