### ISSUE TITLE
Where do I define top_k documents to be returned by similarity search over vectorstore?

### ISSUE THREAD

**Issue by mzhadigerov** [jerryjliu/llama_index#905]
When calling `query` function, how do I specify how many `k`s do I want the retriever to pass to a LLM? Or do I need to specify it before calling `query` function?

```
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0, openai_api_key=api_key))
index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor,
                                     prompt_helper=prompt_helper)

index.query(question, mode="default")
``` 

code doc of `GPTSimpleVectorIndex` says that during query time it uses top k most similar nodes:

```
    """GPT Simple Vector Index.

    The GPTSimpleVectorIndex is a data structure where nodes are keyed by
    embeddings, and those embeddings are stored within a simple dictionary.
    During index construction, the document texts are chunked up,
    converted to nodes with text; they are then encoded in
    document embeddings stored within the dict.

    During query time, the index uses the dict to query for the top
    k most similar nodes, and synthesizes an answer from the
    retrieved nodes.

    Args:
        text_qa_template (Optional[QuestionAnswerPrompt]): A Question-Answer Prompt
            (see :ref:`Prompt-Templates`).
            NOTE: this is a deprecated field.
        embed_model (Optional[BaseEmbedding]): Embedding model to use for
            embedding similarity.

    """
 ```

but I don't have ability to pass how many ks do I need

**Comment by logan-markewich** [comment]
You can set it like this 
`index.query(..., similarity_top_k=3)`

The default is 1. You can also set a similarity cutoff, which will filter out nodes below a certain similarity:
`index.query(..., similarity_cutoff=0.5)`

**Comment by mzhadigerov** [comment]
@logan-markewich Sorry, I'm new in  using llamaindex and have a confusion in the interface of the framework. By "default=1", do you mean that by while performing similarity search between a query and whole a lot of N documents in vectorestore, the algorithm picks a single most similar document and sends it to a LLM as a context in prompt? 

e.g.:

user_query= "Which pharaoh built the tallest pyramid?" 

user_query ---> vectorstore ---> (returns a single similar document) ----> creating a prompt, like: "answer a question {user_query} using the context {a_single_document_text}


Is that how it works? Please, correct me If I'm wrong

**Comment by logan-markewich** [comment]
@mzhadigerov yea you've described that properly! 👍 so if you set it to something like 3, it will ask the model as you've laid out for the first matching node, and then for the next two it will ask the model to refine its original answer

**Comment by logan-markewich** [comment]
You might be interested in our docs, especially this page: https://gpt-index.readthedocs.io/en/latest/guides/index_guide.html

**Comment by mzhadigerov** [comment]
Thanks @logan-markewich .I will definitely read the docs for better understanding 🙇🏻‍♂️
One thing I've noticed, while comparing llamaindex with langchain and haystack, is that llamaindex made the pipeline too abstract (like in the case with the "query" function, it performs  several important steps in one function). I am not really a fan of such "hiding", but prolly I'm wrong and I need to check the docs . Anyways, thanks and have a good day 🙏

**Comment by logan-markewich** [comment]
@mzhadigerov sounds good!

Also, definitely check out the discord if you have more questions. Lots of good ideas and helpful stuff discussed there: https://discord.gg/Z5Eu6jYy

**Comment by wilmerhenao** [comment]
> You can set it like this `index.query(..., similarity_top_k=3)`
> 
> The default is 1. You can also set a similarity cutoff, which will filter out nodes below a certain similarity: `index.query(..., similarity_cutoff=0.5)`

This doesn't seem to work anymore :(

**Comment by logan-markewich** [comment]
The API has changed quite a bit @wilmerhenao 

Our docs usually have the answer if you search though. I highly recommend taking a light read through the usage primer in the docs for a refresh 

Here's some updated usage (setting similarity_cutoff is a little annoying. The top k be easily set using `index.as_query_engine(similarity_top_k=3)` though, or you can use the method in the below link

https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#low-level-api
