### ISSUE TITLE
How to prepare a product information correctly so that llama_index returns a reasonable answer

### ISSUE THREAD

**Issue by shangdev** [jerryjliu/llama_index#917]
This is the profile of one of the products, I used html to store him:

```
<h1>产品资料介绍</h1>
<p>产品编码:00001.</p>
<p>产品名称:abcd.</p>
<p>产品型号:abcd.</p>
<p>封装形式:.</p>
<p>规格参数:.</p>
<p>高度:.</p>
<p>高低压:高压.</p>
<p>物理尺寸:.</p>
<p>设计工程师:.</p>
<p>画板工程师:.</p>
<p>计量单位:只.</p>
<p>销售基准价:1600.</p>
<p>料单版本::V0.1/V0.2.</p>
<p>创建时间:2019-08-30 10:06:00.</p>
<p>重量或质量:.</p>
```

When I asked llama: `abcd 的产品编码是多少？`, he returned: 

```
abcd是一款产品，产品编码为00001，型号为abcd，规格参数为：高度为高度接，设计工程师为，绘制工程师为，计价单位为只，批准价格或建议价格为1600，标准版本为V0.1/V0.2，创建时间为2019-08-30 10:06:00，质量或质量控制为。
```

![image](https://user-images.githubusercontent.com/15621520/227877787-4efd6c79-ca8e-4a0f-a49a-f7aa120c57a5.png)

I just asked for the `产品编码` and he couldn't seem to identify where the `产品编码` ended from. 

Is there something wrong with my html? How can I improve this text?

**Comment by Disiok** [comment]
Hey @shangdev This could be a number of reasons: 1) the model not doing well on HTML  format, 2) the model not reasoning over chinese well. I would suggest trying some other document format, and some prompt engineering.
