### ISSUE TITLE
How to get a DOCUMENT NAME from the doc_id parameter in the index.json output.

### ISSUE THREAD

**Issue by kindler-king** [jerryjliu/llama_index#923]
I am curious, after parsing the directory using SimpleDirectoryReader().load_data() and creating the index, each document has an attached ID and text in the .json output of the index. 

Is it possible anyhow to get the relevant file_name from the attached doc_id parameter? I am curious of mapping the doc_id's to actual names of the file. Thanks a lot for the help :D

**Comment by onesecurity** [comment]
https://github.com/jerryjliu/llama_index/issues/613

**Comment by jerryjliu** [comment]
yeah if you specify a file_metadata callable then you can define an arbitrary function to load metadata per file
