### ISSUE TITLE
RetryError[<state=finished raised RateLimitError>] 

### ISSUE THREAD

**Issue by ashutoshsinha25** [jerryjliu/llama_index#924]
I'm getting this error : 
raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fcf1f3d9630 state=finished raised RateLimitError>]

this error is occurring from this line : GPTSimpleVectorIndex(docs, llm_predictor=gpt3_5_llm_predictor, prompt_helper=prompt_helper,chunk_size_limit=1024)
here gpt3_5_llm_predictor = ChatGPTLLMPredictor( max_tokens=num_output)

**Comment by Terranic** [comment]
getting the same error while processing 5000 plain text files with a total of 5 GB Text....

**Comment by kurtsenol** [comment]
getting the same error while processing a single 27 KB .txt file.

**Comment by ashutoshsinha25** [comment]
my text files are in range of 10Kb (.txt files) still facing this issue

**Comment by yuhua21223** [comment]
yes, I am experiencing same issue. Has anyone figured out solution to issue? Just running with a 10kb file.

**Comment by mateuszgruszka** [comment]
Maybe you finished free limit of 5 dollars on your OpenAI account, it also expires after 3 months.
https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial

**Comment by ashutoshsinha25** [comment]
@mateuszgruszka i have a plus account and sufficient balance

**Comment by WiktorLigeza** [comment]
Hi, any solution?

**Comment by proDOOMman** [comment]
Throttling is not supported in async querying. May be related to this line:
https://github.com/jerryjliu/llama_index/blob/085c88f52dd73f947e5d26bd6de57513b2b5a96c/llama_index/llm_predictor/base.py#L309

**Comment by banank1989** [comment]
facing the same with just 1 line in input file. Any solutions?

**Comment by createchange** [comment]
+1

**Comment by JViggiani** [comment]
+1

**Comment by logan-markewich** [comment]
If you have a free account, you'll need to add payment info to get large rate limits/quotas

**Comment by FMassion** [comment]
I have the same issue with some others in this discussion. Just trying the llama connectors an a very small file with a few lines of code like: 
```
from pathlib import Path
from llama_index import download_loader
DocxReader = download_loader("DocxReader")

loader = DocxReader()
documents = loader.load_data(file=Path('/myfile.docx'))
query_engine = index.as_query_engine()
query_engine.query("my question?")
```
This is what I got:
```
---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    381                 try:
--> 382                     result = fn(*args, **kwargs)
    383                 except BaseException:  # noqa: B902

18 frames
AuthenticationError: <empty message>

The above exception was the direct cause of the following exception:

RetryError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in iter(self, retry_state)
    324             if self.reraise:
    325                 raise retry_exc.reraise()
--> 326             raise retry_exc from fut.exception()
    327 
    328         if self.wait:

RetryError: RetryError[<Future at 0x7f69849cf460 state=finished raised AuthenticationError>]
```
I have a paid account (20$, payment infos are in my profile). I checked the usage, there is plenty of reserve. I tried to run in different environments (local, Colab) and with different types of file (pdf and youtube transcripts,) but got the same issue. Any help would be appreciated.

**Comment by mhasabir** [comment]
Use old package langchain==0.0.188.
There are some issues in new releases.

**Comment by FMassion** [comment]
Thanks to mhasabir. My version of langchain was 0.0.192. I did as suggested and now it works fine.

**Comment by nithinjp1997** [comment]
Oh thank you for that helped

**Comment by ashutoshsinha25** [comment]
I'm closing this issue, major issue was related to langchain version, hope this would help others in the future if they face similar issue

**Comment by yogeshhk** [comment]
Even with langchain=0.0.188, getting same error

`
from langchain import HuggingFaceHub

from llama_index import VectorStoreIndex, SimpleDirectoryReader, LLMPredictor, ServiceContext

documents = SimpleDirectoryReader('data/experiment').load_data()
repo_id = "tiiuae/falcon-7b"

llm_predictor = LLMPredictor(llm=HuggingFaceHub(repo_id=repo_id,
                                                model_kwargs={"temperature": 0.1, 'truncation': 'only_first',
                                                              "max_length": 1024}))
service_context = ServiceContext.from_defaults(chunk_size=1024, llm_predictor=llm_predictor)

index = VectorStoreIndex.from_documents(documents=documents, service_context=service_context)
`

The error is:

`
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\llama_index\embeddings\openai.py", line 267, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1b98bb0a750 state=finished raised RateLimitError>]
`
But I guess main reason is, though I am using LLM from HuggngFaceHub, via Service Context, it is still searching for OpenAI

`
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\llama_index\embeddings\openai.py", line 150, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\yoges\anaconda3\envs\langchain\Lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
`

Now the error is being generated in langchain land, but the suggested version does not solve it

@ashutoshsinha25 @jerryjliu @ravi03071991

**Comment by Tapan-yadav** [comment]
import openai
import os

openai.api_key = 'Your api key'

# Set the OpenAI API key
os.environ["OPENAI_API_KEY"] = "your API key"

please don't forget to set your open ai key and you won't get the error again

**Comment by harshitsinghai77** [comment]
I'm getting the same error.
