### ISSUE TITLE
How to increase the length of the output ?

### ISSUE THREAD

**Issue by FiveTechSoft** [jerryjliu/llama_index#940]
I am using this code to document some code files:

```
import os
from llama_index import SimpleDirectoryReader
from llama_index import GPTSimpleVectorIndex

os.environ['OPENAI_API_KEY'] = "sk-..."  
documents = SimpleDirectoryReader('', ['c:/harbour/src/vm/arrays.c']).load_data()
index = GPTSimpleVectorIndex( documents )
response = index.query("list, explain and document all the functions and parameters for each function provided in such file")
print( response )
```
the printed response stops before finishing. How to increase the output length ?

**Comment by ytopia** [comment]
try response.get_formatted_sources(500)

**Comment by FiveTechSoft** [comment]
> try response.get_formatted_sources(500)

same issue

**Comment by ytopia** [comment]
The number of output tokens is usually set to some low number by default (for instance, with OpenAI the default is 256).
try llm_predictor
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="text-davinci-003", max_tokens=1024))
index = GPTSimpleVectorIndex.load_from_disk('index.json', llm_predictor=llm_predictor)
response = index.query(input_text, response_mode="default")

**Comment by Disiok** [comment]
Thanks @ytopia! Also see the FAQ: https://docs.google.com/document/d/1bLP7301n4w9_GsukIYvEhZXVAvOMWnrxMy089TYisXU/edit?usp=sharing
