### ISSUE TITLE
Invalid document type: <class 'llama_index.readers.schema.base.Document'>  examples/chatbot/Chatbot_SEC.ipynb    Running Error

### ISSUE THREAD

**Issue by Gavin2318** [jerryjliu/llama_index#943]
I am trying to run examples/chatbot/Chatbot_SEC.ipynb, and getting error below:

code:
`cur_index = GPTSimpleVectorIndex(doc_set[year], chunk_size_limit=512)`

error:
`Invalid document type: <class 'llama_index.readers.schema.base.Document'>.`

![image](https://user-images.githubusercontent.com/9253996/228188305-749c8e09-ff51-49a6-a928-c9d66e62019e.png)

My env is python 3.8.5
gpt-index==0.4.32  
langchain==0.0.116

Does any one encounter the same issue? Is there anyone know how to fix it? Any help will be appreciated!

**Comment by borisalmonacid** [comment]
I have this error. with Python 3.8.10, test in google colab.

Requirement already satisfied: rich==13.0.1 in /usr/local/lib/python3.9/dist-packages (13.0.1)

![image](https://user-images.githubusercontent.com/28852633/228415867-7c2a8c62-2fb8-4286-a7ee-f7989fe475ad.png)

**Comment by Gavin2318** [comment]
> I have this error. with Python 3.8.10, test in google colab.
> 
> Requirement already satisfied: rich==13.0.1 in /usr/local/lib/python3.9/dist-packages (13.0.1)
> 
> ![image](https://user-images.githubusercontent.com/28852633/228415867-7c2a8c62-2fb8-4286-a7ee-f7989fe475ad.png)

But as the screenshot showed, you installed rich 13.3.2, not  13.0.1. 

You can try to uninstall the rich 13.3.2 and install the correct version
`pip uninstall rich
 pip install rich==13.0.1
`

**Comment by logan-markewich** [comment]
This should be fixed in the latest versions of this tutorial. Please re-open if I am wrong!

**Comment by sujitsubhash7** [comment]
I'm getting the same error:
python 3.11.9
llama-index 0.10.27

![image](https://github.com/user-attachments/assets/b97386ab-46ef-4dea-86bd-8c462c2c59f4)
