### ISSUE TITLE
why query not use gpt-3.5 model ?

### ISSUE THREAD

**Issue by neove** [jerryjliu/llama_index#944]
here is my code ,i use gpt-3.5-turbo to build index,
`

def construct_index(directory_path, output_path):
    # set maximum input size
    max_input_size = 4096
    # set number of output tokens
    num_outputs = 2000
    # set maximum chunk overlap
    max_chunk_overlap = 20
    # set chunk size limit
    chunk_size_limit = 900

    # define LLM
    llm_predictor = LLMPredictor(llm=OpenAI(
        temperature=0.5, model_name="gpt-3.5-turbo", max_tokens=num_outputs))
    prompt_helper = PromptHelper(
        max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)

    documents = SimpleDirectoryReader(directory_path).load_data()

    index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper
    )

    index.save_to_disk(output_path)

    return index

`

then i query it:

`
def ask_ai(query, directory_path):
    index = GPTSimpleVectorIndex.load_from_disk(directory_path)
    # define custom QuestionAnswerPrompt
    QA_PROMPT_TMPL = (
        "这里有份视频字幕， \n"
        "---------------------\n"
        "{context_str}"
        "\n---------------------\n"
        "回答问题要语句完整通顺，语义清晰，我的问题是: {query_str}\n"
    )
    QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_TMPL)
    response = index.query(query,  mode="default", response_mode="default",  text_qa_template=QA_PROMPT)
    print(response)
    return response`

and then log this :
<img width="573" alt="image" src="https://user-images.githubusercontent.com/18530075/228203414-9aa52f2c-4cf5-47d3-8dd9-1b714a33306c.png">

**query use text-davinci-003 model, but not gpt-3.5, why ?**

**Comment by logan-markewich** [comment]
You need to pass in the llm_predictor when doing load_from_disk

`load_from_disk(..., llm_predictor=llm_predictor)`
