### ISSUE TITLE
llama_index/setup_llama.py", line 7, in <module>     with open(Path(__file__).absolute().parents[0] / "llama_index" / "VERSION") as _f: FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by jinfagang** [jerryjliu/llama_index#945]
llama_index/setup_llama.py", line 7, in <module>
    with open(Path(__file__).absolute().parents[0] / "llama_index" / "VERSION") as _f:
FileNotFoundError: [Errno 2] No such file or directory:

**Comment by Disiok** [comment]
What did you run to get this error?
