### ISSUE TITLE
Hope ComposableGraph.query() supports stream processing.

### ISSUE THREAD

**Issue by onesecurity** [jerryjliu/llama_index#946]
`TypeError: ComposableGraph.query() got an unexpected keyword argument 'streaming'`

I used a lot of text when querying and searching, and processed it with ComposableGraph. Unfortunately, this tool does not currently support streaming transmission. Is there any way to obtain its Composable process so that my users can know what searches the program has performed?

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/61774041/228269575-a1f37094-ec4f-40c5-8212-d0d82b0b2122.png">

**Comment by anhquyetnguyen** [comment]
@Disiok hi
When will Composable Graph support streaming?

**Comment by logan-markewich** [comment]
The graph supports streaming, but it is a little clunky

```python
>>> from llama_index import Document, GPTListIndex, LLMPredictor, ServiceContext
>>> documents = [Document("hello world")]
>>>
>>> from langchain.llms import OpenAI
>>> llm = OpenAI(model_name='text-davinci-003', temperature=0, streaming=True)
>>> service_context = ServiceContext.from_defaults(llm_predictor=LLMPredictor(llm=llm))
>>>
>>> index1 = GPTListIndex.from_documents(documents, service_context=service_context)
>>> index2 = GPTListIndex.from_documents(documents, service_context=service_context)
>>>
>>> from llama_index.indices.composability import ComposableGraph
>>> graph = ComposableGraph.from_indices(GPTListIndex, [index1, index2], index_summaries=['1', '2'], service_context=service_context)
>>> query_engines = {
...     index1.index_id: index1.as_query_engine(streaming=True),
...     index2.index_id: index2.as_query_engine(streaming=True),
...     graph.root_index.index_id: graph.root_index.as_query_engine(streaming=True)
... }
>>> query_engine = graph.as_query_engine(custom_query_engines=query_engines)
>>> response = query_engine .query("Hello world")
>>> type(response)
<class 'llama_index.response.schema.StreamingResponse'>
>>> for token in response.print_response_stream()
```

**Comment by hoangsonsky** [comment]
> The graph supports streaming, but it is a little clunky
> 
> ```python
> >>> from llama_index import Document, GPTListIndex, LLMPredictor, ServiceContext
> >>> documents = [Document("hello world")]
> >>>
> >>> from langchain.llms import OpenAI
> >>> llm = OpenAI(model_name='text-davinci-003', temperature=0, streaming=True)
> >>> service_context = ServiceContext.from_defaults(llm_predictor=LLMPredictor(llm=llm))
> >>>
> >>> index1 = GPTListIndex.from_documents(documents, service_context=service_context)
> >>> index2 = GPTListIndex.from_documents(documents, service_context=service_context)
> >>>
> >>> from llama_index.indices.composability import ComposableGraph
> >>> graph = ComposableGraph.from_indices(GPTListIndex, [index1, index2], index_summaries=['1', '2'], service_context=service_context)
> >>> query_engines = {
> ...     index1.index_id: index1.as_query_engine(streaming=True),
> ...     index2.index_id: index2.as_query_engine(streaming=True),
> ...     graph.root_index.index_id: graph.root_index.as_query_engine(streaming=True)
> ... }
> >>> query_engine = graph.as_query_engine(custom_query_engines=query_engines)
> >>> response = query_engine .query("Hello world")
> >>> type(response)
> <class 'llama_index.response.schema.StreamingResponse'>
> >>> for token in response.print_response_stream()
> ```

The streaming part doesn't work bro
