### ISSUE TITLE
openai:error_code=None error_message='Too many inputs for model None. The max number of inputs is 1.

### ISSUE THREAD

**Issue by ShubhamVerma16** [jerryjliu/llama_index#947]
while using llama_index GPTSimpleVectorIndex
I am reading a pdf file using SimpleDirectoryReader.

I am unable to create index for the file and it is generating the below error:

INFO:openai:error_code=None error_message='Too many inputs for model None. The max number of inputs is 1. We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

The code works for some files and fails for others with the above error.

Please suggest what does it mean by Too many inputs for model that comes as a error only for some files.

**Comment by Disiok** [comment]
Does this happen when you try to construct the index or when querying it?

**Comment by ShubhamVerma16** [comment]
This happens when i try to construct the index.

**Comment by raghavmittal101** [comment]
I too am getting the same error. Any fix to this?

**Comment by iaalm** [comment]
I hit same issue while using Azure OpenAI API. The workaround is to set `DEFAULT_EMBED_BATCH_SIZE` to 1 in `llama_index/embeddings/base.py`.
I think this is an Azure specific issue.

**Comment by danielbichuetti** [comment]
Azure OpenAI Embedding endpoint only accepts 1 input per request. To use batching you need to use parallelism.

**Comment by ShubhamVerma16** [comment]
> DEFAULT_EMBED_BATCH_SIZE

@iaalm The workaround helped me solve the issue

**Comment by ShubhamVerma16** [comment]
> Azure OpenAI Embedding endpoint only accepts 1 input per request. To use batching you need to use parallelism.

@danielbichuetti Thank you for your suggestion. Could you please elaborate on how do I use parallelism in this case.

**Comment by raghavmittal101** [comment]
@iaalm A big thanks 🙌🏻. It solved my problem.

**Comment by raghavmittal101** [comment]
> I hit same issue while using Azure OpenAI API. The workaround is to set `DEFAULT_EMBED_BATCH_SIZE` to 1 in `llama_index/embeddings/base.py`.
> I think this is an Azure specific issue.

@iaalm A big thanks 🙌🏻. It solved my problem.

**Comment by dwr-psandhu** [comment]
> 
For anyone looking for how, I had to create ServiceContext and then pass it to the methods that allow passing a service_context keyword

```
sc = ServiceContext.from_defaults(embed_model=OpenAIEmbedding(embed_batch_size=1))
GPTSimpleVectorIndex.from_documents(documents, service_context=sc)
```

**Comment by iaalm** [comment]
> For anyone looking for how, I had to create ServiceContext and then pass it to the methods that allow passing a service_context keyword
> 
> ```
> sc = ServiceContext.from_defaults(embed_model=OpenAIEmbedding(embed_batch_size=1))
> GPTSimpleVectorIndex.from_documents(documents, service_context=sc)
> ```

This's a much more decent solution. 👍

**Comment by dwr-psandhu** [comment]
Latest. Heres an example from the test code
https://github.com/jerryjliu/llama_index/blob/73c575438dbabc29ddbdd14ec42a2d103512f5fe/tests/embeddings/test_base.py#L45

**Comment by dwr-psandhu** [comment]
This is all I have
```
from llama_index.indices.service_context import ServiceContext
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.llm_predictor.base import LLMPredictor
sc = ServiceContext.from_defaults(embed_model=OpenAIEmbedding(embed_batch_size=1),
        llm_predictor=LLMPredictor(llm=AzureOpenAI(deployment_name='text-davinci-002')))

```

**Comment by richie-03** [comment]
NameError: name 'AzureOpenAI' is not defined

can you tell from where do i import AzureOpenAI?

**Comment by jokerjoey** [comment]
> is it embedding or emeddings? im using from langchain.embeddings import OpenAIEmbeddings

use 
from llama_index.embeddings.openai import OpenAIEmbedding
not 
from langchain.embeddings import OpenAIEmbeddings

**Comment by martinzwirner** [comment]
In my case the following fixed it:

embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        document_model_name=document_model_name,
        query_model_name=query_model_name
    ),
    embed_batch_size=1)

**Comment by zioproto** [comment]
I confirm adding `embed_batch_size=1` works. Tested with LangChain version 0.0.160

```
embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="text-embedding-ada-002",
        openai_api_key="secret",
        openai_api_base="https://<redacted>.openai.azure.com/",
        openai_api_type="azure",
        openai_api_version="2023-03-15-preview",
    ),
    embed_batch_size=1
)

```

**Comment by RobRoyce** [comment]
Use `chunk_size=1`:

```
embeddings = OpenAIEmbeddings(
    model='text-embedding-ada-002',
    deployment='text-embedding-ada-002',
    openai_api_base=BASE_URL,
    openai_api_type='azure',
    openai_api_key=API_KEY,
    chunk_size=1
)
```

**Comment by zhangminxiaozhang** [comment]
embeddings = OpenAIEmbeddings(
    chunk_size=1
)
it solve my problem

**Comment by gclem** [comment]
Just adding here,
With LangchainJS, parameter to overwrite is BatchSize

```
    const embeddings = new OpenAIEmbeddings({
      batchSize : 16
    }); 
```

**Comment by KeyanatGiggso** [comment]
> Latest. Heres an example from the test code https://github.com/jerryjliu/llama_index/blob/73c575438dbabc29ddbdd14ec42a2d103512f5fe/tests/embeddings/test_base.py#L45

This worked, Thanks for the workaround
