### ISSUE TITLE
error the index = GPTSimpleVectorIndex(documents)

### ISSUE THREAD

**Issue by ainteligencia** [jerryjliu/llama_index#954]
in the following code is pulling the
from llama_index import GPTSimpleVectorIndex
index = GPTSimpleVectorIndex(documents)

Error
ValueError: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.

**Comment by jerryjliu** [comment]
with 0.5.0, do `GPTSimpleVectorIndex.from_documents(documents)` 

Check out our discord for more questions!

**Comment by ainteligencia** [comment]
and this other error 

TypeError: __init__() got an unexpected keyword argument 'llm_predictor'

code implemented before

# Prepare su LLM
from llama_index import  GPTSimpleVectorIndex, PromptHelper,LLMPredictor
from langchain import OpenAI
# define LLM
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.1, model_name="text-davinci-002"))
# definir prompt helper
# definir tamaño máximo de entrada
max_input_size = 4096
# establecer el número de tokens de salida
num_output = 256
# Establecer el solapamiento máximo de trozos
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

custom_LLM_index = GPTSimpleVectorIndex(
    documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper
)
