### ISSUE TITLE
paul_graham_essay example returning "NONE"

### ISSUE THREAD

**Issue by unruledboy** [jerryjliu/llama_index#964]
After following the tutorial at https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html  ,I ran the following sample:

```
import os

os.environ["OPENAI_API_KEY"] = "MY-API-KEY-HERE"

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader("data").load_data()
index = GPTSimpleVectorIndex.from_documents(documents)

response = index.query("What did the author do growing up?")
print(response)

```

and the response is "NONE".

Logs:

> INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 0 tokens
> INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 8 tokens
> None
> 

If I tried to load from the index.json file:
```
import os

os.environ["OPENAI_API_KEY"] = "MY-API-KEY-HERE"

from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader

# documents = SimpleDirectoryReader("data").load_data()
# index = GPTSimpleVectorIndex.from_documents(documents)
index = GPTSimpleVectorIndex.load_from_disk(
    os.path.abspath("examples/paul_graham_essay/index.json")
)

response = index.query("What did the author do growing up?")
print(response)
```

It would give me this error:

> PS llama_index-main> & AppData/Local/Programs/Python/Python311/python.exe d:/Workspaces/AI/llama-index/llama_index-main/llama_index-main/examples/paul_graham_essay/test.py
> Traceback (most recent call last):
>   File "llama_index-main\examples\paul_graham_essay\test.py", line 9, in <module>
>     index = GPTSimpleVectorIndex.load_from_disk(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\base.py", line 353, in load_from_disk
>     return cls.load_from_string(file_contents, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\base.py", line 329, in load_from_string
> load_from_dict
>     return super().load_from_dict(result_dict, **config_dict, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\base.py", line 303, in load_from_dict
>     index_struct = load_index_struct_from_dict(result_dict[INDEX_STRUCT_KEY])
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\registry.py", line 90, in load_index_struct_from_dict
>     type = struct_dict[TYPE_KEY]
>            ~~~~~~~~~~~^^^^^^^^^^
> KeyError: '__type__'

Any idea?

Environment: Windows 11
Python: 3.11.2

**Comment by jerrykhh** [comment]
I also facing the problem of Key error:
```
KeyError: 'index_struct'
```

I downgrade the llama-index to 0.4.36 the problem is solved.

**Comment by unruledboy** [comment]
@jerrykhh  any idea why the response will return "None" instead of meaning values?

**Comment by jerrykhh** [comment]
I see the jerryjliu is released v0.5.3. Also, I tried run the tutorial in Google Colab. It can work.
I think you may check your version of llama_index and please update it to latest version
I feel there are some bugs in previous version.

<img width="1117" alt="Screenshot 2023-03-31 at 7 41 52 PM" src="https://user-images.githubusercontent.com/47948629/229111928-12c933e4-1700-42f5-9955-23ed6c96f37a.png">

**Comment by unruledboy** [comment]
thanks @jerrykhh  . the sample from https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html does not work, but the on in TestEssay.ipynb work.

**Comment by akshay08-repo** [comment]
![image](https://user-images.githubusercontent.com/69821921/230113285-22786cdc-efa8-45ee-855b-3d35aa47097d.png)

you need to update the caller fun. post ver5 there are breaking changes.
