### ISSUE TITLE
I can not find ServiceContext in llama-index and from_document method can‘t be found as well

### ISSUE THREAD

**Issue by sa1utyeggs** [jerryjliu/llama_index#966]
![image](https://user-images.githubusercontent.com/63895563/228467838-79e665c2-ee2c-4101-83ed-96af6eda1bc8.png)

is this two just been deleted ?

**Comment by luca-secchi** [comment]
I had the same problem. I fixed forcing the upgrade:
`pip install --upgrade --force-reinstall llama-index`

**Comment by sa1utyeggs** [comment]
thank you，I have solved this problem by updrade llama-index；
By the way, the version of llama-index in tsinhua mirror is much lowwer. So, I just upgrade from PyPi and it works

**Comment by Tavish77** [comment]
> thank you，I have solved this problem by updrade llama-index； By the way, the version of llama-index in tsinhua mirror is much lowwer. So, I just upgrade from PyPi and it works

I have the same problem, but update llama_ Index seems to be useless

**Comment by sa1utyeggs** [comment]
make sure your version of llama-index is 0.5.1.

**Comment by Tavish77** [comment]
> make sure your version of llama-index is 0.5.1.

Thank you ,my version is 0.4.3,my pip think it is the lastest version

**Comment by padhraigeaton** [comment]
llama_index/indices/service_context.py 
(using llama-index==0.8.21 )
