### ISSUE TITLE
how to get prompt when query

### ISSUE THREAD

**Issue by mingxin-yang** [jerryjliu/llama_index#967]
I want know what's the complete question that I send to openai, and the context I found in my json file. How to get it?

**Comment by neove** [comment]
add log
`
import logging
logging.getLogger().setLevel(logging.DEBUG)
`

**Comment by mingxin-yang** [comment]
I have added `logging`, but only the token used for each operation will be displayed, and I am running it in pycharm. The prompt information will not be displayed.

**Comment by jheyder213** [comment]
Check out the bug report: https://github.com/jerryjliu/llama_index/issues/720 

You need to either use the `force=true` flag in 
```python
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, force=True)
```

Or as the previous comment mentioned
```python
logging.getLogger().setLevel(logging.DEBUG)
```

**Comment by mingxin-yang** [comment]
Yeah, them all work to me , thank you!
