### ISSUE TITLE
 Filtering Documents by Keywords in "extra_info" Field in  Vector Index (QDrant specifically)

### ISSUE THREAD

**Issue by ssmssam** [jerryjliu/llama_index#969]
Hello,

I am currently using the "llama_index" library with the vector index (Qdrant specifically) and am interested in filtering documents based on keywords in the "extra_info" field. I was wondering if this is currently possible, and if not, if there are any plans to implement such a feature?

If not, could you provide guidance on how one might go about implementing this feature? I'm new to the library and would appreciate any advice on how to extend its functionality.

Thank you for your time and for creating such a useful library!

**Comment by Disiok** [comment]
We added filters to the vector store query interface, but haven't added to Qdrant yet (AFAIK). Would appreciate contribution on this! You could take a look at the Pinecone or Chroma implementation for reference.

**Comment by thedoor76** [comment]
FYI, I am able to use filters with Qdrant, e.g.: 

`from llama_index.vector_stores.types import MetadataFilters, ExactMatchFilter

...

query_engine = index.as_query_engine(filters=MetadataFilters(
    filters=[
        ExactMatchFilter(key="diUIN", value="AF/0033"),
        ExactMatchFilter(key="sector", value="Mining")
    ]
))`
