### ISSUE TITLE
index.query suddenly returning responses that are not in loaded index.json

### ISSUE THREAD

**Issue by kleek430** [jerryjliu/llama_index#972]
As of last week Thursday index.query would return an out of context answer if asked a question not in the loaded index . I checked today and now its returning answers to questions that are not in the index  .   I am using this code   :    `  index = GPTSimpleVectorIndex.load_from_disk("index.json")   `. and  ` response = index.query(question)`   One example there is no info on cake baking in the index but now I am getting cake making instructions

**Comment by sergiopiedra** [comment]
Actually I have the same problem, I have validated the prompts, in addition to similarity_top_k but nothing solves it or limits the data source to be only from index.json. For example I ask for activities to do in Costa Rica or capitals of countries, and nowhere in my index appears anything related to this.  

![image](https://user-images.githubusercontent.com/43553385/228654322-ddc05206-944c-47de-b78a-414c15307043.png)

**Comment by kleek430** [comment]
I was able to fix by stating a prompt with the index creation ,suggested by Logan M on disrupt channel :
from llama_index import GPTSimpleVectorIndex, Document, SimpleDirectoryReader,QuestionAnswerPrompt
QA_PROMPT_TMPL = (
"We have provided context information below. \n"
"---------------------\n"
"{context_str}"
"\n---------------------\n"
"Given this information, please answer the question: {query_str}\n"
)
QA_PROMPT = QuestionAnswerPrompt(QA_PROMPT_TMPL)
# Construct a simple vector index
index = GPTSimpleVectorIndex(documents=documents, text_qa_template=QA_PROMPT )
index.save_to_disk('index.json')

**Comment by jerryjliu** [comment]
hey @kleek430, out of curiosity were you using chatgpt vs. davinci? empirically i've noticed davinci hallucinates more and chatgpt is more prone to saying something like "this is out of context"

**Comment by kleek430** [comment]
@jerryjliu  I am just using whatever is the default model for GPTSimpleVectorIndex . index = GPTSimpleVectorIndex(documents=documents, text_qa_template=QA_PROMPT ) . As an update @sergiopiedra   the fix I mentioned above is not always working . I'm currently trying  adding  the the string t , "Do not give me any information about procedures and service features that are not mentioned in the PROVIDED CONTEXT."  found [here ](https://community.openai.com/t/how-to-prevent-chatgpt-from-answering-questions-that-are-outside-the-scope-of-the-provided-context-in-the-system-role-message/112027/3) to each query before sending it to the index.query() method . So far that seems to be working
