### ISSUE TITLE
Example-using-a-custom-llm-model throws 'llm_predictor' error

### ISSUE THREAD

**Issue by dhnanjay** [jerryjliu/llama_index#974]
I am trying to replicate this Notebook : [Example using a custom LLM Model](https://github.com/jerryjliu/llama_index/blob/046183303da4161ee027026becf25fb48b67a3d2/docs/how_to/custom_llms.md#example-using-a-custom-llm-model) and it throws the following error: TypeError: __init__() got an unexpected keyword argument 'llm_predictor'

Here is  my code:
```
import torch
from langchain.llms.base import LLM
from llama_index import SimpleDirectoryReader, LangchainEmbedding, GPTListIndex, PromptHelper, ServiceContext,GPTSimpleVectorIndex
from llama_index import LLMPredictor
from transformers import pipeline
from typing import Optional, List, Mapping, Any
# define prompt helper
# set maximum input size
max_input_size = 2048
# set number of output tokens
num_output = 256
# set maximum chunk overlap
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)

```
```
class CustomLLM(LLM):
    model_name = "facebook/opt-iml-max-1.3b" # "facebook/opt-iml-max-30b"
    pipeline = pipeline("text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)
        response = self.pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        return response[prompt_length:]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": self.model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"

# define our LLM
llm_predictor = LLMPredictor(llm=CustomLLM())
```

```
# Load the your data
documents = SimpleDirectoryReader('./data').load_data()
index = GPTListIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)
```
I get the error in the above chunk : 
_---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-049bc5782086> in <module>
      1 # Load the your data
      2 documents = SimpleDirectoryReader('./data').load_data()
----> 3 index = GPTListIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

~/.local/lib/python3.8/site-packages/llama_index/indices/list/base.py in __init__(self, nodes, index_struct, service_context, text_qa_template, **kwargs)
     52         """Initialize params."""
     53         self.text_qa_template = text_qa_template or DEFAULT_TEXT_QA_PROMPT
---> 54         super().__init__(
     55             nodes=nodes,
     56             index_struct=index_struct,

TypeError: __init__() got an unexpected keyword argument 'llm_predictor'_

![llm_predictor](https://user-images.githubusercontent.com/6330554/228664850-94be99b9-eacb-4888-9f37-81d8e0ffad4d.jpg)

**Comment by jerryjliu** [comment]
hi @dhnanjay since you're on a branch these docs are out of date. take a look at this for latest instructions (we made breaking changes with 0.5.0 https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html)
