### ISSUE TITLE
GPTSimpleVectorIndex Throwing Error

### ISSUE THREAD

**Issue by g-benton** [jerryjliu/llama_index#975]
I'm experience the same issue with GPTSimpleVectorIndex that appeared in [issue 617](https://github.com/jerryjliu/llama_index/issues/617), but was not resolved. I tried the same simple test with the Paul Graham essay using a LLM from huggingface. 

Below is a minimum working example, note that if I use a list index instead of the simple vector index everything runs fine.

```{python}
from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader, PromptHelper, LLMPredictor, ServiceContext
import torch
from langchain.llms.base import LLM
from transformers import pipeline
from typing import Optional, List, Mapping, Any

# define prompt helper
# set maximum input size
max_input_size = 512
# set number of output tokens
num_output = 512
# set maximum chunk overlap
max_chunk_overlap = 20
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)


class CustomLLM(LLM):
    model_name = "t5-small"
    pipeline = pipeline("text2text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        response = self.pipeline(prompt)[0]["generated_text"]

        # only return newly generated tokens
        return response

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": self.model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"

llm_predictor = LLMPredictor(llm=CustomLLM())

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)


documents = SimpleDirectoryReader('data').load_data()
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
```

**Comment by logan-markewich** [comment]
@g-benton the vector index still defaults to using openAI to generate embeddings during the index construction.

To you have access to openAI? If you want to use lo al hughingface embeddings, see this guide: 
https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

You can set the embedding model to be anything from huggingface

**Comment by javixeneize** [comment]
same here, with 0.5.6

**Comment by logan-markewich** [comment]
@javixeneize see my answer above 👍🏻

**Comment by javixeneize** [comment]
hi. I think the problem is the doc has been updated to llama_index, but not all the methods have been ported yet. if i use gpt_index instead, it works

**Comment by logan-markewich** [comment]
@javixeneize llama index has all the same methods, it's actually the same package.

`pip install --upgrade llama_index langchain` should get everything updated for you

**Comment by javixeneize** [comment]
Hi

No... Methods like ServiceContext are not in llamaindex

**Comment by logan-markewich** [comment]
@javixeneize I think you have some env issues, works fine for me 
![image](https://user-images.githubusercontent.com/22285038/229555189-29b487a6-5968-41ae-a1c5-1609df0b5575.png)

**Comment by AGRocky** [comment]
I'm getting below error when I try to ask the question in the query engine
TypeError: 'method' object is not iterable

**Comment by logan-markewich** [comment]
@AGRocky how did you create the query engine and query?
