### ISSUE TITLE
ImportError: cannot import name 'DOCSTORE_KEY' from 'llama_index.constants'

### ISSUE THREAD

**Issue by Eng-ZeyadTarek** [jerryjliu/llama_index#982]
I'm trying to import the `**ComposableGraph**` class using `llama_index.indices.composability import ComposableGraph`, but there's no constant called `DOCSTORE_KEY`, where's the problem?

**llama_index.__version__ is '0.4.36'**

**Comment by logan-markewich** [comment]
This is no longer an issue in recent versions of LlamaIndex

`from llama_index.indices.composability import ComposableGraph` is the correct import
