### ISSUE TITLE
How to use llama-index in alpaca-7b?

### ISSUE THREAD

**Issue by sa1utyeggs** [jerryjliu/llama_index#984]
Can GPTListIndex be used in alpaca-7b?
I tried to use GPTListIndex in my own built model, but the log shows 0 token:
![image](https://user-images.githubusercontent.com/63895563/228748641-afbd421b-0d8a-4abb-bd29-88f43d27e4fb.png)

I also trie with OpenAI( and I set my OpenAI KEY),it shows the same logs:
![image](https://user-images.githubusercontent.com/63895563/228748889-0d2f6e26-5d5c-4588-a9b9-4a09b68c780d.png)
when I query, it shows content;

pls tell me how to use llama-index in alpaca :)

**Comment by jerryjliu** [comment]
building the list index doesn't consume any tokens! which is why that shows up 

by the way, assuming this works, do you have an example notebook for showcasing llamaindex with alpaca? would love to feature this as a demo

**Comment by shreedhan** [comment]
@sa1utyeggs Do you have a complete example on how to do this? I see your example above but where does it get the model from? And how do you create the model using local Alpaca 7b model?

**Comment by sa1utyeggs** [comment]
yes,I use the "Facico/Chinese-Vicuna" project, And it use the huggingface's package: transformer.
Transformer can down load the model from hugginface.com.

I succeed to use the llama-7b-hf and alpaca-7b model with GPTListIndex. But it runs slowly.
So I tried to Use GPTFaissIndex, then it failed to genereate index with my local model;

Just now, I tried to use ChatGPT to generate the faiss-index.json, then load from disk.
Unfortunately, it throw out a Exception about some node_key is not exist(sry i don't have screen shot)

**Comment by sa1utyeggs** [comment]
finally, I trie to run it in mac silicon, and it works

**Comment by lucasalvarezlacasa** [comment]
It doesn't work to me. It says:
KeyError: 'llama'

When trying to download the files for the "decapoda-research/llama-7b-hf" model.

Any ideas?

**Comment by Datta0** [comment]
@sa1utyeggs can you help me understand how you got Vicuna to run with LLAMA Index?
You just wrote a CustomLLM with HF pipeline (which pipeline, I mean text-generation or text2text or any other?) with Vicuna as the model_name?

And which Index did you build? GPTSimpleVectorIndex?

Thanks.

**Comment by afbenevides** [comment]
Also interested in running vicuna with llama-index context. Has anyone see or created a how-to guide for that? @Datta0, @sa1utyeggs ?

Thanks,
