### ISSUE TITLE
question about index

### ISSUE THREAD

**Issue by mingxin-yang** [jerryjliu/llama_index#986]
The index mentioned above is GPTSimpleVectorIndex, because I divided it into two steps. ***The first step*** is to read the file to the json file, **and the second step** is to answer questions based on the json file, not using the same index. So my first step Is it possible not to add `ServiceContext`, `PromptHelper`, `LLMPredictor` in `GPTSimpleVectorIndex.from_documents`？ @jerryjliu

**Comment by Disiok** [comment]
Not super sure I understand the question.
