### ISSUE TITLE
load_from_disk resets llm_predictor

### ISSUE THREAD

**Issue by SajadAzami** [jerryjliu/llama_index#992]
Is it possible to modify `BaseGPTIndex.save_to_disk()` to also save `ServiceContext` or should it be saved/loaded separetly?

The issue is, once an index is saved, important configurations in ServiceContext will have to be reset upon loading the index. For example, users might use `gpt-3.5-turbo` as their LLMPredictor when they call `GPTSimpleVectorIndex.from_documents(docs, service_context=service_context)`, but then after saving and loading the index, they expect the same LLMPredictor to be set but this is not the case (it resets to default and more expensive davinci text model).

**Comment by logan-markewich** [comment]
The index and service context are separate

You can pass in the service context when loading from disk
`.load_from_disk("index.json", service_context=service_context)`

**Comment by SajadAzami** [comment]
Thanks. This is what I'm doing now but I thought it might be worth logging what service context is being used after loading the index. A lot of examples I'm seeing online overlook this and they would only notice it if they go through their OpenAI bill carefully.

**Comment by jerryjliu** [comment]
@SajadAzami it's a good point, just put out a PR to address a piece of this
