### ISSUE TITLE
Unable to Delete Document from Index after updating llama index

### ISSUE THREAD

**Issue by achempak-polymer** [jerryjliu/llama_index#995]
I'm unable to delete documents from an index in llama-index after updating to version 0.5.2. All I'm doing is 
1. Breaking a document into smaller documents, all with the same document ID (`doc_id`)
2. Calling `index.insert(d)` on each of these smaller documents
3. Saving the index to a string and then to my local file system
4. Loading the index from my file system
5. Calling `index.delete(doc_id)`

Before updating, this would delete every document with `doc_id` from the index. Now, it doesn't seem to do anything. The file size is slightly smaller after deleting, but a majority of the data is still there. I've attached before and after files for an example index.

[before_delete.txt](https://github.com/jerryjliu/llama_index/files/11117503/before_delete.txt)
[after_delete.txt](https://github.com/jerryjliu/llama_index/files/11117504/after_delete.txt)

**Comment by achempak-polymer** [comment]
part of this issue was fixed; however, information related to the deleted document still exists in the `docstore` object even after deleting

**Comment by prateekaffine** [comment]
Did you find any solution to delete a document from index?

**Comment by logan-markewich** [comment]
@achempak-polymer  This should be fixed, or at least much clearer, see this page for detailed guide/usage! Docs are not deleted from the docstore by default (since multiple indexes can be sharing the same docstore), but you can set a flag to force the delete

https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/document_management.html

**Comment by logan-markewich** [comment]
Latest link is here. Closing for now!
https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/document_management.html#deletion
